### ISSUE TITLE
Loosing DB-connection on long inactivity

### ISSUE THREAD

**Issue by sergejzr** [IQSS/dataverse#8959] opened 2022-09-07 14:09 UTC
**What steps does it take to reproduce the issue?**

We did not access the running dataverse for several weeks (due to illness and vacations). In the meantime the DB connection got lost and only a server restart helped.

* When does this issue occur?

on 4 or more weeks on inactivity

* Which page(s) does it occurs on?

Any page
![image](https://user-images.githubusercontent.com/12542792/188899061-a4c94a34-1e64-4f72-a161-e2dcee482b8b.png)

* What happens?
Database connection gets lost and the whole site crashes. Only a server restart fixed the issue

* To whom does it occur (all users, curators, superusers)?
anyone

* What did you expect to happen?

Dataverse could catch lost connection exception and try to reconnect (at least several times).

**Which version of Dataverse are you using?**

v. 5.10.1 build 907-b844672

**Any related open or closed issues to this bug report?**

Any database issues, however I could not find exactly that one.

**Screenshots:**

**Comment by pdurbin** [comment] 2022-09-15 18:46
It looks like we also saw "Internal Exception: org.postgresql.util.PSQLException: This connection has been closed" at #4416 but other than that, I'm not sure what's going on.

@sergejzr you don't happen to be running AWS RDS are you? Somewhat recently we added some monitoring suggestions: https://guides.dataverse.org/en/5.11.1/admin/monitoring.html#aws-rds

I guess I'm curious if you're doing any monitoring in particular for PostgreSQL and if you're seeing any spikes or patterns.

**Comment by poikilotherm** [comment] 2022-09-15 20:05
I have no idea why this happens (lots of options), but maybe merging https://github.com/IQSS/dataverse/pull/8915 and activation of connection validation ([https://docs.payara.fish/community/docs/Technical%20Documentation/Payara%20Server%20D[…]on%20And%20Management/JDBC%20Resource%20Management/JDBC.html](https://docs.payara.fish/community/docs/Technical%20Documentation/Payara%20Server%20Documentation/Server%20Configuration%20And%20Management/JDBC%20Resource%20Management/JDBC.html#full-list-of-properties)) might help?

**Comment by sergejzr** [comment] 2022-09-19 12:49
Hi Philipp,
thanks! No, we are still in our experimental phase and are not monitoring the processes yet (it is definitely planned). I am also sorry, I missed testing if Postgres was running at all.
Connection validation should surely solve the thing, thanks, Oliver! Maybe I find some spare time and install Dataverse on a VM and do not touch it for a month, just to see if the problem appears again.
Thanks again for your suggestions!
Sergej

**Comment by pdurbin** [comment] 2022-10-01 18:31
@sergejzr sounds good. I don't think we have a way to reproduce this issue. Are you ok with closing it? You'd be very welcome to open a fresh one in the future, of course!

**Closed** 2022-10-06 11:34 UTC
