### ISSUE TITLE
file upload: when uploading a combination of files that include tabular data, the "select and delete" option will not work although the "action" is available to attempt, until files ingest

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2876] opened 2016-01-15 21:30 UTC
It appears to be a "bug" because the option to select files and delete is still available, but when you complete the action, the page appears to "refresh" without deletion and leaves you in "edit" mode to select "save" for tabular data ingest

**Comment by mheppler** [comment] 2016-02-10 21:39
@sbarbosadataverse - I could not replicate this locally. Is there more information you could provide? Maybe the amount of files you upload at once, and how big the largest files?

**Comment by sbarbosadataverse** [comment] 2016-02-11 01:06
No more info to provide.  If you upload a zip fir example and files are
extracted, including tabular files,  the option to select filed and delete
remains "active" although ingest is in process.  The select and delete
should not be options until the ingest is complete.

**Comment by kcondon** [comment] 2016-04-14 16:46
Possibly related to #2862 since you cannot delete when you are adding/ creating.

**Comment by kcondon** [comment] 2016-04-14 16:49
Please retest to clarify the steps -is tabular file required, is it while ingesting (should not be possible) or is it just while uploading and editing that file list?

**Comment by pdurbin** [comment] 2017-06-25 18:19
@sbarbosadataverse are you still seeing this issue?

**Comment by mheppler** [comment] 2019-06-13 18:26
Tested a ZIP of various files that would be ingested, as well as a couple of images files.

1. Created dataset
2. Clicked Upload Files btn
3. Drag-n-drop'd a ZIP that uploaded 2 image files and 13 various files for ingest
4. Clicked Save Changes btn
5. Saw "Ingest in progress..." but Edit Files btn was disabled, so could not select the Delete action

![Screen Shot 2019-06-13 at 2 21 10 PM](https://user-images.githubusercontent.com/687227/59457809-276e1b80-8de7-11e9-9ecc-11f4ec1735e7.png)

@sbarbosadataverse please confirm that this is the correct workflow to test, and clarify with more detail if not.

**Comment by kcondon** [comment] 2019-06-17 17:14
Confirmed, closing

**Closed by kcondon** 2019-06-17 17:14 UTC
Labels: Feature: File Upload & Handling, Type: Bug, User Role: Depositor
