### ISSUE TITLE
Hyperlink ORCID

### ISSUE THREAD

**Issue by adam3smith** [IQSS/dataverse#4289] opened 2017-11-17 18:53 UTC
Very simple feature request/enhancement:
When I select Author Identifier --> ORCID and then include an ORCID like 0000-0001-8249-7388, Dataverse should hyperlink the ORCID (by prepending https://orcid.org/), i.e. the part in red here:
![image](https://user-images.githubusercontent.com/128986/32963656-b133c30e-cb9e-11e7-917c-8ce481284a65.png)

I suppose there might be a UX question in that being redirected to an external site (i.e. an ORCID profile) is unexpected? But external DOIs and URLs do this, so I think that should be fine.

**Comment by scolapasta** [comment] 2017-11-17 19:05
Sounds like a great idea. It will be more difficult technically than it should seem, based on the dynamic metadata, but it would be nice to find a generic solution for other identifiers / metadatafields as well.

We recently added something like this for when we know the field is *always* from a certain location, but this is trickier in that it would depend on the Controlled Vocabulary Value. So we'd likely have to add another column there and also finally tackle https://github.com/IQSS/dataverse/issues/1625

**Comment by adam3smith** [comment] 2017-11-17 19:07
ah, I understand the difficulty, thanks for clarifying. Obviously this isn't essential, but it's definitely a nice-to-have.

**Comment by djbrooke** [comment] 2018-04-04 20:24
We discussed this in Backlog Grooming last week, and as @scolapasta mentions, the best path here is to address #1625. I'm going to close this so we're no longer tracking it as a open ticket and we'll plan to fix the root cause in the other issue.

**Closed by djbrooke** 2018-04-04 20:24 UTC
Labels: Status: Backlog
