### ISSUE TITLE
Harvesting - Data Citation Values Missing

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#3290] opened 2016-08-17 18:44 UTC
When investigating how the citation is handled for harvested datasets, I noticed that our two latest and greatest harvesting test servers are not able to display the full, original citation after the dataset is harvested. Specifically, the distributor and version values are missing.

To add to the mystery, you can see that the value is actually harvested, and can be found when searching for the expected value in the Distributor field on the Advanced Search page.

Original Citation:
<img width="859" alt="screen shot 2016-08-17 at 2 40 56 pm" src="https://cloud.githubusercontent.com/assets/687227/17748772/f46e1b52-6488-11e6-99d2-b88f270faabe.png">

Harvested Citation:
<img width="858" alt="screen shot 2016-08-17 at 2 40 41 pm" src="https://cloud.githubusercontent.com/assets/687227/17748787/01c56fb2-6489-11e6-8f81-ae2c70f97465.png">

**Comment by landreev** [comment] 2016-08-17 19:43
OK, I couldn't stop myself from going digging in there... Yes, the value was exported, harvested and imported properly... and even indexed properly - but only as an individual field, and not as part of the citation (we index the citation as a complete string).
It was literally 1 line in DatasetVersion.java: 
for (DatasetField dsf : this.getFlatDatasetFields()) {
instead of
for (DatasetField dsf : this.getDatasetFields()) {

![screen shot 2016-08-17 at 3 30 51 pm](https://cloud.githubusercontent.com/assets/737558/17750378/2408e85e-6490-11e6-8d73-175e8c324007.png)

I checked in the fix. Please test/verify; but I'd say it looks safe enough to go into 4.5... 
(version numbers are not included into citations for harvested datasets by design - see Gustavo's DataCitation.java; I don't know why that " [distributor]" is being added to the distributor name for harvested, but not for local datasets either. I imagine it was all discussed and designed at some point)

**Comment by mheppler** [comment] 2016-08-17 20:57
I am trying to find reference to the use of bracketed labels in the citation, but I am struggling to find good source. There are a few old tickets that reference that once had a "[Publisher]" label in the early dev stages of 4.0, but that was since removed -- I believe at the suggestion of Gary.

@sekmiller might be of some help in figuring out if "[Distributor]" should also be removed. I believe that it should be removed, based upon the fact that a citation for a harvested dataset was most likely never properly demoed in those early dev stages.

**Comment by kcondon** [comment] 2016-08-19 14:24
Just tested and the [distributor] label still appears. This was in QA but not assigned to me. Was it ready for testing?

**Comment by sekmiller** [comment] 2016-08-19 15:45
Checked in the removal of [distributor] label to harvest branch...

**Comment by kcondon** [comment] 2016-08-19 16:57
Works for DDI, json is now putting the wrong value in place: putting the actual distributor field there, should be getting it from the json exported publisher field:

"publisher":"Root* Dataverse"

I think.

**Comment by djbrooke** [comment] 2016-08-19 19:46
This is related to a discussion in Google Groups (https://groups.google.com/forum/#!topic/dataverse-community/xnB2lComOrs) and some history about why this is set up this way is in #2146. 

I'd like to revisit this with @mcrosas, but this is not something that should hold up the release.

**Comment by cmbz** [comment] 2024-08-20 15:25
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Closed by cmbz** 2024-08-20 15:25 UTC
Labels: Type: Bug, Feature: Harvesting
