### ISSUE TITLE
Enable auto-sync of Dataverse forks on GitHub

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#6053] opened 2019-07-25 08:15 UTC
Being a contributor regularly, I would like to have my Dataverse fork `master` and `develop` branches in sync with upstream.

This can be done by yourself with proper `git remotes` and merging. Or you can automate it with a tool, so this gets easier and you don't forget it.

One option for this tool is [wei/pull](https://github.com/wei/pull), using Github Apps.
As it is necessary to sync both `master` and `develop`, I propose adding a small config file to upstream, so people can "just install pull" after forking.

PR is in #6054

To see what happens after enabling the app, you can take a look at https://github.com/poikilotherm/dataverse/pull/1, which was automatically created by wei/pull after installing it. As `develop` is the default branch for both repos, it is automatically synced just by installing the app.

**Comment by pdurbin** [comment] 2019-07-25 11:37
> This can be done by yourself with proper `git remotes` and merging.

@poikilotherm are you interested in documenting this manual process? Fancy tools are great but I don't want us to rely on them too heavily.

Currently it says "Always create your feature branch from the latest code in develop, pulling the latest code if necessary" at http://guides.dataverse.org/en/4.15.1/developers/version-control.html#create-a-new-branch-off-the-develop-branch

This "just works" for me but is that only because I clone from the IQSS repo?

At a high level, I think some or all Dataverse developers should consider working from forks rather than "upstream" (IQSS) so that we feel the pain a bit. Otherwise, we don't understand in a visceral way what the problem is.

**Comment by poikilotherm** [comment] 2019-07-25 12:13
Thx for reviewing @pdurbin.

Syncing your repo at Github will not automagically sync the develop branch on your dev machine, due to the nature of Git.

Some people (like me) tend to `git remote add upstream https://github.com/IQSS/dataverse.git && git pull upstream develop:develop` or similar to sync to local or directly merge upstream `develop` into the feature branch. Others might prefer to sync GitHub automatically and pull from their fork. Anyway they will need at some point to merge it. This merge has been described in the docs already.

One might argue that using `git pull` from your fork with sync on GitHub will avoid the default of pulling all feature branches, tags etc from the upstream repo (which makes it tedious and crowded on your dev machine).

Would you be happier when adding sth. like 
```
git remote add upstream https://github.com/IQSS/dataverse.git
git pull upstream develop
```
to merge latest `develop` into a feature branch?

With auto-sync this can be shortened to
```
git pull origin develop
```
although the remote has only to be added once and forever per local repo.

One could argue that the whole sync thing is mostly cosmetic and boils down to "follow good practice"...

**Comment by scolapasta** [comment] 2019-08-21 17:40
@poikilotherm thanks for the issue and the PR. It seems as if anyone who wants to use this tool (or other similar tool) is not blocked from doing so. This PR is just some documentation on how to use this particular tool and a sample pull.yml file.

We checked with the community and it didn't seem like there was a strong need for this (in fact, many contributors seemed to prefer to manually deal with these merges), so for now we're going to close this. We can always revisit in the future if the community feels differently.

**Closed by scolapasta** 2019-08-21 17:40 UTC
