### ISSUE TITLE
Publish Dataset to Datacite : Title is not updated (4.9.1)

### ISSUE THREAD

**Issue by Thanh-Thanh** [IQSS/dataverse#5346] opened 2018-11-27 14:31 UTC
Hello all,

We are using dataverse 4.9.1, with the configuration to Datacite.
We've just found out that if we modify the title of the dataset (among other metadata), the published version in datacite has always the old title. Other metadata are, however, well updated.

Another remark: we are moving to dataverse 4.9.2, in test phase, and saw that the bug is still there. 
In addition, when we publish a dataset with 4.9.2, we have 2 updated versions in datacite.

Can you confirm the bugs and make the correction please?

Thanks in advance,

Thanh Thanh

**Comment by djbrooke** [comment] 2018-11-27 15:44
Hi - I'm going to close this as a duplicate of #4837, which we'll plan to estimate soon. I'll leave this description as a comment there. Please reopen this if you feel this is incorrect!

**Closed by djbrooke** 2018-11-27 15:44 UTC
