### ISSUE TITLE
"Unknown File Format:" before "publishing" file format is identified. After publishing, file format becomes "unknown"

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2784] opened 2015-11-30 19:44 UTC
<img width="1348" alt="screen shot 2015-11-30 at 2 41 58 pm" src="https://cloud.githubusercontent.com/assets/8322346/11482441/c6aaf9e6-9770-11e5-960f-2111c799e48b.png">

This "unknown file format" has been found on most if not all of the "corrupt" files issues we have seen latelty. The user tried to download the file and they get html code instead.

**Comment by landreev** [comment] 2015-11-30 20:30
@sbarbosadataverse  this has been fixed in 4.2.2. There was a separate ticket for it, #2735 - you saw it.
I'll close this one as a duplicate.

(this "unknown" instead of the original format is NOT related to the fact that the user could not download the file; it's an entirely different, less serious issue. Just a missing label).

**Comment by landreev** [comment] 2015-11-30 20:30
Closing the issue as a duplicate of #2735.

**Closed by landreev** 2015-11-30 20:30 UTC
Labels: Priority: Critical, Type: Bug
