### ISSUE TITLE
Download Buttons - consolidate render logic

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#7006] opened 2020-06-22 19:11 UTC
file-download-button-fragment.xhtml is where all of the code for rendering the download buttons on the Dataset Page (for each fileMetadata displayed in the files table) and the File landing page. The rendering is dependent on file type (with special handling for tabular files - a separate link for each format a user may download a tabular file), package files, etc. There is also separate handling for displaying buttons dependent on whether a popup for Terms of Use/Guestbook is required. There are also separate buttons on the file landing page for exporting file Citation info in various formats (bibTex, RIS, etc.)

The goal here would be to consolidate as much as possible especially with an eye toward bringing the File Page and Dataset Page rendering logic back together.

**Comment by TaniaSchlatter** [comment] 2020-07-06 14:41
Is this the right home for these points from dataset and file page [design QA](https://docs.google.com/presentation/d/1sCgPCTkTuRnWSEWPDd-JEbxomoWydn2tTjevt6xdfUw/edit#slide=id.g87b57c935a_0_0)? 

<img width="609" alt="Screen Shot 2020-07-06 at 10 40 02 AM" src="https://user-images.githubusercontent.com/15386424/86605833-3507bd80-bf75-11ea-935b-bd58d2e3e382.png">

**Comment by mheppler** [comment] 2020-08-06 14:09
I believe this issue is a duplicate of an older issue, **Download Permissions: Remove business logic from Application fragments. #2698**. We should discuss the scope for this to make sure we cover all outstanding technical debt, and outline it here.

**Comment by djbrooke** [comment] 2020-08-20 15:13
@mheppler @scolapasta we discussed closing this in sprint planning as this is one of the steps in #7081 . I'll close this, and I'll close the suggested duplicate (#2698) as well. Feel free to reopen if this is incorrect.

**Closed by djbrooke** 2020-08-20 15:13 UTC
Labels: Feature: File Upload & Handling, Feature: Permissions
