### ISSUE TITLE
Notification was deleted, but remains visible; delete again -> HTTP 500

### ISSUE THREAD

**Issue by bencomp** [IQSS/dataverse#804] opened 2014-08-05 09:22 UTC
I just created an account on the [demo instance of Dataverse 4]. All goes well, and upon return to the homepage, I see I have a notification.
After reading the notification ("Welcome" etc.), I click the cross on the right to delete it. I may have clicked right next to the cross instead of exactly on it. It looks like something is happening for a moment (AJAX request sent or something), but the notification does not disappear.

When I click again, this time right on the cross, I get an EJBException message in an HTTP 500 report.

    type Exception report
    messageInternal Server Error
    descriptionThe server encountered an internal error that prevented it from fulfilling this request.
    exception
    javax.servlet.ServletException: javax.ejb.EJBException
    root cause
    javax.faces.el.EvaluationException: javax.ejb.EJBException
    root cause
    javax.ejb.EJBException
    root cause
    java.lang.IllegalArgumentException: Object: null is not a known entity type.

(There's a stacktrace in the server.log, the report says.)

Could it be that the notification was deleted (that's my gut instinct) but the interface not updated?

**Comment by scolapasta** [comment] 2015-01-08 21:28
I was not able to reproduce - however I did notice that the link was an h:commandLink so maybe it used to be a p:commandLink that had no update?

Anyway, I changed it to p:commandLink so that it just does a partial submit and added an update attribute and seems to work as expected.

**Comment by esotiri** [comment] 2015-01-12 21:52
can't reproduce it either, closing for now and keep an eye on it.

**Closed by esotiri** 2015-01-12 21:52 UTC
Labels: Priority: Medium, Status: QA, Type: Bug
