### ISSUE TITLE
"Request Access" not working on single files

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#3595] opened 2017-01-25 02:36 UTC
The request access does not work on single files in a dataset. To reproduce:

- Log in to demo.dataverse.org (not with the superadmin account)
- Go to https://demo.dataverse.org/dataset.xhtml?persistentId=doi%3A10.5072%2FFK2%2FRVPDHV
- Click "Request Access" on the Screen Shot file
- The spinner appears briefly, but the button does not change and no notification is generated 

To see a case where it does work:

- Log in to demo.dataverse.org (not with the superadmin account)
- Go to https://demo.dataverse.org/dataset.xhtml?persistentId=doi%3A10.5072%2FFK2%2FXYJAWB (note that there is now a second button for request access that works for multiple files selected)
- Select the checkbox for the restricted file
- Click the "Request Access" button above the table
- The button changes and a notification is generated

**Comment by djbrooke** [comment] 2017-01-25 22:11
We identified only one potential task in the sprint planning meeting today:

- Investigate why this is working on develop by not on Prod. Is it a data or configuration issue?

**Comment by scolapasta** [comment] 2017-01-25 22:45
So, I tested the current dev branch (build 63-531cd75) on both dvn-build and dvn-vm5 (which has production like data). The functionality worked on dvn-build, but not on dvn-vm5. So that seems to imply that the issue is somehow related to the data? (whether this is something that needs to be cleaned up / fixed in the data, or whether the code needs to be more robust to handle the type of data on dvn-5 / production remains to be determined).

**Comment by scolapasta** [comment] 2017-01-25 22:55
Sample datasets (these may not exist any more if data is wiped from environments):

dvn-build: https://dvn-build.hmdc.harvard.edu/dataset.xhtml?persistentId=doi%3A10.5072%2FFK2%2FFRXAG9
dvn-vm5: http://dvn-vm5.hmdc.harvard.edu:8080/dataset.xhtml?persistentId=doi:10.5072/FK2/5JFFD3

**Comment by pdurbin** [comment] 2017-01-26 14:05
I don't think this is just a data thing. On develop as of 03ac5b8 (newer than 531cd75), I'm seeing this:

`[2017-01-25T16:12:22.840-0500] [glassfish 4.1] [WARNING] [] [javax.enterprise.resource.webcontainer.jsf.lifecycle] [tid: _ThreadID=134 _ThreadName=http-listener-1(2)] [timeMillis: 1485378742840] [levelValue: 900] [[
  /file-download-button-fragment.xhtml @250,113 actionListener="#{fileDownloadService.requestAccess(fileMetadata.dataFile)}": java.lang.IllegalArgumentException: Cannot convert [DataFile id:13 name:null] of type class edu.harvard.iq.dataverse.DataFile to class java.lang.Long
javax.el.ELException: /file-download-button-fragment.xhtml @250,113 actionListener="#{fileDownloadService.requestAccess(fileMetadata.dataFile)}": java.lang.IllegalArgumentException: Cannot convert [DataFile id:13 name:null] of type class edu.harvard.iq.dataverse.DataFile to class java.lang.Long`

**Comment by pdurbin** [comment] 2017-02-07 15:58
I just did some code review of pull request #3627 and it looks good. Moving to QA at https://waffle.io/IQSS/dataverse

**Closed** 2017-02-07 23:07 UTC
Labels: Status: QA
