### ISSUE TITLE
Guestbook Popup Remains up behind Two Ravens Popup

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#1742] opened 2015-03-20 23:14 UTC
If the user selects Data Subset and successfully completes the Guestbook questions the Two Ravens Popup will display but the guestbook popup remains under the Two Ravens Popup.  Once you close Two Ravens you have to also manually close the guestbook.

**Comment by mheppler** [comment] 2016-02-10 16:32
@sekmiller - I tried looking into this and I could not reproduce it locally with my post-4.2.3 branch off develop and on dvn-build (also post-4.2.4). Can you give it a try again? If you still see it, please add details to the issues. If you don't see it, close it!

**Comment by sekmiller** [comment] 2016-02-10 18:20
This is no longer happening. Perhaps a side-effect of PF upgrade.

Closing

**Closed** 2016-02-10 18:21 UTC
Labels: Component: Account & User Info, Component: TwoRavens, Component: UX & UI, Priority: High, Status: Cannot Reproduce, Type: Bug
