### ISSUE TITLE
"Restricted" Files page, giving option to download "Selected files" followed by glassfish error

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#1845] opened 2015-04-02 15:16 UTC
![ci-69-2byv_kkpltdxm-t7rthxeuavlppx9ykr_lzly](https://cloud.githubusercontent.com/assets/8322346/6966782/7e60a16e-d929-11e4-8297-74511e32ee2f.png)

![re69jkyigox-kig0ylpsmqyblhnprim0kvuavaafrwm](https://cloud.githubusercontent.com/assets/8322346/6966814/ab65957a-d929-11e4-82a0-cad3db2f37a4.png)

**Comment by scolapasta** [comment] 2015-04-14 03:49
Duplicate of #1950

**Closed** 2016-01-12 19:05 UTC
Labels: Component: UX & Upgrade, Priority: Critical, Status: QA, Type: Bug
