### ISSUE TITLE
Can't change from published version to "draft" version in 4.0 production

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2390] opened 2015-07-22 16:21 UTC
I added new files, saved "successfully" but page resolved to a "published" version upon save. I go into versions and select "draft" and page remains on "published" version.

The link says draft: https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl%3A1902.1/16786&version=DRAFT

but version says "V3 published."

I refreshed, left the dataset and came back to the page and still won't work.

**Comment by scolapasta** [comment] 2015-09-18 21:09
I was not able to reproduce. (the current production dataset actually no longer has a draft)

**Comment by kcondon** [comment] 2015-09-22 21:37
Did not see this behavior in testing. Closing but will reopen if see it again.

**Closed by kcondon** 2015-09-22 21:37 UTC
Labels: Priority: Critical, Status: QA
