### ISSUE TITLE
File Download w/ Rsync UI/Workflow changes

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#3998] opened 2017-07-12 19:53 UTC
Download compliment to #3348 .

Backend dependency on #3561

**Comment by mheppler** [comment] 2017-07-12 19:57
**UI IMPACT**

As defined in the following [mockup document](https://docs.google.com/document/d/1nzkuv9BW4A2xEbmGTQNqrwrcxRpGvwEgm9xHoPDW4uc/edit).

**Dataset (file table)**
- [ ] Display "Local Access" path, "Download Access" rsync commands for various locations (with location name country in parentheses), "Verify Data" command

**File**
- [ ] New "Data Access" tab, displayed first, with help msg and labels/values to display "Local Access" path, "Download Access" rsync commands for various locations (with location name country in parentheses), "Verify Data" command

**Comment by pameyer** [comment] 2017-07-26 15:51
From another round of testing:
- hide "guestbook" block under terms tab; since "package files" and guestbooks are not intended to work together.

**Comment by dlmurphy** [comment] 2017-08-01 21:08
Wrote some new messaging for the rsync download pages, would love to get @pameyer's verification that everything is accurate.

## Data Access tab at the bottom of the file page:
![dataaccess](https://user-images.githubusercontent.com/22962740/28845729-f9050fe8-76d6-11e7-9f17-4e1d2839768f.PNG)
There will be gray help text at the top, and tooltips on each of the three blue headers.

**Gray instructions at top:** "This data can be accessed through your computer's Terminal using the commands below. For more information, see our User Guide." ("User Guide" links to a guide page with more info)

**Local Access tooltip:** "If this data is locally available, this is its file path."

**Download Access tooltip:** "Download this data by running this command from your preferred mirror."

**Verify Data tooltip:** "This command runs a checksum to verify the integrity of the data you've downloaded."

--------------

## File table at the bottom of the dataset page:
![filetable](https://user-images.githubusercontent.com/22962740/28846945-5e7cc042-76db-11e7-85e7-bc35e2c5f1f2.PNG)
This page will use the exact same help text as the other page. As discussed with @mheppler and @TaniaSchlatter, the gray general instructions should go on the right side of the file table, above "Local Access". The three headers will have the same tooltips as the headers on the file page.

## Text styling
All red-on-pink text should be changed to highlighted black text, as in this earlier mockup: 
![font2](https://user-images.githubusercontent.com/22962740/28847041-c98c925e-76db-11e7-80ea-7cfa50ead6bc.PNG)

**Comment by pameyer** [comment] 2017-08-01 21:21
@dlmurphy looks good to me

**Comment by pameyer** [comment] 2017-08-28 21:24
One update - these UI changes should be conditional on the downloadMethods setting that was previously added (for this purpose).

**Comment by landreev** [comment] 2017-08-29 16:38
It doesn't say so in the checklist explicitly, but, there is no "Download" button on the page for a package file, correct? (just to confirm). I.e., that "Data Access" text on the dataset page, in the mockup above, replaces the current Download button - correct? 

If so, the checklist really should say "render logic to hide download count AND download button"...

**Comment by landreev** [comment] 2017-08-29 16:43
It sounds so far like this issue is mostly about changing the rendering of the dataset and other pages for "package" files. 
So then, in order to work on it, you just need a file with the "package" mime type. One way of creating such a file - aside from actually running a successful DCM upload - would be to pick a dataset with a single file; find the file in the DataFile Postgres table; and change the ContentType field to application/vnd.dataverse.file-package.

**Comment by pameyer** [comment] 2017-08-29 17:28
@landreev - you are correct; there shouldn't be a "Download" button

**Comment by djbrooke** [comment] 2017-08-31 20:22
Note from sprint planning meeting:

- We closed out #3249. Does this need to be handled in this issue? If so, @pameyer can you please update the checklist before we too many items done?

**Comment by pameyer** [comment] 2017-08-31 20:49
@djbrooke "Data Access" checklist items and mock-ups cover #3249; so I don't think there's anything to update from it into this one.

**Comment by rbhatta99** [comment] 2017-09-01 15:00
I have a few questions:
1. In the checklist, for the dataverse page and dataset page, the checklist consists of hiding the metric block for dataverses and dataset. Will the metric block be hidden if rsync is enabled? 

2.I saw the renders @dlmurphy made. The download links which are provided for various providers, would it make sense to have a dropdown with the provider names, and when a particular provider is chosen, we can provide that specific link? This is more of a suggestion than a question.  My argument is, that if(and this is a questionable if) the list of providers increase i the future, the dataaccess block, or the files tab would look very large accomodating all the providers.

**Comment by pameyer** [comment] 2017-09-01 15:11
@rbhatta99 

1. right; the information going into the metrics block comes from the dataverse application, and downloads not going through the application (aka - all rsync downloads) aren't counted.

2. potentially; probably makes sense to keep this in mind when thinking about generalizing dataset locality

**Comment by mheppler** [comment] 2017-09-08 19:09
Merged branch '3348-RSync-FileUpload-Workflow' into 3998-rsync-download 3b7051292843318fbd0d4462b4042f9566f31e65

**Comment by dlmurphy** [comment] 2017-09-12 17:06
Just added commit 8ddef8ef4a934b83f72b17015968877e7388707e (but forgot to link it to this issue). Documentation should be all set for this issue now!

**Comment by pameyer** [comment] 2017-09-14 19:07
(filtered) notes from another run-through.

- [ ] "submit for review" button is visually active when a dataset is locked for DCM upload
- [ ] possible escaping typo in email notifications for DCM success: `Dataset <a href="https://localhost/dataset.xhtml?persistentId=doi:10.5072/FK2/BQIIEF" title="$title"&>$title</a> has been successfully uploaded and verified.`
- [ ] "upload files" button visually active (but correctly non-functional) when a dataset is locked for review
- [ ] "dataset has been published" email goes out before a workflow has finished; move notification to “post-publish” from “pre-publish”?
- [ ] tooltip for download access needs rewording (suggests that the command is executed on the mirror vs downloading from it)
- [ ] "reason for return" lost when a curator sends a dataset back to the depositor via API (did not check UI, but @kcondon also found this).
- [ ] data access tab info might make users think that they can download/access unpublished data.

Which users get sent notifications for events appears inconsistent; this needs further investigation to determine if these are bugs, user error, or intended behavior.
- Dataset creator is notified about dataset creation through UI (not API)
- DCM success notifies dataset creator, other users with the same permission level (dsContributor) on the same dataverse, curator (2x); same behavior for DCM failure.
- "submit for review" notifies goes to curator only
- "return from review" notification to depositor (2x), and other users with same permission level on the same dataverse.
- "dataset has been published" email goes to depositor (2x), other users with same permission level on the same dataverse; also sends a "you have been assigned a role" notification to the depositor.

Good stuff:
- unanticipated case (major version of dataset published, update metadata to add PDB ID, publication DOI, etc not available at original publication time; submit for review; publish minor version) works as expected (assuming the RSAL can handle it, which won't be a problem).
- run upload script -> generate intentional corruption -> DCM failure -> depositor re-runs script -> DCM success pathway keeps working
- API usage still works

**Comment by matthew-a-dunlap** [comment] 2017-09-15 21:14
As part of the above commit, I slightly reworded the email strings. We can support html in our emails, but "just turning it on" breaks the return formatting in our old emails, so it seems better to fix this later.

**Comment by kcondon** [comment] 2017-09-15 21:40
Authoritative List of Open Issues - Please add to and update this list as needed.

- [ ] "submit for review" button is visually active when a dataset is locked for DCM upload
- [ ] possible escaping typo in email notifications for DCM success: `Dataset <a href="https://localhost/dataset.xhtml?persistentId=doi:10.5072/FK2/BQIIEF" title="$title"&>$title</a> has been successfully uploaded and verified.` (in progress by @matthew-a-dunlap )
- [ ] "upload files" button visually active (but correctly non-functional) when a dataset is locked for review
- [ ] "dataset has been published" email goes out before a workflow has finished; move notification to “post-publish” from “pre-publish”?
- [x] tooltip for download access needs rewording (suggests that the command is executed on the mirror vs downloading from it)
- [ ] "reason for return" lost when a curator sends a dataset back to the depositor via API (~did not check UI,~ but @kcondon also found this).
- [x] data access tab info might make users think that they can download/access unpublished data.
- [] Dataset creator is not notified about dataset creation if dataset created using API
- [] DCM success and failure notify all users with dsContributor on a dataset not only dataset creator (as designed/feature request)
- [] DCM success and failure notify curator 2x (retest, check for multiple roles)
- [] "submit for review" ideally should go to dataverse contact in addition to curator (feature request)
- [] "return from review" notification to depositor (2x) (retest, check for multiple roles)
- [] "return from review" notification sent to all users with dsContributor level on the dataset (as designed, feature request)
- [] "dataset has been published" email goes to depositor (2x) (retest, check for multiple roles)
- [] "dataset has been published" email sent to all users with dsContributor level on the same dataset (as designed, feature request)
- [] "dataset has been published" sends a "you have been assigned a role" notification to the dataset creator (should be sent on dataset creation/ when role is actually assigned.)

**Comment by pameyer** [comment] 2017-09-15 22:10
From discussions with @scolapasta and @kcondon , it's likely that some of the user notification items can be resolved by changing while roles are given to which users. I'll investigate and update these items (and create issues as necessary).

**Comment by landreev** [comment] 2017-09-20 21:37
I may have been able to fix that annoying "CSS blink after the page auto-refreshes" issue. (the "blink" itself was a Chrome-only issue; but the auto-refresh was also causing the files table to be resized incorrectly, and that was affecting all (or most) browsers. I've updated the checklist entry). 

It was all caused by the "update=@all" in the autorefresh block. It's just that for whatever reason I couldn't get it to properly refresh all the affected page parts without resorting to "all", back when I was working on it for tabular ingest. (so, this was not anything introduced in these rsync branches; we've had this issue forever). 

But, as I said, I think I got it to work, by updating just the affected components (the files table; the citation; the edit/publish/etc. buttons; and the message panel). But please re-test carefully. And see if I missed anything.

**Comment by landreev** [comment] 2017-09-21 15:58
![screen shot 2017-09-21 at 11 57 20 am](https://user-images.githubusercontent.com/737558/30705686-1f23faf8-9ec4-11e7-9280-8b86d16e9dd3.png)

**Comment by landreev** [comment] 2017-09-21 18:32
Wait, my commit with the message fix didn't seem to go through. Trying again.

**Comment by landreev** [comment] 2017-09-21 23:04
@kcondon I've added a similar success message to file delete on the single file page as well.

**Comment by kcondon** [comment] 2017-09-22 11:13
Awesome, thanks!

________________________________

**Closed** 2017-09-25 18:21 UTC
Labels: Collaboration: SBGrid
