### ISSUE TITLE
Featured Dataverses link broken when no logo

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1239] opened 2014-12-11 16:47 UTC
Set a featured dataverse of a dataverse which has no logo, clicking on image does not go to dataverse.

**Comment by sekmiller** [comment] 2015-01-30 22:36
I'm not able to get this to happen.  Please re-test and let me know a specific set of steps to recreate.

**Comment by kcondon** [comment] 2015-02-04 00:40
Could not reproduce @scolapasta cannot feature any dv below immediate child, plus if try to feature dv from a dv, not root level, featured dv feature never appears. Comment?

**Comment by scolapasta** [comment] 2015-02-04 19:37
Only featuring immediate children is not ideal, but we may have to live with for 4.0. But not being able to feature below root seems to me a bug.

**Comment by kcondon** [comment] 2015-02-05 23:34
Opened separate ticket: #1434 Closing

**Closed by kcondon** 2015-02-05 23:34 UTC
Labels: Status: QA, Type: Bug
