### ISSUE TITLE
Dataset Page: Download button for tabular file has dropdown but is cut off if near the bottom of the list of files

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3835] opened 2017-05-16 16:08 UTC
Originally reported by @rmo-cdsp at http://irclog.iq.harvard.edu/dataverse/2017-05-16#i_52784 for v. 4.6.1 build 69-1ed82ae

In the example below the last tabular file is "004_Nigeria-Cassava_Sociodemographic.tab" from https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/29604 . Notice how the dropdown is hidden:

## Dropdown cut off due to being at end of list of files

![screen shot 2017-05-16 at 12 02 33 pm](https://cloud.githubusercontent.com/assets/21006/26116058/d0858fea-3a2f-11e7-899f-80760c11895f.png)

What you **should** see is all the stuff in the drop down, such as for this file that's higher up in the file list:

## Dropdown not cut off

![screen shot 2017-05-16 at 12 00 24 pm](https://cloud.githubusercontent.com/assets/21006/26116128/0f7c30e6-3a30-11e7-8a53-1fa0cd3c461d.png)

**Comment by dlmurphy** [comment] 2017-05-16 16:43
Just checked, and this bug is appearing on my own setup as well. One can work around the bug by opening the dropdown and then scrolling down while the dropdown is open. This workaround is definitely not intended behavior, it's very difficult to pull off, and it's not at all telegraphed to the user. This bug puts a significant roadblock in the way of half of the file's download options, so it strikes me as pretty significant.

**Comment by pdurbin** [comment] 2017-07-07 14:16
@rbhatta99 took at look at the code this morning and has some ideas that we talked about. I asked him to get in touch with @mheppler .

**Comment by rbhatta99** [comment] 2017-07-07 20:57
@pdurbin i tried some things, but it broke the whole files table. So, @mheppler suggested we shelf it again for now.

**Comment by mheppler** [comment] 2017-07-07 21:07
@pdurbin @rbhatta99 I am just going to go ahead and close this issue, and add it to the long list of closed issues related to the scrollable datatable for files on the dataset pg (see #3404).

When this issue was first raised, I suggested it wasn't a bug because you can scroll the scrollable datatable and see the "cut off" menu options. Here is a screenshot of the [exact same dataset referenced above](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/29604) with the menu options in full display.

![screen shot 2017-07-07 at 5 05 37 pm](https://user-images.githubusercontent.com/687227/27976989-c04048ac-6336-11e7-82a3-f9267184c590.png)

**Closed by mheppler** 2017-07-07 21:07 UTC
Labels: Component: UX & UI, Persona: Curator, Status: Development, Type: Bug
