### ISSUE TITLE
Solr and init-container not working properly in OpenShift

### ISSUE THREAD

**Issue by thaorell** [IQSS/dataverse#4874] opened 2018-07-20 18:51 UTC
After issue #4764, there are some minor changes need to be made because right now there are two bugs:
1. Glassfish cannot talk to Solr
2. Every time the user scales up the Glassfish StatefulSet, the database is flushed. 

The main work will be made in install and postgres-setup scripts.

**Comment by thaorell** [comment] 2018-07-23 20:40
what I've attempted to get solr to work:
1. reindexing
2. getting solr documents json using `curl -s 'http://dataverse-solr-service:8983/solr/collection1/select?rows=1000000&wt=json&indent=true&q=*%3A*'`

**Comment by pdurbin** [comment] 2018-07-23 20:52
@thaorell is testing c560667 on https://github.com/thaorell/dataverse/tree/4874-bug-fix-glassfish-solr-container if someone wants to help reproduce the problem.

@thaorell do you think it would be easy to replicate this problem on the "develop" branch?

**Comment by thaorell** [comment] 2018-07-24 13:15
@pdurbin I think you can just run Dataverse on OpenShift/ MiniShift
1. log in
2. create and publish a dataset
3.  go to the main page, and you will see that the dataset is not there. 
4. `oc rsh` into postgres pod and select dataset, the dataset is present
5. query solr, the docs will show that the dataset is there

**Comment by pdurbin** [comment] 2018-07-24 13:32
@thaorell ok, I won't push to Docker Hub. It might be interesting for one of us to see if `oc new-app conf/openshift/openshift.json` on the "develop" branch yields a working Dataverse installation or not. Again if `openshift.json` and those old images are out of sync, it might all be broken anyway. If it's already broken, I feel like we should feel free to push new images. I recently added a note to all the images emphasizing  how experimental they are:

![screen shot 2018-07-20 at 3 59 41 pm](https://user-images.githubusercontent.com/21006/43141586-46dcc376-8f24-11e8-9632-1b6df769ffa0.png)

Do you or @tkmonson want to try the images as-is using the `openshift.json` on the "develop" branch and confirm if Dataverse is working or not?

**Comment by thaorell** [comment] 2018-07-24 13:34
It does work (I tested it yesterday), but it eliminates all the efforts on #4764 because it runs the old install script.

**Comment by pdurbin** [comment] 2018-07-24 14:57
I'm on commit 8587646 from pull request #4886 and I can't see the logs for the dataverse-glassfish-0 pod like I used to be able to a couple months ago. It says "Pod initializing" like this:

![screen shot 2018-07-24 at 10 54 42 am](https://user-images.githubusercontent.com/21006/43147091-341f1ade-8f30-11e8-97a6-f3fcc179152d.png)

When I click on "events" I see a dozen "Back-off restarting failed container" messages:

![screen shot 2018-07-24 at 10 54 50 am](https://user-images.githubusercontent.com/21006/43147090-341369be-8f30-11e8-92bf-3d74d656edf3.png)

**Comment by thaorell** [comment] 2018-07-24 14:59
The log is sometimes too slow, you can try `oc log dataverse-glassfish-0` on the command line.

**Comment by pdurbin** [comment] 2018-07-24 15:01
@thaorell thanks. This is what I'm getting though:

```
murphy:dataverse pdurbin$ oc log dataverse-glassfish-0
W0724 11:01:02.781387   80735 cmd.go:403] log is DEPRECATED and will be removed in a future version. Use logs instead.
Error from server (BadRequest): container "dataverse-plus-glassfish" in pod "dataverse-glassfish-0" is waiting to start: PodInitializing
murphy:dataverse pdurbin$ 
```

**Comment by pdurbin** [comment] 2018-07-25 21:05
@thaorell on my machine the "Back-off restarting failed container" issue is fixed as of a8f2257. Thanks!!!

Now we can focus on the Solr error. This is how it looks for me ("Required service Solr not running. Have you started the required services?"):

![screen shot 2018-07-25 at 5 04 39 pm](https://user-images.githubusercontent.com/21006/43227490-d8bd1c6a-902c-11e8-8427-fb875ff74b53.png)

Oh, I added a line to .gitignore in 9b89140 and I'm very tempted to reformat openshift.json with `jq` but maybe we can do that at the end once we get Solr working.

**Comment by thaorell** [comment] 2018-07-25 21:10
What does the log spit out for the solr pod?

**Comment by pdurbin** [comment] 2018-07-25 22:14
Can you please remind me what command to run?

**Comment by thaorell** [comment] 2018-07-26 13:58
First we need the pod name so run ‘oc get pods’, then we run ‘oc logs <solr_pod_name>’

**Comment by pdurbin** [comment] 2018-07-26 14:51
@thaorell thanks! Here you go:

```
murphy:dataverse pdurbin$ oc get pods
NAME                     READY     STATUS    RESTARTS   AGE
dataverse-glassfish-0    1/1       Running   1          17h
dataverse-postgresql-0   1/1       Running   0          17h
dataverse-solr-1-8flkb   1/1       Running   0          17h
murphy:dataverse pdurbin$ oc logs dataverse-solr-1-8flkb
solr-7.3.0/LUCENE_CHANGES.txt
solr-7.3.0/contrib/analysis-extras/lib/
solr-7.3.0/contrib/clustering/lib/
[snip]
solr-7.3.0/docs/images/solr.svg
solr-7.3.0/docs/index.html
whoami: cannot find name for user ID 1000070000
NOTE: Please install lsof as this script needs it to determine if Solr is listening on port 8983.

Started Solr server on port 8983 (pid=98). Happy searching!

whoami: cannot find name for user ID 1000070000

Created new core 'collection1'
murphy:dataverse pdurbin$ 
```

**Comment by thaorell** [comment] 2018-07-26 14:59
It looks normal. I wonder if anything is wrong in entrypoint.sh, I will take a look.

**Comment by thaorell** [comment] 2018-07-26 17:31
@pdurbin is it possible that you could upload your images to docker hub, let's say pdurbin/dataverse-glassfish and pdurbin/init-container so I can try them out?

**Comment by pdurbin** [comment] 2018-07-26 19:07
@thaorell sure, I'm still on 9b89140 and I just ran `./build.sh huborg pdurbin` to build and push images to https://hub.docker.com/u/pdurbin/

I'm confused about your status. Again, I'm seeing "Required service Solr not running". What are you seeing? Solr is running but Glassfish can't talk to it, as you originally reported? Something else? Is everything working for you?

**Comment by thaorell** [comment] 2018-07-27 14:08
I am using your image and everything is running fine. I wonder if it's your Solr pod that is creating troubles

**Comment by thaorell** [comment] 2018-07-27 14:08
recent:///b4d76cba9577ab433d78dd095b5b2603

**Comment by thaorell** [comment] 2018-07-27 14:09
![screenshot from 2018-07-27 10-01-43](https://user-images.githubusercontent.com/25762021/43325603-1e3c3c54-9185-11e8-9a46-35b093915551.png)

**Comment by pdurbin** [comment] 2018-07-27 14:20
@thaorell oh! That's fantastic news that everything is working for you! Let's get some eyes on pull request #4893 since you modified the installer. I just dragged this issue to code review at https://waffle.io/IQSS/dataverse

I'm home with a sick kid today so I'm on completely different hardware and software. Linux (Ubuntu) instead of Mac. It'll take me a while to get set up but I'll report back. If I can get similar results to yours with stuff working from the openshift perspective, I'm completely satisfied and can troubleshoot my Mac when I'm back from vacation on August 6th. We just need to make sure that whatever you did in the installer didn't break non-openshift installations. To test this, you could run `vagrant up` and see if it still works. You could also test the docker-aio environment and please note that yesterday @matthew-a-dunlap reported trouble that may have resulted from the recent work by you or @tkmonson: https://github.com/IQSS/dataverse/issues/4703#issuecomment-408247317

**Closed** 2018-07-31 19:27 UTC
