### ISSUE TITLE
Error Pgs - broken for pages "not found" (404) or unpublished dataset or other admin pgs without access permsissions (403)

### ISSUE THREAD

**Issue by adam3smith** [IQSS/dataverse#5589] opened 2019-02-28 21:24 UTC
Steps to reproduce:
1. Create a dataset with Account A and don't publish it; note down the URL (e.g. https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/FK2/OUHMYV&version=DRAFT )
2. Logout of Account A and log into Account B
3. Try to access the unpublished draft dataset using the URL

_Expected behavior:_ "You do not have access to this resource/dataset" or comparable message
_Actual behavior:_ While this does throw a 403, on screen there's an incomprehensible red error message instead of an explanation. Below the error thrown by Demo Dataverse and by QDR's install

Demo Dataverse (using above URL)
![image](https://user-images.githubusercontent.com/128986/53599186-972c0380-3b74-11e9-8fba-169d8eb3b419.png)

QDR
![image](https://user-images.githubusercontent.com/128986/53599170-8e3b3200-3b74-11e9-99e6-b81f99b2a6c7.png)

**Comment by pdurbin** [comment] 2019-02-28 21:33
Huh. Weird. I can definitely reproduce it in Firefox. Screenshots below (I highlighted line 121). For the record demo is running Dataverse 4.11.

Thanks for the bug report @adam3smith !

![screen shot 2019-02-28 at 4 27 35 pm](https://user-images.githubusercontent.com/21006/53599744-e9b9ef80-3b75-11e9-9599-122bcacef249.png)
![screen shot 2019-02-28 at 4 27 47 pm](https://user-images.githubusercontent.com/21006/53599745-e9b9ef80-3b75-11e9-9dfd-a55ed72deecd.png)

**Comment by pdurbin** [comment] 2019-03-06 23:17
I should point out that the error code is "403 Not Authorized" but the 404 page being similarly broken was just reported at #5609

**Comment by mheppler** [comment] 2019-03-06 23:34
I have a sneaking suspicion that the new [analytics changes in 4.11](https://github.com/IQSS/dataverse/issues/4660) might be related to the various error pgs being reported as no longer displaying properly.

When tested on my localhost environment -- with no analytics, the 403 and 404 error pages display properly in all their Bootstrappy glory.

<img width="990" alt="screen shot 2019-03-06 at 6 30 21 pm" src="https://user-images.githubusercontent.com/687227/53921475-87159780-403e-11e9-8f60-3c937a296968.png">

**Comment by mheppler** [comment] 2019-03-15 20:10
While reviewing #5627 I was able to confirm my analytics code suspicions.

```
<o:resourceInclude path="/CustomizationFilesServlet?customFileType=analytics" />
```

That line of code recently added to the top of the `<head>` section of the dataverse-template as part of #4660 is disabling our nice formatted 404 pgs from being displayed when you access a dataset pg that doesn't exist, and the 403 pg from being displayed when you access a dataset pg you don't have access to.

For some reason this bug does not have the same effect on the dataverse pg. But it effects every other page I looked at. The 404 and 403 pgs are displayed as expected on the dataverse pgs. Maybe this has something to do with PrettyFaces?

Experimenting further, if I move that line of analytics code down to the bottom of the `<head>` section in the dataverse-template, the ugly errors are still displayed... but for whatever reason the font changed... probably something to do with the PrimeFaces and Bootstrap CSS files loading but nothing else.

I tried to move the analytics code all the way down to the bottom of the `<body>` section of the dataverse template, where it once used to live, but I did not see the results I had hoped. Close though...

<img width="1144" alt="Screen Shot 2019-03-15 at 4 09 00 PM" src="https://user-images.githubusercontent.com/687227/54459341-ccbc1980-473c-11e9-898b-ae6d7af6f51f.png">

**Comment by landreev** [comment] 2019-03-25 15:13
Yes, it is related to Google Analytics. In a way that when it bombs in the browser, the error message "attribute must have value" or something along these lines really refers to this line in the analytics fragment that we load on every page: 
```
<script async src="https://www.googletagmanager.com/gtag/js?id=XXXXXXX"></script>
```

That "async" does indeed look weird there without a value... but then, again, we are loading it like that on every page - so not sure why it becomes an issue with *some* 404 and 403 pages... 

I'll try to figure it out.

**Comment by landreev** [comment] 2019-03-25 15:15
(that issue we had with dataverse URLs failing with the trailing slash added - it was failing the same way; throwing a 404, then the 404 page bombing in the browser, on account of this attribute in the GA fragment)

**Comment by landreev** [comment] 2019-03-25 17:05
To reiterate/confirm what @mheppler was saying earlier: this is only a problem in production and other hosts configured with our Google Analytics fragment. You can't reproduce this on your local build without GA enabled. 
A Google search find other people who have encountered this, and fixed it with changing that async to async="async". (but not async="true" - that doesn't work). 
It looks like Mike had already found this workaround while working on the other GA PR. 
I'm just going to document this (already fixed in production; the fragment lives outside the deployed application, in /var/www/dataverse)

**Closed** 2019-03-25 19:25 UTC
Labels: Status: QA
