### ISSUE TITLE
Redirect to login page after sign up submission

### ISSUE THREAD

**Issue by bsilverstein** [IQSS/dataverse#3225] opened 2016-07-28 20:14 UTC
While testing email confirmation with @pdurbin we happened upon a bug wherein after creating a [builtin] user, the redirect page brings you to loginpage.xhtml after logging in the newly created user. Using demo.dataverse.org to test (v4.4 build 132-47b04ed), the resulting URL from pressing Sign Up via loginpage.xhtml is:

https://demo.dataverse.org/dataverseuser.xhtml?editMode=CREATE&redirectPage=%2Floginpage.xhtml

Note the redirectPage.

To reproduce this you'll be redirected upon signup to whatever page you hit "Sign Up" from. So if it's from the root dataverse, great!  However if you are on the login page (after logging out) and find yourself without a user, then go to sign up, you'll be brought to the login page after registering (while already being logged in). See screenshot below and note that there is a user dropdown in the upper right while also displaying login form.

![loginbug](https://cloud.githubusercontent.com/assets/16244907/17227632/3c7b3436-54dd-11e6-85fb-72038ee00016.jpg)

This is the direct landing page of registering as user foo bar (PHD, astrophysics) upon hitting Sign Up from the login page. So hitting Sign Up from any page will redirect you to that respective location assuming you can view it while logged out, but perhaps after signing up from loginpage.xhtml the user should be forcibly sent to either the home page or the account page.

**Comment by scolapasta** [comment] 2016-07-28 21:52
Something may be broken...

There is an optional parameter on each xhtml file that is supposed to direct it to where to go after login, if not itself.

login.xhtml has:
<ui:param name="loginRedirectPage" value="dataverse.xhtml"/>

But clearly it's not doing that...

**Comment by scolapasta** [comment] 2016-07-28 21:57
Ah, I think this is a regression from when I moved some logic from the header to the new navigationWrapper.

**Comment by djbrooke** [comment] 2016-10-17 23:44
@bsilverstein95 - welcome back! I'm going to assign this one to you.

**Comment by pdurbin** [comment] 2017-06-25 15:37
I wouldn't be surprised if this is fixed now that the UI is completely different (#3338) and that shib redirect works (#1551). @bsilverstein95 can you retest?

**Comment by mheppler** [comment] 2018-10-25 15:56
@pdurbin I can confirm this bug is still buggy in `develop`.

@scolapasta I tried looking at the `loginRedirectPage` param on the login.xhtml compared to how other pages use it, and couldn't see an obvious fix. There are 8 other pages that use the same parameter.

What I believe is the problem is that signup/"Create Account" page should never have the login page as a redirect destination.

`http://localhost:8080/dataverseuser.xhtml?editMode=CREATE&redirectPage=%2Floginpage.xhtml`

Maybe that is stating the obvious, but I just wanted to call that out clearly none the less.

**Comment by landreev** [comment] 2018-11-21 00:57
I made a PR with a simplest possible 3 line fix. 
No refactoring of the redirect framework in this PR.

**Comment by pdurbin** [comment] 2018-11-21 01:43
Pull request #5335 may not be a complete solution of "someone emailed me a link to an unpublished dataset that I couldn't see and I clicked the link and went through the create account workflow and landed on the dataset" workflow. Instead, this user ends on the home page. But it's better than the login page. It's incremental progress. Approved. Moving to QA. Kudos to @landreev for coming up with a quick fix because I didn't pick this up over fear of the work involved in a more complete solution.

**Closed** 2018-11-30 21:04 UTC
Labels: Feature: Account & User Info, Type: Bug
