### ISSUE TITLE
Should the Geographic Bounding Box allow optional coordinates and multiple boxes in the XML?

### ISSUE THREAD

**Issue by JingMa87** [IQSS/dataverse#7108] opened 2020-07-22 03:33 UTC
When the issue occurs: When harvesting a dataset with Geospatial Metadata
Which page it occurs on: It occurs when harvesting, so the Dashboard
To whom it occurs: People who harvest Geospatial Metadata
Version: 4.20

**Context**
In issue https://github.com/IQSS/dataverse/issues/3648 we addressed the problem that Dataverse doesn't always produce valid DDI. One of the issues is that DDI doesn't allow optional coordinates and is unclear about multiple geographic bounding boxes. This problem can be fixed by filtering out DDI-invalid entries when making the XML. There's also an issue open for similar changes in the UI: https://github.com/IQSS/dataverse/issues/7091

**All four points are mandatory**
DDI requires a bounding box element to have exactly one occurrence of every point. The default minOccurs and maxOccurs is 1 when not specified.

![image](https://user-images.githubusercontent.com/16444164/87686267-9b19ef00-c784-11ea-8bd3-47c694a9e207.png)

**Unlimited boxes?**
On the one hand, the geoBndBox element can logically only occur once according to the DDI textual description since it's the biggest box where all locations fall in. On the other hand, the technical spec says that the geoBndBox element can occur multiple times as part of the sumDscr element. Does it logically make sense to add unlimited amounts then? Do researchers define multiple boxes? We will conclude this in the Geospatial Discovery Working Group.

![image](https://user-images.githubusercontent.com/16444164/87687093-9c97e700-c785-11ea-8029-5dabc6eccaa0.png)

**Comment by JingMa87** [comment] 2020-07-29 09:51
@pdurbin @jggautier I've had email contact with the DDI Alliance and Wendy Thomas, the chair of the technical committee, responded that the Codebook only supports one Geographic Bounding Box. They are basically in the process of reviewing the DDI specs and also adding high level documentation. This problem has been added to their own issue tracker so their working group can address it. I'm also going to join the group to add a Dataverse perspective. To me it seems that there's green light to make a PR for only adding one geoBndBox element to the XML, do you guys agree? Otherwise we'd have to wait until at least September for discussing this in the Geospatial Discovery Working Group.

**Comment by jggautier** [comment] 2020-07-29 15:55
I agree, especially about not recording in the DDI XML export when there are fewer than four fields filled.

To help answer "Do researchers define multiple boxes?", in the 35 Dataverse installations whose metadata I've collected so far, when people haven't filled out all four bounding box fields it's almost always because they used two of the fields for lat long points instead (there are other GitHub issues about adding fields for recording other types of geographic metadata, like lat long points, and fixing this metadata in Harvard Dataverse).

About the multiple boxes, in those 35 installations there are eight datasets whose latest versions have multiple sets of bounding box fields where each set has all four fields filled. In at least one case, this was done because the data of two studies was put into one dataset. I've heard from researchers that putting the data of multiple studies into one dataset is just more convenient than creating two datasets, especially if both studies are associated with one journal article. I don't know if that's the case for all eight datasets. Maybe something the working group can look into.

So would the PR you're thinking of change the DDI XML export so that only the first set of bounding boxes is included in the XML and only if all four fields are filled? (Surprisingly, the DDI Codebook xsd allows anything to be entered in those fields.)

I think it should be noted that this will also affect the DDI HTML Codebook export. (The PR for that HTML export at https://github.com/IQSS/dataverse/pull/6081 makes me think that the HTML is generated from the DDI XML. One HTML codebook with multiple complete bounding boxes is at https://dataverse.harvard.edu/api/datasets/export?exporter=html&persistentId=doi:10.7910/DVN/6R8F7U)

If this is something that needs to be fixed before the working group can consider it, I think it's fine to make this change, especially since it seems easy to adjust later assuming that it's easy for installations to recreate or reexport the DDI Codebook XML and HTML of existing datasets.

**Comment by JingMa87** [comment] 2020-07-30 08:15
> I've heard from researchers that putting the data of multiple studies into one dataset is just more convenient than creating two datasets, especially if both studies are associated with one journal article.

I can definitely understand that, but then there should be one bounding box which encompasses both studies geographically.

> So would the PR you're thinking of change the DDI XML export so that only the first set of bounding boxes is included in the XML and only if all four fields are filled?

Yes.

> I think it should be noted that this will also affect the DDI HTML Codebook export.

I'll check if I need to fix anything for that.

**Comment by pdurbin** [comment] 2020-07-30 16:19
> the DDI Alliance are basically in the process of reviewing the DDI specs to address problems like this. It has also been added to their issue tracker so their working group can address it.

Great! If their issue tracker is public, please link to the issue here.

> I'm also going to join the group to add a Dataverse perspective.

Fantastic! Thank you! 🎉 I'm hoping you'll find some other Dataverse people there, such as @stevenmce

> To me it seems that there's green light to make a PR

I'm torn between saying, "Sure, go ahead" and "Maybe wait until the GDCC geopatial working group has met." The problem is, I have no idea when they will meet. So I guess you should go ahead if you feel like it. @jggautier seems to be on board. 😄

**Comment by stevenmce** [comment] 2020-07-31 02:29
Hi all,
I'm involved in the DDI codebook review, as is @jggautier and others. Would be good to have the DataverseNL/CESSDA perspective in there.
Cheers,
Steve

**Comment by JingMa87** [comment] 2020-07-31 17:08
Multiple bounding boxes: https://ddi-alliance.atlassian.net/browse/DDICODE-70
Geographic hierarchies (geoCover): https://ddi-alliance.atlassian.net/browse/DDICODE-71

**Comment by JingMa87** [comment] 2020-08-03 20:29
@pdurbin Actually, it's better to wait for this fix until https://github.com/IQSS/dataverse/pull/7135 is merged, because the code base overlaps.

**Comment by jggautier** [comment] 2020-08-25 14:24
Just updating this issue: In the ticket at https://ddi-alliance.atlassian.net/browse/DDICODE-70 Wendy reiterated that only one bounding box should be included per dataset and suggested that the DDI documentation about the field could be edited "to explain the point of having a single Bounding Box." 

Wendy also noted that bound polygons might be the best option when depositors need to define individual areas.

Maybe the geospatial and/or metadata working groups can consider editing the tooltip with the Bounding Box explanation that makes its way into the DDI Codebook documentation and consider adding a repeatable bound polygon field.

If Dataverse's geospatial metadatablock is changed so that the Geographic Bounding Box field is non-repeatable, what will happen if someone tries to edit a dataset that currently has multiple Geographic Bounding Boxes? (I think the same question applies for several metadata model changes that need to be made in existing Dataverse-based repositories. I'm trying to test this scenario but it might take some time. Still learning how to change Dataverse's configurations.)

**Comment by pdurbin** [comment] 2022-10-12 02:19
@JingMa87 is no longer working on the issues he opened: https://github.com/IQSS/dataverse/issues/7412#issuecomment-1273464175

We should check with the DANS crew to see if any of them are still interested in this: @PaulBoon @janvanmansum @WittenbergM @LauraHuisintveld

It looks like @stevenmce commented above. Hi!

> Issue at DDI Alliance: https://ddi-alliance.atlassian.net/browse/DDICODE-70

There's some robust discussion in the issue above as well.

**Comment by janvanmansum** [comment] 2022-10-28 14:10
@pdurbin : sorry for the delay. This issue is not a priority for DANS.

**Comment by jggautier** [comment] 2023-11-17 16:45
There's some related work being documented at https://github.com/IQSS/dataverse/issues/9547

**Comment by cmbz** [comment] 2024-08-20 15:19
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Closed by cmbz** 2024-08-20 15:19 UTC
Labels: Type: Suggestion, Feature: Harvesting, User Role: API User, Feature: Geospatial
