### ISSUE TITLE
Last Login Time is not updated for Shibboleth user

### ISSUE THREAD

**Issue by joe00z** [IQSS/dataverse#8637] opened 2022-04-22 02:33 UTC
**What steps does it take to reproduce the issue?**
User login via Shibboleth
Dataverse admin check the user information by curl -X GET http://$SERVER/api/admin/authenticatedUsers/$identifier and check the information in the table authenticateduser

* When does this issue occur?
When Dataverse admin check the user information by API and from the database

* What happens?
The last login time of the users who login via Shibboleth is not updated

* To whom does it occur (all users, curators, superusers)?
Admin (cannot get the last login time of the user)
Users who login via Shibboleth (their last login time is not updated)

* What did you expect to happen?
The last login time of the users who login via Shibboleth is updated when they login

**Which version of Dataverse are you using?**
5.5

**Any related open or closed issues to this bug report?**
https://groups.google.com/g/dataverse-community/c/Nsk6guWCW3U

**Comment by pdurbin** [comment] 2022-10-01 16:07
@joe00z thanks for opening this issue. I haven't tested it but I wouldn't be surprised if it's a legit bug. 🐞

**Comment by pdurbin** [comment] 2022-10-08 21:14
@joe00z it turns out we're already tracking this exact issue here:

- #6630

I'm going to close this issue as a duplicate of that older one. Thanks for reminding us about it!

**Closed by pdurbin** 2022-10-08 21:14 UTC
Labels: Type: Bug
