### ISSUE TITLE
Dashboard to manage users: expose more fields and make them sortable, in the API and UI 

### ISSUE THREAD

**Issue by gohsunee** [IQSS/dataverse#5726] opened 2019-04-08 14:05 UTC

**Comment by djbrooke** [comment] 2019-04-10 14:38
Thanks @gohsunee, this is a good idea (as is #5727). We'll consider this.

**Comment by pdurbin** [comment] 2020-04-22 19:02
@gohsunee there is a new pull request at #6848 by @pkiraly to make fields sortable via API, a step forward.

**Comment by djbrooke** [comment] 2020-08-27 20:21
Closing as a duplicate of #4285

**Closed by djbrooke** 2020-08-27 20:21 UTC
