### ISSUE TITLE
Dataset Metadata - Producer and Distributor Logos URL + Logo URL Fields 

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#207] opened 2014-07-09 15:36 UTC
---

Author Name: **Mike Heppler** (@mheppler)
Original Redmine Issue: 3621, https://redmine.hmdc.harvard.edu/issues/3621
Original Date: 2014-03-04
Original Assignee: Kevin Condon

---

Due to the 3.x way of saving logo URLs for the Contributor (was Distributor and Producer fields in 3.x), in the long term we can end up with broken image links when the image file link changes or the server that we're pointing to is down.

To avoid this in 4.0, test out removing Contributor Logo URL and URL from the UI to test out if users will miss it or not during beta. Will review after Beta to see if they should be added back. If added back we should consider allowing the data creator to upload a logo, via popup/image upload, that we will store the file in our database/server.

---

Related issue(s): #485
Redmine related issue(s): [3900](https://redmine.hmdc.harvard.edu/issues/3900)

---

**Comment by eaquigley** [comment] 2015-01-12 15:58
@posixeleni regarding your comment on 11/13/14 about modifying the tsv file for this. Wanted to confirm if that has been done. Thanks!

**Comment by posixeleni** [comment] 2015-01-12 16:02
RE: my comment on https://github.com/IQSS/dataverse/issues/207#issuecomment-62941598 yes this has been implemented in Dataverse 4.0 demo with the Beta 10 release. However, this is not complete since in 3.6 we can display the logo rather than just the URL of the logo.

**Comment by posixeleni** [comment] 2015-01-12 16:11
P.S. just noticed a typo in the watermarks for both Distributor and Producer Logo URL... put in a fix in the .tsv for this https://github.com/IQSS/dataverse/commit/bb07f2fea58dec22888f518f3bf7c92fd794660d

**Comment by eaquigley** [comment] 2015-01-14 22:39
@scolapasta who should this be assigned to?

**Comment by scolapasta** [comment] 2015-01-16 00:16
So to make this work,we need new "types" for url and logo, so we know to generically display them that way. @posixeleni and @sekmiller should coordiante to work on this, with Eleni changing the tsv files, and Steve changing the code to handle this. Might also need some @mheppler work on the UI side.

**Comment by mheppler** [comment] 2015-01-16 15:20
Related to #1319 and #656, maybe even a duplicate of one or both.

We should find time to meet, and discuss these tickets in more detail. @scolapasta @sekmiller @posixeleni @eaquigley

**Comment by scolapasta** [comment] 2015-01-30 19:47
Passing to @posixeleni to set values in displayFormat in db for these (per #1319).

**Comment by posixeleni** [comment] 2015-02-04 20:44
Per #1309 I have enabled this in the displayFormat field in the db. However, will need @mheppler to help me with the CSS styling to make these logos display in a uniform size. A more robust solution will be needed after 4.0 to look into implementing a feature for users to upload their distributor or producer logos using a form within the dataset.

**Comment by mheppler** [comment] 2015-02-05 18:00
Added Bootstrap style class to metadata logo image HTML to fix width issues with really large images. [ref #47f6d6dfefaaabff5bb9279f79df67e14304998b]

**Comment by mheppler** [comment] 2015-02-17 23:48
Added CSS styling to limit the height (40px) and width (180px) of logo images in the metadata fields, similarly to how it was done in 3.6.

**Comment by kcondon** [comment] 2015-02-19 19:34
Works, closing

**Closed by kcondon** 2015-02-19 19:34 UTC
Labels: Priority: High, Status: QA, Type: Feature
