### ISSUE TITLE
Curation API to find Datasets with db entries that will fail validation

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#5753] opened 2019-04-10 20:36 UTC
Over the years, we've tightened up our data validation rules in Dataverse. In Harvard Dataverse we have several datasets that can't be updated because the records in the DB contain characters that don't pass our current bean validation (#5744 has a few examples).

We should add a new API that allows Dataverse installation administrators to determine the problematic data within a suspected problematic dataset.

**Comment by landreev** [comment] 2019-04-12 18:32
Note that we appear to already have ``/api/admin/validate``. 
It goes through all the datasets in the database, and intercept any constraint violations. 
The API calls this method in BeanValidationServiceBean:
```
@TransactionAttribute(TransactionAttributeType.REQUIRES_NEW)
    public void validateDatasets() {
        for (Dataset dataset : datasetService.findAll()) {
            for (DatasetVersion version : dataset.getVersions()) {
                for (FileMetadata fileMetadata : version.getFileMetadatas()) {
                }
            }
        }
    }
```
(so I guess the idea is it'll throw an exception and stop as soon as it comes across the first invalid object?)

Questions: 
- Is this issue for creating a similar API, but for just one dataset? 
- (not a question, strictly speaking) The mysterious constraint violations I'm seeing throughout the app now do not appear to be thrown from just attempting to load a dataset; but only when you attempt to write the values back in the db (?)

**Comment by landreev** [comment] 2019-04-12 18:39
Hah, that API above has been in there since 2015. No wonder I didn't remember anything about its existence!

**Comment by djbrooke** [comment] 2019-04-12 19:27
@landreev thanks for the reminder about that API :) 

@scolapasta thanks for offering to run the existing API. Once we have more details about the output there, I'd like to re-evaluate if we take this on.

**Comment by landreev** [comment] 2019-04-16 17:36
@djbrooke - we definitely do want to take this on in this sprint, I don't think it's a matter of any debate at this point. These constraint violations are affecting our production operations (and other partners' installations too, as we know by now), and we still don't have a way to diagnose it. 
That old API that we've had since 2015 is not suitable for that (but it has some code already written that can be reused for our current needs). 
The current plan for moving forward is outlined in my comment in https://github.com/IQSS/dataverse.harvard.edu/issues/8. (once we release in prod., we'll also upgrade vm5, and I'll throw a custom build on it and we'll hopefully find the offending pieces).

**Comment by donsizemore** [comment] 2019-04-16 17:43
@landreev I can reproduce this problem with the same dataset on a test Dataverse instance which I'm happy to poke, Tase® or otherwise discomfort in order to help you troubleshoot.

**Comment by djbrooke** [comment] 2019-04-16 17:43
Thanks @landreev! @scolapasta showed me the... unhelpful output of the existing API yesterday. My question to him was if we should make that API better or make a new API. He wanted to talk with you. I don't have a preference either way, and I definitely agree that some fix is a priority.

**Comment by landreev** [comment] 2019-04-16 17:49
Thanks @donsizemore. We know of a few datasets and reproducible scenarios that result in these type of exceptions; unfortunately the resulting stack traces do not say what it is that actually violates the constraint. (```Please refer to embedded ConstraintViolations for details``` - but no details provided). Apparently you need special exception handling to get that - so we are adding it to the code now, and are going to run it on a copy of our prod. database soon.

**Comment by landreev** [comment] 2019-04-16 17:54
> My question ... was if we should make that API better or make a new API.

Probably both? We'll fix the existing API (that tries to go through all the datasets in the database). It also needs to be made asynchronous (it takes too much time to be able to complete - so it should run in the background, and write the output into its own log - ?). 

But we probably also want to add another API call, to be able to run this validation on just one dataset. 

This should all be very easy, once we have the actual validating code that works.

**Comment by landreev** [comment] 2019-04-16 21:21
I added a quick single-dataset validation API, and deployed the war file on vm5 (with a recent copy of the prod. db). 
Running it on the dataset from https://github.com/IQSS/dataverse.harvard.edu/issues/15:
```
# curl http://localhost:8080/api/admin/validate/dataset/47996
{"status":"OK","data":{"entityClassDatabaseTableRowId":"[DatasetVersion id:44542]","field":"archiveNote","invalidValue":"Replaced by version 2"}}
```

**Comment by landreev** [comment] 2019-04-16 23:39
I have started a validate-all-datasets job, using the new experimental API on vm5. We'll know if it's all the same error by tomorrow.

**Comment by landreev** [comment] 2019-04-22 19:17
As I mentioned earlier, I made the validate-all API (```/api/admin/validate/datasets```) streaming (i.e. it starts producing output immediately). 
It's working for all practical purposes; we were able to use it to locate all the invalid datasets currently in the production database. 
There's still something that would be nice to resolve before we move this - even though we are intercepting these extended constraint violation exceptions, the server log file is still getting filled with the exception stack traces (??). 
I'm not actively working on this issue at this very moment.

**Comment by landreev** [comment] 2019-04-25 22:41
Question for the reviewer: 
I'm thinking of removing the BeanValidationServiceBean altogether. It doesn't do any validation really - it just goes through the list of the datasets; with the assumption that an invalid one will trigger a constraintviolation exception, that can be intercepted outside. 
My current implementation does not use this service bean at all; it instantiates one dataset at a time, in a new transaction each time - so that all the datasets can be validated, as opposed to stopping when the first violation is encountered. 
I used a method from DdatasetServiceBean for that instantiation. So eanValidationServiceBean is not being used at all. 

Should I remove it? Or keep it for future use?

**Comment by pdurbin** [comment] 2019-04-26 16:20
Pull request #5799 looks good from a code perspective so I moved it to QA so testing can begin.

Removing BeanValidationServiceBean should be straightforward and yes, I think it should be removed. It looks like I added it in 0493d47 back in 2015 so it's even in 4.0. At the time I remember being frustrated that all bean validation errors were blamed on indexing (which I was mostly responsible for) and I stubbed out that code back then to exercise the bean validation rules outside of indexing. @scolapasta has a good memory and asked me the other week if I had pushed this code into the repo or not and because I never documented the "validate" endpoint I added, I couldn't find it. No harm done. This issue is the real, documented "validate" endpoint that I'm sure will be very useful. @donsizemore asked about it in the pull request. It sounds like he's got a dataset he wants to try it on. More on that in a bit.

I did leave some feedback for possible doc improvements and I have one more that I forgot to add. @donsizemore asked if the files need to be in place to use this API endpoint. My read is that the files do not need to be in place. This could be added to the docs. Plus some other tweaks. I'm happy to make these tweaks if someone wants me to. Please let me know.

**Comment by landreev** [comment] 2019-04-26 20:42
I made a few minor doc changes, and linked the new validation API section from the "Datasets Management" and "Troubleshooting" sections of the Admin guide, per @pdurbin suggestions. 
Should be ready to be merged, if there are no other suggestions.

**Closed** 2019-04-26 20:46 UTC
