### ISSUE TITLE
Chrome browser is stripping the file extensions for .csv and .xlsx files when downloading original format

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2121] opened 2015-04-30 17:37 UTC
Discovered by a user when they tried to download an xlsx file but I also then found out that this issue is occurring for csv files as well. The file extensions for other tabular files are not being removed (tested .sav, .dta and .rdata)

CSV example
https://dataverse.sandbox.socialhistoryservices.org/dataset.xhtml?persistentId=hdl:10622/UFQVCS

XLSX example
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi%3A10.7910%2FDVN%2FHEWGDD&version=DRAFT

This issue only appears to be happening in Chrome. Tested on Firefox and Safari and did not have this issue with those browsers.

**Comment by kcondon** [comment] 2015-06-15 22:15
I was not able to reproduce this with the above links. Closing as resolved.

**Closed by kcondon** 2015-06-15 22:15 UTC
Labels: Component: File Upload & Handling, Priority: High, Status: QA, Type: Bug
