### ISSUE TITLE
Track views for Dataverses and Datasets

### ISSUE THREAD

**Issue by mercecrosas** [IQSS/dataverse#1969] opened 2015-04-10 18:48 UTC
We have the metric UI, but not yet tracking the views to a dataset or dataverse page. This can be obtained from Google analytics.

**Comment by bencomp** [comment] 2015-04-14 10:05
We would like these numbers too, but please do not rely on Google Analytics exclusively (#1594).

**Comment by mcrosas** [comment] 2015-04-14 18:27
Thanks @bencomp - we will take this into account, and it might be a good idea to work on it together.

**Comment by jggautier** [comment] 2018-01-12 00:42
@pdurbin, I'm going to remove the Vote to Close tag, and perhaps expand the scope to include Piwiks as suggested by @bencomp. (Is expanding the scope to include any analytics tool prohibitively broad?)

**Comment by pdurbin** [comment] 2018-01-12 00:54
@jggautier I'm fine with whatever but I'm wondering if you (or whoever) wants Dataverse itself to track the data into the PostgreSQL database or if the tracking is supposed to be done by Google Analytics or Piwik (both of which are supported these days). Or both.

**Comment by jggautier** [comment] 2018-01-12 01:11
The request I think is tracking page views in the UI, similar to download metrics, for datasets and dataverses (which would be a sum of page views of that dataverse's datasets). It's easy to get page views of datasets directly from Google Analytics or Piwiks, but it's very time consuming to get page views of datasets of a particular dataverse (because dataset URLs don't include info about its dataverse, which is what #3312 is about).

@sbarbosadataverse has to configure and send reports for a few dataverse admins (e.g. Harvard Business School), many with lots of datasets. Others would like the same info. The only solution right now is configuring reports in Google Analytics for each dataverse's dataset, and adding more datasets to that report as new datasets are published. This doesn't scale well.

I'm looking for any Google Analytics tricks that might involve getting page views for a saved list of dataset URLs, but this still involves us configuring and sending reports to these dataverse admins.

**Comment by jggautier** [comment] 2018-01-12 03:16
Because the dataverse admins Sonia works with need monthly page view reports, I suppose storing the data in the database to make it downloadable the way guestbook responses are would work.

**Comment by mheppler** [comment] 2018-04-02 15:58
Related to, duplicate of issue **Dataverse - Views, Downloads, Citations, Shares #1808** and **Dataverse metrics bar at sub-dataverse level #3527**.

**Comment by jggautier** [comment] 2018-09-28 18:00
Noting that metrics that Dataverse will display when implementing Make Data Count standard (#4821) will include page views.

**Comment by pdurbin** [comment] 2018-09-28 18:03
@jggautier I removed the "vote to close" label but please help us remember to put this issue through QA as part of Make Data Count support if we're not simply closing it as a duplicate.

**Comment by pdurbin** [comment] 2019-07-26 15:40
@djbrooke do you think we should put this issue through QA along with pull request #6040 for Make Data Count? Views for dataverses are not tracked by Make Data Count but views for datasets are.

**Comment by djbrooke** [comment] 2019-07-26 15:48
I'm going to close this. We'll verify the dataset views as part of the QA in the Make Data Count issue. This does not include views for Dataverses and Datasets in non-MDC installations, but Matomo, GA, Splunk and other tools exist for those who want to set up monitoring at these levels.

**Closed by djbrooke** 2019-07-26 15:48 UTC
Labels: Feature: Metrics + Reports, Status: UX & UI, User Role: Curator

**Comment by pdurbin** [comment] 2019-07-26 15:54
> Matomo, GA, Splunk and other tools exist for those who want to set up monitoring at these levels

Yep, and these days we document some of them at http://guides.dataverse.org/en/4.15.1/admin/monitoring.html#http-traffic
