### ISSUE TITLE
dataverse.publish.not.authorized used but not defined

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#6375] opened 2019-11-15 17:29 UTC
In DataversePage.java around line 911 but not in Bundle.properties.

**Comment by mheppler** [comment] 2021-02-17 16:37
Closing as duplicate of **Bundle missing "dataverse.publish.not.authorized" #7438**, which was fixed in PR #7620.

**Closed by mheppler** 2021-02-17 16:37 UTC
