### ISSUE TITLE
User SignUp allows invalid characters and results in partial account creation

### ISSUE THREAD

**Issue by mdmADA** [IQSS/dataverse#4121] opened 2017-08-31 21:16 UTC
Version 4.6.1

Go to Sign Up:

1. Enter a username with "@" in it (a lot of users will try to user their email address as their username) - the "@" is not 'allowed' according to the hint but they only know that if they read the hint.

2. Fill in the rest of the fields and click "Create Account"
Nothing happens - the page appears to just 'sit' there with the data filled in.

3. Click "Create Account" again and it says the email address and username are already in use.

4. Try to log in with the username - UI says username and/or password are incorrect

4. Look in the database:

There is a record with the defective username (and the other details) in authenticateduser
There is a record with the defective username (and the other details) in authenticateduserlookup

There is no record in builtinuser so login is impossible.

5. In server.log:

Caused by: java.lang.IllegalArgumentException: BuiltinUser could not be saved to due constraint violations:  Invalid value: <<<xxxxx.xxxx@gmail.com>>> for userName at BuiltinUser{id=null, userName=xxxxx.xxxx@gmail.com, email=xxxxxxx@gmail.com} - Found an illegal character(s). Valid characters are a-Z, 0-9, '_', '-', and '.'.
        at edu.harvard.iq.dataverse.authorization.providers.builtin.BuiltinUserServiceBean.save(BuiltinUserServiceBean.java:68)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)

6. The user can't log in. And since there is no indication of an issue in the UI, doesn't realise what has happened.

They try to Sign Up again with different username and same email address, they get the message that the email address has already been taken.

The username should be validated to prevent this from happening.

**Comment by djbrooke** [comment] 2017-08-31 23:30
Hey @mdmADA - good find, good report. Thanks! I think this is a duplicate of #3752, which will be fixed when we ship the next release. I'll close this one, but feel free to reopen if you think it's a different issue.

**Closed by djbrooke** 2017-08-31 23:30 UTC

**Comment by mdmADA** [comment] 2017-09-01 02:36
Yes, it's a duplicate. Same issue. I did a search beforehand to see if there was already an issue but my search terms need some work I guess!

I also noticed that the username UI hint does not match the database error - the latter says that '.' and '-' are allowed but the UI hint implies those are not allowed.
