### ISSUE TITLE
Add persistent identifier parameter option for File Download API

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#4295] opened 2017-11-20 19:41 UTC
Now that we are adding persistent identifiers to files we want to update the file download APIs so that they can take in a persistent identifier instead of the file ID. (related to #2438 and #4232) 

connects to #2438

**Comment by pdurbin** [comment] 2017-11-21 15:08
Unless there is a compelling reason not to, I think we should address this issue of supporting persistentIds (DOIs and Handles) at the file level, the same way @michbarsinai implemented this support at the dataset level in pull pull request #2893 for issue #1837.

You can find `private static final String PERSISTENT_ID_KEY=":persistentId";` in `AbstractApiBean.java`, which is the magic string to use to have the code switch from "database id mode" to "DOI mode".

Just yesterday @matthew-a-dunlap and I were discussing how confusing this is for API users so I'd love for us to to improve the documentation in the API Guide in this area. 

In practice, you use `:persistentId` like this: https://dataverse.harvard.edu/api/datasets/:persistentId/versions/:latest?persistentId=doi:10.7910/DVN/TJCLKP

**Comment by michbarsinai** [comment] 2017-11-21 22:25
Just a bit of background for future readers: The reason for this weird URL is that persistent IDs may - and often do - contain "/". So they can't be a regular fragment of the URL.

**Comment by pdurbin** [comment] 2017-11-27 16:44
As I mentioned before the break and at standup this morning, pull request #4301 is difficult to code review because it's hard to see just the "Add persistent identifier parameter option for File Download API" changes. I even tried comparing the two related branches that are in flight but there's all sorts or ORCID and schema.org stuff in the diff:

https://github.com/IQSS/dataverse/compare/2438-persistent-identifiers-for-files...4295-File-download-api-via-persistent-identifiers

Maybe I'll try making a new branch or something, but it sounds like the `2438-persistent-identifiers-for-files` branch is still in flight due to requested changes for #2438.

Perhaps we should wait for the `2438-persistent-identifiers-for-files` to settle down and then make a new branch off of it for this issue?

Or maybe someone can show me how to see just the diff that this issue is supposed to represent.

**Comment by pdurbin** [comment] 2017-12-04 21:33
We're thinking about testing this issue and #2438 in single branch. Please see https://github.com/IQSS/dataverse/issues/2438#issuecomment-349112944

**Comment by kcondon** [comment] 2017-12-11 21:42
This works for hdl and doi.

**Comment by djbrooke** [comment] 2018-05-17 15:35
Discussed after standup, @kcondon is going to take another quick look. Moving to QA.

**Comment by kcondon** [comment] 2018-05-17 19:07
Works on all endpoints except multiple files download (as designed):
1. Basic file download
2. Column-wise subset
3. Bundle download
4. Metadata download
5. Preprocessed download.
Have tested so far using doi with shoulder.
Will test with handles and doi without shoulder.

**Closed** 2018-05-17 21:31 UTC
Labels: Status: QA
