### ISSUE TITLE
File Categories + Tabular Data Tags - Improve Layout

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1776] opened 2015-03-26 00:10 UTC
Now that the file category and tabular data tags are properly displaying on the browse/search file cards and the files table on the dataset page, please review their layout, see what improvements can be made.

- [x] "You currently have no categories set for this file" message on Upload + Edit Files is displayed when the tabular data tags are displayed.
- [x] Review label colors for file categories, tabular data tags, draft, unpublished, etc.

**Comment by mheppler** [comment] 2015-03-31 15:25
Need some fixes to the Edit Tags popup. The Tabular Data Tags aren't saving.

Please also review the SPSS workflows to make sure they are working properly. The text still needs to be updated on those buttons and popups from "Advanced Options" to something more specific. @landreev  @eaquigley -- suggestions?

**Comment by landreev** [comment] 2015-04-01 21:46
I'm going to check in a fix for this, and 1775, shortly.

**Comment by landreev** [comment] 2015-04-02 02:01
@mheppler 
Tabular tags should now be working; 
#1775 is already in QA;
SPSS ingest options are working too. 
This ticket should be ready for QA. Except I noticed that the "File Tags" (former "categories") and "Tabular Tags" are being displayed in the same color. And I don't know if this is by design, or by accident. 

So please either send this to QA or change the color, whichever is appropriate.

**Comment by mheppler** [comment] 2015-04-02 19:24
Cleaned up the "Advanced Ingest Options" popup for SPSS files on ingest. Changed label colors for Tabular Data Tags on dataset and browse/search on dataverse pages.

**Closed** 2016-01-12 19:05 UTC
Labels: Component: File Upload & Handling, Component: Search/Browse, Component: UX & Upgrade, Status: QA
