### ISSUE TITLE
Harvard Dataverse: Breadcrumbs link to search results page, not new home page

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#5682] opened 2019-03-26 15:11 UTC
Now that Harvard Dataverse has a home page, the "Harvard Dataverse" breadcrumb should link to the home page, not the search results page.

**Comment by dlmurphy** [comment] 2019-03-26 15:22
I originally surfaced this issue (noticed it in the UI and thought "hm, is this inaccurate?). But we just discussed with @mheppler and he pointed out that the "Harvard Dataverse" breadcrumb is not referring to the website Harvard Dataverse but rather the root dataverse _called_ Harvard Dataverse. A fine distinction, but he's right, this is actually working as intended. After discussing with @TaniaSchlatter, we're closing this issue.

**Closed by dlmurphy** 2019-03-26 15:22 UTC
