### ISSUE TITLE
4.9.4 : Connexion problem with French local

### ISSUE THREAD

**Issue by Thanh-Thanh** [IQSS/dataverse#5338] opened 2018-11-22 10:19 UTC
Hi all,

We are in the process to upgrade to 4.9.4, however, we got the problem using this 4.9.4 version : can not connect with username/password.

The scenario to reproduce this bug :
- Our machine is in French local
- After the deploiment of 4.9.4, the first connexion comes from a navigator with French local
- Connect with builtin mode : username and password
=> [2018-11-20T15:56:25.969+0100] [glassfish 4.1] [WARNING] [AS-EJB-00056] [javax.enterprise.ejb.container] [tid: _ThreadID=48 _ThreadName=jk-connector(1)] [timeMillis: 1542725785969] [levelValue: 900] [[
  A system exception occurred during an invocation on EJB AuthenticationServiceBean, method: public edu.harvard.iq.dataverse.authorization.users.AuthenticatedUser edu.harvard.iq.dataverse.authorization.AuthenticationServiceBean.getUpdateAuthenticatedUser(java.lang.String,edu.harvard.iq.dataverse.authorization.AuthenticationRequest) throws edu.harvard.iq.dataverse.authorization.exceptions.AuthenticationFailedException]]

[2018-11-20T15:56:25.969+0100] [glassfish 4.1] [WARNING] [] [javax.enterprise.ejb.container] [tid: _ThreadID=48 _ThreadName=jk-connector(1)] [timeMillis: 1542725785969] [levelValue: 900] [[
  
javax.ejb.EJBTransactionRolledbackException
	at com.sun.ejb.containers.BaseContainer.mapLocal3xException(BaseContainer.java:2342)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2123)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2044)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:220)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
	at com.sun.proxy.$Proxy271.validate(Unknown Source)
	at edu.harvard.iq.dataverse.validation.__EJB31_Generated__PasswordValidatorServiceBean__Intf____Bean__.validate(Unknown Source)
	at edu.harvard.iq.dataverse.authorization.providers.builtin.BuiltinAuthenticationProvider.authenticate(BuiltinAuthenticationProvider.java:126)
	at edu.harvard.iq.dataverse.authorization.AuthenticationServiceBean.getUpdateAuthenticatedUser(AuthenticationServiceBean.java:346)

Complete stacktrace attached here:
[connexionProblem_4.9.4_server.log](https://github.com/IQSS/dataverse/files/2607542/connexionProblem_4.9.4_server.log)

I've debugged this part and see that the bug lies in the way of construction and getting the password  from AuthenticationRequest : 
in BuiltinAuthenticationProvider class, the authenticate method :
- password is retrived with the fix string "Password" (ligne 126)
- AuthenticationRequest, however, has a translation as key for the password

Can you please fix the bug please ?

Thanks in advance,

Thanh Thanh

**Comment by djbrooke** [comment] 2018-11-26 17:08
Ping @JayanthyChengan - do you have any thoughts on what this could be? I also know we've merged in quite a bit of internationalization code that will be included in the next release, so this may already be fixed.

**Comment by pdurbin** [comment] 2018-11-26 17:15
This reminds me a lot of the "Can't log in in French" issue at #5090 which was fixed in pull request #5222 but we haven't made a release yet.

**Comment by mheppler** [comment] 2019-06-19 18:20
@Thanh-Thanh have you been able to upgrade to 4.10? If so, please confirm if the fix from #5090 resolves the issue you reported above and we can close this issue.

**Comment by Thanh-Thanh** [comment] 2019-06-24 19:52
@mheppler : sorry for the late reply. We've upgraded our env test to 4.10.1 and we do not have this problem any more. 
Thanks !

**Comment by mheppler** [comment] 2019-06-24 19:55
Good to hear, @Thanh-Thanh. Thank you for the reply. I am going to close this issue as a duplicate of the _Can't log in in French #5090_ issue that was fixed in 4.10.1.

**Closed by mheppler** 2019-06-24 19:55 UTC
Labels: Status: Still Interested?
