### ISSUE TITLE
Dataset subjects listed out of order on dataset create, edit and advanced search pages

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#4532] opened 2018-03-21 16:16 UTC
On Harvard Dataverse (Dataverse version 4.8.4), Demo Dataverse (4.8.4), UNC (4.7.1) (and maybe other installations), the subject list (on dataset create, edit and advanced search pages) is not in the order that [the citation.tsv](https://github.com/IQSS/dataverse/blob/master/scripts/api/data/metadatablocks/citation.tsv) says it should be (i.e. alphabetical except for "Other" at the end).

Looks like this was noticed and fixed in 2016: https://github.com/IQSS/dataverse/issues/2355.

Other controlled vocabs in both checkbox and pulldown lists are in the right order from what I can tell.

Some other installations' subject lists seem to be in the right order (e.g. Scholars Portal Dataverse (4.7.1), TDL (4.8.4))

I'm seeing this on MacOS High Sierra 10.13.3 (17D102), on Chrome (Version 65.0.3325.162 (Official Build) (64-bit)) and Firefox (59.0.1 (64-bit)).

**Comment by mheppler** [comment] 2019-11-20 19:08
I am closing this issue, as I was not able to reproduce it. Looking at my local dev environment while working on #6339, I did not see an issue with the ordering. I also checked production (4.17), demo (4.17), and Scholars Portal (4.17), and didn't see any funny business any where.

The order of the subjects in the citations.tsv has not changed in over 4 years, so not sure what @jggautier saw on production that fateful day in March, 2018.

Also, note, we are changing the UI component for the Subject metadata form in #6339. (See screenshot.)

![Screen Shot 2019-11-20 at 2 02 28 PM](https://user-images.githubusercontent.com/687227/69269330-ca993d00-0b9e-11ea-9d9b-a660ced9a4ed.png)

**Closed by mheppler** 2019-11-20 19:08 UTC
Labels: Feature: Metadata, Type: Bug
