### ISSUE TITLE
Allow installation to decide if displayoncreate is true or false for metadata fields

### ISSUE THREAD

**Issue by vbernabe** [IQSS/dataverse#6561] opened 2020-01-23 06:47 UTC
Bug Report: Optional Metadata not showing on Dataset Form
Dataverse version: 4.18.1
Glassfish: 4.1

I am trying to update the Metadata to include optional field such as grant information but this is not showing up on the Create Dataset form.
Steps: 
1. Update Citation Metadata of Dataverse -> set grant information as optional field
![image](https://user-images.githubusercontent.com/3328254/72961679-e2827c80-3dec-11ea-9592-c919d974f71e.png)
2. Create a Dataset - it should show the grant information field without *
Issue below: grant field not showing
![image](https://user-images.githubusercontent.com/3328254/72961751-22496400-3ded-11ea-9a7f-dd39568579b1.png)

If I set the Metadata to Required though it will show up in the form.
Steps:
1. Update Citation Metadata of Dataverse -> set grant information as required field
![image](https://user-images.githubusercontent.com/3328254/72961900-aef42200-3ded-11ea-8b51-11e4e5114037.png)
2. Create a Dataset - it should show the grant information field with *. Correctly shown on form
![image](https://user-images.githubusercontent.com/3328254/72961852-8b30dc00-3ded-11ea-913f-63c043b7f1dd.png)

**Comment by pdurbin** [comment] 2020-01-23 12:32
@vbernabe hi! This is controlled by the "displayoncreate" boolean.

> "Designate fields that should display during the creation of a new dataset, even before the dataset is saved. Fields not so designated will not be displayed until the dataset has been saved."

Please see http://guides.dataverse.org/en/4.18.1/admin/metadatacustomization.html#datasetfield-field-properties

Here's a screenshot of that part of the doc.

![Screenshot from 2020-01-23 07-29-07](https://user-images.githubusercontent.com/21006/72984669-46d41a80-3db2-11ea-9f6a-161f332d8d22.png)

You can find the "displayoncreate" column here: https://github.com/IQSS/dataverse/blob/v4.18.1/scripts/api/data/metadatablocks/citation.tsv#L3

I hope this helps!

**Comment by djbrooke** [comment] 2020-01-23 15:44
Hi @vbernabe, I'll close this out since it appears to be answered but please let us know in a comment if there are any other questions. 

Thanks @pdurbin !

**Comment by vbernabe** [comment] 2020-01-24 05:41
Hi @pdurbin and @djbrooke, Thanks for your quick response. 

Is there a way to distinguish if a field is set as "optional" and can be viewed on creation of new dataset or if it will only be displayed after creation of a dataset? This is to avoid confusion, similar fields like - keyword, related publication, notes are showing even if it is set as optional but other fields set as optional for instance on this sample - grant information is not showing up.

Or maybe we can also include on the documentation that updating metadata blocks shipped with Dataverse will not automatically be shown to the creation of new dataset? I was thinking that I don't need to do custom metadata and can customize based on Dataverse web interface as suggested on the introduction of the documentation [http://guides.dataverse.org/en/4.18.1/admin/metadatacustomization.html#id14](url)

For now though I will do custom metadata update as you suggested :)

**Comment by pdurbin** [comment] 2020-01-24 12:26
@vbernabe right. Ideally, we don't want anyone to have to customize citation.tsv and other metadata blocks we ship with Dataverse. It's common in our release notes that we ask installations to reload citation.tsv, for example.

I'm reopening it because I think there is a usability problem here. I don't have all the answers, unfortunately.

Have you looked into dataset templates? http://guides.dataverse.org/en/4.19/user/dataverse-management.html#dataset-templates . I forget if they interact with `displayoncreate` or not.

**Comment by vbernabe** [comment] 2020-01-28 10:51
@pdurbin Unfortunately using the Dataset Templates doesn't show the optional fields on creation too.

I did the custom metadata route, setting the "displayoncreate" for "grant information" and it now shows up on create Dataset.

**Comment by pdurbin** [comment] 2020-01-29 22:16
@vbernabe cool but what if afterwards you reload the citation.tsv file from a Dataverse release? Does it undo your changes?

Here's an example of a Dataverse release that indicates to reload the citation.tsv file: https://github.com/IQSS/dataverse/releases/tag/v4.18

**Comment by vbernabe** [comment] 2020-02-16 05:03
@pdurbin yes it will undo my changes if I reload a new citation.tsv file. I need to make sure that the changes I have is applied to the updated citation.tsv before I reload it. It will be better though if there is an feature on the UI to make the optional field available on initial creation of metadata.

**Comment by pdurbin** [comment] 2020-02-24 16:13
@vbernabe ok, let me make sure I understand your current workflow:

- Check Dataverse release notes to see if citation.tsv must be reloaded.
- If a reload is required, edit citation.tsv from the release to make "Grant Information" (for example) available on dataset creation.
- Reload citation.tsv

Is that right? Thanks.

**Comment by vbernabe** [comment] 2020-02-26 11:19
@pdurbin Yes this is correct.

**Comment by pdurbin** [comment] 2020-02-26 11:32
@vbernabe ok, thanks. That does sound like a pain. I do agree we should make this easier. Expressing funding information is very important and I can understand why you want it on the shorter "create" form for datasets.

I guess a fix for you would be to simply make "Grant Information" displayoncreate=true for everybody. We did something similar for "Related Publication" recently in #3838.

Or is "Grant Information" just an example? Do you have a lot of fields that you want to be added to the "create" form?

**Comment by vbernabe** [comment] 2020-02-27 05:26
@pdurbin We have two fields "Grant Information" and "Software" that we show on the create form. It will be great if these will be displayed on create form, these fields are optional so if you make this displayoncreate=true I think it might not be an issue with others - this is just me though, I'm not sure how others will feel if this shows on the create form if they are not using it.

Ideally there should be a feature, maybe another checkbox on metadata settings? 
<img width="709" alt="image" src="https://user-images.githubusercontent.com/3328254/75414579-f8dba500-5963-11ea-8954-edd057ae00ca.png">

However, if this will take time to be implemented we are okay either way if we will reload the citation.tsv or making "Grant Information" and "Software" part of the default create form with displayoncreate=true.

**Comment by pdurbin** [comment] 2020-02-27 09:52
@vbernabe I mean, we are trying to encourage people to deposit code for reproducibility but I'm not sure if we really want "Software" on the create form out of the box or not. Entering funding information is also very important too, but again, we're trying to keep the "create" form somewhat short.

As we're discussing, it would be great to allow a "Display on Create" configuration option so that you don't have to do so much hacking on your citation.tsv file.

As a workaround I wonder if you or some other developer could write a wrapper script around the "reload" command. Maybe a file on the side called displayOnCreate.txt could have "Grant Information" and "Software" in it. Then the wrapper script would make the changes to the tsv file before loading it. If this sounds reasonable or interesting, you could add it as a use case to the Google doc attached to https://github.com/poikilotherm/dvcli/issues/1 (heads up to @poikilotherm ).

**Comment by poikilotherm** [comment] 2020-02-27 12:37
@pdurbin @vbernabe I remembered that Phil and I discussed this `displayOnCreate` issue a while ago and I [found it in IRC logs](http://irclog.iq.harvard.edu/dataverse/2019-05-10#i_93140). I never created an issue for that, I'm sorry that one slipped through.

Your suggestion sounds reasonable @pdurbin but I think we need to think bigger, which is why I created #6700 as a first (baby) step towards salvation of #4451 (thx for linking) and #6030.

If this would help you @vbernabe please reach out there. Thanks!

**Comment by pdurbin** [comment] 2020-02-27 12:42
@vbernabe or you are welcome to join me, @poikilotherm and [the gang][] at https://chat.dataverse.org of course! :smile: 

[the gang]: https://docs.google.com/spreadsheets/d/16h3jv24usMGq18495C-JA-yNcQCKiKDa65MTraNDd7k/edit?usp=sharing

**Comment by pdurbin** [comment] 2022-10-08 21:30
@vbernabe I just updated the title of this issue. I hope it looks ok.

Also, these issues related:

- #6885
- #6030

**Closed** 2024-08-20 15:21 UTC
Labels: Type: Suggestion, Feature: Metadata, User Role: Curator

**Comment by pdurbin** [comment] 2024-08-20 20:10
This issue is more or less the same as this newer one:

- #10476
