### ISSUE TITLE
Use DataCite Handle URL for testing?

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#7119] opened 2020-07-23 13:54 UTC
An issue for discussion: 

In https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/dataverse-community/4RZksu57AAk , there's discussion that DataCite appears to be creating a live https://handle.stage.datacite.org/* URL for test DOIs. That could give us a way to test/demonstrate how real DOIs work. (This used to be possible with the old 10.5072/FK2 test DOIs from EZID, but DataCite doesn't make test DOIs resolvable so there has been no way, without doing something like going into the Fabrica UI to see if the redirect to Dataverse works.) If the handle is going to stay (I think it's a recent feature), we might be able to use it in the Dataverse UI.

**Comment by poikilotherm** [comment] 2020-07-23 13:59
This is a duplicate of #6677.

**Closed** 2020-07-23 14:02 UTC
