### ISSUE TITLE
Email Dataset Contact - Email needs more information when authors replyto a user

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2882] opened 2016-01-21 14:29 UTC
I've been using the email icon to contact authors and when they reply I get no indication which dataset/dataverse they are replying from. Would be more helpful to have this info attached to the email dialogue box in some way.

**Comment by mheppler** [comment] 2017-01-06 16:24
@sbarbosadataverse this issue you opened looks to be similar to **Email Dataset Contact: No context info given in the email correspondance received #1916**.

Please clarify any differences between these issue in a new comment #1916, and then close issue as a duplicate.

**Comment by mheppler** [comment] 2018-04-10 13:53
Closing this issue as a duplicate of #1916 which is currently in development. Will also copy over the comment above from @sbarbosadataverse from Jan 21, 2016.

**Closed by mheppler** 2018-04-10 13:53 UTC
Labels: Feature: Email Dataset Contact, Help Wanted: Code, Mentor: pdurbin, Status: UX & UI, Type: Feature, User Role: Curator
