### ISSUE TITLE
Index: Cannot see unpublished dv or ds if assigned proper view perms as IPGroup.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1513] opened 2015-02-25 23:41 UTC
I've directly assigned admin role/ view unpublished dv/ds to an ipgroup but still cannot see the unpublished dv/ds cards, though I can see the role assignment on the permissions page. I can go directly to the landing pages for both and the permissions page for both as a member of the ip group.

**Comment by scolapasta** [comment] 2016-03-31 16:55
Please retest.

Be aware that IPGroups cannot have edit typer permissions, just read permissions.

**Comment by kcondon** [comment] 2016-04-28 21:40
Waiting for #1380 to be fixed before we can test.

**Comment by kcondon** [comment] 2016-07-15 13:55
Related, possibly a duplicate: #3105

**Comment by pdurbin** [comment] 2016-08-03 19:58
Today @michbarsinai @scolapasta @kcondon and I discussed IP groups and I've been asked to try to reproduce this bug in the branch that pull request #3103 is based on. It's believed this is still a bug.

**Comment by pdurbin** [comment] 2016-08-04 19:50
I can easily reproduce this bug by giving an IP Group "admin" on an unpublished non-root dataverse, which should result in the "Guest" user being able to see a search card for the unpublished dataverse.

Interestingly, the indexing seems fine. The unpublished dataverse in question says it's discoverable by the IP Group: `"discoverableBy":["group_ip/ipGroup3", "group_user5"]`

The problem is at runtime we need a method in Dataverse to provide a list of all the IP Groups that a user (such as Guest) is a member of. This strongly reminds me of the `public Set<Group> groupsFor(AuthenticatedUser au)` method I introduced in pull request #3062 but in the code you can see I wrote `@todo Determine if this method works with IP Groups`. Sadly, it seems the answer is no and since @michbarsinai is in town I plan to see if he can help with this.

**Comment by pdurbin** [comment] 2016-08-05 20:38
Some initial progress in e6438c7 but a bit rushed. Ideally I'd add some API tests.

**Comment by kcondon** [comment] 2016-08-12 20:59
This is working now. Phil, we can close this unless there is something more you want to do.

**Comment by pdurbin** [comment] 2016-08-19 17:41
@kcondon I'm glad to hear e6438c7 helped. It's in pull request #3103. I'll close this issue but I'll note that #3273 is still open which is about "groups within groups".

**Closed by pdurbin** 2016-08-19 17:41 UTC
Labels: Component: Permissions, Component: Search/Browse, Effort 3: Large, in progress, Priority 2: Moderate, Type: Bug
