### ISSUE TITLE
Make Waiver configurable

### ISSUE THREAD

**Issue by Thanh-Thanh** [IQSS/dataverse#4740] opened 2018-06-06 11:32 UTC
Hi all,
In our context, we want to change the default Waiver, in order to use another compatible license. 
This way, we facilitate the end user in their download action (without the need to say yes to the Term of use) 
Can you please make the default Waiver configurable (the text of the waiver and the 2 questions) ?
Thanks in advance,

Thanh Thanh

**Comment by poikilotherm** [comment] 2020-11-30 12:46
I think this is a duplicate of #1753 (like others #6436 #7440)

**Comment by pdurbin** [comment] 2022-09-30 21:15
@Thanh-Thanh Dataverse now supports lots of flexibility when it comes to licensing. (Yes, those issues are related. Thanks, @poikilotherm .)

Can you please check out https://guides.dataverse.org/en/5.11.1/installation/config.html#configuring-licenses and let us know if your needs are now met? Thanks.

**Comment by DS-INRA** [comment] 2022-12-14 09:47
Hello,
As Thanh Thanh is nolonger working with Dataverse this went out of the radar, but yes it is solved by the "new" licence feature !
You can close the issue :)

**Comment by pdurbin** [comment] 2022-12-14 18:28
@DS-INRA ok! Thanks! Closing!

**Closed by pdurbin** 2022-12-14 18:28 UTC
Labels: Status: UX & UI, Feature: Terms & Licensing, Status: Still Interested?
