### ISSUE TITLE
File Download: File download appears to have a 15 minute timeout, causing failures for large files and slow links.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2080] opened 2015-04-23 17:54 UTC
Reported by various users, especially on slow links but any download taking more than 15 minutes, the download halts, resulting in various user symptoms: zero length file (Mac/Mozilla) to partial download and corrupted zip file (windows, chrome)

**Comment by scolapasta** [comment] 2015-04-23 19:14
Closing as duplicate of #2068

**Closed** 2015-04-23 19:15 UTC
Labels: Component: File Upload & Handling, Priority: Critical, Status: Dev, Type: Bug
