### ISSUE TITLE
Create Account: Duplicate email addresses should not be allowed.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1141] opened 2014-11-18 18:04 UTC
For testing purposes, it is convenient to reuse the same email address when testing but this should not be allowed in production code, especially required by reset password.

This should be enforced prior to release.

**Comment by scolapasta** [comment] 2015-01-06 21:02
passing to QA as duplicate of #845

**Closed** 2015-01-07 18:27 UTC
Labels: Component: UX & Upgrade, Priority: Medium, Status: QA, Type: Bug
