### ISSUE TITLE
Can't read S3-stored datafile without the dataverse.files.s3-bucket-name JVM option present

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#5065] opened 2018-09-17 22:56 UTC
The JVM option dataverse.files.s3-bucket-name is required when using S3 and storing new files; it tells the S3 driver what "bucket" to put the file into. 
If you switch back to the filesystem, or swift driver, that's where any new files will be stored. But we're still supposed to be able to read any old S3 files. 
It appears that this is no longer working if the JVM option above is no longer present. Which seems unnecessary, because the bucket name is actually embedded in the storageidentifier that's saved in the database. 
For example, "s3://iqssqa:165a6268a5e-fb97b82e022d" - "iqssqa" is the bucket where the file lives. 

(This is probably one of the least important bugs/issues we have; it's just weird, and the failures are somewhat confusing...)

**Comment by poikilotherm** [comment] 2018-09-19 08:56
As I am currently looking into the S3 stuff anyway (see #4690), maybe I can try to fix this, too.

**Comment by pdurbin** [comment] 2018-09-19 11:07
@poikilotherm sure, while you're in there you could at least try to reproduce the bug and report any findings here. Thanks!

**Comment by qqmyers** [comment] 2018-10-06 12:12
FWIW - Looks like S3IOAccess just reads the jvm option and fails if it is not set. If it is set, for file reads, the code does use the bucketname written in the file storage identifier.

**Comment by pdurbin** [comment] 2023-12-01 20:55
I just checked with @landreev and he said it's safe to close this.

**Closed by pdurbin** 2023-12-01 20:55 UTC
Labels: Feature: File Upload & Handling, Type: Bug
