### ISSUE TITLE
Native API call to create dataset with JSON file changes keyword=Law to subject=Law and keyword=Engineering to subject=Engineering

### ISSUE THREAD

**Issue by mdmADA** [IQSS/dataverse#4877] opened 2018-07-23 01:33 UTC
DV 4.6.1 

1. API call:     POST http://$SERVER/api/dataverses/$id/datasets/?key=$apiKey
 send metadata json file containing keyword=Law and/or keyword=Engineering as post data.

2. the method removes Law/Engineering as keyword and sets subject=Law and/or subject=Engineering. It shouldn't. (ADA has a Social Sciences study researching professions, one of which is Engineering. So Engineering is a keyword but the Subject is Social Sciences).

Note this doesn't happen with manual entry of the metadata. If you set keyword=Law manually, it correctly stays as a keyword.

**Comment by pdurbin** [comment] 2018-07-24 02:35
@mdmADA thanks for the bug report. You're right, this is easy to reproduce on the "develop" branch. I'm on commit 42e6f7d.

Using `curl -H "X-Dataverse-key: $API_TOKEN" -X POST $SERVER_URL/api/dataverses/$DV_ALIAS/datasets --upload-file issue4877.json.txt` with this [issue4877.json.txt](https://github.com/IQSS/dataverse/files/2221719/issue4877.json.txt) file that contains the following:

          {
            "typeName": "subject",
            "multiple": true,
            "typeClass": "controlledVocabulary",
            "value": [
              "Social Sciences"
            ]
          },
          {
            "typeName": "keyword",
            "multiple": true,
            "typeClass": "compound",
            "value": [
              {
                "keywordValue": {
                  "typeName": "keywordValue",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "Law"
                }
              },
              {
                "keywordValue": {
                  "typeName": "keywordValue",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "Bugs"
                }
              }
            ]
          },

I get a dataset like this where the keyword "Law" gets turned into a subject:

<img width="1863" alt="screen shot 2018-07-23 at 10 29 51 pm" src="https://user-images.githubusercontent.com/21006/43113442-6a5c327a-8ec8-11e8-89ce-64d03f227fa0.png">

Weird.

**Comment by pdurbin** [comment] 2018-07-24 13:58
In b4cd129 in February 2015 which was before Dataverse 4.0 was released a method called `convertKeywordsToSubjects` was added.

The commit message was "add special processing to JsonParser to move keywords that match subject controlled vocabulary values to the subject datasetField"

The javadoc says, "Special processing of keywords and subjects. All keywords and subjects will be input from foreign formats (DDI, dcterms, etc) as keywords. As part of the parsing, we will move keywords that match subject controlled vocabulary values into the subjects datasetField."

I had added the "bug" label to this issue but it appears that this behavior was added for a reason. I'm not sure what that reason is.

**Comment by scolapasta** [comment] 2018-07-24 15:33
@mdmADA @pdurbin  well, it's not really a bug as it was added purposefully. This was due to wanting to add subjects to datasets that were being migrated from DVN 3.x. Since we've removed that migration route, we probably can remove it.

**Comment by pdurbin** [comment] 2018-07-24 15:45
@scolapasta thanks.

@mdmADA to provide a bit more context, subjects were not required in DVN 3 but as you probably know, they are required in Dataverse 4.

**Comment by mdmADA** [comment] 2018-07-24 23:20
Ok, thank you for the information.

Something to be aware of for API users, I guess. If that functionality could possibly still be needed in the future for those who may still be on version 3.x, setting a flag instead of removing it completely might be an idea.

**Comment by pdurbin** [comment] 2018-07-25 00:07
@mdmADA sure. Now that you have more information, what would you consider the "definition of done" to be for this issue? Document the behavior in the API Guide? Add a flag to enable (or disable) the behavior? Something else? :smile:

**Comment by mdmADA** [comment] 2018-07-25 00:19
I personally would prefer the functionality be changed by adding a flag or removing it - whichever the Dataverse team decides is the best approach.

People tend not to read documentation in its entirety. And if a user is using the API to create many datasets, going in and having to change subjects back to keywords really would not be fun so changing/removing the functionality is, IMO, the "definition of done".

Thanks!

**Comment by pdurbin** [comment] 2018-07-25 20:57
We made a decision at sprint planning today to simply delete the functionality rather than adding a flag.

**Comment by pdurbin** [comment] 2018-07-26 19:19
Pull request #4900 looks good so I moved it to QA at https://waffle.io/IQSS/dataverse

**Closed** 2018-07-27 21:33 UTC
