### ISSUE TITLE
Support for stata 14

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2883] opened 2016-01-21 14:33 UTC

**Comment by pdurbin** [comment] 2016-01-21 14:35
This seems to be a duplicate of #2301

**Comment by sbarbosadataverse** [comment] 2016-01-21 14:41
Thanks, Phil! I searched but nothing came up!


On Thu, Jan 21, 2016 at 9:35 AM, Philip Durbin <notifications@github.com>
wrote:

> This seems to be a duplicate of #2301
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2301&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=Jldt_AA61xrS7ZGxrbYjKeutH5GJik4oTrLeE8vaq0g&s=i-tTJw5VNcq3qnBUkm6rhJ-W5nTN9ye_7UqUj7d1Klw&e=>
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2883-23issuecomment-2D173586476&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=Jldt_AA61xrS7ZGxrbYjKeutH5GJik4oTrLeE8vaq0g&s=URoEwKIefgJSQwnCKa-_UGq2lM0nYFYRmBJp5Ghna3M&e=>
> .
>



-- 
Sonia Barbosa
Manager of Data Curation, IQSS Dataverse Network
Manager of the Murray Research Archive, IQSS
Data Science
Harvard University

Dataverse 4.0 is now available for use!
http://dataverse.harvard.edu

All test dataverses should be created  in 4.0 Demo!
http://dataverse-demo.iq.harvard.edu/

Join our Dataverse Community!
https://groups.google.com/forum/#!forum/dataverse-community

**Closed** 2016-01-21 14:41 UTC
Labels: Component: File Upload & Handling, Priority: Medium, Type: Feature, Type: Suggestion

**Comment by wbuchanan** [comment] 2016-01-25 10:08
@pdurbin Not sure how well/easily things would fit into your project, but I started working on building out a more comprehensive .dta reader with handling for the different .dta file formats.  It is still a while away from being completed, but I classes to handle the individual tag elements and have been trying to create a consistent interface (with regards to the structure/objects in the files).  I have plans to work on a .dta writer as well and ultimately my goal is to build out something like a smaller version of StatTransfer with the capability to use SQL type methods for managing/merging data across file formats.

You can see more at https://github.com/wbuchanan/data-transfer.

**Comment by pdurbin** [comment] 2016-01-25 14:04
@wbuchanan interesting! Thanks for letting us know about your project! I left a comment for @landreev especially (who works on Stata ingest) at https://github.com/IQSS/dataverse/issues/2331#issuecomment-174517288
