### ISSUE TITLE
Metadata Topic Classification as Facets: where we display these two fields as concatenated so we would show the Term and the Vocabulary in parentheses. Ex. 1 (Generations)

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2160] opened 2015-05-13 17:31 UTC
Eleni spoke with Phil about this and explained to him that this is expected UI behavior since we are just showing the Topic Classification Term field and not also showing the Topic Classification Vocabulary field right next to it which provides some context as to what the "1" means.

One solution would be to have this show like it did in 3,6 where we display these two fields as concatenated so we would show the Term and the Vocabulary in parentheses. Ex. 1 (Generations). This will need to be a ticket in Github for development to review and see if it can be implemented.

**Comment by pdurbin** [comment] 2015-09-17 19:42
@scolapasta just put this in 4.3 but I assume that's for an estimate of how much work this will be, not necessarily a working implementation. I'm not sure this is an easy fix.

**Comment by pdurbin** [comment] 2015-10-30 15:29
I don't have an estimate yet but in looking at this issue I have a couple questions:

## Question 1

I can see that https://dataverse.harvard.edu/dataverse/mra has the "Topic Classification Term" facet enabled but what other dataverses have this facet enabled? Screenshot below.

![murray_research_archive_dataverse_-_2015-10-30_11 14 54](https://cloud.githubusercontent.com/assets/21006/10849522/79e899f6-7ef7-11e5-94e2-01c031b6871d.png)

## Question 2

How do dataverses other than the Murray us the "Topic Classification" metadata field? Can I have some links to some example datasets?

Here's how the Murray uses the "Topic Classification" metadata field:

![screen shot 2015-10-30 at 11 17 18 am](https://cloud.githubusercontent.com/assets/21006/10849606/e6fa34b4-7ef7-11e5-9254-d6d77a1128f5.png)

At http://dx.doi.org/10.7910/DVN/28530 here's how BARI uses the "Topic Classification" metadata field:

![methane_emissions_from_natural_gas_infrastructure_and_use_in_the_urban_region_of_boston _massachusetts_-_boston_regional_atmospheric_measurement_network_dataverse_-_2015-10-30_11 19 14](https://cloud.githubusercontent.com/assets/21006/10849739/7998eb58-7ef8-11e5-9536-79bc8ffd4da6.png)

## Developer Comments

I don't think we want any special cases of Murray in the code. I'm not sure how I would distinguish between the "1" used in the Murray vs. "Atmospheric Science" used by BARI.

To reproduce this locally, it's handy to import the DDI file from http://hdl.handle.net/1902.1/00012 that's part of this commit: 49dd844.

/cc @sbarbosadataverse @posixeleni @scolapasta @suenjedt

**Comment by mcrosas** [comment] 2015-10-30 15:42
This might be more a curation question for @sbarbosadataverse and @posixeleni before we figure out if there are code implications.

**Comment by mcrosas** [comment] 2015-10-30 15:44
OK, missed the beginning of the issue. Of course, this is not a special case for Murray code. This for any topic classification.

**Comment by pdurbin** [comment] 2015-10-30 15:55
> I can see that https://dataverse.harvard.edu/dataverse/mra has the "Topic Classification Term" facet enabled but what other dataverses have this facet enabled?

@kcondon provided me with the list below! Thanks!

- https://dataverse.harvard.edu/dataverse/AgEconSearch
- https://dataverse.harvard.edu/dataverse/Avahan
- https://dataverse.harvard.edu/dataverse/Botswana
- https://dataverse.harvard.edu/dataverse/CIAT
- https://dataverse.harvard.edu/dataverse/CMMR
- https://dataverse.harvard.edu/dataverse/Cameroon
- https://dataverse.harvard.edu/dataverse/ChaanNg
- https://dataverse.harvard.edu/dataverse/EQR-UCLA
- https://dataverse.harvard.edu/dataverse/HBGDki
- https://dataverse.harvard.edu/dataverse/HCPDS
- https://dataverse.harvard.edu/dataverse/IFPRI
- https://dataverse.harvard.edu/dataverse/Media_Advocacy
- https://dataverse.harvard.edu/dataverse/NEEO
- https://dataverse.harvard.edu/dataverse/OD
- https://dataverse.harvard.edu/dataverse/SLPs_Avahan
- https://dataverse.harvard.edu/dataverse/SOCRATESJOURNAL
- https://dataverse.harvard.edu/dataverse/STI_Mne
- https://dataverse.harvard.edu/dataverse/SocSciBib
- https://dataverse.harvard.edu/dataverse/aas
- https://dataverse.harvard.edu/dataverse/adavis
- https://dataverse.harvard.edu/dataverse/antislaverypetitionsma
- https://dataverse.harvard.edu/dataverse/bmgf
- https://dataverse.harvard.edu/dataverse/cces
- https://dataverse.harvard.edu/dataverse/cnv-sabre
- https://dataverse.harvard.edu/dataverse/darmc
- https://dataverse.harvard.edu/dataverse/dataconnect
- https://dataverse.harvard.edu/dataverse/datapass
- https://dataverse.harvard.edu/dataverse/digaaidataverse
- https://dataverse.harvard.edu/dataverse/diw
- https://dataverse.harvard.edu/dataverse/dmgibler
- https://dataverse.harvard.edu/dataverse/economics
- https://dataverse.harvard.edu/dataverse/georgetownlaw
- https://dataverse.harvard.edu/dataverse/glewis
- https://dataverse.harvard.edu/dataverse/govdept
- https://dataverse.harvard.edu/dataverse/hrs
- https://dataverse.harvard.edu/dataverse/icpsr
- https://dataverse.harvard.edu/dataverse/icraf
- https://dataverse.harvard.edu/dataverse/ih-ess
- https://dataverse.harvard.edu/dataverse/ipcd
- https://dataverse.harvard.edu/dataverse/jhuber
- https://dataverse.harvard.edu/dataverse/jop
- https://dataverse.harvard.edu/dataverse/king
- https://dataverse.harvard.edu/dataverse/map
- https://dataverse.harvard.edu/dataverse/migration
- https://dataverse.harvard.edu/dataverse/mra
- https://dataverse.harvard.edu/dataverse/nyulawreview
- https://dataverse.harvard.edu/dataverse/odp
- https://dataverse.harvard.edu/dataverse/odum
- https://dataverse.harvard.edu/dataverse/poole
- https://dataverse.harvard.edu/dataverse/romanwarships
- https://dataverse.harvard.edu/dataverse/roper
- https://dataverse.harvard.edu/dataverse/rtownsend
- https://dataverse.harvard.edu/dataverse/searle
- https://dataverse.harvard.edu/dataverse/socialsciencercts
- https://dataverse.harvard.edu/dataverse/ssda_ucla
- https://dataverse.harvard.edu/dataverse/technology_science
- https://dataverse.harvard.edu/dataverse/tiversen
- https://dataverse.harvard.edu/dataverse/tse
- https://dataverse.harvard.edu/dataverse/umasspoll
- https://dataverse.harvard.edu/dataverse/vanv
- https://dataverse.harvard.edu/dataverse/wfhn
- https://dataverse.harvard.edu/dataverse/worldhistorical

**Comment by pdurbin** [comment] 2015-10-30 18:03
@scolapasta in 03cc7eb I started exploring the idea of turning "1" into "1 (Generations)" but I hit a roadblock on how to get the data out. Probably you or @sekmiller will have a better idea of where the data is so I'm giving this to you to give me some hints if you still want to go down that path. Please check out that commit and let me know what you think.

Otherwise, it's potentially a curation issue if the Murray dataverse is using the "Topic Classification" metadata field in some suboptimal way. Here's the current help text:

- **Topic Classification**: The classification field indicates the broad important topic(s) and subjects that the data cover. Library of Congress subject terms may be used here.
  - **Term**: Topic or Subject term that is relevant to this Dataset
  - **Vocabulary**: For the specification of the keyword controlled vocabulary in use, such as LCSH, MeSH, or others.
  - **Vocabulary URL**: Specifies the URL location for the full controlled vocabulary

**Comment by pdurbin** [comment] 2015-11-02 21:41
@scolapasta and I met and he explained what to do. In 5763950 I pushed a fix. Here's the javadoc:

    /**
     * If the "Topic Classification" has a "Vocabulary", return both the "Term"
     * and the "Vocabulary" with the latter in parentheses. For example, the
     * Murray Research Archive uses "1 (Generations)" and "yes (Follow-up
     * permitted)".
     */
    private String getTopicClassificationTermOrTermAndVocabulary(...

I tried to figure out a way to write a unit test for this but I'm not sure how because there's so much reliance on the relationships between the entity (database) objects.

Passing to QA. I think this is what people want. The javadoc above explains the new logic.

**Comment by kcondon** [comment] 2015-11-16 21:06
@pdurbin Weird. When I pushed to an instance running a copy of production db, do not see correct behavior for Murray dv.

**Comment by kcondon** [comment] 2015-11-16 21:45
Ok, found out this requires reindexing to work. New ds will work.

**Comment by kcondon** [comment] 2015-11-17 16:58
This also worked on copy of production db after reindex for Murray. Closing.

**Closed by kcondon** 2015-11-17 16:58 UTC
Labels: Component: UX & Upgrade, Priority: Medium, Status: QA, Type: Suggestion

**Comment by pdurbin** [comment] 2015-12-16 22:05
Now that this is in production, the "Topic Classification Term" term in [the MRA](https://dataverse.harvard.edu/dataverse/mra) looks nice (compare with https://github.com/IQSS/dataverse/issues/2160#issuecomment-152556315 ):

![murray_research_archive_dataverse_-_2015-12-16_17 02 02](https://cloud.githubusercontent.com/assets/21006/11855240/03472cc8-a417-11e5-9304-182eb5e1a52f.png)
