### ISSUE TITLE
Internationalization - Terms of Use

### ISSUE THREAD

**Issue by JayanthyChengan** [IQSS/dataverse#5303] opened 2018-11-09 20:24 UTC
Requirement for internaionalization:
terms of use - 

![image](https://user-images.githubusercontent.com/12862735/48286367-6728eb00-e433-11e8-9feb-534000c83e6a.png)

**Comment by pdurbin** [comment] 2018-11-13 17:11
@JayanthyChengan thanks for pull request #5304 

I took a quick look and the first thing that struck me is that you are changing how "General Terms of Use" is configured in the application. We've always configured it with the ":ApplicationTermsOfUse" database setting like this:

![screen shot 2018-11-13 at 12 04 00 pm](https://user-images.githubusercontent.com/21006/48429975-3c44dc80-e73c-11e8-99bf-0f2f89090dd1.png)

Thanks from http://guides.dataverse.org/en/4.9.4/installation/config.html#applicationtermsofuse and I believe #2669 was recently fixed by pull request #5269, by the way.

Please edit doc/sphinx-guides/source/installation/config.rst in your pull request to remove the old way and add the new way to set General Terms of Use.

Also, while you're on that branch, please take a look at the preferred placement of curly braces at http://guides.dataverse.org/en/4.9.4/developers/coding-style.html#braces-placement . In Java it's valid to leave out the braces in the following code...

        if(appTermsOfUse != null)
            return appTermsOfUse;
        else
            return saneDefaultForAppTermsOfUse;

... but we prefer to keep them in like this:

        if (appTermsOfUse != null) {
            return appTermsOfUse;
        } else {
            return saneDefaultForAppTermsOfUse;
        }

If you reformat the lines you changed as advised at http://guides.dataverse.org/en/4.9.4/developers/coding-style.html#format-code-you-changed-with-netbeans Netbeans will add the curly braces in for you automatically.

**Comment by JayanthyChengan** [comment] 2018-11-13 20:41
@pdurbin - updated the docs.  I noticed that in this approach, by default, any new dataverse installation will display the "Dataverse General Terms of Use" from termsofuse.properties instead of "There are no Terms of Use for this Dataverse installation".  Is that ok? , if not , how can we design?

**Comment by pdurbin** [comment] 2018-11-14 17:54
@kcondon and I discussed this issue after standup and agreed that the out-of-the-box settings should be the same. That is to say, "General Terms of Use" on the Sign Up page should continue to show "There are no Terms of Use for this Dataverse installation." I attempted to implement this in f09e897 but heads up to @JayanthyChengan that I had trouble following the docs and ended up fixing what I assume is a typo. The files should go in the path for "dataverse.lang.directory", right?

@kcondon something else that occurs to me is that we should add a file to docs/release-notes (#5284) once we're sure the code is working as intended. Unless installations put their General Terms of Use in the new location (on the filesystem instead of in the database) they won't be displayed.

**Comment by JayanthyChengan** [comment] 2018-11-14 17:59
sorry - it's typo and Yes, once the JVM option for "dataverse.lang.directory" is specified, all the property files should be saved under it.

Thanks to all.

**Comment by scolapasta** [comment] 2018-11-14 21:56
@JayanthyChengan @pdurbin @kcondon  @djbrooke 
I'm a little torn on this one.

On the one hand, moving the terms of use out of the setting makes sense since it's displayed text and generally displayed text is on the bundles. 

On the other hand, all the other displayed text is not really text that an installation configures. Yes, an installation choses their language selections and metadata blocks, but once they do, they should be able to use the out of the box bundles and not have to change them. 

In other words, the text that we have in the bundles isn't really user input data. The terms of use ae user input, where the user is a installation admin.

Additionally if this were a column in the db, such that to add a new language we would need to add a new column (i.e. change the db structure), that would definitely be not scalable. But in the case of terms of use, adding a new language could be accomplished by adding a new row to the setting table (imagine one setting per language). This is doable by API. Changing a bundle is not.

Thoughts from others?

**Comment by JayanthyChengan** [comment] 2018-11-16 20:14
@scolapasta I will follow the above mentioned design and submit it soon.

**Comment by pdurbin** [comment] 2019-03-20 03:17
@JayanthyChengan head up that pull request #5304 has merge conflicts.

**Comment by JayanthyChengan** [comment] 2019-07-19 19:32
@scolapasta @pdurbin - as mentioned in above comment([link](https://github.com/IQSS/dataverse/issues/5303#issuecomment-439196523)),  I added new column(lang) to the setting table.  

Now Setting table got three columns (name, content, lang) and "name" as primary key

When I add new row (:ApplicationTermsOfUse , "...." , "fr" ) using curl command, I get the below exception, 

org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "setting_pkey"

So, modified primary key 

ALTER TABLE ONLY setting
    ADD CONSTRAINT setting_pkey PRIMARY KEY (name,lang);

Please review the PR https://github.com/IQSS/dataverse/pull/6042
Thanks

**Closed** 2020-01-24 04:53 UTC
