### ISSUE TITLE
Featured Dataverse: Allow dv admin to select from all children, not just direct children.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#802] opened 2014-08-04 20:08 UTC
Spoke with Gustavo and the decision to only allow direct child dv's to be featured needs to be revisited. We should support all child dv's and find another solution to the performance issue.

**Comment by eaquigley** [comment] 2016-03-30 16:54
Closing as a duplicate of #752. This functionality is listed in that ticket as one to improve.

**Closed by eaquigley** 2016-03-30 16:54 UTC
Labels: Component: Search/Browse, Component: UX & UI, Status: Triaged, Type: Bug
