### ISSUE TITLE
Linked Dataverse: Contents of linked objects are not searchable and do not show up as cards.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1366] opened 2015-01-22 00:02 UTC
A requirement for linked dv/ds was to show the linked object and all it's contents as cards and make them searchable in the host dv. Currently only the linked object itself appears, though files are searchable and show up as cards.

**Comment by pdurbin** [comment] 2015-01-23 20:16
@sekmiller implemented the [dvLinkingService.findLinkingDataverses](https://github.com/IQSS/dataverse/blob/16e23f53ede26c348fd14bb52fabf084ff30af5f/src/main/java/edu/harvard/iq/dataverse/IndexServiceBean.java) code to support indexing so I think he'd be a better fit for this ticket.

Also, I suspect that this is yet another tree traversal problem similar to the ones I listed at https://github.com/IQSS/dataverse/issues/182#issuecomment-64119983

**Comment by pdurbin** [comment] 2015-02-07 17:43
In addition to the trickiness of tree traversal, in my mind this ticket represents the need to switch away from an indexing operation of a dataverse being for **just that dataverse**. Rather, we need to change the operation (or introduce a new operation) to handle re-indexing off **all of the content of that dataverse**, including sub dataverses and datasets. I suppose it also needs to handing sub dataverses and datasets of linked dataverses. And files of linked datasets? It's complicated. Here's a tree start at from https://github.com/IQSS/dataverse/issues/752#issuecomment-64442551 and it doesn't even have links. #752 is the ticket where it is well-argued we must embrace the tree-like nature of Dataverse 4.0 and write efficient methods for tree traversal.

![tree](https://cloud.githubusercontent.com/assets/21006/6093043/bb4e1c10-aec6-11e4-8179-3d3da856d785.png)

**Comment by eaquigley** [comment] 2015-02-24 19:11
@pdurbin @ekraffmiller @scolapasta will meet and discuss how to do this. we need something for 4.0.

**Comment by scolapasta** [comment] 2015-03-17 18:25
We are deferring this from 4.0. For Data-pass and other dvs that need it, we will manually link the datasets.

**Comment by pdurbin** [comment] 2015-04-02 20:03
I'm moving this ticket to QA and the current milestone (beta 15) because I believe I've fixed this in #1852.

**Comment by sbarbosadataverse** [comment] 2015-04-09 19:30
checked along with 1852

**Comment by pdurbin** [comment] 2015-04-10 18:45
@sbarbosadataverse I'm going to re-open this ticket until I've confirmed that the `curl` command mentioned at https://github.com/IQSS/dataverse/issues/1852#issuecomment-89027304 was run during testing. The thing about the "Change 'link dataverse' feature to be powered by Saved Search" change developed in #1852 is that it's **not** fully automatic. It requires command-line access to the server to kick off the curl command. This makes it hard to fully test!

**Closed** 2016-01-12 19:05 UTC
Labels: Component: UX & Upgrade, Priority: Medium, Status: QA, Type: Bug
