### ISSUE TITLE
Improve reporting of ingest failures

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#3769] opened 2017-04-12 17:32 UTC
These are the errors that appear when users mouse over the red triangles indicating ingest failures. 

Some immediate improvements to make: 

- duplicate these with notifications sent to the owner (possibly: keep the mouseover messages brief; send a more detailed message in the notification)
- add a "dismiss" checkbox, for the owner to be able to make the red mark disappear from the page;
- make the messages more detailed/provide more information. for example: instead of reporting the first unparseable line in a CSV file, report all (or first 10? - some limit would help). make sure we always provide *some* error message - even if it's "the file can't be parsed at all, ingest can't open the file, no further information is available".

**Comment by pdurbin** [comment] 2017-04-12 17:36
There's also the fact that the icon used for ingest failure seems to give wrong impression to the user, as if they did something wrong, that Dataverse is angry with them. Here's a representative quote:

> "That’s exactly what’s happening – the file uploads, then takes a very long time to go through the ingest process (assuming because it’s a large dataset), and eventually gives me a big angry red triangle that says “Tabular Data Ingest Failed”." -- https://help.hmdc.harvard.edu/Ticket/Display.html?id=215748#txn-4279663

TODO: insert screenshot here

Maybe we could come up with a friendlier icon that isn't angry and red. 😄

**Comment by landreev** [comment] 2017-04-12 17:48
Well, it's red and angry specifically to get their attention. But once they mouse over, we can definitely do a better job explaining what happened; and, among other things, communicate more clearly that this is not a fatal condition, that the file will still be available to their users; and, perhaps, that it's "not their fault" too.

**Comment by oscardssmith** [comment] 2017-07-05 15:14
Some of the proposed changes here would be quite easy, others much harder. Reporting all failures rather than the first will be very difficult, because it would require being able to parse past the broken bit, which in many cases may not work. We could make the error messages nicer though, although with the new parser (see #3767), all errors in the parser will (hopefully) be the user's fault for supplying a broken CSV.

**Comment by jggautier** [comment] 2017-08-08 14:19
I like the idea of sending a more detailed or less technical message in the notification, which could include a link to a guide in the documentation (if one needs to be written after all of the great CSV ingest work that's been done so far).

**Comment by TaniaSchlatter** [comment] 2017-09-07 16:24
There's a that came in through RT recently about a user instance of this issue: https://help.hmdc.harvard.edu/Ticket/Display.html?id=252818

**Comment by pdurbin** [comment] 2022-09-30 02:21
We made some improvements in this PR:

- #8271

@adam3smith what do you think? Better? Needs more work? I see you have this down as a papercut. 😄

**Comment by adam3smith** [comment] 2022-09-30 02:31
Yeah, I've been noticing the improved messages coming through -- I think in terms of messages, this is about as good as it's going to get, thanks! (Obviously it'd also be great to fix at least some of the causes of ingest failure, but that's on different issues)

**Comment by cmbz** [comment] 2024-08-20 15:25
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Closed by cmbz** 2024-08-20 15:25 UTC
Labels: UX & UI: Design, Type: Suggestion, Feature: File Upload & Handling, Feature: Messaging
