### ISSUE TITLE
MyData: Clicking on draft version of dataset takes user to published version

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#6834] opened 2020-04-17 10:05 UTC
If a published dataset has a draft version and it appears in MyData, clicking on that takes the user to the published version instead.

**Comment by mheppler** [comment] 2020-06-08 11:41
@kcondon, @djbrooke this appears to be a duplicate of **Draft Version URL Problem in "My Data" #3038**.

**Comment by djbrooke** [comment] 2020-06-08 12:39
Thanks @mheppler. I'd still like to work on #5696 as a general rearchitecture, but thanks for the quick fix in the PR #6969

**Comment by mheppler** [comment] 2020-06-08 12:42
@djbrooke I agree 100%, that PR is a minor repair on bridge to that effort. Closing this issue a duplicate.

**Closed by mheppler** 2020-06-08 12:42 UTC

**Comment by kcondon** [comment] 2020-06-08 15:28
@mheppler @djbrooke Yes, it looks like a duplicate.
