### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by pengchengluo** [IQSS/dataverse#2753] opened 2015-11-23 02:58 UTC
When I start glassfish, the log report error as following:

The web application [] created a ThreadLocal with key of type [java.lang.ThreadLocal](value [java.lang.ThreadLocal@3b7fb45f]) and a value of type [org.glassfish.admingui.theme.AdminguiThemeContext](value [org.glassfish.admingui.theme.AdminguiThemeContext@697373da]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.]]

When glassfish is running, the log report error as following:

WELD-000225: Bean store leak was detected during org.jboss.weld.context.http.HttpRequestContextImpl association: org.apache.catalina.connector.RequestFacade@5935b530]]

Eventually, the memory is exhausted.

How can I solve this problem? Thanks very much!

**Comment by jri-sp** [comment] 2016-10-12 07:24
Hi,

I think I have same issue here... 

I have to restart Glassfish every morning due to memory consumption (WebUI is not responding), and I got same messages in the logs.

I don't think my server is too small, there is two Glassfish with Xmx up to 4Go for 100 visitors a day.
It's more like the Java memory is filling up little by little (sometimes with no visits) before Glassfish crash.

**Comment by pdurbin** [comment] 2016-10-15 14:08
@pengchengluo do you have to restart Glassfish every morning too? I don't believe we have this problem at https://dataverse.harvard.edu but we do have some sort of restart script in place to detect if Glassfish is dead or not responding or whatever. I don't believe it gets triggered very often.

If @pengchengluo or @jri-sp or others can suggest how we can reproduce this problem on a test box, please advise! Having to restart Glassfish every morning is pretty extreme!

**Comment by pengchengluo** [comment] 2016-10-16 12:15
I restarted our glassfish and find the first error doesn't exist but the second error still exist.

We don't restart glassfish every morning. But the web page responding become longer over time. So restarting the glassfish every week is necessary.

**Comment by pdurbin** [comment] 2016-11-16 18:24
@pengchengluo we see above that @jri-sp said he has two Glassfish with Xmx at 4 GB. Can you provide any details about the amount of memory in your installation?

We don't have these problems on https://demo.dataverse.org (running v. 4.5.1 build 49-7e5e8c9) has 64 GB of memory and here's how the JVM options look when Glassfish starts:

```
[pdurbin@dataverse-demo ~]$ grep -i 'JVM invocation' /usr/local/glassfish4/glassfish/domains/domain1/logs/server.log_2016-09-02T21-50-17 -A82 -B2

[2016-08-24T16:08:34.617-0400] [] [INFO] [NCLS-GFLAUNCHER-00005] [javax.enterprise.launcher] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1472069314617] [levelValue: 800] [[
  JVM invocation command line:
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.101-3.b13.el6_8.x86_64/bin/java
-cp
/usr/local/glassfish4/glassfish/modules/glassfish.jar
-XX:+UnlockDiagnosticVMOptions
-XX:NewRatio=2
-XX:+UseG1GC
-XX:MaxPermSize=512m
-XX:PermSize=256m
-Xmx24159m
-server
-javaagent:/usr/local/glassfish4/newrelic/newrelic.jar
-javaagent:/usr/local/glassfish4/glassfish/lib/monitor/flashlight-agent.jar
-Djavax.xml.accessExternalSchema=all
-Djavax.net.ssl.trustStore=/usr/local/glassfish4/glassfish/domains/domain1/config/cacerts.jks
-Ddataverse.siteUrl=https://demo.dataverse.org
-Ddataverse.timerServer=true
-Djdk.corba.allowOutputStreamSubclass=true
-Dfelix.fileinstall.dir=/usr/local/glassfish4/glassfish/modules/autostart/
-Djavax.xml.parsers.SAXParserFactory=com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl
-Ddoi.password=apitest
-Dorg.glassfish.additionalOSGiBundlesToStart=org.apache.felix.shell,org.apache.felix.gogo.runtime,org.apache.felix.gogo.shell,org.apache.felix.gogo.command,org.apache.felix.shell.remote,org.apache.felix.fileinstall
-Dcom.sun.aas.installRoot=/usr/local/glassfish4/glassfish
-Dfelix.fileinstall.poll=5000
-Djava.endorsed.dirs=/usr/local/glassfish4/glassfish/modules/endorsed:/usr/local/glassfish4/glassfish/lib/endorsed
-Djava.security.policy=/usr/local/glassfish4/glassfish/domains/domain1/config/server.policy
-Ddataverse.rserve.host=localhost
-Dosgi.shell.telnet.maxconn=1
-Dfelix.fileinstall.bundles.startTransient=true
-Dcom.sun.enterprise.config.config_environment_factory_class=com.sun.enterprise.config.serverbeans.AppserverConfigEnvironmentFactory
-Dfelix.fileinstall.log.level=2
-Ddataverse.fqdn=demo.dataverse.org
-Ddataverse.auth.password-reset-timeout-in-minutes=60
-Ddataverse.dropbox.key=1itrou6ddxx0bsd
-Ddataverse.rserve.password=rserve
-Djavax.net.ssl.keyStore=/usr/local/glassfish4/glassfish/domains/domain1/config/keystore.jks
-Djava.security.auth.login.config=/usr/local/glassfish4/glassfish/domains/domain1/config/login.conf
-Dfelix.fileinstall.disableConfigSave=false
-Ddoi.username=apitest
-Ddataverse.rserve.port=6311
-Dfelix.fileinstall.bundles.new.start=true
-Dcom.sun.aas.instanceRoot=/usr/local/glassfish4/glassfish/domains/domain1
-Dosgi.shell.telnet.port=6666
-Dgosh.args=--nointeractive
-Dcom.sun.enterprise.security.httpsOutboundKeyAlias=demo-iq
-Dosgi.shell.telnet.ip=127.0.0.1
-Ddataverse.files.directory=/usr/local/glassfish4/glassfish/domains/domain1/files
-Ddataverse.rserve.user=rserve
-DANTLR_USE_DIRECT_CLASS_LOADING=true
-Djava.awt.headless=true
-Dcom.ctc.wstx.returnNullForDefaultNamespace=true
-Djava.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.101-3.b13.el6_8.x86_64/lib/ext:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.101-3.b13.el6_8.x86_64/jre/lib/ext:/usr/local/glassfish4/glassfish/domains/domain1/lib/ext
-Ddataverse.datadeposit.hostname=demo.dataverse.org
-Ddoi.baseurlstring=https://ezid.cdlib.org
-Djdbc.drivers=org.apache.derby.jdbc.ClientDriver
-Djava.library.path=/usr/local/glassfish4/glassfish/lib:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
com.sun.enterprise.glassfish.bootstrap.ASMain
-upgrade
false
-domaindir
/usr/local/glassfish4/glassfish/domains/domain1
-read-stdin
true
-asadmin-args
--host,,,localhost,,,--port,,,4848,,,--secure=false,,,--terse=false,,,--echo=false,,,--interactive=true,,,start-domain,,,--verbose=false,,,--watchdog=false,,,--debug=false,,,--domaindir,,,/usr/local/glassfish4/glassfish/domains,,,domain1
-domainname
domain1
-instancename
server
-type
DAS
-verbose
false
-asadmin-classpath
/usr/local/glassfish4/glassfish/lib/client/appserver-cli.jar
-debug
false
-asadmin-classname
com.sun.enterprise.admin.cli.AdminMain]]

[2016-08-24T16:08:37.668-0400] [glassfish 4.1] [INFO] [NCLS-LOGGING-00009] [javax.enterprise.logging] [tid: _ThreadID=18 _ThreadName=RunLevelControllerThread-1472069317543] [timeMillis: 1472069317668] [levelValue: 800] [[
  Running GlassFish Version: GlassFish Server Open Source Edition  4.1  (build 13)]]

[pdurbin@dataverse-demo ~]$ 
```

**Comment by donsizemore** [comment] 2016-11-16 19:12
Odum runs Glassfish in a VM with 64GB of RAM as well (VMware's maximum allowed with Fault Tolerance). We currently specify an Xmx of 48GB for Glassfish, and typically see the machine use 16-17GB actively, keep ~1.5GB free and use the rest for buffers/cache.

I've found on my test servers that the minimum Xmx needed to index our production database is around 24GB, otherwise Glassfish will run out of memory.

I hope this information helps in some way.

**Comment by pengchengluo** [comment] 2016-11-23 00:17
@pdurbin following is the JVM options.  Our server has 189 GB of memory and the dataverse version is 4.0.

 JVM invocation command line:
/usr/java/jdk1.8.0_66/bin/java
-cp
/usr/local/glassfish4/glassfish/modules/glassfish.jar
-XX:+UnlockDiagnosticVMOptions
-XX:NewRatio=2
-XX:MaxPermSize=512m
-XX:PermSize=256m
-Xmx64088m
-client
-javaagent:/usr/local/glassfish4/glassfish/lib/monitor/flashlight-agent.jar
-Djavax.xml.accessExternalSchema=all
-Djavax.net.ssl.trustStore=/usr/local/glassfish4/glassfish/domains/domain1/config/cacerts.jks
-Ddataverse.siteUrl=http://opendata.pku.edu.cn
-Djdk.corba.allowOutputStreamSubclass=true
-Dfelix.fileinstall.dir=/usr/local/glassfish4/glassfish/modules/autostart/
-Ddoi.password=[xxx]
-Djavax.xml.parsers.SAXParserFactory=com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl
-Dorg.glassfish.additionalOSGiBundlesToStart=org.apache.felix.shell,org.apache.felix.gogo.runtime,org.apache.felix.gogo.shell,org.apache.felix.gogo.command,org.apache.felix.shell.remote,org.apache.felix.fileinstall
-Dcom.sun.management.jmxremote.authenticate=false
-Dcom.sun.aas.installRoot=/usr/local/glassfish4/glassfish
-Dfelix.fileinstall.poll=5000
-Djava.security.policy=/usr/local/glassfish4/glassfish/domains/domain1/config/server.policy
-Djava.endorsed.dirs=/usr/local/glassfish4/glassfish/modules/endorsed:/usr/local/glassfish4/glassfish/lib/endorsed
-Ddataverse.rserve.host=localhost
-Dfelix.fileinstall.bundles.startTransient=true
-Dosgi.shell.telnet.maxconn=1
-Dfelix.fileinstall.log.level=2
-Dcom.sun.enterprise.config.config_environment_factory_class=com.sun.enterprise.config.serverbeans.AppserverConfigEnvironmentFactory
-Ddataverse.fqdn=[xxx.xxx.xxx.xxx]
-Ddataverse.auth.password-reset-timeout-in-minutes=60
-Ddataverse.rserve.password=rserve
-Djavax.net.ssl.keyStore=/usr/local/glassfish4/glassfish/domains/domain1/config/keystore.jks
-Dfelix.fileinstall.disableConfigSave=false
-Djava.security.auth.login.config=/usr/local/glassfish4/glassfish/domains/domain1/config/login.conf
-Dcom.sun.management.jmxremote.ssl=false
-Dcom.sun.management.jmxremote
-Ddoi.username=[xxx]
-Dcom.sun.management.jmxremote.port=8686
-Ddataverse.rserve.port=6311
-Dfelix.fileinstall.bundles.new.start=true
-Dcom.sun.aas.instanceRoot=/usr/local/glassfish4/glassfish/domains/domain1
-Dosgi.shell.telnet.port=6666
-Dgosh.args=--nointeractive
-Dcom.sun.enterprise.security.httpsOutboundKeyAlias=s1as
-Dcom.sun.management.jmxremote.local.only=false
-Dosgi.shell.telnet.ip=127.0.0.1
-Ddataverse.rserve.user=rserve
-Ddataverse.files.directory=/usr/local/glassfish4/glassfish/domains/domain1/files
-DANTLR_USE_DIRECT_CLASS_LOADING=true
-Djava.awt.headless=true
-Dcom.ctc.wstx.returnNullForDefaultNamespace=true
-Djava.ext.dirs=/usr/java/jdk1.8.0_66/lib/ext:/usr/java/jdk1.8.0_66/jre/lib/ext:/usr/local/glassfish4/glassfish/domains/domain1/lib/ext
-Ddoi.baseurlstring=https://mds.datacite.org
-Djdbc.drivers=org.apache.derby.jdbc.ClientDriver
-Djava.library.path=/usr/local/glassfish4/glassfish/lib:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
com.sun.enterprise.glassfish.bootstrap.ASMain
-upgrade
false
-domaindir
/usr/local/glassfish4/glassfish/domains/domain1
-read-stdin
true
-asadmin-args
--host,,,localhost,,,--port,,,4848,,,--secure=false,,,--terse=false,,,--echo=false,,,--interactive=true,,,start-domain,,,--verbose=false,,,--watchdog=false,,,--debug=false,,,--domaindir,,,/usr/local/glassfish4/glassfish/domains,,,domain1
-domainname
domain1
-instancename
server
-type
DAS
-verbose
false
-asadmin-classpath
/usr/local/glassfish4/glassfish/lib/client/appserver-cli.jar
-debug
false
-asadmin-classname
com.sun.enterprise.admin.cli.AdminMain

**Comment by pdurbin** [comment] 2017-06-23 13:07
@pengchengluo if you're still having trouble, please email support@dataverse.org . Thanks. I'm closing this issue.

**Closed by pdurbin** 2017-06-23 13:07 UTC
Labels: Component: Code Infrastructure, Component: Performance & Stability, Status: Triaged
