### ISSUE TITLE
Once you are in data "explore" no options to exit and get back into the dataset file page

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#1844] opened 2015-04-02 15:06 UTC
Once you hit "explore" you are taken to "Two ravens" but there are no options to get back to the study page, and two ravens doesn't open in a new window

**Comment by mheppler** [comment] 2015-04-02 15:17
This is a duplicate of #1699. @kcondon

**Comment by kcondon** [comment] 2015-04-07 17:03
Closing as a duplicate.

**Closed by kcondon** 2015-04-07 17:03 UTC
Labels: Component: UX & Upgrade, Priority: High, Status: Dev, Status: QA, Type: Feature
