### ISSUE TITLE
"File Downloader" role: should not allow users to access "unpublished" data, should not send link to user if role assigned but data unpublished

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2645] opened 2015-10-15 14:57 UTC
RT ticket: https://help.hmdc.harvard.edu/Ticket/Display.html?id=228447 

user reported he has file downloader role, but when he clicks on dataset name gets an error page.

I gave myself the same role with a non superuser account and I get the same error.

when you login you see the dataset is : draft unpublished file downloader   clearly labeled
attempting to access throws error: NOT AUTHORIZED

![image 1](https://cloud.githubusercontent.com/assets/8322346/10517621/84351358-732b-11e5-9717-b66b008b4c65.png)

![image 2](https://cloud.githubusercontent.com/assets/8322346/10517635/9a37261e-732b-11e5-85e7-5ca0dd9ff8e7.png)

**Comment by mcrosas** [comment] 2015-10-15 15:00
Changed this to Critical - needs to be fixed in the next patch.

**Comment by sbarbosadataverse** [comment] 2015-10-15 15:23
reproduced in Demo site:

<img width="1218" alt="screen shot 2015-10-15 at 11 21 59 am" src="https://cloud.githubusercontent.com/assets/8322346/10518376/1b05ec6e-732f-11e5-8df1-421e6b24004a.png">

**Comment by pdurbin** [comment] 2015-10-15 15:30
It looks like I can reproduce this on my laptop in the 4.3 branch (I'm on commit ea290e4).

Here's the "spruce" user giving access to a restricted file to the "finch" user:

![file_permissions_-_spruce_goose_-_2015-10-15_11 25 00](https://cloud.githubusercontent.com/assets/21006/10518449/812c70c6-732f-11e5-988a-27b8e64c2e6e.png)

Then "finch" logs in and clicks on either "trees.png" or "Spruce Goose" from MyData...

![screen shot 2015-10-15 at 11 26 19 am](https://cloud.githubusercontent.com/assets/21006/10518477/adcf2d30-732f-11e5-981d-12765ea1a56f.png)

... and gets an error when trying to go to http://localhost:8080/dataset.xhtml?persistentId=doi:10.5072/FK2/QBQGQG

![screen shot 2015-10-15 at 11 27 46 am](https://cloud.githubusercontent.com/assets/21006/10518521/dc171c16-732f-11e5-9cf5-46f2407df0ee.png)

**Comment by pdurbin** [comment] 2015-10-15 16:55
I pushed 8f0549a to a new branch as a proposed fix. Ideally it would be code reviewed. I'll see if @sekmiller or @raprasad or @scolapasta is available.

**Comment by pdurbin** [comment] 2015-10-15 17:24
@scolapasta I'm passing this ticket to you to review the summary of my conversation with @sekmiller (and the commit itself) at  8f0549a and decide if we should merge the fix as-is or not.

**Comment by sbarbosadataverse** [comment] 2015-10-15 18:45
@scolapasta @pdurbin 
if file downloaders shoudn't access unpublished, that needs to be made clear here too


<img width="1217" alt="screen shot 2015-10-15 at 2 44 42 pm" src="https://cloud.githubusercontent.com/assets/8322346/10524028/62a374c6-734b-11e5-98e1-dcbbdcde1dfc.png">

**Comment by sbarbosadataverse** [comment] 2015-10-15 18:58
I updated the issue title to fit the actual bug. Did I miss anything?

**Comment by eaquigley** [comment] 2015-10-15 19:34
Updated the json file for this (forget it was in json not bundle)

**Comment by pdurbin** [comment] 2015-10-15 20:08
> Updated the json file for this role description (forget it was in json not bundle)

@eaquigley please check out the comment I left on that commit you just made: https://github.com/IQSS/dataverse/commit/c8e49f2001171ae0e9baab7e9acefeb7ff5a121b . The tl;dr is that someone with the "File Downloader" role is able to download files even if they are published.

**Comment by pdurbin** [comment] 2015-10-16 13:12
@eaquigley basically, I think we should revert c8e49f2 since it misrepresents how the system actually behaves.

> I updated the issue title to fit the actual bug. Did I miss anything?

@sbarbosadataverse you changed the title to '"File Downloader" role: should not allow users to access "unpublished" data, should not send link to user if role assigned but data unpublished' which more or less makes sense but to make this more clear and actionable for a developer, let me try to express it this way:

- When the file downloader role/permission is assigned at the dataset level, rather [sending a notification with a link to a dataset that the user is unable to view](https://cloud.githubusercontent.com/assets/8322346/10518376/1b05ec6e-732f-11e5-8df1-421e6b24004a.png) ("Not Authorized"), the notification should... what? Not be sent? Not include a link? It sounds like you're saying a notification shouldn't be sent.
- When someone has the "File Downloader" role on a file, MyData currently [displays file cards with links to datasets that can not be viewed](https://cloud.githubusercontent.com/assets/8322346/10517621/84351358-732b-11e5-9717-b66b008b4c65.png) ("Not Authorized"). Rather than this, we should... provide a link to download the file? (Both @landreev and @raprasad suggested this.) Or should something else happen?

**Comment by sbarbosadataverse** [comment] 2015-10-16 13:44
Notifications should not be sent until dataset is published. Liz and I
agreed on this yesterday.

No file card should be displayed under my data/ no notification of such
dataset under mydata, until dataset is published.

File downloader active role is dependent on dataset being "published."

**Comment by sekmiller** [comment] 2015-10-16 14:36
Right now there's no mechanism by which we can delay the sending of a notification.  We can add it and then have the publish command check to see if there are pending file downloader notifications waiting to be sent.

Are there any other circumstances under which it would be appropriate/necessary to delay the sending of a notification?

**Comment by sbarbosadataverse** [comment] 2015-10-16 14:38
This case in particular. File downloader itself is for "published" data. If
admins are allowed to set this role before data are published,
notifications should not be sent. The other option is to NOT allow this
role to be set pre-publishing. I'm ok with either one.
Liz may want to chime in.

On Fri, Oct 16, 2015 at 10:36 AM, Stephen Kraffmiller <
notifications@github.com> wrote:

> Right now there's no mechanism by which we can delay the sending of a
> notification. We can add it and then have the publish command check to see
> if there are pending file downloader notifications waiting to be sent.
>
> Are there any other circumstances under which it would be
> appropriate/necessary to delay the sending of a notification?
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2645-23issuecomment-2D148734197&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=DhMAc-yOTaNwNiqOcPKllLy43SFJ7Dfsh8wk5T3KS7c&s=7SsPZ6E4-wjs6SnMd4VG5MBdKxtAPtgi5NYTzkXT5Vg&e=>
> .
>



-- 
Sonia Barbosa
Manager of Data Curation, IQSS Dataverse Network
Manager of the Murray Research Archive, IQSS
Data Science
Harvard University

Dataverse 4.0 is now available for use!
http://dataverse.harvard.edu

All test dataverses should be created  in 4.0 Demo!
http://dataverse-demo.iq.harvard.edu/

Join our Dataverse Community!
https://groups.google.com/forum/#!forum/dataverse-community

**Comment by pdurbin** [comment] 2015-10-16 14:54
> File downloader itself is for "published" data.

@sbarbosadataverse no, it's not. That's why I'm arguing that c8e49f2 should be reverted because saying that the file dowloader role only applies to published data is a misrepresentation of that role given how the code works today. I gave demos of this yesterday and explained how if you know the file id you can download unpublished files if you have the file downloader role: https://github.com/IQSS/dataverse/commit/c8e49f2001171ae0e9baab7e9acefeb7ff5a121b

**Comment by sbarbosadataverse** [comment] 2015-10-16 15:01
I understand how it's working is wrong. That's the issue. The code is
working incorrectly.

**Comment by eaquigley** [comment] 2015-10-16 17:24
@sekmiller yes, when we bring embargoed datasets in as a functionality, we would need a delayed notification sent to someone if they have "subscribed" to the dataset to let them know it has been released.

**Comment by pdurbin** [comment] 2015-10-16 18:47
> I understand how it's working is wrong. That's the issue. The code is working incorrectly.

@sbarbosadataverse I wanted to confirm with @scolapasta that the code isn't working as desired, which he did, so I created #2648 about the bug that if you know the file id and have the DownloadFile permission you can download files when they haven't been published.

**Comment by pdurbin** [comment] 2015-10-16 19:19
> When someone has the "File Downloader" role on a file, MyData currently [displays file cards with links to datasets that can not be viewed](https://cloud.githubusercontent.com/assets/8322346/10517621/84351358-732b-11e5-9717-b66b008b4c65.png) ("Not Authorized"). Rather than this, we should... provide a link to download the file? (Both @landreev and @raprasad suggested this.) Or should something else happen?

@scolapasta and I discussed this and we decided that what should happen is that MyData should not show the cards in the first place. I created a separate issue about this: #2649.

**Comment by pdurbin** [comment] 2015-10-19 20:05
> I think this ticket is getting a bit long winded and I should create tickets

@eaquigley yes, please create more issues. These are the three I've already created for this issue:

- #2648 Downloads
- #2649 MyData
- #2654 Notifications ( @eaquigley please touch base with @sekmiller about what's possible in a reasonable time frame

Some of the issues you emailed about feel like post 4.2.1 issues to me since 4.2.1 is about performance and stability. We should definitely capture the ideas, though! If an FRD is better, that's fine too. I'm giving this issue to you @eaquigley to decide how best to capture those ideas. Please pass this back to @kcondon when you're done.

**Comment by pdurbin** [comment] 2015-10-20 15:39
@eaquigley captured many ideas in a variety of issues (thanks!):

- #2653
- #2655
- #2657
- #2658
- #2659

@kcondon I'm passing this to QA to decide what to do with this issue. In my opinion, if #2654  and #2649  pass QA, that's enough to reply to the user in https://help.hmdc.harvard.edu/Ticket/Display.html?id=228447 to say that the bugs have been fixed. I'm still planning to work on #2648 for 4.2.1 but it's not really the bug reported by the user; it's a bug I discovered while poking around in this code. Since it's security-related I think it's worth looking at.

**Comment by kcondon** [comment] 2015-10-20 16:58
@pdurbin @eaquigley @scolapasta @sbarbosadataverse @sekmiller 
It appears this was the initial ticket that subsequently was broken up into other related tickets. So, it can be difficult to test and close this one unless we say the child tickets adequately represent the issues. It sounds like from various discussions that having the file card not appear incorrectly and not sending notifications prematurely are the main issues. There are two tickets for these, the ones Phil mentioned, Liz also mentioned adding some messaging. I don't know if there is a ticket for that. 
I am closing this ticket as a dupe/ parent ticket and will test the remaining notification ticket when it arrives.

**Closed by kcondon** 2015-10-20 16:58 UTC
Labels: in progress, Priority: Critical, Status: QA, Type: Bug

**Comment by pdurbin** [comment] 2016-01-13 16:00
> I pushed 8f0549a to a new branch as a proposed fix.

I'm just noting here that since we didn't go with this fix I'm deleting the branch it was in: 2645-file-downloader-view-dataset
