### ISSUE TITLE
Request access for restricted files with terms not working from the file page

### ISSUE THREAD

**Issue by PaulBoon** [IQSS/dataverse#4554] opened 2018-03-29 11:48 UTC
Request access for restricted files with  'terms of access' not working from the file page
When pushing the request button on the file page, no pup-up appears. 

This is related to issue #4251, and the fix is indeed working in 4.8.4, but it fails in 4.8.5. 
The file.xhtml in 4.8.5 does not contain <ui:include src="file-request-access-popup-fragment.xhtml">.

**Comment by pdurbin** [comment] 2018-03-29 12:05
@PaulBoon thanks for the bug report. I can definitely reproduce the bug on the demo site, which is running 4.8.4. You click and button goes gray but nothing happens:

<img width="1484" alt="screen shot 2018-03-29 at 7 58 47 am" src="https://user-images.githubusercontent.com/21006/38087842-acb9303e-3327-11e8-8506-4e54318f003d.png">

I feel like @sekmiller and I noticed this bug recently and he may have fixed it in one of the open pull requests but I'm having trouble finding it. I think you're right that a line like this is missing: `<ui:include src="file-request-access-popup-fragment.xhtml">`.

**Comment by pdurbin** [comment] 2018-03-29 12:11
@PaulBoon of course, if you have a working fix in front of you, please feel free to make a pull request!

**Comment by PaulBoon** [comment] 2018-03-29 12:18
On 4.8.4 it works, it is greyed out because you have the access you requested. 
This also works on 4.8.5, but what doesn't work its the popup you should get when there are 'terms of access'.

**Comment by PaulBoon** [comment] 2018-03-29 12:28
Have look at [https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/FK2/P10AJJ&version=2.1](https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/FK2/P10AJJ&version=2.1)
This one hat terms, and if you request it you get a popup. 

![screen shot 2018-03-29 at 14 23 11](https://user-images.githubusercontent.com/2151103/38088813-786c3ca0-335d-11e8-8a53-d6186493b8a3.png)

**Comment by pdurbin** [comment] 2018-03-29 12:32
> it is greyed out because you have the access you requested

No, it only turned grey after I clicked it. I think this establishes that it's broken in on 4.8.4 and 4.8.5.

> This one has terms, and if you request it you get a popup.

Weird.

**Comment by PaulBoon** [comment] 2018-03-29 12:50
Ok, there are two UI scenarios for this access request on the files page:

With no terms of access. You push the 'Request Access' button. Shortly a progress spinner appears, then the button is greyed out and the label is changed to 'Access Requested'. 

With terms of access. After pushing the button you should get this dialog, showing the terms and an 'Accept' button to do the request. Etc. Etc.

This works fine on the demo server (4.8.4)
On 4.8.5. we don't get the popup and therefore no 'Accept' button and cannot do a request.

**Comment by pdurbin** [comment] 2018-03-29 16:43
Ok, a couple things.

@sekmiller and I talked about this issue this morning and he did some testing on the `2438-4295-dois-for-files` branch for pull request #4350 and he's pretty sure everything is working there.  @PaulBoon do you feel like switching to that branch to test it?

Also. above I was saying that clicking the "Access Request" button didn't do anything. I thought it was broken because it went grey and became unclickable. @sekmiller said that's the indication that it worked. I expected to see a green message at the top of the page saying something like "Access has been requested". I'm going to flag this for UX attention.

**Comment by scolapasta** [comment] 2018-03-29 16:47
The button doesn't just turn grey - the text change to "Access Requested". While we may want to consider if this is enough from a UX perspective, I don't think we've received any reports from the field of this being an issue.

**Comment by pdurbin** [comment] 2018-03-29 16:49
@scolapasta ok, thanks

@PaulBoon sorry, sorry but I just talked to @sekmiller again and he said you're right. It's broken on the file page, as you reported. In the develop branch. Previously he was testing the dataset page. So if you want to make a pull request to fix it, please feel free!

**Comment by sekmiller** [comment] 2018-03-29 19:12
@PaulBoon It looks like you'll also have to add getters and setters for the fileDownloadHelper to FilePage.java

**Comment by pdurbin** [comment] 2018-07-26 18:55
I believe #4897 is a duplicate.

**Comment by djbrooke** [comment] 2018-08-15 21:02
Closing as a duplicate of #4897, which we estimated during backlog grooming today.

**Closed by djbrooke** 2018-08-15 21:02 UTC
Labels: Feature: Request Access Workflow, Status: UX & UI, Type: Bug, User Role: Guest
