### ISSUE TITLE
Spike: embed external tool in file page as a preview

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#6048] opened 2019-07-23 18:41 UTC
As a first step to get #3758 we should do a quick spike of creating an iframe on the file page and embedding an external tool (one of the previewers?) to ensure it will work as expected.

(for the spike we can even hard code the URL, as needed)

Once we have that, we can polish the logic to deal add preview mode to external tools and support for muliple previewers.

**Comment by mheppler** [comment] 2019-08-09 20:20
Created a new branch `3758-file-pg-preview` with the initial UI prototype for the new file pg Preview tab.

<img width="1166" alt="Screen Shot 2019-08-09 at 4 03 49 PM" src="https://user-images.githubusercontent.com/687227/62806458-e0d42f00-bac0-11e9-9876-8cf8888f39cb.png">

In order to investigate this feature's use of an iframe, I took the WorldMap preview popup from  file-download-button-fragment.xhtml, and moved it's contents into a new tab on file.xhtml. This confirmed the initial design, but there were other issues with usability, accessibility, security and performance, that it might still be worth exploring with demo's and testing, before we close this issue.

Having already looked into a few of those issues, I have put together a rough outline of the efforts that will left when the main development issue #3758 is picked up.

- configuration setting and render logic for external preview tools
- maintain WorldMap hard coded feature
- responsive sizing for iframe
- noframes option, appropriate role and title attributes
- mixed content?
- lazy loading and/or defering scripts?

**Comment by djbrooke** [comment] 2019-08-09 20:28
Thanks @mheppler!!! 

@scolapasta I believe the goal for this spike was to test out the technical feasibility, so it looks like we're good there. Do you (and @TaniaSchlatter from the design perspective) feel OK bringing this into the sprint starting 8/14 with the questions Mike outlined above? If so, I'll close this one out and we can move along #3758. I'll assign it to you two for now.

**Comment by TaniaSchlatter** [comment] 2019-08-09 21:41
Exciting. Thanks, Mike!

I'd like a little more info to understand the scope of some of the items on
this list before answering:

   - responsive sizing for iframe
   Q: what do we know about resizing content in an iframe? Is it possible?
   - noframes option, appropriate role and title attributes
   Qs: I assume that "noframes option" means defining what we are going to
   show to users who's browsers don't support or have disabled frames? (Side
   question – do enough browsers support <frame>? Should we be/are we using
   <iframe>?)
   - Is there a reference you know if we can use to help guide defining
   role and title attributes, or would we have to find something to use for
   best practices?
   - I assume we would want the role and title to be dynamic based on the
   type of/source of preview brought in?

   - mixed content?
   Q: what's an example of this?

   - lazy loading and/or defering scripts?
   not sure what this means in this context? How might this impact?


- Tania

**Comment by pdurbin** [comment] 2019-08-09 22:40
This seems great but I'm wondering why we didn't try to put one of the file previewers ( https://github.com/QualitativeDataRepository/dataverse-previewers ) in an iframe, as suggested by @scolapasta above. It seems like we're testing with WorldMap instead, which is not technically an external tool. Maybe it doesn't matter. I don't know. I'm happy to spin up a branch on AWS if we'd like to poke around collectively.

**Comment by scolapasta** [comment] 2019-08-12 18:54
Yes, it would be good to use one of the actual external tools for the spike before closing it out from the technical perspective. (and hopefully these previews help get the "make geo connect / world map external tools" train moving. :)

**Comment by scolapasta** [comment] 2019-08-12 21:07
After some further thought, we can save the using of an actual external tool for dev (i.e. from the technical perspective, I'm ok with what the spike accomplished).

**Closed** 2019-08-13 15:28 UTC
Labels: Small
