### ISSUE TITLE
Umlauts and formatting chars in metadata fields shown as Unicode Replacement Char

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#6675] opened 2020-02-25 11:35 UTC
When using umlauts lik äöü or formatting chars as "–" (U+2013) in metadata fields descriptions, field values etc you will see � (U+FFFD) as a replacement. See the following image as an example:

![image](https://user-images.githubusercontent.com/5468333/75243633-8be0d780-57ca-11ea-99a3-1b1dc6f202e3.png)

For reproducing, feel free to use our custom metadata block at https://jugit.fz-juelich.de/fdm/schemas/blob/master/fzj.tsv

**Comment by pdurbin** [comment] 2020-02-25 11:58
Thanks for the bug report. Related issues:

- Add Support for International Characters Across All Display Functionality #786
- Citation - Unicode + Emojis 🍔 #5020

**Comment by poikilotherm** [comment] 2020-03-04 11:24
Possibly related or maybe even a duplicate is #6717

**Comment by syats** [comment] 2022-06-21 19:35
This is still an issue, definitely an issue with Dataverse (or maybe the underlying glassfish).  But I've found a client-side workaround (see below).

After investigating, the cause seems to be that not all strings returned by Dataverse API are equally normalized. Strings with diacritics, such as Äpfel or Páginas, can be represented in two ways in UTF-8:  Normal Form C (NFC): where the characters with diacritics are a single "point" (two bytes), and Normal Form D (NFD): where they are each two characters, one representing the underlying vowel, and one with the diacritics.  Dataverse is not normalizing strings in a uniform way, which is confusing for rendering applications (the browser, terminal, etc.), as a single string is supposed to be in only one form.  I was getting the following two bytestrings in a single dataverse API reponse:

 `p\xc3\xa1ginas`    <- páginas
`ba\xcc\x81sicos`   <- básicos

As you see, the same à "Latin Small Letter A with Acute" character is represented in two different ways. The first one as `xC3 xA1` ([NFC](https://www.compart.com/en/unicode/U+00E1)) and the second as `a xCC x81` (NFD for [a](https://www.compart.com/en/unicode/U+0061) followed by [accute accent](https://www.compart.com/en/unicode/U+0301)).

**Workaround**
Is to take the responses from Dataverse as binaries, decode-them as UTF-8, normalize them, and then parsethem as you see fit. 
Here is an example in python for getting the info on a datafile:

```
import requests
import json
import unicodedata as ud

def get_info_for_datafile(persistent_id, dataverse_root, dataverse_token):
    """
     Gets info on a datafile with a given persistent identifier using Dataverse's search api
    """
    url = f"{dataverse_root}api/search"
    headers = {"X-Dataverse-key": dataverse_token}
    fq = f"publicationStatus:Draft&& filePersistentId:\"{persistent_id}\" "
    querystring = {
        "q": "*",
        "type": "file",
        "per_page": 30,
        "start": 0,
        "fq": fq
    }
    req = requests.get(url, headers=headers, params=querystring)
    b = req.raw.data
    rj = json.loads(ud.normalize('NFC', b.decode("utf-8")))

    return rj["data"]["items"][0]
```

**Comment by pdurbin** [comment] 2022-06-23 15:54
@syats thanks for the research and workaround! Definitely something we should fix.

One thought is that we could add a dataset or two with plenty of unicode characters to our "sample data" repo: https://github.com/IQSS/dataverse-sample-data

Obviously, we could also add examples to the main repo as well so we can test them regularly with unit and API tests.

**Comment by cmbz** [comment] 2024-08-20 15:20
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Closed by cmbz** 2024-08-20 15:20 UTC
Labels: UX & UI: Design, Feature: Metadata, Type: Bug
