### ISSUE TITLE
Saved search: problem when selecting destination dataverse

### ISSUE THREAD

**Issue by suenjedt** [IQSS/dataverse#1890] opened 2015-04-06 18:08 UTC
![screen shot 2015-04-06 at 13 40 23](https://cloud.githubusercontent.com/assets/7300319/7009097/e69c7eda-dc65-11e4-8aaf-8a488a0114c2.png)

**Comment by pdurbin** [comment] 2015-04-06 18:11
@suenjedt can you please elaborate on what the problem is?

**Comment by pdurbin** [comment] 2015-04-06 18:16
@suenjedt explained that the facet are not friendly enough, so as I mentioned at https://github.com/IQSS/dataverse/issues/90#issuecomment-90180966 we can use this ticket to track this.

**Comment by mheppler** [comment] 2015-04-09 16:07
Additional QA note from #1884: "UX/UI wise I did not see any warning that "files" are not linked."

**Comment by cmbz** [comment] 2024-08-26 14:19
2024/08/26: Confirm that this problem still exists, we will close if not.

**Comment by jggautier** [comment] 2024-08-26 15:15
I can't get that "Facets" field to show in the popup. Here's what I see when I both the search field and a facet to narrow search results on Harvard Dataverse and click Link, then "Link Search" to get the Link Search popup:

<img width="1474" alt="Screenshot 2024-08-26 at 10 26 55 AM" src="https://github.com/user-attachments/assets/201b104f-00ac-4048-8ec4-5b6c231c09b1">

It looks like the Facet field was removed from the popup, so there's nothing to make more friendly or easier for users to make sense of.

I think we could close this issue, and the usability of the feature (including looking into what Mike wrote about not seeing any warning that "files" are not linked") can be reviewed later, especially if we ever consider letting more types of users use this super-user only feature.

**Comment by cmbz** [comment] 2024-08-26 15:58
2024/08/26: Closing as per @jggautier's comment: https://github.com/IQSS/dataverse/issues/1890#issuecomment-2310462661

**Closed by cmbz** 2024-08-26 15:58 UTC
Labels: UX & UI: Design, Feature: Metadata, Type: Bug, Help Wanted: Code, Mentor: pdurbin, User Role: Superuser
