### ISSUE TITLE
Problems with v4.6.1 release

### ISSUE THREAD

**Issue by 4tikhonov** [IQSS/dataverse#3698] opened 2017-03-16 14:08 UTC
Hi guys,

We just tried v4.6.1 but there is something wrong with upload files functionality. It's freezing immediately after the upload but in the same time after refresh of the dataset landing page it's possible to see deposited files.

**Comment by djbrooke** [comment] 2017-03-16 14:43
Thanks for the report @4tikhonov. Is this happening with a particular type of file? We'll try to reproduce this on our demo instance.

**Comment by 4tikhonov** [comment] 2017-03-16 15:11
No, it seems to be common case for any file. I've tried to deploy it on our test server and after on my laptop with the same result.

**Comment by djbrooke** [comment] 2017-03-16 15:17
@4tikhonov - we've been unable to reproduce this one. Can you try it on demo.dataverse.org and see if you see the same behavior?

**Comment by 4tikhonov** [comment] 2017-03-16 15:24
No, it works fine in demo. Are you sure there are no changes glassfish or SOLR configuration?

**Comment by landreev** [comment] 2017-03-16 16:14
Is there anything interesting in the logs? - any error messages when this happens?

**Comment by landreev** [comment] 2017-03-16 16:19
Also, there was a similar-sounding report recently, from another remote installation: 
https://github.com/IQSS/dataverse/issues/3644

In their case, a Glassfish restart made the issue go away... So we don't really know what was causing it for them in the first place. 

(but please see the JHove configuration discussion in that ticket; as it may apply to your installation too).

**Comment by landreev** [comment] 2017-03-16 16:24
So yes, please try and restart Glassfish. 
Also, this could (in theory) be a conflict with some jsf your browser has cached from the previous version... So I would also clear the browser cache and try again. (unless you already know for the fact that it's happening for everybody, in all browsers...)

If these sophisticated techniques do not produce results, yes, let's look for any error messages in the logs and/or in the browser js error console.

**Comment by djbrooke** [comment] 2017-03-23 20:50
Hey @4tikhonov - I'm going to close this out. Please feel free to reopen or otherwise get in touch if there's a specific issue.

**Closed by djbrooke** 2017-03-23 20:50 UTC
