### ISSUE TITLE
Move guestbook up the user story

### ISSUE THREAD

**Issue by tokeefe** [IQSS/dataverse#2260] opened 2015-06-15 13:52 UTC
The ability to capture additional information about users is important to decide who should be granted access to a restricted file, or files. I propose that the Guestbook should be presented when the user requests access to restricted files, not when the user attempts to download these files.

**Comment by tokeefe** [comment] 2015-06-15 14:07
Sorry this is a duplicate of #2043

**Comment by eaquigley** [comment] 2015-09-18 20:10
Passing this ticket to QA to close since it is a duplicate of #2043.

**Comment by kcondon** [comment] 2016-01-16 12:06
Closing as duplicate

**Closed by kcondon** 2016-01-16 12:06 UTC
Labels: Status: QA
