### ISSUE TITLE
Restricted File Download: "Download (selected files)" button above files table is not properly handling restricted files

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2722] opened 2015-11-04 17:32 UTC
If I navigate to this dataset, when not logged in: https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl%3A1902.1%2F00169

and I select the restricted files and select download at the top right of the file list--because it shows up as an option and doesn't disappear when I select restricted files, it throws the attached error instead of a message saying "files can't be downloaded see terms of use"

<img width="1708" alt="screen shot 2015-11-04 at 12 29 50 pm" src="https://cloud.githubusercontent.com/assets/8322346/10946365/e9ad28dc-82ef-11e5-93f3-f700c0ca0550.png">

Additionally, the Terms of Use are popping up which should not be happening.

**Comment by pdurbin** [comment] 2015-11-04 20:15
This may be a duplicate of #2719.

**Comment by landreev** [comment] 2015-11-04 21:25
No, I don't think this has anything to do/in common with #2719.

**Comment by eaquigley** [comment] 2016-01-05 18:46
@sbarbosadataverse do you mind trying this again and seeing if it is still happening? i believe this was before we made changes to the dataset page. thanks!

**Comment by sbarbosadataverse** [comment] 2016-01-05 18:48
sure will!

On Tue, Jan 5, 2016 at 1:46 PM, Elizabeth Quigley <notifications@github.com>
wrote:

> @sbarbosadataverse
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sbarbosadataverse&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=MiIxyiKP2HxgQiNhstxu7jV31uzeb2TEXpb5_UVb124&s=JIhoDF2r9RuoUjmRuJlUuyw_opMht1lMjxLqbDY5HSM&e=>
> do you mind trying this again and seeing if it is still happening? i
> believe this was before we made changes to the dataset page. thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2722-23issuecomment-2D169094044&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=MiIxyiKP2HxgQiNhstxu7jV31uzeb2TEXpb5_UVb124&s=mrulFo31z_w7Uzjiv-vvmGXxsy65Hfa5QEcahjTLkjE&e=>
> .
>



-- 
Sonia Barbosa
Manager of Data Curation, IQSS Dataverse Network
Manager of the Murray Research Archive, IQSS
Data Science
Harvard University

Dataverse 4.0 is now available for use!
http://dataverse.harvard.edu

All test dataverses should be created  in 4.0 Demo!
http://dataverse-demo.iq.harvard.edu/

Join our Dataverse Community!
https://groups.google.com/forum/#!forum/dataverse-community

**Comment by pdurbin** [comment] 2016-01-05 18:51
This is still happening. For example: https://dataverse.harvard.edu/api/access/datafiles/104548

**Comment by sbarbosadataverse** [comment] 2016-01-05 18:52
@eaquigley just tested and still happens.
The "download" option is still available on the top of the files list, when not logged on, and select a "Restricted" file that doesn't allow "request access to data"

Glass fish error shows up after you see the "murray terms" of agreement and of course, you shouldn't even get that far

**Comment by eaquigley** [comment] 2016-01-05 18:52
@sbarbosadataverse ah! not logged in is the account state for this. adding that to the original issue text. thanks!

**Comment by sbarbosadataverse** [comment] 2016-02-02 18:26
@scolapasta @mheppler 
This needs to be modified:
The other bug described by Tim (Brain Genomics Dataverse)

1. Open a private browsing tab
2. Navigate to
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/25833

3. Click the checkbox next to a restricted file.
4. Click the Download button (not the Request Access button)

Expected Result:
User is not authenticated and will not be presented with the Guestbook. The
user should be instructed to click on the Request Access button, or the
Download button should not be present.

Actual Result:
User is presented with the Guestbook. The user can fill out the form and
submit. The server responds with a 403 Forbidden, but the Guestbook entry
is still saved.

**Comment by mheppler** [comment] 2016-02-02 21:49
OK, to summarize, as I understand it.

The "Download" button at the top of the files table on the dataset page, which is intended for downloading "selected files", is not properly handling the use case for restricted files being selected.

**Comment by sekmiller** [comment] 2016-02-08 16:30
Based on discussions with Liz and Gustavo I have implemented the following:

If the user selects only files that are restricted he will be shown a popup saying that none of the selected can be downloaded.  If the dataset allows request access that will be noted in the popup.

If the user selects both files that he can and cannot download, he will be shown a popup which lists by name those files that cannot be downloaded with an option to continue to download those files for which he does have permission or to cancel.

If he chooses to continue the guestbook/terms will be shown next or if not required the download of permitted files will continue directly.

**Comment by sekmiller** [comment] 2016-02-08 16:33
@eaquigley can you review the bundle and make changes or pass to Kevin.

**Comment by eaquigley** [comment] 2016-02-08 17:05
@sekmiller can do. could you comment on the pull request for this feature with this issue # so its easier to find. thanks!

**Comment by eaquigley** [comment] 2016-02-08 21:27
text updated in the bundle. passing to @kcondon. could i get another build on dataverse-internal to see how the text looks in the UI? thanks!

**Comment by kcondon** [comment] 2016-02-08 21:50
OK, popups are correct except in the case where you want to download the unrestricted files of those selected, they don't actually download.

**Comment by eaquigley** [comment] 2016-02-09 16:38
Had @sbarbosadataverse try out this new workflow. Everything looks good to her except for how difficult it is to identify the names of the restricted files that won't be downloaded. @sbarbosadataverse also stated that no matter the # of restricted files selected, all names need to appear either in a column style or the way it currently is with more formatting (like: File 1, File 2, File 3) and a way for them to stand out more. 

@sekmiller @scolapasta @kcondon @mheppler

**Comment by sekmiller** [comment] 2016-02-09 17:07
I have formatted the requested restricted files as a list for readability.

The code has been pushed to the branch.

**Comment by kcondon** [comment] 2016-02-09 18:56
Works as described, closing.

**Closed by kcondon** 2016-02-09 18:56 UTC
Labels: Component: File Upload & Handling, Component: Permissions, Component: UX & UI, Priority: Critical, Status: Triaged, Type: Bug
