### ISSUE TITLE
Dataset Explore Data + Guestbook/Terms - TwoRavens Opens in Same Browser Window

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1699] opened 2015-03-18 01:18 UTC
- [ ] With Terms or Guestbook prompt, TwoRavens is loaded into the same window as Dataverse, and not new window.

**Comment by scolapasta** [comment] 2015-04-04 03:51
Duplicate of #1564

**Comment by kcondon** [comment] 2015-04-07 16:16
Closing as a duplicate

**Closed by kcondon** 2015-04-07 16:16 UTC
Labels: Component: UX & Upgrade, Status: QA
