### ISSUE TITLE
File download and handling (download all): resulting zip file should download files in "original format" 

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#4215] opened 2017-10-17 21:13 UTC
IFPRI is making this request. Currently, files are downloaded in "tabular" format, they would like the files in original format.

**Comment by pdurbin** [comment] 2017-10-17 22:24
This reminds me of #4000 opened by @acoppock

**Comment by djbrooke** [comment] 2017-10-18 02:08
Thanks @pdurbin - I'm going to close this out as a dupe of #4000.

**Closed by djbrooke** 2017-10-18 02:09 UTC
Labels: Feature: File Upload & Handling, Type: Feature, Type: Suggestion
