### ISSUE TITLE
index all fails to index some datasets but they can be indexed individually

### ISSUE THREAD

**Issue by lmaylein** [IQSS/dataverse#5575] opened 2019-02-26 10:37 UTC
Update 4.9.4 => 4.11 

> 41 dataset(s) failed to index

Build new index (solr 3.7.1)

```
[2019-02-26T11:21:11.108+0100] [glassfish 4.1] [INFO] [] [edu.harvard.iq.dataver
se.search.IndexBatchServiceBean] [tid: _ThreadID=131 _ThreadName=__ejb-thread-po
ol1] [timeMillis: 1551176471108] [levelValue: 800] [[
  There were index failures. 0 dataverse(s) and 41 dataset(s) failed to index. P
lease check the log for more information.]]
```

[2019-02-26T11:20:27.563+0100] [glassfish 4.1] [WARNING] [AS-EJB-00056] [javax.enterprise.ejb.container] [tid: _ThreadID=131 _ThreadName=__ejb-thread-pool1] [timeMillis: 1551176427563] [levelValue: 900] [[
  A system exception occurred during an invocation on EJB DataverseServiceBean, method: public edu.harvard.iq.dataverse.Dataverse edu.harvard.iq.dataverse.DataverseServiceBean.findRootDataverse()]]

[2019-02-26T11:20:27.564+0100] [glassfish 4.1] [WARNING] [] [javax.enterprise.ejb.container] [tid: _ThreadID=131 _ThreadName=__ejb-thread-pool1] [timeMillis: 1551176427564] [levelValue: 900] [[
  
javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean
	at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBContainerTransactionManager.java:662)
	at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:507)
	at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4566)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2074)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2044)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:220)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
	at com.sun.proxy.$Proxy343.findRootDataverse(Unknown Source)
	at edu.harvard.iq.dataverse.__EJB31_Generated__DataverseServiceBean__Intf____Bean__.findRootDataverse(Unknown Source)
	at edu.harvard.iq.dataverse.search.IndexServiceBean.findRootDataverseCached(IndexServiceBean.java:1400)
	at edu.harvard.iq.dataverse.search.IndexServiceBean.findPathSegments(IndexServiceBean.java:1201)
	at edu.harvard.iq.dataverse.search.IndexServiceBean.addOrUpdateDataset(IndexServiceBean.java:658)
	at edu.harvard.iq.dataverse.search.IndexServiceBean.indexDataset(IndexServiceBean.java:525)
	at edu.harvard.iq.dataverse.search.IndexServiceBean.indexDatasetInNewTransaction(IndexServiceBean.java:288)
	at sun.reflect.GeneratedMethodAccessor617.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)
	at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.GeneratedMethodAccessor127.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at sun.reflect.GeneratedMethodAccessor126.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
	at com.sun.proxy.$Proxy208.indexDatasetInNewTransaction(Unknown Source)
	at edu.harvard.iq.dataverse.search.__EJB31_Generated__IndexServiceBean__Intf____Bean__.indexDatasetInNewTransaction(Unknown Source)
	at edu.harvard.iq.dataverse.search.IndexBatchServiceBean.indexAllOrSubset(IndexBatchServiceBean.java:147)
	at edu.harvard.iq.dataverse.search.IndexBatchServiceBean.indexAllOrSubset(IndexBatchServiceBean.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:73)
	at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.GeneratedMethodAccessor127.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at sun.reflect.GeneratedMethodAccessor126.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
	at com.sun.ejb.containers.EjbAsyncTask.call(EjbAsyncTask.java:101)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.persistence.PersistenceException: javax.validation.ConstraintViolationException: Bean Validation constraint(s) violated while executing Automatic Bean Validation on callback event:'preUpdate'. Please refer to embedded ConstraintViolations for details.
	at org.eclipse.persistence.internal.jpa.QueryImpl.getSingleResult(QueryImpl.java:547)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.getSingleResult(EJBQueryImpl.java:400)
	at edu.harvard.iq.dataverse.DataverseServiceBean.findRootDataverse(DataverseServiceBean.java:164)
	at sun.reflect.GeneratedMethodAccessor304.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)
	at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.GeneratedMethodAccessor127.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at sun.reflect.GeneratedMethodAccessor126.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
	... 74 more
Caused by: javax.validation.ConstraintViolationException: Bean Validation constraint(s) violated while executing Automatic Bean Validation on callback event:'preUpdate'. Please refer to embedded ConstraintViolations for details.
	at org.eclipse.persistence.internal.jpa.metadata.listeners.BeanValidationListener.validateOnCallbackEvent(BeanValidationListener.java:90)
	at org.eclipse.persistence.internal.jpa.metadata.listeners.BeanValidationListener.preUpdate(BeanValidationListener.java:72)
	at org.eclipse.persistence.descriptors.DescriptorEventManager.notifyListener(DescriptorEventManager.java:721)
	at org.eclipse.persistence.descriptors.DescriptorEventManager.notifyEJB30Listeners(DescriptorEventManager.java:691)
	at org.eclipse.persistence.descriptors.DescriptorEventManager.executeEvent(DescriptorEventManager.java:229)
	at org.eclipse.persistence.descriptors.changetracking.DeferredChangeDetectionPolicy.calculateChanges(DeferredChangeDetectionPolicy.java:87)
	at org.eclipse.persistence.descriptors.changetracking.DeferredChangeDetectionPolicy.calculateChangesForExistingObject(DeferredChangeDetectionPolicy.java:56)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.calculateChanges(UnitOfWorkImpl.java:664)
	at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.writeChanges(RepeatableWriteUnitOfWork.java:438)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.flush(EntityManagerImpl.java:863)
	at org.eclipse.persistence.internal.jpa.QueryImpl.performPreQueryFlush(QueryImpl.java:963)
	at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:207)
	at org.eclipse.persistence.internal.jpa.QueryImpl.getSingleResult(QueryImpl.java:517)
	... 104 more
]]

**Comment by pdurbin** [comment] 2019-02-26 11:50
@lmaylein it's weird that you're seeing a ConstraintViolationException on what seems to be your root dataverse. Are all the required fields filled out? Your root dataverse has a name, alias, category, etc?

**Comment by lmaylein** [comment] 2019-02-26 12:01
name: heiDATA
Identifer: root
category: Uncategorized
description exists.
There is no alias for the root dataverse.

I changed category to "Organization or institution" but that did not help :-(

**Comment by lmaylein** [comment] 2019-02-26 12:18
This is an example of a dataset which is not indexed:
https://heidata.uni-heidelberg.de/dataset.xhtml?persistentId=doi:10.11588/data/10002

**Comment by lmaylein** [comment] 2019-02-26 12:18
The two other datasets in the same dataverse are indexed.

**Comment by pdurbin** [comment] 2019-02-26 12:32
Ok, and another way to access that dataset that isn't being indexed is via its database id: https://heidata.uni-heidelberg.de/dataset.xhtml?id=70

What if you try this to reindex just that one dataset...

curl http://localhost:8080/api/admin/index/datasets/70

... and then email your server.log to support@dataverse.org (and/or paste as much of the stracktrace as you can here)?

**Comment by lmaylein** [comment] 2019-02-26 12:35
> ... and then email your server.log to support@dataverse.org (and/or paste as much of the stracktrace as you can here)?

I've mailed it to dataverse_support@help.hmdc.harvard.edu
ticket id: #272859

**Comment by lmaylein** [comment] 2019-02-26 12:37
```
curl http://localhost:8080/api/admin/index/datasets/70
{"status":"OK","data":{"message":"starting reindex of dataset 70"}}
```

This works:

https://heidata.uni-heidelberg.de/dataverse/statnlpgroup

shows all the datasets now.

Strange!

**Comment by pdurbin** [comment] 2019-02-26 12:47
Yes, very strange. If you're able to index the datasets individually as a workaround for now, that's great. You can find the id of the dataset by exporting the dataset in JSON format and looking for "id", for example.

The thing that jumps out at me from the stacktrace you emailed is "findLinkingDataverses" in DatasetLinkingServiceBean which causes the EJBTransactionRolledbackException.

For those who have access, here's a handy link to the ticket with server.log attached: https://help.hmdc.harvard.edu/Ticket/Display.html?id=272859

**Comment by lmaylein** [comment] 2019-02-26 13:08
The missing datasets are now indexed individually.

**Comment by pdurbin** [comment] 2019-02-26 13:14
@lmaylein great! We've bought ourselves some time, at least. It sounds like learning how to index datasets individually was helpful and if you'd like to make a pull request for #2279 to update http://guides.dataverse.org/en/4.11/admin/solr-search-index.html I would really appreciate it.

Should we give this issue a new title? It sounds like you're actually able to index all the datasets if you index them one at a time. What would be a better summary of the issue? Please feed free to edit the title.

**Comment by lmaylein** [comment] 2019-02-26 14:00
I'm not sure about a better title/summary of this issue. Neither "reindex in place" nor "clear and reindex" worked.
I think it must be a problem introduced in 4.10 or 4.11.

**Comment by qqmyers** [comment] 2019-02-26 18:17
FWIW, I've seen an error from the same line (IndexServiceBean:1400) due to out of memory issues (when using full-text indexing). While the cause is different, the symptom is the same: the findRootDataverse query returns null. Since it is just a query for SELECT d FROM Dataverse d where d.owner.id=null - with no reference to the current dataset, it's odd that would ever fail for some datasets and not others, except if it is something like running out of memory. -- makes me wonder if there is some other problem beyond the ConstraintViolationException here...

**Comment by pdurbin** [comment] 2019-02-26 18:18
Huh, I hadn't considered out of memory. I did mention this issue at standup this morning.

**Comment by djbrooke** [comment] 2019-02-26 19:39
Some additional stack traces from @kcondon in the other report:

https://github.com/IQSS/dataverse/issues/4547#issue-309090095

**Comment by qqmyers** [comment] 2019-02-26 19:44
Looks like 3 of the 4 from #4547 are failing at the same findRootDataverse() line (1284 versus 1400 in the latest code, but same call)...

**Comment by dheles** [comment] 2019-04-10 18:24
I have this problem as well, when upgrading to versions 4.11 or 4.12. Individually reindexing the 24 nonsequential datasets works as a workaround. I can reproduce the problem on a non-production server & would be willing to help test a fix, when one is available.

**Comment by pdurbin** [comment] 2019-04-10 22:40
@dheles would you be able to provide a database dump from your non-production server to replicate the issue?

**Comment by dheles** [comment] 2019-04-16 13:40
@pdurbin here's a (lengthy) gist of the error log: https://gist.github.com/dheles/b445637629e05d0298165c95f9f589fe
working on anonymizing the db so we can share a dump of that with you as well

**Comment by dheles** [comment] 2019-04-22 16:37
@pdurbin The ticket regarding the backup you requested is: https://help.hmdc.harvard.edu/Ticket/Display.html?id=275089

**Comment by pdurbin** [comment] 2019-04-25 21:15
@dheles thank you so much. And thanks for creating #5776 to document the script you used to de-identify your database. We talked about this issue in sprint planning yesterday but we don't have the capacity to have it in the sprint we just started. We said maybe the next one.

@qqmyers since you're affected as well, do you happen to have capacity to work on this? 😄

**Comment by qqmyers** [comment] 2019-04-29 16:09
@pdurbin - I don't really have a reliable way to cause the issue, so it's hard to debug (and we see it primarily on dev/test machines with less memory so it's not a big production issue for QDR). 

Other than trying to add logging to get more detail about the constraint violation (e.g. as in https://stackoverflow.com/questions/22946549/javax-validation-constraintviolationexception) to a version to pass to others, I don't have any ideas. 

The one thing that looks odd to me, although it appears to work most of the time, is that the query used is 
`SELECT d FROM Dataverse d where d.owner.id=null`
which tries to get the owner id, when, for the root dataverse d.owner itself is null...

**Comment by pdurbin** [comment] 2019-04-29 16:17
@qqmyers ok. @dheles has a database dump that he may be willing to share with you to reproduce the issue.

On a related note, a new constraint validation checker was merged last week in pull request #5799

**Comment by pdurbin** [comment] 2019-05-13 13:02
@lmaylein @qqmyers @dheles

I'm wondering if you'd be able to run the new Dataset Validation API endpoint described in http://guides.dataverse.org/en/4.14/admin/troubleshooting.html#constraint-violations-issues to see if it detects any invalid values.

**Comment by lmaylein** [comment] 2019-05-13 13:30
We are running on 4.11. I have to update first.

**Comment by lmaylein** [comment] 2019-05-23 07:40
heiDATA is running on 4.14 now. A full reindex (clear+reindex) was successful. 
All datasets are valid.

**Comment by pdurbin** [comment] 2019-05-23 10:46
@lmaylein great! Was the Dataset Validation API useful? Did it find some problems to correct? And then you fixed them? Or are simply saying that a normal "index all" worked this time? It sounds like you're saying a normal "index all" worked.

**Comment by lmaylein** [comment] 2019-05-23 10:52
Yes. There was no need to correct any problems.

**Comment by pdurbin** [comment] 2019-05-23 10:58
@lmaylein ok, if upgrading to Dataverse 4.14 resolved this issue, I'm going to close it, especially since you opened it. 😄  @dheles thanks again for the database dump. If you're still having trouble after upgrading to 4.14, please open a fresh issue. @qqmyers same for you, please. Thanks, all.

**Closed by pdurbin** 2019-05-23 10:58 UTC
Labels: Medium
