### ISSUE TITLE
Impossible to edit the "Terms" section of a published dataset before 5.10 and subsequent updates

### ISSUE THREAD

**Issue by BPeuch** [IQSS/dataverse#8921] opened 2022-08-17 14:41 UTC
**What steps does it take to reproduce the issue?**
I think this occurs for datasets published before a Dataverse installation has been updated to version 5.10, though it could be earlier than that.

* When does this issue occur?
This happened to me when I tried to edit the "Terms" section of a dataset published before the late v5 updates.

* Which page(s) does it occurs on?
On the form webpage for editing the "Terms" section of a dataset. I used [this one](https://test.sodha.be/dataset.xhtml?persistentId=doi%3A10.80118%2FFK2%2F58CVZW&version=1.1) on our own test platform but the same happened with other datasets.

* What happens?
In the "Restricted Files + Terms of Access" metadata box, both the "Request Access" button and the "Terms of Access for Restricted Files" metadata field are gray and unclickable. I can neither enable request access nor add terms of access, as you can see here:

![imposs_edit_terms](https://user-images.githubusercontent.com/15209224/185164825-7932173e-7b47-42e9-960a-ef1dc67797b2.png)

* To whom does it occur (all users, curators, superusers)?
All users, including admin, non-admin, and superuser.

* What did you expect to happen?
I wish I could either add terms of access or enable access request, either of which would in theory solve the problem. But both actions are denied to me now.

**Which version of Dataverse are you using?**
Our [test instance](https://test.sodha.be/) is version 5.11.1.

**Any related open or closed issues to this bug report?**
This might be related to [issue #8553](https://github.com/IQSS/dataverse/issues/8553), which was fixed very recently.

**Comment by BPeuch** [comment] 2022-08-17 14:43
I thought about seeing if this occurs on Demo Dataverse as well, but I don't have any 'old' datasets there, ones that have been published before the latest updates. Maybe someone else does?

**Comment by poikilotherm** [comment] 2022-08-24 13:55
Looks like this is a duplicate of #8832, solved with #8834

**Closed by poikilotherm** 2022-08-24 13:55 UTC
