### ISSUE TITLE
better organization to bundle properties

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4825] opened 2018-07-10 18:18 UTC
`Bundle.properties` is ~2k lines of unstructured key/value pairs, comments and empty lines.  With more information moving there, it may be worth investigating how to split this into several smaller property files according to functionality, or other potential approaches to reduce cognitive complexity.

**Comment by pdurbin** [comment] 2018-07-10 18:23
@pameyer good idea. You'll be pleased to know that @JayanthyChengan has already begun the process of spitting up that giant Bundle.properties file into smaller files. She added ValidationMessages.properties in pull request #4815 for issue #3980.

**Comment by mheppler** [comment] 2018-07-10 18:23
Potentially duplicate of:
- _Highly excessive duplication in Bundle.properties #4807 

Related to:
- _Internationalization #209_
- _Style guide – document messaging text and visual styles #3865_

**Closed** 2023-10-07 22:43 UTC
Labels: Component: Code Infrastructure, Component: JSF, UX & UI: New React UI
