### ISSUE TITLE
Publishing: sub-sub dataverses no prompt to publish "all."

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2181] opened 2015-05-19 16:41 UTC
When publishing a sub sub dataverse within an unpublished sub-dataverse and unpublished parent dataverse, you are not prompted to published the entire Dataverse tree.

**Comment by scolapasta** [comment] 2015-06-01 18:46
At some point this was by design. @eaquigley can you comment?

**Comment by eaquigley** [comment] 2016-01-06 19:47
I was able to find #626 that relates to this. I am guessing that we followed the same conventions for dataverses within dataverses, @sekmiller do you remember if that is what we did? 

I'm not sure though because there is a comment in #626 from @scolapasta that says, "We'll need to think how this works with dataverses within dataverses (that are all unpublished). Maybe we can add a simple only one dataverse up logic for 4.0, while we think about the broader issue)." 

No matter what though, it seems like we only went two levels deep with these messages.

**Comment by sekmiller** [comment] 2016-01-06 20:04
I think the intent was to allow you to publish a parent, but to only go up one level - that is if your parent and grandparent are unpublished then you have to go up the line and publish them manually.


On Jan 6, 2016, at 2:47 PM, Elizabeth Quigley <notifications@github.com<mailto:notifications@github.com>> wrote:


I was able to find #626<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_626&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=EC0XJgsXpFR0Jo8SUSNzDQMXruYqB7xylrd-SOJU5kY&s=YKzhdIKnOp_ONxdQ6tQOoww8i7qtx2ZeBw42zGgyLHI&e=> that relates to this. I am guessing that we followed the same conventions for dataverses within dataverses, @sekmiller<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sekmiller&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=EC0XJgsXpFR0Jo8SUSNzDQMXruYqB7xylrd-SOJU5kY&s=Voo5RaJuOBDS2nQGDDUpBx9ZPcKLyaY79uNZvmVcxjo&e=> do you remember if that is what we did?

I'm not sure though because there is a comment in #626<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_626&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=EC0XJgsXpFR0Jo8SUSNzDQMXruYqB7xylrd-SOJU5kY&s=YKzhdIKnOp_ONxdQ6tQOoww8i7qtx2ZeBw42zGgyLHI&e=> from @scolapasta<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_scolapasta&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=EC0XJgsXpFR0Jo8SUSNzDQMXruYqB7xylrd-SOJU5kY&s=jL6QgdrePs6GfIPBUNlbKUoc84alwrOsJw130lf0h-w&e=> that says, "We'll need to think how this works with dataverses within dataverses (that are all unpublished). Maybe we can add a simple only one dataverse up logic for 4.0, while we think about the broader issue)."

No matter what though, it seems like we only went two levels deep with these messages.

**Comment by kcondon** [comment] 2016-04-05 16:05
This is not a bug because it is as designed. We do not plan to implement this as a feature at this point due to lack of use request. Closing.

**Closed by kcondon** 2016-04-05 16:05 UTC
Labels: Component: Publishing & Versions, Component: UX & UI, Status: Triaged, Type: Feature, Type: Suggestion
