### ISSUE TITLE
Metadata customization

### ISSUE THREAD

**Issue by edzale** [IQSS/dataverse#3506] opened 2016-12-05 20:45 UTC
Hi,
in our local installation, we would like to customize the metadata:

- remove the Astronomy metadata block because it's not accurate for our scientific domains
- add and remove certain metadata elements in the other blocks
- and define controlled vocabularies for certain metadata elements
Questions: is there any available documentation about these kind of customizations? Is there any way to use a remote controlled vocabulary (accessible through an API for example)?
Thank you in advance for your help.

**Comment by pdurbin** [comment] 2016-12-05 21:19
@edzale thanks for opening this issue. Would you say it's a duplicate of #3168?

**Comment by pdurbin** [comment] 2017-06-23 12:37
@edzale I copied your comment into #3168 and am closing this issue. Thanks for your feedback!

**Closed by pdurbin** 2017-06-23 12:37 UTC
Labels: Component: Metadata
