### ISSUE TITLE
Export Errors: DDI, HTML DDI have issues

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#8036] opened 2021-07-29 20:40 UTC
Discovered in 5.6 dev but confirmed on 5.5.

DDI export shows an error at the top of the export:
This page contains the following errors:
error on line 1 at column 30220: Extra content at the end of the document
Below is a rendering of the page up to the first error.

HTML DDI Codebook export just shows a blank page.

**Comment by landreev** [comment] 2021-07-29 21:33
This is a bit confusing... The DDI error does appear to be happening on demo.dataverse.org ("confirmed on 5.5"); example: https://demo.dataverse.org/api/datasets/export?exporter=ddi&persistentId=doi%3A10.70122/FK2/BRJLGV - the outer `<codeBook>` element isn't closed  at the end.
But this doesn't seem to be universally happening everywhere. For example, this  dataset in prod. that has just been published has a well-formatted DDI: https://dataverse.harvard.edu/api/datasets/export?exporter=ddi&persistentId=doi%3A10.7910/DVN/LPCEXG.  

It could be caused by specific metadata of course... but the above dataset on demo doesn't have much metadata at all - it's a bare bones dataset with 3 files.

**Comment by landreev** [comment] 2021-07-29 21:41
P.S. Not only the closing `</codeBook>` is missing, but the closing `</dataDscr>` element is in the wrong place (*after* the last `</otherMat>`, for some reason...)

Hmmmm.

**Comment by poikilotherm** [comment] 2021-07-29 21:43
For the record: I refactored lots of tests and XML stuff in #8000. This might have an influence on this one.

**Comment by landreev** [comment] 2021-07-29 22:18
Kevin, check out this dataset I just created and published on internal: 
Same files, same amount of metadata (or lack thereof) - but valid DDI export: 
https://dataverse-internal.iq.harvard.edu/dataset.xhtml?persistentId=doi%3A10.70122%2FFK2%2FBS7KXQ&version=DRAFT

I'm having a bad feeling that it's working w/ S3... but not when the export lives on a filesystem. This would explain the fact that it's working in prod. 
Can you see anything else that's different, between my test dataset, above, and yours?? 

(it's not impossible; that we flush some buffers in that export, in a way that fails differently, depending on the physical driver... but that would still be quite weird!)

**Comment by landreev** [comment] 2021-07-29 22:23
@poikilotherm Thanks!

I'll take a look, but... When you say "refactored"... how broken were they?

**Comment by landreev** [comment] 2021-07-29 22:43
But, I CANNOT reproduce this on my own build (develop branch);  these DDI exports are just working for me, regardless of the type of dataset or where they are written. 

Is there a chance that both demo and dataverse-internal are broken in some similar way, outside of the application itself? Some metadata block update that was applied to both of them? - idk.

OK, I've already spent more time looking into this than I could afford...

**Comment by kcondon** [comment] 2021-07-30 13:42
OK, I've identified the missing step, still trying to isolate issue: I've restricted 2 of 3 files. Doesn't happen with 1 or 2 restricted files. Doesn't need terms of access.

**Comment by landreev** [comment] 2021-07-30 14:02
Thanks! I feel bad now, having missed this part last night. 
So I guess our export code tries to skip that restricted file in the DDI, but messes up the formatting in the process.

**Comment by qqmyers** [comment] 2021-08-01 19:03
Yep - https://github.com/IQSS/dataverse/blob/69cfaf11417718c59b57ab7d4d75ea7c22702313/src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java#L1428 should be a `continue;` not `return;` Otherwise, the restricted file causes you to exit the loop through files and, if you've already had a tabular file, you never write the closing "dataDscr" element, which means the writeEndElement() that is supposed to close the overall codeBook element just ends the dataDscr element and leaves the codeBook unclosed.

**Closed** 2021-08-04 16:27 UTC

**Comment by pdurbin** [comment] 2021-08-10 19:47
Shoot. I added the `return` in pull request #7642. Thanks for fixing, @qqmyers !
