### ISSUE TITLE
Doc update: TestShib not available anymore

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#5666] opened 2019-03-19 14:08 UTC
TestShib.org referenced in the [Shibboleth docs](http://guides.dataverse.org/en/latest/installation/shibboleth.html#id36) for testing your SP is not available anymore.

Instead, https://samltest.id can be used for testing purposes. This will be done for IQSS/dataverse-kubernetes#14.

**Comment by pdurbin** [comment] 2019-03-19 16:56
This is a duplicate of #5369

@poikilotherm would you like to make a pull request? 😄

**Comment by poikilotherm** [comment] 2019-03-19 17:34
Sorry for the duplicate. Shall I close this in favor of the original issue?

**Comment by pdurbin** [comment] 2019-03-19 18:04
@poikilotherm no worries. We appreciate the bug report. I'll close it.

**Closed by pdurbin** 2019-03-19 18:04 UTC
