### ISSUE TITLE
File Upload: completed files remain in the "select files to add" box after finishing upload

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#2880] opened 2016-01-19 21:11 UTC
Uploaded ~150 ~11 MB files individually (not in zip/tgz)
 - create new dataset
 - files -> "+ Select Files to Add"
 - select all (in browser window)
 - small number of files (not fully reproducible - ~2-5) remain in the "Select Files to Add" box after upload completes (judging by drop in server load, presence of these files in the unlabeled box of files uploaded below, and presence on the filesystem (w\ matching checksums).  Number of files shows up correctly after dataset save; suggesting that it's a UI problem.  Observed in both firefox and safari.

Possibly related : https://github.com/IQSS/dataverse/issues/2491 , https://github.com/IQSS/dataverse/issues/2482

**Comment by pdurbin** [comment] 2016-01-20 15:49
I'll probably try to reproduce this with files from https://data.sbgrid.org/dataset/133/ based on what @pameyer mentioned at http://irclog.iq.harvard.edu/dataverse/2016-01-20

**Comment by pameyer** [comment] 2016-01-20 15:51
For reproducibility, I was seeing this on 4.2.2

**Comment by pdurbin** [comment] 2016-01-20 15:53
> I was seeing this on 4.2.2

Thanks. I wonder if the upgrade from Primefaces 4 to 5 in #2730 as part of 4.2.3 will make any difference in reproducing this bug.

**Comment by pdurbin** [comment] 2016-01-20 18:20
On my laptop I'm on commit a90be2a of the 4.2.3 branch and I just tried uploading all 148 files from https://data.sbgrid.org/dataset/133/

The main thing I want to do for now is upload a screenshot of what I'm seeing, which I'll put below, to make sure this is what @pameyer is talking about.

Other observations (while using Firefox) are that my Mac was "beachballing" during the upload and I couldn't switch tabs. I'm pretty sure my fans were blowing pretty hard. That is to say this feel like an expensive operation for a browser.

![upload_files_-_sbgrid133_-_2016-01-20_13 07 02](https://cloud.githubusercontent.com/assets/21006/12458568/6e8b4ace-bf78-11e5-9eda-4f137dbe3b43.png)

**Comment by pameyer** [comment] 2016-01-20 19:29
@pdurbin - that screenshot matches what I was seeing.  The number of files varied (I deleted and re-uploaded a few times).

I didn't notice any beachballing - but I wasn't watching for it.

**Comment by pameyer** [comment] 2016-01-21 15:23
@pdurbin - the fans spinning up on your laptop might have been the dataverse app (ingestion?) rather than the browser?

**Comment by pdurbin** [comment] 2016-01-21 15:26
@pameyer I had that thought as well but I don't have any evidence one way or the other. :)

**Comment by pdurbin** [comment] 2016-02-22 21:36
@bmckinney for now can you please see if you can reproduce this in the "develop" branch?

**Comment by bmckinney** [comment] 2016-03-15 18:43
@pdurbin and @pameyer - confirmed with develop branch

Also, not only do random successful uploads linger in the "Select files" section, but one of the 120 files I attempted to upload failed to upload and it wasn't listed in either section. If I count the files in dataverse's temp folder (prior to saving the dataset), it is also 1 shy of the 120 total. This bug is more concerning to me!

**Comment by pdurbin** [comment] 2016-03-15 18:49
> If I count the files in dataverse's temp folder (prior to saving the dataset), it is also 1 shy of the 120 total.

I assume you're talking about the JSF temp folder? (#2848 is about documenting all of them.) If so, you could repeat your test via SWORD to avoid JSF.

**Comment by bmckinney** [comment] 2016-03-15 19:47
also seeing lots of java.util.ConcurrentModificationException when checking for duplicates

**Comment by bmckinney** [comment] 2016-03-15 20:05
yeah, i think **edu.harvard.iq.dataverse.EditDatafilesPage#isDuplicate** (which generates java.util.ConcurrentModificationException) is the culprit. 

when i comment out the md5 stuff in that method and return false in all cases, i'm unable to reproduce the bug (all files reported uploaded and no lingering files in the top section)

**Comment by kcondon** [comment] 2016-04-14 16:52
There is a pull request made to fix this. Will test and close.

**Comment by kcondon** [comment] 2016-05-27 18:15
OK, the fix did not correct the one missing file issue, that is being tracked in: #3116 
We are seeing "hung up files" when uploading zip files, before unpacking, also in #3116.
I have not yet reproduced the initial problem reported in this ticket.

**Comment by kcondon** [comment] 2016-05-27 19:11
Tested the above scenario with the mentioned files. Was able to upload twice without errors or missing/ hung files. Closing this particular issue but as mentioned, some weirdness remains and will be addressed in #3116. Closing.

**Closed by kcondon** 2016-05-27 19:11 UTC
Labels: Component: File Upload & Handling, Status: QA, Type: Bug
