### ISSUE TITLE
Guestbook - Downloads via API are not counted

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3331] opened 2016-09-06 19:35 UTC
originally part of #3324

---

Update: Downloads via the API are not counted in the GuestBookResponses -- e.g. don't seem to be counted at all.

See this file: `Access.java` and this method--and add a new `GuestBookResponse` object to it: 

``` java
@Path("datafile/{fileId}")
    @GET
    @Produces({ "application/xml" })
    public DownloadInstance datafile(@PathParam("fileId") Long fileId, @QueryParam("key") String apiToken, @Context UriInfo uriInfo, @Context HttpHeaders headers, @Context HttpServletResponse response) /*throws NotFoundException, ServiceUnavailableException, PermissionDeniedException, AuthorizationRequiredException*/ {                
```

**Comment by sekmiller** [comment] 2016-10-12 13:25
This has been addressed in conjunction with the file landing page redesign of the download processing. Guestbook records will be created when the user invokes a download via the API.

**Comment by djbrooke** [comment] 2016-10-14 15:43
Closing this. Will leave a note in #2465.

**Comment by pdurbin** [comment] 2016-10-15 14:24
The non-counting of downloads via API has been noted in #2911.

**Comment by pdurbin** [comment] 2017-01-24 01:15
The comment by @sekmiller makes it sound like this was addressed in 4.6 so I'll add that milestone to that issue.

**Comment by kcondon** [comment] 2017-02-07 20:03
Reopen per Danny and testing shows it still exists.

**Comment by shlake** [comment] 2018-01-19 15:54
When a user uses the Download URL, this type of download is not being counted.

Does "downloadtype" include counts from non-dataverse-clicking - like a person entering the DownloadURL in a browser window and "clicking go" from the browser.

Because what I see right now, if I copy/paste the download URL, view that URL in a browser window, that "download" is not counted.

**Comment by landreev** [comment] 2018-01-19 21:13
From a quick look, unfortunately this may have been broken for more than a year. It looks like in the all of 2016 we rearranged how the guestbook records are written by the API. The actual writing was moved from Access.java into DownloadInstanceWriter.java; in  in order to write the record *after* the download is complete, not before; to ensure that only the successful downloads are counted.
However, in Nov. 2016 it looks like these lines in Access.java were commented out: 
```
/*
        if (gbrecs == null && df.isReleased()){
            //commenting out for 4.6 SEK
           // gbr = guestbookResponseService.initDefaultGuestbookResponse(df.getOwner(), df, session);
        }
        */
```
this means gbr stays null; but then further down we have:
```
if (gbr != null){
            downloadInstance.setGbr(gbr);
            downloadInstance.setDataverseRequestService(dvRequestService);
            downloadInstance.setCommand(engineSvc);
        }
```
And because of this, since the gbr element in the DownloadInstance is null, the following code in DownloadInstanceWriter.java never gets executed:
```
if (di.getGbr() != null && !(isThumbnailDownload(di) || isPreprocessedMetadataDownload(di))) {
                        try {
                            logger.fine("writing guestbook response.");
                            Command<?> cmd = new CreateGuestbookResponseCommand(di.getDataverseRequestService().getDataverseRequest(), di.getGbr(), di.getGbr().getDataFile().getOwner());
                            di.getCommand().submit(cmd);
                        } catch (CommandException e) {
                            //if an error occurs here then download won't happen no need for response recs...
                        }
                    } else {
                        logger.fine("not writing guestbook response");
                    } 
```
(and even if it were executed, because downloadInstance.setCommand(...) was never done, the command could not be executed either...)
Hmmm... Once again, that was a very quick look, so I may be missing something. 
But what's particularly annoying is that the last message on the issue is Kevin saying back in Feb. that yes, it is still broken.

**Comment by djbrooke** [comment] 2018-01-19 21:17
Thanks for the summary @landreev, we'll pick it up when someone has capacity.

**Comment by landreev** [comment] 2018-01-19 21:38
It may be an honest 1 - just a matter of uncommenting/changing a couple of lines of code in the 2 class files. 
Either way, what I entered should be enough to estimate, and for somebody to fix it, when capacity presents itself.

**Comment by mheppler** [comment] 2018-01-23 23:54
Related #3572

**Comment by kcondon** [comment] 2018-02-09 19:37
-Single file API download does increment count but does not record user if key is used. Always identified as guest.
-Multiple file API download does not increment count.
-Single or multiple file download using top download button doesn't work in UI if no popup defined (gb or tou). Known issue but ideally should be fixed.
-API download always records as default guestbook whether or not a gb is defined. Known limitation of current design.

**Comment by pdurbin** [comment] 2018-02-12 21:47
> -Also throws an integration test error per pameyer

I just tested this on my laptop as of d54117b and sure enough, line 291 of SwordIT.java is failing. Here's a screenshot from Netbeans:

![screen shot 2018-02-12 at 4 44 50 pm](https://user-images.githubusercontent.com/21006/36121461-3ba3e4b0-1014-11e8-8647-77faab5563b7.png)

This is the line that's failing:

        assertEquals(NOT_FOUND.getStatusCode(), downloadDeletedFileWithValidApiToken.getStatusCode());

For comparison I also tested develop as of c6e1177 and all 7 tests in SwordIT are passing.

**Comment by sekmiller** [comment] 2018-02-13 14:29
Fixed and checked in the getting user key info into the default record. Also assigned to the gb selected at dataset level, but doesn't add answers for custom questions or enforce required fields.

**Comment by sekmiller** [comment] 2018-02-13 14:30
@pdurbin and @pameyer thanks for your research on the integration test. Since I'm already in the code  there I'll take care of it.

**Comment by pdurbin** [comment] 2018-02-13 14:32
I just pulled the latest (d30aeca) and all seven tests in SwordIT are passing now.

**Comment by sekmiller** [comment] 2018-02-13 19:21
Fixed the multiple download issue, so all of the items noted by Kevin above have been addressed.

**Comment by kcondon** [comment] 2018-02-14 23:04
OK, all reported issues above were fixed, including download bundle. Did find one new issue: clicking on Two Ravens explore increments count by 2 and responses shows 1 TwoRavens and 1 download.

**Comment by landreev** [comment] 2018-03-06 02:20
I have moved the issue back into QA. 
The fixes for counting zipped downloads of multiple files and "download bundles" look great. 
As for the issue of the extra count coming from the data file download coming from TwoRavens, this is addressed on the TwoRavens side - and does not require any code changes in the Dataverse. 

OK, let's merge it... since all these downloads that are killing the prod. servers are not getting counted!

**Comment by kcondon** [comment] 2018-03-07 17:31
OK 2 ravens was patched in production and we agreed to supply that patch in the release notes with instructions on how to apply it.

**Closed by kcondon** 2018-03-07 17:31 UTC
Labels: Feature: API, Feature: Code Infrastructure, Status: QA, Type: Bug
