### ISSUE TITLE
Ingest of Stata file with diacritics characters produces not correct encoded variable metadata

### ISSUE THREAD

**Issue by CB-HAL** [IQSS/dataverse#9469] opened 2023-03-23 13:37 UTC
After the upload of Stata files (Version SE17, .dta-format 118 from Stata 14, 15, 16, or 17) the ingest runs correctly. The original binary and tab file can be downloaded correctly. But the metadata of variables isn’t correct encoded. Diacritics are shown as unicode replacement character ��. Variable & value level are affected.
e.g. https://data.aussda.at/api/datasets/export?exporter=ddi&persistentId=doi%3A10.11587/QQ7HTL  
\<var ID="v31494" name="G1" intrvl="discrete">
\<location fileid="f472"/>
\<labl level="variable">laufende Nummer des Gespr��chsturns</labl>
		
\<var ID="v31501" name="G3" intrvl="discrete">
\<location fileid="f472"/>
\<catgry>
\<catValu>201</catValu>
\<labl level="category">Alois Mock (��VP)</labl>
Note: In this metadata export example there are also correct diacritics from other data files, csv and SPSS ingest is correct.

This error can only be found in not restricted data files, where variable metadata can be exported.
But the search can find other corrupted characters, the variable metadata is also ingested from restricted files
https://data.aussda.at/dataverse/AUSSDA/?q=%EF%BF%BD%EF%BF%BDsterreich
 
I think it has something to do with https://en.wikipedia.org/wiki/Variable-width_encoding 
I can also exclude that the Stata files are corrupted, attached a small test file which generates the same error.

Dataverse 5.12.1
the first issue concern the same Dataverse instance

- https://github.com/IQSS/dataverse/issues/7507 
- https://github.com/IQSS/dataverse/issues/6675

[stata14_ingest_diacritics_numericVariable.zip](https://github.com/IQSS/dataverse/files/11051102/stata14_ingest_diacritics_numericVariable.zip)

**Comment by landreev** [comment] 2023-03-24 18:31
Hello, 
Thank you for the report, and for sending a .dta file along. 
Problems with accented characters or other kinds of non-ASCII/unicode characters come up once in a while. In most cases however it ends up being a matter of running the application server in a wrong locale, instead of en_US.UTF-8 (or similar). Unfortunately, this does not appear to be the case, because I'm getting the same result on my own instance. (Also, the end result is usually different - a 2-byte UTF character representing a diacritic would become 2 individual byte characters; in your case they are turned into the 3-byte Unicode "unknown character" symbols `<EF><BF><BD>`). 
I know for the fact that accented UTF8 characters are handled properly in at least some Stata files; or used to be, at least. But I can confirm that the UTF8 bytes in your Stata file appear to be correct (`<C3><96>sterreich` - these are the correct 2 bytes representing the unicode character). 

I will need to take a closer look next week.

**Comment by landreev** [comment] 2023-03-24 18:33
P.S. To be precise, each of your accented characters is turned into TWO "unknown character" Unicode symbols (6 bytes total). So this does mean that our reader attempts to process them as 2 individual bytes... Ok, I'll figure it out.

**Comment by landreev** [comment] 2023-03-27 04:49
I was wrong. When I said

> I know for the fact that accented UTF8 characters are handled properly in at least some Stata files ... 

\- I was thinking of utf characters in string values in the data columns, not in value labels. It really looks like we never properly processed any accents or such in labels! The fix appears to be completely straightforward - literally 1 line in the Stata parser. I will make a PR.
With the fixed parser:

```
<catgry>
<catValu>3</catValu>
<labl level="category">Türkiye</labl>
<catStat type="freq">1</catStat>
</catgry>
<catgry>
<catValu>1</catValu>
<labl level="category">Österreich</labl>
<catStat type="freq">2</catStat>
</catgry>
```

**Comment by landreev** [comment] 2023-03-27 13:56
(The "one line fix" was specifically for the category labels; I still need to figure out what's going on with the variable labels proper).

**Comment by landreev** [comment] 2023-03-30 20:59
For the record, it's just as straightforward with the variable-level labels. Our parser appears to have been implemented  under the assumption that only plain ASCII characters were allowed in those: 
```
String ret = new String(readBytes(n), "US-ASCII");
```
... and that is obviously not true. I'm wondering if that was something in the spec of the old, pre-v13 Stata format, that we mistakenly transferred into the new DTA reader... idk. 
But yes, we will fix this in the next Dataverse release. 

Thank you again for the report.

**Comment by CB-HAL** [comment] 2023-03-31 07:27
Perfect, thank you for the fast solution.

**Comment by landreev** [comment] 2023-03-31 17:14
Can I ask you what language locale you are running Dataverse under? (`echo $LANG` on the command line, or something similar). 
Is it `de_AT.UTF-8`, or ...?

**Comment by CB-HAL** [comment] 2023-04-03 13:57
our local language `en_US.UTF-8`

**Closed** 2023-05-12 16:20 UTC
