### ISSUE TITLE
Change the different fields of the metadata Citation 

### ISSUE THREAD

**Issue by youssefOuahalou** [IQSS/dataverse#6435] opened 2019-12-05 10:45 UTC
![subjectORi](https://user-images.githubusercontent.com/46802308/70228304-68226e00-1754-11ea-9136-e4e95851b24d.PNG)
![subjectModified](https://user-images.githubusercontent.com/46802308/70228310-6bb5f500-1754-11ea-8d1c-9ba95b769218.PNG)
![AuthorAffOri](https://user-images.githubusercontent.com/46802308/70228316-6f497c00-1754-11ea-8826-310f18ed3167.PNG)
![AuthorAFFModified](https://user-images.githubusercontent.com/46802308/70228323-72446c80-1754-11ea-8978-f8a22e09cb50.PNG)
It would be nice to be able to directly modify the metadata block of Dataverse

**Comment by djbrooke** [comment] 2019-12-09 21:31
Hi @youssefOuahalou, I'm going to close this as a duplicate of #2297. This is a long-going discussion and generally we don't want to make this citation metadata block editable as its implementation is a reflection of best practices for data citation.

**Closed by djbrooke** 2019-12-09 21:31 UTC

**Comment by pdurbin** [comment] 2019-12-09 21:39
I would say this is more of a duplicate of #6030, especially these use case:

- I want depositors to select from a list of people provided by LDAP (or another system) for fields such as author, contributor, producer
- I want depositors to be able to select from metadata options provided by an API instead of from hard coded values

Other related issues:

- Customization of subject list #5938 
- Request: ability to use remote and dynamic lists in properties such as author, contributor, producer, contributor #3622 
- Referencing API data in the metadata #4772
