### ISSUE TITLE
File Upload: For slow uploading files, add note to files tab not to move away from page or it will halt upload.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3279] opened 2016-08-12 21:57 UTC
Sometimes files take a long time to upload and at certain points, feedback is limited, such as when a large zip file has uploaded but is unpacking. 

In those times, users may navigate away from the page and come back only to find the upload has disappeared and in fact fails.

So one of our in house users suggested we add a note to the files upload screen saying not to navigate away or it will halt upload.

**Comment by mheppler** [comment] 2016-09-02 16:59
Related to/duplicate of: Tabular File Ingest: No message indicating page will refresh on its own, or if user needs to manually refresh #1798; and: Ingest Dataset File: provide more guidance and information about ingestion process for large files #2204

**Comment by raprasad** [comment] 2016-11-02 20:42
### Dev team discussion

The team discussed this issue on Nov. 2 using these google slides:
  - [Simplifying* File Upload](https://docs.google.com/presentation/d/147y0a5vzLj_Np28K68DSL1bYkYTi6HnJyF7ZfqamZzw/edit?usp=sharing)

Some notes from that talk:
  - @landreev has a fix which doesn't link new  DataFile/FileMetadata objects to the DatasetVersion _until_ they are persisted  which cuts down some of the complexity
    - @landreev - also fixed issue with error messages only able to show info on one file when there may be multiple file issues (such as duplicates)
  - File upload is happening with parallel processing which "helps" freeze the upload page with lots of message uploads, etc
   - serial processing may help to stop page from freezing
  
@kcondon (who created this ticket) did describe user issues.  We also described Sonia's current issues with freezing (with or without .zip files)
  - Several dev members would like to see more research on UX experience

@scolapasta - brought up possible solution of saving DataFiles as soon as they're added--and not allowing name, description, tag editing until the next page

## Overall:
  - Solution in slides would fix refresh issue
  - @landreev thought it wouldn't be complicated to do
     - Although did point out that abandoning a file _replace_ operation (vs file _add_) may raise some extra complexity (or error messaging)
  - **Decision**: Given timing, this is not directly on the 4.6 critical path but _may_ be addressed during this release
      - e.g. There will be a 4.6 check-in on this ticket

**Closed** 2023-11-11 02:18 UTC
Labels: UX & UI: Design, Type: Suggestion, Feature: File Upload & Handling, User Role: Depositor
