### ISSUE TITLE
No warning when files not included because of download size limit

### ISSUE THREAD

**Issue by mankoff** [IQSS/dataverse#7157] opened 2020-08-03 14:51 UTC
When I download a file from a dataset which is bigger than the max allowed download size, there is no warning, random files are simply not included. I have to dig into the MANIFEST.TXT to find out that something was dropped.

**Comment by pdurbin** [comment] 2020-08-03 14:54
@mankoff thanks for the bug report. This is probably a duplicate of this issue:

- Download All Error Reporting - Hidden in Manifest if not all files are downloaded (4.9.4) #5588

**Comment by djbrooke** [comment] 2020-08-03 14:57
Thanks @pdurbin 

@mankoff I'm going to close this as a duplicate, but we hope that the occurrences of this will be greatly reduced by the work in https://github.com/IQSS/dataverse/pull/6986 that moves the zipping to an external service.

**Closed by djbrooke** 2020-08-03 14:57 UTC

**Comment by mankoff** [comment] 2020-08-03 15:02
Yes dupe. Sorry. Did not find that when I searched.
