### ISSUE TITLE
Remove html comments from builds

### ISSUE THREAD

**Issue by matthew-a-dunlap** [IQSS/dataverse#4281] opened 2017-11-14 17:14 UTC
Right now there are many html comments in our xhtml pages, and those comments muck up our code in source view. We can add this chunk to our web.xml to remove the comments:

```
    <context-param>
        <param-name>facelets.SKIP_COMMENTS</param-name>
        <param-value>true</param-value>
    </context-param>
```

It looks like there is no downside, and if a developer needs the comments for debugging its easy to turn off.

**Comment by pdurbin** [comment] 2018-06-28 01:37
Closing as a duplicate of #4351.

**Closed by pdurbin** 2018-06-28 01:37 UTC
