### ISSUE TITLE
Popup text can be hidden under Primefaces 11

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#8656] opened 2022-04-27 13:32 UTC
**What steps does it take to reproduce the issue?** With Primefaces 11 popups are responsive to changing the size of the browser (shrink to fit) Viewing certain popups in a narrowed browser window cuts off text rather than wrapping it.

* When does this issue occur? One known popup where you can see this effect it the Access Popup which is shown to the dataset admin when they restrict a file. (screen shots are included below) there may be others.

* Which page(s) does it occurs on? Access popup on the dataset page and edit files page

* What happens? as described above. 

* To whom does it occur (all users, curators, superusers)? curators and super users. general users would not see this popup

* What did you expect to happen? we would like the info text to wrap so that all of it can be read, instead of "falling off the edge"

**Which version of Dataverse are you using?** 5.10.1 dev

**Any related open or closed issues to this bug report?** #8456 upgrade PrimeFaces

**Screenshots:**
Before narrowing the browser window:

<img width="751" alt="Screen Shot 2022-04-25 at 2 16 32 PM" src="https://user-images.githubusercontent.com/2364928/165530076-06f9b2ab-4dea-4aa0-b16a-dfb47b2987e4.png">

After narrowing the browser window:

<img width="600" alt="Screen Shot 2022-04-25 at 2 16 47 PM" src="https://user-images.githubusercontent.com/2364928/165530144-91d5d71f-be12-4218-9309-f449ebeb1767.png">

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

**Comment by mreekie** [comment] 2022-04-27 18:40
prio:
 - we should fix this while we are here.
 - Impacts this popup
 - part of this will be looking for other instances of this popup issue and applying this fix.

sprint: 
 - small

**Comment by mreekie** [comment] 2022-04-27 18:42
Sounds like moving to 11 fixed non responsive windows, but left the text cutoff

**Comment by scolapasta** [comment] 2022-05-06 18:30
A couple suspects to look at:

The style sheet seems to define a minimum width, which is likely the cause. 

Also, in this file:
```dv_rebind_bootstrap_ui.js ```
 there is this:
```function handleResizeDialog(dialog) {```
which seems to mess with width.

**Comment by mreekie** [comment] 2022-05-11 19:27
Sprint:
 - Gustavo indicates to keep this in 
 - This was raised by Tania

**Comment by mreekie** [comment] 2022-05-25 17:22
- in WIP at end of [pm.sprint.2022_05_11](https://github.com/IQSS/dataverse/labels/pm.sprint.2022_05_11)

**Comment by qqmyers** [comment] 2022-05-25 20:14
If I understand the issue correctly, I'm not seeing this exactly in Chrome, Firefox, or Edge on Windows. The Restrict Access dialog does get slightly smaller, and the 'Enable access request' with the checkbox will drop to the next line as in second pic, but at that point the dialog itself stops shrinking. 
![image](https://user-images.githubusercontent.com/6731983/170358954-a14ad1d1-e3a7-4955-ae11-5cb50e92da84.png)
 
So the dialog itself can get cut off if the window keeps getting smaller, but that is just because the width of the dialog is set at 700px and the min-width is constrained to 600px. If I remove those, the dialog continues to get narrower with the window: e.g. in the extreme: 
![image](https://user-images.githubusercontent.com/6731983/170358674-0a443d1d-f929-42ca-ad99-390ebb461b14.png)

Removing the width/min-width also let's the dialog width grow, so replacing those with a max-width:700px seems to be useful as well.

Does it work differently on the Mac? Or is the second image above just showing the whole dialog getting cut off? If it's the latter, perhaps the min/max and width changes will resolve things?

**Comment by mreekie** [comment] 2022-06-08 17:54
Sprint:
- pm.sprint.2022_05_25 ended WIP

**Comment by mreekie** [comment] 2022-07-20 18:31
Steve tried several suggestions on a fix for this including what Jim suggested.
This occurs only on a very narrow screen.
The team is split on priorty.
We'll put this on the queue as a small.

**Comment by sekmiller** [comment] 2022-08-03 14:56
As I mentioned previously, the text of the popups will wrap as expected if the user shrinks the width of the popup itself. Wrapping does not occur if the user shrinks the browser window - the popup moves to accommodate the smaller browser window, but at a certain point the text of the popup can be hidden slightly. This occurs regardless of the "width" setting for the popup either in its definition or the css. At this point I am inclined to punt as we should rely on the user recognizing that resizing the browser window may result in text being hidden.

**Comment by qqmyers** [comment] 2022-08-03 16:55
FWIW: On a Mac Air with 11.6, in Safari and Chrome, looking at demo.dataverse.org today, I do not see the original issue with the dialog shrinking but cutting off text. Instead, I'm seeing what I saw on Windows - the dialog won't shrink unless we change the dialog width:700px to max-width:700px and remove the min-width constraint.

**Comment by scolapasta** [comment] 2022-11-02 17:30
I am going to close this issue - this is a) a fairly minor thing, and b, with the rearchitecture we'll be revamping the UI.

**Closed by scolapasta** 2022-11-02 17:30 UTC
