### ISSUE TITLE
DOI: Broaden support for DOI registration to non US providers

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#896] opened 2014-09-02 14:27 UTC
---

Author Name: **Kevin Condon** (@kcondon)
Original Redmine Issue: 3387, https://redmine.hmdc.harvard.edu/issues/3387
Original Date: 2013-11-12
Original Assignee: Gustavo Durand

---

From Merce, see RT #170142

The DOI registration was implemented using the EZID API. However, this is
only useful if DVN gets DOIs through the Digital California Library (CDL).
This might be true for most US DVNs, but not for DVNs in Europe, for
example. It should be written with a more open architecture, as a
"persistent identifier Service" with modules for different DataCite sites
around the world (even if other write that, it should be easy to extend,
with instructions).

http://thedata.harvard.edu/guides/dataverse-installer-main.html#digital-object-identifiers [Open URL]

Merce

**Comment by pdurbin** [comment] 2015-08-03 12:17
@bencomp just mentioned the potential use of DataCite Netherlands at https://groups.google.com/forum/#!topic/dataverse-community/xVb9a6dY8FQ

**Comment by pdurbin** [comment] 2015-08-03 12:19
Actually, this issue might be a duplicate of #24 but I'm not sure.

**Comment by bencomp** [comment] 2015-08-03 13:02
Talking directly to DataCite to register DOIs (which is #24) seems the most straightforward way to support non-US RAs. As far as I can tell, it is actually the only way. An organisation who wishes to allocate DOIs registers with a local DataCite Member (such as DC NL or DC CA), but everyone uses the same API. So I'd say it's a duplicate.

We must, however, first decide whether we want to use DataCite DOIs or continue to use Handle (which is getting [a major upgrade](http://www.handle.net/mail-archive/handle-info/msg00698.html)).

**Comment by eaquigley** [comment] 2015-08-25 18:45
Closing this ticket as it is a duplicate of #24

**Closed by eaquigley** 2015-08-25 18:45 UTC
Labels: Priority: Medium, Type: Feature
