### ISSUE TITLE
Native API doesn't show Categories or File Tags (at least for "FITS file" and "Image file")

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3067] opened 2016-04-07 15:08 UTC
Dataset with FITS file tag:
     https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:10904/10065

API call used:  https://dataverse.harvard.edu/api/datasets/:persistentId?persistentId=hdl:10904/10065

See this gist for resulting JSON w/o `FITS file` and `Image file`` tags:
   https://gist.github.com/raprasad/1387646984f7c8402278d69f793e5379#example-fits-file

**Comment by kcondon** [comment] 2016-04-21 19:12
@raprasad does this happen for all file tags or only fits?

**Comment by raprasad** [comment] 2016-04-25 13:13
As far as I can tell, all tags.  Including ```Code```, ```Data```, ```Documentation```, etc

**Comment by pdurbin** [comment] 2017-01-03 18:12
This was requested in https://groups.google.com/d/msg/dataverse-community/obUKSqR4GRA/MWKo7bb1EgAJ and the fix is trivial, I think, so I went ahead and made pull request #3553. I'll put this in Code Review at https://waffle.io/IQSS/dataverse

**Comment by pdurbin** [comment] 2017-01-03 18:15
Here's how I tested locally, with a dataset that has two files, one with tags and one without tags:

`curl -s http://localhost:8080/api/datasets/:persistentId?persistentId=doi:10.5072/FK2/G3KNOU | jq '.data.latestVersion.files'`

```
[
  {
    "label": "50by1000.tab",
    "directoryLabel": "example",
    "version": 1,
    "datasetVersionId": 43,
    "tags": [
      "Code",
      "Data"
    ],
    "dataFile": {
      "id": 16,
      "filename": "50by1000.tab",
      "contentType": "text/tab-separated-values",
      "storageIdentifier": "159231994f1-b1509642e2a5",
      "originalFileFormat": "application/x-stata",
      "originalFormatLabel": "Stata Binary",
      "UNF": "UNF:6:x10r+Q9EK6aF/BMi+eKzGw==",
      "md5": "003b8c67fbdfa6df31c0e43e65b93f0e",
      "checksum": {
        "type": "MD5",
        "value": "003b8c67fbdfa6df31c0e43e65b93f0e"
      }
    }
  },
  {
    "description": "",
    "label": "trees.png",
    "directoryLabel": "trees",
    "version": 1,
    "datasetVersionId": 43,
    "tags": [],
    "dataFile": {
      "id": 12,
      "filename": "trees.png",
      "contentType": "image/png",
      "storageIdentifier": "159042c66b3-01aa5fa3c874",
      "originalFormatLabel": "UNKNOWN",
      "md5": "0386269a5acb2c57b4eade587ff4db64",
      "checksum": {
        "type": "MD5",
        "value": "0386269a5acb2c57b4eade587ff4db64"
      },
      "description": ""
    }
  }
]
```

**Comment by pdurbin** [comment] 2017-01-05 18:54
@scolapasta @landreev and I met this morning and in c8b57f8 I believe I implemented the fixes we talked about. Next, I'd like to add some unit tests. Here's the new output:

```
[
  {
    "label": "50by1000.tab",
    "directoryLabel": "example",
    "version": 1,
    "datasetVersionId": 95,
    "categories": [
      "Code",
      "Data"
    ],
    "dataFile": {
      "id": 16,
      "filename": "50by1000.tab",
      "contentType": "text/tab-separated-values",
      "storageIdentifier": "159231994f1-b1509642e2a5",
      "originalFileFormat": "application/x-stata",
      "originalFormatLabel": "Stata Binary",
      "UNF": "UNF:6:x10r+Q9EK6aF/BMi+eKzGw==",
      "md5": "003b8c67fbdfa6df31c0e43e65b93f0e",
      "checksum": {
        "type": "MD5",
        "value": "003b8c67fbdfa6df31c0e43e65b93f0e"
      },
      "tabularTags": [
        "Time Series",
        "Survey"
      ]
    }
  },
  {
    "description": "",
    "label": "trees.png",
    "directoryLabel": "trees",
    "version": 1,
    "datasetVersionId": 95,
    "dataFile": {
      "id": 12,
      "filename": "trees.png",
      "contentType": "image/png",
      "storageIdentifier": "159042c66b3-01aa5fa3c874",
      "originalFormatLabel": "UNKNOWN",
      "md5": "0386269a5acb2c57b4eade587ff4db64",
      "checksum": {
        "type": "MD5",
        "value": "0386269a5acb2c57b4eade587ff4db64"
      },
      "description": ""
    }
  }
]
```

**Comment by pdurbin** [comment] 2017-01-05 21:07
I turns out @raprasad already worked on a similar fix at https://github.com/IQSS/dataverse/blob/6cfc03635e8b878389d5cefe854d03f12bd976f4/src/main/java/edu/harvard/iq/dataverse/util/json/JsonPrinter.java#L525 so I'll probably jump on the 2290-file-replace branch and tweak the code to make it conform to the design above.

**Comment by pdurbin** [comment] 2017-01-06 20:41
In f620c80 I implemented the same fix as above but in the 2290-file-replace branch. That is to say, I changed where "categories" and "tabularTags" appear to be what we want. I added unit tests in cc37155.

One problem I'm having is that while I can set a file description via native API, I can't set the categories. @landreev said this might be a one line fix so I'm adding him to this issue. Check out the change to FilesIT.java in f620c80 to see the REST Assured test in question.

**Comment by pdurbin** [comment] 2017-01-10 17:17
@landreev @scolapasta I'm moving this issue to Code Review in Waffle so that you can check out 6a75c84 where I added the ability to harvest file categories by modifying JsonParser.

**Comment by landreev** [comment] 2017-01-13 20:04
OK, since I have worked both on the branch 2290, and was talking to Phil as he was working on this task (adding the categories and tags); so it was easy to review. 
It all looks great. The only not-entirely-straightforward thing here was the distinction between the "categories" and "tabular tags" - the former go into filemetadata sections, the latter - into the top-level datafile section. And it's all implemented properly now.

The non-trivial part about the logistics of handling this issue is that while the issue is "in review" on waffle, there is no pull request for it yet. Since Phil added this fix to the 2290 branch; and 2290 is still being finished. So I can't formally review it on github yet. So Phil and I agreed that I'll move the issue back into dev., and then, when Steve and Raman make a pull request for the 2290 branch, he'll link this issue to that PR and move it into QA...

**Comment by kcondon** [comment] 2017-01-26 20:36
OK, working. Closing.

**Comment by pdurbin** [comment] 2017-01-26 21:18
@kcondon as I mentioned, there's a harvesting component that could be tested. Please see this comment for details: https://github.com/IQSS/dataverse/issues/3067#issuecomment-271637256

**Comment by kcondon** [comment] 2017-01-27 03:23
@pdurbin json harvest is failing, ddi and dc work

**Comment by pdurbin** [comment] 2017-01-27 14:12
Huh, I only tried JSON harvesting and I just got the stacktrace below as of e8dd342 when I click the "Run Harvesting" button. This may have been pulling the latest without doing a clean and build. Let me restart Glassfish and play with this some more.

```
[2017-01-27T09:07:37.972-0500] [glassfish 4.1] [SEVERE] [] [] [tid: _ThreadID=184 _ThreadName=Thread-9] [timeMillis: 1485526057972] [levelValue: 1000] [[
  java.lang.RuntimeException: java.lang.IllegalStateException: This web container has not yet been started
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1455)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2979)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:489)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
        at edu.harvard.iq.dataverse.harvest.client.FastGetRecord.harvestRecord(FastGetRecord.java:138)
        at edu.harvard.iq.dataverse.harvest.client.FastGetRecord.<init>(FastGetRecord.java:97)
        at edu.harvard.iq.dataverse.harvest.client.oai.OaiHandler.runGetRecord(OaiHandler.java:227)
        at edu.harvard.iq.dataverse.harvest.client.HarvesterServiceBean.processRecord(HarvesterServiceBean.java:326)
        at edu.harvard.iq.dataverse.harvest.client.HarvesterServiceBean.harvestOAI(HarvesterServiceBean.java:272)
        at edu.harvard.iq.dataverse.harvest.client.HarvesterServiceBean.doHarvest(HarvesterServiceBean.java:186)
        at edu.harvard.iq.dataverse.harvest.client.HarvesterServiceBean.doAsyncHarvest(HarvesterServiceBean.java:106)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:55)
        at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
        at sun.reflect.GeneratedMethodAccessor1292.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
        at sun.reflect.GeneratedMethodAccessor1293.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
        at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
        at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
        at com.sun.ejb.containers.EjbAsyncTask.call(EjbAsyncTask.java:101)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: This web container has not yet been started
        at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1674)
```

**Comment by pdurbin** [comment] 2017-01-27 14:23
@kcondon ok, I stopped Glassfish, did `mvn clean` and `mvn package` and now harvesting seems to work via JSON. I'm still on e8dd342. Screenshots below.

![screen shot 2017-01-27 at 9 21 49 am](https://cloud.githubusercontent.com/assets/21006/22374025/4fd28370-e472-11e6-848b-42dfb282379c.png)
![screen shot 2017-01-27 at 9 21 19 am](https://cloud.githubusercontent.com/assets/21006/22374026/4fd7aa3a-e472-11e6-8366-59f48fde8bf6.png)

**Comment by pdurbin** [comment] 2017-01-27 15:02
I just tested harvesting file tags specifically (I'm still on e8dd342 ) and that seems to work too. Here's a screenshot:

![screen shot 2017-01-27 at 10 01 59 am](https://cloud.githubusercontent.com/assets/21006/22375370/c500154a-e477-11e6-9262-cedb947d3826.png)

**Comment by kcondon** [comment] 2017-01-27 16:53
This is working, was a config issue involving certs and siteUrl setting that needed to be documented.

**Closed** 2017-01-27 16:53 UTC
Labels: Component: API, Status: Code Review, Type: Bug

**Comment by pdurbin** [comment] 2017-01-27 16:57
With a self signed cert, this was the error I saw on my laptop in glassfish/domains/domain1/logs/harvest_tab_2017-01-27T11-51-33.log

`<message>Exception processing harvest, server= https://dev1.dataverse.org/oai,format=dataverse_json com.lyncode.xoai.serviceprovider.exceptions.InvalidOAIResponse com.lyncode.xoai.serviceprovider.exceptions.HttpException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target</message>`
