### ISSUE TITLE
OpenStack Integration - Compute Buttons

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#3747] opened 2017-04-04 15:59 UTC
For the Openstack summit in early May, we should allow users to access an OpenStack instance through Dataverse via a "Compute" button or other means (design will fill in detail here).

**Comment by TaniaSchlatter** [comment] 2017-04-12 16:23
Please see UI/UX guidance for the compute button in this document:
https://docs.google.com/document/d/16tFwds9qW3PX4lkuxiglbbqHiQrCeAim_O_evFMZY8w/edit

**Comment by djbrooke** [comment] 2017-04-12 20:45
When this is picked up, work should be done on a different branch created from the Swift branch:

https://github.com/IQSS/dataverse/tree/3747-swift-and-compute-button

**Comment by pdurbin** [comment] 2017-05-01 16:30
@ferrys said we should merge `3747-compute-button-UI` into `3747-swift-with-derivative-file-support` but I didn't want to trash `3747-swift-with-derivative-file-support` so I created a new branch from `3747-swift-with-derivative-file-support` called `2909-3747-swift-compute-button` and merged both `3747-compute-button-UI` and `develop` into it. That branch should be code reviewed. Here's a hand link: https://github.com/IQSS/dataverse/compare/2909-3747-swift-compute-button

I'm moved this issue to Code Review at https://waffle.io/IQSS/dataverse

**Comment by pdurbin** [comment] 2017-05-01 16:34
@ferrys is going to look into publishing not working and will commit a fix to the new `2909-3747-swift-compute-button` branch.

**Comment by pdurbin** [comment] 2017-05-01 17:30
As of e2f5dcc when I click "Publish" I'm seeing `Caused by: javax.el.PropertyNotWritableException: /filesFragment.xhtml @37,163 value="#{DatasetPage.getSwiftContainerName()}": Illegal Syntax for Set Operation`

**Comment by sekmiller** [comment] 2017-05-01 19:32
The Publish Issue has been fixed in the combined branch. Mike is on wiring up the copy button.

**Comment by pdurbin** [comment] 2017-05-02 13:07
912d0a5 and 26d56ca fixed some bugs that cropped up in the `2909-3747-swift-compute-button` branch but with no more features to be added or bugs to be fixed, it should be ready for Code Review. The only thing I can think to do is merge the latest from `3747-swift-with-derivative-file-support` where some bug fixing is going on.

**Comment by pdurbin** [comment] 2017-05-02 14:56
@mheppler there are some important bug fixes in `3747-swift-with-derivative-file-support` that I'd like to merge into `909-3747-swift-compute-button`. Please ping me to let me know when you're done making commits so I can should proceed with this. Thanks.

Also, @landreev made some comments about UI implications of the "Download URL" link when a Dataverse installation is configured for Swift: https://github.com/IQSS/dataverse/issues/2909#issuecomment-298446655 . Heads up to @TaniaSchlatter @mheppler @dlmurphy @jggautier

**Comment by pdurbin** [comment] 2017-05-02 15:02
Oh, in addition to bug fixes, I just merged `develop` into `3747-swift-with-derivative-file-support` because the branch had merge conflicts with `develop`. That's the other reason I'd like to merge `3747-swift-with-derivative-file-support` into `2909-3747-swift-compute-button`. Alternatively, we can wait until `3747-swift-with-derivative-file-support` is merged into `develop` and merge `develop` into `2909-3747-swift-compute-button`. Otherwise, we won't be able to make a pull request due to merge conflicts.

**Comment by pdurbin** [comment] 2017-05-02 16:00
In 85d221f I merged `3747-swift-with-derivative-file-support` into  `2909-3747-swift-compute-button` to pick up the latest bug fixes and resolve conflicts between `2909-3747-swift-compute-button` and develop so that we can someday make a pull request based on `2909-3747-swift-compute-button`.

If anyone is interested in more context for when we added the Download URL, see #3584: Provide Download URL for Public Files.

**Comment by mheppler** [comment] 2017-05-02 19:07
UI clean up and various other loose enough have been tied up. Documentation placeholder on the Dataset + File Management pg in the User Guide is ready when the documentation is.

**Comment by mheppler** [comment] 2017-05-02 19:10
As part of the UI clean up on the dataset and file pg associated with this issue, we also resolved this issue, **Version number display #3706**.

**Comment by kcondon** [comment] 2017-05-05 20:09
A few issues:
1. Compute button appears to guest user but according to UX doc it should not. Need to verify requirement or fix
2. help text on dataset pg needs a space between icon and first letter of text.
3. when you click the copy button (in FF at least) you are bounced up to the top of the page, so the link needs a `return:false;` or some other JS in there.
4. Potentially change "To learn more about Cloud Storage Access, visit the Cloud Storage Access section of the User Guide." to be less redundant: to learn more, visit the Cloud Storage Access section...
5. Editing Swift file metadata, specifically tags fails with error or silently doesn't add them.

**Comment by mheppler** [comment] 2017-05-05 20:36
Fixed jumping issue with Copy button, and spacing and grammar issues with help text in Cloud Storage Access block.

**Comment by kcondon** [comment] 2017-05-05 20:46
Yes, #2-#4 are fixed, just whether compute button appears to guest and excessive logging on dataset load, happens with both local and swift files but more with swift. 13 cat images also a good test case ;)

**Comment by dlmurphy** [comment] 2017-05-15 15:49
Just added new material about Cloud Dataverse to the Installation and User guides. 

@mheppler, I recommend checking the Guides link in the Cloud Storage Access help text on the dataset page to make sure it still correctly links to the Cloud Storage Access section of the Dataset Management section of the user guide. I tried to set it up so it'll still work, but I want to make sure.

**Closed** 2017-05-17 22:55 UTC
