### ISSUE TITLE
API regression: sometimes dataverseAdmin becomes creator of all dataverses and datasets created via native API

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2318] opened 2015-07-06 17:26 UTC
Something happened with the API in the 4.0.2 branch (I'm on c02e100 currently) whereby dataverses created via API have `@dataverseAdmin` as their creator even if an API token for another user is used.

In this example we look up the API token for user "finch"...

`curl -s http://localhost:8080/api/builtin-users/finch/api-token?password=finch | jq .`

```
{
  "data": {
    "message": "96825b49-2263-49d0-a8fb-766eec1358ac"
  },
  "status": "OK"
}
```

... then we use that API token to create a dataverse. Notice that under "creator" that it says `"identifier": "@dataverseAdmin"` when `"identifier": "@finch"` is expected:

`curl -s -H Content-type:application/json -X POST -d @scripts/search/data/in/dv-birds1/1 'http://localhost:8080/api/dataverses/root?key=96825b49-2263-49d0-a8fb-766eec1358ac' | jq . `

```
{
  "data": {
    "creator": {
      "displayInfo": {
        "email": "dataverse@mailinator.com",
        "Title": "Dataverse Admin"
      },
      "identifier": "@dataverseAdmin"
    },
    "id": 22,
    "alias": "birds",
    "name": "Birds",
    "dataverseContacts": [
      {
        "contactEmail": "birds@birds.com",
        "displayOrder": 0
      }
    ],
    "permissionRoot": true,
    "description": "A bird dataverse with some trees",
    "ownerId": 1,
    "creationDate": "2015-07-06T17:19:51Z"
  },
  "status": "OK"
}
```

I'm hoping that if we fix this regression the other regression I reported about being unable to delete datasets will also be resolved: #2313.

**Comment by pdurbin** [comment] 2015-07-06 17:58
Later I tried using "junk" as an API token and I was able to create a dataverse (also with dataverseAdmin as the creator). Then I restarted Glassfish and got the expected `"message": "Bad api key 'junk'"` error. This is all on my laptop. Very strange. I'm pretty sure I can reproduce it by re-running my https://github.com/IQSS/dataverse/blob/master/scripts/database/homebrew/rebuild-and-test script, which I've done several times by this point. Anyway, it feels like the system somehow gets in a weird state and restarting Glassfish helps? I'm not sure.

**Comment by pdurbin** [comment] 2015-07-06 19:07
I deployed a war file built from c02e100 (part of 4.0.2 branch) to https://shibtest.dataverse.org and I'm getting similarly strange behavior. The "trees" dataverse has an admin of `@dataverseAdmin` rather than `@spruce` like I expect.

The scripts I'm running are very minor variations on https://github.com/IQSS/dataverse/tree/master/scripts/deploy/apitest.dataverse.org

![permissions_-_trees_dataverse_-_2015-07-06_15 05 58](https://cloud.githubusercontent.com/assets/21006/8530710/9284258c-23f0-11e5-9a83-ecc01ec848dc.png)

**Comment by pdurbin** [comment] 2015-07-06 20:01
I did a little more testing on https://shibtest.dataverse.org and I'm quite confident that we didn't have these problems as of the 4.0.1 tag.

**Comment by michbarsinai** [comment] 2015-07-06 21:50
I had similar issues for the initial implementation of #2123. The issue there was stale data in the injected fields of AbstractApiBean - namely, the request http headers containing the API key. The issue was resolved by using `@Context` to inject a `HttpServletRequest` rather than `@HeaderParam`.
I was not able to reproduce this issue (stale `@HeaderParam`) on a clean GF project, and switching to the `@Context` solved the problem.

We might have dependency injection issue again....

**Comment by pdurbin** [comment] 2015-07-07 12:19
@michbarsinai interesting. And disturbing. Your "stale data" theory would explain why the creator unexpectedly becomes `@dataverseAdmin` since that's the user that creates the root dataverse. Also, as I was telling @scolapasta I don't believe the SWORD API is affected by this bug. When I go to create a dataset via SWORD it seems to always look up the correct user properly. I'm guessing this is because the SWORD classes do not extend `AbstractApiBean`.

The question is how can we get the code back to how it was before this regression was introduced. I don't think we can easily revert fa26ec8 (I tried) and we definitely want the feature that commit introduced for #2123.

**Comment by pdurbin** [comment] 2015-07-07 12:28
@scolapasta I'm giving this to you to assign to someone. I went ahead and marked this as a critical bug. Heads up to @kcondon .

**Comment by pdurbin** [comment] 2015-07-09 15:20
Rather than using **my** scripts that (I think) only I use and that I mentioned at https://github.com/IQSS/dataverse/issues/2318#issuecomment-118939414 the easiest way I've found to reproduce this bug is to uncomment the "setup-optional.sh" script in "setup-all.sh" and observe that Pete's dataverses have dataverseAdmin as the creator (admin role) rather that Pete.

**Comment by pdurbin** [comment] 2015-07-10 15:02
From some (minimal) testing I've done d9f866a seems like a good fix. Thanks @michbarsinai !

**Comment by kcondon** [comment] 2015-07-20 21:01
Verified this is working for the above mentioned case. Was able to create dv as pete and api key of junk was rejected. Closing.

**Closed by kcondon** 2015-07-20 21:01 UTC
Labels: Component: API, Component: Code Infrastructure, Priority: Critical, Status: QA, Type: Bug
