### ISSUE TITLE
IP Groups: Continue to support IP Groups for v4.0 and add better support for specifying ranges such as subnets.

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#700] opened 2014-07-09 15:40 UTC
---

Author Name: **Kevin Condon** (@kcondon)
Original Redmine Issue: 4156, https://redmine.hmdc.harvard.edu/issues/4156
Original Date: 2014-06-25
Original Assignee: Gustavo Durand

---

Retaining IP Group authentication was mentioned as being a requirement by a current partner.

Note: there are two types of notation we might consider supporting: subnetwork notation and CIDR notation.

This was originally requested here: 

#60969: v2.0 - IP Groups: Need to support adding ip addresses by ranges that don't span entire octet.
https://help.hmdc.harvard.edu/Ticket/Display.html?id=60969

I recently needed to add some large ip address ranges that did not 
cover the entire octet (number between the decimals). 

For example: 199.94.0.*-199.94.47.* required me to enter 48 individual 
addresses.

Then recently here: 

#180843: Feature request: support for subnet notation when defining IP groups
https://help.hmdc.harvard.edu/Ticket/Display.html?id=180843

Not sure if this is on the agenda at all, and it's a minor point, but it
would be really useful to be able to define IP groups using subnet
notation rather than just * as a wildcard.

Our use case is, we have some universities with multiple class C
networks in the middle of a range. (e.g. 134.117.10-135). No easy way to
input this at present.

**Comment by michbarsinai** [comment] 2015-01-20 09:53
Role assignment via API now supported. Permissions granted to IP groups are given to the user as requested.

Now struggling with the UI crashing in the roles page.

**Comment by michbarsinai** [comment] 2015-01-20 10:24
Ready for QA.
Notes for testing:
* I'm unsure how permissions granted via groups work with search in the UI, so may be better to test via API initially.
* For IP groups, one can spoof the IP address by adding the "X-Forwarded-For" header. May be easier than creating and removing groups and assignments.

**Comment by kcondon** [comment] 2015-01-21 19:09
@michbarsinai I'm getting a foreign key constraint error when attempting to add the sample ip group from ipGroup1.json, see below. I've tried without a key, since that is how it is presented in the doc but that sounds like a bug and with the admin key and get the same error.

Call: INSERT INTO IPV4RANGE &#40;ID, BOTTOMASLONG, TOPASLONG, OWNER_ID&#41; VALUES &#40;?, ?, ?, ?&#41;
	bind =&gt; [4 parameters bound]
Query: InsertObjectQuery&#40;[IpAddressRange 60.0.0.255-60.0.0.0]&#41;</pre></p><p><b>root cause</b> <pre>Exception [EclipseLink-4002] &#40;Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd&#41;: org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: insert or update on table &quot;ipv4range&quot; violates foreign key constraint &quot;fk_ipv4range_owner_id&quot;
  Detail: Key &#40;owner_id&#41;=&#40;303&#41; is not present in table &quot;persistedgroup&quot;.
Error Code: 0
Call: INSERT INTO IPV4RANGE &#40;ID, BOTTOMASLONG, TOPASLONG, OWNER_ID&#41; VALUES &#40;?, ?, ?, ?&#41;
	bind =&gt; [4 parameters bound]
Query: InsertObjectQuery&#40;[IpAddressRange 60.0.0.255-60.0.0.0]&#41;</pre></p><p><b>root cause</b> <pre>org.postgresql.util.PSQLException: ERROR: insert or update on table &quot;ipv4range&quot; violates foreign key constraint &quot;fk_ipv4range_owner_id&quot;
  Detail: Key &#40;owner_id&#41;=&#40;303&#41; is not present in table &quot;persistedgroup&quot;.</pre></p><p><b>note</b> <u>The full stack traces of the exception and its root causes are available in the GlassFish Server Open Sou

**Comment by pdurbin** [comment] 2015-01-21 20:13
> For IP groups, one can spoof the IP address by adding the "X-Forwarded-For" header.

@michbarsinai this is just for testing, right? You'll be taking this out? Is there a ticket for this? Being able to spoof an IP address so easily is alarming.

**Comment by kcondon** [comment] 2015-01-21 20:48
All of the create, list, delete functions work with basic test data. Having trouble assigning a role, have asked Michael for advice.

**Comment by michbarsinai** [comment] 2015-01-21 20:57
@pdurbin indeed. But this is how apache tells Glassfish who sent the request originally. We can do a test, but I assume apache would overwrite the header if someone was spoofing it.
Maybe we should add a Setting for this, so admins can turn the functionality off.

**Comment by pdurbin** [comment] 2015-01-21 23:39
> I assume apache would overwrite the header

Please keep in mind that we are not 100% sure that we will be fronting Glassfish with Apache we have only ever seen the session bug in #647 when Glassfish is fronted with Apache.

@michbarsinai I'm asking you to think about the scenario where Glassfish is **not** fronted with Apache and the security implications of letting users specify the "X-Forwarded-For" header.

**Comment by michbarsinai** [comment] 2015-01-22 13:22
very good point. also easy to solve. I'll open an issue.

**Comment by michbarsinai** [comment] 2015-01-22 13:25
Created https://github.com/IQSS/dataverse/issues/1368

**Comment by kcondon** [comment] 2015-01-23 19:54
Basic functionality in place, opened tickets for completing integration with rest of app. Closing

**Closed by kcondon** 2015-01-23 19:54 UTC
Labels: Priority: High, Status: QA, Type: Feature

**Comment by pdurbin** [comment] 2016-10-03 19:20
See also pull request #3103 which was merged in 4.5.1 to address #1380 and related issues.
