### ISSUE TITLE
Files/Datasets: Show which pdf or image file has been selected as default thumbnail

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1712] opened 2015-03-18 15:55 UTC
Have something that signifies on the dataset page which image or pdf file is the default thumbnail without having to go into Advanced Options.

This needs to be after a user selects a file as the default thumbnail in the Edit Files view as well as in the view mode.

**Comment by scolapasta** [comment] 2015-03-18 18:04
Closing as a duplicate of #1653

**Comment by posixeleni** [comment] 2015-03-27 17:36
As @scolapasta mentions above this ticket is a duplicate of #1653 so I will close this one.

**Closed by posixeleni** 2015-03-27 17:36 UTC
Labels: Component: File Upload & Handling, Component: UX & Upgrade, Status: QA
