### ISSUE TITLE
500: Internal Server Error  upon  https://dataverse.harvard.edu/api/dataverses/icpsr/contents?key=

### ISSUE THREAD

**Issue by yarikoptic** [IQSS/dataverse#3058] opened 2016-04-04 13:41 UTC
```
$> wget  'https://dataverse.harvard.edu/api/dataverses/icpsr/contents?key=SENSORED' 
--2016-04-04 09:32:48--  https://dataverse.harvard.edu/api/dataverses/icpsr/contents?key=c87766ca-e34c-4e9c-a23e-be277265074c
Resolving dataverse.harvard.edu (dataverse.harvard.edu)... 128.103.69.227
Connecting to dataverse.harvard.edu (dataverse.harvard.edu)|128.103.69.227|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2016-04-04 09:33:49 ERROR 500: Internal Server Error.
```

**Comment by pdurbin** [comment] 2016-04-04 13:44
I encouraged @yarikoptic to open this issue at http://irclog.iq.harvard.edu/dataverse/2016-04-04 but on second thought I think this may well be a duplicate of #2122 given the size of the icpsr dataverse. As of this writing I see 8,967 datasets at https://dataverse.harvard.edu/dataverse/icpsr which may be too many for the "contents" API to handle.

**Comment by yarikoptic** [comment] 2016-04-04 13:50
could well be I guess, and the same story FWIW if I request for id 1

**Comment by mheppler** [comment] 2016-10-10 14:27
Closing in favor of #2122 as @pdurbin suggested above. Moved the code snippet from @yarikoptic to that older issue.

**Closed by mheppler** 2016-10-10 14:27 UTC
