### ISSUE TITLE
Special terms  on dataset make the redirection to external tool goes wrong

### ISSUE THREAD

**Issue by Thanh-Thanh** [IQSS/dataverse#5354] opened 2018-11-29 08:29 UTC
Hello all,

We have configured our dataverse to use TwoRavens and Data Explorer. It worked well the two tools.
However, when the dataset has special terms activated, before viewing the file in external tool, we have a popup asking for agreement. The redirection from this popup is always to TwoRavens. 

Thanks in advance for correcting the bug.

Best regards,
Thanh Thanh

**Comment by pdurbin** [comment] 2018-11-29 12:02
@Thanh-Thanh thanks for the bug report. Which version of Dataverse are you running? Thanks.

**Comment by Thanh-Thanh** [comment] 2018-11-29 12:54
@pdurbin We're running Dataverse 4.9.1, but I'm not sure whether the bug is from this version. Thanks!

**Comment by djbrooke** [comment] 2020-07-22 16:51
Hi @Thanh-Thanh - I'm going to close this as a possible duplicate of #6923, which covers similar behavior in a newer version.

**Closed by djbrooke** 2020-07-22 16:51 UTC
Labels: Feature: External Tool
