### ISSUE TITLE
API test suite failures on develop as of ca48b59

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#5686] opened 2019-03-26 23:48 UTC
As the screenshot below from https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/344/testReport/ indicates, there are several API test suite failures on develop as of ca48b59 that we should fix before our next release, which is planned to be 4.12.

<img width="1603" alt="Screen Shot 2019-03-26 at 7 46 30 PM" src="https://user-images.githubusercontent.com/21006/55040729-0ffd6e80-5000-11e9-9aa3-b38ac75bc3fe.png">

**Comment by pdurbin** [comment] 2019-03-26 23:54
I just updated the list of tests on phoenix from...

`test -Dtest=DataversesIT,DatasetsIT,SwordIT,AdminIT,BuiltinUsersIT,UsersIT,UtilIT,ConfirmEmailIT,FileMetadataIT,FilesIT,SearchIT,InReviewWorkflowIT,HarvestingServerIT,MoveIT -Ddataverse.test.baseurl='http://phoenix.dataverse.org'`

... to this...

`test -Dtest=DataversesIT,DatasetsIT,SwordIT,AdminIT,BuiltinUsersIT,UsersIT,UtilIT,ConfirmEmailIT,FileMetadataIT,FilesIT,SearchIT,InReviewWorkflowIT,HarvestingServerIT,MoveIT,MakeDataCountApiIT -Ddataverse.test.baseurl='http://phoenix.dataverse.org'`

... which is the list from https://github.com/IQSS/dataverse/blob/81f87013350af931c9e1e871606d3f5e56ef50de/conf/docker-aio/run-test-suite.sh and I am re-running the tests.

**Comment by pdurbin** [comment] 2019-03-27 00:08
Bah, there's still some work to do on the "deploy" step for phoenix, as I commented about at https://github.com/IQSS/dataverse/issues/5649#issuecomment-476904502

**Comment by pdurbin** [comment] 2019-03-27 00:48
Ok, I fixed the deployment issue (the dvnapp database user needed more permission) and now we can see the Make Data Count error reported in #5662 by @pameyer (thanks!):

<img width="1375" alt="Screen Shot 2019-03-26 at 8 46 07 PM" src="https://user-images.githubusercontent.com/21006/55042561-6a023200-5008-11e9-95a5-94b53214aa54.png">

This is from https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/345/testReport/

**Comment by pameyer** [comment] 2019-03-27 15:56
This is a duplicate of #5662 (FilesIT hadn't been erroring out when the title went on that one); so feel free to close that one.

**Comment by pdurbin** [comment] 2019-03-27 20:16
Please note that I've already fixed the make data count error by adding the following line to https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-build-develop/configure

`scp src/test/java/edu/harvard/iq/dataverse/makedatacount/sushi_sample_logs.json phoenix.dataverse.org:/tmp/sushi_sample_logs.json`

Here's a screenshot for more context:

![Screen Shot 2019-03-27 at 4 15 26 PM](https://user-images.githubusercontent.com/21006/55109186-98851900-50ab-11e9-83de-f5c20bba69f2.png)


The rest of the fixes are in pull request #5692

**Closed** 2019-03-28 00:18 UTC
Labels: Status: Code Review
