### ISSUE TITLE
For harvesting, allow advanced feature of using listRecords vs ListIdentifiers

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#10936] opened 2024-10-18 15:13 UTC
Currently, havrvesting uses ListIdentifers then called GetIdentifier for each record.

However, the DataCite OAI only supports sets via ListRecords. So we want to allow a harvesting client (on our side) to use ListRecords so we can harvest Sets from DataCite.

(This would go away of we DataCite begins to support sets with ListIdentifiers)

**Comment by scolapasta** [comment] 2024-10-18 15:15
As a quick "hack" we could just get the list of identifiers from list records, and then still call GetIdentifier for each identifer. This, of course, would result in getting double in the info from DataCite, but would be a fairly quick thing to add.

The more complete solution would be to use the data as well from ListRecords. In this case, we would have to make sure to handle the case where one (or more) harvest fails, while still allowing the others to succeed - the reason we currently split the calls up via GetIdentifier in the first place.

**Comment by scolapasta** [comment] 2024-10-18 15:42
Sized as a 10 with the idea that we would start with the quick fix; we should resize appropriately if we decide we want to use the 2nd approach instead.

**Comment by landreev** [comment] 2024-10-18 20:47
I just proposed in a direct slack to close this issue, since it's a duplicate of 1/2 of #10909. The 2 items under #10909 can of course be separately implemented; but since the overall delivery of being able to harvest from DataCite appears to be an urgent/asap task, splitting the 2 does not really offer any benefit. Testing the 2 things separately would be a bit convoluted however and has some potential for creating unnecessary overhead. 

Also, I am not super comfortable with the ListRecords -> GetRecord solution. The common sense test here is that I would be upset if somebody were harvesting from my servers like that. I would rather implement it properly. It's not going to be a 10 for sure, but should not be an insane amount of work either.

**Comment by landreev** [comment] 2024-10-22 13:14
Closing as a duplicate of #10909.

**Closed by landreev** 2024-10-22 13:14 UTC
Labels: NIH CAFE, GREI 3
