### ISSUE TITLE
Metadata Selection For A Dataverse Reset To Default

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2095] opened 2015-04-25 00:50 UTC
User reported (RT https://help.hmdc.harvard.edu/Ticket/Update.html?id=214953) that all of a sudden they started seeing a field they had "hidden" from showing in their dataverse (Depositor) https://dataverse.harvard.edu/dataverse/socialsciencercts so when they went in to Edit "General Information" to hide the field their metadata and facet settings had disappeared (see screenshot below). When I went in to recreate I saw a red validation error message saying that the Dataverse Category was not selected even though it was and the Metadata and Facets were the system default ones so I had to try to recreate their setup for them to quickly resolve the issue.
![image](https://cloud.githubusercontent.com/assets/5013837/7330785/5e9bbb24-eac3-11e4-97cb-3521ef4a0665.png)

**Comment by sekmiller** [comment] 2015-05-01 13:30
We've been unable to recreate this issue.  I've checked with Eleni and she had no more insight into the steps required to do so.  At this point all we have is that it happened - there are screenshots - but that's all.

**Comment by posixeleni** [comment] 2015-05-20 18:18
@sbarbosadataverse just had another user report this same issue and can replicate it

**Comment by sbarbosadataverse** [comment] 2015-05-20 18:36
@scolapasta

**Comment by scolapasta** [comment] 2015-05-20 19:43
These issue is being caused by duplicate entries being created in the DataverseFieldTypeInputLevel table for a dataverse and datasetfield.

While we don't know the cause of that, we shouldn't allow it to happen, so we will add a unique constraint on the db aide.

**Comment by sekmiller** [comment] 2015-05-21 14:33
Constraint added to entity

**Comment by sekmiller** [comment] 2015-05-26 18:46
Script Added to upgrade sql

**Comment by kcondon** [comment] 2015-06-01 22:54
Closing.

**Closed by kcondon** 2015-06-01 22:54 UTC
Labels: Component: Metadata, Component: UX & Upgrade, Priority: High, Status: QA, Type: Bug
