### ISSUE TITLE
Unable to search for non-latin characters

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1274] opened 2014-12-18 16:27 UTC
To test non-latin character searching in Dataverse. I created a dataset with a title in Chinese characters (based on a dataset in Fudan University's Dataverse http://hdl.handle.net/11521/61933):

Title:
浙江省人口发展报告(四)

When I tried to search for the dataset I received a no results found and instead of the Chinese characters the search box now has random looking latin characters but the URL still displays the Chinese characters correctly.

![image](https://cloud.githubusercontent.com/assets/5013837/5491678/f9ffff46-86a8-11e4-9f7c-a7f71dadf029.png)

**Comment by landreev** [comment] 2015-01-20 20:53
This is a duplicate of #818. 
Should be working now - see attached. 
![search_accents_2](https://cloud.githubusercontent.com/assets/737558/5825847/664751e0-a0bc-11e4-9507-7283e8fb6e91.png)

**Comment by kcondon** [comment] 2015-01-20 23:03
Tested, used: 方彝, works in both simple and adv search, closing.

**Closed by kcondon** 2015-01-20 23:03 UTC
Labels: Component: Search/Browse, Status: QA, Type: Bug
