### ISSUE TITLE
File Permissions: Granting File Access to Group

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#2232] opened 2015-06-02 19:56 UTC
When I create a group, I am able to assign it a role to a dataverse or dataset, but I can not grant it access to a restricted file. To replicate, follow these steps:

1. As the dataverseAdmin, create group in the Edit Dataverse > Permissions page.
2. Go to dataset with restricted files, and navigate to Edit Dataset > Permissions > Files page.
3. Click the "Grant Access to Users/Groups" button.
4. Type in group name/identifier into User/Group field of the Grant File Access popup.
5. "No matches found" is returned by the dropdown select.

UPDATE: Apparently, locally, this is only an issue when creating groups through the UI (#92) and not when using the script found at scripts/search/tests/ipgroup-add.

**Comment by pdurbin** [comment] 2015-11-03 14:45
@posixeleni as we discussed, please let me know if you can reproduce this issue. (@bencomp [put it on my radar](http://irclog.iq.harvard.edu/dataverse/2015-10-29#i_26328) the other day.)

I'm realizing now that it probably is still an issue since #2241 is probably a duplicate. :/

**Comment by mheppler** [comment] 2016-10-06 16:24
I believe that this issue has been fixed in [4.5.1](https://github.com/IQSS/dataverse/releases/tag/v4.5.1) or earlier. Having retested this locally, I can no longer reproduce this issue. Sending to QA.

**Comment by kcondon** [comment] 2016-10-13 19:30
Works, closing.

**Closed by kcondon** 2016-10-13 19:30 UTC
Labels: Component: File Upload & Handling, Component: Permissions, Status: QA
