### ISSUE TITLE
DOI: Investigate making DOI format support more generic, don't assume a specific shoulder or separation character.

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#898] opened 2014-09-02 14:27 UTC
---

Author Name: **Kevin Condon** (@kcondon)
Original Redmine Issue: 3400, https://redmine.hmdc.harvard.edu/issues/3400
Original Date: 2013-12-05
Original Assignee: Gustavo Durand

---

This ticket came about as a result of a user ticket, RT #171102

EZId demo creates a DOI that has not / after the shoulder. Freeman in the above ticket has existing DOIs that do not have a / after the shoulder and wants to import them. Since we assume a / after the shoulder, this would not work. So, this request is to remove any assumptions about shoulder and separators after the shoulder.

Merce felt we should adopt this general approach to improve future interoperability.

---

Update by @pdurbin on 2018-05-21

connects to #3583

**Comment by kcondon** [comment] 2016-05-16 16:27
The shoulder separator should not be part of authority but rather the identifier per examples on EZID site.
Also Sherry from UVa commented about this since they did not intend to use /.

**Comment by scolapasta** [comment] 2016-05-16 16:27
Reference: https://wiki.ucop.edu/display/DataCite/Identifier+Concepts+and+Practices+at+the+California+Digital+Library

**Comment by pdurbin** [comment] 2017-02-02 14:41
Related: #3583.

**Comment by tdilauro** [comment] 2017-02-02 15:32
We are definitely affected by this insistence on separator between the shoulder and remainder of the identifier mentioned in #898. This has forced us to change our identifier structure to accommodate Dataverse 4. This problem seems to affect only minting and validation (and the implementation detail of how a DOI is stored in the database). Fortunately -- because we can't change them -- our older identifiers still work (e.g., when re-registering all datasets after migration). 

Our shoulder is 10.7281/T1. Our earlier identifiers look like "doi:10.7281/T10Z715B" and are stored in the db (protocol, authority, identifier) like "doi  | 10.7281    | T10Z715B". The new ones look like "doi:10.7281/T1/XS93KD" (note the extra separator after "T1") and are stored in the db like "doi | 10.7281/T1 | XS93KD".

There is no way to configure ":Authority" in DV 4 such that we would get identifiers of the earlier form. It would be nice to be able to set ":Authority" as "10.7281/T1" (no trailing slash) to get what we used to get or as "10.7281/T1/" to get what we are currently getting. Or to have something like this that provides comparable control.

**Comment by pdurbin** [comment] 2017-07-13 01:50
Closing as a duplicate of #3583.

**Closed** 2018-06-01 17:53 UTC
Labels: Feature: Code Infrastructure, Feature: Metadata, Feature: Publishing & Versions, Status: QA, Type: Feature
