### ISSUE TITLE
Deaccessioning: What should show in search card?

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1221] opened 2014-12-05 20:52 UTC
I deaccessioned a dataset and only I can see the search card (good). But it still shows the thumbnail and the description. - should it only show the citation?

**Comment by pdurbin** [comment] 2015-03-06 21:06
I'm a little confused by this ticket.

First, the thumbnail images are controlled by code by @landreev so at some point it would be best for him to consider that part.

Second, all this talk of what's indexed and searchable for deaccessioned datasets will complicate the code but I'll do what I can. Maybe it would be easier if @posixeleni and @eaquigley and @scolapasta look at the list below and tell me which fields **should** be indexed and searchable for deaccessioned datasets:

      {
        "id":"dataset_10_deaccessioned",
        "entityid":10,
        "identifier_s":"doi:10.5072/FK2/0MUGVG",
        "persistent_url_s":"http://dx.doi.org/10.5072/FK2/0MUGVG",
        "dvtype":"datasets",
        "release_or_create_date_dt":"2015-03-06T16:57:45.27Z",
        "date_en":["Mar 6, 2015"],
        "publication_date_s":"2015",
        "dsPublicationDate_s":"2015",
        "dataset_version_id_l":1,
        "citation_s":"Spruce, Sabrina, 2015, \"Spruce Goose\", <a href=\"http://dx.doi.org/10.5072/FK2/0MUGVG\">http://dx.doi.org/10.5072/FK2/0MUGVG</a>,  Root Dataverse,  V1,  DEACCESSIONED VERSION ",
        "dsDescriptionValue":["What the Spruce Goose was really made of."],
        "authorName":["Spruce, Sabrina"],
        "authorName_ss":["Spruce, Sabrina"],
        "subject":["N/A"],
        "subject_ss":["N/A"],
        "name_sort":"Spruce Goose",
        "title":"Spruce Goose",
        "depositor":"Spruce, Sabrina",
        "subtree_ss":["/7",
          "/7/8"],
        "parentid":"8",
        "parentname":"Spruce",
        "_version_":1494924628450082816}

And we're saying the **reason** should be searchable? I don't index that at all currently.

**Comment by posixeleni** [comment] 2015-03-06 22:00
Hi folks,

My two cents: I honestly don't think deaccessioned datasets should even be searchable in the UI. You should only get to a deaccessioned dataset page if, for example, you are trying to access it via a data citation (DOI or handle URL) someone put in a paper or if it belongs to you.

-Eleni

**Comment by pdurbin** [comment] 2015-03-06 22:10
@posixeleni where were you went we [designed the indexing rules](https://docs.google.com/document/d/1lFcwjtdGIqqQLYYnwtTI2GZNzmzYlrnMk2omGcXO9oY/edit?usp=sharing) for deaccessioning?! ;)

**Comment by scolapasta** [comment] 2015-03-07 17:33
to be clear @posixeleni, deaccessioned studies are not public. They are searchable for those who have the view permission. (or at least it *should* work this way). Since we use solr for all listings of datasets, that is why it needs to be indexed.

That said, I don't see much gain in indexing the reason, unless others do. Other fields being searchable: I think maybe they should be - for example if I search by author name, I think I should still see the deaccessioned ones? I'm OK with any decision on this.

I originally opened the issue for the display of the card. 

So, let's discuss on Monday and finalize what to display and what is searchable and be set for 4.0.

**Comment by posixeleni** [comment] 2015-03-07 20:35
Wait, @scolapasta, I am confused now. There should be a publicly viewable landing page for deaccessioned studies. Are you saying this is not the current functionality?

--
Eleni Castro
Research Coordinator, Data Acquisition and Archiving, Data Science
IQSS, Harvard University
http://www.iq.harvard.edu/people/eleni-castro

We're redesigning Dataverse and want your feedback! Please check out our Beta Site.<http://dataverse-demo.iq.harvard.edu/>

**Comment by scolapasta** [comment] 2015-03-07 21:11
Sorry for the confusion. Us there is a landing page. I was referring to them not being returned in a public search.

**Comment by pdurbin** [comment] 2015-03-09 13:16
> I honestly don't think deaccessioned datasets should even be searchable in the UI

But should you be able to **browse** to a deaccessioned dataset? (Browse is powered by search, a wildcard search.) Since I already extracted the indexing rules for https://github.com/IQSS/dataverse/issues/57#issuecomment-65466348 it probably won't hurt to put them here again:

![deacc-rules](https://cloud.githubusercontent.com/assets/21006/6555396/fd7858f8-c63b-11e4-89e0-a0d14df64c78.png)

Notice that it's uncommon for a deaccessioned dataset to be indexed at all. It only happens when there is no published version and there's no draft. And as @scolapasta said, only someone with permission can see it. The thinking at the time is that **someone** should be able to **browse** to the deaccessioned dataset. Otherwise it exists in the system but there's no way to get at it unless you have bookmarked the link. Again, for more of the thinking behind the design, please see the [Google doc](https://docs.google.com/document/d/1lFcwjtdGIqqQLYYnwtTI2GZNzmzYlrnMk2omGcXO9oY/edit?usp=sharing) from which the screenshot above was taken. Honestly, I think if we're going to make a change, it could probably wait until after 4.0.

**Comment by posixeleni** [comment] 2015-03-09 16:27
@pdurbin I misunderstood the search functionality. I thought it was for public searching but thanks to Gustavo's clarification I think its ok people who have access/permissions to the deaccessioned dataset already to be able to search for it. Sorry for my confusion

**Comment by pdurbin** [comment] 2015-03-09 18:35
> I originally opened the issue for the display of the card.

@scolapasta for the display of the card (no indexing or backend or Search API changes) we could add a little logic in the place where we add the blue "Deaccessioned" label...

```
if (datasetVersion.isDeaccessioned()) {
    solrSearchResult.setDeaccessionedState(true);
+    String deaccessionReason = datasetVersion.getVersionNote();
+    if (deaccessionReason != null) {
+        solrSearchResult.setDescriptionNoSnippet(deaccessionReason);
+    }
}
```

... to at least replace the description with the deaccession reason while **browsing**. (Search behavior would remain the same.)

Sounds like you'd like to chat with @eaquigley about the final decision tomorrow so I'll pass it to her for now.

**Comment by scolapasta** [comment] 2015-03-10 19:48
So reviewed with @eaquigley and decided:

- No changes to what is indexed - since this is private already, you should be able to search based on the metadata

- Display should should the default icon, the citation, and the deaccesioned reason.

- Ideally search API should work the same way

**Comment by pdurbin** [comment] 2015-03-13 15:51
> Ideally search API should work the same way 

@eaquigley and @scolapasta do you have a preference for either of these?

- "deaccession_reason": "There is identifiable data in one or more files. "
- "deaccessioning_reason": "There is identifiable data in one or more files. "

This would appear in the JSON returned by the Search API once #1299 is complete.

**Comment by pdurbin** [comment] 2015-03-13 17:07
@eaquigley I made a change that I'd like you to review. In the UI, the deaccessioned reason now replaces the description for deaccessioned study. The description is still searchable ("no change to what is indexed"). @eaquigley if you're happy with this, please pass it to @landreev to work on which icon is displayed.

(Technically, I am indexing a new field into Solr but don't worry about that. I left a [todo](https://github.com/IQSS/dataverse/commit/7e19df7865cbf30d20e2baa69ac6ad8c4d34404b#diff-1d33a1df4fba34b71107b782707dcf18R159) to make it non searchable. It's in there so the Search API can return the "deaccession_reason" field. In the Search API I'm not overwriting the description, which I think would be odd.)

**Comment by mheppler** [comment] 2015-03-13 17:17
Related to #1670. To be reviewed in our UI Review Part II meeting.

**Comment by eaquigley** [comment] 2015-03-17 20:48
@pdurbin after two demos and two usability sessions, i can confirm that having the deaccession reason appearing in the card instead of the dataset description has been well received. passing to @landreev as the above comment mentioned.

**Comment by eaquigley** [comment] 2015-03-17 21:07
@pdurbin one thing though that is happening with deaccessioned migrated datasets is the dataset description is appearing is in the card instead of nothing.

**Comment by pdurbin** [comment] 2015-03-17 22:14
> with deaccessioned migrated datasets

Hmm, I wonder what makes them different.

**Comment by jggautier** [comment] 2018-07-09 21:44
It seems that the only unaddressed suggestion in this github issue is about the thumbnails: The search card and landing pages of deaccessioned datasets should show only the default dataset icon (and not show whatever thumbnail the dataset had before it was deaccessioned).

In Dataverse 4.9.1, the search card and landing pages of deaccessioned datasets **do** show the thumbnails that the dataset had before it was deaccessioned. If guest users have a deaccessioned dataset's URL (https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/R3TJBS) or persistent ID (https://doi.org/10.7910/DVN/R3TJBS), they can see the thumbnail. I imagine this could be a problem if the deaccession reason was related to data privacy concerns.

@scolapasta, is the thumbnail issue the only unaddressed issue in this github issue? Could we open a new one for it (and close this one)?

**Closed** 2020-06-11 17:24 UTC
Labels: Feature: Search/Browse, Status: UX & UI, Type: Bug, User Role: Curator
