### ISSUE TITLE
Access API: Multi-file "bundle" download doesn't retrieve all files it should.

### ISSUE THREAD

**Issue by evelynPM** [IQSS/dataverse#2493] opened 2015-09-03 00:02 UTC
According to the documentation at http://guides.dataverse.org/en/latest/api/dataaccess.html, a bundle should include the following:

Tab-delimited; “Saved Original”, the proprietary (SPSS, Stata, R, etc.) file from which the tabular data was ingested; Generated R Data frame (unless the “original” above was in R); Data (Variable) metadata record, in DDI XML; File citation, in Endnote and RIS formats.

However a bundle retrieved through the Data Access API from https://apitest.dataverse.org/ included only the TAB file, the DDI XML and the citation files, not the original SPSS file or an R derivative.

**Comment by pdurbin** [comment] 2015-09-03 00:22
This was on v. 4.1 build 71 from dataset http://dx.doi.org/10.5072/FK2/0MOPJM with the tab file below which I uploaded to Google Drive for safe keeping: https://drive.google.com/a/harvard.edu/file/d/0B_qMYwdHFZghOXhMVnNHdkl3elE/view?usp=sharing

![metadata_mapping_test_study_-_artefactual_systems_dataverse_-_2015-09-02_20 18 11](https://cloud.githubusercontent.com/assets/21006/9647883/d728207a-51af-11e5-8808-517116b841b7.png)

**Comment by pdurbin** [comment] 2015-10-23 15:32
I just selected all the files (2 of them) from https://apitest.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/FK2/0MOPJM running v. 4.2 build 92-d6443eb and clicked "Download" and @evelynPM is right, the zip file does not contain a file called "Weather_data.sav". These are the files in the zip:

MD5 (MANIFEST.TXT) = 96645b45eeefb0e0bf77e5df8a7152cd
MD5 (Weather_data.tab) = ea0ceb96c2d5b67c539e91aecd812e79
MD5 (chelan 052.jpg) = c77cea64f072d317bf7a9c8a9ed03b0f

I'm flagging this as a bug. Sorry for not doing this earlier. Heads up to @scolapasta and @landreev .

**Comment by landreev** [comment] 2015-11-10 19:44
In the original user's question, they are talking about a different "bundle". 
We have a function in the API, where, yes, you can call the access API on a given file and request the "all-format bundle". And yes, it will give you a zip file that contains all the available formats, including the original. It should be working as advertised, to the best of my knowledge. 

We have however removed it from the UI at some point (it used to show in that pulldown download menu, in addition to "original", "tab-delimited", etc.)
 
@pdurbin, what you tried was a "multiple files download", still available on the dataset page. 
The fact that the original is not in the resulting zip file is not a bug, in a sense that this is how it was meant to work. 
The actual datafile that we store and serve is weather_data.tab, and it's included in the zip file. 
We do keep the original stata file from which the tab file was produced (weather_data.sav); but you have to ask for it separately. Either on the page or via the API. 

This is how we've been handling it back in the DVN since forever. 
Granted, in DVN 3* we had an option for uploading a Stata file as is, without trying to convert it to tabular data. In case someone wanted to serve the original Stata file more prominently. 

If we want to change this - always include the originals in the zip bundle; or to bring back the "don't convert" option - should be very easy to do.

**Comment by landreev** [comment] 2015-11-10 19:47
p.s. 
@pdurbin:  the api call in question is 

/api/access/datafile/bundle/{fileId}

(will retest it on api-test shortly)

**Comment by landreev** [comment] 2015-11-10 19:55
Uh, ok, the original report is actually correct: the "saved original" appears to be missing from the API access "bundle": 

$ wget -O /tmp/foo.zip  "http://localhost:8080/api/access/datafile/bundle/91"

HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: “/tmp/foo.zip”

2015-11-10 14:52:21 (262 KB/s) - “/tmp/foo.zip” saved [180399]

$ zipinfo /tmp/foo.zip 
Archive:  /tmp/foo.zip
Zip file size: 180399 bytes, number of entries: 4
-rw----     2.0 fat   563285 bl defN 15-Nov-10 14:52 Weather_data.tab
-rw----     2.0 fat    15337 bl defN 15-Nov-10 14:52 Weather_data-ddi.xml
-rw----     2.0 fat      619 bl defN 15-Nov-10 14:52 Weather_datacitation-endnote.xml
-rw----     2.0 fat      325 bl defN 15-Nov-10 14:52 Weather_datacitation-ris.ris
4 files, 579566 bytes uncompressed, 179817 bytes compressed:  69.0%

I can take this ticket and fix it.

**Comment by landreev** [comment] 2015-11-10 20:09
OK, so I'm going to fix the /access/datafile/bundle call; 
And I'm going to change the title of the ticket, adding the words "access API/bundle" - to avoid confusion. 
If we want to modify the behavior of the multi-file zip to include all these aux. files - let's do that in a different ticket.

**Comment by landreev** [comment] 2015-11-23 17:23
Should be working properly, as of next dev 4.2.2 build (the original file should be in the bundle).

**Comment by kcondon** [comment] 2015-11-24 22:33
OK, works. Got all files listed in the UI download list. Closing.

**Closed by kcondon** 2015-11-24 22:33 UTC
Labels: Status: QA, Type: Bug
