### ISSUE TITLE
Permissions: Root dataverse access permissions not correctly enforced if contributor creates a dataverse.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4744] opened 2018-06-07 01:44 UTC
Reported by an installation here: https://help.hmdc.harvard.edu/Ticket/Display.html?id=262722

Root dataverse access perms are set to any user account can create dataverses and datasets but receive contributor permissions on dataset creation. This works initially -when a user creates a dataset in root they are a contributor and see the submit for review button. However, if they create a dataverse in root, they get admin perms on that dataverse and appears as admin, contributor in the user dashboard. When that user now checks their root dataset, they have publish ability. This only seems to happen with the root dataverse and does not affect other dataverses.

**Comment by djbrooke** [comment] 2018-06-11 13:27
I'm going to close this one, feel free to reopen if it verifies or if we receive additional information from the installation.

**Closed by djbrooke** 2018-06-11 13:27 UTC
Labels: Status: Backlog

**Comment by pdurbin** [comment] 2018-06-11 13:44
To be clear, the reason this was closed is that we were unable to reproduce it: https://help.hmdc.harvard.edu/Ticket/Display.html?id=262722#txn-5512871
