### ISSUE TITLE
Select multiple datasets for compute 

### ISSUE THREAD

**Issue by ferrys** [IQSS/dataverse#4246] opened 2017-10-30 18:25 UTC
As a user of secure multi party computation, I would like to be able to select multiple datasets at one time so I can compute on them together in my computing environment.

**Comment by ferrys** [comment] 2017-11-08 19:50
Some notes from a meeting today with @TaniaSchlatter:

The current UI implemented by the cloud class last semester allows a user to select multiple datasets by going to the dataset page and adding the current dataset to a compute batch. We want to change this functionality a little bit, by adding a dropdown at the top of the dataset page which contains something similar to:

<img width="510" alt="screen shot 2017-11-08 at 2 48 23 pm" src="https://user-images.githubusercontent.com/15023025/32570962-e65acb98-c493-11e7-8ff7-a994291828c3.png">

**Comment by ferrys** [comment] 2018-01-17 17:28
In the 4246-compute branch, there is now a 'Compute Batch' dropdown button:
<img width="1167" alt="screen shot 2018-01-17 at 12 15 34 pm" src="https://user-images.githubusercontent.com/15023025/35056609-5e9e749c-fb80-11e7-8cab-88565e2de8ae.png">

The dropdown options allow users to 'Add to Compute Batch', 'Delete from Compute Batch', 'List Compute Batch' and 'Compute on Compute Batch':
<img width="1171" alt="screen shot 2018-01-17 at 12 15 51 pm" src="https://user-images.githubusercontent.com/15023025/35056879-24b3fb70-fb81-11e7-9d18-e5f313abf50f.png">

**Comment by TaniaSchlatter** [comment] 2018-01-17 18:26
Comments:
- move the button to the right of Edit
- treat the button as the same button type as "Download" – gray and shaded
- change the button text to "Compute" (drop "Batch") for consistency with the button at the file level 
- use render logic to display only one dropdown link for "Add Dataset to Batch" vs "Delete Dataset from Batch"
- edit the text in the drop down items: "Add to Batch", "Delete from Batch", "List Batch", "Compute on Batch"

Add success and error messages for these actions.

**Comment by mheppler** [comment] 2018-01-31 17:42
**What we are building**

Dataset Pg
- Compute button dropdown, at dataset-level, for computing a dataset (opens external tool in new window), or adding it to a batch list of multiple datasets to compute together
- Conditionally rendered actions remove, list, clear and compute options available if there is a batch of datasets, also available in the dropdown
- Validation success/error messages

Compute Batch Popup
- Compute Batch dataTable listing all dataset contained in the batch list
- Remove button for each dataset in the table, clear button for the batch list above table, compute button (opens external tool in new window) and cancel (closes popup) below table

**Comment by kcondon** [comment] 2018-02-28 22:01
After talking with folks it seems this feature is essentially a shopping cart for data, with the exception that the cart disappears when the session expires.

The new thing is a compute button near the top of the dataset page. Initially the users cart (batch list) is empty. The only options are compute dataset (just go to compute now, ignore cart) or add to batch (cart). Once anything is added to the user's batch, a larger list appears under compute for dataset: Remove from batch, list batch, clear batch, compute batch. Compute always takes you to the compute url.

This all works as expected. I'm told :publicinstall is not required and you do not need to be the data owner but you do need to be logged in to see the compute button. Confirmed. There is an open question on how datasets with restricted files are to be handled. Gustavo will work with Sarah on it.

From Sarah:
In terms of what you should see: 
- if you have compute enabled, the compute button in the corner shows up
- you should always be able to see the 'compute dataset' option 
- if you have no datasets in the cart, you should see 'compute dataset' and 'add to batch'
- if you have a dataset in the cart, you should see 'compute dataset', 'add to batch' OR 'remove from batch', 'list batch', 'clear batch' and 'compute batch'

- you will see 'remove from batch' if the specific dataset you're on is in the batch, or add vice versa

**Comment by djbrooke** [comment] 2018-02-28 22:24
@ferrys are you picking this up?

**Comment by djbrooke** [comment] 2018-02-28 22:31
Just saw Kevin's note, assigning to Gustavo and Sarah.

**Comment by mheppler** [comment] 2018-03-15 17:31
Minor UI improvements to message text and other code clean up found in code review:

Dataset Pg
- Changed confirmation popup header to read just "Compute" as that is the action the user is in the process of accessing
- Revised msg displayed when trying to compute on a file you do not have access to `dataset.compute.computeBatchRestricted=This dataset contains restricted files you may not compute on because you have not been granted access.` which is more consistent with other permissions related validation msg's
- Changed confirmation popup button to read "Close" rather than "Cancel" as there is no action to cancel
- Removed old `datasetComputeAccessDeniedPopup` popup and related bundle text that is no longer needed now that the batch functionality has been addedFile Pg
- Revised msg displayed when trying to compute on a file you do not have access to `file.compute.fileAccessDenied=This file is restricted and you may not compute on it because you have not been granted access.` which is more consistent with other permissions related validation msg's
- Changed confirmation popup button to read "Close" rather than "Cancel" as there is no action to cancel
If all that sounds kosher, I will commit the changes and add this info to the ticket. If you could, please pull these changes and confirm I didn't break nothing in a properly setup compute+swift environment. I am going to double check right now that I removed my "true" calls I hacked into the render logic.

**Closed** 2018-04-05 18:33 UTC
