### ISSUE TITLE
When uploading files, have an option to restrict files before clicking save

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#386] opened 2014-07-09 15:38 UTC
---

Author Name: **Elda Sotiri** (@esotiri)
Original Redmine Issue: 3801, https://redmine.hmdc.harvard.edu/issues/3801
Original Date: 2014-04-02
Original Assignee: Gustavo Durand

---

Sonia suggested this feature. It would be very handy especially for zip files.

**Comment by scolapasta** [comment] 2015-01-20 16:32
This is a duplicate of #792 (this one is older, but designs were added to #792, so leaving that one as the open issue)

**Comment by kcondon** [comment] 2015-01-20 23:17
Closing as duplicate.

**Closed by kcondon** 2015-01-20 23:17 UTC
Labels: Priority: Medium, Status: QA, Type: Feature
