### ISSUE TITLE
File upload: Page is broken after file ingest completes, can't publish or download tabular files.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1469] opened 2015-02-18 19:14 UTC
I created a dataset, saved. Uploaded akiotestfiles.zip, waited for it to complete ingest and then clicked publish, nothing happened. Left page, came back and it works.

**Comment by scolapasta** [comment] 2015-02-19 16:50
@landreev can you see what is happening here?

**Comment by scolapasta** [comment] 2015-02-20 21:45
assigning to beta 14 so @landreev can review if it is critical or easy. If neither, then this can be deferred.

**Comment by kcondon** [comment] 2015-03-04 18:29
Also download button for subsettable files is broken.

**Comment by landreev** [comment] 2015-03-11 17:23
I believe I have fixed this, with just one extra ajax update.
The problem with this issue is that it appeared to be very intermittent (the same ingest could leave either or both of the 2 buttons disabled, or leave both buttons working ok... seemingly unpredictably)
I haven't been able to reproduce the problem since I made the change... but can't be 100% sure it's never coming back.

**Comment by sbarbosadataverse** [comment] 2015-03-18 20:48
Uploaded tabular file (spss portable)
File ingest via drag and drop  - successful
explore tab file -  successful
delete tab file -failed* see previous ticket on deleting files not working
download tab file (Selected original spss portable format) = Internal Server Error - An unexpected error was encountered, no more information is available.

**Comment by kcondon** [comment] 2015-03-18 22:01
This ticket was mainly about the page breaking after index with the various function/ buttons not responding. Sonia's testing and mine shows this issue is resolved.

The download as R Data issue is a known issue and has another ticket.
The delete file issue is a known issue and has another ticket. 
I was not able to reproduce the download as tab issue. Will follow up with Sonia.

**Closed** 2015-03-18 22:09 UTC
Labels: Priority: Medium, Status: QA, Type: Bug
