### ISSUE TITLE
download all files does not download all files.

### ISSUE THREAD

**Issue by smakonin** [IQSS/dataverse#4051] opened 2017-08-09 01:41 UTC
Using my dataset (http://dx.doi.org/10.7910/DVN/FIE0S4) which has 88 files. Check the "all" checkbox and click the download button. Less than 88 files are downloaded. Sometimes on 20 and sometimes only 37.

All 88 file should be downloaded.

**Comment by pdurbin** [comment] 2017-08-09 10:45
@smakonin thanks for the bug report. It looks like #3711 may be related.

**Comment by pdurbin** [comment] 2017-10-27 15:32
@djbrooke and I discussed this issue yesterday during my one on one. We agreed that it sounds like a bug. Needs investigation.

**Comment by pdurbin** [comment] 2017-11-01 20:20
We just had a nice discussion about this issue during backlog grooming today and it sounds like we're going to try an approach where if the user clicks the box under "88 files" in the screenshot below, we'll set some sort of "all" boolean in the backend and zip up all the files, regardless of what the PrimeFaces component shows as check or unchecked for each file. When we pick up issue I think we could close #3711 as a duplicate of this one.

![screen shot 2017-11-01 at 4 14 27 pm](https://user-images.githubusercontent.com/21006/32295471-c6d25738-bf1f-11e7-8353-23531cd2b080.png)

Longer term #3404 enumerates a number of problems with how files are handled on the dataset page.

**Comment by sekmiller** [comment] 2017-12-06 15:22
I have a partial fix due to the limitations of the Primefaces table component. In my fix, if a user clicks the "Select All" and then download, she will get all of the files downloaded. However if another user selects all then de-selects one or more files in the table, then downloads he will still get all of the files.

Is this an acceptable improvement?

**Comment by pdurbin** [comment] 2017-12-06 15:23
I suspect the most common case is the user think, "Just let me download all the files and I'll sort them out on my laptop." That is to say, yes, I think this is an improvement.

**Comment by sekmiller** [comment] 2017-12-06 16:35
Based on our Stand-up discussion I am moving to Code Review

**Comment by mheppler** [comment] 2017-12-14 20:20
Fixed scrolling bug associated with CSS hack in previous scrolling bug fix (836d2484e748bb90b49e811928e8bba1bc969ef9).

I was attempting to add extra spacing to the bottom of the files table in order to display dropdown menus for the Download, Explore, Configure buttons. Unfortunately I added the space to the wrong containing element. This should now be fixed. Sorry @sekmiller.

**Comment by sekmiller** [comment] 2017-12-19 19:20
In its final version, (at least for this ticket) if a user clicks the checkbox at the top of the table then clicks the Download button he will get all of the files. If after clicking the select all box the user has any other interaction with the table at the file level (unselect or select) before clicking the download button then they will only get the files physically selected in the table.

**Comment by kcondon** [comment] 2017-12-19 20:14
Works except if in draft.

**Closed** 2017-12-19 21:16 UTC
Labels: Feature: File Upload & Handling, Status: QA, Type: Bug, User Role: Guest
