### ISSUE TITLE
Performance: Opening restricted file permissions and adding a user very slow for larger dataset, assignment list.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3450] opened 2016-11-03 16:21 UTC
Reported by Sonia. Not sure yet whether this is an issue where a threshold was passed or intermittent.

As reported:
It's the MADICS dataset in Murray..I work with this often and I noticed right away how slow it was today...

navigate to MADICS, select "permissions-restricted files",---this is where a weird box shows up around permissions....it has 45 restricted files....permissions dialogue box finally pops up, i add name, comes up fine, i hit 'save" and adding takes much longer that expected. Again, I do this dataset often enough to observe this change.

As tested by me:
I was able to see slowness just accessing the dataset and opening restricted file permissions. 
I'm wondering whether this is a growing list/ threshold issue: the algorithm is slow and we are now hitting a threshold on # of assigned users + # restricted files + determining permissions for display purposes at each step: listing files on dataset page, listing assigned users on permissions page. Not sure about the insert/add part. Adding took me 10 seconds or so.Removing took 30sec. Might there be an opportunity for lazy loading on this page? Seems like with all the info, it might be loading everything up front.

**Comment by mheppler** [comment] 2018-02-02 18:55
@kcondon I believe this might be a duplicate of **Permissions: Grant access errors for large # of files #2641**. I can copy your comment over and close this one.

**Comment by kcondon** [comment] 2018-02-02 19:26
@mheppler I'd rather not since that other ticket discusses specific behavior and is more confusing that this one. True, they both have to do with adding user access to restricted files. This one is about performance, that one is about misreporting # files, and generally bad behavior in the UI for a large list.

**Comment by mheppler** [comment] 2020-02-11 15:15
Investigate if related to _Code Cleanup - Refactor autoComplete components to be more efficient, avoid duplicate id warnings in server logs #6360_.

**Closed** 2024-08-20 15:25 UTC
Labels: Type: Bug, Feature: Permissions, Feature: Performance & Stability, User Role: Depositor
