### ISSUE TITLE
200+ files uploaded to Harvard Dataverse failed ingest during one month in 2017

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3675] opened 2017-03-08 11:47 UTC
Between 2/4/2017 and 3/8/2017 (today), over 4,300 DataFiles received an **ingest status**\* of "error".

A cursory glance at several files shows that they have not been converted to tabular files and remained in their native formats.

Minimal file information, including links to the files may be found here: 

https://services.dataverse.harvard.edu/miniverse/qc/bad-ingest-list

(When this becomes actionable, more info can be supplied re: file name/content type)

  - \* Note: It may be possible that an ingest status of "error" may not reflect the underlying state--that the process went ok.

**Comment by pdurbin** [comment] 2017-03-08 14:38
Yikes! In the same time period, how many files were successfully ingested? What percentage failure vs. success are we seeing?

What does the pull request for this issue look like? How does the code change?

What's the relationship between this issue and #585 #2626 or #3288?

**Comment by raprasad** [comment] 2017-03-08 16:33
fyi: ingest failure icon only shows when the owner is logged in.

screen shot below from a public dataset when logged in as an admin/superuser:

---

![poweful_women_and_aspirations_in_india_-_the_abdul_latif_jameel_poverty_action_lab_dataverse](https://cloud.githubusercontent.com/assets/1036060/23713163/043947f0-03f3-11e7-9b36-f2d1c7711577.png)

**Comment by pdurbin** [comment] 2017-03-08 20:51
Related ticket: https://help.hmdc.harvard.edu/Ticket/Display.html?id=246242

**Comment by donsizemore** [comment] 2017-03-09 16:26
This issue prompted me to install miniverse and point it at a test server running an import of our production database. It may or may not be helpful for me to note that Odum shows 11 ingest failures, all between Oct. and Nov. 2016 when Thu-Mai and Sophia ran into ingest problems right after our migration. All STATA 13, and thank goodness none since.

Odum is still running the 4.5 release. We had planned to update, but put on the brakes when we saw this issue.

**Comment by raprasad** [comment] 2017-03-09 16:28
@donsizemore : we'll have more data this week but it looks like the vast majority of the ingest failures were Excel files from a specific user.  will keep you updated.

**Comment by landreev** [comment] 2017-03-09 19:41
@donsizemore and everybody: 

Don, I honestly don't think there is any reason to delay the upgrade on account of this issue! 

- These failures were not caused by anything unique to the (4.6) production version; 

- 4100+ of these failures ARE ACTUALLY THE SAME FILE. We have a user who (for some reasons) maintains his research as thousands of separate datasets that he creates with some automated script. Each one of them contains this same Excel spreadsheet, which consistently fails to ingest as tabular data. 

- Which is actually ok with him. His research is not quantitative science per se. That spreadsheet contains some bibliographic information, but not anything anyone would want or need to run statistical analysis on... which brings us to the next item: 

- Please note that these are not fatal, catastrophic failures. "Failed ingest" in this context meant failed to convert to tabular data. I.e. we failed to extract the additional metadata describing the data columns in these files, that would allow exploring the data in TwoRavens. But the files were still added successfully to the datasets, and the users can still download them as is - as Excel, Stata, etc. files. The red triangles with the ingest failure messages are only shown to the owner of the dataset. 

- Among the remaining files the number of Stata failures (86) is a bit high, unfortunately (Stata is our best supported format, really). But tabular ingest is something we've been trying to improve continuously. We will never be able to guarantee a 100% success rate - since this involves trying to parse third party proprietary formats - but we can definitely keep improving it. 

(Personally I've been advocating revisiting tabular ingest and its performance for a while; but we've had to ration our development time, to address other feature requests and issues, etc.)

**Comment by raprasad** [comment] 2017-03-09 21:42
changing title, to exclude single file repeated 4,100 times.

more accurate link is here: 207 files.  

https://services.dataverse.harvard.edu/miniverse/qc/bad-ingest-list?exclude_filesize=1226912
(Note url parameter)

**Comment by landreev** [comment] 2017-03-10 19:43
To add a bit more context for these stats: 

There were 87 Stata ingest failures (1 more recorded since yesterday) during this period (since Feb. 4); vs. 326 successful Stata ingests during the same time frame. 
Which makes it a 79% success rate. While not abysmal, this is not a good success rate. 
Based on our historical experience, I consider 90+ % to be a "good" rate.

Probably another reason to try to allocate some dev. time to tabular ingest. I'm almost positive there should be at least some relatively easy possible fixes that would improve this ratio.

**Comment by landreev** [comment] 2017-03-10 19:45
I really love miniverse though!  And I'm already thinking of extra features/improvements for these report pages - like maybe a checkbox to "hide duplicates" vs. "show all"; plus "sort by size", by file type, show success ratios, etc. etc.

**Comment by landreev** [comment] 2017-03-10 19:52
(if/when we make a new iteration of the ingest driver improvements, we'll need to make some decisions - do we just give the dataset owners an ability to "try again" on these files that failed to ingest the first time around? or do we automatically try to re-ingest? - but then, if that succeeds, we'll probably have to automatically create new versions of at least some datasets... do we want to do that? - All interesting questions)

**Comment by pdurbin** [comment] 2017-05-25 11:18
@landreev @raprasad what is the definition of done for this issue? Does it help at all that we have addressed #3768 in the upcoming 4.6.2 release?

**Comment by raprasad** [comment] 2017-06-07 15:03
Follow-up on this.  The link in the comment above still holds:

https://services.dataverse.harvard.edu/miniverse/qc/bad-ingest-list?exclude_filesize=1226912

As of today, the failure symbol appears on: **884 Files** within **432 datasets** and 87 dataverses 

  - **March 9, 2017**: 207 files
  - **June 7, 2017**: 884 files

It is a steady, near daily occurrence.  A way for the user to remove the failure message may be appropriate

![mozilla_firefox](https://user-images.githubusercontent.com/1036060/26885492-c9c821d4-4b70-11e7-84fd-359309f6131a.png)

**Comment by pdurbin** [comment] 2017-06-13 11:30
@raprasad @landreev what do you think of #3893 ("Cannot remove/delete failed ingest datafile")?

**Comment by pdurbin** [comment] 2018-05-31 17:27
I just noted the usefulness of this "bad ingest" list at https://github.com/IQSS/dataverse/issues/2301#issuecomment-393609757 as I work on Stata 13 bugs and support for Stata 14 and 15. Thanks, @raprasad !

**Comment by raprasad** [comment] 2018-05-31 20:18
@pdurbin: Not sure if it's as helpful now but you can exclude some of the files via `exclude_filesize`:

- e.g. https://services.dataverse.harvard.edu/miniverse/qc/bad-ingest-list?exclude_filesize=1226912
  (I think the link above excludes 4k+ files)

(it was a 1-off when the page was overloaded with the same file uploaded many, many times to different datasets giving an error...)

**Comment by landreev** [comment] 2018-05-31 20:26
@pdurbin @raprasad Or you can just download that list and sort-uniq it by md5...

**Comment by pdurbin** [comment] 2018-06-12 14:23
I spoke to @kcondon about this issue this morning and I don't feel like much value is being added by keeping it open so I'm closing it. In practice, we just check the database for ingest failures and grab the files to run them through tests. That's been our process for pull request #4708. I also don't think we plan to run miniverse forever for Harvard Dataverse.

**Closed by pdurbin** 2018-06-12 14:23 UTC
Labels: Feature: File Upload & Handling
