### ISSUE TITLE
Allow for empty directories

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#6627] opened 2020-02-07 21:19 UTC
description from Google groups (https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/dataverse-community/JorBq9OxhMA/2sdictMNAgAJ):

A researcher would like to ingest a data set with a complex folder hierarchy, mostly to do with the organization of scripts and dependencies related to the data.  This hierarchy also includes empty folders.  However, these folders are removed in the upload process, presumably because there are no files with associated folder/location metadata from which to derive the folder information.

**Comment by djbrooke** [comment] 2020-02-10 15:38
Closed #5683 as a duplicate of this.

**Comment by pdurbin** [comment] 2022-12-22 11:22
This "create folder in folder" thread is related:

- https://groups.google.com/g/dataverse-community/c/7L0wZc_3frg/m/EcJO0JrjEAAJ

**Comment by cmbz** [comment] 2024-08-20 15:21
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Closed by cmbz** 2024-08-20 15:21 UTC
Labels: Feature: File Upload & Handling
