### ISSUE TITLE
Files Advanced Options: Updates

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1653] opened 2015-03-12 16:37 UTC
- [x] Tags---need these to display on file cards. Use labels in another color.
- [x] Something showing an image is the default. “Used as dataset image/icon/thumbnail”

**Comment by scolapasta** [comment] 2015-03-18 18:04
From #1712:

Have something that signifies on the dataset page which image or pdf file is the default thumbnail without having to go into Advanced Options.

This needs to be after a user selects a file as the default thumbnail in the Edit Files view as well as in the view mode.

**Comment by landreev** [comment] 2015-03-18 18:51
@mheppler 
Mike, 
This is the code you would need for the render logic, to add these extra things to the file boxes on the dataset page: 
(these are things that are only visible inside the "advanced options" menu as of now)

1) "Data Tags" (only available for tabular data files); 
these will be displayed similarly to the file categories; but in a different color: 

"#{fileMetadata.dataFile.tags}" will return the list of tags for this tab file, if present; 
"!(empty fileMetadata.dataFile.tags)" - will tell you if the file has any tags... etc. 

2) For images:
To tell if this image has been selected to be used as the thumbnail for the entire dataset: 
rendered="#{DatasetPage.isDesignatedDatasetThumbnail(fileMetadata)}"

please make sure you have the latest code.

**Comment by mheppler** [comment] 2015-03-23 22:29
@eaquigley -- to clarify -- "Tags---need these to display on file cards. Use labels in another color."

That means that the tags need to be displayed on the browse/search cards of the dataverse page, right? Those tags are already displayed on the dataset page.

If that is the case, I'll need to get new render logic from @landreev and have him discuss with @pdurbin and @landreev to make sure that information is being indexed.

**Comment by mheppler** [comment] 2015-03-23 22:58
Added "Thumbnail" label to the file which is the Dataset Thumbnail in Upload + Edit Files table on the dataset page.

Went above and beyond added a tooltip to the label, to let the user know what it means, as well as how to edit it.
````
The thumbnail for this file is used as the default thumbnail for the dataset. Click 'Advanced Options' button of another file to select that file.
````
(Just realized that I checked in the single quotes, which should be double quotes. I assume this message will be edit, please also clean up that snafu.)

**Comment by mheppler** [comment] 2015-03-23 23:01
@landreev -- Passing back to you. Your render logic I used on this "Thumbnail" label doesn't render if the thumbnail is selected by default, and only when a user has selected the Advanced Option. Please look into how the default thumbnail is selected and make it that it actually sets the setting you are checking in that render logic ("#{DatasetPage.isDesignatedDatasetThumbnail(fileMetadata)}").

**Comment by scolapasta** [comment] 2015-03-24 15:21
Confirmed with @mcrosas  that that tags are only for the file cards on the dataset page.

**Comment by landreev** [comment] 2015-03-25 19:47
@mheppler 
Mike, this is how it works. 
The "advanced options" is the only place where you can select an image to be the thumbnail.
There's no such thing as "selected by default" - if no specific thumbnail is selected, it just grabs the first image in the dataset it can find (there's no guarantee that the same image will be selected on different occasions). 
This should encourage users to select specific images to represent their datasets, if they care at all.

**Comment by mheppler** [comment] 2015-03-25 20:30
@landreev -- confirmed with @mcrosas that leaving this "grab the first image" as a default, without setting the "use this image" checkbox is fine for 4.0.

However, in my previous comment, I explained that your render logic ("#{fileMetadata.dataFile.tags}") for the tags in the browse/search cards doesn't work. Can you clarify or come by and help me figure out what I'm doing wrong?

**Comment by landreev** [comment] 2015-03-25 20:51
Didn't notice that, sorry.
That render logic  was for the dataset page only. It won't work in the search fragment because it doesn't know what  "filemetadata" is. (it's the row name of the files table in dataset.xhtml).

In the search fragment, try this:

#{result.entity.tags}

and if that isn't working either, @scolapasta  will know how to get it to work.

All that said, are you sure the tab file tags need to be displayed in the search cards?
I thought when @eaquigley  was saying "file cards" she meant the file entries on the dataset page (?)

**Comment by mheppler** [comment] 2015-03-25 21:21
@landreev @scolapasta -- That displays: "{IndirectList: not instantiated}" on the file card. Do I need a ui:repeat or some jazz?

Yes, @mcrosas has requested tags on the browse/search cards.

**Comment by mcrosas** [comment] 2015-03-25 21:36
I'm confused!

- I just wanted to make sure that tags that apply to a file are shown for
each file card. This is sufficient for 4.0 (there could be MANY tags for a
dataset that has 100s of files, so if we want to show then in the dataset
cards, we would need to figure out how many we display, etc).
- What do I mean by a file card? The file card inside a dataset page or a
file card return in a search result.

@landreev is there more difficulty to show the tags in the file card from a
search? If this adds a lot more work, let me know.

**Comment by mheppler** [comment] 2015-03-25 21:55
@mcrosas @landreev -- Here is what is being asked for on the browse/search file cards.

![screen shot 2015-03-25 at 5 49 05 pm](https://cloud.githubusercontent.com/assets/687227/6836367/9d26bd94-d317-11e4-83dd-3c942c872442.png)

**Comment by landreev** [comment] 2015-03-25 22:00
@mcrosas 
No, it's not that difficult to show the tags in both places (dataset page and dataverse/search results pages). It's just something minor that needs to be figured out there (the 2 pages use different ways of access the metadata).

I did initially assume that we wanted the files on the dataset page only. So I only told Mike how to access these tags from there.

**Comment by mcrosas** [comment] 2015-03-25 22:12
OK, thanks @landreev and thanks @mheppler


Now that I see it in more detailed I realized that the TAGS I was referring
were the tags that say "geospatial" "survey" "time series" etc for tabular
files (not the categories). But I guess they are all (both categories and
tabular types) considered TAGS, right?

**Comment by mheppler** [comment] 2015-03-25 22:14
Do we even have "tags" (not categories) implemented anywhere on the site?

**Comment by landreev** [comment] 2015-03-25 22:16
@mheppler 
@scolapasta 
And you are positive the file you are testing has assigned tags? 
Gustavo says he will take a look at this. 

Once you can get the tags list, you should be able to get away with something like 

```
   <ui:fragment rendered="#{!(empty result.entity.tags)}">
      <ui:repeat value="#{result.entity.tags}" var="tag">
         <h:outputText value="#{tag.typeLabel}" styleClass="label label-info (OR SOMETHING)"/>
      </ui:repeat>
   </ui:fragment>
```

So yeah, I guess I should've mentioned that you need tag.typeLabel to get the actual string representing the type of the tag.

**Comment by landreev** [comment] 2015-03-25 22:56
@mcrosas 
I've been trying to use the word "tag" to only refer to these special "data tags", that only apply to tabular files. So that they are not confused with the file categories...

But yes, it is potentially confusing. Somebody who's just learning the Dataverse terminology may not initially see the difference between "tag" and "category". 

I guess the solution is to try and always use the long, self-explanatory forms - "Data File Category" and "Tabular Data File Tag", at least in the documentation...

**Comment by mheppler** [comment] 2015-03-26 00:11
Sorry for the confusion on this ticket. The two tasks outlined in the original comment have been completed. Separate bug (#1775) and UI clean up (#1776) tickets have been created for issues this ticket discovered.

**Comment by posixeleni** [comment] 2015-09-17 15:45
Based on the original request this is working as expected. Closing.

**Closed by posixeleni** 2015-09-17 15:45 UTC
Labels: Priority: High, Status: QA
