### ISSUE TITLE
Can not create a dataset, in a particular published dataverse

### ISSUE THREAD

**Issue by Thanh-Thanh** [IQSS/dataverse#5936] opened 2019-06-12 09:28 UTC
Hi all,

We're upgrading to dataverse v4.10.1. We got 1 error when trying to create a dataset in a particular dataverse. And we've reproduced the bug on the demo website :

Within this dataverse https://demo.dataverse.org/dataverse/tests-ng-s123, we can not create any dataset, with the following error :

_This page contains the following errors:
error on line 129 at column 17: AttValue: " or ' expected
Below is a rendering of the page up to the first error._

Thanks in advanced for any further information,

Best regards,
Thanh Thanh

**Comment by pdurbin** [comment] 2019-06-12 10:19
Hi @Thanh-Thanh thanks for reporting this issue.

Last week this bit me as well. @pdante-ubc had reported a bug at #5929 about metadata blocks other than the citation block. It sounded like an annoying bug. So I went to the demo site to see if I could reproduce it. This is what I did:

- Create new dataverse.
- Turn on some extra metadata blocks besides just "citation" (under "Edit" then "General Information").
- Save changes.

Then I went to create a dataset.

## Click "New Dataset"

![Screenshot from 2019-06-12 06-08-12](https://user-images.githubusercontent.com/21006/59342953-cd7f3000-8cd8-11e9-939f-317c5c061076.png)

## BOOM!!

![Screenshot from 2019-06-12 06-08-17](https://user-images.githubusercontent.com/21006/59342952-cd7f3000-8cd8-11e9-8273-ec4bb9fc0265.png)

This was very strange to me. I went back into "General Information" and the boxes I had checked for geospatial, social science, astronomy, etc were no longer checked. It looked like this:

![Screenshot from 2019-06-12 06-09-08](https://user-images.githubusercontent.com/21006/59342951-cd7f3000-8cd8-11e9-8504-c9c368ac871f.png)

I spoke with @kcondon and @sekmiller about it. The workaround (I think) is to check those boxes again (for geospatial or whatever) and click Save Changes. This issue seems to be related, if not the root cause of the bug: Add Dataset: Throws exception when on dataverse create, inherit metadata blocks is unchecked. #5613

**Comment by Thanh-Thanh** [comment] 2019-06-12 12:11
Thanks @pdurbin for the reference and the work-around. This is exactly what we have in fact. We have the same thing as #5613 in the server log...

**Comment by pdurbin** [comment] 2019-06-12 12:19
@Thanh-Thanh ok, thanks for confirming this. Are you interested in working on a pull request? :smile:

**Comment by Thanh-Thanh** [comment] 2019-06-13 09:19
@pdurbin :( I can not say yes this time. Actually we're busy to finish up others subjects that we've engaged. I'll come back on this later on if possible. 
So sorry :(

**Comment by pdurbin** [comment] 2019-06-13 10:34
@Thanh-Thanh no problem! You didn't introduce the bug! It's not your fault. :smile: Thank you for even considering fixing it for us!

I hope you or someone has time to take a look in the future. I'm happy to help find the right part of the code to look at.

**Comment by mheppler** [comment] 2019-06-21 17:28
I also saw locally on develop (v 4.15) the same problem that @Thanh-Thanh did. Confirmed it was related to the bug opened by @kcondon _Add Dataset: Throws exception when on dataverse create, inherit metadata blocks is unchecked. #5613_.

Closing this issue with the suggestion of following that older issue to track our progress resolving this bug.

**Closed by mheppler** 2019-06-21 17:28 UTC
Labels: Feature: Dataverse General Info, Feature: Metadata, Type: Bug
