### ISSUE TITLE
Custom HBGDki Metadata - Gates Foundation

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2646] opened 2015-10-15 15:53 UTC
Need to create a custom metadata block for this particular group's datasets

[HBGDki Metadata Fields.xlsx](https://github.com/IQSS/dataverse/files/14179/HBGDki.Metadata.Fields.xlsx)

**Comment by posixeleni** [comment] 2015-10-18 14:08
Developing this metadata block here: https://docs.google.com/spreadsheets/d/17Xzl1FnlkMHoCSdiFei5iRDBQyg4LXHRhtvFum9ayKs/edit#gid=556626993

**Comment by posixeleni** [comment] 2015-10-21 17:55
Received confirmation from the user that this is what they are looking for. Will assign to @kcondon to get this metadata showing up in production (but test on another server first). @scolapasta will send us instructions on where this needs to be updated for the API.

**Comment by pdurbin** [comment] 2015-10-21 19:57
This will require a new Solr schema.xml so I'll push a new one before passing to QA.

**Comment by pdurbin** [comment] 2015-10-21 20:40
@kcondon I pushed a new Solr schema.xml for this metadata block in d1d3705

Here's the "raw" version to download: https://raw.githubusercontent.com/IQSS/dataverse/d1d3705a08e440165f23d87f17b491164b9b4fe7/conf/solr/4.6.0/schema.xml

After loading the new block you won't be able to create a dataset using this block without the new Solr schema.xml. You would get errors like the ones I captured in #2665.

Passing to QA.

**Comment by pdurbin** [comment] 2015-10-22 14:14
I've been asked to see if the new fix at 506b470 results in a new schema.xml

**Comment by kcondon** [comment] 2015-10-22 14:18
I tested last night's fix and saw this error when creating a dataset, which seemed to indicate needing a schema change:


We found a field definition issue last night with the new Gates metadata block and Eleni fixed it. However, when I try to create a dataset with the modified field I get a Solr error so it seems the schema needs one last update?

Caused by: org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSolrException: ERROR: [doc=dataset_2672206_draft] multiple values encountered for non multiValued field hbgdkiStudyRegistryType: [ICTRP, DOI]


Thanks,

Kevin

**Comment by kcondon** [comment] 2015-10-22 14:22
@pdurbin It looks like when that compound field was corrected, the multiple values applies to the child fields now. Everything works if there is only one instance as Eleni confirmed. When you add multiples it fails.

**Comment by pdurbin** [comment] 2015-10-22 14:37
Sure enough, 506b470 (apparently but I'm not sure why) resulted a change to the Solr schema.xml in which two fields went from false to true for multiValued. I just pushed f3f5802 which contains the fix.

Back to QA.

**Comment by kcondon** [comment] 2015-10-22 16:38
In production, confirmed by Eleni, closing.

**Closed by kcondon** 2015-10-22 16:38 UTC
Labels: Component: Metadata, Priority: High, Status: QA
