### ISSUE TITLE
Delete File: Success message for deleting file before save needs spaces between file names.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2224] opened 2015-06-01 16:06 UTC
Success message for deleting file, before save needs spaces between file names:
 Success! – Files images.jpgmuench2002.fitsharris_s1635_spss.tab will be permanently deleted from this version of this dataset once you click on the Save Changes button.

**Comment by mheppler** [comment] 2016-02-10 20:54
Added commas and quotation marks to the success message for delete/restrict actions on Edit Dataset Files pg.

**Comment by scolapasta** [comment] 2016-02-11 20:26
Actually it turns out there's an even earlier issue, #2206 which mentions the space, but is also more general about the display. So I suggest we close this issue as a duplicate of that one.

**Closed** 2016-02-22 19:46 UTC
Labels: Component: File Upload & Handling, Priority: Medium, Status: Duplicate, Type: Bug
