### ISSUE TITLE
Template feature: deleting an existing template should show success message banner and refresh automatically by default

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#7570] opened 2021-02-01 20:40 UTC
Deleting a template in production does not show a success message banner and the page does not automatically refresh to show the template has been removed from the list of templates. If you refresh the page yourself, the template is removed from the list, but users may not know that they can refresh the page to get some kind of confirmation that the template was deleted.

Julian can also reproduce in Harvard Dataverse repository. But when testing on Demo Dataverse, running v6.2, the deleted template was removed from the list without him needing to refresh the page and there was a success message.

**Comment by cmbz** [comment] 2024-05-06 18:07
2024/05/06
- @jggautier will attempt to reproduce the issue again on HDV
- If the issue still exists, then we can move into Needs Sizing

**Comment by jggautier** [comment] 2024-05-06 18:25
Today when I used the latest versions of Chrome, Firefox and Safari to delete dataset templates in Harvard Dataverse, which was using Dataverse v6.2, the template was deleted from the table in the UI right away, without me needing to refresh the page, and a success message appeared right away.

<kbd><img width="1169" alt="Screenshot 2024-05-06 at 2 17 38 PM" src="https://github.com/IQSS/dataverse/assets/18374574/6d11dbef-e28c-44a1-9bab-ebb5e25fe51c"></kbd>

So I can't reproduce this and I don't think the issues still exist. I'm going to close this GitHub issue.

**Closed by jggautier** 2024-05-06 18:25 UTC
Labels: Feature: Templates
