### ISSUE TITLE
Multiple KindOfData fields

### ISSUE THREAD

**Issue by rmo-cdsp** [IQSS/dataverse#3186] opened 2016-06-28 09:06 UTC
Hello !

I'm making some python datasets import scripts for Dataverse, and I just had a strange "bug":
I've made multiple kindOfData fields in the Citation metadatas (I made a loop mistake :( ), like this:

```
'citation':{
'fields':[
... other datas ...,
{'typeName': 'kindOfData', 'multiple': True, 'value': [u'Fichiers num\xe9riques (audio, textes entretiens, notes observation participante) + support papier (documentation indig\xe8ne, transcriptions papier, etc.)', u'5 entretiens retranscrits', u'7 entretiens enregistr\xe9s'], 'typeClass': 'primitive'}, 
{'typeName': 'kindOfData', 'multiple': True, 'value': [u'Fichiers num\xe9riques (audio, textes entretiens, notes observation participante) + support papier (documentation indig\xe8ne, transcriptions papier, etc.)', u'5 entretiens retranscrits', u'7 entretiens enregistr\xe9s'], 'typeClass': 'primitive'}, 
{'typeName': 'kindOfData', 'multiple': True, 'value': [u'Fichiers num\xe9riques (audio, textes entretiens, notes observation participante) + support papier (documentation indig\xe8ne, transcriptions papier, etc.)', u'5 entretiens retranscrits', u'7 entretiens enregistr\xe9s'], 'typeClass': 'primitive'},
... other datas ...,
]
}
```

By seeing my metadatas json result, I though my dataset's update failed but ... in this case, it succeed and updated the dataset with the kindOfData field, but there is 3 kindOfData fields when you look at the dataset, but only one when editing it.
![triplekindofdataedit](https://cloud.githubusercontent.com/assets/14806890/16410212/b9ee9c1a-3d21-11e6-9791-f9752728fc26.png)
![triplekindofdata](https://cloud.githubusercontent.com/assets/14806890/16410213/ba039156-3d21-11e6-905a-38783dc9d9a3.png)

In order to do my "scripted" metadata update, I use the python api, and my tests are on your beta dataverse (https://beta.dataverse.org). And here is my test dataverse : https://beta.dataverse.org/dataverse/testGrim . The dataset concerned by the bug is in draft version and his id is 83.

The full metadata file is in the attached file.
[metadatas_json_kindofdata_bug.txt](https://github.com/IQSS/dataverse/files/336614/metadatas_json_kindofdata_bug.txt)

As always, I'm available for any question.

**Comment by pdurbin** [comment] 2017-06-23 12:49
@rmo-cdsp thanks for the bug report!

**Comment by jggautier** [comment] 2019-11-07 19:39
On a few Dataverse installations (Demo Dataverse, Harvard Dataverse and some others) I can't reproduce this problem).

Is this a bug related to using the python api? Or a bug only happening on https://beta.dataverse.org, or a bug with the particular dataset created on that server?

(Sorry if I missed any further conversation that happened outside of this ticket.)

**Comment by pdurbin** [comment] 2022-10-11 00:24
@rmo-cdsp hi! Have you tried this lately? Is this still a bug? Thanks.

**Comment by cmbz** [comment] 2024-08-20 15:26
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Closed by cmbz** 2024-08-20 15:26 UTC
Labels: Feature: Metadata, Feature: API, Type: Bug, User Role: API User, Status: Needs Reproducing
