### ISSUE TITLE
Set expiration date for permissions

### ISSUE THREAD

**Issue by bethtruesdale** [IQSS/dataverse#7622] opened 2021-02-17 16:45 UTC
I would like to be able to set an expiration date for roles/permissions in a dataverse or dataset.

We have restricted data that users apply for.  If successful, access to data is granted for one year (this is stipulated in the Data Use Agreement).  At the moment, we have to track whose access expires when.  Then we have to manually go into the various datasets to remove the individual's assigned role.  Because managing this process isn't much fun, it results in many users ending up with access far longer than their DUA says they should have access.

It would be VERY helpful if, at the same time that we grant File Downloader access in the UI, we could enter a future date for the access to expire.  On the given date, Dataverse would automatically remove the assigned role.

**Comment by djbrooke** [comment] 2021-02-17 17:20
Thanks @bethtruesdale. This is something that we're certainly interested in implementing. I'm going to close this as a duplicate of #6055 and will add these details there.

**Closed by djbrooke** 2021-02-17 17:20 UTC
