### ISSUE TITLE
dataverseService.findAllPublishedByOwnerId is not performant

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#785] opened 2014-07-30 16:02 UTC
This issue was originally reported by @raprasad at https://github.com/IQSS/dataverse/issues/181#issuecomment-50604633

By using his script at https://github.com/IQSS/dv-api-test/blob/master/scripts/add_vdc.py I was able to replicated the performance problem. It look a little over 18 seconds to load the homepage:

```
murphy:dataverse pdurbin$ time curl http://localhost:8080 > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 49729    0 49729    0     0   2743      0 --:--:--  0:00:18 --:--:-- 12096

real	0m18.134s
user	0m0.006s
sys	0m0.005s
```

By commenting out the `featuredSource.addAll(dataverseService.findAllPublishedByOwnerId(dataverse.getId()));` line on the DataversePage, I'm able to reduce the time spent loading the home page from 18.1 to 1.6 seconds:
```
murphy:dataverse pdurbin$ time curl http://localhost:8080 > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 49626    0 49626    0     0  31792      0 --:--:--  0:00:01 --:--:-- 31811

real	0m1.569s
user	0m0.006s
sys	0m0.004s
```

This is line 144 as of commit 454da54 - https://github.com/IQSS/dataverse/blob/454da544c37afb5ecb72a236d129c91757027d3b/src/main/java/edu/harvard/iq/dataverse/DataversePage.java#L144

**Comment by eaquigley** [comment] 2016-03-30 16:53
Closing this ticket as a duplicate of #752

**Closed by eaquigley** 2016-03-30 16:53 UTC
Labels: Component: Performance & Stability, Priority: High, Status: Triaged, Type: Bug
