### ISSUE TITLE
File level permissions: access granted but permissions page not reflecting this

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#4287] opened 2017-11-16 05:39 UTC
https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/00786

I assigned one user access and in the two levels of access on the "permissions-file" page, Top level of page says user is granted access, but the bottom level says file was deleted with "0" access, but file is in the published version.
Not attaching screen shot because of user name. Only 1 user is assigned to this dataset.

I used a workaround of granting her access at the "Dataset" level which is not the preferred choice.

**Comment by scolapasta** [comment] 2017-11-16 18:46
Some additional details:
File 1 was added, published, then deleted in an earlier version.
File 2 was added in the same version with the same file name (i.e. a replacement, though not using our replace functionality).

Only File 1 appears to be showing up in the File list on the File permissions page. Also, for some reason the file list shows 0 groups, but should be showing the one.

FYI, I checked in the db for these particular files and there is an assignment of the user on file 1, and not on file 2.

**Comment by pdurbin** [comment] 2017-11-27 16:05
I'm having trouble understanding the steps to reproduce this issue so to make it easier to fix I'm posting screenshots of only public information of the dataset in question:

There are seven files and only one is restricted, so I assume we're talking about the one called `00786Ybarra-OralHistory-PaperData.pdf`:

![screen shot 2017-11-27 at 10 59 11 am](https://user-images.githubusercontent.com/21006/33275981-2fff7960-d362-11e7-82e9-6e6a367ac755.png)

From version 1.0 to 2.0 the file in question (`00786Ybarra-OralHistory-PaperData.pdf`) was added:

![screen shot 2017-11-27 at 10 58 26 am](https://user-images.githubusercontent.com/21006/33276016-49f8c538-d362-11e7-984e-4122fbe794c8.png)

From version 2.0 to 3.0 the original file in question (`00786Ybarra-OralHistory-PaperData.pdf`) was removed and a file with the same name was added:

![screen shot 2017-11-27 at 10 58 47 am](https://user-images.githubusercontent.com/21006/33276045-5f2c0140-d362-11e7-956a-e5b3bf9cd7ad.png)

**Comment by pdurbin** [comment] 2017-11-27 16:14
Yeah, I agree this is super confusing. I made these screenshots long so you can see how it says "Deleted" under "Published". It's not clear which "restricted.txt" you're operating on, the original or the new one.

![screen shot 2017-11-27 at 11 12 51 am](https://user-images.githubusercontent.com/21006/33276623-1270b650-d364-11e7-915c-f578cd0328b8.png)

![screen shot 2017-11-27 at 11 13 10 am](https://user-images.githubusercontent.com/21006/33276622-1265e252-d364-11e7-8e4b-d63d90608d01.png)

**Comment by djbrooke** [comment] 2019-11-22 21:21
Closing as duplicate of #6401

**Closed by djbrooke** 2019-11-22 21:21 UTC
Labels: Feature: Request Access Workflow
