### ISSUE TITLE
Guestbook: Guestbook csv download has issues if contents also includes commas, title, text q.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3449] opened 2016-11-02 21:30 UTC
Found by a user, see RT 243224, if a dataset's title contains a comma, loading the guestbook download csv into a spreadsheet requires manually removing the comma before it is properly imported. This would also happen if a question had commas or an answer had commas.

One solution might be to scrub commas from content when writing this doc.

---

Update by @pdurbin 2018-05-21

connects to #4671

**Comment by mheppler** [comment] 2018-05-16 19:21
Closed this issue as a duplicate of *Dataverse Guestbook: Custom question output has inconsistent order #4671* and copied over the original comment.

**Comment by pdurbin** [comment] 2018-05-21 19:28
Now that pull request @4700 is in and has nothing to do with commas, @mheppler and I feel a little weird about having this issue closed so I'm re-opening it to put it through QA.

Basically, I added commas all over the place, in questions, answers, dataset titles, etc, and I could not reproduce the bug reported in #4671. It looks like the comma handling was rewritten in Dataverse 4.8 as part of pull request #4057 so I think this bug was fixed then but never tested.

I will say that the code replaces commas with spaces, which is a little weird.

**Comment by mheppler** [comment] 2018-05-21 19:39
Confirmed on [demo (4.8.6)](https://demo.dataverse.org/manage-guestbooks.xhtml?dataverseId=11008) that commas in answers to custom questions are being replaced with spaces.

<img width="1128" alt="screen shot 2018-05-21 at 3 31 08 pm" src="https://user-images.githubusercontent.com/687227/40326121-3f580e3e-5d0c-11e8-9771-ee1b91845765.png">

Also went back and tried commas in the dataset title, as well as custom guestbook questions, and everything seems kosher here. Looks like commas are properly "scrubbed" and the CSV of responses is downloadable and openable.

![screen shot 2018-05-21 at 3 37 18 pm](https://user-images.githubusercontent.com/687227/40326416-254b29e4-5d0d-11e8-95d5-6d5615648e02.png)

**Comment by mheppler** [comment] 2018-05-21 19:49
This looks like the commit 4eb80d18f37cc3eea27e738d29cd5cfdf94813f3 from @landreev that removed the commas from the responses.

**Comment by mheppler** [comment] 2019-03-06 16:10
This looks like a duplicate of _Guestbook: Cannot download a particular guestbook using Chrome, throws duplicate header error #3581_ and also _Cannot download guestbook in Chrome if Dataverse has a "," in the name #4512_.

@kcondon and @scolapasta are the of those. I already suggested to Kevin that #3581 be closed as a duplicate. I will let the two of them arm wrestle it out to determine if this gets closed, or remains open as the one issue to rule them all.

**Comment by kcondon** [comment] 2019-03-07 00:15
@mheppler @scolapasta This appears related to the other 2 since it is a problem with Chrome guestbook download when content contains ',' but I'd just point out that this refers to a comma in dataset whereas the other 2 are likely due to comma in dataverse name. 

If Gustavo or Dev wants to work on this together (ask Danny) feel free to combine them. I'd combine to this one, just point to the other 2 since this is the earliest one.

**Comment by cmbz** [comment] 2024-08-20 15:25
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Closed by cmbz** 2024-08-20 15:25 UTC
Labels: UX & UI: Design, Type: Bug, Feature: Metrics + Reports, Feature: Guestbook, User Role: Depositor
