### ISSUE TITLE
API: Do not apply pretty error handling pages (404, etc.) to API calls/pages, simple http errors are better.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1158] opened 2014-11-22 00:09 UTC
When I attempt something invalid with the native API that normally returns a simple http 404, I get the pretty 404 error page html, which is more useful to a human than a program.

**Comment by pdurbin** [comment] 2016-05-18 19:28
What does this issue have to do with #2367 if anything?

**Comment by pdurbin** [comment] 2017-02-08 15:40
This is a duplicate of #3235 and should be closed since pull request #3381 was merged. The fix was shipped in 4.6 so I'll add that milestone.

**Closed** 2017-02-08 15:41 UTC
Labels: Component: API, Effort 2: Medium, Priority 1: Low, Status: Triaged, Type: Bug
