### ISSUE TITLE
Review what shows in user account info and what can be changed

### ISSUE THREAD

**Issue by mcrosas** [IQSS/dataverse#2046] opened 2015-04-20 15:25 UTC
@eaquigley @mheppler we'll review what should be shown in the user account and what they can or can't change.

From @scolapasta 

Usability: 

- what we show the users. We decided we needed to show users something unique and so opted for showing the useridentifier. The fact that it shows with a @ can indeed be confusing, we discussed that, but decided it was lower priority for the 4.0 release. However we did discuss several issues of not displaying the @ (easy to strip out) and handling the other prefixes (& and :) in a different manner. One such solution was to group users and groups separately, using a primefaces feature to the auto complete, but we also did not implement that because we first need to upgrade primefaces (there is a github issue for this).

- can users change user names / identifiers? We decided to not allow users to change this. Whether we want to or not can still be up for debate*. If we do, then it would make sense for sure to separate these as the identifier is used to assign roles. As Michael pointed out there were technical reasons for this (supported role assignees, some of which are internal). Of course, we can revisit this like we can revisit anything, but this was something that was thought out and thoroughly discussed (and yes, there were differing opinions).

This is issue is not about the technical issues related to this (although they need to be taken into account):

Technical:

- the issue of how we reference role assignments, discussed briefly above

- this particular user (and others like him): in this case really, there is no reason we just don't allow '.' and maybe some other characters as usernames. So then that will work. If no one has objections, I will add that for the next patch (some time today).

**Comment by scolapasta** [comment] 2015-06-08 15:38
We should discuss what exactly we mean for this issue.

**Comment by pdurbin** [comment] 2015-06-16 17:45
Related: [2015-04-30 Dataverse User Accounts and Auth Meeting](https://docs.google.com/document/d/157sw9gaFGwrb0EtCGGlLMxSg0cooHfKEvIsjcebPcA8/edit?usp=sharing)

**Comment by pdurbin** [comment] 2016-02-04 15:51
As of Dataverse 4.2.3, when users log in via Shibboleth and click on "Account Information" they see "You are logged in through your institution. If you need to update any of this information, please contact your institution." Here's a screenshot:

![account_-_root_dataverse_-_2016-02-04_10 46 20](https://cloud.githubusercontent.com/assets/21006/12820324/901657dc-cb2c-11e5-98df-46c3c4275cbd.png)

We like to show something that looks more like what a builtin/local user sees (but they won't be able to edit anything for "phase 1" of the next round of Shibboleth development:

![account_-_phoenix_dataverse_-_2016-02-04_10 48 07](https://cloud.githubusercontent.com/assets/21006/12820385/d4967d06-cb2c-11e5-8975-2dcf137d3440.png)

**Comment by eaquigley** [comment] 2016-02-12 18:31
Notes on this page from 2/11 Design Review of Shibboleth:
- [ ] Render position to not appear since it won't have a value
- [ ] Leave this text above filled out account information: You are logged in through your institution. If you need to update any of this information, please contact your institution.
- [ ] If possible, make API Token a tab on account page and remove the Edit Account Information button for remote auth users

**Comment by pdurbin** [comment] 2016-02-12 18:47
I'm just copying a comment from @eaquigley from https://github.com/IQSS/dataverse/issues/2915#issuecomment-183444622 to this issue since that issue is about API stuff and this issue is about UI stuff (different parts of the code):

"Additionally, we discussed adding a line of text into the UI on Create Account and Account Information pages to direct them to the user guide to learn more about converting their remote account into a local account if they are leaving their university."

**Comment by eaquigley** [comment] 2016-02-23 15:43
@pdurbin gave us a demo of what this currently looks like:
![screen shot 2016-02-23 at 10 42 08 am](https://cloud.githubusercontent.com/assets/5922904/13256790/1f985b5c-da1a-11e5-9667-4d3ac2b07a07.png)

Comments from @mheppler and me:
- [ ] remove tool tips
- [ ] have user identifier be username (for consistency with built in account page)
- [ ] strip out @ for the username

**Comment by pdurbin** [comment] 2016-02-23 17:47
In b317365 I changed the following:

- Get values from AuthenticatedUser rather than BuiltIn user (except I show username for builtin users and "useridentifier" for Shib users with the `@` removed. Shibboleth users don't have a username per #1445).
- Never show Position for Shib users (it's never populated)

I deployed this to https://shibtest.dataverse.org if anyone would like to check it out.

@mheppler I'm giving this issue to you to work on tooltips, etc. that we talked about. Please make your changes to the ([2939-shib branch](https://github.com/IQSS/dataverse/tree/2939-shib)) but please be aware that I'll be continuing to make changes there as well (so you'll want to pull the latest before committing and pushing.) My understanding is that we want:

- [ ] non-broken tooltips when builtin users are editing their info
- [ ] better wording for tooltips when in "view" mode (Shib users shouldn't see "the name you would **like** to use since they can't directly change it)
- [ ] a better bundle key name than `user.toEditDetail` (I left a TODO about this)

As a reminder, you can fake out your development environment to log in as a Shibboleth user with a dev setting: http://guides.dataverse.org/en/4.2.4/developers/dev-environment.html#shibboleth . Without this you won't be able to see what Shibboleth users will see. Only "RANDOM" is documented but you can also use "HARVARD1" if you want the same user over and over when you visit <http://localhost:8080/shib.xhtml>

@eaquigley there's a note about "direct them to the user guide to learn more about converting their remote account into a local account if they are leaving their university". Are you planning on letting me know when you've added this to the User Guide (I'd suggest using the same branch that @mheppler and I are working on, mentioned above. Also, please not that I'm planning on deferring any work related to the API token page.

@michbarsinai when playing with the code I made some direct edits to my database to make the builtin username different from the corresponding authenticateduser "identifier". To my surprise, this meant that I was no longer able to log in as this user. The code seemed to be trying to create a **new** user when I attempted to log in. Anyway, I thought this was all very strange and thought I'd mention it. I guess we'll deal with this if someone requests a username change (due to marriage or divorce or whatever) which is mentioned in #1445.

**Comment by mheppler** [comment] 2016-02-23 19:27
Did a few things while I was in the 2939-shib branch.

- Styled "isShibUser" message on Account pg.
- Removed tooltips from the "view" version of the Account Information.
- Fixed broken tooltip issue on the Edit Account Information pg.
- Added empty render logic to the Affiliation and Position fields on Account pg.
- Removed a bunch of old pre-My Data code that was commented out and no longer needed (per @raprasad).

**Comment by pdurbin** [comment] 2016-02-23 19:57
@mheppler I pulled the latest and it's looking good. Thanks. I deployed it to https://shibtest.dataverse.org so folks can take a look. I'm **slightly** concerned about the removal of the pre-MyData code but I left a note under "Features that should be re-tested (no regressions)" at #2939 to remind ourselves to re-test MyData a bit.

@eaquigley I'm passing this to you for feedback on what I wrote at https://github.com/IQSS/dataverse/issues/2046#issuecomment-187813696 to make sure we've done everything you want.

**Comment by eaquigley** [comment] 2016-02-23 20:52
@mheppler for Account Information text can you change it from "You are logged in through your institution. If you need to update any of this information, please contact your institution." to be:

Account information cannot be edited when logged in through an institutional account. Leaving your institution? Get in touch with Dataverse support for assistance.

I could not for the life of me find an example in the bundle of where we have a link to the Support pop up but if possible, would be great to have it in that message.

**Comment by mheppler** [comment] 2016-02-23 22:08
Revised text for Shibboleth users on the Account Information pg, added a link to the Contact Dataverse Support popup. Also added this link to the error message text for 404 and 403 errors.

**Comment by pdurbin** [comment] 2016-02-24 15:13
@mheppler I left a note about regression testing 404 and 403 errors in #2939 but I couldn't quickly figure out how to trigger a 403 error. Any advice?

**Comment by pdurbin** [comment] 2016-03-21 16:42
I'm moving this issue to QA. There's lots of stuff in the initial description/comment for this issue but what we've done on the account page for pull request #3025 is:

- Allow Shibboleth users to **view** (but not edit) their account information. (Prior to pull request #3025 they would only see "You are logged in through your institution. If you need to update any of this information, please contact your institution.")
- Indicate that users should contact Support if they are leaving their institution.

**Comment by kcondon** [comment] 2016-03-25 21:51
This is working as described but the Support popup does not include the check for robots equation's operands: 2+3= shows up as +=

**Comment by pdurbin** [comment] 2016-03-28 13:17
@kcondon unfortunately, the math challenge started being broken in 4.3 and it's gotten worse in the Shib branch. I just opened #3036 about this. Thanks for the heads up.

**Comment by pdurbin** [comment] 2016-03-28 15:30
@scolapasta I'm giving this issue to you. Please see my comment at https://github.com/IQSS/dataverse/issues/3036#issuecomment-202439945 .

**Comment by kcondon** [comment] 2016-03-28 15:44
OK, since the only remaining issue in this ticket was opened in a new ticket, 3036 (thanks phil) we can close this one. The 4.3 issue is only on sign up welcome screen, was not aware of changes there. Noticed it here because shib changes added more places for this link and so triggered explicit test.

Closing.

**Closed by kcondon** 2016-03-28 15:44 UTC
Labels: Component: Account & User Info, Priority: Medium, Status: QA, Type: Suggestion
