### ISSUE TITLE
Dataverse Pg -- Broken Save Functionality, Layout Issue Search-Include Ignoring "Edit" Mode

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#2775] opened 2015-11-25 17:24 UTC
New to 4.2.3's technology branch is a layout issue on the dataverse pg, where the search-include -- with it's search box, facets and results cards -- is being displayed on the edit General Information view of the dataverse pg, just below the Save Changes and Cancel buttons.

In addition to the layout issue, it appears that the Cancel button is broken, doing nothing when clicked, and the Save Changes button, although it brings you back to the "infoMode" view of the dataverse pg, doesn't actually save anything.

**Comment by mheppler** [comment] 2015-11-30 18:06
Related to #2757

**Comment by sekmiller** [comment] 2015-12-01 18:18
This was tripping up because the scroll to in the event of error had improper syntax in the PF5 world 

 <f:ajax onerror="window.scrollTo(0, 0)" />

**Comment by kcondon** [comment] 2015-12-01 18:58
When I reported #2757, I tried editing and cancelling and it seemed to work for me for the main general info fields but not for the metadata blocks. This is still the case.

This is still not working for the metadata blocks view fields.  This ticket seems to be a duplicate of #2757 based on my testing.

**Comment by mheppler** [comment] 2015-12-01 19:03
@kcondon -- this ticket was specifically opened because of the layout issue in the edit view of the dataverse pg, which is not mentioned in your original ticket. I added the save being broken to the ticket when I tried to get as detailed an explanation of what happening as possible. This resulted in some duplication apparently.

**Comment by kcondon** [comment] 2015-12-01 19:11
OK:
1. not seeing search box in edit mode. Good.
2. save/ cancel works for general edit but fails for metadata block view state. Less good.

I'm closing this ticket and will open a separate ticket for the issue in #2.

Closing.

**Closed by kcondon** 2015-12-01 19:11 UTC
Labels: Component: UX & Upgrade, Priority: High, Status: QA, Type: Bug
