### ISSUE TITLE
Better Detection of Memory Leaks/Usage

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#5977] opened 2019-06-26 19:01 UTC
In the sprint planning meeting June 26th, we pulled off this issue from the larger https://github.com/IQSS/dataverse.harvard.edu/issues/18. Through better tooling or investigation, we should detect and fix these issues. Suggestions welcome.

**Comment by djbrooke** [comment] 2019-07-10 18:25
- We should scope this as a way of better detection of leaks before they get to prod/into a release

**Comment by pdurbin** [comment] 2019-07-16 12:40
Related: Test Automation: Investigate, specify, prototype a performance test suite that can be run at build time. #4201 

Also, right now we are using Locust to generate load: http://guides.dataverse.org/en/4.15.1/developers/testing.html#load-performance-testing

**Comment by pdurbin** [comment] 2019-07-23 15:08
The status of this issue is that I stubbed out JMeter docs and config and single simple test in pull request #6043 

If I hear that we should continue down the JMeter road, next I think we should try to reproduce the memory leak @PaulBoon reported in #6035.

**Comment by pdurbin** [comment] 2019-07-24 11:54
> If I hear that we should continue down the JMeter road, next I think we should try to reproduce the memory leak @PaulBoon reported in #6035.

@PaulBoon provided his JMeter script (thanks!!) at https://github.com/IQSS/dataverse/issues/6035#issuecomment-514538824

**Comment by djbrooke** [comment] 2019-07-25 21:27
@scolapasta - what's the question or item for me to take on here?

**Comment by djbrooke** [comment] 2019-07-25 21:34
Moving out of the sprint and replacing with #6035. We will apply what we learned from the practical case of #6035 when we revisit this.

**Comment by landreev** [comment] 2019-09-19 16:59
The PR is of a modestly ambitious scope, as outlined in @scolapasta's comment above: 

> As a first step, we can use this to establish a baseline, and then run this in an regular way to make sure that code commits don't worsen these numbers.

This is a first attempt to produce some quantifiable results, that can be used to both detect an unacceptable inefficiency introduced in a branch AND to compare the result to the benchmark from a previous test. 

This PR does not solve the logistics of the second part of the above: we will still need to figure out if we want to somehow archive these results for our releases and how to do that. The plots that the test produces have value of their own, but it would even more useful to superimpose them onto the graphs from the previous release. Because that would provide an immediate visual indication of whether memory usage has gotten worse. But in order to be able to do that easily, you need that data from the previous release benchmark. Once again, putting together a system of running these tests automatically and archiving the results is out of scope for now.

**Comment by landreev** [comment] 2019-09-19 20:08
I'm assuming I'll still need to work with @kcondon during QA, to finalize the tests and the format of the result output; how much data we want to save, etc. (for ex., originally I wanted to save the listings of all the edu.harvard.iq classes on the heap throughout the test run; that made the raw file too long, so now I'm only saving some select important classes)

The test relies heavily on scripts in dataverse-ansible and dataverse-sample-date. The scripts in the PR are very lightweight; I spent most of the time figuring out how to reliably spin up properly populated instances, with some minor fixes in the repos above (small stuff - some things were a little behind what's in the dev. branch now, like the new solr schema install. But things like that should be less of a problem going forward as we are using these tools more regularly now).

**Comment by landreev** [comment] 2019-09-25 22:17
Added some extra output to the benchmark script, that explains what's going on, and tells the user running the test how to look at the output generated by each test in real time. Like this:
```
Beginning the load test of the dataverse page.
You can monitor the progress of the test by checking the output at http://ec2-3-92-28-124.compute-1.amazonaws.com/memory-benchmark-raw-dataverse.txt
The basic test of 100 page loads, followed by a snapshot of the 
heap space and the GC status, will be repeated 200 times total
(This means that once the test completes, the output file above will contain the 200 entries total;
so looking at the timestamps in the output should give you an idea how long it's going to take to finish)
```
Similarly, once a plot is generated, a link to it is immediately provided, so the user running the script can look at it, without waiting for everything else to finish. 

Also added a prominent reminder at the very end of the script showing how to terminate the instance when no longer needed. (that info is already provided in the output of Don's create-instance script, but it may be buried in all the other output by the time it's all finished.

**Comment by landreev** [comment] 2019-09-26 14:55
I've checked in all the interactivity/extra messaging to the scripts that I wanted to add; moved back in QA.

**Closed** 2019-09-30 17:15 UTC
Labels: Medium
