### ISSUE TITLE
Destroy Dataset: Cannot destroy a dataset that has a mapped shape file.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4093] opened 2017-08-18 18:08 UTC
This is currently in production, v4.7.1

Server log error:

Local Exception Stack: 
Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: update or delete on table "dvobject" violates foreign key constraint "fk_maplayermetadata_datafile_id" on table "maplayermetadata"
  Detail: Key (id)=(3047705) is still referenced from table "maplayermetadata".
Error Code: 0
Call: DELETE FROM DVOBJECT WHERE (ID = ?)
        bind => [1 parameter bound]
Query: DeleteObjectQuery([DataFile id:3047705 name:null])
        at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:340)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.processExceptionForCommError(DatabaseAccessor.java:1611)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:898)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeNoSelect(DatabaseAccessor.java:962)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:631)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:558)
        at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2002)
        at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:298)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.deleteObject(DatasourceCallQueryMechanism.java:203)
        at org.eclipse.persistence.internal.queries.StatementQueryMechanism.deleteObject(StatementQueryMechanism.java:104)
        at org.eclipse.persistence.queries.DeleteObjectQuery.executeDatabaseQuery(DeleteObjectQuery.java:218)
        at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:899)
        at org.eclipse.persistence.queries.DatabaseQuery.executeInUnitOfWork(DatabaseQuery.java:798)
        at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWorkObjectLevelModifyQuery(ObjectLevelModifyQuery.java:108)
        at org.eclipse.persistence.queries.DeleteObjectQuery.executeInUnitOfWorkObjectLevelModifyQuery(DeleteObjectQuery.java:119)
        at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWork(ObjectLevelModifyQuery.java:85

**Comment by pdurbin** [comment] 2017-09-15 18:35
We talked about this on Wednesday during sprint planning and I think we agreed we should fix it with a cascade delete. A related post from TDL just came in: https://groups.google.com/d/msg/dataverse-community/84beQsFuC9w/LZF_dHn-AAAJ

**Comment by pdurbin** [comment] 2017-09-15 19:43
Hmm. Well, they should start with the `check` command at http://guides.dataverse.org/en/4.7.1/admin/geoconnect-worldmap.html#removing-dead-explore-links I guess.

**Comment by pdurbin** [comment] 2017-10-20 19:35
Once we fix this bug, we'd like to destroy this dataset: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/T2VIXT

**Comment by djbrooke** [comment] 2017-10-25 21:11
Another one, good test case in prod: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/4WL81Z

**Comment by pdurbin** [comment] 2017-10-30 17:33
I just made pull request #4245 and am moving this to Code Review at https://waffle.io/IQSS/dataverse

**Comment by matthew-a-dunlap** [comment] 2017-11-03 17:04
Moving this into develop to take a stab at utilizing cascade / jpa

**Comment by matthew-a-dunlap** [comment] 2017-11-03 23:03
In addition to the currently committed code, I have an extra small piece that deletes the map from worldmap itself, as that does not seem to happen in the current flows (I may have missed it tho). The piece of code I have still hits an error in tests tho, so it'll have to wait.

**Comment by landreev** [comment] 2017-11-08 15:00
I can't decide if adding the cascade for automatically deleting the maplayermetadata is actually a good solution. I can see that it's working. But, seeing how we still must do something in addition to deleting the map layer locally - go out and delete the files from worldmap - doesn't that mean, that we actually DON'T want to have the layer automatically deleted, ever? Not being able to delete the datafile, and, as a result, the dataset actually serves the purpose of alerting us that we still have some files sitting out on the worldmap side that we need to take care of. 
I would like somebody else to weigh in on this. 
@scolapasta ?

**Comment by pdurbin** [comment] 2017-11-08 15:23
@landreev there's also the thumbnail cleanup to consider. Back in 3271032 I added a call to `DeleteMapLayerMetadataCommand` but this was removed in 20c66bc. I raised a flag about this in this comment: https://github.com/IQSS/dataverse/pull/4245#commitcomment-25388076

**Comment by landreev** [comment] 2017-11-08 16:21
Just to make sure I was clear, the potential issue I was describing is as follows: if we have a cascade delete between the datafile and the maplayermetadata, if the datafile itself is ever deleted bypassing the DeleteCommand workflow - by a direct EJB delete, cascade, etc. - then the maplayermetadata gets quietly deleted too, leaving the associated content sitting on the worldmap side, with no record of it left on the dataverse side.

**Comment by matthew-a-dunlap** [comment] 2017-11-08 18:02
I can see why not using cascade would be the better solution, I am indifferent on it. I went about using cascade in part to teach myself aspects of JPA as it was topical.

**Comment by scolapasta** [comment] 2017-11-08 22:27
Reviewed. 
The thumbnails we handled here because since it was destroy dataset, all thumbnails were being deleted.

That said, there is the same issue @leonid brought up about somehow deleting outside the command workflow. 

So sure let's go with the Composable Command way of doing it and leave JPA out of this one. (though generally, JPA should still be our goto first stab, so it's good to continue sprading knowledge on how to do that).

**Comment by matthew-a-dunlap** [comment] 2017-11-09 17:14
Changes are done, ready for QA (unless it needs a quick review). 

Here is a summary of the change: When a datafile (or its dataset) is deleted, worldmap layer will be deleted from our system as well as externally off worldmap

**Comment by kcondon** [comment] 2017-11-09 19:56
Prelim testing shows destroy/restrict delete not working.

**Comment by matthew-a-dunlap** [comment] 2017-11-16 15:50
In my testing the reported problem with geoconnect cannot be reproduced. It looks like it may have been an environment problem on the geoconnect end.

**Comment by landreev** [comment] 2017-11-17 18:02
So the latest I'm hearing is that it's working on dvn-build.hmdc.harvard.edu, and NOT working on dvn-vm4.hmdc.harvard.edu ("dataverse-internal"). A quick inspection shows that dvn-build is using the dev instance of geoconnect (geoconnect-dev.herokuapp.com), and dvn-internal - the prod. version (geoconnect.datascience.iq.harvard.edu). 
So my early guess may be correct after all - maybe that (somewhat) recent geoconnect modification, that allowed the deletion of worldmap-side stored layer files to be initiated from Dataverse, never got deployed in production. 
Will try to confirm today.

**Comment by matthew-a-dunlap** [comment] 2017-11-20 22:10
The code so far correctly solved the original error, that the MapLayerMetadata was not being deleted before the data file. Now that it is being deleted correctly, a new error has appeared which is that the WorldMapToken is not being deleted!

```
Local Exception Stack: 
Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: update or delete on table "dvobject" violates foreign key constraint "fk_worldmapauth_token_datafile_id" on table "worldmapauth_token"
  Detail: Key (id)=(1616) is still referenced from table "worldmapauth_token".
Error Code: 0
Call: DELETE FROM DVOBJECT WHERE (ID = ?)
	bind => [1 parameter bound]
Query: DeleteObjectQuery([DataFile id:1616 name:null])
```

There was not a straightforward way to get the WorldMapToken to delete it (we hadn't needed to before) so I've tried writing some code to do so. Its blowing up attempting to get the WorldMapToken by dataFile and I am unsure why. As testing this involves getting Kevin to deploy on a remote server, I could use some help trying to solve this without a ton of manual testing.

```
Caused by: java.lang.NullPointerException
       	at edu.harvard.iq.dataverse.worldmapauth.WorldMapTokenServiceBean.findByDataFile(WorldMapTokenServiceBean.java:86)
       	at edu.harvard.iq.dataverse.engine.command.impl.DestroyDatasetCommand.executeImpl(DestroyDatasetCommand.java:91)
       	at edu.harvard.iq.dataverse.engine.command.AbstractVoidCommand.execute(AbstractVoidCommand.java:29)
       	at edu.harvard.iq.dataverse.engine.command.AbstractVoidCommand.execute(AbstractVoidCommand.java:13)
```

I tried copying the findByDataFile from MapLayerMetadataServiceBean and can't tell easily what I missed.

**Comment by matthew-a-dunlap** [comment] 2017-11-22 18:35
Using JPA cascade to delete the WorldMapToken on deletion of the DataFile works for most cases. For some reason if the DataFile is restricted when calling the dataset destroy command, the WorldMapToken hits the same error as above ( `Detail: Key (id)=(1616) is still referenced from table "worldmapauth_token"` ). The Dataset is not deleted and the DataFile is still listed in the UI, but if I go to download the DataFile it cannot be found.

Before, it looks like two errors are being thrown. One from attempting to delete the maplayer from worldmap itself (not our database) and one from attempting to delete aux objects. The latter I have improved the error reporting on but have yet to test.

Does anyone know why the DataFile being restricted would cause this?

**Comment by pdurbin** [comment] 2017-11-22 18:40
Nope. Sorry. It sure sounds like action at a distance to me. 😟

**Comment by kcondon** [comment] 2017-11-27 21:51
Status as of last week:
Destroy dataset with mapped files works for the main case:
Working:
-for both shape and geospatial mapped files, removes layers at Worldmap and destroys dataset
-for a previously mapped file that becomes restricted, mapped layer is removed when dataset version with restricted file is published (existing but related behavior)
Not Working:
-for a dataset with a mapped file that became restricted, then published dataset, destroy not working.

Status today:
Destroy dataset with mapped files now does not remove mapped layers, still cannot destroy dataset with previously mapped then restricted file

**Comment by matthew-a-dunlap** [comment] 2017-11-27 22:04
The only change that I added was improving logging to try to understanding the deeper error. Maybe the logging itself is broken. Will take a look shortly.

**Comment by djbrooke** [comment] 2017-11-28 03:39
Thanks for the continued work on this. I mentioned in Sprint Planning earlier today that it's OK if we move this to the backlog instead of continuing to spend time here. If there's some value here (seems to work for non-restricted files?), we should consider merging what we have instead of trying to track down all cases.

**Comment by matthew-a-dunlap** [comment] 2017-11-28 19:55
Below is my summary of the state of this branch. Without a local dev environment for this it is hard to move forward. I've tried following the guides and working with Kevin to point to the dev geoconnect from my local, but the connection fails. I could try setting up geoconnect locally but that seems out of scope. I could also keep sending builds off to Kevin and testing remotely but that's extremely slow and a poor use of time.

The branch as-is could be pulled into development but I don't like how little improvement it causes.

**Current status**
Works:
- [ ] Deletion of dataset triggers delete of mapLayerMetadata and worldmapauth_token for unrestricted datasets.

Broken:
- [ ] Deletion of restricted dataset fails because worldmapauth_token is says it still referenced the datafile. Unsure why restriction makes this delete flow different.
- [ ] Deletion of map off worldmap during dataset deletion fails with null pointer. This still works when restricting the file. This worked at some point on the feature branch, possibly when we used JPA to delete the local map layer. I am unsure why this change would cause problems... is it possible the external delete is started, then the database deletes are called before it completes? Seems like a bit of a black hole, but it still may be possible to get a better log message for the null pointer. 

Not in scope but broken:
- [ ] Deleting an individual data file connected to worldmap does not trigger deletion of the data off worldmap. There is no code yet for this. Restricting the file does trigger this external delete.

**Comment by matthew-a-dunlap** [comment] 2017-11-28 20:05
One other option would be to just rely on manual steps to do this cleanup. This would mean:

**For unrestricted datasets**
- Manually call a curl(?) command to trigger deletion of the external map

**For restricted datasets**
- Manually run sql commands to delete the mapLayerMetadata and worldmapauth_token
- Manually call a curl(?) command to trigger deletion of the external map

This does not work for deletion of individual **DataFiles** because this action can be performed by the end user. We have yet to try fixing this one with code tho, and may be a simple code fix.

**Comment by djbrooke** [comment] 2017-11-29 01:01
Thanks for putting a bow on this. Moving to backlog, we can pick it up in the future.

**Comment by kcondon** [comment] 2018-02-03 00:06
Need to remove this dataset from prod when fixed: doi:10.7910/DVN/SCYBXS

**Comment by djbrooke** [comment] 2020-04-15 18:44
- We suspect this may be easier since our work on the delete user API. There may be some investigation needed.

**Closed** 2020-05-04 16:10 UTC
Labels: Feature: File Upload & Handling, Feature: Publishing & Versions, Medium

**Comment by jggautier** [comment] 2020-10-19 16:23
@kcondon [You wrote](https://github.com/IQSS/dataverse/issues/4093#issuecomment-362746931) in this issue "Need to remove this dataset from prod when fixed: doi:10.7910/DVN/SCYBXS".

Do you mind if I use the destroy endpoint to try to remove it? I just used it to destroy two other test datasets with mapped shape files, but Harvard Dataverse sent me an email about how it "failed to delete the WorldMap layer associated with the restricted file". I don't remember seeing any restricted files in the two datasets, and I'm wondering if I'd get the same message after trying to destroy doi:10.7910/DVN/SCYBXS, which has no restricted files.

**Comment by kcondon** [comment] 2020-10-19 19:22
@jggautier I'm not responsible for destroying any datasets. I believe people recorded some problem ones in this ticket so if you are destroying any of those, just note it, thanks.

**Comment by jggautier** [comment] 2020-10-19 22:21
Okay, these datasets were mentioned in this thread:

1. https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/T2VIXT
2. https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/4WL81Z
3. https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/SCYBXS

The first was already destroyed. I just destroyed the other two.

Neither had restricted files but each time I used the endpoint, an email like the one below was still sent to my superuser account email address:

> Subject line: Harvard Dataverse: Failed to delete WorldMap layer
> 
> Hello,
> We failed to delete the WorldMap layer associated with the restricted file boston_trash_bytract.tab, and any related data that may still be publicly available on the WorldMap site. Please try again, or contact WorldMap and/or Dataverse support. (Dataset: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/4WL81Z)
> 
> You may contact us for support at support@dataverse.harvard.edu.
> 
> Thank you,
> Harvard Dataverse Support

I guess I'm just including this here "for the record" since it doesn't matter much: these are test files so we don't need to make an effort to delete them from the internet (like we would if they contained PII) and the WorldMap integration is going away eventually.
