### ISSUE TITLE
Upload: Adding files on dataset create seem to succeed, files are listed but not saved.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3866] opened 2017-05-30 21:02 UTC
This issue appeared during development and has not been released. It has been merged into /develop however.

**Comment by pdurbin** [comment] 2017-05-31 13:28
I can confirm this bug as of cb0e38f in the `develop` branch.

The dataset is created but there is no thumbnail for a jpg file and I'm seeing "Internal Server Error" when I click Download, as shown in the screenshot below. In server.log, on clicking Download, the error says `java.io.IOException: Failed to open local file file:///Users/pdurbin/dataverse/files/10.5072/FK2/I9O8AB/15c5ead307a-a2619b2c5d5d`.

![screen shot 2017-05-31 at 9 24 09 am](https://cloud.githubusercontent.com/assets/21006/26634026/49b05e7c-45e3-11e7-86be-6c698275927c.png)

![screen shot 2017-05-31 at 9 24 22 am](https://cloud.githubusercontent.com/assets/21006/26634030/4db03b00-45e3-11e7-86d4-d93ddcc54d5a.png)

**Comment by pdurbin** [comment] 2017-05-31 14:51
On create, the directory where files are to be stored is not created. In production the directory is something like `/usr/local/glassfish4/glassfish/domains/domain1/files/10.5072/FK2/IF3GJB`.

The reason the directory is not being created is that `this.getIdentifier()` is null in the `getFileSystemDirectory` method of Dataset.java.

Here's how the method looks as of cb0e38f:

```
    public Path getFileSystemDirectory() {
        Path studyDir = null;

        String filesRootDirectory = System.getProperty("dataverse.files.directory");
        if (filesRootDirectory == null || filesRootDirectory.equals("")) {
            filesRootDirectory = "/tmp/files";
        }

        if (this.getAuthority() != null && this.getIdentifier() != null) {
            studyDir = Paths.get(filesRootDirectory, this.getAuthority(), this.getIdentifier());
        }

        return studyDir;
    }
```

Here's a link to the code: https://github.com/IQSS/dataverse/blob/cb0e38f3bb2706b332e7e54e36e2af1283998a4e/src/main/java/edu/harvard/iq/dataverse/Dataset.java#L506

**Comment by pdurbin** [comment] 2017-05-31 15:05
I just created pull request #3868 and will move this issue to code review at https://waffle.io/IQSS/dataverse

**Comment by djbrooke** [comment] 2017-05-31 15:33
@raprasad - you mentioned in standup you were going to take a look at this.

**Comment by sekmiller** [comment] 2017-05-31 15:34
@djbrooke I just looked at it. It looks good. Moving to QA

**Closed** 2017-05-31 20:20 UTC
Labels: Component: File Upload & Handling, Type: Bug
