### ISSUE TITLE
Converter DataCite metadata (Dataset) to DDI format

### ISSUE THREAD

**Issue by didaRo** [IQSS/dataverse#3646] opened 2017-02-24 13:16 UTC
Hello

I use this command to import the dataset as DDI
curl -H "X-Dataverse-key: $apiKey" "http://$SERVER/api/batch/migrate/?dv=dataverseName&path=/path/to/version1.xml&createDv=true"

I have a DataCite metadata and I hope to converter the xml file to DDI format in order to migrate a dataset.
you use an API to do this in Dataverse ?

Thanks!
Fairouz

**Comment by pdurbin** [comment] 2018-07-19 01:56
@didaRo are you still interested in this? If so, is this a duplicate of #3632?

**Comment by pdurbin** [comment] 2022-10-10 01:14
@didaRo hi? Still interested? Please let us know. Thanks.

**Closed** 2023-10-07 20:33 UTC
Labels: Feature: Metadata, User Role: Sysadmin
