### ISSUE TITLE
IP Groups: Permissions assigned to group are no longer applied except by indexing.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4268] opened 2017-11-09 15:24 UTC
Reported by partner, see RT 255173 .

Partner using v4.7.1 reports that ip groups assigned access to restricted files no longer have access but did in the 4.5-4.6 timeframe (ip groups restored for v4.5.1).
Have reproduced that ip groups permissions are not honored to dataverses, datasets, or files with 4.8.2 but unreleased dv,ds,files do appear to ipgroups assigned access but clicking results in log in screen. This seems to indicate indexing is properly detecting permissions but underlying permission system is not.

**Comment by pdurbin** [comment] 2017-12-06 15:30
I forgot how IP Groups even work and the documentation is lacking so @dlmurphy and I made some improvements yesterday in 9791c47 and d883dff. I'm not playing around with IP Groups on https://dev1.dataverse.org and I can confirm that they don't seem to work at all.

![my-eyes-the-goggles-do-nothing](https://user-images.githubusercontent.com/21006/33669438-78abaf7a-da70-11e7-9ec4-6a4d7b6dc517.jpg)

I'll keep investigating.

**Comment by pdurbin** [comment] 2017-12-06 21:07
I'm poking at the file download via API stuff (wrote some API tests) in 99570b6

**Comment by pdurbin** [comment] 2017-12-07 18:52
I just created pull request #4367

The fix is in 9fa3f1a which reverts eea4655 and adjusts the Guest user handing of `FileDownloadHelper.java`.

Moving to code review.

**Comment by djbrooke** [comment] 2017-12-07 20:38
Ping @kevinworthington if you'd like to take a look. Thank you for reporting this issue!

**Comment by landreev** [comment] 2017-12-13 01:54
Left feedback in the PR; I'm essentially requesting what @scolapasta  had asked for earlier. 
Full disclosure, I haven't worked on the permissions as much, so I may be missing something. But it does look like the permissionService.userOn(...) method ignores "request-level permissions" (e.g. from IP groups); but the .on(dvObject).has(permission) method covers those too. So it sounds like that's what we want to use. 

But, in addition to what Gustavo mentioned in the PR - I don't think this is just a matte of code cleanup. Because (again, unless I'm missing something) as currently implemented, the DownloadHelper will check the IP group-based permissions for the guest user ONLY. I'm assuming we want authenticated users to be able download files based on IP groups too - correct?

**Comment by pdurbin** [comment] 2017-12-13 11:34
@landreev yes, good point. Indeed, the requirement is that IP Groups work for both authenticated users as well as users who haven't logged in (the `Guest` user in the code). I'll take another look and will likely try that change you and @scolapasta have suggested.

**Comment by pdurbin** [comment] 2017-12-14 01:32
I was lamenting a bit to @sekmiller today that the code in question `FileDownloadHelper.java` cannot be exercised via API and I'm planning on seeing if I can fix this. Lots of meetings today. Stay tuned.

**Comment by pdurbin** [comment] 2017-12-14 18:40
> as currently implemented, the DownloadHelper will check the IP group-based permissions for the guest user ONLY

@landreev you're right. I just exercised the bug on my dev1 server. I'll work on a fix.

**Comment by scolapasta** [comment] 2017-12-14 18:42
@landreev @pdurbin good point on this being more than just cleanup and also a bug fix. The fix should just be to use the permission method that takes the request.

@michbarsinai is there any need to still have the one that takes in the roleassignnee? is that uses anywhere that can't use the request one?

**Comment by pdurbin** [comment] 2017-12-14 21:45
@landreev @scolapasta I'm playing around with a fix at 011e122 but I'm not done testing it.

**Comment by pdurbin** [comment] 2017-12-15 15:08
To be clear, I pushed 011e122 to a new branch, not to the pull request. I'm still playing around. Part of my hesitancy is that I just noticed a problem (I'm testing 92d087a). There must be different business logic used for the "search cards" on the home page versus the dataset and file pages because on the search card the icon show red even though the file is downloadable. Screenshots might help:

## search cards: red lock

![screen shot 2017-12-15 at 10 02 24 am](https://user-images.githubusercontent.com/21006/34047840-98353a1c-e17f-11e7-8da8-cb3cb8a749d3.png)

## dataset page: green lock

![screen shot 2017-12-15 at 10 07 48 am](https://user-images.githubusercontent.com/21006/34047923-de3b1d74-e17f-11e7-8e06-6db22520107a.png)

## file page: green lock

![screen shot 2017-12-15 at 10 02 35 am](https://user-images.githubusercontent.com/21006/34047846-9e51c1fe-e17f-11e7-9b84-64d82fe3d526.png)

Also, I'd be remiss if I didn't mentioned that @pengchengluo just opened #4386 about IP Groups being broken.

**Comment by pdurbin** [comment] 2017-12-15 15:25
I'm looking at e8a9116 and wondering why `if (this.permissionService.on(fileMetadata.getDataFile()).has(Permission.DownloadFile))` was commented out when logic was moved from `DatasetPage.java` to `FileDownloadHelper.java`

**Comment by pdurbin** [comment] 2017-12-15 18:27
> There must be different business logic used for the "search cards" on the home page versus the dataset and file pages because on the search card the icon show red even though the file is downloadable.

I just opened #4387 about this because it's a separate issue that can be exercised without any use of groups.

**Comment by pdurbin** [comment] 2017-12-15 18:33
@scolapasta and @landreev I'm moving this to code review because I implemented the fix you suggested at eb9a753 and it works. As of that commit, membership in an IP Group allows you to download a restricted file whether or not you are logged in.

Along the way I discovered #4387 but it's a pre-existing condition about inheritance of permissions for all role assignees, not just groups.

**Comment by dlmurphy** [comment] 2017-12-15 22:46
Just updated docs in 98672ad0c82f3afcd4236d84911a8a8f0fc1b0e1
(forgot to tag it with this issue!)

**Comment by michbarsinai** [comment] 2017-12-18 08:35
I'm pretty sure it could be replaced with the request one. Note that there's a lot of deprecated code there, some of which is used from the UI, so it might warrant it's own clean-up issue. We should definitely do this before 5.0, though.

**Comment by pdurbin** [comment] 2017-12-18 12:32
Over at https://github.com/IQSS/dataverse/issues/4386#issuecomment-352341360 @pengchengluo wrote, "Thanks! I test the code of 4268-ip-groups-broken branch and find it works correctly now." I was happy to hear that. 😄

**Comment by pdurbin** [comment] 2017-12-19 19:03
I addressed some code review in 9db04be and 13e9384 and merged the latest from the `develop` branch in 99b6f39. I believe I'm done so I'm getting off this branch and issue.

**Closed** 2018-01-11 19:56 UTC
Labels: Feature: Permissions, Status: QA, Type: Bug
