### ISSUE TITLE
Need ability to edit variable metadata 

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#961] opened 2014-10-16 17:35 UTC
Be able to edit the variable label and type, and to tag columns.

Need to consider how this affects the download the format that is the original file.

type:
numeric
boolean
string
date

tags:
weights
time
continuous
count
ordinal
unique identifier
nominal / categorical
space
-   lat / long
-   FIPS
-   census

**Comment by pdurbin** [comment] 2016-10-16 02:07
It's not entirely clear to me what this issue is about but `label` and `type` both exist in the `datavariable` table ( http://phoenix.dataverse.org/schemaspy/latest/tables/datavariable.html ) so I assume that's what it's about. A user story would help. Even better would be knowing who is asking for this feature so we can let them know if or when we implement it. :smile:

**Comment by pdurbin** [comment] 2016-10-16 02:10
Hmm, editing variable labels and types is mentioned (among many other things) in #962 (and opened on the same day).

**Comment by pdurbin** [comment] 2017-06-25 18:52
@scolapasta is this a duplicate of #962?

**Comment by pdurbin** [comment] 2019-04-03 01:07
We should probably close this issue in favor of #4448

**Closed** 2019-10-01 21:10 UTC
Labels: Feature: File Upload & Handling, Vote to Close: pdurbin
