### ISSUE TITLE
Guestbook: Guestbook added to option when creating templates, under "terms of use" section

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#4029] opened 2017-07-27 17:16 UTC
Currently when creating templates, you can add "terms," but you can't add a guestbook which interrupts the workflow in using templates for datasets that require guestbook. The request is to add the ability to enable guestbook at the template - create terms-level

**Comment by mheppler** [comment] 2019-03-06 16:04
Closing as duplicate of _Guestbook: User should be able to associate a guestbook with a template in a dataverse #4889_, which was also requested by @sbarbosadataverse -- almost a year apart to the day.

**Closed by mheppler** 2019-03-06 16:04 UTC
Labels: Feature: Guestbook, Feature: Metrics + Reports, Feature: Templates, Feature: Terms & Licensing, Type: Feature, User Role: Curator
