### ISSUE TITLE
Should see all the fields filled in for a dataset regardless of what the parent dataverse specifies

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#756] opened 2014-07-21 20:06 UTC
This came up in SWORD testing, where the [sample XML file we document in the Data Deposit API](https://github.com/IQSS/dvn/blob/3.6.2/doc/sphinx/source/dataverse-api-main.rst#create-a-study-with-an-atom-entry-xml-file) has fields that span multiple citation blocks in Dataverse 4.0.

This is the way I first described this problem:

**Hidden non-citation fields when metadata block is not turned on for a dataverse**

This one surprised me a bit... I created a dataset and was thinking, "Dude, where's my geographicCoverage? I *know* it's in the Atom entry I fed to SWORD".

It turns out the fields *were* populated for the dataset I just but I couldn't see them until I went in to my dataverse and turned on the social sciences metadata block. Is this the behavior we want? I didn't test if the native API behaves the same way with regard to creating datasets.

**Comment by scolapasta** [comment] 2015-02-20 22:55
This is a duplicate of #636

**Closed** 2016-01-12 18:57 UTC
Labels: Component: Metadata, Priority: High, Status: QA, Type: Bug
