### ISSUE TITLE
File Permissions: Grant File Access popup should display number of restricted files

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2716] opened 2015-11-02 18:56 UTC
When adding a user to restricted files, the dialogue box doesn't display the number of "restricted" files the user is about to be assigned. This is only seen under the "terms" tab. Since not everyone gets blanket permission to files, and sometimes you have long list of files, the dialogue box should display:

how many restricted files you start with
how many restricted files you have selected to assign permission to...

Once assigned, the screen does diplay how many files the user has been assigned but this should also happen at above level.

**Comment by mheppler** [comment] 2016-01-29 21:15
As suggested in #2896, this feature request could potentially be useful in other places in the permissions workflow, such as, on the File Permissions page to show a total number of users that have access to files for a dataset. Currently, an admin is required to count the rows of the `userGroupsAccess` table to determine this number.

**Comment by mheppler** [comment] 2016-02-09 00:58
I am taking this issue, as I have found a [potential solution](http://stackoverflow.com/questions/9372632/rowselect-event-primefaces-datatable) to the dynamic counter associated with a selection dataTable.

**Comment by mheppler** [comment] 2016-02-09 04:04
Added counter to dataTables in the File Permissions pg, plus prototype for dynamic "selected" counter in the access action popups.

**Comment by mheppler** [comment] 2016-02-09 16:45
Here is a break down of all the counters that are being added to the various permissions page.

*Dataverse/Dataset Permissions*
- Users/Groups role assigned table

*File Permissions*
- Users/Groups access requests table
- Users/Groups file access requested popup (w/ dynamic "Selecting # of... " count)
- Users/Groups access granted table
- Users/Groups file access granted popup (w/ dynamic "Selecting # of... " count)
- Users/Groups grant access popup (w/ dynamic "Selecting # of... " count)
- Files restricted table
- Files users/groups access assigned popup (w/ dynamic "Selecting # of... " count)
- Files grant access popup (w/ dynamic "Selecting # of... " count)

<img width="964" alt="screen shot 2016-02-08 at 10 57 12 pm" src="https://cloud.githubusercontent.com/assets/687227/12923125/7ebde7e4-cf22-11e5-819c-21767dc9313a.png">
![screen shot 2016-02-09 at 11 45 07 am](https://cloud.githubusercontent.com/assets/687227/12923157/9d1cf2b6-cf22-11e5-8913-d0faf6684cb9.png)

**Comment by sbarbosadataverse** [comment] 2016-02-09 16:55
Will a "date and time" stamp be part of what you are doing? or a separate
ticket?

Thanks

On Tue, Feb 9, 2016 at 11:45 AM, Michael Heppler <notifications@github.com>
wrote:

> Here is a break down of all the counters that are being added to the
> various permissions page.
>
> *Dataverse/Dataset Permissions*
>
>    - Users/Groups role assigned table
>
> *File Permissions*
>
>    - Users/Groups access requests table
>    - Users/Groups file access requested popup (w/ dynamic "Selecting #
>    of... " count)
>    - Users/Groups access granted table
>    - Users/Groups file access granted popup (w/ dynamic "Selecting #
>    of... " count)
>    - Users/Groups grant access popup (w/ dynamic "Selecting # of... "
>    count)
>    - Files restricted table
>    - Files users/groups access assigned popup (w/ dynamic "Selecting #
>    of... " count)
>    - Files grant access popup (w/ dynamic "Selecting # of... " count)
>
> [image: screen shot 2016-02-08 at 10 57 12 pm]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_687227_12923125_7ebde7e4-2Dcf22-2D11e5-2D819c-2D21767dc9313a.png&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=WHtGN2aBMcTtspcHK-7sEfYqQU3PsTqb8JihqtpHANw&s=9_60Ll3gUf_ZCyVBR2DOo1-RQcLVlRvxHbrlGg7tAkA&e=>
> [image: screen shot 2016-02-09 at 11 45 07 am]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_687227_12923157_9d1cf2b6-2Dcf22-2D11e5-2D8913-2Dd0faf6684cb9.png&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=WHtGN2aBMcTtspcHK-7sEfYqQU3PsTqb8JihqtpHANw&s=ZQFM2mtQc_BuKGy7T9srL0LPumFHK8DW26NzgvjrfVc&e=>
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2716-23issuecomment-2D181950750&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=WHtGN2aBMcTtspcHK-7sEfYqQU3PsTqb8JihqtpHANw&s=MLmyIzMkIUjwDQAOJnOP4XYHRRlT-uCfqkHjIFOzTzw&e=>
> .
>



-- 
Sonia Barbosa
Manager of Data Curation, IQSS Dataverse Network
Manager of the Murray Research Archive, IQSS
Data Science
Harvard University

Dataverse 4.0 is now available for use!
http://dataverse.harvard.edu

All test dataverses should be created  in 4.0 Demo!
http://dataverse-demo.iq.harvard.edu/

Join our Dataverse Community!
https://groups.google.com/forum/#!forum/dataverse-community

**Comment by mheppler** [comment] 2016-02-09 17:02
@sbarbosadataverse - the issue you reference is outlined in #2855 and will be developed separately from this specific issue. It is my intent to prioritize as many permissions-related issues as possible and get them into development as quickly as possible. This issues is high on that list.

**Comment by sbarbosadataverse** [comment] 2016-02-09 17:05
Great. Thanks. Otherwise what you sent looks great!

On Tue, Feb 9, 2016 at 12:02 PM, Michael Heppler <notifications@github.com>
wrote:

> @sbarbosadataverse
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sbarbosadataverse&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=779lkQTrFK9ZktrFlcNfIWCb2QvnapHdxD10gVAWj4o&s=iErFm-pNIWdjqSG9DYZqeQjLWfYdKNa2EwI3mZwr-sM&e=>
> - the issue you reference is outlined in #2855
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2855&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=779lkQTrFK9ZktrFlcNfIWCb2QvnapHdxD10gVAWj4o&s=UFzhmqYMGmQ2JUZNWK8IA4gm7nE9qw9P2SMYUosj9H0&e=>
> and will be developed separately from this specific issue. It is my intent
> to prioritize as many permissions-related issues as possible and get them
> into development as quickly as possible. This issues is high on that list.
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2716-23issuecomment-2D181958048&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=779lkQTrFK9ZktrFlcNfIWCb2QvnapHdxD10gVAWj4o&s=7n66wlk1UvAsWtQspNDvgGgtg6pRX6-jDnN1wd7MXpU&e=>
> .
>



-- 
Sonia Barbosa
Manager of Data Curation, IQSS Dataverse Network
Manager of the Murray Research Archive, IQSS
Data Science
Harvard University

Dataverse 4.0 is now available for use!
http://dataverse.harvard.edu

All test dataverses should be created  in 4.0 Demo!
http://dataverse-demo.iq.harvard.edu/

Join our Dataverse Community!
https://groups.google.com/forum/#!forum/dataverse-community

**Comment by mheppler** [comment] 2016-08-05 17:01
The dynamic "selecting" count is buggy. If you click around on the Restricted File Permissions pg and go from one popup to another the count can carry over and incorrectly display a count.

![screen shot 2016-08-05 at 1 00 35 pm](https://cloud.githubusercontent.com/assets/687227/17444190/b46f25da-5b0c-11e6-853a-ed7378b54346.png)

![screen shot 2016-08-05 at 1 01 03 pm](https://cloud.githubusercontent.com/assets/687227/17444193/b74ee77c-5b0c-11e6-8b48-8e5420464768.png)

**Comment by kcondon** [comment] 2016-09-15 21:00
Ok, generally works well. Found 2 issues that are relatively minor or rare and could be ignored or opened in separate ticket if not have time:
1. Granting perms on dataverse or dataset page does not update user count on success, need to refresh page, otherwise works.
2. If decide to grant access to all files to a user that already has access to some throws both a success msg and 2 exceptions, though it works and user has correct access.
Passing back to Mike to see what he wants to do with it.

**Comment by mheppler** [comment] 2016-09-19 14:44
Thank you, @kcondon. Do you have a test environment for this branch still or should I just take a look locally to reproduce? Once I've had a look, I'll review with @sekmiller to get his input.

**Comment by kcondon** [comment] 2016-09-19 14:46
@mheppler I've switched out the build already so please test locally and let me know if you cannot reproduce it.

**Comment by mheppler** [comment] 2016-09-19 18:01
My notes...

> 1. Granting perms on dataverse or dataset page does not update user count on success, need to refresh page, otherwise works.

I was not able to replicate this. I went to the dataset pg, and using both the Grant Access and the Assign Access buttons, was able to see the counts updated properly with the success msg displayed.

> 2. If decide to grant access to all files to a user that already has access to some throws both a success msg and 2 exceptions, though it works and user has correct access.

This is pretty ugly. Ideally we find a better solution than multiple mixed messages, and hopefully something more specific than "The role was not able to be assigned". Also, these msgs don't follow our usual format. The Date/Time timestamps and Server names are kind of an eyesore.

![screen shot 2016-09-19 at 1 57 03 pm](https://cloud.githubusercontent.com/assets/687227/18643097/91ce3fb0-7e71-11e6-8ce6-deaa108cebf1.png)

**Comment by sbarbosadataverse** [comment] 2016-09-19 20:13
If you need me to test let me know

**Comment by sekmiller** [comment] 2016-09-20 15:44
Made the error message more user friendly when there's a Command Exception. The user will still get multiple messages if they try to assign roles that already exist multiple times. Also, nothing done WRT consolidating success and error messages.

Out of scope for now.

**Comment by kcondon** [comment] 2016-09-20 16:55
OK, more user friendly, closing.

**Closed by kcondon** 2016-09-20 16:55 UTC
Labels: Component: Permissions, Component: UX & UI, Status: QA
