### ISSUE TITLE
5.10 logo and version displaying in middle of the page and over dataset description

### ISSUE THREAD

**Issue by jmjamison** [IQSS/dataverse#8587] opened 2022-04-06 23:14 UTC
We just installed 5.10. This is a small issue but the Dataverse logo and version number are displaying oddly. Usually displayed at the lower right of the page and staying there. Logo and version number are appearing in the middle of the page (test.dataverse.ucla.edu) and sometimes on top of page text.

**Comment by pdurbin** [comment] 2022-04-07 00:42
This sounds a lot like #8506 which is a bug introduced in 5.10 and fixed in 5.10.1 by pull requests #8507 and #8565.

@jmjamison can you please take a look at screenshots at #8506 and at https://github.com/IQSS/dataverse/pull/8507#pullrequestreview-916311901 ?

If you think what you're seeing is a different bug, can you please post your own screenshots here? Thanks.

**Comment by jmjamison** [comment] 2022-04-07 01:13
That is what I'm seeing, so will go ahead with 5.10.1

Thank you,

Jamie

________________________________________

**Comment by pdurbin** [comment] 2022-04-07 11:12
Great. 5.10.1 should be an easy upgrade. Just a war file  deployment.

I'm closing this as a duplicate of #8506.

**Comment by pdurbin** [comment] 2022-04-08 18:20
@jmjamison since you're still having the problem, are you able to provide the custom footer file you're using? Or any other files you think might help us reproduce the problem (custom CSS, if you have any), etc. Thanks!

**Comment by jmjamison** [comment] 2022-04-08 19:00
Following the branding directions (https://guides.dataverse.org/en/latest/installation/config.html?highlight=branding), we have custom footer and css in /var/www/dataverse/branding/    
I'm attaching them in a zip file.   These are for the test system: [](https://test.dataverse.ucla.edu/[](url)
[custom-branding-files.zip](https://github.com/IQSS/dataverse/files/8454595/custom-branding-files.zip)
)
[custom-branding-files.zip](https://github.com/IQSS/dataverse/files/8454596/custom-branding-files.zip)

**Comment by qqmyers** [comment] 2022-04-08 19:27
One quick thing - the #footer element (e.g. a div with id 'footer') no longer exists, it is now the a footer element (which is understood as such for accessibility). That means that the `#footer` entry in your css isn't doing anything now. It may be that just changing that to `footer`, which will apply the same styling to the footer element, is all that you need.

**Comment by jmjamison** [comment] 2022-04-08 20:29
I'm going to have to check with the person doing the custom branding.  Will check back in after that.

**Comment by donsizemore** [comment] 2022-04-26 17:15
@jmjamison: per @qqmyers "quick fix is to remove position:absolute from line 52 of the resources/css/structure.css file. Not sure if that works if/when people do custom footers, etc./for all cases," but it did fix the installation I upgraded this morning.

**Comment by pdurbin** [comment] 2022-04-26 17:33
@donsizemore thanks. I'll put the line below so we can see it. From https://github.com/IQSS/dataverse/blob/v5.10.1/src/main/webapp/resources/css/structure.css#L52

`footer {position:absolute; bottom:0; width:100%; height:60px; padding-bottom:100px; color:#767676;}`

**Closed** 2022-04-26 21:37 UTC

**Comment by eunices** [comment] 2022-06-17 03:51
Just to report that we had this issue with v5.10 and v5.10.1 as well, even after removing the custom footer. It'll be good to bundle v5.10/10.1/11 together when upgrading.

**Comment by eunices** [comment] 2022-06-17 05:08
> Just to report that we had this issue with v5.10 and v5.10.1 as well, even after removing the custom footer.
> 
> May be good to bundle v5.10/10.1/11 together when upgrading on production.
