### ISSUE TITLE
Private URL To Unpublished Dataset

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1012] opened 2014-10-28 17:18 UTC
We are working to integrate with PLOS and they require a private dataset URL (similar to Google Docs or Dropbox links) which can be sent to reviewers to view specific datasets before they are published (read only). The Private URL can also be revoked.

See how figshare handles sharing private URLs: http://figshare.com/blog/figshare_new_features_Get_DOI_or_private_sharing_link/135

**Comment by posixeleni** [comment] 2015-01-07 15:21
Got a response from PLOS that either option works for them:

>Either works for me.  If there are
>different sharing options, makes sense to put them all on that page.
>There might be different options available for the type of "embargo"
>we're talking about: when journal article publishes, at a specified date
>by author, etc.

**Comment by posixeleni** [comment] 2015-01-13 09:22
Got a revised response from PLOS when they asked me to clarify the two options further: (prefer option 1 but either works)

> Thanks for the clarification.  Either works, but I prefer the first option since it makes it very clear that a private URL is an available functionality.

**Comment by eaquigley** [comment] 2015-01-13 20:03
@posixeleni I like option 1 better myself. Is cleaner and easier to get to. Will pass to @scolapasta to determine which developer can implement this.

**Comment by scolapasta** [comment] 2015-01-16 00:10
Assigning to @sekmiller for the next beta (final?)

**Comment by posixeleni** [comment] 2015-03-19 13:43
We also just received a request from Nature Publishing for this particular feature: 

>I was wondering how I can allow confidential review of datasets that are deposited in dataverse (but not yet released)? Is there a way I can provide a link to the dataset for as yet not released data for some individuals to view, without fully releasing the data? This would be very useful for us during the peer review process. Ideally the reviewer would not be able to see the identity of the individual who has uploaded the dataset (i.e. we do anonymous peer review) - is that also something we can also tweak?

They would also like the ability to hide the identity of the authors to allow for anonymous peer review (this will need to be tracked in a separate ticket).

**Comment by posixeleni** [comment] 2015-06-03 13:51
@scolapasta the design for this was already completed by @eaquigley (see mockups above) is there any chance we can change the label from design and assign to a developer?

**Comment by pdurbin** [comment] 2016-01-11 17:51
@posixeleni I noticed that this issue has a high priority number in the new spreadsheet and your name appears under "BRD Lead" so I'm assigning this to you (after consulting with @scolapasta and Len) to work on the BRD. In the spreadsheet there's no "target release" so I'll leave the milestone unassigned.

**Comment by posixeleni** [comment] 2016-03-09 15:37
BRD for this feature is here: https://docs.google.com/document/d/1FT47QkZKcmjSgRnePaJO2g1nzcotLyN3Yb2ORvBr6cs/edit

**Comment by posixeleni** [comment] 2016-03-09 18:52
@mcrosas ok to assign to @pdurbin ?

**Comment by mcrosas** [comment] 2016-03-10 04:24
yes, thanks

**Comment by pdurbin** [comment] 2016-03-24 16:51
I gave a demo to @posixeleni this morning (the code at https://github.com/pdurbin/dataverse/commit/e1029d5ecf50e6c7c87f03eade40d04e7e2e0f64 is where I built the war file from) but after talking through it with her, @scolapasta @landreev and @kcondon I'm planning on trying a different approach: creating temporary users per dataset. I added some notes to the [FRD](https://docs.google.com/document/d/1iL2b4YHYRzrOOgC4J4K0-O14PnNXjiDH31GOGoUF8P0/edit?usp=sharing).

Oh, @posixeleni and I also decided that this feature will be called "Private URL To Unpublished Dataset" so we updated this issue, the BRD, and the FRD to reflect this. No objections on this.

**Comment by pdurbin** [comment] 2016-04-01 19:43
This afternoon I gave a demo of "take 2" to @eaquigley @scolapasta and @kcondon based on code at https://github.com/pdurbin/dataverse/commit/fd566867f64539e04e354ab53f8dbc1441c7597f . Take 2 involves creating a temporary "builtin" user and we're concerned that there's no way to distinguish it from any other builtin users. The temporary user can create data, be assigned roles, etc. @eaquigley sent some updated mockups, which I added to the FRD.

@scolapasta emailed some questions to @michbarsinai for another approach, take 3, which I'll start hacking a bit on. The crux of it is wondering if we could have `:guestOfDataset1` for example as a role assignment. More to come.

**Comment by pdurbin** [comment] 2016-04-06 21:22
I just pushed "take 3" which is a work in progress toward to `:guestOfDataset1` approach: https://github.com/pdurbin/dataverse/commit/40d090b5a24e0a84c8663f4f7e808f0786ac3237 ... I'm happy to demo it for anyone who's interested. I've been discussing some of the internals with @michbarsinai

**Comment by pdurbin** [comment] 2016-04-22 17:09
Work on "take 4" (1012-private-url-token-on-roleassignment branch) began yesterday with 74141b3 and the key here is that instead of having a new `privateurl` table we are adding a new column called "privateurltoken" on the roleassignment table. So far so good. Now to work the list of UI improvements from @eaquigley below:

- I was confused when I went to a published dataset and didn’t see the Private URL option. I know it is only for unpublished datasets because I know the requirements but I’m thinking we should have it listed in the drop down and grayed out for a published dataset with a pop up that says, “Private URL can only be used with unpublished versions of datasets.”
- For a dataset with the Private URL enabled, we should add it as a blue info message on the the top that says, “Private URL is in use for this dataset."
- I still think on the permissions page it should say, “Private URL Enabled” in the User/Group Name column with the Remove Assigned Role button in the Action column.
- Need a confirmation pop up when someone clicks the “Disable Private URL” button that alerts the user with this message, “By disabling this Private URL, anyone who has been sent it will no longer be able to access this unpublished dataset.” with Confirm Disable and Cancel buttons.

**Comment by pdurbin** [comment] 2016-04-25 17:06
This morning I demo'ed "v. 4.3 build 1012-private-url-token-on-roleassignment-980c229" to most of the Dataverse team: Len, @scolapasta @landreev @mheppler @sekmiller @raprasad @eaquigley @kcondon . Overall the feedback was good. I took some notes but @eaquigley will be providing a list of changes.

**Comment by jeisner** [comment] 2016-04-25 18:08
If this feature is ready for testing by a *novice* end user, I am about to submit a paper for double-blind review and would like to include an anonymous URL to a draft version of our dataset.  

The dataset should be about 30G.  We might be encouraged to modify the format or other details before publication, so #3087 is also relevant -- that is, we'd like the ability to change the dataset.

Would you recommend trying Dataverse at this point, or just setting up an anonymous account on github to deposit the data, as we were originally planning to do?

**Comment by pdurbin** [comment] 2016-04-25 18:59
@jeisner hi! #3087 is a bug, probably a regression. We'll fix it. It should work.

Officially, the Private URL feature is slated for Dataverse 4.5 so it won't be running in production anywhere for a bit. The current released version of Dataverse is 4.3. Private URL is one of the current projects at http://dataverse.org/releases-roadmap

That said, we love feedback and I don't you checking out the feature at http://dev1.dataverse.org but please understand that I may drop the database on that server at any time. You'd want the Private URL feature in a production installation such as https://dataverse.harvard.edu before you trust it to for your actual paper. Oh, you're at Johns Hopkins. Someday you'll hopefully be able to use it at https://archive.data.jhu.edu/dvn/ (/cc @tdilauro). Anyway, maybe we can list you a stakeholder in our business requirements document at https://docs.google.com/document/d/1FT47QkZKcmjSgRnePaJO2g1nzcotLyN3Yb2ORvBr6cs/edit?usp=sharing so we remember to ping you when announce to other stakeholders that the Private URL feature is ready for feedback.

**Comment by eaquigley** [comment] 2016-04-25 19:29
Notes from today's demo:

- [ ] Need something signifying to a reviewer that a dataset is being seen via Private URL; @pdurbin will put in the blue i info box just like how it is showing currently for the dataset admin
- [ ] In the blue i info box for the dataset admin, add the Private URL link so a user doesn't have to go back into the menu to find it
- [ ] Need to check out the following use case to make sure the Private URL still works:
  - Publish V1-> Create new draft -> Create Private URL -> Deaccession V1 -> Does Private URL still work?
- [ ] @posixeleni I have a few use case questions to talk to you about with you. They relate to logging in/logging out and the Recreate URL button.

**Comment by jeisner** [comment] 2016-04-25 21:13
@pdurbin Thanks for the quick and informative reply!  And yes, please add me to the stakeholders list.  Beyond my own paper, I can say that this problem comes up increasingly in my subfield of computer science.  I'm a action editor on 2 journals and am also often involved in our conference reviewing/publishing practices.  I think it would be great if Dataverse could provide a standard solution that we could recommend to our authors.  To my knowledge, no one in my community is using Dataverse yet.

I'll post separately about my own situation.

**Comment by jeisner** [comment] 2016-04-25 21:14
@pdurbin  My own case is actually a bit simpler, and possibly common in CS.  Privacy and anonymity are separate.  I don't strictly need a **private** URL; I don't mind if the data resource is publicly discoverable before publication.  If someone manages to find it and wants to use it, more power to them!  All I need is to preserve my **anonymity**, to avoid violating the journal's policy.  In other words, whoever has the URL (in particular, reviewers) should not be able to identify me until after publication.  

Could I arrange this at present simply by creating an account with username "Anonymous Author"?  If I did that, would my email address be masked, or would I have to create an email address that can't be traced back to me?  After publication, would I be able to change the anonymous account to have my real name and email -- or better yet, transfer ownership of the dataset to my existing account (if I had one) that has my real name and email?

**Comment by posixeleni** [comment] 2016-04-26 01:25
Thanks @jeisner for your feedback and use case. Please note that we have a different github issue where we plan to work on double-blind review: https://github.com/IQSS/dataverse/issues/1724 The issue you are on currently would only be for single-blind review since as you noted the authors names can be seen by the reviewers.

**Comment by jeisner** [comment] 2016-04-26 02:25
@posixeleni - Ah, sorry to hijack the thread!  Being so accustomed to double-blind review, I mistakenly assumed that this thread was about that.  (It's hard to get my head around the fact that there are reputable journals that only use single-blind.)  So I jumped to the conclusion that "private URL" was shorthand for "private and anonymous."  But I see now that the Google Doc that @pdurbin linked to has double-blind support (anonymity) listed only in Phase 3 and marked as out-of-scope.

Thanks for the correction.  Shall I repost my comments at #1724, and edit them here to indicate that they've been moved?

**Comment by posixeleni** [comment] 2016-04-26 13:18
@jeisner yes please. Thanks for the helpful feedback!

**Comment by pdurbin** [comment] 2016-04-27 13:46
@posixeleni @eaquigley I feel like we are starting to accumulate some specific functional requirements in this issue especially at https://github.com/IQSS/dataverse/issues/1012#issuecomment-213515675 and https://github.com/IQSS/dataverse/issues/1012#issuecomment-214492199 . Can I please get some assistance from you in incorporating them into Functional Requirements Document at https://docs.google.com/document/d/1iL2b4YHYRzrOOgC4J4K0-O14PnNXjiDH31GOGoUF8P0/edit?usp=sharing ? Also, please advise if there is a need to update the mockups at https://iqssharvard.mybalsamiq.com/projects/privateurl-dataverse40/list

**Comment by eaquigley** [comment] 2016-04-28 15:46
@pdurbin 

@posixeleni and I met today to review this

- [ ] We are both in agreement with removing the recreate button from the private url pop up so you can take that out and only worry about the confirmation pop up for the disable button
- [ ] The success message on the dataset page isn't appearing when I create a private URL. I refreshed the page and then all I got was the blue i message block. There was never a success message.
- [ ] Go ahead and add the link without it being hyperlinked so we can see what it looks like

Additionally, I don't feel like we need to spend time updating the mock ups since I created screen shot mock ups for the recent changes. @pdurbin do you need a mock up with the confirmation message for the disable URL button?

**Comment by pdurbin** [comment] 2016-04-28 16:32
@eaquigley I don't feel like I need mockups, especially at this point. Without the "Recreate" button the screenshots in the FRD are out of date but as long I as know what you and @posixeleni want I guess that's all that matters.

What I really would like is for someone to clean up the requirements in the FRD at https://docs.google.com/document/d/1iL2b4YHYRzrOOgC4J4K0-O14PnNXjiDH31GOGoUF8P0/edit?usp=sharing (now there are three lists in this issue of things to change) which @posixeleni has offered to do next week. Thanks @posixeleni !!! Especially missing from the FRD is what the user experience should be for the person clicking the link. I think we'd like that FRD to be in decent shape before we pass this issue to @kcondon for QA. (Maybe he'd like the screenshots in the FRD to match reality.)

**Comment by pdurbin** [comment] 2016-05-08 04:11
I started writing what I'm calling a "Private URL Design Doc" to describe the implementation of Private URL in my fork of Dataverse at https://github.com/pdurbin/dataverse/tree/1012-private-url-token-on-roleassignment as of d2c89dd . It's a work in progress and the design may change before I make a pull request but I enabled public comments in case anyone would like to give feedback, which I certainly welcome: https://docs.google.com/document/d/1ENQCT0g2x9tdTep3ImtAHFww8f1WJr9d2o4UMcr_gSM/edit?usp=sharing

**Comment by pdurbin** [comment] 2016-05-10 20:54
Today I gave a demo to @mcrosas @posixeleni @eaquigley @sbarbosadataverse and @scolapasta of the Private URL feature I've been working on. Everyone was supportive of me going ahead and making a pull request, which I did at #3111. The pull requests is full of links to requirements, a design document I just wrote, updated API guides, etc. Passing to QA.

**Comment by pdurbin** [comment] 2016-06-22 19:20
Today @djbrooke @mheppler and I met to discuss the Private URL feature and the state of the branch, open issues, and pull request.

We are now definitely targeting 4.5 so in 95570c7 I renamed the SQL script to have the target release in it (`upgrade_v4.4_to_v4.5.sql`)

I'm going to pass this issue to @scolapasta to weigh in on a javadoc comment/todo about the identifier (":privateUrl42" vs. "#42" or "#privateURL42" or whatever else) that I mentioned before but have since reworded: https://github.com/IQSS/dataverse/blob/9480a63ec41e117c7868786ed44fb2276f62469a/src/main/java/edu/harvard/iq/dataverse/privateurl/PrivateUrlUtil.java#L27

Here's a screenshot:

![screen shot 2016-06-22 at 3 15 35 pm](https://cloud.githubusercontent.com/assets/21006/16280295/dbfa5464-388c-11e6-8370-032f4c199f4d.png)

**Comment by pdurbin** [comment] 2016-06-24 15:12
I just left a status update at https://github.com/IQSS/dataverse/pull/3111#issuecomment-228370372 (the pull request for this feature).

Since this issue is mostly about the code from my perspective, I'm going to pass it to @mheppler who can move this to QA when he's done reviewing or changing things in #3174. Please note that there is a separate issue about docs at #3138.

**Comment by mheppler** [comment] 2016-06-27 19:00
Workflow displaying "Success!" msg is great. After reviewing with @pdurbin and @scolapasta we're going to fine tune it an improvement to the backing bean.

**Comment by pdurbin** [comment] 2016-06-27 19:58
@mheppler @scolapasta and I worked through the final fixes for the success message in 50ae521 . It's working as desired now.

Passing to QA.

**Comment by pdurbin** [comment] 2016-07-08 17:19
I took pull request #3111 out of QA due to #3200 and #3201 so I'm taking this out of QA as well.

**Comment by pdurbin** [comment] 2016-07-14 13:24
@scolapasta please see https://github.com/IQSS/dataverse/issues/3200#issuecomment-232458080

**Comment by pdurbin** [comment] 2016-07-14 20:45
@scolapasta and @michbarsinai blessed the fix at 24df280 so I merged it into pull request #3111. Passing to QA.

**Comment by kcondon** [comment] 2016-07-18 17:02
Tested according to the design doc in github and looks good, closing.

**Closed by kcondon** 2016-07-18 17:02 UTC
Labels: Component: Metadata, Component: Permissions, Priority: High, Status: QA, Type: Feature
