### ISSUE TITLE
View Dataset: Versions tab does not display file restriction info

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1747] opened 2015-03-22 19:29 UTC
Not sure how important this is but I was testing the behavior of file restriction by version and changing file perms creates a new draft. However, these changes do not appear on the file versions tab/ differences so you can't determine why a new version was made.

**Comment by scolapasta** [comment] 2015-04-18 19:14
This is a duplicate of #1410

**Closed** 2015-06-02 21:51 UTC
Labels: Component: UX & Upgrade, Priority: Medium, Status: QA, Type: Bug
