### ISSUE TITLE
Save on Upload error: Upload 3 files at once with descriptions and custom tags results in exception.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4918] opened 2018-08-03 18:10 UTC
Uploading 3 files to an already created, unpublished draft in production results in an exception error.
The 3 files are 1 doc, 1 tab, 1 .sav. All have descriptions and 2 custom tags.
They belong to: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/AUSK9U&version=DRAFT
Clicking save on the same dataset eventually succeeds after a few clicks.

This does not happen if the files have a single, non custom tag, nor does it happen with only the tabular file with description and custom tags.

This seems similar to #3482

Here is the stack trace:

    Local Exception Stack: 
    Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
    Internal Exception: org.postgresql.util.PSQLException: ERROR: null value in column "createdate" violates not-null constraint
      Detail: Failing row contains (3202469, DataFile, null, null, 2018-08-03 13:42:36.001, null, 2018-08-03 13:42:36.001, null, null, 3202467, null, f, s3://dvn-cloud:16500e24ee1-46a7832bb091, null, null, f, null, null).
    Error Code: 0
    Call: INSERT INTO DVOBJECT (AUTHORITY, CREATEDATE, GLOBALIDCREATETIME, IDENTIFIER, IDENTIFIERREGISTERED, INDEXTIME, MODIFICATIONTIME, PERMISSIONINDEXTIME, PERMISSIONMODIFICATIONTIME, PREVIEWIMAGEAVAILABLE, PROTOCOL, PUBLICATIONDATE, STORAGEIDENTIFIER, CREATOR_ID, OWNER_ID, RELEASEUSER_ID, DTYPE) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        bind => [17 parameters bound]
    Query: InsertObjectQuery([DataFile id:null name:null])
        at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:340)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.processExceptionForCommError(DatabaseAccessor.java:1611)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:898)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeNoSelect(DatabaseAccessor.java:962)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:631)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:558)
        at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2002)
        at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:298)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.insertObject(DatasourceCallQueryMechanism.java:363)
        at org.eclipse.persistence.internal.queries.StatementQueryMechanism.insertObject(StatementQueryMechanism.java:165)
        at org.eclipse.persistence.internal.queries.StatementQueryMechanism.insertObject(StatementQueryMechanism.java:180)
        at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.insertObjectForWrite(DatabaseQueryMechanism.java:489)
        at org.eclipse.persistence.queries.InsertObjectQuery.executeCommit(InsertObjectQuery.java:80)
        at org.eclipse.persistence.queries.InsertObjectQuery.executeCommitWithChangeSet(InsertObjectQuery.java:90)
        at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.executeWriteWithChangeSet(DatabaseQueryMechanism.java:301)
        at org.eclipse.persistence.queries.WriteObjectQuery.executeDatabaseQuery(WriteObjectQuery.java:58)
        at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:899)
        at org.eclipse.persistence.queries.DatabaseQuery.executeInUnitOfWork(DatabaseQuery.java:798)
        at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWorkObjectLevelModifyQuery(ObjectLevelModifyQuery.java:108)
        at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWork(ObjectLevelModifyQuery.java:85)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1804)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1786)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1737)
        at org.eclipse.persistence.internal.sessions.CommitManager.commitNewObjectsForClassWithChangeSet(CommitManager.java:226)
        at org.eclipse.persistence.internal.sessions.CommitManager.commitAllObjectsForClassWithChangeSet(CommitManager.java:193)
        at org.eclipse.persistence.internal.sessions.CommitManager.commitAllObjectsWithChangeSet(CommitManager.java:138)
        at org.eclipse.persistence.internal.sessions.AbstractSession.writeAllObjectsWithChangeSet(AbstractSession.java:4207)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabase(UnitOfWorkImpl.java:1441)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabaseWithPreBuiltChangeSet(UnitOfWorkImpl.java:1587)
        at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.writeChanges(RepeatableWriteUnitOfWork.java:452)
        at org.eclipse.persistence.internal.jpa.EntityManagerImpl.flush(EntityManagerImpl.java:863)
        at com.sun.enterprise.container.common.impl.EntityManagerWrapper.flush(EntityManagerWrapper.java:437)
        at edu.harvard.iq.dataverse.DataFileServiceBean.mergeFileMetadata(DataFileServiceBean.java:988)
        at sun.reflect.GeneratedMethodAccessor1723.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)
        at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
        at sun.reflect.GeneratedMethodAccessor108.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
        at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
        at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
        at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
        at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
        at com.sun.proxy.$Proxy204.mergeFileMetadata(Unknown Source)
        at edu.harvard.iq.dataverse.__EJB31_Generated__DataFileServiceBean__Intf____Bean__.mergeFileMetadata(Unknown Source)
        at edu.harvard.iq.dataverse.EditDatafilesPage.save(EditDatafilesPage.java:1246)
        at sun.reflect.GeneratedMethodAccessor1817.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.el.parser.AstValue.invoke(AstValue.java:289)
        at com.sun.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:304)
        at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
        at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
        at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105)
        at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:87)
        at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:102)
        at javax.faces.component.UICommand.broadcast(UICommand.java:315)
        at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790)
        at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282)
        at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:295)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:412)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "createdate" violates not-null constraint
      Detail: Failing row contains (3202469, DataFile, null, null, 2018-08-03 13:42:36.001, null, 2018-08-03 13:42:36.001, null, null, 3202467, null, f, s3://dvn-cloud:16500e24ee1-46a7832bb091, null, null, f, null, null).
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2157)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1886)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:559)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:417)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:363)
        at sun.reflect.GeneratedMethodAccessor770.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.postgresql.ds.jdbc23.AbstractJdbc23PooledConnection$StatementHandler.invoke(AbstractJdbc23PooledConnection.java:453)
        at com.sun.proxy.$Proxy334.executeUpdate(Unknown Source)
        at com.sun.gjc.spi.base.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:125)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:890)
        ... 119 more
    ]]

**Comment by kcondon** [comment] 2019-08-09 17:10
Not sure this is the same issue since the circumstances are slightly different as is the server log error but it does have the combination of custom and tabular tags in common so I'm adding it here. Please note that it does not seem to always happen.

Warning:   Method not found: edu.harvard.iq.dataverse.EditDatafilesPage@7b6bfe8b.TabularTagsSelection(javax.faces.event.AjaxBehaviorEvent)
javax.el.MethodNotFoundException: Method not found: edu.harvard.iq.dataverse.EditDatafilesPage@7b6bfe8b.TabularTagsSelection(javax.faces.event.AjaxBehaviorEvent)
    at com.sun.el.util.ReflectionUtil.getMethod(ReflectionUtil.java:160)
    at com.sun.el.parser.AstValue.invoke(AstValue.java:286)
    at com.sun.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:304)
    at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
    at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
    at org.primefaces.behavior.ajax.AjaxBehaviorListenerImpl.processCustomArgListener(AjaxBehaviorListenerImpl.java:101)
    at org.primefaces.behavior.ajax.AjaxBehaviorListenerImpl.processArgListener(AjaxBehaviorListenerImpl.java:83)
    at org.primefaces.behavior.ajax.AjaxBehaviorListenerImpl.processAjaxBehavior(AjaxBehaviorListenerImpl.java:64)
    at javax.faces.event.AjaxBehaviorEvent.processListener(AjaxBehaviorEvent.java:113)
    at javax.faces.component.behavior.BehaviorBase.broadcast(BehaviorBase.java:106)
    at javax.faces.component.UIComponentBase.broadcast(UIComponentBase.java:804)
    at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790)
    at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282)
        ...
That was using an existing draft, no files, ingest tab, go to Edit Files pg, apply custom and tabular tag, before you leave the popup you can see the tabular tag is not applied when selected from the popup. Saw the error in the logs. Clicked save and still didnt see a tabluar tag.

**Comment by matthew-a-dunlap** [comment] 2020-07-06 17:08
I think we are running into a similar issue at UNC on 4.16. One of our archivists has been uploading files and editing the metadata before saving, which errors about the createdate. She says she's only using native DV tags, no custom ones. Its happened with 3-15 files, she hasn't attempted this with only 1 file.

As she describes it: 

> Issue: When going to draft records and clicking on the Upload Files button, I get redirected to the Upload Files screen per usual. I then drag and drop my files into the box and edit the metadata. Then I hit Save and get this lovely, super descriptive error message at the top of the screen: The files could not be updated. – Please contact UNC Dataverse Support for assistance. Date/Time: 2020-07-06 16:12:59 Server: dataverse.unc.edu

Here is our full stack trace passed to me by @donsizemore :

```Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: null value in column "createdate" violates not-null constraint
  Detail: Failing row contains (7510723, DataFile, null, null, 2020-07-06 12:08:38.365, null, 2020-07-06 12:08:38.365, f, null, null, 7509799, null, 17324e2ecdd-871743380e7e, null, null, f, null, null).
Error Code: 0
Call: INSERT INTO DVOBJECT (AUTHORITY, CREATEDATE, GLOBALIDCREATETIME, IDENTIFIER, IDENTIFIERREGISTERED, INDEXTIME, MODIFICATIONTIME, PERMISSIONINDEXTIME, PERMISSIONMODIFICATIONTIME, PREVIEWIMAGEAVAILABLE
, PROTOCOL, PUBLICATIONDATE, STORAGEIDENTIFIER, CREATOR_ID, OWNER_ID, RELEASEUSER_ID, DTYPE) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        bind => [17 parameters bound]
Query: InsertObjectQuery([DataFile id:null label:SRSS Child-Level Public Access Data Final Coh 2 & 3 n = 138.sav])
        at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:340)

<snip>

Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "createdate" violates not-null constraint
  Detail: Failing row contains (7510723, DataFile, null, null, 2020-07-06 12:08:38.365, null, 2020-07-06 12:08:38.365, f, null, null, 7509799, null, 17324e2ecdd-871743380e7e, null, null, f, null, null).
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)

then

[#|2020-07-06T12:10:03.552-0400|WARNING|glassfish 4.1|edu.harvard.iq.dataverse.ingest.IngestServiceBean|_ThreadID=51;_ThreadName=jk-connector(5);_TimeMillis=1594051803552;_LevelValue=900;|
  Failed to save the file, storage id 17324e2dfc3-d62af8c5e7c6 (/usr/DVN/data/temp/17324e2dfc3-d62af8c5e7c6)|#]

[#|2020-07-06T12:10:03.558-0400|WARNING|glassfish 4.1|edu.harvard.iq.dataverse.ingest.IngestServiceBean|_ThreadID=51;_ThreadName=jk-connector(5);_TimeMillis=1594051803558;_LevelValue=900;|
  Failed to delete temp file /usr/DVN/data/temp/17324e2dfc3-d62af8c5e7c6|#]

[#|2020-07-06T12:10:03.559-0400|WARNING|glassfish 4.1|edu.harvard.iq.dataverse.ingest.IngestServiceBean|_ThreadID=51;_ThreadName=jk-connector(5);_TimeMillis=1594051803559;_LevelValue=900;|
  Failed to save the file, storage id 17324e2ec4f-2120342c5986 (/usr/DVN/data/temp/17324e2ec4f-2120342c5986)|#]

[#|2020-07-06T12:10:03.564-0400|WARNING|glassfish 4.1|edu.harvard.iq.dataverse.ingest.IngestServiceBean|_ThreadID=51;_ThreadName=jk-connector(5);_TimeMillis=1594051803564;_LevelValue=900;|
  Failed to delete temp file /usr/DVN/data/temp/17324e2ec4f-2120342c5986|#]

[#|2020-07-06T12:10:03.565-0400|WARNING|glassfish 4.1|edu.harvard.iq.dataverse.ingest.IngestServiceBean|_ThreadID=51;_ThreadName=jk-connector(5);_TimeMillis=1594051803565;_LevelValue=900;|
  Failed to save the file, storage id 17324e2ecdd-871743380e7e (/usr/DVN/data/temp/17324e2ecdd-871743380e7e)|#]

[#|2020-07-06T12:10:03.570-0400|WARNING|glassfish 4.1|edu.harvard.iq.dataverse.ingest.IngestServiceBean|_ThreadID=51;_ThreadName=jk-connector(5);_TimeMillis=1594051803570;_LevelValue=900;|
  Failed to delete temp file /usr/DVN/data/temp/17324e2ecdd-871743380e7e|#]

[#|2020-07-06T12:10:03.594-0400|INFO|glassfish 4.1|edu.harvard.iq.dataverse.ingest.IngestServiceBean|_ThreadID=51;_ThreadName=jk-connector(5);_TimeMillis=1594051803594;_LevelValue=800;|
  Ingest of 2 tabular data file(s) is in progress.|#]

then the non-existent files unsurprisngly fail ingest.```

**Comment by sekmiller** [comment] 2020-07-06 19:46
I could not get this to happen with multiple files in Dataverse 5. I tried with both "regular" files and tabular and regular and custom tags. And updating "description" but not File Path at the same time as adding tags.

**Comment by matthew-a-dunlap** [comment] 2020-07-06 20:04
@sekmiller Thanks for doing that! I ended up testing the bug myself on my end too, and while I can get it to manifest in 4.16 it doesn't happen in DV5. 

@akio-sone looked into the code and reported that :
> DataFileServiceBean.java#mergeFileMetatada(), the method that threw the above EclipseLink exception,  is no longer used in the post-4.20-dev branch although this method  was used/called in EditDataFilePage. java#save() of version 4.16.  So I'm afraid that this failure might be specific to version 4.16 or before.

So I guess our archivist will work around this until we upgrade. Not sure if @kcondon 's previous issue has the same root cause, but if it does maybe this issue can be closed.

**Comment by djbrooke** [comment] 2020-08-12 16:17
I'm going to close this one since there has been some retesting. We can retest if we have the cycles, in which case we'll reopen.

**Closed by djbrooke** 2020-08-12 16:17 UTC
Labels: Feature: File Upload & Handling
