### ISSUE TITLE
Linked dataverses dont (always) show up in their linking dataverses

### ISSUE THREAD

**Issue by AACGSR** [IQSS/dataverse#7430] opened 2020-11-19 08:03 UTC
Very closely related to: 
- #8724   

- using version v. 5.1.1 build 221-1b59dac

Our Dataverses hierarchy goes root - level 1 - level 2 - level 3. All three levels have multiple dataverses.

Many linked dataverses dont appear in their linking dataverses. The link Dataverse API gives back 200 and a database entry is added properly, yet they don't show up being linked in those dataverses. Neither reindexing the linking dataverses nor a full reindex helps with this.

Linking level 1 into level 1 works.
Linking level 2 into level 1 works.
Linking level 3 into level 1 works.

Linking level 1 into level 3 doesnt work.
Linking level 2 into level 3 doesnt work.
Linking level 1 into level 2 doesnt work.
Linking level 2 into level 2 doesnt work.
Linking level 3 into level 3 doesnt work.
Linking level 3 into level 2 doesnt work.

We assume that linking a superior level dataverse into a subordinated dataverse does not work as a feature, since it's considered to be unlogical (please correct me if this should work).
However this doesnt explain all of the "doesnt work" lines above.

**Comment by djbrooke** [comment] 2020-11-19 13:54
Hi @AACGSR - it's possible that you're running into this issue, just on a Dataverse instead of a Dataset:

https://github.com/IQSS/dataverse/issues/7259

Can you see if there are multiple entries in the DB?

**Comment by AACGSR** [comment] 2020-11-20 10:41
Thanks @djbrooke 

Indeed there was a double entry I did know about (the first time the linked dataverse didnt show up, I linked it via GUI, and retried using the API for the same link, which resulted in two rows in the DB). However, every other link that failed only has one DB entry. I just deleted the 2nd row of the double entry and ran a reindex. Unfortunately, that did not help.

**Comment by pdurbin** [comment] 2020-11-20 15:25
I just wanted to mentioned I fixed the double row/entry problem in 5d4a3dc in pull request #7415 but it hasn't been merged yet.

**Comment by pdurbin** [comment] 2020-11-20 17:42
>  Linking level 2 into level 2 doesnt work.

I can confirm that this doesn't work (and I assume deeper levels don't work either). In 403a96644 for pull request #7415 I wrote some tests to exercise this. Hopefully they will be a good starting point when we pick this up.

**Comment by kcondon** [comment] 2020-11-20 23:44
I'm assuming the test cases are between two separate dataverses so linking level 1 of dv1 to level 1 of dv2, level 2 of dv1 (dv1_1) into level 2 of dv2 (dv2_1)?

While testing the duplicate linking pr, I did find you could like a parent dv into a child dv, which I don't think should be allowed. That is possible in both the UI and API.

**Comment by AACGSR** [comment] 2020-11-23 07:58
> I'm assuming the test cases are between two separate dataverses so linking level 1 of dv1 to level 1 of dv2, level 2 of dv1 (dv1_1) into level 2 of dv2 (dv2_1)?

Exactly!

**Comment by AACGSR** [comment] 2020-12-21 14:57
> I'm assuming the test cases are between two separate dataverses so linking level 1 of dv1 to level 1 of dv2, level 2 of dv1 (dv1_1) into level 2 of dv2 (dv2_1)?

@kcondon sorry for the late answer, but to be explicit: yes, you assumed correctly!

**Comment by plesubc** [comment] 2022-05-13 18:42
UBC is experiencing similar behaviour with Dataverse v5.6 (cf: [https://groups.google.com/g/dataverse-community/c/DDmVelt3Zfk](https://groups.google.com/g/dataverse-community/c/DDmVelt3Zfk))

Note that this behaviour is not limited to our production server; it also occurs on our test server with newly created collections and data sets. Generally speaking, the linking we are generally using is with datasets on the same hierarchy.

root
  collection A
  collection B
  collection C
    collection D

Collections B and C, if linked to A, show only the collection title but no contents. Even if collection D is linked directly to A, there are no contents displayed, even though D is one level down.

**Comment by pdurbin** [comment] 2022-05-20 13:46
Seems related:

- #8724

**Comment by mreekie** [comment] 2022-05-23 18:27
priority:
- This came in from a customer this week.
- Brought in by Gustavo.

**Comment by mreekie** [comment] 2022-05-25 17:52
@scolapasta - is this part of the harvesting feature?

**Comment by pdurbin** [comment] 2022-10-01 02:25
@mreekie no, this is unrelated to harvesting.

**Comment by mreekie** [comment] 2022-12-12 17:30
Sizing:
 - Deferred
 - we need @sekmiller for this.

**Comment by mreekie** [comment] 2023-01-04 16:26
sizing discussion [here](https://github.com/IQSS/dataverse/issues/8724#issuecomment-1371144794)

This one is sized at an 80 since it could be more complex.

**Comment by pdurbin** [comment] 2023-01-23 23:44
closed by this PR:

- #9304

**Closed by pdurbin** 2023-01-23 23:44 UTC
Labels: Size: 80, FY26 Sprint 14
