### ISSUE TITLE
"Add data" feature displays an uncommon error

### ISSUE THREAD

**Issue by bappun** [IQSS/dataverse#6673] opened 2020-02-24 13:55 UTC
As a user without the permission to add data, I can still see the "Add data" nav link in the menu and click on it. Doing so, I get an not authorized access error and also another one which isn't user friendly and a bit scary:

```
This page contains the following errors:
error on line 164 at column 69: AttValue: " or ' expected
Below is a rendering of the page up to the first error.
```
![data sciencespo fr_dataverse xhtml_ownerId=1 (1)](https://user-images.githubusercontent.com/24225471/75157788-21219480-5715-11ea-9a2f-b56b39484b39.png)

Moreover while on this page, I can't click any link in the menu (except the logo and user guide links).

Notes:
- The dataverse doesn't contain any published data
- Dataverse v. 4.19 build 331-affbf4f

**Comment by djbrooke** [comment] 2020-02-25 21:49
Hi @bappun is the root dataverse published? Also, can you let me know how the permissions are set up for the root dataverse? Specifically:

Who can add to this dataverse?
When a user adds a new dataset to this dataverse, which role should be automatically assigned to them on that dataset?

Thank you!

**Comment by pdurbin** [comment] 2020-02-25 22:10
@bappun in addition, can you reproduce the error on https://demo.dataverse.org ?

**Comment by djbrooke** [comment] 2020-02-25 22:16
@pdurbin I thought of that, but I think because we let all users Add Data on demo, it's not set up for this barring a permissions change. 🤷‍♂ ?

**Comment by pdurbin** [comment] 2020-02-25 22:17
@djbrooke ah, but each dataverse (subdataverse, if you will), is an island of permissions. So as long as @bappun creates a dataverse on demo he should be able to test there. I hope. 😄

**Comment by bappun** [comment] 2020-02-26 10:17
Hi everyone, we just found out why there was a strange red box with an error on this page and it was because of a html parsing error due to the modification of the copyright footer with a malformed html tag on our side. However the error wasn't displayed on other pages which is a bit intriguing since the custom footer works on other pages.

Sorry for the inconvenience. I think we can close this issue :smiley:

**Comment by pdurbin** [comment] 2020-02-26 10:48
@bappun weird. Do you think it would be easy to reproduce this if we had your footer file? Or if you showed how you would edit the custom footer at http://guides.dataverse.org/en/4.19/installation/config.html#custom-footer to introduce a malformed html tag to reproduce the error?

If this sounds like too much work, please feel free to simply close this issue. 😄

**Comment by bappun** [comment] 2020-02-26 14:23
@pdurbin We got the error after using the `:FooterCopyright` with this command:
`curl -X PUT -d ", Sciences Po | <a href="https://data.sciencespo.fr/misc/cond_jur/ToU.pdf" target="_blank">General Terms of Use</a>" http://localhost:8080/api/admin/settings/:FooterCopyright`

Which has wrong quotes, so we changed the command to:
`curl -X PUT -d ', Sciences Po | <a href="https://data.sciencespo.fr/misc/cond_jur/ToU.pdf" target="_blank">General Terms of Use</a>' http://localhost:8080/api/admin/settings/:FooterCopyright`

And now it's working.

I think you could reproduce the error using the first command, then going to Add dataverse/dataset from the menu.

**Comment by mheppler** [comment] 2020-02-26 14:57
@bappun I am going to add your comment to another issue we currently have, **As a sysadmin, I would like an easy option to link to legal notice #6676**, because in the code snippet you shared, I can see you have added a "General Terms of Use" link to your footer through the copyright configuration setting. We are considering a redesign of that feature to make it easier for installations to add links like these.

If you have any additional information about your use case, please add it to that issue.

**Comment by bappun** [comment] 2020-02-26 15:52
@mheppler Thank you!

**Closed** 2020-04-14 20:32 UTC
