### ISSUE TITLE
For Dataverse users, record (1) date created, (2) last login, and (3) lastApiUse

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3246] opened 2016-08-08 15:11 UTC
Add the following timestamp columns to the authenticated user table:
- authenticateduser.created
- authenticateduser.last_login  (this may already be covered by 'modificationtime')
- authenticateduser.last_confirmed (possible - @scolapasta's discretion)

To supply basic metrics to stakeholders and dev. team including:
- how many users are added to the system during specific time periods (e.g. users added per month)
- how many people log in to the system  (e.g. each month, each day, etc.)
- how many accounts are "inactive" -- e.g. haven't logged in for extended periods of time
- when does activity spike for logged in users, etc

**Comment by pdurbin** [comment] 2016-08-15 17:08
Related: #2470

**Comment by raprasad** [comment] 2017-06-14 20:11
- [ ] do we want to record lastlogin info for API calls?
  - e.g. file: ```AbstractAPIBean.java``` method: ```findAuthenticatedUserOrDie```

**Comment by pdurbin** [comment] 2017-06-25 12:21
@bsilverstein95 is the code your writing a fix for #2470? Should we close that issue as a duplicate of this one?

**Comment by pdurbin** [comment] 2017-06-25 19:02
@bsilverstein95 same question for issue #2485.

**Comment by bsilverstein95** [comment] 2017-06-26 14:14
@pdurbin For #2470 yes, my code for this issue covers it with addition of `authenticateduser.createdtime`; as for #2485 (which is already closed now!) it effectively covers that as well except I haven't modified the `builtinuser` table.

**Closed** 2017-06-27 16:33 UTC
Labels: Component: Account & User Info, Component: Code Infrastructure, Type: Feature
