### ISSUE TITLE
Deaccessioned Dataset: edit dataset button doesn't render when a draft exists before dataset version is deaccessioned

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#3096] opened 2016-04-29 14:34 UTC
If a user has a published version of a dataset, creates a draft, and then deaccessions the published version, the Edit button for the dataset doesn't appear in the right corner of the page. It still renders within the individual tabs.

![screen shot 2016-04-29 at 10 34 21 am](https://cloud.githubusercontent.com/assets/5922904/14919245/f658c47e-0df5-11e6-991d-87cbe29539e7.png)

Saw this on demo.dataverse.org

**Comment by mheppler** [comment] 2016-10-20 20:01
Closing this issue as a duplicate of #1308.

**Closed by mheppler** 2016-10-20 20:01 UTC
Labels: Component: Publishing & Versions, Component: UX & UI
