### ISSUE TITLE
order "publication date" facet: facet should appear in order by year

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2936] opened 2016-02-09 18:16 UTC
currently "publication date" facet shows up by "year with most datasets"--Gary would like to see it ordered by "year" regardless of # of datasets published, and this can be part of giving the dataverse admin more options in displaying their facets, feature?

**Comment by pdurbin** [comment] 2016-02-09 18:22
I left a related comment at https://github.com/IQSS/dataverse/issues/70#issuecomment-181405821

**Comment by eaquigley** [comment] 2016-02-09 18:30
@thegaryking the standard way facets work would be to have it the way we currently do it or as @pdurbin says, by using a slider with the ability to input specific years to determine the range of dates. The Harvard HOLLIS Catalog and most databases use the slider (examples below). If the slider works for you, then we should close this ticket and prioritize #70.

![screen shot 2016-02-09 at 1 26 12 pm](https://cloud.githubusercontent.com/assets/5922904/12926382/3720e828-cf31-11e5-8b56-88c5f2a1e8ff.png)

![screen shot 2016-02-09 at 1 26 20 pm](https://cloud.githubusercontent.com/assets/5922904/12926386/3bfee6d8-cf31-11e5-8fee-ab4276ce3ed0.png)

**Comment by mheppler** [comment] 2016-10-12 19:18
Closing this issue as a duplicate of **Search/Browse: Improve facet UI for dates in fields such as "Publication Date" #70**.

**Closed by mheppler** 2016-10-12 19:18 UTC
Labels: Component: Metadata, Type: Feature, Type: Suggestion
