### ISSUE TITLE
Error message when trying to delete file

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse#7026] opened 2020-06-26 16:45 UTC
Earlier today, I tried to delete [this file](https://dataverse.no/file.xhtml?persistentId=doi:10.18710/JWTJJB/BX3XCM&version=1.0) in DataverseNO, which is running on Dataverse v. 4.19. I got the following error message:

![image](https://user-images.githubusercontent.com/21955790/85880589-8b8a3480-b7dc-11ea-8913-c41397955c58.png)

But when I refreshed the page, the file was deleted, and I was able to upload a new [version of it](https://dataverse.no/file.xhtml?persistentId=doi:10.18710/JWTJJB/O77MAT&version=2.0).

An extract from the log file for the period in question is available [here](https://drive.google.com/file/d/1nbXV0sVbPGALODL1OJk7_FBgZKuYWhoL/view?usp=sharing).

We have experience similar behavior in other datasets.

**Comment by pdurbin** [comment] 2020-06-26 17:55
@philippconzett thanks for the log. Here's the relevant error:

Caused by: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://localhost:8983/solr/collection1: ERROR: [doc=datafile_19493] unknown field 'fileDeleted'

The fix is to update your Solr schema.xml to include that "fileDeleted" field. Please see the releases notes at https://github.com/IQSS/dataverse/releases/tag/v4.15 . This field was added in pull request #5820.

This was also reported at #6457.

**Comment by djbrooke** [comment] 2020-06-26 20:48
@philippconzett I'm going to close this, but feel free to comment here if the solution that @pdurbin mentioned doesn't resolve this.

**Closed by djbrooke** 2020-06-26 20:48 UTC
