### ISSUE TITLE
Facets: "More" and "Less" links stopped working, works in v4.16

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#6191] opened 2019-09-19 17:04 UTC
While testing another facet issue, noticed the more link does nothing -does not expand view, throws no errors, no browser errors.

**Comment by mheppler** [comment] 2019-09-19 18:04
[@pdurbin figured this out... I'm just writing it up...]

In the commit 2c2f70390b903bf7ab3f2dc29c3aef51f6da6608 @landreev commented out the `@ViewScoped` and added `@RequestScoped` in SearchIncludeFragment.java as an attempt to combat memory issues in #6035.

That is all well and good for all the facet links in search-include-fragment, that open new pages with new views, but not so for the "More" and "Less" links that do partial refreshes of the facet links for that category.

Here is the More link in search-include-fragment.xhtml:

```
<p:commandLink actionListener="#{SearchIncludeFragment.incrementFacets(facetCategory.name,5)}" update="facetCategoryList" rendered="#{SearchIncludeFragment.getNumberOfFacets(facetCategory.name,5) lt facetCategory.facetLabel.size()}">#{bundle.more}</p:commandLink>
```

**Comment by pdurbin** [comment] 2019-09-19 18:15
I went ahead made pull request #6193 to revert the backing bean to ViewScoped but I think we're going to want a better fix (we can just keep it our back pocket) and @sekmiller is going to take a look.

If anyone wants to see the More button not working, you can go to http://phoenix.dataverse.org (which runs develop). Everyone here reading this probably knows what More button we're talking about but here's a screenshot:

![Screen Shot 2019-09-19 at 2 14 22 PM](https://user-images.githubusercontent.com/21006/65269793-e2453e00-dae7-11e9-8bf3-c44f9469fdc2.png)

**Comment by landreev** [comment] 2019-09-19 19:34
@pdurbin you are correct, we want a better fix. as in, we don't want to revert something that has improved the dataverse page so dramatically,  on account of a minor cosmetic thing that took weeks to even be noticed.

**Comment by pdurbin** [comment] 2019-09-19 19:38
@landreev sounds good. That's what @sekmiller and I weren't sure about when we were chatting just now... how much the scope changed helped. (Obviously, the session change was a big help too.) Thanks.

**Comment by landreev** [comment] 2019-09-19 19:56
I can work on this, yes. There's no reason it shouldn't be possible to handle it the same way we handle pagination - to have all the state info the page needs embedded in the links.

**Comment by kcondon** [comment] 2019-09-25 16:26
@landreev @mheppler 
Some quick feedback on the solution you might want to review:
1. when clicking on the more link, it jumps to the top of the page, unlike the current solution, which simply expands in place. This can be somewhat confusing. Looking for Design feedback here.
2. after opening one set of facets by clicking more, then clicking on another one, it closes the first, unlike the current implementation, which leaves it open. again, looking for Design feedback here.

**Comment by landreev** [comment] 2019-09-25 16:54
(adding @scolapasta as well)
On the 2 issues reported: 

1) Is by design - I changed the way these links work, from being ajax driven (which required the backing bean to be ViewScoped) to rendered links. In other words, switched to handling them the way we've been handling pagination links - with the link itself having all the state information embedded into itself. I mentioned this in the PR. I acknowledge that it has the drawback of being less pretty, than keeping these updates dynamic. But I feel pretty strongly that it's worth it, because keeping the bean RequestScoped makes the page so much more efficient memory-wise (none of the objects below Dataverse even make it to oldgen, ever). So I would be very very happy if we could keep this solution. 

2) Yes, the current solution only expands one facet at a time. That's what I meant in the commit message when I said it had "limitations". I was curious if anyone was going to notice and/or care. 
I can definitely fix this, by adding more state information to the links. Please let me know if it's worth fixing. 

One thing I have to say, facets are generally nice, they make the site look professional and whatnot... but, according to the logs, nobody seems to be using them all that much (except for the bots, who indeed crawl them with abandon). In real life, few people come to the site not quite knowing what it is that they need and go through the facets to see what's available... All that said, I'll do whatever I can to improve how these things work/look etc., as long as we can keep the underlying SearchIncludeFragment RequestScoped...

**Comment by scolapasta** [comment] 2019-09-25 17:05
Agree 100% we want to keep the idea of RequestScoped here (or find an alternative solution to GCing these objects, but for now the RequestScoped way is straightforward)

I do think this is a regression in the design of these facets (both 1 and 2). Other links (clicking on an actual facet, pagination, etc) change the dvobjects shown, so it makes perfect sense to treat as a new page and start from the top. In this case, though, all you are changing is the available facets right there, so the reloading will be confusing and awkward.

I think we can live with it, if getting this into 4.17 is a priority (my opinion is it is), and if 4.17 needs to be released ASAP.

If it doesn't, then we can try to explore some other options:
- an ajax call that doesn't need the view around? (redo search and just return the facets?)
- load the facet upfront and show / hide via javascript

A possible hybrid solution would be to release this with 4.17 and trying on of these alternatives post 4.17.

**Comment by mheppler** [comment] 2019-09-25 17:30
Re: $0.02 idea to resolve jumping to the top of the page...

If we added anchors to the facet category headers (e.g. `<a name="authorName_ss"><span class="facetCategoryName">Author Name</span></a>`), then we could add those anchors to the More and Less link URL's (e.g. `/dataverse/root?q=&fq0=&types=dataverses%3Adatasets&sort=dateSort&order=desc&adjustFacetName=authorName_ss&adjustFacetNumber=10#authorName_ss`) that will scroll the page down to that specific facet category.

**Comment by landreev** [comment] 2019-09-25 18:08
> an ajax call that doesn't need the view around? (redo search and just return the facets?)
This solution would require taking the method out of SearchIncludeFragment, correct? (I may be missing something about the nature of the solution proposed...)

**Comment by landreev** [comment] 2019-09-25 18:10
Re: anchors - that I'm happy to add. There's still going to be a bit of a blink of the page reloading, but it'll get them to the right place on the page.

**Comment by scolapasta** [comment] 2019-09-25 18:44
> > an ajax call that doesn't need the view around? (redo search and just return the facets?)
> > This solution would require taking the method out of SearchIncludeFragment, correct? (I may be missing something about the nature of the solution proposed...)

Probably. I could imagine it still creating a new SearchIncludeFragment for all the search init logic and passing the parameters for the facet and "page" of the facets.

**Comment by landreev** [comment] 2019-09-25 18:58
Generating all the lists upfront and hiding/showing with javascript may be the best long-term solution, imo. (maybe? not 100% sure how straightforward/complicated that javascript is going to be, off the top of my head...)

**Comment by landreev** [comment] 2019-09-30 15:13
The version checked in now has restored the functionality of the UI to how it was before (dynamic). It was achieved by some rearrangements of objects on the inside, between the request- and view-scoped beans; and at the expense of sacrificing *a reasonable amount* of the earlier memory allocation gains.
The graph below illustrates the difference between the "broken" and "fixed" memory allocation/GC picture:
![comparison](https://user-images.githubusercontent.com/737558/65891521-ac6b4980-e372-11e9-8235-6a4386f21070.png)

This is the standard sample data test (from the "memory benchmark" branch); this is to say that the picture will be a bit different (worse) in production, where we have more facet strings. But the basic idea should be the same - the heap grows slightly faster, resulting in more full GCs - but it's still way better than before, as illustrated by the next picture - the comparison between the current version, and the version with all the backing beans ViewScoped: 
![comparison-3](https://user-images.githubusercontent.com/737558/65891717-0409b500-e373-11e9-8158-c19b256cdd29.png)

it's visibly much better, with roughly 3x fewer GCs. 
(drawing an imaginary line through the lower peaks of each red saw tooth - the mark around 3.5K GETs, where it stops climbing up, is where the 10 min. session expiration mark kicks.

**Closed** 2019-09-30 17:28 UTC
Labels: Feature: Search/Browse, Type: Bug
