### ISSUE TITLE
Version number display

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#3706] opened 2017-03-17 14:55 UTC
The display of the version number on the dataset page appears to be random in terms of placement and styling. It is inconsistent with the display of the version number on the file page (which is not necessarily an ideal model to be followed).

<img width="1222" alt="screen shot 2017-03-17 at 10 46 20 am" src="https://cloud.githubusercontent.com/assets/15386424/24048655/eff5a540-0aff-11e7-8564-e2161122b164.png">
<img width="1196" alt="screen shot 2017-03-17 at 10 44 28 am" src="https://cloud.githubusercontent.com/assets/15386424/24048656/effbb7aa-0aff-11e7-818f-7897f044c872.png">

**Comment by mheppler** [comment] 2017-03-17 15:12
Related to/duplicate of: View Dataset Versions Button does not appear on Page Load #2782

**Comment by TaniaSchlatter** [comment] 2017-04-11 20:57
Solution to present the Version number in a consistent location as a label following the Dataset/datafile title as designed for https://github.com/IQSS/dataverse/issues/3747:
![compute_dataset_round3_top](https://cloud.githubusercontent.com/assets/15386424/24930587/03299e78-1ed8-11e7-85ab-9c295d46cea0.jpg)

**Comment by mheppler** [comment] 2017-05-02 19:11
The new version label next to the dataset and file titles has been delivered as part of the UI clean up in this issue, **OpenStack Integration - Compute Buttons #3747**.

The code can be found on the `2909-3747-swift-compute-button` branch at:

https://github.com/IQSS/dataverse/commits/2909-3747-swift-compute-button

**Comment by kcondon** [comment] 2017-05-05 20:03
This appears to be working

**Closed** 2017-05-17 22:55 UTC
Labels: Component: Publishing & Versions, Component: UX & UI
