### ISSUE TITLE
Edit Dataset Metadata Fields: Clicking on the plus button breaks the page 

### ISSUE THREAD

**Issue by esotiri** [IQSS/dataverse#1317] opened 2015-01-12 19:55 UTC
Trying to add author  or using + on any of the compound or simple fields break the page, save/cancel do not work. 
There is no error on the log

**Comment by sekmiller** [comment] 2015-01-28 20:27
Doesn't seem to be happening - or I need more detailed steps to recreate

**Comment by kcondon** [comment] 2015-01-29 20:26
was not able to reproduce, closing

**Closed by kcondon** 2015-01-29 20:26 UTC
Labels: Priority: High, Status: QA, Type: Bug
