### ISSUE TITLE
File Upload Performance: Batch uploading larger image files in numbers causes browser instability/freezing, due to PrimeFaces image processing.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2482] opened 2015-08-27 18:34 UTC
Reported by a user, see RT 226297

User had created 10 datasets and uploaded 215 files, mostly PDFs and images, ranging in size from 10MB to 280MB.

They experienced their UI freezing and we received a server critical warning but it recovered. 

We recommended for now that they upload fewer files at one time as a temporary workaround.

**Comment by bencomp** [comment] 2016-01-06 09:03
Related to but not the same as #2491?

**Comment by pdurbin** [comment] 2016-01-06 15:24
@pameyer and I will be working support for uploading largish files (up to maybe 60 GB?) as part of https://hms.harvard.edu/news/dropbox-structural-biologists and I'll try to remember to report back here on any findings. It sounds like the problem reported here has more to do with many large files at once.

**Comment by kcondon** [comment] 2016-04-12 16:09
Will retest.

**Comment by kcondon** [comment] 2016-04-12 22:47
3 tickets are related: all zip uploads of larger files, large # of files resulting in server sluggishness, UI progress bar hang, and ultimate failure to upload. Each is slightly different but combining them here since it is the same functional area.

This ticket, 2482 is about large PDF uploads and may be mitigated by the jvm pdf size option:
        <jvm-options>-Ddataverse.dataAccess.thumbnail.pdf.limit=300000</jvm-options>

The other two tickets I am closing to consolidate here but you should reference them for details:
 File Upload: Uploading a relatively large number of larger files results in inability to save, need to start over. #2491 
 File Upload: Uploading larger zip files never complete, no feedback to user. #2643

**Comment by bencomp** [comment] 2016-04-13 07:54
Just out of interest, what is the reasoning for using a JVM option vs a database setting?

**Comment by kcondon** [comment] 2016-04-15 22:54
JVM options were mostly about configuring the run time but we had used them to store params. We've since moved to putting many application level settings in the db but still have a few legacy settings that we haven't moved.

**Comment by kcondon** [comment] 2016-05-12 19:27
Sonia reported a problem uploading 41 pdfs of around 40K in size. These were small enough to be below the threshold. She was working through a batch of 1000 files but saving them in smaller batches to individual datasets. Eventually resulted in server issue not being able to upload files at all.

**Comment by djbrooke** [comment] 2016-11-15 21:07
Per @landreev, we should retest this when we test the fixes for #3116.

**Comment by landreev** [comment] 2016-11-30 16:09
To summarize: 
I originally missed the "pdf" part in the description of the scenario in question. 
We now know that there was indeed a performance issue very specific to pdf files. This was addressed in the latest fixes committed to the main upload branch (#3116). 
Re-testing the scenario described here (a bunch of "small enough" pdf files), there should be a *noticeable* difference between "before" and "after", i.e., testing with and without these latest code changes.

**Comment by kcondon** [comment] 2016-11-30 21:39
OK, confirmed that large numbers  (100) of larger pdfs, 1-10MB, can be dragged and dropped and does not freeze client or server. The pdf part of the stability issue appears fixed.

We did discover that large numbers (70) of larger images, 1-10MB, does freeze the browser and local client, though it did not seem to make the server unstable in initial tests. We think the client issues are due to the PrimeFaces file upload control automatically generating its own image thumbnails, because pdfs of roughly the same size and number do not show this issue and also do not generate PrimeFaces thumbnail images.

So, for purposes of further investigation this ticket is now about image files causing client instability. There may be unidentified cases that still cause server instability (eg. large number of large tabular files that undergo ingest) but those should be opened as separate tickets as needed.

**Comment by landreev** [comment] 2016-12-01 21:10
@kcondon: (and anybody else interested)
OK, to confirm: Yes, the issue with the browser freezing on large image (non-pdf) uploads IS actually due to the PrimeFaces own image processing. That was a great catch, thank you! For everybody else who may be interested: This is yet another upload-related problem. Unlike everything else addressed so far (as part of #3116), this has got nothing to do with what WE are doing with the uploaded files. Because this is something the PrimeFaces upload component is doing before the files get to us. They are trying to generate their own thumbnail images for their progress display; they are doing it *still on the client side*, i.e. in the user's browser, with javascript. It is super expensive, it is not needed, and there is no *clean* way to disable this and/or set a size limit. 

As an experiment, I have actually found a way to disable their thumbnails. The build currently on vm5 is "primefaces thumbnail-free". (make sure to reload your upload page if you want to try it; to make sure your browser isn't caching any code). It definitely makes a difference, for a use case like that archeological archive that Sonia has been uploading. 

Unfortunately, it's not pretty at all, the way I did it. I confirmed that there was no programmatic way to turn this functionality off. So I just went inside the PrimeFaces jar file we are using, edited their javascript code and removed their image processing code by hand. 

I'm not suggesting we use this hack in the release (even though it's a little tempting). But I spoke to Gustavo, and we did some brief research, and it appears like it may be possible to do this in a cleaner fashion; by overrwriting/extending their javascript functions in our own code. 
So let's keep this ticket open for tracking this particular issue. And maybe we will be able to address it for 4.6, depending on how much time we have.

**Comment by landreev** [comment] 2016-12-01 21:14
I edited the title, to specifically reflect this one remaining issue. 
Since the performance issues with pdf files have been addressed in 3116.

**Comment by cmbz** [comment] 2024-08-20 15:26
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Closed by cmbz** 2024-08-20 15:26 UTC
Labels: Feature: File Upload & Handling, Type: Bug, Feature: Performance & Stability, User Role: Depositor

**Comment by sbarbosadataverse** [comment] 2024-09-11 19:57
@cmbz Julian and I still have concerns about this happening with the new SPA and would like to know the improvement is verified with the SPA process
