### ISSUE TITLE
Guestbook "name" field is prefilled to "Guest"

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3628] opened 2017-02-08 19:22 UTC
When someone who isn't logged in tries to download an unrestricted file whose dataset has a guestbook, the guestbook form's name field is "pre-filled" to "Guest".

- **Issue**: The "Name" field should not be pre-filled

https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/CVKM87:
<kbd><img width="1242" alt="311_requests_-_city_of_boston_administrative_data_dataverse" src="https://cloud.githubusercontent.com/assets/1036060/22753341/d175dbf2-ee09-11e6-86c2-f05fb6e37b02.png"></kbd>

**Comment by pdurbin** [comment] 2017-02-08 20:12
@raprasad this appears to have been a design decision. I think the code is at https://github.com/IQSS/dataverse/blob/v4.6/src/main/java/edu/harvard/iq/dataverse/GuestbookResponseServiceBean.java#L377

Let's talk about what you'd like to do with this issue. I'll assign it to both of us.

**Comment by pdurbin** [comment] 2017-02-08 20:16
At the very least the string English string "Guest" shouldn't be hard coded in Java. It should go in a bundle so that it can be translated into French or whatever. Also, this seems to be part of the guestbook functionality.

**Comment by pdurbin** [comment] 2017-02-14 21:02
@raprasad and I discussed this issue and the thought is that the word "Guest" should not be pre-filled.

**Comment by pdurbin** [comment] 2017-05-25 11:20
I just added the UI/UX label and I'm curious if @mheppler @TaniaSchlatter @dlmurphy or @jggautier have an opinion on this.

**Comment by jggautier** [comment] 2017-07-28 20:00
My hunch is that if a user creating a guestbook makes the "name" field required, that field shouldn't be pre-filled with "Guest". It's prefilled with "Guest" whether or not the "name" field is required. I'm saying this without knowing why it was designed this way in the first place.

If we want to get user feedback on this, to get a sense from users if and how much this has been an inconvenience, we could identify dataverses on Harvard Dataverse that use guestbooks most often and get their feedback.

**Comment by djbrooke** [comment] 2018-05-22 13:53
@jggautier is this still an issue following the guestbook work in recent releases?

**Comment by pdurbin** [comment] 2018-05-22 13:57
@djbrooke yes.

**Comment by jggautier** [comment] 2018-05-22 21:11
When a user who's not logged in tries to download a file in a dataset that has a guestbook, the guestbook's name field is still prefilled with "Guest."

I think what changed, when https://github.com/IQSS/dataverse/issues/4393 was completed for version 4.8.5, is the behavior for logged in users: When a user who is logged in tries to download a file that has a guestbook, the guestbook name field is filled with the user account name.

I just tested this in Harvard Dataverse, version 4.6.

**Comment by jggautier** [comment] 2019-03-04 16:02
In Harvard Dataverse, in 2019 (since this guestbook name bug was fixed in version 4.10 (https://github.com/IQSS/dataverse/issues/4696)) there have been 27,146 entries in dataverse guestbooks where the name is required. Of those, 12,051 have the word "Guest" in the name field. That's the number of downloads where the downloader left the pre-filled "Guest" instead of entering a name.

**Comment by pdurbin** [comment] 2019-03-05 17:29
@jggautier thanks for the update.

I think the fix is a one line change, replacing "Guest" with "" (empty string) here:

https://github.com/IQSS/dataverse/blob/v4.11/src/main/java/edu/harvard/iq/dataverse/GuestbookResponseServiceBean.java#L562

**Comment by mheppler** [comment] 2019-03-05 17:38
"1".

Ready for code review.

**Comment by jggautier** [comment] 2019-03-05 18:49
Does this change mean that "Guest" won't be prefilled when the guestbook doesn't require a name?

**Comment by mheppler** [comment] 2019-03-05 18:54
@jggautier Correct. See screenshot in my comment above. Not logged in (see "Log In" link in navbar), and the input for Name in the guestbook form is blank after I clicked the file "Download" btn.

**Comment by jggautier** [comment] 2019-03-05 19:47
Thanks @mheppler! We spoke and agreed that I'll talk to @sbarbosadataverse, @kcondon and some folks who use the guestbook reports a lot (like the admin of JPAL's dataverse who posted [a guestbook question in Google Groups](https://groups.google.com/forum/#!topic/dataverse-community/oFErNwAZtFs)) to see if there are any drawbacks to this change.

**Comment by jggautier** [comment] 2019-03-18 15:01
I spoke with the JPAL dataverse admin and others on the team. This change won't affect how the JPAL admin uses guestbooks, and there don't seem to be any drawbacks. I'm cool with moving this PR along. Thanks!

**Closed** 2019-03-18 20:06 UTC
Labels: Feature: Guestbook, Status: QA
