### ISSUE TITLE
Add S3 tests to the regular integration test suite

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#6783] opened 2020-04-01 13:56 UTC
We rely heavily on S3 storage, including in our production use, but there are no regularly-run integration tests for the functionality.
We do already have a RestAssured test class (test/java/edu/harvard/iq/dataverse/api/S3AccessIT.java) with one test, written by @bsilverstein (hi!). We are not regularly running it on jenkins.dataverse.org. 
S3 needs to be configured on the test bed installation for the test to work. But since our new jenkins infrastructure already depends on utilizing AWS, this is not an issue. We would just need to modify our scripts to copy the AWS credentials to the target EC2 instance and configure an S3 file store there. 

So I propose we do that; plus extend the S3 test class above, for some more extensive testing and to test the functionality that's been added since it was written. (for example, as it is now, the test relies on having S3  configured as the default storage driver. We can instead make it create a new dataverse, set S3 as the storage for that specific dataverse, using the new multistore functionality, and proceed testing it)

S3 testing was specifically requested in #5068. But I'm opening a dedicated issue for it since there were other things being discussed there.

**Comment by djbrooke** [comment] 2020-04-01 13:58
Thanks @landreev - I'm very interested in us working on this. 

@scolapasta I added this to the board in "Needs discussion before ready" feel free to discuss briefly in a tech hour, add an estimate, and move to ready.

**Comment by landreev** [comment] 2020-04-01 13:59
As an added bonus, we can use this to test the failure case for #6558 (validate physical files on publish): we can create an S3-stored dataset, upload a file, then mess with the file - delete it/overwrite it via the standard S3 API directly so that the md5 we have in the database is no longer valid - then attempt to publish the dataset, and watch Dataverse do its preventive magic.

**Comment by poikilotherm** [comment] 2020-04-03 08:34
This might be linked to my current efforts to come up with more integration testing.

For #6694 I'm introducing a new Maven profile und JUnit tests using testcontainers.org.
There is already an upstream module for testing against AWS: https://www.testcontainers.org/modules/localstack

You might be interested in taking a look at https://github.com/IQSS/dataverse/compare/develop...poikilotherm:6694-refactor-auth-config#diff-2487ecfd7d3cac06640e742876b1e14e for an example using a Postgres container to do an integration test for entity object marshaling/unmarshaling.

It's fast and doesn't need a full deployment.

**Comment by poikilotherm** [comment] 2020-04-03 08:35
And this might be a duplicate of #5068

**Comment by djbrooke** [comment] 2020-04-03 13:49
Thanks @poikilotherm, I'm always interested in closing out duplicate issues. 👍 I'll leave it to someone more technical than me (@landreev @scolapasta ) to check out that issue and to work with you to pull out any details.

**Comment by donsizemore** [comment] 2020-04-07 21:01
@pdurbin @poikilotherm @landreev I cobbled together a basic Ansible task to stand up an S3 LocalStack container at https://github.com/IQSS/dataverse-ansible/compare/164_localstack

Corrections, suggestions, etc. welcomed.

**Comment by cmbz** [comment] 2023-07-25 15:21
- This issue becomes a spike to analyze current state
- Follow up with a plan

**Comment by pdurbin** [comment] 2023-09-19 19:59
I just check with @poikilotherm and he recommends merging this PR of his...

- #9273

... before we pick up this issue because he has added a lot of testing goodies there such as Testcontainers that should make working on this issue easier.

**Comment by pdurbin** [comment] 2023-09-27 18:34
I just tested at PR above and Testcontainers magic seems to be working! Hopefully off to QA soon.

**Comment by pdurbin** [comment] 2023-10-16 14:16
Just a quick note that these days, thanks to all the MPCONFIG efforts by @poikilotherm it's straightforward to get S3AccessIT to pass locally on my laptop by adding the following environment variables to `docker-compose-dev.yml`:

```
       - DATAVERSE_AUTH_OIDC_AUTH_SERVER_URL=http://keycloak.mydomain.com:8090/realms/test
       - DATAVERSE_JSF_REFRESH_PERIOD=1
+      - dataverse_files_storage__driver__id=s3
+      - dataverse_files_s3_type=s3
+      - dataverse_files_s3_label=S3
+      - dataverse_files_s3_custom__endpoint__url=s3.us-east-2.amazonaws.com
+      - dataverse_files_s3_custom__endpoint__region=us-east-2
+      - dataverse_files_s3_bucket__name=pdurbin
+      - dataverse_files_s3_upload__redirect=true
+      - dataverse_files_s3_access__key=REDACTED
+      - dataverse_files_s3_secret__key=REDACTED
     ports:
       - "8080:8080" # HTTP (Dataverse Application)
```

Above I'm using the magic trick described at https://guides.dataverse.org/en/6.0/container/app-image.html#tunables

Here's a screenshot:

![Screenshot 2023-10-16 at 10 07 43 AM](https://github.com/IQSS/dataverse/assets/21006/623cf8bc-1cbc-4c08-a95b-f69ad1905c21)

As part of this effort, we should probably add first class support for these configuration options, rather than depending on the magic trick.

Finally, as discussed [in Slack](https://iqss.slack.com/archives/C010LA04BCG/p1697464284147569), in the EC2 instances spun up by Jenkins, we'd like to keep "file" as the default store but add an additional "s3" store. If it's not possible to do all the configuration already, we'll add APIs as needed. For example, we'll need to be able to configure the collection to use the S3 store. @landreev pointed out we can extend the `updateAttribute` API endpoint for collections.

**Comment by poikilotherm** [comment] 2023-10-16 14:43
Heads up that I created #9998 and #10000 for this first class Support.

**Comment by pdurbin** [comment] 2023-10-25 20:47
I create this draft PR:

- #10044

In it I switch from the magic trick above to adding JVM options, inspired by work by @ErykKul that he posted about at https://dataverse.zulipchat.com/#narrow/stream/375812-containers/topic/testing.20S3/near/397481973 (we also talked about it last week [2023-10-19, 09:30 Eastern](https://time.is/compare/0930_19_Oct_2023_in_Boston) meeting [notes](https://docs.google.com/document/d/1CT2HiulVF3DSto4GBOq6F6VcR724vyEdykY1o60I4xU/edit?usp=sharing), [recording](https://harvard.zoom.us/rec/share/sXvYnt4ojCIePOafbYCnTp4Jvmuyd3dO6I2sRSP2U-jIkSPZV3q3DSrY2iN3kYLL.AythwksVvTKN3Lmk) )

It looks like this:

```
    environment:
      DATAVERSE_DB_HOST: postgres
      DATAVERSE_DB_PASSWORD: secret
      DATAVERSE_DB_USER: ${DATAVERSE_DB_USER}
      ENABLE_JDWP: "1"
      DATAVERSE_FEATURE_API_BEARER_AUTH: "1"
      DATAVERSE_AUTH_OIDC_ENABLED: "1"
      DATAVERSE_AUTH_OIDC_CLIENT_ID: test
      DATAVERSE_AUTH_OIDC_CLIENT_SECRET: 94XHrfNRwXsjqTqApRrwWmhDLDHpIYV8
      DATAVERSE_AUTH_OIDC_AUTH_SERVER_URL: http://keycloak.mydomain.com:8090/realms/test
      DATAVERSE_JSF_REFRESH_PERIOD: "1"
      JVM_ARGS: -Ddataverse.files.storage-driver-id=file1
        -Ddataverse.files.file1.type=file
        -Ddataverse.files.file1.label=Filesystem
        -Ddataverse.files.file1.directory=${STORAGE_DIR}/store
        -Ddataverse.files.localstack1.type=s3
        -Ddataverse.files.localstack1.label=LocalStack
        -Ddataverse.files.localstack1.custom-endpoint-url=http://localstack:4566
        -Ddataverse.files.localstack1.custom-endpoint-region=us-east-2
        -Ddataverse.files.localstack1.bucket-name=mybucket
        -Ddataverse.files.localstack1.path-style-access=true
        -Ddataverse.files.localstack1.upload-redirect=false
        -Ddataverse.files.localstack1.access-key=default
        -Ddataverse.files.localstack1.secret-key=default
        -Ddataverse.files.minio1.type=s3
        -Ddataverse.files.minio1.label=MinIO
        -Ddataverse.files.minio1.custom-endpoint-url=http://minio:9000
        -Ddataverse.files.minio1.custom-endpoint-region=us-east-1
        -Ddataverse.files.minio1.bucket-name=mybucket
        -Ddataverse.files.minio1.path-style-access=true
        -Ddataverse.files.minio1.upload-redirect=false
        -Ddataverse.files.minio1.access-key=minioadmin
        -Ddataverse.files.minio1.secret-key=minioadmin
```

That is, I'm spinning up both LocalStack and MinIO now, locally on my laptop, in Docker, and then executing API tests against Dataverse configured to use these stores.

I also added a new-style integration tests for LocalStack that doesn't require Dataverse to be running. It's a lower level test.

I'm pretty sure @landreev would like us to exercise direct upload and download. We mention this here:

- https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/issues/327

So I'll probably work on that next.

Also, @donsizemore we should decide if we want to spin up LocalStack or MinIO (or both, like I'm doing right now) on the EC2 instance. My only reservation about LocalStack on EC2 so far is that attempting to pull the images from Docker Hub filled up the disk! 😬 Maybe the same would happen with MinIO. Not sure.

**Closed** 2023-12-07 15:13 UTC
Labels: Component: Containers, Size: 30
