### ISSUE TITLE
confusing wording for google/github oauth2 login button

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4333] opened 2017-12-01 01:59 UTC
For installations with multiple OAuth2 providers configured, the login button text is confusing:

<img width="549" alt="screen shot 2017-11-30 at 8 59 00 pm" src="https://user-images.githubusercontent.com/10261853/33464648-5340c76a-d611-11e7-8adc-21c536deb0f3.png">

Should be a matter of selecting the correct bundle text.

**Comment by djbrooke** [comment] 2017-12-01 02:47
Thanks @pameyer. Let's get this fix out in 4.8.4.

**Comment by pdurbin** [comment] 2017-12-01 12:44
@xibriz and I have been discussing this issue all morning at http://irclog.iq.harvard.edu/dataverse/2017-12-01 and he's coming up with a fix so I'm assigning this issue to him.

**Comment by xibriz** [comment] 2017-12-01 12:58
Have created a pull request that fixes this issue at https://github.com/IQSS/dataverse/pull/4335

**Comment by pameyer** [comment] 2017-12-01 17:01
@xibriz thanks for the pull request.  I pushed one commit to your PR that makes the text conditional : the goal as to have different text for google/github (and potentially other) OAuth providers and ORCID OAuth.

**Comment by pdurbin** [comment] 2017-12-01 18:55
I just spoke with @kcondon about this issue and it sounds like we're on the same page with regard to the problem and the fix. Two pull requests were made for this issue but #4336 is the one to test and hopefully merge. I don't know if we've started drafting release notes for 4.8.4 yet, but I'd like us to thank @xibriz for his contribution, who independently discovered this issue while hacking on #4334.

I don't think many users are affected by this issue since as far as I know, only Harvard Dataverse is using Google and GitHub authentication. A couple months or so ago, that was 71 and 23 users, respectively. These users see "ORCID" on the login button when they should see "Log In with Google" or "Log In with GitHub". This bug only affects Dataverse 4.8.3 and was introduced in 11d4f0d in an effort to make the login button for just ORCID have custom text.

**Comment by pdurbin** [comment] 2017-12-01 20:26
I used to have a server at http://shibtest.dataverse.org that I did a lot of auth testing on. That server is gone so I may spend a little time getting remote auth working in https://dev1.dataverse.org or some other server.

**Comment by kcondon** [comment] 2017-12-01 20:31
Confirmed button text is now dynamic and correct. Had some trouble verifying existing login functionality is working on my test env so will look at that.

**Comment by pdurbin** [comment] 2017-12-04 01:54
I opened "Internal Server Error when attempting to log in with Google" at #4337 on Friday because @kcondon clued me in that this was happening on one of his test servers, a issue that I assume is in production (4.8.3).

**Closed** 2017-12-05 15:41 UTC
Labels: Status: QA
