### ISSUE TITLE
DOIs for a Collection of Datasets / Dataverse

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2610] opened 2015-09-30 18:14 UTC
Placeholder for us to look into assigning a DOI at a collection or dataverse level.

**Comment by pdurbin** [comment] 2017-06-27 12:55
Is anyone out there interested in this feature? Vote to close.

**Comment by djbrooke** [comment] 2019-10-02 02:07
Duplicate of #6112

**Closed by djbrooke** 2019-10-02 02:07 UTC
Labels: Feature: Metadata, User Role: Curator, Vote to Close: pdurbin
