### ISSUE TITLE
Files Edit Tags: selecting a prefilled "tag" doesn't display the selected tag

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2391] opened 2015-07-22 16:32 UTC
When you select a tag, the dialogue box should continue to display the selection--otherwise it appears that a tag was not selected. In this case you only see successful results of a tag selection after hitting save.
In the image below I selected "1. data" but it doesn't display anywhere prior to my hitting save.

![screen shot 2015-07-22 at 12 38 40 pm](https://cloud.githubusercontent.com/assets/8322346/8831027/9a730676-306d-11e5-96f8-b9bf8c260a0e.png)

**Comment by mheppler** [comment] 2016-02-05 19:01
The SelectCheckboxMenu component shows the same UX issue in the [PrimeFace Component Showcase](http://www.primefaces.org/showcase/ui/input/checkboxMenu.xhtml). In that example, they use a "Submit" link to display the selections to the user on the page. After a quick search, I found a potential [AJAX event listener](https://github.com/primefaces/primefaces/issues/318) solution, which I was able to get working after a quick attempt at a prototype.

**Comment by mheppler** [comment] 2016-02-08 18:31
Added component for viewing Selected Tags to the Edit Tags popup form on the dataset pg. It display the tags in a section of the form labeled "Selected Tags". (See attached.)

Additional development is required to get this new custom component wired with the Custom File Tag input. That is being tracked in issue #2925 because other requirements need development for that feature.

This code was pushed to the ["2391-file-edit-tags"](https://github.com/IQSS/dataverse/commits/2391-file-edit-tags) branch.

<img width="619" alt="screen shot 2016-02-08 at 12 22 26 pm" src="https://cloud.githubusercontent.com/assets/687227/12894877/8333ff2c-ce67-11e5-857d-332d89fbe86d.png">

**Comment by mheppler** [comment] 2016-02-18 16:46
Created an [FRD](https://docs.google.com/document/d/1ihQ9GiK2qVYH_tKOJSCUdNxPdOw1Ut_AXDEIiGRjQss/edit) for this, to cover other requirements that have been identified during design/development. The new features include:
- Component for viewing Selected Tags
- "Apply" button for Custom File Tag input
- Help/info text for Custom File Tag input
- Updated help/info and removed tooltip text for Tabular Data Tags

**Comment by mheppler** [comment] 2016-02-18 17:25
The new component has been added to the Edit Tags popup on the Dataset pg. There are some requirements that will require additional backend development from @sekmiller. Passing this to him to complete those requirements. After which, we can coordinate to apply the new component to the Edit Tags popup on the Edit Files pg.

**Comment by sekmiller** [comment] 2016-03-18 18:08
Coded as designed.  Checked into Branch and Pull request

**Comment by kcondon** [comment] 2016-03-21 17:28
This is working now, tested with FF, Chrome, MSEdge. Closing.

**Closed by kcondon** 2016-03-21 17:28 UTC
Labels: Component: File Upload & Handling, Component: UX & UI, Priority: Medium, Status: QA, Type: Bug
