### ISSUE TITLE
File > Configure > Privacy Preview -- As a Data Owner, I want to create a differentially private view of my metadata so that anyone can see it

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#4233] opened 2017-10-25 02:03 UTC
We should allow Data Owners to enable differentially private access for sensitive files that currently cannot be safely shared. This can be considered done even if the researcher cannot explore the differentially private metadata. 

https://docs.google.com/presentation/d/1rPpaHNW-5QIskYvn_4afzXzU_wcdkZb2SjEDhpUhhLs/edit#slide=id.g26f2e4bd68_0_36

**Comment by mheppler** [comment] 2017-10-26 18:49
Reviewed the workflow slides with @TaniaSchlatter this morning and will be adding mockups to this issue upon finalization.

**Comment by mheppler** [comment] 2017-10-31 18:54
Here is an outline the proposed UI changes.

**UI IMPACT**

*File pg*
- Edit > Privacy Preview, when PSI has been configured, add new dropdown menu option, displayed for tabular files to those with edit access

**Comment by pdurbin** [comment] 2017-11-07 18:26
@matthew-a-dunlap please use branch `4230-4233-external-tool-psi`. I will ping you if I want to re-merge my branch for #4230 into it.

**Comment by pdurbin** [comment] 2017-11-07 20:33
@dlmurphy as we discussed I just merged `4233-PSI-data-owner` into `4230-4233-external-tool-psi`. I'll delete the former and when you are unblocked on the "TO BE ADDED" items, please use the latter.

**Comment by matthew-a-dunlap** [comment] 2017-11-09 21:06
Question about the modular dropdown: 

- Should we only show the provenance option to logged in users? 
- If there are no options in the dropdown (for example if the user is not logged in) should we hide the dropdown?

Other questions:
- Should clicking psi from the pop-up open a new tab instead of directing the current one?
- If the above is yes, I assume the warning message is then triggered on the dataverse page about refreshing?

@mheppler @TaniaSchlatter

**Comment by scolapasta** [comment] 2017-11-09 21:15
Configure options will need to be not just for logged in users, but only if you have edit dataset permission. (As the result of the configure will call apis that edit)

**Comment by mheppler** [comment] 2017-11-13 15:57
@matthew-a-dunlap Gustavo should have covered your first two button questions. Yes and yes for your "other questions". I can stop by if you'd like to talk through the workflow in more detail.

**Comment by matthew-a-dunlap** [comment] 2017-11-14 00:59
This has taken longer than expected but is 90+% done. Here are the outstanding things:

- [ ] Dataset configure dropdowns blocked by edge of file table
- [ ] Dataset configure dropdowns should use better logic to know if it has any entries
- [ ] Dataset configure dropdowns  spacing incorrect
- [ ] File page "Map" popup greys everything with modal="true" or greys nothing otherwise
- [ ] File page map/psi options show up always
- [ ] Pull in develop or phil's branch

**Comment by matthew-a-dunlap** [comment] 2017-11-14 23:13
Discussed with Mike how the file page should have its own configure dropdown instead of being part of "edit". In light of this, I was able to majorly refactor my code and address concerns I had about reuse and efficiency. There are still outstanding issues tho:

- [ ] File page PSI popup width
- [ ] Dataset PSI popup is super weird (probably due to being in an <li> in the configure dropdown).
- [ ] Dataset configure dropdowns blocked by edge of file table (Mike said he'd handle this one)
- [ ] Pull in develop or Phil's branch

Due to this change / refactor this was not completed. I plan to ask for help tomorrow.

**Comment by matthew-a-dunlap** [comment] 2017-11-16 23:12
The above checklist is up to date. I have started with the merge but have one outstanding question for Phil. 

@mheppler this branch is ready for you to do you UI fixes. The one UI thing to note is that I have implemented the alert text to be fairly generic instead of what is in the mock-up above. As we move forward we could have an entry in our modular config for the text when there is an alert, but it seemed like there maybe should be more discussion before going this route. See below for a screenshot.
![screen shot 2017-11-16 at 5 23 57 pm](https://user-images.githubusercontent.com/8901015/32921009-c26b4d4a-caf9-11e7-9219-a3604479c7e8.png)

**Comment by pdurbin** [comment] 2017-11-17 00:22
> I have started with the merge but have one outstanding question for Phil.

What's your concern, @matthew-a-dunlap ?

**Comment by mheppler** [comment] 2017-11-17 19:14
Improved style/format for message block and info popup for privacy-preserving preview on dataset pg.

Note: @dlmurphy -- I tried to revise the text that goes with PSI tool in the modular configure popup.

<img width="608" alt="screen shot 2017-11-17 at 1 29 57 pm" src="https://user-images.githubusercontent.com/687227/32964515-7e496158-cba1-11e7-92ed-002d9eadbb1f.png">

**Comment by dlmurphy** [comment] 2017-11-17 21:42
@mheppler I've further revised the text for that popup. I've made it more about what PSI is and what it allows, and I left out the info about how to use the tool, since the budgeter tool itself contains a thorough tutorial.

**Privacy-Preserving Data Preview**
Use the PSI Budgeter tool to create safe, privacy-preserving summary statistics for this data file. The tool protects data using the [differential privacy](https://privacytools.seas.harvard.edu/publications/differential-privacy-primer-non-technical-audience-preliminary-version) framework. It allows you to introduce just enough noise into your summary statistics to ensure privacy while still allowing a useful (if blurry) window into the contents of the data. Dataverse users will be able to explore a preview of your data without any danger of exposing private information.

**Comment by matthew-a-dunlap** [comment] 2017-11-17 21:57
@dlmurphy @mheppler I'll add that text change in after finishing up this big merge.

**Comment by matthew-a-dunlap** [comment] 2017-11-17 22:34
I take that back, we moved those to the psi.json that is no longer in the project! So I can't update it hah.

**Comment by matthew-a-dunlap** [comment] 2017-11-17 22:56
There is an outstanding need to add file handling to the backend code, which will be done on this branch instead of 4230.

**Comment by pdurbin** [comment] 2017-11-20 21:19
Yes, @scolapasta @matthew-a-dunlap and I discussed this issue and #4230 this morning and we decided that since the issue about the UI is close to being done, we'll have single pull request based on the branch `4230-4233-external-tool-psi` that we'll put through QA.

On that branch I've been completing the work for #4230 and I just went to take a look at the GUI for this issue. Unfortunately, as of 553d8d4 I can't create a dataset. I'm getting `javax.el.ELException: /dataset.xhtml @1188,163 rendered="#{DatasetPage.sessionUserAuthenticated and DatasetPage.canUpdateDataset()}": javax.ejb.EJBException` and `Caused by: java.lang.IllegalArgumentException: Cannot query permissions on a DvObject with a null id.` I'm attaching the full stack trace. This is the code:

                    <p:dialog header="#{configureFragmentBean.configurePopupToolHandler.externalTool.displayName}" widgetVar="configureToolPopup" modal="true" 
                            id="configureToolPopup" styleClass="smallPopUp" rendered="#{DatasetPage.sessionUserAuthenticated and DatasetPage.canUpdateDataset()}">

I was attempting to create the dataset in the root dataverse, if that matters.

[create-dataset-in-root-553d8d4.txt](https://github.com/IQSS/dataverse/files/1489167/create-dataset-in-root-553d8d4.txt)

@matthew-a-dunlap said he'd take a look.

**Comment by matthew-a-dunlap** [comment] 2017-11-21 18:43
Here is the list of code review feedback on the UI side of modular configure:

- [ ] The logic for what tools to show for a file should be moved out of the UI and instead be at creation of the list of handlers for the files. 
    * Eventually we will likely add the file to the configurations themselves. At the moment we will only have infrastructure to write back in specific cases (e.g. psi fuzzy summary statistics) so file typing is less important. A comment will be left in the code about this
- [ ] Even if the handler list is well populated, passing the full list up front does not work the UI from a lazy loading perspective
    * The one issue I (Matthew) see is that the datasetPage generates a giant list of all tools for all files on load of the page. While this is not passed to the UI it may be better to get the individual per-file lists as needed
- [ ] Make sure popup matches map logic on when to show buttons when dataverse is a widget (e.g. shown in an iframe)

**Closed** 2017-12-07 20:18 UTC
