### ISSUE TITLE
Metadata Block bugs under General information edit window

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#4026] opened 2017-07-26 21:26 UTC
Three bugs occurred during a Dataverse demo.

**1.** In PSI's dataverse, the "Citation Metadata" label was changed to "Quote Metadata":
<kbd><img width="2502" alt="screen shot 2017-07-26 at 1 02 18 pm" src="https://user-images.githubusercontent.com/8322346/28942589-ea57b178-7869-11e7-8ff2-1b1fbb358354.png"></kbd>

**2.** In PSI's dataverse, Citation Metadata gets unchecked (should never happen):
<kbd><img width="2252" alt="screen shot 2017-07-26 at 12 10 40 pm" src="https://user-images.githubusercontent.com/8322346/28644336-218dfc90-7227-11e7-9f99-038ef137e8e0.png"></kbd>

**3.** When creating a dataverse, part of my dataset screen showed up under the "general info" edit window!<-now that is crazy!
<kbd><img width="2516" alt="screen shot 2017-07-26 at 1 46 10 pm" src="https://user-images.githubusercontent.com/8322346/28644334-1b8a3dea-7227-11e7-94bb-367c220e1a0b.png"></kbd>

**Comment by jggautier** [comment] 2017-07-27 02:29
@sbarbosadataverse Looks like these are bugs just for the dataverse in the screenshots ("Sonia's geospatial data"). Is that right?

**Comment by pdurbin** [comment] 2017-07-28 01:36
DataversePage.java has an enum called `EditMode` to put the page into different states for creating a new dataverse vs. showing info for an existing dataverse, etc.:

    public enum EditMode {
        CREATE, INFO, FEATURED
}

My guess is that an error happened preventing the page's state to get set back to how it's supposed to be. Just a guess.

**Comment by sbarbosadataverse** [comment] 2017-08-03 20:36
<img width="2502" alt="screen shot 2017-07-26 at 1 02 18 pm" src="https://user-images.githubusercontent.com/8322346/28942589-ea57b178-7869-11e7-8ff2-1b1fbb358354.png">

**Comment by LauraHuisintveld** [comment] 2019-02-12 12:41
Just wanted to let you know that error number 2 from Sonia's list above is still there. A user from DataverseNL (v.4.8.6) reported this, and I also tested it at demo.dataverse.org  (v. 4.10.1).
To reproduce:
1. Go to the General information page
2. Click 'View fields' for the Citation Metadata
3. Do not change anything, and click 'Done'.

As a result, the box is unchecked. If you click 'Cancel' or 'Save changes' and reopen the General information page again, the box is checked again.
Not a big issue, but it might be at bit confusing for users.

**Comment by jggautier** [comment] 2019-02-13 16:30
Hi Laura. I can't reproduce this on the [test dataverse](https://demo.dataverse.org/dataverse/juliangautier) I use on demo.dataverse.org (tried it on Chrome, Firefox and Safari). The check box is always checked (and grayed out). Could you share the dataverse on the demo site that you're seeing this bug?

**Comment by LauraHuisintveld** [comment] 2019-02-15 07:55
Hi Julian, Yes I used this test dataverse: https://demo.dataverse.org/dataverse/laurahuis

Here is a screenshot:
![screenshot 2019-02-15 at 08 53 40](https://user-images.githubusercontent.com/34090667/52842431-645b2780-30ff-11e9-962a-7724898354d3.png)

**Comment by pdurbin** [comment] 2019-02-15 11:27
I can definitely reproduce this on the demo site, which is (still) running 4.10.1. The behavior is weird. I hope it's harmless.

While I was in there I noticed that when you click "View fields" on any metadata blocks, all of the "View fields" link disappear. So if we pick up this issue to work on we might want to take a look at this too. Here's a screenshot:

<img width="622" alt="screen shot 2019-02-15 at 6 25 36 am" src="https://user-images.githubusercontent.com/21006/52853839-c8272580-30ea-11e9-97b5-e646c1407b5f.png">

**Comment by cmbz** [comment] 2024-08-20 15:24
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Closed by cmbz** 2024-08-20 15:24 UTC
Labels: Feature: Metadata, Type: Bug, Feature: Dataverse General Info, User Role: Curator
