### ISSUE TITLE
Metadata template: Countries don't display in alpha order after selecting for template

### ISSUE THREAD

**Issue by amberleahey** [IQSS/dataverse#5291] opened 2018-11-07 21:29 UTC
Testing metadata templates it shows list of countries in alpha order upon selection, but after saving in template and attempting to reuse/edit when creating new studies the countries appear out of order (no alpha order) which makes it harder to select / identify for removal. Is this an indexing issue?

See screenshot
![image001](https://user-images.githubusercontent.com/17624834/48162080-349fb680-e2aa-11e8-912b-deb15bf38546.png)

**Comment by jggautier** [comment] 2018-11-09 20:49
Hi @amberleahey. Did you mean that you expected the order of each group of four fields to stay in the same order they were in when saving the metadata template? For example, in your screenshot, did you expect that the group of fields with China in the "County / Nation" field would appear at the top, then the group of fields with Costa Rica, then Hungary, etc?

Or did you mean that when you select the dropdowns, the full list of countries are not alpha ordered, even though they were when you were creating/edit the metadata template?

I don't know if it would be helpful to know what browser you're using? And are you seeing this bug on Scholar's Portal's 4.8.4 version?

I tested both cases in the newest version of Google Chrome on MacOS, using the Geographic Coverage fields and other fields with controlled vocabs, but I'm not able to reproduce either bug in Dataverse 4.9.4 on Harvard Dataverse or [Demo Dataverse](https://demo.dataverse.org/). (I know some vocabs are not in alpha order, like Subject and Author Identifier Scheme.)

**Comment by cmbz** [comment] 2024-08-20 15:23
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Closed by cmbz** 2024-08-20 15:23 UTC
Labels: Feature: Metadata, Type: Bug, User Role: Depositor, Component: JSF, UX & UI: New React UI
