### ISSUE TITLE
CkEditor in dataverse

### ISSUE THREAD

**Issue by youssefOuahalou** [IQSS/dataverse#6353] opened 2019-11-08 09:02 UTC
Hello everyone. Is it possible to associate Ckeditor with dataverse to replace all HTML tag tags with "textarea Ckeditor"?

**Comment by djbrooke** [comment] 2019-11-11 08:26
Hi @youssefOuahalou, thanks for adding this. Are you asking for ckeditor support in Dataverse? If so, what would be the benefit and what are some of the drawbacks?

**Comment by youssefOuahalou** [comment] 2019-11-11 22:15
Thank you for your reply. I think the html tags are not very user-friendly because there are people who do not understand how html tags work.

**Comment by djbrooke** [comment] 2019-11-11 23:36
I think we'd want to not implement this because, while an external editor could provide a more user-friendly editing experience through the front end, I'd be concerned about unexpected characters or other content having an effect on interoperability with other systems. I think simpler is better in this case. 

@jggautier do you have any thoughts on this?

**Comment by jggautier** [comment] 2019-11-12 17:13
I would wonder that, too: Would the editor make it easier for people to add unexpected characters? 
I think I read that it's able to sanitize anything that's copied and pasted into metadata fields, which sounds like more of a benefit if it can prevent unexpected characters instead.

Also, I think @scolapasta said Dataverse does a better job now of preventing these characters, like different types of line breaks, from getting into the database (and into the metadata exports), and the cases I know of where weird characters in the database have caused problems have been from older datasets.

It looks like you can customize this editor to add and remove buttons, too, so functions that aren't in the current white list of HTML tags, like indenting, can be removed from the editor.

And it looks like you can add a "view source" button for people who still want to type HTML tags, copy and paste source code, or check how the editor has converted what they've copied from another editor like Word or a PDF.

**Comment by djbrooke** [comment] 2019-11-20 15:33
Going to close as this is very closely related to and/or is a duplicate of #6383.

**Closed by djbrooke** 2019-11-20 15:33 UTC
