### ISSUE TITLE
metadata xml error, & and message users see

### ISSUE THREAD

**Issue by jmjamison** [IQSS/dataverse#7611] opened 2021-02-12 23:21 UTC
This may relate to:   https://github.com/IQSS/dataverse/issues/3328

When creating a dataset one of our researchers included an ampersand '&' in his description of the dataset, when he tried to publish failed with this message:
" Simulation results of ...  could not be published due to a failure to register, or update the Global Identifier for the dataset or one of the files in it. Contact support if this continues to happen."

When I poked into the system.log I found:
Call to globalIdServiceBean.createIdentifier failed: edu.ucsb.nceas.ezid.EZIDException: bad request - datacite: metadata validation error: XML parse error: xmlParseEntityRef: no name, line 15, column 161 (line 15)|#]

Fixed the error, explained situation to the user.  I'm going to add this to our documentation but I'm wondering if it is at all possible to have a more informative message.

**Comment by djbrooke** [comment] 2021-02-16 14:26
Hey @jmjamison - I think this is a duplicate of #3328. We spent some time working on it a little while ago and we thought we had a fix, but it wasn't sufficient. I'll close this and we'll take another look at #3328 when we can.

**Closed by djbrooke** 2021-02-16 14:26 UTC
