### ISSUE TITLE
Update Metrics Aggregator with New Metrics

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#5492] opened 2019-01-28 22:03 UTC
The Metrics Aggregator (https://github.com/IQSS/metrics.dataverse.org) needs to be updated to account for changes in PR #5475. This includes the new parameter:

- dataLocation (harvested vs nonharvested) for datasets and files

**Comment by djbrooke** [comment] 2019-01-28 22:12
The Metrics Aggregator (https://github.com/IQSS/metrics.dataverse.org) needs to be updated to account for changes in PR #5475.

**Comment by matthew-a-dunlap** [comment] 2019-02-06 20:17
I've run into an issue with the new `dataLocation` metrics and integrating with metrics.dataverse.org. The `dataLocation` is specified by a query parameter and operates without issue. The problem is that if a query parameter is not recognized by the API endpoint, it is silently discarded and the metric without the parameter is returned (in this case the count of local datasets/files).

This means that installations that have not upgraded will return the local results when we expect them to return remote or local+remote.

I think the best solution is to update https://github.com/IQSS/dataverse/issues/5445 to have the API endpoints error when an unrecognized api endpoint is passed. With that code in place we'll need to wait for all installations to upgrade to that version of the system before adding the remote metrics to this code.

Thoughts @pdurbin @scolapasta @djbrooke ?

**Comment by djbrooke** [comment] 2019-02-06 20:47
@matthew-a-dunlap thanks for tagging me in. Sorry if I'm missing something, but I think we only want the metrics aggregator to get the local counts from installations. In the situation that you describe, if the aggregator hits an installation that has metrics endpoints that are not updated, it's fine (from my perspective) if it "fails" and returns local counts. If it hits one that's updated, it should only be querying for the local counts. If we start to query and try to count remote results we'll get a bunch of double (and triple, and quadruple) counts since the installations harvest from each other.  

There may be questions about the best technical implementation and how this can be scaled appropriately across our very distributed community, but I don't think there's necessarily anything happening here that is undesirable from my perspective. If we need to re-discuss or re-scope this issue, that's fine.

**Comment by matthew-a-dunlap** [comment] 2019-02-06 20:51
@djbrooke Ah ok, then I think there may be no work needed for this story. The current implementation returns local when no dataLocation queryParam is passed.

I think #5445 should still error when unexpected query params are passed, as it'll make the results returned not confusing to folks working across Dataverse versions.

**Comment by djbrooke** [comment] 2019-02-06 20:57
@matthew-a-dunlap thanks, yeah - the work in #5445 sounds like a good use of time. We'll continue to have Dataverse installations that have varied upgrade schedules, so better error reporting and fewer silent failures will be helpful.

**Comment by matthew-a-dunlap** [comment] 2019-02-06 23:13
I'm closing this issue as we currently don't want to track the new metrics added by the homepage work.

**Closed by matthew-a-dunlap** 2019-02-06 23:13 UTC
Labels: Status: Development
