### ISSUE TITLE
Metadata field values in dataset draft are deleted after pressing ENTER

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse#8948] opened 2022-08-31 11:32 UTC
**What steps does it take to reproduce the issue?**
- Go to a Dataverse installation of v. 5.6.
- Log in, and click on Add Data > Add Dataset.
- Enter a fake title into the metadata field Title.
- (Enter any other values in other metadata fields.)
- Put the cursor in to an empty metadata field, e.g., Title, Author - Name, Author - Identifier, Description Date, and press ENTER.

**When does this issue occur?**
See below.

**Which page(s) does it occurs on?**
The metadata record creation page, e.g., https://demo.dataverse.org/dataset.xhtml?ownerId=<id>

**What happens?**
The previously filled in values are deleted from the dataset draft.

**To whom does it occur (all users, curators, superusers)?**
All users

**What did you expect to happen?**
Not sure, but probably 1) the dataset draft to be saved; or 2) the cursor moving to the next metadata field; or 3) an message appearing prompting me to use Tab or mouse click instead of Enter.

**Which version of Dataverse are you using?**
5.6

**Any related open or closed issues to this bug report?**
https://github.com/IQSS/dataverse/issues/8820

**Other relevant information?**
- Using Using Chrome (104.0.5112.102; 64-bit) and Firefox (91.13.0esr; 64-bit)
- The issue could not be reproduced on demo.dataverse.org (v. 5.11.1).

**Comment by pdurbin** [comment] 2022-09-07 10:46
@philippconzett thanks for the bug report. I'm very glad to hear you can't reproduce this on the demo server running the latest (5.11.1).

Are you ok with closing this issue? Is there something else you had in mind? Maybe an update to the 5.6 release notes?

**Comment by philippconzett** [comment] 2022-09-07 15:50
Thanks, @pdurbin  So, you mean this bug was fixed somewhere between 5.6 and 5.11.1? In that case, I think it's safe to close the issue.

**Comment by pdurbin** [comment] 2022-09-07 15:53
@philippconzett I'm not aware of a specific pull request that fixed this. Maybe a PrimeFaces upgrade?

**Comment by pdurbin** [comment] 2022-09-07 17:23
I just found "the form is reset and any fields that have been filled in previously are cleared" at #7895 so I think this was fixed in 5.10.1 with PR #8500 by @ErykKul . Not sure.

**Comment by pdurbin** [comment] 2022-10-01 18:16
> I think it's safe to close the issue.

Closing!

**Closed by pdurbin** 2022-10-01 18:16 UTC
