### ISSUE TITLE
Dataset page: files are listed in random order -> Sort them!

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2014] opened 2015-04-14 21:33 UTC
Please sort files by filename.  It is confusing to upload meaningfully named files and see them randomly listed.

**Comment by posixeleni** [comment] 2015-04-14 21:34
Would be really nice to sort them by the "Category" tag as well

**Comment by mcrosas** [comment] 2015-04-14 21:39
yes, we need for some datasets as soon as possible a way to sort or filter them by category - we could, for example, display the categories as "tags" at the top of the page (if the dataset has any tags), and when you click in a "tag", it filters the files for that category. This is needed son to bring functionality we had in 3.6 that a few dataverses are heavily relying on.

**Comment by scolapasta** [comment] 2015-04-14 21:46
We need sorting for sure for the patch to help resolve some other issues we're seeing.

And we need to decide if filtering by categories needs to be done now or can wait for 4.0.1.

**Comment by pdurbin** [comment] 2015-04-14 23:30
This seems to be a duplicate of #1836

**Comment by raprasad** [comment] 2015-04-15 10:00
@scolapasta @landreev 
Didn't see this was assigned.  Checked in an annotation update to sort by category and label

**Comment by scolapasta** [comment] 2015-04-15 20:49
Files now sorted by label (filename).

Passing this issue to QA; will open new issue for @mcrosas ideas.

**Comment by scolapasta** [comment] 2015-04-15 21:02
New issue is #2021

**Comment by kcondon** [comment] 2015-04-15 21:49
Sorting works but noticed it treats files beginning with capital letters differently so files with caps always appears before lowercase files.

So, M51 appears before collier. Otherwise appears to work fine. Gustavo asked that I pass to @eaquigley for comment on above behavior.

**Comment by eaquigley** [comment] 2015-04-16 20:09
Personally, I think lowercase and uppercase should be treated the same so M51 should not be appearing before collier.

**Comment by mheppler** [comment] 2015-04-16 20:13
Where do numbers-first fall then?

Order these files:

M51, michael75, m2000, 22mheppler


On Thu, Apr 16, 2015 at 4:09 PM, Elizabeth Quigley <notifications@github.com

**Comment by eaquigley** [comment] 2015-04-16 20:14
22mheppler
m2000
M51
michael75

This is a fun quiz!

**Comment by scolapasta** [comment] 2015-04-16 20:17
That's weasy, the challenge is aways:
1a
10a
2a

**Comment by kcondon** [comment] 2015-04-16 20:58
Right, numbers always come before letters but 10 comes before 2 in sorting but in human readable terms it doesn't. Capital and small letters are sorted differently but in human terms they are the same.

________________________________

**Comment by scolapasta** [comment] 2015-04-16 21:00
Right. For 4.0 we are handling the upper case lower case aspect.

#s will sort alphabetically.

**Comment by kcondon** [comment] 2015-04-16 21:21
I'm tired of this ticket, closing.

**Closed by kcondon** 2015-04-16 21:21 UTC
Labels: Component: UX & Upgrade, Priority: High, Status: QA, Type: Bug

**Comment by kcondon** [comment] 2015-04-16 21:25
OK order is fine.

**Comment by pdurbin** [comment] 2017-06-30 19:24
> yes, we need for some datasets as soon as possible a way to sort or filter them by category - we could, for example, display the categories as "tags" at the top of the page (if the dataset has any tags), and when you click in a "tag", it filters the files for that category. This is needed son to bring functionality we had in 3.6 that a few dataverses are heavily relying on.

@dliburd does this comment by @mercecrosas capture what you were showing me yesterday? Either, way, can you please open a new GitHub issue and include a screenshot? Thanks!
