### ISSUE TITLE
Edit Dataverse Page: Fails to reset metadata fields to inherit from parent

### ISSUE THREAD

**Issue by ferrys** [IQSS/dataverse#4474] opened 2018-02-26 17:06 UTC
Following the workflow:
1. Create a new Dataverse. Uncheck the box "Use metadata fields from ___". Save Dataverse.
2. Edit --> General Information. Check the box "Use metadata fields from ___".  Attempt to save Dataverse.
3. Edit button is not responsive until refresh & the metadata fields do not actually update. You can alter the other checkboxes to add/remove other metadata fields but never go back to the metadata fields from the parent.

I tested this on the Demo Dataverse v. 4.8.4 build 128-ef7dce7.

**Comment by LauraHuisintveld** [comment] 2018-08-13 07:27
This bug has also been reported by one of our users. (DataverseNL) I tested it as well on demo.dataverse.org and I found that the bug is still there in version 4.9.1.

**Comment by LauraHuisintveld** [comment] 2019-01-08 15:39
I was checking the release notes for version 4.10, and I was wondering if this is a duplicate issue of #3427 ? We did not upgrade yet, so I cannot test it myself in version 4.10.

**Comment by pdurbin** [comment] 2019-01-08 15:50
@LauraHuisintveld it sure looks like a duplicate. https://demo.dataverse.org is running Dataverse 4.9.4 right now but I'll try to remember to let you know when it has been upgraded to 4.10 or higher so you can re-test.

**Comment by mheppler** [comment] 2019-01-08 16:18
I have checked this on the latest and greatest `develop` branch and can confirm the bug outlined in this has been fixed.

That said, as @kcondon pointed out in his last comment before #3427 was closed and merged, clicking "Continue" on the popup saves the action and moves you to the dataset pg with a success msg. That should be fixed, so that clicking continue brings you back to the Edit Dataverse General Information form.

I suggest we leave this issue open in order to resolve that last issue, or we close this and open a new issue.

**Comment by mheppler** [comment] 2019-01-08 17:32
I have opened a new issue, _Metadata Fields > Edit Dataverse General Information - Various bugs and other UX unpleasantries #5441_, to report the popup "Continue"/saving issue, as well as consolidate any other know UX issues with this Metadata Fields form component.

@LauraHuisintveld @pdurbin I am going to close this issue as a duplicate of #3427. Please comment on the new issue if you have any more feedback about specific issues you are experiencing, or would like to track these issues getting fixed in an upcoming release.

**Closed by mheppler** 2019-01-08 17:32 UTC
Labels: Feature: Dataverse General Info, Help Wanted: Code, Mentor: pdurbin, Type: Bug
