### ISSUE TITLE
Metadata + Terms - Support Markdown syntax

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#4647] opened 2018-05-04 12:55 UTC
I thought we had an old issue requesting this, but I could not find it. Seeing this comment from @pdurbin on #4645 caused me to shudder a little bit.

> As you observed (and as I think I said wrong in my reply on the forum), you can retrieve "Terms of Use" via API like this (truncated example reformatted a bit):
> 
> `curl -s 'https://dataverse.harvard.edu/api/datasets/:persistentId?persistentId=hdl:1902.1/00875' | jq '.data.latestVersion.termsOfUse' | cut -c-300`
> 
> `"<div style=\"padding-left: 30px;\"> <ul style=\"list-style-type: decimal;\" ><li> The Murray Archive (the Distributor) has granted me a revocable license to use this dataset solely for the purposes of conducting research, and the Distributor may terminate this license at any time and for any reason`...

The API returns the dataset Terms of Use, which includes HTML formatting to improve the layout in the UI. However that HTML does not improve the UX in the API.

In order to get the best of both worlds, we need to support Markdown, a lightweight markup language with plain text formatting syntax. This is what GitHub supports right here in the comment input, and it will make it easier for contributors to add text for metadata and terms that look great in the UI and API.

**Comment by pameyer** [comment] 2018-05-04 13:58
@mheppler any thoughts on Dataverse recognizing markdown as a filetype in datasets?

**Comment by pdurbin** [comment] 2018-05-04 13:58
@mheppler it's been over three years since I made the argument for supporting Markdown in https://github.com/IQSS/dataverse/issues/1320#issuecomment-70260091 so I'm not surprised the conversation wasn't top of mind for you, but I still very much think we should support Markdown. Of course, to my knowledge no one in the community has asked for Markdown support. Comments on this issue are welcome to indicate interest.

**Comment by djbrooke** [comment] 2019-11-20 15:29
Closing as duplicate of #6383

**Closed by djbrooke** 2019-11-20 15:29 UTC
Labels: Feature: Metadata, Feature: Terms & Licensing
