### ISSUE TITLE
schema.org representation of license is incorrect

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse#7574] opened 2021-02-02 16:00 UTC
Our repository (DataverseNO) has recently been FAIR-evaluated by the Scandinavian node of EOSC, EOSC-Nordic ([https://www.eosc-nordic.eu/](https://www.eosc-nordic.eu/)). Among other things, we got the following feedback:

> There seems to be an issue with how the license metadata is presented in Schema.org format. We got the following warning from our evaluation tool: "INFO  License metadata found (schema.org) - {'@type': 'Dataset', 'text': 'CC0', 'url': 'https://creativecommons.org/publicdomain/zero/1.0/'}
> WARNING  Looks like schema.org representation of license is incorrect, skipping the test."
>

**Comment by jggautier** [comment] 2021-02-04 19:46
Thanks @philippconzett. This sounds related to the changes to the Schema.org export proposed in https://github.com/IQSS/dataverse/issues/7349.

Would you know if EOSC-Nordic's FAIR evaluation tool is expecting the license metadata in the way that's proposed in https://github.com/IQSS/dataverse/issues/7349, did they provide more info about what their tool expects, or could we contact them (or ask them to hop on this GitHub issue)? I see their report at https://doi.org/10.5281/zenodo.4045401, which might have these kinds of details, but it's a hefty 42 pages. Haven't had the time to dig in.

**Comment by adam3smith** [comment] 2022-10-12 16:07
I think this is actually a duplicate of #7349 and should be closed as such, unless you want to split that ticket into sub-issues.

**Comment by qqmyers** [comment] 2022-10-18 15:54
This was improved / perhaps resolved in #7920 - when multiple licenses were introduced we switched to using the 'license':'https://creativecommons.org/publicdomain/zero/1.0/' form (just URL, not a json object) which is allowed by Google.

**Comment by pdurbin** [comment] 2022-10-21 22:05
@qqmyers great!

@philippconzett what do you think? Better? Need anything else?

**Closed** 2023-01-05 11:29 UTC
Labels: Feature: Metadata, Type: Bug, Status: Still Interested?, User Role: Curator
