### ISSUE TITLE
Documentation: Update api examples that use json input files to also specify file type json or won't work.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#8862] opened 2022-07-26 21:28 UTC
Somewhere along the way some of the command line examples that upload json files as input dropped the file type and that won't work. So, need to review which ones need updating and make them consistent to specify file type, otherwise people copy and paste this from prior entries.

**Comment by pdurbin** [comment] 2023-11-11 03:07
Closing as a duplicate of this issue:

- #6645

**Closed by pdurbin** 2023-11-11 03:07 UTC
