### ISSUE TITLE
Navigation: clicking on dataverse links in breadcrumb, dataset card not working.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4030] opened 2017-07-28 19:41 UTC
Found on develop branch, not in prod.

Saw three examples of links to dataverses not working:
1. click on dv link on dv card results in dataverse page showing no content.
2. click on dv portion of breadcrumb while on dataset page, shows dv page no content.
3. click on dv link on dataset card, just refreshes homepage.

Update, 3 always happens but 1,2 happens for one dv on both build and internal but not on other dv's. The dv is: kc072817

**Comment by mheppler** [comment] 2017-08-17 17:39
Since there was a similar problem for dataverse links across various pages, I sought out as many links to dataverse as I could find, to make sure that we were all properly linking to dataverses. Most links don't properly use `/dataverse.xhtml?alias=#{page.dataverseAlias}` but instead use `/dataverse/#{page.dataverseAlias}`. I have fixed all these links that so they are all consistent, and we should no longer see inconsistent behavior when navigating around the site. Also confirmed the newly formatted links work for widgets.

*Header*
- search button
- dataverse theme logo
- breadcrumbs

*Dataverse*
- feature dataverse carousel
- dataverse card
- dataset card

*Account*
- notifications

*Manage Harvest Clients*
- harvest client dataverse

**Comment by pdurbin** [comment] 2017-08-18 00:54
Pull request #4086 looks good and I moved it into QA.

**Comment by mheppler** [comment] 2017-08-18 16:48
![screen shot 2017-08-18 at 12 46 22 pm](https://user-images.githubusercontent.com/687227/29468752-8352de70-8413-11e7-960f-beb411563a1c.png)

I found a layout that I wanted to get fixed ASAP, and put it into this branch. There was a misplaced style class in the stylesheet that was causing action buttons on the bottom of the page to be aligned right, as opposed to left. This was fixed by moving the offending style class to another line in the stylesheet.

![screen shot 2017-08-18 at 12 48 28 pm](https://user-images.githubusercontent.com/687227/29468761-8f9c7f38-8413-11e7-9574-2baa0694eebc.png)

**Closed** 2017-08-23 22:07 UTC
Labels: Type: Bug
