### ISSUE TITLE
Support Open Badges for Dataverses 

### ISSUE THREAD

**Issue by mercecrosas** [IQSS/dataverse#2119] opened 2015-04-29 21:34 UTC
We should consider supporting  OpenBadges as an option for Dataverses (and possibly datasets):

http://openbadges.org/

Also, from OSF, support Open Data badges

**Comment by bencomp** [comment] 2015-05-01 08:29
Great idea! I had found the OSF [Open Data Badges](https://osf.io/tvyxz/wiki/home/) recently. 

IMHO "support Open Badges" needs to be more specific :) Would you like to import and display badges with personal names, datasets/dataverses, if some other organisation awarded the badges? Or should Dataverse reward users a badge automatically? Or should a dataverse "badge manager" be able to manually reward people creating high-quality datasets after a check?

**Comment by pdurbin** [comment] 2015-05-01 12:12
> reward people creating high-quality datasets

This reminds me of an idea I shopped around internally a while back:

Subject: the "quality" of a dataverse (good practices)

We all just discussed good practices for data curation and it reminded me of a "quality" metric used by the Perl community.

Except they spell it "kwalitee" because they don't want to hurt anyone's feelings...

For example, it's considered a good practice to write tests, so they check for that:

http://cpants.cpanauthors.org/kwalitee/has_tests

And you can see year over year how the authors are doing on this metric... generally, the trend is better... Perl authors are writing more tests.

Maybe the admins of a dataverse could see a report like this for the good practices we are trying to promote*. And the admins could nudge the authors a bit to improve. So that the numbers look better year over year.

Phil

\* i.e. http://www.force11.org/AmsterdamManifesto

**Comment by mcrosas** [comment] 2015-05-01 13:58
@bencomp I agree, I wasn't specific about what supporting badges mean in part because it needs brainstorming and good understanding of how the badges are used in other contexts. We'll need to do some research associated to this. Assigning to @posixeleni

**Comment by posixeleni** [comment] 2015-05-01 14:01
@bencomp i imagine we may want to offer both automated and manual options for badge assigning depending on the type of badge. But as @mcrosas mentions we will need to research this a bit further.

Some preliminary thoughts:
Example for an OSF **Open Data Badge** there are two sets of criteria that need to be met:

**1. Provide the URL, doi, or other permanent path for accessing the data in a public, open access repository** 
[This can be set automatically by Dataverse when the dataset is published and unrestricted]

**2. Is there sufficient information for an independent researcher to reproduce the reported results? If no, explain.**
[Would most likely need a human aka Dataverse Admin (i.e. journal editor) to vet this information before granting the badge.]

**Comment by eaquigley** [comment] 2015-05-04 21:23
Another thought of a way to do a badge would be to have an online course (like with Coursera) on how to use Dataverse. If a user completes it, their dataverse and/or datasets would have a badge signifying this. 

Inspired by seeing this course on Coursera: https://www.coursera.org/course/datascitoolbox

**Comment by pdurbin** [comment] 2016-10-16 01:55
#924 is related.

**Comment by jggautier** [comment] 2018-04-27 18:47
We're considering badges as part of the DataTags work (https://github.com/IQSS/dataverse/issues/871, which will let depositors apply tags that signify the level of access others have to the data).

We're considering if and how OSF badges can be applied to data with certain DataTags. Eleni wrote in an [earlier comment here](https://github.com/IQSS/dataverse/issues/2119#issuecomment-98140246) that:

> for an OSF Open Data Badge there are two sets of criteria that need to be met:
> 
> 1. Provide the URL, doi, or other permanent path for accessing the data in a public, open access repository
> [This can be set automatically by Dataverse when the dataset is published and unrestricted]
> 
> 2. Is there sufficient information for an independent researcher to reproduce the reported results? If no, explain.
> [Would most likely need a human aka Dataverse Admin (i.e. journal editor) to vet this information before granting the badge.]

The criteria are in [COS's Awarding Badges doc](https://osf.io/tvyxz/wiki/2.%20Awarding%20Badges/). The badge is awarded to the report, like an article, and not the data. When the party awarding the badges is making sure that an independent researcher can reproduce the reported results, of course that's verification that the data is associated with the article.

Like Eleni wrote, the first part can be automated, in that any data published with the right DataTag and/or license meets the first criteria. The second criteria would involve manual review for each award. Maybe [Code Ocean](https://codeocean.com/) could help automate the second criteria for some datasets.

**Comment by jggautier** [comment] 2018-04-28 17:38
Openbadges.org is a technical standard for creating and distributing badges (https://openbadges.org/get-started/). Where COS's badges are a set of "flat" images with defined criteria, Open Badges are "portable digital badges with embedded metadata about skills and achievements." (COS is [considering](https://osf.io/tvyxz/wiki/6.%20Future%20Directions/) making their badges "digitally verifiable" in the same way.)

Using Openbadges might mean:
- Dataverse becomes its own issuer of badges, adopting the "Open Badges Specification" (https://openbadges.org/get-started/issuing-badges/) and becoming a platform others use to create and issue badges.
- Dataverse uses one of [these platforms](https://www.imsglobal.org/openbadges-certified-products) instead, like Credly (looks like [Harvard School of Education uses it](https://credly.com/u/2036543) or [Badgr](https://info.badgr.io/) (free and open source) to create, issue and display badges.

**Comment by pdurbin** [comment] 2019-06-07 19:51
Related: Handling and measuring (meta)data quality inside Dataverse #4751

**Comment by djbrooke** [comment] 2019-07-19 18:29
Closing this in favor of #6041 for a more generalized approach.

**Closed by djbrooke** 2019-07-19 18:29 UTC
Labels: Feature: External Tool

**Comment by bencomp** [comment] 2019-07-22 07:39
This issue was quite general already, wasn't it?

**Comment by djbrooke** [comment] 2019-07-22 14:09
#6041 is an attempt to capture the use cases for displaying metadata and data quality measurements, which we'll be user testing soon. Badging can be a part of that. The consolidation was to make sure we took into account as many use cases as possible when delivering a solution. From there, we may spin out individual efforts for implementation, which may or may not include badging.

**Comment by pdurbin** [comment] 2024-05-07 21:08
A new issue just came in:

- #10544
