### ISSUE TITLE
Address Test Failures

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#6073] opened 2019-08-06 11:45 UTC
I just ran the phoenix API test suite as of 271dbd0 and tests are failing as shown in the screenshot below and https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/

The last time the tests were run was over two weeks ago on July 20 so we'll need to figure out what changed since then.

![Screenshot from 2019-08-06 07-41-04](https://user-images.githubusercontent.com/21006/62537256-f970ea80-b81d-11e9-9217-412cc8b188f6.png)

Recently merged pull requests include #6060 and #5987.

**Comment by landreev** [comment] 2019-08-06 20:20
With the failures I've reviewed so far (for ex., FileIT:testForceReplaceAndUpdate), I'm at a complete loss as to why file replace stopped working... and how it could be connected to the small permission change I made in the create dataset command. 
I'm hearing the same thing from @sekmiller who's been looking into a few other failures (for ex., test_007_ReplaceFileUnpublishedAndBadIds). 
The reason appears to be the same - 500 thrown from an attempt to replace a file, caused by something inside the permissionservice bean.

**Comment by landreev** [comment] 2019-08-06 20:45
OK, I think I kinda see what's going on...
All I did in that PR, I changed the required permissions on the CreateNewDataset command, to prevent a user with an account (but no special rights on the dataverse) to add datasets before the dataverse is published. I looked through the restassured tests, and it doesn't look like any of them relied on being able to do so... 

However, it appears that switching from using the "@RequiredPermissions(Permission.AddDataset)" annotation in the command to a dynamic required permissions map results in different permissions that the user ends up having on the dataset created - "contributor" vs. "curator"... and that in turn is what's causing file replace to no longer be permitted. 

Does this ring a bell for anyone, as to why this would be happening?

**Comment by sekmiller** [comment] 2019-08-06 20:48
The weird thing is that in the AddReplaceFileHelper there's a permission test that requires AddDataset permission in order to replace a file (see  step_015_auto_check_permissions). If I change it to editDataset then the FilesIT tests pass.

**Comment by landreev** [comment] 2019-08-06 20:54
But that's the thing - this has to have something to do with the user no longer being recognized as the curator, but as a mere contributor. 
That permission requirement has always been there, and file replace was always working.

**Comment by sekmiller** [comment] 2019-08-06 21:09
Right but the failure isn't a run of the mill permission requirement failure it's an java.lang.UnsupportedOperationException when you try to remove the admin permissions from the required permissions in "hasGroupPermissionsFor".

**Comment by landreev** [comment] 2019-08-06 21:42
That looks like yet another, unrelated bug on its own. 
We may investigate why it happens, but it is the loss of the AddDataset permission that appears to be the issue at hand - right? 

(did we ever mean to only allow admins to replace files?)

**Comment by landreev** [comment] 2019-08-06 21:49
I have to mention that one way of fixing this would be to simply reverse the PR #6061 - I'm currently trying to figure out if it was something we really can't live without. 
We'll figure it out tomorrow.

**Comment by landreev** [comment] 2019-08-06 23:19
RoleAssignments on the dataverse and dataset are exactly the same (1 and 6, respectively), whether the CreateNewDataset is using an annotation, or a dynamic permissions map... 
But yeah, it bombs with the latter, goes back to working with the former... - that's all I know for the fact at this point; still don't have any idea why.

**Comment by landreev** [comment] 2019-08-07 00:03
OK, I *think* I got it... Will retest and finish tomorrow.

**Comment by djbrooke** [comment] 2019-08-07 02:23
FWIW, I'm fine simply reverting the changes in #6061. It does address a possible vector for spam/abuse but the fix may be more challenging than we thought and we should move onto other higher priority problems.

**Comment by sekmiller** [comment] 2019-08-07 13:28
@landreev we both figured it out. see my commit https://github.com/IQSS/dataverse/commit/9f9ec403bfaa643d368be5758627649297c67370

This does the same thing as yours and fixes the FilesIT failures. It does not address Phil's use case in the InReview workflow where he gives a user addDataset permissions but not view unpublished DV and has that user in the test add a dataset to an unpublished DV. That test needs to be rewritten somewhat to get it to pass.

**Comment by pdurbin** [comment] 2019-08-07 14:40
@landreev @sekmiller good catch. 😄 

Something I brought up to @djbrooke and @sekmiller yesterday is that if we're changing the rules with regard what is required to create a dataset, our SWORD API (in the "develop" branch at least) is now out of step with the "create dataset" command.

The entry point for SWORD is the Service Document. Basically the user asks, "Where do I have permission to create a dataset?"

SWORD returns a list of dataverse aliases using the following code in ServiceDocumentManagerImpl.java:

    permissionService.getDataversesUserHasPermissionOn(user, Permission.AddDataset)

SWORD does not pay any attention to whether or not a dataverse is published. For consistency, if we are changing the rules, we should probably also change the SWORD API to enforce the same rules. Otherwise, SWORD users can have a confusing user experience of getting an error when trying to create a dataset in a dataverse that SWORD just told them is a legit place to create a dataset. From a spot check, Harvard Dataverse returns many unpublished dataverse via the SWORD Service Document, which contains for me 162 dataverses I'm allowed to create datasets in (this seems like a lot and I wonder why there are so many), two of which I created myself.

This is in the API Guide but here's how to get the names of all the dataverses you have "AddDataset" on:

    curl -u $API_TOKEN: https://$HOSTNAME/dvn/api/data-deposit/v1.1/swordv2/service-document

I also think that we should put a line about the rules in the API guide. And in a release note, to note the change in behavior. Something like this maybe:

- API Guide: "To create a dataset, you must have the `AddDataset` and `ViewUnpublishedDataverse` on the parent dataverse if it is unpublished. If the parent dataverse has been published, only `AddDataset` is required."
- Release note: `Additional permission is now required to create datasets in unpublished dataverses. In addition to `AddDataset`, you must have the `ViewUnpublishedDataverse` on the unpublished dataverse. As before, after a dataverse has been published, having the `AddDataset` permission is sufficient."

And to reiterate, possible remaining todo are:

- [ ] Update the SWORD API to not return dataverses that users cannot create datasets into.
- [ ] Update all API tests following the change above to keep the API test suite passing.

**Comment by landreev** [comment] 2019-08-07 15:10
@pdurbin Of the two "todo" checkboxes from your message, is the number one ("update sword no to return unpublished dataverses, if the user can't create datasets in them") something we can live without?
Sword is likely not the most widely used api... and as long as an actual attempt to create a dataset in such a dataverse fails with a clear error message ("you will only be able to add datasets once the dataverse is published"?), this may be ok - what do you think? 

And, once again, there's an option to reverse #6061

**Comment by landreev** [comment] 2019-08-07 15:12
@sekmiller All that said, what Raman is doing there with the permission test on "AddDataset" is likely wrong.

**Comment by landreev** [comment] 2019-08-07 22:28
I made a PR reverting the original change, as discussed. 
However, this one RA test still appears to be failing: 

UsersIT.testChangeAuthenticatedUserIdentifier:93 Expected status code <400> doesn't match actual status code <500>

this is a username validation test; we attempt to use a single character username, and expect it to fail cleanly. Instead there are bean validation exceptions in the server log, and a 500 response. 
I'm somewhat positive this is not related to the pr #6061... 
@sekmiller - you (relatively) recently worked on something validation-related in ChangeUserIdentifierCommand - does this error make any sense to you by any chance?

**Comment by sekmiller** [comment] 2019-08-08 14:50
I'll take a look at the change Identifier command. Not sure what is going on there.

**Comment by landreev** [comment] 2019-08-08 15:10
@sekmiller I don't want to jump to conclusions, I've been wrong about causes of some issues lately, but I'm guessing there's at least a chance that this one is a result of the merge of the "on success" command functionality.

**Comment by landreev** [comment] 2019-08-08 19:13
Thanks for removing the 6061-specific restassured test!

**Comment by landreev** [comment] 2019-08-08 19:46
Moving this into CR. 
This brunch contains: 
- Undoing of #6061 - Configuring a dataverse so that "anyone with an account can add ..." now allows anyone to do just that, even if the dataverse isn't published, again. There's commented-out code left that can be re-enabled if ever need to. (or to be used as a model for something similar; for ex., if we ever need another dynamic permission setup that produces sets of multiple permission values)
- A fix for the command engine that allows validation errors that may occur inside commands to be properly intercepted (that addresses the last test failure above, in UsersIT. 

and also: 

- A minor change in Raman's file replacement code; something that was discovered as we were looking into this; and just made sense to fix while we were at it. (it was checking a wrong permission)

**Closed** 2019-08-09 19:32 UTC

**Comment by pdurbin** [comment] 2019-08-09 20:10
Hooray! Now that pull request #6077 has been merged, the phoenix tests are passing again. See https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/ or the screenshot below:

![Screen Shot 2019-08-09 at 4 08 49 PM](https://user-images.githubusercontent.com/21006/62806191-23e1d280-bac0-11e9-9e24-717b525d0cf3.png)
