### ISSUE TITLE
Edit Dataset Files Message: file names extend off page, need a space

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2206] opened 2015-05-27 18:50 UTC
![uvj7__pikbjpt5tgqlxcjoeomjo_0z7n6wj9yyai0ck](https://cloud.githubusercontent.com/assets/8322346/7844614/a0150918-047f-11e5-956e-cace05ede114.png)

**Comment by mheppler** [comment] 2016-02-10 21:20
@sbarbosadataverse - this issues looks to be a duplicate of #2224, which I am working on currently to fix. Please close this is it is a duplicate, or provide more details explaining if the issues are different.

**Comment by sbarbosadataverse** [comment] 2016-02-11 01:03
Will do. Thanks

**Comment by mheppler** [comment] 2016-02-11 20:29
Already committed a fix (ae12ba6fc473e5c5617282adcbaf1f3d19e1bb8c) for this, which was referenced on the other ticket.

**Comment by kcondon** [comment] 2016-04-05 16:11
Closing as fixed,

**Closed by kcondon** 2016-04-05 16:11 UTC
Labels: Component: UX & UI, Priority: Medium, Status: Dev, Type: Bug
