### ISSUE TITLE
DCM -> DV user notification APIs

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#3942] opened 2017-06-21 16:17 UTC
Notifications for users about their DCM uploads, mediated through Dataverse (vs having the DCM directly sending email).

1. Success message: dataset has been uploaded, checksums validate.
2. Error message: dataset has been transferred; checksums do not validate; rerun script and/or contact support.

**Comment by djbrooke** [comment] 2017-06-21 19:00
- Need message text
- @pdurbin may already have the code

**Comment by pdurbin** [comment] 2017-06-21 23:07
Heh, true. Just like for #3725 I would plan to dust off the code in https://github.com/pdurbin/dataverse/tree/3145-dcm

As I mentioned in sprint planning, the "When rsync upload begins, send a message to Dataverse" feature requested by @mheppler @TaniaSchlatter @dlmurphy at https://github.com/sbgrid/data-capture-module/issues/21 is related.

**Comment by pameyer** [comment] 2017-06-23 20:25
Re: "send message to Dataverse when transfer starts"; I think the second of the options mentioned in https://github.com/sbgrid/data-capture-module/issues/21 would be the way to go.  That would require a new Dataverse endpoint: script uses user token to notify Dataverse on the user's behalf that transfer has started (and potentially that the transfer has finished, separate from file validation).

**Comment by pdurbin** [comment] 2017-06-26 00:04
@pameyer meh, I'm not very excited about that second option. I'll go leave a comment about this at https://github.com/sbgrid/data-capture-module/issues/21 too. All this is out of scope anyway. I just thought I'd mention it. Thanks.

**Comment by pdurbin** [comment] 2017-07-28 20:15
After discussing this issue with @pameyer at http://irclog.iq.harvard.edu/dataverse/2017-07-28 and yesterday as of 7681c63 I have written a REST Assured test that pretend to be the Data Capture Module (DCM) and that sends JSON like this:

```
{
  "datasetId": 301,
  "status": "validation passed",
  "uploadFolder": "DO7BKX",
  "datasetId​entifier": "DO7BKX",
  "totalSize": 1234567890
}
```

In the UI, a "package" is created that looks like this:

![njaxyxq](https://user-images.githubusercontent.com/21006/28734626-e9736838-73af-11e7-8a9e-f5303d1d0a4a.png)

There are still a lot of FIXMEs and TODOs in the code but some definite progress.

**Comment by pdurbin** [comment] 2017-08-01 18:28
I just created pull request #4034 and moved it to Code Review at https://waffle.io/IQSS/dataverse

In half an hour or so, I'll be talking more about the issue and pull request in our weekly technical meeting.

**Comment by pdurbin** [comment] 2017-08-02 12:50
To do list based on tech meeting yesterday with @sekmiller @landreev @bsilverstein95 @oscardssmith @rbhatta99 and @jacobmakar as of 3af2355:

- [ ] Move Big Data Support page from Installation Guide to Dev Guide.
- [ ] Document that a shared filesystem is required and that you can't use Swift of S3.
- [ ] Document details of the JSON passed into API: status, uploadFolder, and totalSize
- [ ] To the "unhappy path" notification, add something like "run the script the script again or contact support." Something more like this: "One or more files in your dataset failed to match the checksum calculated on your local system.  Please re-run the upload script associated with this dataset.  If you have any questions, please contact data@sbgrid.org."
- [ ]  To the "happy path" notification, add something like more like this: "Dataset doi:10.15785/SBGRID/480has been successfully uploaded and verified.  If you have any questions, please contact data@sbgrid.org."

**Comment by dlmurphy** [comment] 2017-08-02 15:54
Piggybacking off Phil's suggestions, here is some messaging for both notifications.

**Success:** Dataset $DATASET_PERSISTENT_ID has been successfully uploaded and verified.

**Failure:** "One or more files in your upload failed checksum validation. Please re-run the upload script. If the problem persists, please contact Dataverse Support at $SUPPORT_EMAIL."

**Comment by pdurbin** [comment] 2017-08-02 20:04
@dlmurphy thanks, I incorporated the new wording as part of ea04262.

I also implemented all of the items from the todo list above.

**Comment by pameyer** [comment] 2017-08-02 22:45
- Notification logic appears different for "validation passed" vs "validation failed"; with failure path sending messages to more users than success path.
- For the shared filesystem docs; is it worth mentioning permission/uid/gid matching, or is that obvious?

**Comment by pdurbin** [comment] 2017-08-03 15:07
@sekmiller improved the notifications base on @pameyer 's feedback in 2dd89a5 .

@pameyer and I talked about the uid/gid matching and decided we can add it to the DCM README if necessary. Basically, the DCM need to be able to move files around at will on the shared filesystem between Dataverse and DCM.

**Comment by pdurbin** [comment] 2017-08-07 19:15
@michbarsinai suggested removing the port 8080 requirement by refactoring the logic in FileRecordJobResource.java into a command, which I did in f8809c3.

**Comment by kcondon** [comment] 2017-08-10 18:09
OK notifications work as described in the doc but currently seeing an exception in the logs when loading the homepage and not a super user.:

[2017-08-10T13:37:20.950-0400] [glassfish 4.1] [WARNING] [] [javax.enterprise.resource.webcontainer.jsf.lifecycle] [tid: _ThreadID=52 _ThreadName=jk-connector(4)] [timeMillis: 1502386640950] [levelValue: 900] [[
  /search-include-fragment.xhtml @653,93 actionListener="#{SearchIncludeFragment.setDisplayCardValues()}": java.lang.NullPointerException
javax.el.ELException: /search-include-fragment.xhtml @653,93 actionListener="#{SearchIncludeFragment.setDisplayCardValues()}": java.lang.NullPointerException
	at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:111)
	at javax.faces.event.MethodExpressionActionListener.processAction(MethodExpressionActionListener.java:147)
	at javax.faces.event.ActionEvent.processListener(ActionEvent.java:88)
	at javax.faces.component.UIComponentBase.broadcast(UIComponentBase.java:813)
	at javax.faces.component.UICommand.broadcast(UICommand.java:300)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790)
	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282)
	at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.ApplicationDispatcher.doInvoke(ApplicationDispatcher.java:873)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:739)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:575)
	at org.apache.catalina.core.ApplicationDispatcher.doDispatch(ApplicationDispatcher.java:546)
	at org.apache.catalina.core.ApplicationDispatcher.dispatch(ApplicationDispatcher.java:428)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:378)
	at org.ocpsoft.rewrite.servlet.impl.HttpRewriteResultHandler.handleResult(HttpRewriteResultHandler.java:41)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.rewrite(RewriteFilter.java:268)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:188)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:412)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at edu.harvard.iq.dataverse.ThumbnailServiceWrapper.getDatasetCardImageAsBase64Url(ThumbnailServiceWrapper.java:180)
	at edu.harvard.iq.dataverse.ThumbnailServiceWrapper.getDatasetCardImageAsBase64Url(ThumbnailServiceWrapper.java:177)
	at edu.harvard.iq.dataverse.ThumbnailServiceWrapper$Proxy$_$$_WeldClientProxy.getDatasetCardImageAsBase64Url(Unknown Source)
	at edu.harvard.iq.dataverse.search.SearchIncludeFragment.setDisplayCardValues(SearchIncludeFragment.java:1178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.el.ELUtil.invokeMethod(ELUtil.java:332)
	at javax.el.BeanELResolver.invoke(BeanELResolver.java:537)
	at javax.el.CompositeELResolver.invoke(CompositeELResolver.java:256)
	at com.sun.el.parser.AstValue.invoke(AstValue.java:283)
	at com.sun.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:304)
	at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
	at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
	at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105)
	... 56 more
]]

**Closed** 2017-08-10 20:40 UTC
Labels: Component: File Upload & Handling, SBGrid

**Comment by pdurbin** [comment] 2017-08-11 01:25
> currently seeing an exception in the logs when loading the homepage and not a super user

I followed up with @kcondon about this in person and it sounds like Swift storage was down. That's unrelated to this issue but @kcondon @landreev and I agreed could probably do a better job of monitoring external services like that.

**Comment by pdurbin** [comment] 2017-08-11 16:42
Follow up issue created: #4067 External Storage: For external storage, Swift/S3, should consider providing health check and fail more gracefully.
