### ISSUE TITLE
Confusing dates on a dataset

### ISSUE THREAD

**Issue by suenjedt** [IQSS/dataverse#2061] opened 2015-04-21 15:32 UTC
I am going through scholar's dataverses and am a little confused about the dates shown in the cards. In particular in the screenshot below where dates dont match when comparing 3.6 and 4.0. Also I could not find the date Sept 30 2012 in any of the metadata fields. 
https://dataverse.harvard.edu/dataverse/alansz [see also screenshots below].
And another example where I don't understand the given date, https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/14819 

![screen shot 2015-04-21 at 11 20 19](https://cloud.githubusercontent.com/assets/7300319/7255709/019a35ec-e819-11e4-8eaf-f207175b501a.png)
![screen shot 2015-04-21 at 11 18 02](https://cloud.githubusercontent.com/assets/7300319/7255710/019b87c6-e819-11e4-9edd-a5bd9ebf87d6.png)

**Comment by kcondon** [comment] 2016-04-04 17:54
The date of 9/30/2012 does not appear in the dataset metadata in the example given. However, there is a version 2 and it's publication date is 10/1/2012 so maybe it is related to creation date for the version?
2 issues:
1. What does this date mean? Should be clearer.
2. Did not find the date anywhere.

**Comment by mheppler** [comment] 2016-10-13 21:31
Closing this issue as a duplicate of #2607.

**Closed by mheppler** 2016-10-13 21:31 UTC
Labels: Component: Metadata, Effort 2: Medium, Priority 3: Serious, Status: Triaged, Type: Bug
