### ISSUE TITLE
Dataset Pg, File Search - After search with 0 or 1 results, search box is missing

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#4184] opened 2017-10-10 18:08 UTC
1. Go to a dataset.
2. Type something into "Search this dataset" and click "find".
3. If 0 or 1 results, the search goes away.

Issues with this are: 
1. No indication of what you've searched.
2. No way to modify your search.
3. No way to return to full view.

**Comment by pdurbin** [comment] 2017-10-10 19:04
I can reproduce this on v. 4.8 build 105-896714e on https://demo.dataverse.org

**Comment by mheppler** [comment] 2017-10-12 17:47
Changed render logic from using search metadata size `DatasetPage.fileMetadatasSearch.size() gt 1` to instead look for the number of total files `DatasetPage.workingVersion.fileMetadatas.size() gt 1`.

**Comment by pdurbin** [comment] 2017-10-13 13:38
Pull request #4192 looks like a good fix. Approved. Moving to QA.

**Closed** 2017-10-19 18:55 UTC
