### ISSUE TITLE
Optimize Permissions Lookup

### ISSUE THREAD

**Issue by astrofrog** [IQSS/dataverse#2122] opened 2015-04-30 17:50 UTC
I tried accessing:

```
https://dataverse.harvard.edu/api/dataverses/:root/contents?key=...
```

but this hangs. If I replace `:root` by say `cfa`, then it works fine.

**Comment by pdurbin** [comment] 2015-04-30 18:28
"I wonder if querying the root is an expensive operation," I opined at http://irclog.iq.harvard.edu/dataverse/2015-04-30#i_19145

This is potentially yet another expensive tree traversal problem. See also #752.

**Comment by pdurbin** [comment] 2015-06-29 13:39
This performance problem with the "contents" API endpoint was also mentioned at https://github.com/IQSS/dataverse/issues/1837#issuecomment-102085381

**Comment by garthg** [comment] 2015-06-29 20:12
Hi,

@pdurbin Thanks for connecting this issue to the other trackers. This bug is a blocker for my project, as it impacts API-driven dataset editing and dataset creation. The non-returning call to get_contents() is very hard to avoid due to the combination of:
1) requiring database IDs instead of working with only with DOIs (tracked in issue #1837), AND
2) the inability to search for non-published datasets (tracked in issue #1299).

Garth

**Comment by pdurbin** [comment] 2015-12-17 15:30
@michbarsinai and I took a look at this today and I captured some profiling data, which I uploaded to [Google Drive](https://docs.google.com/a/harvard.edu/document/d/1dafzUn7Ng6q-DBPqQliJdSW6Y4j5wEObu0f8GRmXb1w/edit?usp=sharing). `curl http://localhost:8080/api/dataverses/:root/contents?key=$API_TOKEN` ran for about 40 minutes but I'm not sure what the output ultimately was since I was piping the output to `jq` and it wasn't valid JSON.

**Comment by pdurbin** [comment] 2016-01-04 19:51
@michbarsinai you poked at the code a bit the other day, I believe. Perhaps you could comment on any findings.

**Comment by michbarsinai** [comment] 2016-01-05 06:39
Seems to have something do to with group resolution. This one is the next on my list, so hopefully we'll see some advances here soon.

**Comment by pdurbin** [comment] 2016-02-29 19:02
@scolapasta has been working on groups stuff in #2978 but I'm not sure it's related to group resolution or not.

**Comment by kcondon** [comment] 2016-04-04 18:11
The root cause of this may be #752, tree traversal, however there is a related issue, #1160 . The effort will be to investigate root cause.

**Comment by mheppler** [comment] 2016-10-10 14:26
@yarikoptic commented on Apr 4 on issue #3058

```
$> wget  'https://dataverse.harvard.edu/api/dataverses/icpsr/contents?key=SENSORED' 
--2016-04-04 09:32:48--  https://dataverse.harvard.edu/api/dataverses/icpsr/contents?key=c87766ca-e34c-4e9c-a23e-be277265074c
Resolving dataverse.harvard.edu (dataverse.harvard.edu)... 128.103.69.227
Connecting to dataverse.harvard.edu (dataverse.harvard.edu)|128.103.69.227|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2016-04-04 09:33:49 ERROR 500: Internal Server Error.
```

**Comment by pdurbin** [comment] 2017-06-23 13:24
Is anyone who is following this performance issue still suffering from it?

**Comment by yarikoptic** [comment] 2017-06-23 14:16
did API change?  I got the API token from https://dataverse.harvard.edu/dataverseuser.xhtml?selectTab=apiTokenTab and tried to do as I did previously:
```shell
$> wget "https://dataverse.harvard.edu/api/dataverses/icpsr/contents?key=$DATAVERSE_API"
--2017-06-23 10:14:17--  https://dataverse.harvard.edu/api/dataverses/icpsr/contents?key=7e8.......................
Resolving dataverse.harvard.edu (dataverse.harvard.edu)... 128.103.69.227
Connecting to dataverse.harvard.edu (dataverse.harvard.edu)|128.103.69.227|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
```

**Comment by garthg** [comment] 2017-06-23 15:33
Hi,

I still had this problem as of last week. Should I re-test now?

Thanks,

Garth

**Comment by pdurbin** [comment] 2017-06-25 20:44
@yarikoptic @garthg no the API didn't change. Sorry to get your hopes up! I was just sweeping through old issues the other day trying to gauge interest. Sounds like you're both still interested in a fix. Thanks!

**Comment by SamiSousa** [comment] 2018-03-25 20:51
I'm still interested in this issue. Ultimately displaying the contents of the root dataverse can be avoided by using the search API to find subtree dataverses, and using the native API from there (assuming there aren't datasets listed directly under the root dataverse). However, this doesn't solve the issue for other large dataverses beneath root...

**Comment by djbrooke** [comment] 2018-04-16 17:29
Moving to backlog column to get an estimate on this during our next backlog grooming discussion. The performance issues here are affecting some integrations.

**Comment by pdurbin** [comment] 2018-05-25 12:47
> The performance issues here are affecting some integrations.

I just tested OSF and while I can see datasets in my "Open Source at Harvard" dataverse at https://dataverse.harvard.edu/dataverse/open-source-at-harvard just fine ....

<img width="1333" alt="screen shot 2018-05-25 at 8 42 41 am" src="https://user-images.githubusercontent.com/21006/40544896-c4a0d844-5ff7-11e8-8a1d-6b67cba76bea.png">

... I can't see any datasets in the "root" dataverse, which is called "Harvard Dataverse" and see an error saying "Could not load datasets":

<img width="1333" alt="screen shot 2018-05-25 at 8 44 27 am" src="https://user-images.githubusercontent.com/21006/40544918-d9cbadde-5ff7-11e8-999a-9628b4f7f27d.png">

Mind you, I don't actually have any datasets in the root dataverse of Harvard Dataverse, so I'm not affected. @shlake are any of your users affected by this bug?

Yesterday @djbrooke forwarded to me a conversation with @sloria (hi!) and I'm trying to get a sense of the extent of the problem.

**Comment by shlake** [comment] 2018-05-25 13:19
This used to work. Yes, in the list you would only see datasets in main Harvard dataverse (top level) that you have curator (and another, I think) permissions too. Very well could be a timing issues that OSF can't sort through & test permissions with thousands of datasets. UVA has less than 100 so timing hasn't effected us.

This whole display needs MAJOR work & OSF didn't have the capacity to look at it, & I didn't have time to pursue and the project manager at OSF had a baby last Fall. So nothing has been upgraded in a year or two.

I can look at my. Otes next week when I get back in the office.

**Comment by shlake** [comment] 2018-05-25 13:29
@pdurbin here's some info in my Dataverse Presentation last year https://osf.io/7w8rz/

**Comment by sloria** [comment] 2018-05-25 13:43
There's more detail in my email thread with @djbrooke , but this is the method that is timing out: https://github.com/IQSS/dataverse-client-python/blob/66a01e216812b338c9502911a2d022223b9094a7/dataverse/dataverse.py#L137 

In addition, this request to get a Dataverse's contents hangs then eventually returns a 500 response (which may be a separate issue from the slowness?): https://gist.github.com/sloria/409d6b5d547aa65d9d01dcc67aceec36

**Comment by pdurbin** [comment] 2018-07-09 15:59
@oscardssmith and I discussed this issue this morning and we agree that it will be important for a developer to be able to load up a heavily nested hierarchy of dataverses in order to see the slowness in a dev environment. I mentioned that Raman wrote a Python script to do this that I mentioned over at https://github.com/IQSS/dataverse/issues/752#issuecomment-64442551 . I'm attaching it and the input file here (with ".txt" appended so GitHub Issues will take it) but please note that it uses Selenium and we might want to simply it to just hit the API directly.

- [dv_make_flare_dataverses.py.txt](https://github.com/IQSS/dataverse/files/2176971/dv_make_flare_dataverses.py.txt)
- [flare.json.txt](https://github.com/IQSS/dataverse/files/2176970/flare.json.txt)

This is how the tree of dataverses looks:

![tree](https://user-images.githubusercontent.com/21006/42461771-4b9f7900-836f-11e8-94ca-5689d2f17a2b.png)

Based on old comments in this issue it looks like I suspected slowness in the permission system and I don't believe this has been addressed yet. It would be a good place to start digging, I think. There's also the concept of Modified Preorder Tree Traversal (MPTT) that may or may not be worth investigating. I wrote about it at https://github.com/IQSS/dataverse/issues/752#issuecomment-64132165

**Comment by oscardssmith** [comment] 2018-07-09 16:09
My initial reaction is that MPTT is a really bad fit for our structure. It has the significant weakness that creating or deleting new objects in the tree requires remaking a significant portion of the structure. Instead, I think a better approach would be to use multiple rows per dataverse to list all parents. This has the advantage of never introducing large changes, while still removing the need for recursion.

**Comment by michbarsinai** [comment] 2018-07-09 16:19
That's exactly why we abandoned it last time. I agree that we need to start seeking non-normalize solutions. One way could be what @oscardssmith offers here. We could also use solr (since it's part of the infrastructure already). The extreme solutions could be using graph databases (e.g. Neo4J) or use recursive SQL (e.g. https://www.postgresql.org/docs/8.4/static/queries-with.html).

**Comment by scolapasta** [comment] 2018-07-09 18:05
The issue doesn't relate to the nested hierarchy as this endpoint doesn't delve into the tree structure (please correct me if that's wrong). The issue, as far as we understood it the last time, is with doing individual performance checks on the many dv objects* at one level.

* one way to possible check for this is to run the endpoint as a superuser, which in theory should bypass the permissions checks, or at the very least short circuit them

As @michbarsinai suggests one way is to have this go through solr, as we preindex permissions there. (in fact the current work around for this is to use the search endpoints instead of this one). The biggest concern with this if we wanted to have a way of querying without using solr. At this point, I'd say it'd be reasonable to solve it this way so that we have a working solution.

Brainstorming some other approaches:
- only return a partial list with the idea of a "continue", i.e. get me the first 50, then the next 50, etc. I don't know if I like this idea much.
- rather than use the permissions methods on the service bean do a direct query to the db to check for the roles they have. This wouldn't necessarily account for when the user is in a group that has a role, but in general edit type permissions are rarely given to groups.

**Comment by oscardssmith** [comment] 2018-07-09 18:37
@scolapasta If I am reading the code correctly, this at one point calls `permissionsForSingleRoleAssignee` which does a recursive tree traversal.

**Comment by scolapasta** [comment] 2018-07-09 18:46
@oscardssmith I think that's checking the user/group hierarchy, not the dvObject tree.. (again, I may be misremembering - feel free to stop by and we can look at the code)

**Comment by shlake** [comment] 2018-07-09 18:50
Question: How is "My Data" displayed? That seems to come up fast. Or is it because that's coded in JAVA and not via API (SWORD, etc)? With the OSF example, I would only expect to see the datasets that I have permissions for, which show up in "My Data" right?

**Comment by michbarsinai** [comment] 2018-07-09 19:50
Another thing we should do anyway is test for required permissions for a given command, rather than getting all the permissions for a user on a given DvObject, as we do now. That is:

Today: 
	
	1. Get all the permissions the user has on a DvObject (recursive climb in DvObjcet containment hierarchy x (groups + user) )
	2. Get the permissions required for the command (method call)
	3. Check that (1) contains (2)

Optimized:

	1. Get the permissions required for the command (method call)
	2. Creep up the DvContainment hierarchy until all permissions in (1) are found, or until we hit a permission root.

Today's code was easy to write it's easy to see that it's correct. But it collects more permissions than necessary. Since for most cases only a single permission is required, we might be able to cut down a lot of SQL and JPA code. We could also devise more efficient JPA queries to get all the permissions for the user and the relevant groups in a single query.

**Comment by oscardssmith** [comment] 2018-07-10 13:34
Question: what is the minimal set of things needed to reproduce this issue? I've created 5000 dataverses, and the command is quite quick.

**Comment by pdurbin** [comment] 2018-07-10 13:42
@oscardssmith I believe that the only place where we've heard of this performance problem is https://dataverse.harvard.edu . Anyone can create an account there so you would be welcome to create one and make sure that the problem can still be reproduced. Can you please attach your script to create all those dataverses? I wonder if we need to also create datasets (and maybe files) and also make a large number of role assignments. If necessary, we can get you a dump of the production database but first I'd double check that you're still seeing the performance problem in production, as I suspect you will.

**Comment by oscardssmith** [comment] 2018-07-10 13:46
import json
    import requests


    def make_nested(i=1):
        if i > MAX:
            return
        print(i)
        dataverse_json = '''{
        "name": "Scientific Research",
        "alias": "nested%d",
        "dataverseContacts": [{"contactEmail": "pi@example.edu"}]}''' %i
        
        if i == 1:
            url = f'{dataverse_server}/api/dataverses/root?key={api_key}'
        else:
            url = f'{dataverse_server}/api/dataverses/nested{i//2}?key={api_key}'
        requests.post(url, data=dataverse_json)
        requests.post(f'{dataverse_server}/api/dataverses/nested{i}/actions/:publish?key={api_key}')
        make(2*i)
        make(2*i+1)
        
    def make_flat():
        for i in range(500,MAX+1):
            print(i)
            dataverse_json = '''{
            "name": "Scientific Research",
            "alias": "flat%d",
            "dataverseContacts": [{"contactEmail": "pi@example.edu"}]}''' %i
            
            url = f'{dataverse_server}/api/dataverses/root?key={api_key}'
            requests.post(url, data=dataverse_json)
            requests.post(f'{dataverse_server}/api/dataverses/flat{i}/actions/:publish?key={api_key}')

    dataverse_server = 'http://localhost:8080' # no trailing slash
    api_key = 'aba1b874-b86e-44fd-a992-ced767ece854' #root
    api_key = 'dba4246f-4aec-4579-9c22-8f09b438264b' #user
    MAX = 5000
    #make_nested()
    #make_flat()
        
    r = requests.get(f'{dataverse_server}/api/dataverses/:root/contents?key={api_key}')
    print(r.json())

**Comment by oscardssmith** [comment] 2018-07-10 13:54
Just confirming, this issue is reproducible on harvard dataverse. I think that to move forward on this, I need some place that has enough data, that I can profile and make code changes to.

**Comment by pdurbin** [comment] 2018-07-10 13:56
@oscardssmith ok, @jggautier and @dlmurphy have access to a copy of production data for #4169 and can probably help you get a copy. That copy is updated ever once in a while by @kcondon but I'm sure that the copy will be new enough to exercise the bug.

**Comment by michbarsinai** [comment] 2018-07-10 17:36
The performance issues might have more to do with groups and containment hierarchy depth than with Dataverse count.

**Comment by oscardssmith** [comment] 2018-07-10 19:35
I'm most of the way through installing the harvard dataverse (minus files) to my system, which should let me test this finally.

**Comment by pdurbin** [comment] 2018-07-11 16:49
@oscardssmith the other day I was telling you about a nice visualization in D3 that @raprasad made that shows a hierarchy of dataverse. He and I just looked and couldn't find it but we did find the JSON output that the visualization was created from at "Full Dataverse hierarchy (pretty)" linked from https://services.dataverse.harvard.edu/miniverse/metrics/metrics-links

Here's a few lines of how https://services.dataverse.harvard.edu/miniverse/metrics/dv-tree-full.json?pretty looks:

![screen shot 2018-07-11 at 12 48 11 pm](https://user-images.githubusercontent.com/21006/42587436-b8531fb2-8508-11e8-8a19-41d312d877d7.png)

Here's the code if it's of interest: https://github.com/IQSS/miniverse/blob/864cb9d75c45933cb74f67aa1eada5f2e13c0c13/dv_apps/metrics/urls.py#L79

**Comment by oscardssmith** [comment] 2018-07-19 16:52
At this point, I've added fastpaths for superusers and non logged in users that both only take ~2 seconds to complete. Now to get Authenticated Users equally fast.

**Comment by oscardssmith** [comment] 2018-07-30 20:51
I have an implementation with Solr working, which I am now going to ditch because it takes about as long as my previous attempt (25 min) just for solr to do it's part. At this point we have 3 options to go forward

1. Write lots of custom queries to brute force this
2. Cache group membership
3. Only allow users to lookup some number ~50 at a time.

**Comment by landreev** [comment] 2018-08-15 15:06
I've been reviewing this, and I don't see any problems with the code. 
But, given the complexity of this refactoring, do you think this needs to be tested in some comprehensive way, before we decide that it's done? 
I'm ok if this testing part is done during QA. But I feel it may still be up to the developers, to come up with such comprehensive tests. Again, considering the complexity. 

Since this started as an issue with the specific dataverse-listing API, maybe a good test for this is to script running the API on the entire production database, recursively; and compare the "before" and "after", and confirm that the results are identical? (This of course could take a while, seeing how it takes forever in the "before" state). 

Any better ideas?

**Comment by michbarsinai** [comment] 2018-09-02 21:00
Interesting.... I don't get that one (on a newly installed laptop, using the installer script). I do get some other errors, though. Will report when it's solved (moving back to community dev now 😕)

**Comment by michbarsinai** [comment] 2018-09-03 13:58
Update - I've moved #4944 and its PR to QA. Since this issue is included in that one, you might want to QA only PR #4998. At any event, I didn't get the missing class exception on either issues.

**Comment by landreev** [comment] 2018-09-04 20:55
Hmm. I haven't been able to reproduce it on my dev. system either.
My glassfish setup is identical (4.1 build 13). The jar where the validator class lives (glassfish/modules/bean-validator-cdi.jar) is the same. 
dataverse-internal (vm4) may have a somewhat newer version of jdk 1.8... it could be conceivable that something in that newer jdk conflicts with the (relatively old) jars shipped with GF 4.1... but then it's only bombing with this branch, and not with others... 

@kcondon has just suggested that it could be something with how the war file is built on build.hmdc specifically - I'm going to take that and try to run it on my system now.

**Comment by michbarsinai** [comment] 2018-09-04 20:57
Maybe a messed up maven cache on that machine?

**Comment by landreev** [comment] 2018-09-04 21:01
No, that .war file also deploys just fine on my own Mac OS system. 
I'm kind of out of ideas for now...

**Comment by landreev** [comment] 2018-09-04 21:37
FWIW, we were reading this thread with somebody reporting this same "class not found" exception: https://stackoverflow.com/questions/28719090/java-lang-classnotfoundexception-org-hibernate-validator-internal-cdi-intercept. One thing the victim mentions there is: 
"...It was a @javax.validation.constraints.NotNull annotation on a method parameter in a @Stateless bean..."
and I happened to notice that @michbarsinai did add a couple of NotNull checks to a stateless bean in that branch (DataverseRoleServiceBean). And this was something we hadn't done before (as in, we only used @NotNull in entities before). 
So I tried and commented out these NotNulls from the bean, built a war file - and it is now deploying on dvn-vm4. 
I still have zero idea why this was only a problem on vm4 (and dvn-build - so, presumably, on all of our older RH 6 boxes). 
Please advise.

**Comment by michbarsinai** [comment] 2018-09-04 21:40
I've added them as part of the code review comments. I'm happy to keep the version with the @NotNull comments deleted.

In the long run, we might need to update the validation and JPA implementation anyway, since AFAIK they don't support lambdas etc too. At this point. Out of scope for this issue, though.

**Comment by landreev** [comment] 2018-09-04 21:59
I can check in my version with these annotations commented out. But, would you need to add some alternative logic to check for nulls there?

**Comment by michbarsinai** [comment] 2018-09-04 22:01
No. I left them in and had to explain why (reason: they only create warnings, not complain errors). It's just added documentation, that's all.

**Comment by pameyer** [comment] 2018-09-05 16:15
commented on the PR instead of the issue (
https://github.com/IQSS/dataverse/pull/4883#issuecomment-418759332); integration tests appear to be failing

**Comment by djbrooke** [comment] 2018-09-05 16:20
Hi @michbarsinai - I moved this back to Community Dev for now, as there's still a few items to work on. If you have the time to work on this, great! If not, let me know and we can get together some resources on this side.

**Comment by tomjscox** [comment] 2018-10-24 14:37
Dear all, 

I was sent here by osf.io. Apparently, this issue is causing osf.io projects with api access to dataverse extremely slow to load. I see there's been work going on on this issue over the last days. I was wondering by when you think the issue is expected to be resolved.

Thanks in advance,
Tom

**Comment by djbrooke** [comment] 2018-10-25 14:20
Hi @tomjscox - this is a challenging one and the primary developer for it has been at a conference this week. I don't have an estimate right now, but we'll be getting back to work on it next week. Outside of this issue, we may make some other changes to the application (in #5402) that would let OSF change to a different API, but this work has not been started yet.

**Comment by landreev** [comment] 2018-11-09 16:12
Hi @tomjscox - there were numerous delays with this issue. Because the person who did most of the work initially is no longer around; and when we started looking into it again, it had to be interrupted because a few of us went to a conference. 
But I've been working on it this week, and I am hoping to wrap up the issue today. It will then have to go through our normal process of review and QA. But we are hoping to have this fix ready for and included in the next release.

**Comment by tomjscox** [comment] 2018-11-14 09:13
Thanks for this this follow up. For the time being I just can't let OSF.io connect to Dataverse to check how things are running now; this might be a problem with osf so I'll check later and come back to this issue if necessary.

**Comment by kcondon** [comment] 2018-11-26 23:53
-API returns querying root in 21s.
-Exception thrown when trying to load some manage permissions pages but not others in the same hierarchy. (PSI-EastAfrica, PSI-LatinAmerica-Caribbean fail, PSI, angola, haiti succeed).
```
[2018-11-26T18:22:56.185-0500] [glassfish 4.1] [WARNING] [AS-EJB-00056] [javax.enterprise.ejb.c
ontainer] [tid: _ThreadID=263 _ThreadName=http-listener-1(233)] [timeMillis: 1543274576185] [le
velValue: 900] [[
  A system exception occurred during an invocation on EJB GroupServiceBean, method: public edu.
harvard.iq.dataverse.authorization.groups.Group edu.harvard.iq.dataverse.authorization.groups.G
roupServiceBean.getGroup(java.lang.String)]]

[2018-11-26T18:22:56.185-0500] [glassfish 4.1] [WARNING] [] [javax.enterprise.ejb.container] [t
id: _ThreadID=263 _ThreadName=http-listener-1(233)] [timeMillis: 1543274576185] [levelValue: 90
0] [[
  
javax.ejb.TransactionRolledbackLocalException: Exception thrown from bean
        at com.sun.ejb.containers.EJBContainerTransactionManager.checkExceptionClientTx(EJBCont
ainerTransactionManager.java:662)
        at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTrans
actionManager.java:507)
        at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4566)
        at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2074)
        at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2044)
```

**Comment by landreev** [comment] 2018-11-30 21:40
Please re-test; the issues outlined in your last comment should be fixed; with the exception of "Assigning role to unpublished dv grants access but does not index ..." - but based on our discussion and testing, it appears that it may be a pre-existing condition.

**Comment by kcondon** [comment] 2018-12-03 21:11
OK above issues are either fixed or were preexisting issues. New issues found so far:
- an individual user in an explicit group within an explicit group assigned a role does not result permission granted to that individual. it does work on /develop.

**Comment by landreev** [comment] 2018-12-06 18:36
OK, I'm done with my testing too. 
The only thing that this issue needs is testing of permissions derived from Shib auth. Which we currently cannot do because we don't have a test system with Shib working. 
This is handled in a new issue #5369. 
But this is just to make it clear that this is a hard dependency - we cannot finish QA of this issue, until #5369 is resolved.

**Closed** 2018-12-11 22:10 UTC
Labels: Feature: Performance & Stability, Status: QA

**Comment by pdurbin** [comment] 2019-01-09 23:17
Now that Dataverse 4.10.1 has been deployed to Harvard Dataverse I tried the OSF test again and found that the OSF interface spun for about 60 seconds when I selected "Harvard Dataverse" and then eventually changed from "Retrieving datasets" to "No datasets available" (which makes sense since I don't have any datasets in the "root" dataverse of Harvard Dataverse). Here's a screenshot:

<img width="1790" alt="screen shot 2019-01-09 at 6 11 36 pm" src="https://user-images.githubusercontent.com/21006/50935524-4a606200-143a-11e9-8a4c-8c70688f4efc.png">

I can't quickly determine what version of OSF I'm testing with but based on GitHub releases I assume it's version 18.9.9.

**Comment by shlake** [comment] 2019-01-10 14:05
Thanks @pdurbin 
I'll take a look at this early next week. I am doing a webinar for TDL on OSF/Dataverse integration (on Jan. 22nd) and was going to use demo.dataverse.org, which I see is also at 4.10.1. And I see with a new home page.
