### ISSUE TITLE
API: Create mechanism to shut off API access selectively and globally.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1103] opened 2014-11-10 17:53 UTC
APIs may expose the service to sharp load spikes due to batch/ programmatic nature. Also, potential malicious use.

So, it would be good to have a way to turn off API access entirely or selectively, based on UI, or trusted user/hosts.

**Comment by kcondon** [comment] 2015-08-26 21:07
@scolapasta This wasn't designed or implemented, right?

**Comment by kcondon** [comment] 2015-09-03 15:30
Passing back as a feature request.

**Comment by djbrooke** [comment] 2020-07-24 21:17
Closing as a duplicate of #1339, which has some good discussion.

**Closed by djbrooke** 2020-07-24 21:17 UTC
Labels: Feature: API, Type: Suggestion, User Role: Sysadmin
