### ISSUE TITLE
Metadata fields on the "edit metadata" pages of some datasets are displayed out of order

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#3685] opened 2017-03-10 20:54 UTC
This issue collects several instances of metadata fields within compound metadata fields being displayed out of order on edit dataset metadata pages.

When author metadata fields were added in the citation metadata block of [this dataset](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/EYMZZX&version=DRAFT) (it's unpublished, so you'll need admin access to see it), the order of the fields are different than normal ("Name," Affiliation," on the first row, "Identifier Scheme," and "Identifier" on the second row).

![screen shot 2017-03-10 at 10 38 06 am](https://cloud.githubusercontent.com/assets/18374574/23802068/2ebd4ad8-0580-11e7-97c4-8e38abd5142c.png)

Unfortunately, I'm not able to reproduce this bug, either in other existing or new datasets or even in this dataset: If you press the plus sign to add another author for that dataset, the order of fields will be correct.

**Comment by pdurbin** [comment] 2017-03-10 20:56
Huh, weird. So on https://dataverse.harvard.edu as of v. 4.6 build 62-c913662.

**Comment by jggautier** [comment] 2017-03-10 21:03
Ah, yes. The current build of Harvard Dataverse. Also, those fields had values before they were saved as a draft. (I just removed them to take the screenshot.)

**Comment by sbarbosadataverse** [comment] 2017-09-26 17:16
@jggautier  this issue also happened yesterday for Michelle and I, but in the producer field. And the info for logo url we were trying to add for the fields in question, would not work: see attached images. Same dataset, going in to edit mutiple times in one sitting: 


dataset: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi%3A10.7910%2FDVN%2F22795

same dataset, happened when Michelle did the editing and when I did the editing


![pastedimage 3](https://user-images.githubusercontent.com/8322346/30873606-d0c54a14-a2bb-11e7-87d8-997e9d5c97f4.png)


![pastedimage 2](https://user-images.githubusercontent.com/8322346/30873613-d5290e74-a2bb-11e7-8e4e-2be717a6a5c7.png)

<img width="1566" alt="screen shot 2017-09-25 at 6 06 58 pm" src="https://user-images.githubusercontent.com/8322346/30873626-db2e9b18-a2bb-11e7-9e88-b2cb0978ab47.png">

**Comment by jggautier** [comment] 2017-09-26 17:25
Thanks @sbarbosadataverse! Reopening this issue now that there's a dataset where the bug seems to be reproducible.

**Comment by sbarbosadataverse** [comment] 2017-09-26 17:42
@jggautier  please note that where the fields do shift, the logo url is not working when you hit save. I think these issues are related.

**Comment by jggautier** [comment] 2018-02-27 14:53
Another example of metadata fields being displayed out of order. This is the Related Publication fields on [this dataset](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/1ZPOPB) (you'll need super access to see the fields) on Harvard Dataverse 4.8.4, on MacOS 10.13.3 on Chrome (version 64.0.3282.167) and Firefox (58.0.2 (64-bit))

![screen shot 2018-02-27 at 9 51 49 am](https://user-images.githubusercontent.com/18374574/36735327-eb428846-1ba3-11e8-92f0-f13c6bba0bd5.png)

(The ID Type and ID Number fields are normally next to each other.)

**Comment by qqmyers** [comment] 2020-09-20 13:41
DatasetFieldCompoundValue lists its children  in order by type:  @OrderBy("datasetFieldType ASC") - are the issues being seen consistent with this? (with a quick look above, it looks like filled in fields come first with 'text' fields before 'urls').

**Comment by qqmyers** [comment] 2020-09-20 14:44
Looking in dataset.xhtml and metadataFragment.xhtml the compound field values are retrieved via compoundValue.displayValueMap.entrySet().toArray() - so the order that appears depends on the order returned by the LinkedMap class, which is insert-ordered. It's created in a loop going through the children that should be DatasetFieldType ordered. I don't see anywhere that the displayOrder is used, so it probably 'works' only when the display order and type ids are in the same order. 

I think that would explain https://groups.google.com/d/msgid/dataverse-community/2cfe6e61-50a2-4a09-b62c-85124cdc91dcn%40googlegroups.com?utm_medium=email&utm_source=footer , but I'm not sure if it explains the examples above. For those, could different datasets be using different DatasetFieldTypes (i.e. multiple db entries for the same term from some metadatablock insert issues over time.) Something like that, with the id-based ordering could perhaps cause datasets created at different times to behave differently.

**Comment by qqmyers** [comment] 2020-09-20 15:00
Will test a one-line fix to order the child datasetfields by display order and will create a PR if that works.

**Comment by jggautier** [comment] 2020-09-22 16:10
Thanks @qqmyers! I checked the datasetfieldtype table in Harvard Dataverse's database and didn't see duplicate entries (I spent extra time looking for duplicates of the producer, author and related publication fields referenced in earlier comments in this GitHub issue). But I'm attaching the table (all of the rows and most of the columns) just in case you'd like to check it out: [datasetfieldtype_table_harvard_dataverse.txt](https://github.com/IQSS/dataverse/files/5262616/datasetfieldtype_table_harvard_dataverse.txt)

Should the #7277 PR really close this GitHub issue?

On the other hand, I can't reproduce the problems when looking at the edit metadata pages of the datasets I wrote about in this Github issue. So maybe the problem was unintentionally fixed between Dataverse v4.6 and v5.0, and this issue should be closed.

**Comment by qqmyers** [comment] 2020-09-22 16:24
Hmm. The examples above were suspicious in that it looked like TEXT fields were showing before URIs which were before empty fields, so perhaps somewhere after 4.6 the display changed. 

As for closing this issue - up to you guys. I guess it would be cleaner to close this as not reproducible and then open a compound filed ordering one that my PR can fix - I'm happy to rename the branch/redirect the PR if you want to do that.

**Closed** 2020-09-22 20:21 UTC
Labels: Feature: Metadata, Type: Bug
