### ISSUE TITLE
Assign Role: Assigning roles to user does not update index.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1901] opened 2015-04-06 22:56 UTC
I assigned both shib user and built in user admin role at root.
I noticed they had access to everything root admin had but could not see existing unpublished dvs, ds, or files. However, when as root admin, I created new unpublished dvs, ds, files, they could see the new ds and files but not the dvs. Likewise removing role does not remove the indexed but no longer accessible ds and files.

So there appears to be 2 issues:
1. when assigning greater permissions, index is not updated for existing objects
2. unpublished dv's are not visible to accounts with view unpublished dv permission.

**Comment by scolapasta** [comment] 2015-04-07 16:40
@pdurbin can you look at 1, and I'll see what the issue is with 2?

**Comment by scolapasta** [comment] 2015-04-07 17:10
The answer to 2. Currently we don't have inheritance of permissions of at the dataverse level. ViewUnpublishedDataverse does not mean you get to view children, just if that dataverse is unpublished.

So you would not get to view any child unpublished dataverse unless you had that permission at the child. This is different with Datasets, because Datasets do inherit permissions from the Dataverse. So having ViewUnpublishedDataset is meaningless at the dataverse, but it is inherited by each dataverse.

I understand that this is confusing - we should think of a way to make this make more sense to the end user - though much of that would be for 4.0. 

We could cosnider changing the Permission Name to ViewThisUnpublishedDataverse?

**Comment by pdurbin** [comment] 2015-04-07 20:38
> ViewThisUnpublishedDataverse

That **would** be more accurate. The description currently reads "View an unpublished dataverse". A more accurate description would be "View this unpublished dataverse and its datasets but not its child dataverses (if any)." It gets a little verbose!

As I was telling @kcondon my rule of thumb is that a card shouldn't exist if clicking on it means you are prompted to log in. So I'm not going to touch how **dataverses** are indexed. Child dataverses are their own islands of permissions (detached from their parents) because permissionRoot is hard-coded to true. See also https://github.com/IQSS/dataverse/issues/57#issuecomment-65273753

There **is** something fishy going on with datasets, however. After a role is assigned I do believe cards should be shown when they aren't. I was able to reproduce this locally.

**Comment by pdurbin** [comment] 2015-04-09 01:42
60e82b1 seems like a good fix and I went over it with @scolapasta 

Datasets that are direct children of the root dataverse were not being indexed when roles were granted. This should be fixed.

Because there is no inheritance of permissions, we switched away from using a Solr query to determine the subtree of candidates for re-indexing. We are querying the database instead.

Passing to QA.

**Closed** 2016-01-12 19:05 UTC
Labels: Component: UX & Upgrade, Priority: Critical, Status: QA, Type: Bug
