### ISSUE TITLE
Publish Dataverse: Unpublished state is not refreshed after publishing dataverse.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1232] opened 2014-12-10 16:46 UTC
Using Chrome Version 39.0.2171.71 m

When I published a dataverse, there is not message to indicate anything happened and the dataverse still says unpublished, though refreshing the page shows it is published.

**Comment by mheppler** [comment] 2015-01-07 20:07
The duplicate #1231  was closed.

**Comment by esotiri** [comment] 2015-01-07 20:10
duplicate of #1231 closing

**Closed by esotiri** 2015-01-07 20:10 UTC
Labels: Component: UX & Upgrade, Priority: Medium, Status: Dev, Type: Bug
