### ISSUE TITLE
BARI - Scheduled Processing/Deposit

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3719] opened 2017-03-24 18:45 UTC
dependency: https://github.com/IQSS/dataverse/issues/3718

---

In collaboration/consultation with the Dataverse team, Ista of the Data Science team, 
and Christopher Gandrud of Zelig, a prototype script/program will be created to:

## Step 1 (may be manual)

1. Pull the latest data from the City of Boston building permits API*
1. Deposit the file into a Dataverse Dataset

### What the code should do

1. Pull the latest data from the City of Boston building permits API
   - These data rows contains an ```id```.  
   - Latest data:  where ```id``` > ```last id retrieved```
1. Append the new data to the file deposited in Step 1 above
    - To decide: May involve retrieving the existing file from Dataverse--or having the previous file in storage to this process accessible 
1. Via the Dataverse API, Replace the existing Dataverse file with the new file
1. Via the GitHub API (or similar method), get the latest version of this "BARI Boston Building Permit code" and also deposit in Dataverse

- Notes
  - API endpoints, Dataset location, frequency of script run, etc will be in a separate google doc when this ticket is estimated
  - This process should be in a place where it can run as a scheduled task or cron
  - The "BARI Boston Building Permit code" (and updates to it) will initially be kept in a Github repository within IQSS.  Later, this may move to a BARI or Northeastern Urban Informatics repository

### Availability of code

As mentioned in the steps above, this code will be available in Github. 

In addition, stripped of any API tokens, etc, the code should also be in Jupyter notebook format--assumedly within the same github repo.

### Future notes

Once this is running, the next step is to transition from:

**Current process:** (this ticket) 
  1. Retrieve data
  1. Append data
  1. Deposit raw data and code

**Next Step:** (future ticket) 
  1. Retrieve data
  1. Append data
  1. **Data processing** via custom R scripts**
  1. Deposit raw data and code
  1. **Deposit** up to 3 output files from the Data processing step

The "Next Step" will make this more of a pipeline process. 
- For example, the overall process may be run via python scripts while the data processing part is interchangeable with R, python, etc.  (Currently all of this is open for discussion)

**Comment by mheppler** [comment] 2018-05-21 16:15
Closing as a duplicate of _Create a configurable, scheduled process for the BARI researchers to process and deposit ("stream") Analyze Boston data into their dataverse automatically. #4530_ which is currently in development.

**Closed by mheppler** 2018-05-21 16:15 UTC
Labels: Feature: Code Infrastructure, Feature: WorldMap & GeoConnect
