### ISSUE TITLE
Make retrieval of Dataset Versions uniform

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#1816] opened 2015-03-31 18:47 UTC
The Dataset page and the API retrieve dataset versions differently in some cases.  Review how each is done and implement the best version across the application.

**Comment by mheppler** [comment] 2021-02-11 16:06
Closing as duplicate of **Cleanup: initDatasetFields in DatasetVersion and DatasetVersionUI #1241**, moving comment above over there.

**Closed by mheppler** 2021-02-11 16:06 UTC
Labels: Feature: Code Infrastructure, Hackathon: Technical Debt
