### ISSUE TITLE
Hook up download All button

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#2026] opened 2015-04-15 22:06 UTC
Rather than use a list of id's, in this case, the access api should accept a datasetversion.

**Comment by eaquigley** [comment] 2015-06-25 15:52
Should we have a limit to how many files a user can download? How do we display this in the UI?

Need to review during a UI/UX meeting.

**Comment by mheppler** [comment] 2015-06-25 15:54
Related to/duplicate of #2205 #1476 #639 #1988 #1951 and probably a few more that involve files and checkboxes and "select all" on the dataset.

**Comment by eaquigley** [comment] 2015-09-11 14:59
@kcondon can you close this ticket please? download all is not happening based off the mockups: https://iqssharvard.mybalsamiq.com/projects/filesprovenancefacetsfilter-dataverse40/Dataset%20-%20Files%20-%20Selected since there is a select all files check box.

**Comment by kcondon** [comment] 2015-09-14 19:18
Closing this ticket since this will be implemented as a top level download button that downloads selected files.

**Closed by kcondon** 2015-09-14 19:18 UTC
Labels: Status: QA
