### ISSUE TITLE
Guestbook: Error inserting into guestbook errors appearing in production logs

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2712] opened 2015-10-30 16:18 UTC
Was not able to reproduce in test or production. Thought it may have been related to #2703 but was not able to reproduce it.

Local Exception Stack:
Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: null value in column "datafile_id" violates not-null constraint
  Detail: Failing row contains (2116566, Download, , , Guest, , 2015-10-29 22:39:57.297, edu.harvard.iq.dataverse.DataverseSession@40a30e5b, null, null, 54769, null, 1)
.
Error Code: 0
Call: INSERT INTO GUESTBOOKRESPONSE (DOWNLOADTYPE, EMAIL, INSTITUTION, NAME, POSITION, RESPONSETIME, SESSIONID, AUTHENTICATEDUSER_ID, DATAFILE_ID, DATASET_ID, DATASETVE
RSION_ID, GUESTBOOK_ID) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        bind => [12 parameters bound]

**Comment by landreev** [comment] 2015-10-30 17:04
To add to the ticket what I said earlier: 
We had been seeing these errors in the logs before the upgrade, throughout the 4.2 run (and maybe earlier). There's some, still anecdotal evidence, that these are thrown when the app is already in the process of dying/otherwise in a bad state. 
So my working guess that this is not necessarily a bug in the page. But one of the symptoms of the app dying. 
We've all seen some pages behaving in a weird way when the app is in a bad state. Some half-rendered elements, action clicks not producing the desired effect, etc. In this case - maybe the TOU popup can't do what it needs to do, so a broken download request is passed to the page, with a NULL for file.

All that said, 

a) more defensive code inside the page could help; instead of a long exception in the logs we could be getting a brief, but informative messages. 
and 
b) I'll try to explore an alternative theory - that it is a page state that one can enter in a reproducible way. For example, open the page on a restricted dataset, wait for the session/view to expire, try to download something?

**Comment by lwo** [comment] 2015-12-13 22:46
I see the error as well in a clean install of dataverse 4.2.1. The action that triggers it in this case is a download of dataset files as a zip. The latter works, but throws a database error on the side:

Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "datafile_id" violates not-null constraint
  Detail: Failing row contains (23, Download, , , Guest, , 2015-12-13 23:43:45.339, edu.harvard.iq.dataverse.DataverseSession@511ee918, null, null, 74, null, 1).
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2101)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1834)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:510)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:386)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:332)
	at sun.reflect.GeneratedMethodAccessor684.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.postgresql.ds.jdbc23.AbstractJdbc23PooledConnection$StatementHandler.invoke(AbstractJdbc23PooledConnection.java:453)
	at com.sun.proxy.$Proxy375.executeUpdate(Unknown Source)
	at com.sun.gjc.spi.base.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:125)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:890)
	... 140 more

**Comment by scolapasta** [comment] 2015-12-13 22:54
@kcondon can you verify we closed this with the most recent change to 4.2.2?

**Closed** 2015-12-14 19:43 UTC
Labels: Component: Code Infrastructure, Priority: Medium, Status: QA, Type: Bug
