### ISSUE TITLE
Tabular File Ingest: No message indicating page will refresh on its own, or if user needs to manually refresh

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#1798] opened 2015-03-30 15:39 UTC
Also don't see the "ingest" note until you click save---in 3.6 this is clear before hitting save--what is the expected behavior? Because before hitting save I thought perhaps the system didn't identify my file as subsettable.

![hwtsiuvvfswodhrxsp47dwn11aikzkbj-3siw6psrtq](https://cloud.githubusercontent.com/assets/8322346/6899880/20bba4a0-d6d1-11e4-9908-93a85ba40d99.png)

**Comment by sbarbosadataverse** [comment] 2015-03-30 15:43
So it did not refresh on its own--had to manually refresh to notice it had completed.

**Comment by mheppler** [comment] 2016-09-02 16:59
Related to/duplicate of:  File Upload: For slow uploading files, add note to files tab not to move away from page or it will halt upload. #3279 ; and: Ingest Dataset File: provide more guidance and information about ingestion process for large files #2204

**Comment by mheppler** [comment] 2018-04-02 19:13
Added a strikethrough to my comment above because I no longer believe those are related/dup issues.

Closing this issue in favor of **Dataset Tabular File Ingest - Displaying both "success" and "ingest in process" message is confusing/wrong #2709** which is clearer. Will add more information there in a new comment.

**Closed** 2018-04-02 19:17 UTC
Labels: Feature: File Upload & Handling, Status: UX & UI, Type: Feature, Type: Suggestion, User Role: Depositor
