### ISSUE TITLE
Editing not saving: Page doesn't save then removes newly added metadata values, and gives error for missing value (that was already there prior to hitting save)

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2436] opened 2015-08-05 21:54 UTC
You edit metadata, select save, spinning blue circle spins then stops and remains on editing screen
You hit save again, and blue spinning then error appears for missing required value (but screen shot shows the value was there during the first save attempt).
You add value again, and hit save and nothing happens.

![screen shot 2015-08-05 at 5 51 53 pm](https://cloud.githubusercontent.com/assets/8322346/9098943/ebada626-3b9a-11e5-89af-21021b2657e4.png)

![screen shot 2015-08-05 at 5 58 33 pm](https://cloud.githubusercontent.com/assets/8322346/9098944/ee90d19c-3b9a-11e5-8356-48d70f4457c6.png)

![screen shot 2015-08-05 at 5 58 47 pm](https://cloud.githubusercontent.com/assets/8322346/9098948/f0ae623c-3b9a-11e5-8be5-021295ab6e43.png)

**Comment by pdurbin** [comment] 2016-01-15 18:01
> You edit metadata, select save, spinning blue circle spins then stops and remains on editing screen
> You hit save again

Obviously the app must have been in a strange state if you click "Save" but the page remains on the "edit" view. (My guess is that was probably an exception was thrown.) You shouldn't have to hit "Save" a second time.

I checked with @sbarbosadataverse and am closing this issue based on what she had to say:

"I think this was one of those bugs that we won't be able to reproduce....we have many of these...I think we can close it and say we will open again if it happens again...I haven't seen it since i reported the ticket"

**Closed by pdurbin** 2016-01-15 18:01 UTC
Labels: Priority: Critical, Type: Bug
