### ISSUE TITLE
Metadata Fields: Revisit Display of Compound Fields

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1319] opened 2015-01-12 21:26 UTC
From General UI Doc: https://docs.google.com/document/d/1VXac5Eqx1LDVWvMogf4EYVfxv-9gIavgAnL4x_esiTI/edit 

@mcrosas comment: Revisit display of metadata fields that have subfields (such as author). My suggestion is to not display the name of the subfields (Name, Affiliation, etc) because they become obvious when the value is displayed and it would make the display more concise.

@mheppler comment: I really like this suggestion. Makes perfect sense. Curious how this would work with dynamic fields though. Author is easy, where as, we'd need a custom layout format for each and every custom compound field.

**Comment by mheppler** [comment] 2015-01-14 17:33
Related to #656 -- maybe even a duplicate.

**Comment by mheppler** [comment] 2015-01-16 15:23
Also related to #207.

**Comment by scolapasta** [comment] 2015-01-23 23:21
Merging the details of #1258 

The issue is how we handle the display of compound fields when some of the children are empty (in this case e-mail is always hidden and the other fields are empty.

**Comment by scolapasta** [comment] 2015-01-23 23:23
Also related: #1246

**Comment by scolapasta** [comment] 2015-01-30 19:53
Added infrastructure for this. Will now display compound values per the value in displayFormat. 

Passing to @posixeleni to work with @mheppler and deciding what the formats should be and adding to the TSV files.

**Comment by scolapasta** [comment] 2015-01-30 19:58
Screen shot of some examples:

![displayformatexamples](https://cloud.githubusercontent.com/assets/4268292/5982373/38632e3a-a890-11e4-8721-273838da0232.jpg)

Us the displayFormat of the parent field if you want a separator (like a comma); otherwise just fill in child fields with using #VALUE, #NAME and formatting.

(#EMAIL is also provided for now for hidden e-mail message)

**Comment by posixeleni** [comment] 2015-02-02 17:35
Listed below are ALL metadata blocks that have compound fields and the names of the compound fields (parent). As you can see below the Citation block has the most compound fields and will be the most important block to have display properly in 4.0

**Citation**
-otherId
-author
-description
-keyword
-topicClassification
-publication
-producer
-contributor
-grantNumber
-distributor
-timePeriodCovered
-dateOfCollection
-series
-software

**Geospatial**
-geographicCoverage

**Social Science**
-targetSampleSize
-socialScienceNotes

**Astronomy**
-coverage.Spectral.Wavelength
-coverage.Temporal
-coverage.RedshiftValue

**Comment by posixeleni** [comment] 2015-02-02 17:39
@mheppler for you to look at how Gustavo and I tweaked the display of the compound fields I have just checked in an updated citation.tsv in a new branch 1319-compound-fields

Would you please run a build of this branch and let me know what you think of the display of the compounds and let me know if you want me to tweak.

Also @scolapasta for the display of Producer and Distributor logos I put in some HTML for <img> is this ok?

**Comment by posixeleni** [comment] 2015-02-04 20:33
Will check-in fixes to citation.tsv
- Spacing issue with the commas in the Related Publication field is my bad and I can fix that easily with the next build by adding the comma at the parent rather than each compound field.
- Spacing issue between the two Distributors (sorry said authors earlier): this may need to be a hack for now (add <br/> at the end of the logo URL HTML. But not sure how to solve the spacing issue for Related Publication:
![image](https://cloud.githubusercontent.com/assets/5013837/6049135/0de1c3a0-ac83-11e4-88a1-a045cc2b478e.png)
- Logo URL Display issue: Mike suggested I add this in fieldFormat for now: <img src="#VALUE" alt="#NAME" class="metadata-logo"/><br/> so we can resolve the image sizing issue for now. He will add CSS in the stylesheet to handle this.

**Comment by mheppler** [comment] 2015-02-05 21:41
"Let me think about it another day." -- @scolapasta

**Comment by eaquigley** [comment] 2015-02-24 18:35
@mcrosas has suggested a better way to display compound subfields in the metadata tab to add the names for some of the subfields before the value. @mcrosas and @posixeleni will review this when @posixeleni is back in the office.

**Comment by posixeleni** [comment] 2015-02-25 20:41
Meeting with Merce by the end of this week to finalize this.

**Comment by posixeleni** [comment] 2015-03-05 18:32
Waiting to meet with Merce to go over this. Sent a proposed revision already:

![image](https://cloud.githubusercontent.com/assets/5013837/6511649/1b3ab212-c33c-11e4-89d8-04f4d9fac5a3.png)

**Comment by posixeleni** [comment] 2015-03-05 22:56
Put in these compound field display changes into a separate branch since they are tied to #1597 which needs a schema.xml and db drop. Will move this to QA when that ticket has been completed.

**Comment by pdurbin** [comment] 2015-03-06 17:26
@posixeleni per my comment at https://github.com/IQSS/dataverse/issues/1597#issuecomment-77598311 I merged your change to master and no schema.xml change is required so I'll move this to QA.

**Comment by posixeleni** [comment] 2015-03-20 18:33
Now working as expected. Closing.

**Closed by posixeleni** 2015-03-20 18:33 UTC
Labels: Component: UX & Upgrade, Status: QA
