### ISSUE TITLE
Update Display Logic for Add Data button from My Data page

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse#6951] opened 2020-05-30 08:54 UTC
We have recently been contacted by quite a few depositors who clicked the _Add Data_ button, but got this error message:

> Not Authorized - You are not authorized to view this page. If you believe this is an error, please contact DataverseNO Support for assistance.

I found out that this happens when they are on the _My Data_ page, i.e. they have selected _My Data_ in the user account menu in the top right section (dataverseuser.xhtml?selectTab=dataRelatedToMe):
![image](https://user-images.githubusercontent.com/21955790/83323967-54b71200-a262-11ea-82b4-98c945122a3d.png)

On the _My Data_ page, they see a list of datasets and dataverses they have depositing access to. But on this page, also the _Add Data_ button is displayed. And also, the button displays the _New Dataverse_ option in addition to the _New Dataset_ option, although common depositors in our repository do not have the _Add Dataverse_ option in any collections. When depositors click _Add Dataset_ or _Add Dataverse_, they get the error message pasted above.

I'd like to suggest two changes:

1. Remove the _Add Data_ button from the _My Data_ page, so that depositors do not have this option unless they choose a dataverse they have deposit access to.
2. By default list dataverses before datasets on the _My Data_ page, so that depositors easily find to the repository/-ies they have deposit access to.

Thanks!

**Comment by AACGSR** [comment] 2020-08-18 16:06
@RightInTwo @brittajurtz

Thanks for creating this issue, Philipp!

We have a similar issue, where people clicking on the Navbar's Add Data button always get an error message (since it's linked to creating in the root dataverse by default) instead of being able to choose from host dataverses where they have sufficient permissions. 
If they don't have sufficient permissions to any dataverses, they shouldn't see the button at all.

@pdurbin @djbrooke is there any short term solution to this in sight?

**Comment by djbrooke** [comment] 2020-08-18 16:45
@AACGSR - I believe the similar issue that you describe has been resolved in #6741, which will be included in the next release

**Comment by scolapasta** [comment] 2020-08-18 20:40
Right, Navbar button has new (better) logic and works correctly. I just confirmed and this is not happening this way on the My Data page, so we'll need to modify that logic. (but should be easy, since we have it for the nav bar)

**Comment by djbrooke** [comment] 2020-09-15 19:22
Closing in favor of #7269

**Closed by djbrooke** 2020-09-15 19:22 UTC
