### ISSUE TITLE
"Submitted for Review" message appearing on published versions of datasets can confuse dataset contributors and curators/admins

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#4403] opened 2018-01-09 22:32 UTC
After this workflow...

- The depositor creates a dataset and submits it for review
- the dataset is published by a curator
- the depositor edits the dataset and submits a second version of the dataset for review

... the yellow "Submitted for Review" message exists on all versions of the dataset, although only the draft version is actually submitted for review. The first version is already published/publicly accessible.

The message appearing on pages of published dataset versions can be confusing to the researcher who's deposited the dataset because it looks like the dataset has never been published.

It can also be confusing to the curator who lands on an already published version of the dataset, but sees the "Submitted for Review" message, and doesn't know how to publish or return the dataset. (Doesn't know to click on the draft version link in the versions tab.)

This message is also displayed to users who have no access to the dataset, including guest users not logged in.

Message on draft version page of dataset:
<kbd>![in_review-draft_version](https://user-images.githubusercontent.com/18374574/34746663-d8070ef8-f562-11e7-8a32-1e311b06482c.png)</kbd>

Message on first published version of dataset:
<kbd>![in_review-published_version01](https://user-images.githubusercontent.com/18374574/34746675-e0b30264-f562-11e7-9b21-aa3fc36ea852.png)</kbd>

This is seen on Harvard Dataverse and demo.dataverse running 4.8.4.

**Comment by djbrooke** [comment] 2018-02-23 19:17
Thanks @jggautier. This was noticed during load testing for the move to AWS.

**Comment by mheppler** [comment] 2018-02-23 19:21
This message is also displayed to user without any access related to the dataset, as well as guest users not logged in.

**Comment by pdurbin** [comment] 2018-02-26 19:29
I assume that this used to work fine but a regression slipped in. @jggautier and @mheppler seem to be talking about version 4.8.4, which is what's in production as of this writing.

**Comment by jggautier** [comment] 2018-07-10 17:34
@djbrooke, @mheppler, @sbarbosadataverse, @dlmurphy and @TaniaSchlatter discussed this briefly and agreed that everyone (anyone logged out or logged in with permissions on the dataset) should see the message only on the draft version of the dataset. Already published dataset versions should not have this message.

This issue was prompted by a support ticket from a dataverse curator who landed on an earlier, already published version of a dataset, saw the "Submitted for Review" message, and didn't know how to publish or return the dataset. He didn't know to click on the draft version link in the versions tab. I think our proposal to remove the message from all versions of the dataset that this curator sees would not help him realize that he needs to navigate to the draft version of the dataset in order to publish or return to it to the author. But we agreed that this scenario happens very rarely - we have no evidence that curators often land on older versions of datasets whose drafts they need to publish or return to the author - so it doesn't need to be considered at this point.

**Comment by pdurbin** [comment] 2018-11-13 17:31
@matthew-a-dunlap and I just discussed this regression. In my case I wasn't logged in but I can see the "Submitted for Review" message:

![screen shot 2018-11-13 at 12 30 56 pm](https://user-images.githubusercontent.com/21006/48431572-073a8900-e740-11e8-889d-5351aa30de29.png)

**Comment by mheppler** [comment] 2018-12-03 22:17
To solve the issue with "Submitted for Review" alert msg's being displayed to guests/or users without permsions, I added `canUpdateDataset()` render logic to the lock msg section of the `DatasetPage.java` bean.

```
        if (dataset.isLocked() && canUpdateDataset()) {
            ...
        }
```

In that `if` statement, there are dataset lock warning msg's for multiple workflows, including, `DatasetLock.Reason.Workflow`, `DatasetLock.Reason.InReview`, `DatasetLock.Reason.DcmUpload`, and `DatasetLock.Reason.pidRegister`. Those locks msg are included on more than just the draft version of a dataset, because there are "Edit" and "Upload Files" btn's on all versions that are disabled while the dataset is lock.

Because of these other workflows, I added render logic that determines if you have permission to see these buttons, and not the render logic that only shows the msg while viewing a draft version of a dataset.

I have discussed with @jggautier and @dlmurphy we determined that if we improved the msg text, it should reduce confusion regarding the draft version vs older published versions.

![screen shot 2018-12-03 at 5 13 53 pm](https://user-images.githubusercontent.com/687227/49404903-d508bf80-f71e-11e8-80e9-3c5bc5c4e92e.png)

Also included in this fix are improvements to the writing format and style of the other lock msg's. Those changes included are:

![screen shot 2018-12-03 at 5 15 55 pm](https://user-images.githubusercontent.com/687227/49404979-1e590f00-f71f-11e8-8e80-3ef91ca3894e.png)

![screen shot 2018-12-03 at 5 15 15 pm](https://user-images.githubusercontent.com/687227/49404995-27e27700-f71f-11e8-9891-2032389b90b4.png)

![screen shot 2018-12-03 at 5 14 54 pm](https://user-images.githubusercontent.com/687227/49404983-231dc300-f71f-11e8-9e22-86f6e9bbd0fb.png)

**Comment by dlmurphy** [comment] 2018-12-04 16:48
Suggestions for revisions to the above messages, based on input from @scolapasta and @mheppler:

**Dataset Locked** -- This dataset is locked until publication.

**File Upload in Progress** -- This dataset is locked while its data files are being transferred and verified.

**Publish in Progress** -- This dataset is locked while its file persistent identifiers are being registered or updated.

**Comment by kcondon** [comment] 2018-12-13 22:45
The submit for review banner issue is fixed but the in review tag is broken when viewed from the dataverse page:
![Screen Shot 2018-12-13 at 5.37.20 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5798d98d18ccf10e00ce215e/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216455f06b7191a37df1112c4f5d5f5ecc3c4a4356bcbbd671f3e57862804e0ee8856f5c75903d47afed8a4bec04ec208b4b8de7bddb1ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df24fe64954a5133664e3732431.png)

**Comment by mheppler** [comment] 2018-12-18 15:22
@kcondon I will stop by to review the screenshot above with you, but I believe this is a result of an old javascript cache in your browser. I have pulled this branch and tested again locally and all looks kosher here.

![screen shot 2018-12-18 at 10 22 36 am](https://user-images.githubusercontent.com/687227/50163633-dbff0880-02ae-11e9-998b-90ec405830e8.png)

Submitted for Review warning alert render logic:
- Only display to any users with edit permissions
- Display it on all dataset versions (with msg text to indicate it is the draft version that is under review)
- Lock dataset (edit, upload, etc) for all users except those with publish permissions

**Comment by sekmiller** [comment] 2018-12-18 18:39
@kcondon We found the cause of the weird banner on the home page, so I think this is ready for QA. Also, re-merged with the latest from Dev.

**Closed** 2018-12-19 17:49 UTC
Labels: Feature: In Review Workflow, Feature: Messaging, Status: QA
