### ISSUE TITLE
Add creative commons license info for CC0

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#21] opened 2014-07-09 15:34 UTC
---

Author Name: **Gustavo Durand** (@scolapasta)
Original Redmine Issue: 1828, https://redmine.hmdc.harvard.edu/issues/1828
Original Date: 2012-02-16

---

We need to evaluate with Merce what this entails; how it interacts with Terms of Use, etc.

**Comment by sekmiller** [comment] 2015-01-05 19:08
Basic functionality completed

**Comment by kcondon** [comment] 2015-01-13 16:44
This is effectively a dupe of the other TOU ticket, closing.

**Closed by kcondon** 2015-01-13 16:44 UTC
Labels: Priority: Medium, Status: Design, Status: QA, Type: Feature
