### ISSUE TITLE
How many datasets do I have? Are these 163 more things really My Data?

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#5880] opened 2019-05-23 15:54 UTC
From discussion in #3038 I know we don't plan to fix anything in "My Data" any time soon but I was just talking to @TaniaSchlatter and @djbrooke about #5874 and I'd like to point out what I consider to be a usability problem or at least a point of confusion.

When I first encounter the term "My Data" after clicking my name in the top right corner like this...

![Harvard_Dataverse_-_2019-05-23_11 39 40](https://user-images.githubusercontent.com/21006/58266491-bd1a0c00-7d4f-11e9-8f25-abda43c55b53.png)

... I'm expecting to see my stuff, my data. However, I see a bunch of stuff I've never heard of:

- The National Labor Force : SAKERNAS, 2016
- Italians to America Passenger Data
- CDP Public Scores Data
- CDP Forests Data
- **and a button to see the next 10 of 163 more items like this, stuff I've never heard of**.

Here's how it looks:

![Account_-_Harvard_Dataverse_-_2019-05-23_11 39 57](https://user-images.githubusercontent.com/21006/58266490-bd1a0c00-7d4f-11e9-95b0-02e685ad7648.png)

I find this very confusing and disorienting. I thought this was suppose to be my data. Because I'm familiar with this feature, I know that if I simply uncheck "File Downloader" under "Roles" I get a list of my actual data. This is all stuff I uploaded to Harvard Dataverse:

![Account_-_Harvard_Dataverse_-_2019-05-23_11 40 29](https://user-images.githubusercontent.com/21006/58266489-bd1a0c00-7d4f-11e9-8b21-39cf5e25303c.png)

I can see at a glance, for example, that I have two dataverses and that one of them is published and one of them is unpublished. This makes me happy. It's my data. 😄 

All of this is a long visual way of saying that perhaps when someone visits My Data the "File Downloader" role should be unchecked by default. Otherwise the experience is confusing and perhaps even a little frustrating.

Alternatively we could rename the feature from "My Data" to "Stuff That Someone You May Or May Not Know Has Given You Access To Mixed In With Your Data". 😄

**Comment by TaniaSchlatter** [comment] 2019-05-29 14:00
I ran into this yesterday when testing a different feature. I created a new account, and once the account was created, I got the same list of unfamiliar results on a "My Data" view as the first thing I saw as a new account holder. I assume that there were reasons made at some point for what is shown by default. We should revisit the current functionality and rationale.

**Comment by dlmurphy** [comment] 2019-05-30 18:09
I plan to do some research to figure out which factors influence what appears on the "My Data" page. I discussed with @pdurbin today and our current hypothesis is that creating a new account via Harvard shibboleth causes you to automatically have "file downloader" role on any dataset that grants that role to all Harvard shibboleth users, thus filling your "My Data" page with them.

**Comment by dlmurphy** [comment] 2019-06-04 17:52
Above hypothesis confirmed. I created an account using Harvard shibboleth and reproduced Phil's situation: my "My Data" page was full of datasets I had the "File Downloader" role on. I checked on these datasets and they had this role assigned to ALL Harvard shibboleth users. Here's a screenshot showing this in the Roles table of one of these datasets:

<img width="576" alt="shibbolethgroup" src="https://user-images.githubusercontent.com/22962740/58901638-9c4aa280-86cf-11e9-964a-8ea971e35dec.png">

So: anyone using the Harvard University institutional login has 169 (and counting) mostly irrelevant dataverses and datasets showing up on their My Data page just because someone set those dataverses and datasets to allow file downloads for all users affiliated with Harvard.

**Comment by dlmurphy** [comment] 2019-06-04 18:01
As to what to do about this: 

Currently, by default, the My Data page displays dataverses and datasets that you have the "File Downloader" role on:

<img width="139" alt="filedownloaderrole" src="https://user-images.githubusercontent.com/22962740/58902161-90131500-86d0-11e9-943d-6886debe28df.png">

If we change it so that this box is unchecked by default, then these irrelevant results won't appear on the My Data page unless the user seeks them out. This seems fair because the File Downloader role _only_ grants the ability to download files, so it would be a real stretch to call datasets one has this role on "my data".

That does open up the question of whether we should default uncheck any other roles on the My Data page. For reference, here is the full list of default roles:

<img width="577" alt="roles" src="https://user-images.githubusercontent.com/22962740/58902436-19c2e280-86d1-11e9-9af3-0c3981da4900.PNG">

All other roles besides File Downloader offer the ability for the user to **make changes** to the dataset or dataverse, so I would say that these don't need to be unchecked by default.

**Comment by dlmurphy** [comment] 2019-06-06 19:57
I've created a document [here](https://docs.google.com/document/d/1yOtKE1z8kZKjoW8fHoy_7Ujou3p12Hlb3N96hHa1ic0/edit?usp=sharing) that sums up the research for this issue.

**Comment by dlmurphy** [comment] 2019-06-25 16:34
#3185 is relevant to this issue and includes a request for one possible way of addressing the problem.

**Comment by dlmurphy** [comment] 2019-06-28 15:59
In #5965 I added a bit to the "My Data" section of the user guide to explain this phenomenon:

> If you see unexpected dataverses or datasets in your My Data page, it might be because someone has assigned your account a role on those dataverses or datasets. For example, some institutions automatically assign the "File Downloader" role on their datasets to all accounts using their institutional login.

This doesn't solve the problem by any means, but at least there's an explanation of it in our documentation now.

**Comment by cmbz** [comment] 2024-08-20 15:22
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Closed by cmbz** 2024-08-20 15:22 UTC
Labels: Type: Bug, Feature: My Data
