### ISSUE TITLE
Add FAKE File DOIs

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#6646] opened 2020-02-13 02:49 UTC
When doi provider is set to FAKE, dataset dois are created but file dois are not, even if enabled. This can be confusing and is inconsistent.

**Comment by pdurbin** [comment] 2020-02-13 11:48
Here's a related comment I made at https://github.com/IQSS/dataverse/pull/5399#issuecomment-448289416

@sekmiller pointed out that the fake PID providers doesn't support file DOIs which is a good catch but I don't believe it needs to. The REST Assured test suite passes without it. If we ever need to add support for file DOIs, Steve said we need to write some code in the `publicizeIdentifier` method.

**Comment by kcondon** [comment] 2020-02-13 16:45
@pdurbin Are you saying this ticket is not worthwhile then? What I am presenting is a desire to have a fully functional dataverse installation while using a test doi and also not confusing someone such as myself as to why some functionality silently fails to work. Passing tests that do not test something is not a strong argument IMHO. That said, I'm also not saying this is urgent but performing due diligence in the interest of transparency.

**Comment by pdurbin** [comment] 2020-02-13 19:15
@kcondon on the contrary, I think it's a good idea to support file PIDs with the FAKE DOI provider. I'm just linking back to the old discussion to refresh the collective memories in the hive mind. 🐝

**Comment by landreev** [comment] 2020-03-26 19:37
I agree that this is a real issue - it has already caused some real life confusion (will explain). 

Whether we actually want file-level DOIs generated under the FAKE provider, I don't personally care; I would be ok if we just decided that setting it to FAKE should implicitly set :FilePIDsEnabled to false. The problem with the current state of it is that it results in some inconsistent behavior and at least one UI error: unless :FilePIDsEnabled is explicitly set to false, Dataverse appears to attempt to assign DOIs to files on publish, fails silently, then leaves the dvobjects with null identifiers, BUT with the identifierregistered=true. This in turn results in a null pointer in the file citation and a 500 in the UI. 

To reproduce: with FAKE provider configured, and without :FilePIDsEnabled set to false, publish a dataset with files. Go to the file page, and select any format under "Cite Data File" - you will get a 500. The file citation on the page will also be incomplete. 

This would be the case with any "sample data" instance spun up from the current config. The 500 UI error has been discovered by at least one person who was evaluating Dataverse.

**Comment by mheppler** [comment] 2020-05-28 16:03
I have been tripping over this when testing the download file citation locally in the new UI. Lots of 500 errors. Found this issue in the backlog and wanted to drop a note here in support of resolving this.

**Comment by landreev** [comment] 2020-05-28 16:09
There was some quick workaround though; for how to get rid of the 500 in citations (if this messes up your testing). 

OK, you can set :FilePIDsEnabled to false, and this will prevent it from happening for the files you may publish going forward. For the already existing ones, I think you may need to just unset the "global id registered" time stamp for all the files that don't have global ids... I can look it up this is something you need to do?

**Comment by mheppler** [comment] 2020-05-28 16:29
No, not urgent. But thank you, @landreev, for outlining the workaround option. Didn't need the physical download to work. Just hit the 500 error pg enough times to make me think "we should fix this already".

**Comment by landreev** [comment] 2020-05-28 16:31
it should be an easy fix too; I'll petition to get it into the next sprint.

**Comment by djbrooke** [comment] 2020-05-28 16:32
@mheppler @landreev petition received

**Comment by djbrooke** [comment] 2020-08-05 18:14
- Trivial solution - if the admin chooses to use FAKE for Dataset DOIs, it automatically disables File PID (one line-ish).
- Non-Trivial solution (this is the solution we want) - we actually support FAKE File DOIs. Modify the FAKE code to create a FAKE DOI for the file.

**Comment by pdurbin** [comment] 2021-03-25 15:33
https://groups.google.com/g/dataverse-community/c/2G9cU3VCrVs/m/hgBDvC33AwAJ prompted me to look to see if we have any tests for downloading files by PID but we don't because we can't give files PID when using the FAKE DOI provider.

**Comment by beepsoft** [comment] 2023-12-05 09:38
Is there a reason why fake doi for files is not supported? This makes testing difficult.

**Comment by qqmyers** [comment] 2023-12-05 09:51
FWIW: PermaLinks should be usable for testing instead. I don't think there's any reason Fake DOIs couldn't be made to work with files, but there has also been talk of removing Fake DOI altogether now that PermaLinks exist.

**Comment by beepsoft** [comment] 2023-12-05 13:05
Thanks, @qqmyers! I couldn't find information about this: which versions of Dataverse support PermaLinks?

**Comment by qqmyers** [comment] 2023-12-05 13:07
They came out in 5.14

**Comment by pdurbin** [comment] 2023-12-07 20:02
Just a +1 to what @qqmyers is saying. Death to FAKE DOIs at both the dataset and file level! Long live PermaLinks!

(I don't think we have an issue yet to remove FAKE DOIs.)

**Comment by cmbz** [comment] 2024-08-20 15:20
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Closed by cmbz** 2024-08-20 15:20 UTC

**Comment by qqmyers** [comment] 2024-10-28 14:32
File PIDs work with the Fake provider in v6.4, and have for a while (not sure when - at least since the multiple PID provider support).

**Comment by pdurbin** [comment] 2025-03-07 19:39
> Death to FAKE DOIs at both the dataset and file level! Long live PermaLinks!

I switch our Docker demo to PermaLinks:

- #11108
