### ISSUE TITLE
HTTP 500, NullPointerException on dataset creation

### ISSUE THREAD

**Issue by bencomp** [IQSS/dataverse#966] opened 2014-10-17 09:27 UTC
I just triggered a HTTP 500 Internal Server Error caused by a NullPointerException when I created a dataset on the test server (https://dataverse-demo.iq.harvard.edu/dataset.xhtml?id=93&versionId=24).

Excerpt from error page:

    javax.servlet.ServletException: java.lang.NullPointerException
    root cause: javax.faces.el.EvaluationException: java.lang.NullPointerException
    root cause: java.lang.NullPointerException
    note: The full stack traces of the exception and its root causes are available in the GlassFish Server Open Source Edition 4.0 logs.

Could it be caused by:

- leaving a topic field empty while the vocabulary field was filled out in the *Topic classification* metadata?
- not attaching any files?
- having "ORCID" selected as identifier type but not filling in an ORCID ID?

**Comment by scolapasta** [comment] 2015-02-27 22:21
Reviewing some old tickets, will pass to QA to see if it can be reproduced. (I was not able to)

**Comment by posixeleni** [comment] 2015-03-18 19:02
Unable to reproduce this issue in the current dvn-build and demo environments. I tried reproducing as @bencomp had described above and did not receive an error. Pending further reply I am closing this ticket.

**Closed by posixeleni** 2015-03-18 19:02 UTC
Labels: Status: QA
