### ISSUE TITLE
User Guide: Permissions + Publish Dataset/Dataverse Need More Info

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2653] opened 2015-10-19 19:26 UTC
Need to update the user guide to reflect changes based on features, functionality, and suggestions from users.

Update List:
- [ ] Permissions: write up more information about each specific permission
- [ ] Publish Dataset + Dataverse: add more information about the software will never automatically publish for you, end user needs to do that on their own

**Comment by pdurbin** [comment] 2015-10-19 19:36
@eaquigley just a heads up that soon I'll be creating a new 4.2.1 branch from the 4.3 branch and I might make it the default.

**Comment by pdurbin** [comment] 2015-10-20 15:41
@eaquigley I just created the 4.2.1 branch so if you plan to put this issue through QA for the 4.2.1 milestone, please put your commits in the 4.2.1 branch and change the milestone to 4.2.1.

**Comment by pdurbin** [comment] 2015-10-26 14:20
@eaquigley I don't know if you plan to cover in the guides the fact that roles can be created but @kcondon just reported how it's possible to create roles with combinations of permissions that lead to poor usability in my opinion, such as having a role with only the "ViewUnpublishedDataset" permission: https://github.com/IQSS/dataverse/issues/2648#issuecomment-150947491

**Comment by bencomp** [comment] 2015-10-29 14:02
As Dataverse ships with a default set of roles, may I suggest to explain these roles first? Normal users, including admins, will not be able to create (or update/delete) roles. Relevant roles should be explained at the various levels of role assignment, i.e. both in "Dataverse management" and "Dataset + File management". 

Before making major changes in the user guide, however, the role assignment pages should be given appropriate thought as requested/described in #2255, #2354 (likely dupe of #2255), #2241 (likely dupe of #2232) and possibly other issues. For example, for DataverseNL partners it is more obvious to grant users the *Dataset Creator* role than the *Contributor* role, but that is not a "short-hand option" like *Curator* and *Contributor* are.

**Comment by pdurbin** [comment] 2015-10-30 14:27
Related: #2616

**Comment by pdurbin** [comment] 2017-06-29 02:57
Two things. People continue to struggle with permissions, such as yesterday at https://groups.google.com/d/msg/dataverse-community/OebwRJZwDHY/4LxOf_BSBAAJ .

Also, I'm consolidating the following ticket into this one and I think it's a good idea we should consider:  Permissions: List roles in order of power of permissions #3040

**Comment by pdurbin** [comment] 2017-07-28 01:31
New issue #4027 reflects some of the confusion with permissions. Or maybe it's a legit bug.

**Comment by scolapasta** [comment] 2017-08-08 18:01
Issue #4027 was not a bug, but shows another place of confusion; besides the guides, the questions in the "edit access" section of the permissions page could be made clearer.

**Comment by dlmurphy** [comment] 2017-09-18 18:57
When editing permissions for a dataverse, some of the messaging is unclear:
![permissionsmessage](https://user-images.githubusercontent.com/22962740/30558588-06a5e4aa-9c80-11e7-8a44-e7ad8544a416.PNG)

Some users have expressed confusion over the underlined question. When they change this setting, they expect to see _currently assigned_ roles change. However, the way it really works is that changing this setting actually only changes what roles _will be assigned_ when users create new datasets in this dataverse. It doesn't work retroactively. Per discussion with @scolapasta, this feature is working the way it's intended to, so what we need is new messaging that makes this more clear.

I propose changing the underlined text to:
"When a user adds a new dataset to this dataverse, which role should be automatically assigned to them for that dataset?"

**Comment by TaniaSchlatter** [comment] 2017-09-19 13:01
How would a user expecting to change existing permissions do that? Let's consider providing a link or other to help people do that here as well.

- Tania

**Comment by dlmurphy** [comment] 2017-09-19 20:39
@TaniaSchlatter This is what the Dataverse Permissions page looks like when you first load it:
![permissions1](https://user-images.githubusercontent.com/22962740/30614223-abee0af4-9d58-11e7-8f3c-47a8690d6228.PNG)

The Users/Groups tab can be expanded to reveal the functionality you're talking about, the ability to change existing permissions:
![permissions2](https://user-images.githubusercontent.com/22962740/30614257-cacc7730-9d58-11e7-8f25-8b4e50bf4535.PNG)

It's definitely weird that this functionality is hidden in an unopened tab... I would guess that it's used much more frequently than the "Permissions" tab that's opened by default. Might be worth discussing alternate ways of organizing this page. Maybe three tabs with two of them closed by default isn't the best way to do this.

**Comment by dlmurphy** [comment] 2017-09-19 20:45
Since this is an old and rather expansive issue, the "definition of done" hasn't really been set - I've fixed the messaging issue @scolapasta identified on the "Edit Access" modal and I'm currently working on rewriting and expanding the documentation on permissions in the User Guide, on the Dataverse Management page and the Dataset Management page. Once I've done that, I'm planning to consider this issue finished.

**Comment by TaniaSchlatter** [comment] 2017-09-19 20:58
Ideally users would set permissions for "Anyone" type users (shown in the Edit Access popup) using the same UI convention as setting individual users and groups of individual users. The popup is enabling the setting of features by non-individual groups: "Anyone with a dataverse account" for example, on a broader level.

**Comment by dlmurphy** [comment] 2017-09-21 16:31
I've encountered a usability issue while writing docs for dataset permissions. Paging @TaniaSchlatter and @mheppler for their consideration.

The **file-level** permissions page can only be accessed through the **dataset** page, like so:
![filepermissions1](https://user-images.githubusercontent.com/22962740/30706680-2789b4b4-9ec7-11e7-926e-4ce73971bebf.PNG)

--
This link brings you to this page:
![filepermissions2](https://user-images.githubusercontent.com/22962740/30706718-45db6c14-9ec7-11e7-9038-e83e412b67bb.PNG)

On this page, you can click "Grant Access to Users/Groups" to see this modal:
![filepermissions3](https://user-images.githubusercontent.com/22962740/30706760-73402f3c-9ec7-11e7-8269-af4b5f10d4d7.PNG)

Here you can grant specific users access to specific restricted files. As far as I can tell, this is the **only place** you can do this. 

I expected to be able to do this via the file page for each specific file, but I can't find any option to do that:
![filepermissions4](https://user-images.githubusercontent.com/22962740/30707000-1ba5b552-9ec8-11e7-947a-5f93249e4c61.PNG)

I recommend we include a menu option where I've drawn that arrow, called "Permissions", that takes the user to a page where they can grant specific users access to this file.

Now that we have file pages, it's completely unintuitive to force users to go to the **dataset** level to grant access to a specific **file**.

**Comment by scolapasta** [comment] 2017-09-21 16:39
@dlmurphy , could you open that as a separate issue?

It is true, and technically we could use some aspect of the current ManagePermissionsPage as it could be used for a file. It may not be ideal, but would be the easiest.

**Comment by dlmurphy** [comment] 2017-09-21 16:55
@scolapasta Good call, I created issue #4148 for this. I'll put that info from your comment in there too.

**Closed** 2017-09-25 19:33 UTC
Labels: Feature: User Guide, Type: Suggestion
