### ISSUE TITLE
API endpoint to move dataset: Allow super user to move a dataset to another dataverse, one at a time.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2226] opened 2015-06-01 17:09 UTC
We frequently have requests to move datasets to another dv and it currently is done with a db sql statement along with an api index call.

This could be made a lot easier and enable support to do it directly with the ability to move single datasets through the UI. I am not talking about moving dataverses as in the pre v4.0 feature, only individual datasets. Make it super user only for now?

Related to #2278

**Comment by pdurbin** [comment] 2017-01-26 19:50
See also the "How to move dv's, ds" doc at https://docs.google.com/document/d/1A2v_ylLIRLIV6UpkDAJNNiFQt7q3SrAtAvQmg4nHBoY/edit?usp=sharing mentioned at https://groups.google.com/d/msg/dataverse-community/polE7z9_-NE/3xwAxgIHGgAJ

Here are the related issued:

- Moving Dataverses + Datasets: Provide way in the UI for a user to do this - https://github.com/IQSS/dataverse/issues/2073
- Move Dataset: Allow super user to move a dataset to another dataverse, one at a time. - https://github.com/IQSS/dataverse/issues/2226
- Move Dataverse: Allow super user to move a dataverse and reindex it and all child objects. - https://github.com/IQSS/dataverse/issues/2278

**Comment by djbrooke** [comment] 2018-01-16 15:41
Closing as a duplicate of #4405

**Closed by djbrooke** 2018-01-16 15:41 UTC
Labels: Feature: Permissions, Feature: Search/Browse, Feature: Superuser Dashboard, Help Wanted: Code, Mentor: pdurbin, Status: UX & UI, Type: Suggestion, User Role: Superuser, User Role: Sysadmin
