### ISSUE TITLE
Index: Uploading a file to a preexisting draft dataset without any metadata change does not index file.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3243] opened 2016-08-05 19:06 UTC
If you add a file to an existing draft dataset, regardless of whether it has a published version, and do not modify any metadata, the file is not indexed until metadata is modified of draft is published.

**Comment by pdurbin** [comment] 2016-09-23 19:50
This bug just entered my consciousness today while @sekmiller and I were reviewing pull request #3367 but seeing as how it was filed on August 5th and Dataverse 4.5 was tagged on August 24th is seems like this is a regression in Dataverse 4.5 or possibly earlier. At any rate, I can easily replicate it on https://demo.dataverse.org running v. 4.5 build 41-dc58ae1 by doing the following:

- create dataset (click save)
- upload file (after dataset has been created)
- click parent dataverse
- click "Files" to show only the file cards
- observe that the file card is not there

@landreev and @kcondon and I have been discussing this. I guess users have been living with this bug. The work around is to edit the dataset's metadata because when a dataset is edited the dataset and all of its files are reindexed.

**Comment by kcondon** [comment] 2016-09-23 19:53
Or publish. Most likely a dataset that is draft only is being actively worked on by contributors who likely go directly to the dataset to work on it rather than look for individual file cards that would be produced by indexing.

**Comment by pdurbin** [comment] 2018-09-20 18:36
@mheppler this is the issue I was just telling you about and I guess it's older than I remembered. Time flies when you're having fun! ✈️ 😄

**Comment by mheppler** [comment] 2018-09-20 18:42
Thanks, @pdurbin. Now that this issue has had sufficient time to marinate, I would like to propose we estimate this Bad Larry, and get it done. Came across this bug when developing fixes for #5067. This fix would help make testing that issue easier, as opposed to manually reindexing every time I upload a new file.

**Comment by djbrooke** [comment] 2018-09-20 18:50
Moving to Ready and tagging for estimation despite not knowing what Bad Larry means.

**Comment by mheppler** [comment] 2018-09-20 19:08
Pleaded my case to @djbrooke that this "low hanging fruit" get a "1" slapped on it and moved into this sprint, in order to fix along with #5067 since this bug will make testing that issue harder than it should be.

**Comment by pdurbin** [comment] 2018-09-24 17:18
As I said in my review for pull request #5083, I love one line fixes. Off to QA.

**Closed** 2018-09-24 21:15 UTC
Labels: Feature: Search/Browse, Status: QA, Type: Bug, ready for estimation
