### ISSUE TITLE
Data Package JSON schema

### ISSUE THREAD

**Issue by pkiraly** [IQSS/dataverse#4747] opened 2018-06-12 09:29 UTC
I just come across an interesting paper:

Fowler, Dan, Jo Barratt, and Paul Walsh. “Frictionless Data: Making Research Data Quality Visible.” International Journal of Digital Curation 12, no. 2 (May 13, 2018): 274–85.
https://doi.org/10.2218/ijdc.v12i2.577
http://www.ijdc.net/article/view/577

This is a summary of activities of Open Knowledge International regarding to data quality. One of their suggestion is a JSON schema called Data Package (the full description is available at https://frictionlessdata.io/specs/data-package/) which describes the structure of the underlying data, e.g. the column types of a CSV file, dictionaries, signals for NA etc. They have created Python and JavaScript libraries to read these metadata along with the CSV files, and tell the programs how to interpret the input file. External partners created R and Ruby packages).

I think the Dataverse support of it would be very useful. If you are interested, read first the paper, then the description of the Data Package.

**Comment by pdurbin** [comment] 2018-07-13 03:49
@pkiraly thanks for following up on the discussion at https://groups.google.com/d/msg/dataverse-community/ao-zFwN_M0M/LDlfR3hfBQAJ by creating this issue.

**Comment by lwinfree** [comment] 2019-06-07 18:02
Hi @pkiraly & @pdurbin! I'm the product owner for the Frictionless Data reproducible research project (https://frictionlessdata.io/reproducible-research/). I came across this issue while checking out Dataverse and wanted to say hi! I would be happy to chat with y'all more about if there is a potential collaboration with us and Dataverse, or answer any questions you might have about datapackage.json or any of our other software or specs. 😄

**Comment by pdurbin** [comment] 2019-06-07 18:48
@lwinfree hi! I bet @pkiraly is enjoying his weekend by now but I'm in http://chat.dataverse.org for another hour and a half today. Or there's always next week or whenever. 😄

**Comment by pdurbin** [comment] 2022-10-14 02:58
Fast forward a few years and @qqmyers has been adding excellent support for BagIt as a packaging standard in Dataverse (export first and now import!). A good entry point is the docs: https://guides.dataverse.org/en/5.12/installation/config.html#bagit-file-handler

Just today the team talked about this issue...

- #9033

... that mentions BagIt but another packaging standard we've talked about is RO-Crate:

- #8688

Finally, we've supported SWORD for a long time but that's just for import and we never did get around to having some sort of manifest inside the zip to populate file descriptions:

- #723

(This is just as well, because we have BagIt import now.)

First, @pkiraly are you still interested in this Data Package standard from Frictionless Data (by the way, thank you, @lwinfree for attending a [community call](https://docs.google.com/document/d/13Huxestxl_Mt18AgMsc34dS9lqgrUPx6uHbuXAOBSWw/edit?usp=sharing) a while back!)? Second, is your vision for export or import or both? Is it a zip file? Thanks.

Oh, finally, other packaging stuff I hear about are AIPs, DIPs, and SIPs. I believe these are more conceptual that specific standards. I guess they come from [OAIS](https://en.wikipedia.org/wiki/Open_Archival_Information_System#The_OAIS_environment_and_information_model).

**Comment by cmbz** [comment] 2024-08-20 15:24
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Closed by cmbz** 2024-08-20 15:24 UTC
Labels: Type: Suggestion, Feature: Metadata, Feature: File Upload & Handling, User Role: Depositor, GREI 6
