### ISSUE TITLE
Duplicate logo images in dataverse themes  can cause rendering failure of root dataverse page

### ISSUE THREAD

**Issue by plesubc** [IQSS/dataverse#8249] opened 2021-11-19 22:36 UTC
**What steps does it take to reproduce the issue?**

Having two identical logo images (as set by the GUI using the theming page `ThemeAndWidgets.xhtml`) for _separate_ dataverses causes a rendering failure of the root dataverse (ie, at https://installation.url)

Ultimately, the page fails to render and displays the message

```
"XML Parsing Error: not well-formed
Location: https://installation.url/
Line Number 89, Column 33:
    var index = label.indexOf('&');
--------------------------------^"
```

* When does this issue occur?

As mentioned before, when setting a dataverse theme via the gui at [dataverse landing page]/Edit/Theme+Widgets/Logo Image **AND** this image already exists as a logo image for another dataverse, the above error occurs. It's not possible to tell from the server.log message, but I have a sneaking suspicion that it may be related to the display of the scrolling widget on the top of the root dataverse

* Which page(s) does it occurs on?

For UBC's Abacus installation <https://abacus.library.ubc.ca> this error occured at the top level (ie, at https://abacus.library.ubc.ca). However, this is the only dataverse which features a the scrolling featured dataverse widget in this dataverse installation.

* What happens?
Page rendering fails with XML parsing error

* To whom does it occur (all users, curators, superusers)?

This affects all users coming to the top level page. Other pages are unaffected.

* What did you expect to happen?

I expected that adding a logo image to a newly created dataverse would have no affect on page rendering on pages unrelated to that dataverse. In fact, while performing the actions to add the logo, etc, the software behaves perfectly, and there is no indication that anything is wrong. It is only on returning to the top level that something appears wrong. Unfortunately, there's no guarantee that viewing the top level page has to happen at all in a session, so it would be very easy to miss the correlation between changing a logo in a sub-dataverse and a the rendering failure of the top level.

**Which version of Dataverse are you using?**

v5.6

------------
The error log indicates:

```
[2021-11-19T13:19:56.983-0800] [Payara 5.2021.7] [WARNING] [] [javax.enterprise.web.core] [tid: _ThreadID=89 _ThreadName=http-thread-pool::jk-connector(4)] [timeMillis: 1637356796983] [levelValue: 900] [[
  Servlet.service() for servlet Faces Servlet threw exception
java.lang.NoClassDefFoundError: Could not initialize class com.sun.imageio.plugins.jpeg.JPEGImageReader
```

Note that this issue (as you might suspect) occured using a JPG image. The complete log entry is at the bottom of this message.

The bug is not affected by the _name_ of the JPG image, as renaming the file in question **still** caused the error, so it appears to be caused by having two dataverses share a bitwise identical logo image. This could potentially be a problem as an institution with multiple dataverses could have the same image used for some (or even all) of them.

**What has not been tested**

Only JPG images have been tested for this error; no attempt was made for TIF or PNG images.

Note that the error can be reversed by removing the logo image from the dataverse theme or replacing it with one that is not in use. Once it's been deleted, the root dataverse page immediately renders as normal.

#### server.log

```
[2021-11-19T13:19:56.983-0800] [Payara 5.2021.7] [WARNING] [] [javax.enterprise.web.core] [tid: _ThreadID=89 _ThreadName=http-thread-pool::jk-connector(4)] [timeMillis: 1637356796983] [levelValue: 900] [[
  Servlet.service() for servlet Faces Servlet threw exception
java.lang.NoClassDefFoundError: Could not initialize class com.sun.imageio.plugins.jpeg.JPEGImageReader
	at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageReaderSpi.createReaderInstance(JPEGImageReaderSpi.java:85)
	at java.desktop/javax.imageio.spi.ImageReaderSpi.createReaderInstance(ImageReaderSpi.java:320)
	at java.desktop/javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:532)
	at java.desktop/javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:516)
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1463)
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1315)
	at edu.harvard.iq.dataverse.dataaccess.ImageThumbConverter.generateImageThumbnailFromFile(ImageThumbConverter.java:581)
	at edu.harvard.iq.dataverse.DataverseServiceBean.getDataverseLogoThumbnailAsBase64ById(DataverseServiceBean.java:334)
	at jdk.internal.reflect.GeneratedMethodAccessor1310.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4826)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:665)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at jdk.internal.reflect.GeneratedMethodAccessor206.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
	at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)
	at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at jdk.internal.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:888)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:833)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:375)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4798)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4786)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
	at com.sun.proxy.$Proxy373.getDataverseLogoThumbnailAsBase64ById(Unknown Source)
	at edu.harvard.iq.dataverse.__EJB31_Generated__DataverseServiceBean__Intf____Bean__.getDataverseLogoThumbnailAsBase64ById(Unknown Source)
	at edu.harvard.iq.dataverse.ThumbnailServiceWrapper.getDataverseCardImageAsBase64Url(ThumbnailServiceWrapper.java:320)
	at edu.harvard.iq.dataverse.ThumbnailServiceWrapper$Proxy$_$$_WeldClientProxy.getDataverseCardImageAsBase64Url(Unknown Source)
	at edu.harvard.iq.dataverse.search.SearchIncludeFragment.setDisplayCardValues(SearchIncludeFragment.java:1265)
	at edu.harvard.iq.dataverse.search.SearchIncludeFragment.search(SearchIncludeFragment.java:448)
	at edu.harvard.iq.dataverse.search.SearchIncludeFragment.search(SearchIncludeFragment.java:218)
	at jdk.internal.reflect.GeneratedMethodAccessor17550.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at javax.el.ELUtil.invokeMethod(ELUtil.java:239)
	at javax.el.BeanELResolver.invoke(BeanELResolver.java:440)
	at javax.el.CompositeELResolver.invoke(CompositeELResolver.java:198)
	at com.sun.el.parser.AstValue.invoke(AstValue.java:257)
	at com.sun.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:237)
	at org.jboss.weld.module.web.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
	at org.jboss.weld.module.web.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
	at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:65)
	at com.sun.faces.application.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:66)
	at com.sun.faces.application.ActionListenerImpl.getNavigationOutcome(ActionListenerImpl.java:82)
	at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:71)
	at javax.faces.component.UIViewAction.broadcast(UIViewAction.java:548)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:847)
	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1396)
	at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:58)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177)
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1636)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.apache.catalina.core.ApplicationDispatcher.doInvoke(ApplicationDispatcher.java:816)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:683)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:527)
	at org.apache.catalina.core.ApplicationDispatcher.doDispatch(ApplicationDispatcher.java:497)
	at org.apache.catalina.core.ApplicationDispatcher.dispatch(ApplicationDispatcher.java:379)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:329)
	at edu.harvard.iq.dataverse.HomepageServlet.processRequest(HomepageServlet.java:45)
	at edu.harvard.iq.dataverse.HomepageServlet.doGet(HomepageServlet.java:61)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1636)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:331)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:282)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:253)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:211)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:257)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:577)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:158)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.base/java.lang.Thread.run(Thread.java:829)
]]
```

**Comment by djbrooke** [comment] 2021-11-22 14:09
Thanks @plesubc for the detailed report. We'll work on a fix for this.

**Comment by pdurbin** [comment] 2021-11-23 16:18
@plesubc thanks for the bug report. No doubt something odd is happening in your 5.6 installation but I can't seem to reproduce this locally. I'm on post 5.8, commit c91689a724 of the "develop" branch.

I think I'm following your steps correctly and including adding the collections with the duplicate logos to the "featured dataverses". I'll include a screenshot and the image I'm using (a JPG) below.

Would you be able to see if you can replicate this bug on https://demo.dataverse.org ? It's running the latest release, 5.8.

![Screen Shot 2021-11-23 at 11 08 53 AM](https://user-images.githubusercontent.com/21006/143062114-c35f6eca-05bc-4845-82e6-aa0750e235e5.png)

![among-us](https://user-images.githubusercontent.com/21006/143062077-f115e6cc-134e-4e56-b801-39f0daca182d.jpg)

**Comment by pdurbin** [comment] 2021-11-30 16:38
I mentioned this issue to someone on the community call this morning (@Kris-LIBIS, I believe) who mentioned a potential issue uploading collection logos at all on recent versions of Payara.

It prompted me to look at what version of Payara I'm running. I'm running Payara 5.2021.5 but it looks like @plesubc is running Payara 5.2021.7. So the difference may be the version of Payara.

**Comment by donsizemore** [comment] 2021-11-30 17:53
I have a 5.8 installation running 5.2021.9 lying around, and I couldn't reproduce the problem:

![Screen Shot 2021-11-30 at 12 51 10](https://user-images.githubusercontent.com/12831666/144101013-952da674-7218-4995-b231-43273ce5cb09.png)

I may try again on 5.2021.7 for a better test. Looks like https://abacus.library.ubc.ca/ is running Dataverse 5.6.

**Comment by plesubc** [comment] 2021-11-30 17:56
I have tried replying to this via email twcie (as it says in the footer of the email I get) but apparently my responses have been lost in the ether. This was from November 23rd.

I feel bad that no one saw this as it's ultimately not a Dataverse problem as far as I can tell.

Again, apologies.

-----------------

Despite my extensive testing, log parsing, etc, I missed the most obvious solution to this problem.

On a payara service restart, the error disappeared and I was able to add the duplicate image with no issues.

I suspect this means you can close the ticket, but somewhere down the line someone may be opening a payara ticket.

It didn’t occur to me to restart the service because everything else appeared to be working perfectly. In any case, if the problem happens to someone else, at least there is apparently an easy solution.

Paul

**Comment by pdurbin** [comment] 2021-11-30 18:49
@plesubc ah, thanks for the update. I'm glad restarting Payara resolved the problem for you. I'll go ahead and close this issue. We can open it up again if we can figure out how to reproduce and fix it.

**Closed by pdurbin** 2021-11-30 18:49 UTC
