### ISSUE TITLE
Option to add a custom note for some notifications

### ISSUE THREAD

**Issue by mercecrosas** [IQSS/dataverse#1684] opened 2015-03-16 23:28 UTC
For some features that generate a notification (such as clicking "Return to Author" in a dataset in review, or assigning a role to a user), we should allow to add a custom note that the user gets with the notification.

**Comment by pdurbin** [comment] 2017-06-22 13:08
> For some features that generate a notification (such as clicking "Return to Author" in a dataset in review

#3943 represents the start of (the backend for) supporting the "return to author after a review with a custom note" user story. API-only for that issue is the plan. A better UI/UX would need to be designed.

**Comment by pdurbin** [comment] 2017-06-26 13:57
Related: Submit for review / Return to author - add explanatory note field #3702

**Comment by mheppler** [comment] 2018-07-10 21:16
This issue is being closed as a duplicate of both #2128 and #3702.

There is also _Allow to send a message when Approving or Rejecting a data access request #2139_ which covers Reject Access workflow.

**Closed by mheppler** 2018-07-10 21:16 UTC
Labels: Feature: Account & User Info, Feature: Notifications, User Role: Curator
