### ISSUE TITLE
DOI: Updating title in EZID doi metadata does not work properly.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4837] opened 2018-07-12 21:31 UTC
Each time a dataset is published some fields, including title, author, root dataverse name as publisher, and publication date (publish year?) are updated. This works generally but title shows some strange behavior when updated by itself.

If original published title is title 1, then update it to title 2, publish, ezid shows title 1 but record was updated based on timestamp. If progress to title 3, publish, ezid shows title 2, etc. etc.

This works properly if you update author at the same time, update to title 2 and update author, shows title 2. 

Note that author updates correctly by itself.

**Comment by djbrooke** [comment] 2018-11-27 15:46
From @thahn-thahn in #5346:

"We are using dataverse 4.9.1, with the configuration to Datacite.
We've just found out that if we modify the title of the dataset (among other metadata), the published version in datacite has always the old title. Other metadata are, however, well updated.

Another remark: we are moving to dataverse 4.9.2, in test phase, and saw that the bug is still there.
In addition, when we publish a dataset with 4.9.2, we have 2 updated versions in datacite."

**Comment by sekmiller** [comment] 2019-02-13 15:41
So the issue is that the metadata passed to DataCite/EZID gets the displayName of the dvObject. For a Datafile it is the label on the latest metadata (without regard for released/draft versions) for a dataset it is the released version title or if not released it is the draft version title.  The metadata is being passed to DC/EZId during the publish process, before the publish is finalized, so we're passing the prior released title. 

To fix this for this purpose only i added a getCurrentName to the dvObject. It is overridden in Datafile with essentially getDisplayName. However for Dataset it is overridden with getTitle from the current dataset version whether it is draft or published.

**Comment by kcondon** [comment] 2019-02-14 21:26
Still seems to happen when tested with datacite. Passing back.

**Comment by djbrooke** [comment] 2019-03-20 13:18
Reopening this for now. We need to resolve the conflicts in the PR, do a code review, QA, and then merge the PR. This will hopefully be just a quick check. I'll then tag this for the next release.

**Closed** 2019-03-20 23:30 UTC
Labels: Status: QA
