### ISSUE TITLE
NULL values in TextBox-type metadata fields cause a parser exception. Bug introduced when we switched to indexing values, instead of DisplayValues

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4229] opened 2017-10-24 19:58 UTC
Reindexing is sensitive to non-compliant metadata and halts when it is encountered, see #3190 

One issue found is the email field of the authenticateduser, there are two email addresses. 
Another is a missing required field, dataset contact email.

We have not yet determined the number of affected records or when this may have occurred.

**Comment by pdurbin** [comment] 2017-10-26 17:11
I talked to @landreev after standup and @pameyer at http://irclog.iq.harvard.edu/dataverse/2017-10-26#i_59220

It sounds like a legit way to reproduce this issue is to go in the database and null out a primitive `TEXTBOX` field like `dsDescriptionValue`:

```
curl -s http://localhost:8080/api/admin/datasetfield/dsDescriptionValue | jq .
{
  "status": "OK",
  "data": {
    "name": "dsDescriptionValue",
    "id": 18,
    "title": "Text",
    "metadataBlock": "citation",
    "fieldType": "TEXTBOX",
    "allowsMultiples": false,
    "hasParent": true,
    "parentAllowsMultiples": "true",
    "solrFieldSearchable": "dsDescriptionValue",
    "solrFieldFacetable": "dsDescriptionValue_ss",
    "isRequired": true
  }
}
```

So I blanked out the description of my "Darwin's Finches" dataset:

![screen shot 2017-10-26 at 1 07 19 pm](https://user-images.githubusercontent.com/21006/32066708-ac93747c-ba4e-11e7-832c-5b1b002b791b.png)

After removing the description, reindexing just that dataset with curl http://localhost:8080/api/admin/index/datasets/11 was enough to reproduce the exception we've been talking about in Slack:

```
Caused by: java.lang.IllegalArgumentException: String input must not be null
	at org.jsoup.helper.Validate.notNull(Validate.java:26)
	at org.jsoup.parser.TreeBuilder.initialiseParse(TreeBuilder.java:24)
	at org.jsoup.parser.TreeBuilder.parse(TreeBuilder.java:40)
	at org.jsoup.parser.HtmlTreeBuilder.parse(HtmlTreeBuilder.java:55)
	at org.jsoup.parser.Parser.parse(Parser.java:90)
	at org.jsoup.Jsoup.parse(Jsoup.java:58)
	at edu.harvard.iq.dataverse.util.StringUtil.htmlArray2textArray(StringUtil.java:119)
```

I added a null check in pull request #4241. Moving to Code Review at https://waffle.io/IQSS/dataverse

I noticed that http://guides.dataverse.org/en/4.8/admin/solr-search-index.html doesn't explain how to reindex individual datasets as shown above and I'd be happy to document it.

**Comment by pdurbin** [comment] 2017-10-26 17:57
@scolapasta suggested rewriting c3970a5 with a lambda so I'm pulling this back into development.

**Comment by pdurbin** [comment] 2017-10-26 18:11
@scolapasta I tried replacing...

```
for (DatasetFieldValue dsfv : datasetFieldValues) {
    String value = dsfv.getValue();
    if (value != null) {
        returnList.add(value);
    }
}
```

... with this (suggested by Netbeans):

```
datasetFieldValues.stream().map((dsfv) -> dsfv.getValue()).filter((value) -> (value != null)).forEachOrdered((value) -> {
    returnList.add(value);
});
```

.. but the war file no longer deploys. I'm getting this error:

`Exception Description: [class edu.harvard.iq.dataverse.DatasetFieldValue] uses a non-entity [class edu.harvard.iq.dataverse.DatasetField] as target entity in the relationship attribute [field datasetField].`

I'm going to punt on the lambda for now.

**Comment by scolapasta** [comment] 2017-10-26 19:34
OK, we'll have to wait until we upgrade to do this, as I just read this:
"If you're using a somewhat old implementation of JPA (e.g. EclipseLink 2.5.x) and you're using modern Java 8 features (such as lambda expressions) in your code base - don't ever use them in the JPA entity classes.

EclipseLink 2.5's class metadata parser crashes upon encountering Java 8 features (such as lambda expressions, method references etc.) in the bytecode. The internal crash is a very unfriendly ArrayIndexOutOfBoundsException, but you don't even get to see it, as the weaver code silently ignores metadata parser crashes and just assumes the class has no interesting metadata. This leads it to believe that the class in question is not an entity even though it has all the proper annotations, and the end result is the error message we are talking about."

https://stackoverflow.com/questions/8353752/jpa-error-uses-a-non-entity-class-ch-printsoft-mailhouse-usermgr-entity-departm

**Comment by landreev** [comment] 2017-10-28 19:40
I linked #4179 here, since I believe it is the same bug.  
When this issue goes into QA, I recommend that to re-test 4179 as well.

**Comment by landreev** [comment] 2017-11-06 20:43
To clarify, the exception stack trace for the actual error that was halting the indexing was posted outside the issue, in dv-general on slack. So that's how we determined what was causing it. Which turned out to be different from the original description - hence the changed title.

**Closed** 2017-11-06 20:50 UTC
