### ISSUE TITLE
Bug: cannot delete files from draft

### ISSUE THREAD

**Issue by gboeing** [IQSS/dataverse#4644] opened 2018-05-02 23:59 UTC
I've created a [new draft](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi%3A10.7910%2FDVN%2FCUWWYJ&version=DRAFT) of my data set. I want to delete all the files currently in it, and upload a whole new set of files. I scroll to the bottom of my 290 files (so they're all visible), then click the "select all" tick box to select them all. Then I click "edit files" > "delete" > and confirm. The page spins for a minute then reloads:

![screen](https://user-images.githubusercontent.com/4977197/39554822-e926db08-4e29-11e8-848e-944713723c89.jpg)

As you can see, it says "Success! – The selected files could not be deleted," which is a strangely contradictory status message. Indeed, all 290 files are still there. The delete operation did not succeed.

**Comment by gboeing** [comment] 2018-05-03 00:06
More info: I can delete a single file, one at a time. However, when I tick the box next to the file to select it, the Javascript spinner spins for 20+ seconds before I'm able to proceed with the deletion. Then the deletion takes 30+ more seconds before the page reloads and gives me the success message. This 50+ seconds per file isn't feasible to delete all 290 files... I'd need to be able to select all and delete them in one operation.

**Comment by pdurbin** [comment] 2018-05-03 03:00
Sure, I was just thinking that if there's nothing you care about in the draft you created, no significant time spent editing metadata or whatever, deleting the draft might be the easiest way to "reset" your dataset back to only having a single published version (one row in the `datasetversion` table). Right now you seem to be getting errors when deleting.

We haven't gotten around to adding the ability to delete files via the native API (#3419) but it's possible via SWORD: http://guides.dataverse.org/en/4.8.6/api/sword.html#delete-a-file-by-database-id

I have no idea if this will work for you, but I would try:

- deleting the draft
- creating a new draft by editing some metadata (update the description of the dataset, for example)
- delete files via SWORD or delete in small batches via the GUI.
- upload new files

Obviously, it shouldn't be necessary to reach for an API. Just some thoughts. I hope this helps.

**Comment by pdurbin** [comment] 2018-05-03 03:04
> creating a new draft by editing some metadata (update the description of the dataset, for example)

Oh, the reason why I mentioned this step rather that just deleting files via SWORD to create a new draft version is that years ago I saw a bug in this area: #2464

**Comment by gboeing** [comment] 2018-05-03 17:27
Thanks!

**Comment by pdurbin** [comment] 2018-07-13 03:36
@gboeing hi! Now that fix for #4573 has been deployed to Harvard Dataverse, do you want to see if you can still reproduce this error?

**Comment by gboeing** [comment] 2018-07-13 22:49
@pdurbin just checked it out, and I now cannot delete any files from my draft dataset, even one at a time. I get this error message:

![capture](https://user-images.githubusercontent.com/4977197/42717184-2dd0c8aa-86b4-11e8-90cc-07204f0e4e3a.PNG)

**Comment by pdurbin** [comment] 2018-07-13 22:52
@gboeing bah! I'm guessing there's something wrong it the database or something. Not to alarm you. I'm sure it can be fixed somehow. I'm not sure that this is a code issue. More of a data issue, like I'm saying. Can you please click that "Harvard Dataverse Support" link in the screenshot and report this? Please provide the DOI of your dataset. You should get an email back with a support ticket number and it would be helpful if you would leave a comment here with the number. Thanks!

**Comment by gboeing** [comment] 2018-07-13 23:02
@pdurbin I tried to fill out the ticket, but I'm not sure if it submitted successfully or not. The window just disappears when I hit "send message" and I haven't received a confirmation email. Also, the ticket window has a challenge question with a required answer, but I have no clue what it's asking me because it just says "+=". I entered "0" as my response.

![capture](https://user-images.githubusercontent.com/4977197/42717464-fe8713fe-86b5-11e8-9439-00d2dcb16033.PNG)

**Comment by pdurbin** [comment] 2018-07-14 01:03
@gboeing yikes. Can you please try emailing support@dataverse.harvard.edu instead? It goes to the same ticketing system. Meanwhile, you seem to have found another bug. 😞

**Comment by gboeing** [comment] 2018-07-14 18:58
Email sent. ID # 264343.

**Comment by pdurbin** [comment] 2018-07-14 22:34
@gboeing thanks! Yes, I can see it in the ticketing system. I'm going to close this out. Thanks for your patience.

**Closed by pdurbin** 2018-07-14 22:34 UTC
Labels: Feature: File Upload & Handling, Type: Bug, User Role: Depositor
