### ISSUE TITLE
Terms of Use Acceptance: File Does Not Download

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1397] opened 2015-01-29 18:27 UTC
I clicked Save Changes (this should say Accept by the way) on the Terms of Use pop up and the file never began to download.

**Comment by eaquigley** [comment] 2015-02-03 17:14
@sekmiller okay this is getting there! One last thing is that there is nothing denoting required fields. I logged in and had the pop up appear while downloading a file, I didn't fill out Institution and Position. Clicked accept and nothing happened. Clicked on download again, filled out Institution and Position and the file downloaded. So we need the required asterisks as well as have error messaging to show when a user doesn't fill out a required field.

One other thing, the email field is labeled name not email.

**Comment by mheppler** [comment] 2015-02-03 20:36
Cleaned up the layout of the Download File popup for datasets with the Guestbook enabled. Fixed the labels and layout.

**Comment by sekmiller** [comment] 2015-02-03 21:13
Added asterisks

**Comment by sekmiller** [comment] 2015-02-03 21:23
Added Error message to page. Catching the unanswered q's in the pop-up would take more coding.  Let me know the priority on that.

**Comment by mheppler** [comment] 2015-02-03 21:32
Finished layout clean up.

**Comment by mheppler** [comment] 2015-02-03 21:39
Added back in asterisks for required custom questions in the Guestbook workflow for dataset file download.

**Comment by mheppler** [comment] 2015-02-03 21:41
Additional items to-do:
- Display error message in the popup and not on the dataset page.
- Position isn't automatically filling in user account info.

**Comment by kcondon** [comment] 2015-02-03 23:33
All the above changes are in place but the original issue of not filling in required fields not downloading file with no resulting feedback is still happening but actually throws error in server log:

[2015-02-03T18:32:07.061-0500] [glassfish 4.1] [INFO] [] [edu.harvard.iq.dataverse.DatasetPage] [tid: _ThreadID=48 _ThreadName=jk-connector(2)] [timeMillis: 1423006327061] [levelValue: 800] [[
  Guestbook response isn't valid.]]

[2015-02-03T18:32:18.121-0500] [glassfish 4.1] [WARNING] [] [javax.enterprise.resource.webcontainer.jsf.lifecycle] [tid: _ThreadID=51 _ThreadName=jk-connector(5)] [timeMillis: 1423006338121] [levelValue: 900] [[
  #{DatasetPage.saveGuestbookResponse()}: java.lang.NullPointerException
javax.faces.FacesException: #{DatasetPage.saveGuestbookResponse()}: java.lang.NullPointerException
	at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:118)
	at javax.faces.component.UICommand.broadcast(UICommand.java:315)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790)
	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282)
	at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:295)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:415)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.faces.el.EvaluationException: java.lang.NullPointerException
	at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:101)
	at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:102)
	... 43 more
Caused by: java.lang.NullPointerException
	at edu.harvard.iq.dataverse.DatasetPage.saveGuestbookResponse(DatasetPage.java:704)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at javax.el.ELUtil.invokeMethod(ELUtil.java:332)
	at javax.el.BeanELResolver.invoke(BeanELResolver.java:537)
	at javax.el.CompositeELResolver.invoke(CompositeELResolver.java:256)
	at com.sun.el.parser.AstValue.invoke(AstValue.java:283)
	at com.sun.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:304)
	at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
	at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
	at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105)
	at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:87)
	... 44 more
]]

**Comment by kcondon** [comment] 2015-02-03 23:40
OK, I think I accidentally intercepted a ticket for @eaquigley . Sending back to her.

**Comment by eaquigley** [comment] 2015-02-04 16:00
Assigning this to @sekmiller to work on the comments @mheppler added in above as well as the comment from @kcondon

**Comment by sekmiller** [comment] 2015-02-05 19:32
Fixed the null pointer exception during guestbook response validation.  It will redirect you to the page when required fields are left blank. Catching the invalid response in the popup on hold for now.

**Comment by kcondon** [comment] 2015-02-05 20:51
OK, the incomplete guestbook issue is caught, thanks. Mike has a few more issues above. I added those to the various issues ticket #1411. Closing

**Closed by kcondon** 2015-02-05 20:51 UTC
Labels: Priority: Medium, Status: QA, Type: Bug
