### ISSUE TITLE
Dataset Thumbnails: Shape file thumbnails should have a modal map preview opened by a preview link, it is missing.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3586] opened 2017-01-23 16:20 UTC
Shape files have a thumbnail generated by the map it process and it is special since more than just a mouse over it has a preview link that is a modal popup rather than disappearing when moving off the image. It was opened via a preview link but that is missing, possibly when we optimized this view for performance.

**Comment by djbrooke** [comment] 2017-02-23 01:05
Closing as a duplicate of #3601.

**Closed** 2017-02-23 01:08 UTC
