### ISSUE TITLE
Metadata fields extraction using JSON url FROM DATAVERSE V. 4.6.1

### ISSUE THREAD

**Issue by sbdmicrisat** [IQSS/dataverse#3715] opened 2017-03-23 11:10 UTC
We are using Dataverse v.4.6.1 and designing Dashboard with metadata metrics. We are using this JSON link as data source to get the metadata( example :  http://dataverse.icrisat.org/api/search?q=*&key=API#&per_page=1000&fq=authorName:*)

we are getting few metadata fields(title, DOI, description, authors etc.) using this JSON . However we need to extract more fields like  'Production date', 'Distribution Date', 'Deposit Date', 'Keywords', 'Depositor' and 'download count by dataset /over the time' and JSON is not able to extract these metadata field from the database.

**Comment by djbrooke** [comment] 2017-03-23 15:49
Hey @sbdmicrisat - thanks for opening up this issue. We'll take a look to see if this is expected behavior, a bug, or a feature request (and whether or not it's a duplicate of some other request).

**Comment by djbrooke** [comment] 2017-03-23 20:50
Hey @sbdmicrisat -

This is the search API, so I wouldn't expect it to return the full JSON like what's returned by the API at the dataset/file level. 

I'd check out the dataset API here: 

http://guides.dataverse.org/en/latest/api/native-api.html#datasets

This should provide the information that you need.

**Comment by pdurbin** [comment] 2017-03-24 16:21
@sbdmicrisat if you're curious, the reason we don't return all of the metadata fields from the Search API is that we endeavor to keep the Search API mean and lean by operating only on data that we index into Solr. This avoids to expense of looking up data in the database (PostgreSQL) and should keep the Search API nice and fast. It's certainly possible to index additional metadata fields into Solr (we added a bunch in #2038), but as @djbrooke points out, the way right now to get all the metadata fields is to use the "native" API like this:

https://dataverse.harvard.edu/api/datasets/:persistentId?persistentId=doi:10.7910/DVN/SCN9LA

**Comment by pdurbin** [comment] 2017-06-23 11:32
@sbdmicrisat I hope the information above has been helpful. I'm closing this ticket but please let us know if there's anything else you need!

**Closed by pdurbin** 2017-06-23 11:32 UTC
Labels: Component: API
