### ISSUE TITLE
File: Individual Landing Pages for Files

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2465] opened 2015-08-17 20:31 UTC
Moving towards individual landing pages for files.

Assigning ticket to @mheppler to make wireframe for @sekmiller

**Comment by mheppler** [comment] 2015-08-19 20:47
Emailed ZIP'ed up wireframe to @sekmiller to wire up into the app. It was very basic, so there will need to be well coordinated back and forth between Stephen and I, to get functionality into the page, while steering the UI in the direction of the mockups.

https://iqssharvard.mybalsamiq.com/projects/filesprovenancefacetsfilter-dataverse40/File%20-%20General%20Metadata

**Comment by sekmiller** [comment] 2015-09-11 15:12
Mike, assigning this back to you for any cleanup.

**Comment by sekmiller** [comment] 2015-09-11 16:37
Mike, 
Everything is wired up except for the download and explore buttons which were in the mockup, but I missed them in the wireframes.  I'll see if I can add them in while QA is going on.
All of the data from the mockups is there(except provenence  and FITS). 
For styling help from you I didn't know how to handle the big open box for the file thumbnail, also the tags need some help and the list on the metadata tab.

I apologize for not giving any details previously.

**Comment by mheppler** [comment] 2015-09-11 16:55
Related to File Landing - UI Cleanup #2564.

**Comment by eaquigley** [comment] 2015-09-11 17:12
Passing back to @sekmiller to add additional edit options under the edit button on file landing page.

- [ ] metadata
- [ ] tags
- [ ] delete
- [ ] restrict

**Comment by mheppler** [comment] 2015-09-11 18:58
After reviewing the workflow for restricted files for users without permissions, it was decided that instead of the 403 page being displayed inplace of the file landing page, we should show the user without access permissions the landing page, with a "Request Access" button in place of "Download" and "Explore", just as it does on the dataset page.
- [ ] "Request Access" button

**Comment by eaquigley** [comment] 2015-09-11 19:22
above comment was discussed with @mcrosas to determine correct behavior

**Comment by mheppler** [comment] 2015-09-11 21:22
Additional render logic needed, based on new features added during UI cleanup.
- [ ] Draft/In Review/Unpublished labels next to file title
- [ ] "?" icon in citation block for help text related to newly created dataset DRAFT and new version DRAFT in the citation

**Comment by sekmiller** [comment] 2015-09-14 13:41
Added Render logic and checked in.  For edit, as discussed for a single file we will let Leonid's edit page handle it.

**Comment by djbrooke** [comment] 2016-08-05 19:35
Moving to ready as this is already has work done and is slated for 4.6.

**Comment by djbrooke** [comment] 2016-09-02 19:27
Before ready, need mockups of:

- Metadata layout of current fields 
- Show file citation information

**Comment by mheppler** [comment] 2016-09-07 19:53
Although the details are fuzzy, we'll move forward with this layout mockup and revise as needed.

Mockups: [Files (All Things) - Admin - Dataverse 4.2 and BEYOND...](https://iqssharvard.mybalsamiq.com/projects/filesprovenancefacetsfilter-dataverse40/grid)

![file-metadata](https://cloud.githubusercontent.com/assets/687227/18326321/2c3972ee-7513-11e6-94bb-1146f6da2826.jpeg)

**Comment by mheppler** [comment] 2016-09-07 20:02
Related to/duplicate of: File Metadata Support #2295

**Comment by mheppler** [comment] 2016-09-07 20:03
Started development related to bring back the previously developed file landing pg on the [file-metadata-provenance-2295](https://github.com/IQSS/dataverse/tree/file-metadata-provenance-2295) branch.

**Comment by djbrooke** [comment] 2016-09-09 20:45
Since this is on the critical path for many 4.6 items, we'll wire this up and move it to done as the above mockups specify.

We'll move forward changes to the appearance of the dataverse, dataset, and file landing pages as part of #3341.

**Comment by mheppler** [comment] 2016-09-12 14:51
Outline of requirements for the file pg:

- [ ] File Metadata
  - Name
  - Description
  - Citation (w/ dataset DOI, additional file info, Cite Data button, Data Citation Standards link)
  - Upload Date
  - File Type
  - File Size
  - MD5/UNF, Variables + Observations
  - File Tags
- [ ] Icon/Thumbnail
  - Preview
- [ ] Actions
  - Edit Metadata/Access/Delete
  - (Publish/Submit for Review?)
  - Contact, Share
  - Download/Request Access
  - Explore (TwoRavens, WorldMap)
- [ ] Metrics
- [ ] Terms
- [ ] Versions
- [ ] Provenance
- [ ] (Permissions?)
  - Draft/Review/Published
  - Download/Request Access
  - Thumbnail Preview
  - Restricted/Access icons

**Comment by mheppler** [comment] 2016-09-12 20:00
Added static placeholders (e.g. download, request access, and explore buttons) on file pg.

Passing to @sekmiller to wire these up. Outstanding questions about requirements (citation, publish, permissions, et al) in the outline above can be sorted while this initial development is starting.

**Comment by djbrooke** [comment] 2016-09-12 20:32
Thanks @mheppler!

Can someone instead of @sekmiller pick this up? I'm going to unassign for now since it looks like he has a few things in progress and we can figure it out in standup tomorrow.

**Comment by djbrooke** [comment] 2016-09-13 13:20
My bad! Talked with @sekmiller and we're all set - he recently finished up a few items and has availability.

**Comment by djbrooke** [comment] 2016-10-14 15:44
#3331 will be resolved by this. I've closed that issue, we should test it here.

**Comment by mheppler** [comment] 2016-10-14 16:55
Talked to @mcrosas and @scolapasta to get together an outline of what the file citation should look like. Here is a generalized example, where the squiggly-brackets `{ }` represent dynamic content.

`{dataset.citation} {file.name} [{file.name.label}] {file.unf}`

Here is an example of a citation from tabular file in a [3.6 dataset](http://dvn-archive.hmdc.harvard.edu/dvn/faces/study/StudyPage.xhtml?globalId=doi:10.7910/DVN/29381).

`Stanford University Center on Poverty and Inequality, 2016, "Dataset POVIN_2016_05_v2", http://dx.doi.org/10.7910/DVN/29381 UNF:5:iOXlfdlKOps0Ti308kX1dg== Stanford University Center on Poverty and Inequality [Distributor] V4 [Version] POVIN_2016_05_v2.tab [fileDscr/fileName (DDI)] UNF:5:iOXlfdlKOps0Ti308kX1dg==`

**Comment by mheppler** [comment] 2016-10-17 19:54
Also, as discussed with Mercè, we need to review the use of brackets around the UNF in the dataset citation.

<img width="1155" alt="screen shot 2016-10-17 at 3 52 40 pm" src="https://cloud.githubusercontent.com/assets/687227/19453133/ea31f8e2-9481-11e6-91a4-f9be6d9f74a2.png">

**Comment by mheppler** [comment] 2016-10-19 22:43
After reviewing the file pg with @sekmiller today, we identified a few remaining to-do's and bugs.

- [ ] Deaccession - This entire feature/workflow/use case needs to be added, then demoed and reviewed with @scolapasta and @mcrosas 
- [ ] Permissions/Access - Not logged in, can view draft/unpublished file pg
- [ ] File Citation - version number inaccurate (V2 same even if datasetVersionId=1 vs datasetVersionId2)
- [ ] File Citation - DRAFT VERSION citation in published file pg
- [ ] File Citation - Code Clean up (move file related info in citation out of XHTML and to manage bean)

**Comment by djbrooke** [comment] 2016-11-02 18:05
tagging @sekmiller 

We have news re: deaccession!

"Confirmed with Merce, we should remove the Share button from a deaccessioned dataset/file. I have added an additional screenshot of the deaccessioned dataset to show the Upload, Download, Explore buttons, that Merce made mention we don't want to display."

@mheppler has created a helpful mockup:

<img width="618" alt="screen shot 2016-11-02 at 2 03 30 pm" src="https://cloud.githubusercontent.com/assets/7773392/19941116/42aafd86-a105-11e6-8df5-768742df4814.png">

**Comment by raprasad** [comment] 2016-11-08 18:16
@mheppler @sekmiller : quick UI note.  feel free to add to #2290 if this ticket is closing

![016_txt_-_7801f23d_dataverse](https://cloud.githubusercontent.com/assets/1036060/20111220/828a5118-a5b5-11e6-8361-8a38fdc6f02e.png)

**Closed** 2016-11-23 16:30 UTC
Labels: Component: File Upload & Handling, Component: UX & UI, Type: Feature
