### ISSUE TITLE
Zip downloads disabled unless :ZipDownloadLimit is set, mention in Guides that setting ZipDownloadLimit now toggles UI options

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#7932] opened 2021-06-08 20:22 UTC
- In v5.5, not having a ZipDownloadLimit set results in a limit of 0 being returned and that disables all Zip Downloads. The docs say there is a default limit of 100MB, but the code in SystemConfig sets the default to 0.
- In the docs, we should clarify that the ZipDownloadLimit now controls the workflows implemented in #7714 (this is especially important in installations running the custom zipper service)

**Comment by landreev** [comment] 2021-07-21 15:46
This was happening because the 100MB default was set in the class DataFileZipper.java, outside of the normal framework of keeping the defaults in SystemConfig. Under the original assumption that no other components would need that value, probably? As a result, the page wasn't getting it for the purposes of disabling large downloads.  
The commit above should fixes it by moving the default value to the standard place. (can be confirmed/reviewed as the issue comes up under the normal process)

**Comment by djbrooke** [comment] 2021-07-21 17:55
I added the doc update to the same branch above (https://github.com/IQSS/dataverse/tree/7932-zip-download-limit) so I'm marking this as a small - it could be extremely close to already done!

**Comment by landreev** [comment] 2021-07-21 23:12
Ok, built, re-tested carefully (without the limit set explicitly; with the limit...) - appears to be working as it should be.

**Closed** 2021-07-23 18:31 UTC
Labels: Small
