### ISSUE TITLE
Logging In: Incorrect Password Breaks Page

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2171] opened 2015-05-14 20:07 UTC
I’ve reset my password multiple times because when I go to log in and use one of my two possible passwords, I get the error message then when I do my other possible password I am getting the error message again. I’ve now tested this on dvn-build with using the wrong password then doing the correct password and I am getting the same behavior. 
 
This is leading me to come to the conclusion that the log in page is breaking for some reason and not resetting when I type in the correct password and click Log In.

Page needs to not break when an incorrect password is inputted. This prevents users from logging in and doesn't give them any information as to what is going on.

**Comment by scolapasta** [comment] 2015-11-09 21:52
I am not able to reproduce. @eaquigley could you try this again? And if it happens, keep track of small details (clicked button, hit enter, etc.) I tired a bunch of combinations and was able to log in.

**Comment by pdurbin** [comment] 2016-01-15 17:48
@scolapasta hasn't been able to reproduce this and neither can I (tested 94117bb in 4.2.3 branch).

@eaquigley I'm going to close this issue. If you can reproduce it, please re-open it and (as @scolapasta said) please provide as much detail as possible about how to reproduce it. I'm happy to look over your shoulder. Please just grab me.

**Closed by pdurbin** 2016-01-15 17:48 UTC
Labels: Component: UX & Upgrade, Priority: Critical, Status: Dev, Type: Bug

**Comment by pdurbin** [comment] 2016-01-20 15:00
"Appears to no longer be happening. Thanks." -- @eaquigley
