### ISSUE TITLE
Add Grant Information to Advanced Search and Search Facets

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse#4084] opened 2017-08-17 06:38 UTC
It would be useful if the two metadata fields on grant information could be added to the advanced search options, and to the configurable search facets.

Best,
Philipp

**Comment by pdurbin** [comment] 2017-08-17 10:00
@philippconzett I assume you mean `grantNumberAgency` and `grantNumberValue`, which are the two subfields of `grantNumber` at https://github.com/IQSS/dataverse/blob/v4.7.1/scripts/api/data/metadatablocks/citation.tsv . Are you familiar enough with that file to make a pull request? Please see also http://guides.dataverse.org/en/4.7.1/developers/version-control.html#how-to-make-a-pull-request

**Comment by philippconzett** [comment] 2017-08-17 14:25
I submitted a pull request, my very first one, so I'm not sure I got it right.

**Comment by pdurbin** [comment] 2017-08-17 14:51
@philippconzett the pull request itself looks great and I moved this issue to code review for you at https://waffle.io/IQSS/dataverse but please notice now there is no associated pull request yet:

![screen shot 2017-08-17 at 10 47 49 am](https://user-images.githubusercontent.com/21006/29418190-abbc084e-8339-11e7-87ee-87a10b48ee01.png)

To fix this, can you please edit the description of your pull request and add the following line?

---

connects to #4084 

---

This is magic syntax Waffle uses to associate pull requests with issues.

**Comment by philippconzett** [comment] 2017-08-17 15:47
OK, Phil. I have added the issue no. You said you added the request for review for me in Waffle. Do I have to do anything there before you can process the request?

**Comment by pdurbin** [comment] 2017-08-17 15:51
@philippconzett you're all set. At standup a few minutes ago @jggautier said he'd take a look at your pull request, which is why the issue is now assigned to him.

@jggautier there's a new feature of GitHub where you can go to https://github.com/IQSS/dataverse/pull/4085/files and click "Review Changes" and then "Approve" or "Request Changes". If you haven't used that feature yet, now would be a good time to try it out. 😄

**Comment by pdurbin** [comment] 2017-08-17 15:53
Here's the "after" picture, by the way, with the magic "connects to" syntax in place:

![screen shot 2017-08-17 at 11 52 35 am](https://user-images.githubusercontent.com/21006/29421309-af6778c6-8342-11e7-9518-a365460ed008.png)

**Comment by jggautier** [comment] 2017-08-17 16:02
Thanks for the tip @pdurbin. That's simple.

Just double checked that the TSV is well-formed. It is, so I approved it.

**Comment by pdurbin** [comment] 2017-08-17 16:17
@jggautier thanks, please drag the issue/pr from Code Review to QA at https://waffle.io/IQSS/dataverse when you get a chance.

**Closed** 2017-08-23 21:03 UTC
Labels: Component: Metadata, Persona: Curator, Type: Suggestion
