### ISSUE TITLE
Payara Testing

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6595] opened 2020-01-30 21:24 UTC
http://payara5.odum.unc.edu/ is running Payara. One of the remaining tasks is to test to see if things are working as expected.

**Comment by donsizemore** [comment] 2020-01-30 22:21
@djbrooke if you want, i can cobble in the active bits of https://github.com/IQSS/dataverse-ansible/blob/master/tasks/dataverse-api-testsuite.yml and see how it fares?

**Comment by djbrooke** [comment] 2020-01-30 22:24
@donsizemore thanks for setting this up and for the offer of additional testing. We're expecting mostly front end issues, but this can't hurt!

**Comment by poikilotherm** [comment] 2020-02-28 09:56
[Payara 5.201 has been released yesterday](https://github.com/payara/Payara/releases/tag/payara-server-5.201).

It [contains the JSF 2.3.14 update](https://github.com/payara/Payara/pull/4492), so no manual patching necessary.

**Comment by sekmiller** [comment] 2020-04-02 15:28
I'm unable to save a Guestbook with a custom question that takes a multiple choice response on either of the Payara 5 installations at UNC. It does work under GF4 and PF8.

**Comment by sekmiller** [comment] 2020-04-02 18:18
In P5, if you upload a file on create it does not display in the pending files table. It does save/ingest on dataset create. If you upload a file to an already created draft you do see the uploaded file in the pending table before saving the version.

**Comment by sekmiller** [comment] 2020-04-02 18:58
In P5 the popup warning ("are you sure?...) when you remove a thumbnail from a dataset is not working. If you press the "Remove" button the thumbnail is simply removed.

**Comment by sbarbosadataverse** [comment] 2020-04-03 00:06
guestbook "multiple choice" option does not work.
unable to include multiple responses and unable to save

you can only include one response

<img width="1457" alt="Screen Shot 2020-04-02 at 7 53 42 PM" src="https://user-images.githubusercontent.com/8322346/78310920-5f348400-751d-11ea-89af-0f53a55f0e1a.png">

when you hit save you get this screen
<img width="1590" alt="Screen Shot 2020-04-02 at 7 53 56 PM" src="https://user-images.githubusercontent.com/8322346/78310930-652a6500-751d-11ea-86b0-1c9ea401e59f.png">

**Comment by sbarbosadataverse** [comment] 2020-04-03 00:21
"Drag and drop" for file upload  is not working on on payara. works on primefaces8. 

drag and drop gives you a blank after upload looks like it's completing

<img width="1507" alt="Screen Shot 2020-04-02 at 8 17 24 PM" src="https://user-images.githubusercontent.com/8322346/78311637-6361a100-751f-11ea-87a2-67ecf5ab4b4f.png">

works on primefaces 

<img width="1324" alt="Screen Shot 2020-04-02 at 8 20 57 PM" src="https://user-images.githubusercontent.com/8322346/78311709-8ee48b80-751f-11ea-96c2-cfeed6b12a02.png">

**Comment by sbarbosadataverse** [comment] 2020-04-03 00:23
I got one template error (similar to guestbook error reported above) but wasn't able to reproduce it again. not sure which server I was on

<img width="1629" alt="Screen Shot 2020-04-02 at 8 15 20 PM" src="https://user-images.githubusercontent.com/8322346/78311778-c2271a80-751f-11ea-968e-6f7f50accbe4.png">

**Comment by sekmiller** [comment] 2020-04-03 14:17
Was able to recreate the file upload on create error on my local host.

This is what I'm seeing in the log:
Severe:   Error Rendering View[/dataset.xhtml]
java.lang.ArrayIndexOutOfBoundsException: -2
	at com.sun.faces.renderkit.html_basic.HtmlResponseWriter.writeUnescapedCData(HtmlResponseWriter.java:1474)
	at com.sun.faces.renderkit.html_basic.HtmlResponseWriter.writeText(HtmlResponseWriter.java:961)

I get the same error when I change Dataset Templates on Dataset Create.

**Comment by scolapasta** [comment] 2020-04-03 17:33
As we find issues and report them here, I'm going to go ahead and move them onto a checklist on #6230. That way people can still post issues here (and we can close when we feel that the functionality has been tested) and we can work on solving them over there.

**Comment by scolapasta** [comment] 2020-04-03 17:37
@sbarbosadataverse Can you be more specific about the template error (before I copy over to the other issue)

**Comment by scolapasta** [comment] 2020-04-03 17:54
OK, except for that @sbarbosadataverse one, I copied all of the issues into the the checklist on #6230. If I missed anything, or if you find anything new, let me know.

**Comment by scolapasta** [comment] 2020-04-28 17:25
Closing this as we handled all upgrade related issues found for this in #6230.

**Closed by scolapasta** 2020-04-28 17:25 UTC
