### ISSUE TITLE
Flyway: Add the database migrator in order to make database migration happen automatically.

### ISSUE THREAD

**Issue by MrK191** [IQSS/dataverse#5344] opened 2018-11-27 13:04 UTC
Hi, I've managed to make flyway work, now there will be no need to add upgrade scripts since the migration will happen, after user will boot the war file. 
Just tell me if you want this feature then I will make PR.

**Comment by poikilotherm** [comment] 2018-11-27 13:33
As this involves new deps in `pom.xml` it might be a good idea to rely on the merge of #5289, too.

**Comment by MrK191** [comment] 2018-11-27 14:10
> As this involves new deps in `pom.xml` it might be a good idea to rely on the merge of #5289, too.

Yeah I will wait for the merge and then apply all those rules to this PR.

**Comment by pameyer** [comment] 2018-11-27 19:21
If I'm remembering correctly, when flyway came up in previous discussions there was some uncertainty about the potential for certain postgresql versions being restricted to flyway enterprise.  Is this (still?) a concern?

**Comment by pdurbin** [comment] 2018-11-28 11:46
@MrK191 heads up that pull request #5317 was merged. I don't think you should be blocked on waiting for pull request #5289 to be merged if you are only adding one dependency to pom.xml. There are 9 pull requests in QA right now and I don't know what order they will be worked on.

**Comment by dheles** [comment] 2018-11-30 16:11
I'm in the process of an ansibilized upgrade to which I'm too committed to change horses now, but I will share that once DSpace incorporated Flyway, it made upgrading *much* easier, so i'd be very much in support of this approach moving forward.

**Comment by pdurbin** [comment] 2018-12-01 13:37
@dheles thanks for your input. You're making me think that I should take a look at DSpace's dev guide see how they explain to developers how to use Flyway. I read what @MrK191 wrote in his pull request but I'm still a little confused about what I'm suppose to do as a developer. It all feels a bit magic at the moment.

@MrK191 heads up that after pull request #5289 by @poikilotherm was merged there were merge conflicts in your branch so in 91f6574 I took the liberty of doing two things:

- resolving the merge conflicts
- adjusting your changes to pom.xml to be as small as possible to make code review easier. I overwrote pom.xml with the latest from "develop" and then put in the small changes I think you intended. Previously the "diff" was bigger because you included a number of formatting changes (long lines, whitespace, etc.) in your pull request when it first reached us.

**Comment by landreev** [comment] 2018-12-06 15:39
@MrK191 et al, 
So to recap, this looks promising and we are interested in incorporating FlyWay going forward. 
For upgrading from past releases (prior to the release in which we add FW), we will advice people to first upgrade to the N-1 version, potentially using the scripting solution for jumping across versions provided earlier. But this part needs to be clearly documented. 
There were also some other suggestions (in the PR comments), for the docs and pom.xml, both from me and @poikilotherm. So I would like to jump on this and work on the documentation for this PR. I was going to create a local copy of your branch in the IQSS/dataverse github tree; but, if you prefer, I could instead make a PR into your branch.

I also would like to actually test this whole process myself. I am specifically interested in how to handle a scenario where we don't just modify the structure of the database tables and columns; but also need to repopulate them, based on values from other tables, subject to some extra conditions and transformations... I'm still not sure if this can be done fully within FlyWay, or if we still have to supply custom scripts for that. (either way, this will need to be documented too). Please understand that we have to give priority to other issues on our development stack; so I'm only looking into this whenever I have time. But we will eventually figure it out. 
Thanks again for contributing!

**Comment by pdurbin** [comment] 2018-12-06 16:09
> a scenario where we don't just modify the structure of the database tables and columns; but also need to repopulate them, based on values from other tables, subject to some extra conditions and transformations

For @MrK191 's benefit I'll just highlight #5057 as one of these more complicated scenarios that we don't expect Flyway to handle. It had to do with the shoulder of a DOI and how we store it. @scolapasta @landreev and I discussed yesterday that we expect we'll still need to write some SQL ourselves here and there and I believe @landreev mentioned Flyway has a mechanism for adding custom SQL statements we might need.

**Comment by landreev** [comment] 2018-12-06 16:48
The entire upgrade script for that release (upgrade_v4.8.6_to_v4.9.sql) is a good example. Among other things, we move the columns that store the global identifiers from the table dataset to dvobject; and transfer (and modify!) the values based on some pattern-matching. 

We will likely have cases like that again going forward. So this scenario needs to be tested and documented carefully before we can accept the PR.

**Comment by poikilotherm** [comment] 2018-12-06 17:00
@landreev please be aware that it would be totally possible to have the migrations from 4.x to the first that includes the Flyway stuff. IMHO your existing migration scripts can be reused for this, so this is not lost.

For all cases that require complex stuff which cannot be done in SQL or only in more complex ways, you can always add a Java based migration to the mix. That offers a lot more options for even the most complex data migrations.

**Comment by landreev** [comment] 2018-12-06 18:07
>  please be aware that it would be totally possible to have the migrations from 4.x to the first that includes the Flyway stuff handled with Flyway

I asked that question earlier, and was told that no, it would not work. OK, you mean, it would work, if we go back and create FlyWay upgrade scripts for all the earlier versions, using our old migration scripts as a source - ? Hmm. TBH, that sound like a lot of work, that I'm not sure would be fully justified...

**Comment by poikilotherm** [comment] 2018-12-06 19:41
Maybe I got something wrong, but aren't your upgrade scripts more or less plain SQL stuff like "ALTER, CREATE, ..."?

When using Flyway, you need to write either SQL migration scripts and/or Java migration "scripts" (classes). There is no real "scripting" like in "bash script" involved. So IMHO you could simply reuse the existing "upgrade_v4.8.6_to_v4.9.sql" and others, rename it a bit so it fits in the version schema and go ahead.

Yet there is one thing you need to implement: a custom `MigrationResolver` (a FlyWay Java class), so Flyway upgrading e.g. from "4.8.6" to "4.flyway.introduced" or later knows that you start at "4.8.6". And obviously, you need to provide that information in some way. I have some ideas about that, but I think @MrK191 has some on his own... ;-) And this resolver only needs to cover versions before we integrate Flyway, everything following is usable out of the box (so this is a one-time effort).

From a user perspective, IMHO that would ease the process alot. You could tell people to "just" download the WAR, undeploy, in some way provide the starting version info and deploy. Then Flyway takes care of "the rest". No script running, no fiddling, just one thing to do.

**Comment by pdurbin** [comment] 2018-12-06 19:54
> Maybe I got something wrong, but aren't your upgrade scripts more or less plain SQL stuff like "ALTER, CREATE, ..."?

@poikilotherm well, "plain SQL" can get a little complicated. Like @landreev is saying, if you look at https://github.com/IQSS/dataverse/blob/v4.9/scripts/database/upgrades/upgrade_v4.8.6_to_v4.9.0.sql#L65 for example you'll see this:

`INSERT INTO setting(name, content) VALUES (':Shoulder', (SELECT substring(content, strpos(content,'/')+1) || '/' from setting where name = ':Authority'));`

That logic relates to #5057 and you can see a fix by @qqmyers at https://github.com/QualitativeDataRepository/dataverse/commit/b5334eb61c019f7891239b61c1a899c1c7283572

Good to know that with Flyway we could try writing some of this in Java.

**Comment by MrK191** [comment] 2018-12-06 20:08
@poikilotherm Are you sure you can create a baseline after executing sql scripts?

**Comment by poikilotherm** [comment] 2018-12-06 20:23
@MrK have we been blind? We could just set the proper baseline version depending on the Dataverse version, couldn't we? Wouldn't that render the custom `MigrationResolver` pointless, because then we could "just" transform the existing scripts into versioned ones that will be applied by standard resolver?

**Comment by poikilotherm** [comment] 2018-12-06 20:36
Another thought: it might be a good idea to find out on what versions the 35 production instances are. The lowest version should be the one to base all Flyway migrations upon (kinda "lowest baseline"). Everything before that makes no sense IMHO. This should of course be documented.

**Comment by MrK191** [comment] 2018-12-06 20:39
@poikilotherm Oh yeah you are right, but after we detect which version it is, we would need to move the correct scripts to the db/migration folder and rename them so we can execute them in correct order.

**Comment by poikilotherm** [comment] 2018-12-06 20:40
I don't think so - the Flyway baseline docs state clearly that everything before baseline, including baseline is ignored. 

> Baseline is for introducing Flyway to existing databases by baselining them at a specific version. The will cause Migrate to ignore all migrations upto and including the baseline version. Newer migrations will then be applied as usual.

https://flywaydb.org/documentation/command/baseline

**Comment by MrK191** [comment] 2018-12-06 20:52
@poikilotherm Oh then that would be amazing, I will test it tomorrow.

**Comment by poikilotherm** [comment] 2018-12-06 21:05
@MrK191 you have seen [API docs](https://flywaydb.org/documentation/api/javadoc/org/flywaydb/core/api/configuration/FluentConfiguration.html#baselineVersion(java.lang.String)) about setting the baseline version, haven't you? It should be easy to provide a mapping from Dataverse version to migration version. Maybe add a sysprop for the old version? Easy to set in the app server...

**Comment by dheles** [comment] 2018-12-07 12:56
@poikilotherm we (JHU) are on 4.6.0, but will be upgrading to 4.9.4 next week.

**Comment by landreev** [comment] 2018-12-07 15:55
Seriously, even if it is possible to apply FlyWay to past versions, by doing some retroactive work for the existing releases... IMO, it's a bit hard to justify this extra effort. I would stick to what @Mrk191 originally suggested - we just tell people to upgrade to the last non-FlyWay release first; and for that we have a clearly documented process.

**Comment by landreev** [comment] 2018-12-07 16:02
A correction to what I said yesterday: I'm not going to "jump on it" just yet; because this hasn't gone through our normal planning and scheduling process. 
So I'm going to put this back into community dev column. 
There's been a productive discussion and there's some semblance of a consensus of what needs to be done, before we can incorporate this: 
- The entire process should be very clearly documented, so that all the developers can start using it going forward; 
- That should include what to do with trickier cases, that involve changing/adding the db content; 
- Somebody from within the team should actually test the entire process and verify that it works as documented; 
- This should definitely include testing that everything is still working with the new maven plugins - that are upgraded from versions 2.* to 3.* in this PR; which seems like a serious change, as has been pointed out.

**Comment by landreev** [comment] 2018-12-07 16:38
@dheles If you are upgrading next week, to 4.9.4: the upgrade instructions that come with the release still ask you to perform every intermediate upgrade between 4.6.0 and 4.9.4, manually. We have added a scripting solution, that allows to upgrade the database from 4.6.0 and 4.9.4 in one step; but as of now, it's only available in the develop branch (it will be included in the next release). 
But you should be able to download the scripts involved from the develop branch, run them on your database (DEFINITELY do back up your database first! Just in case...) And then deploy the 4.9.4 war file. You can read about the database upgrade script, in the documentation in the develop branch. 

Alternatively, you can wait until the next release comes out (in a couple of weeks?). The upgrade script will be part of that release. 

There is also a good chance that support for FlyWay will also be included in the next release. My understanding so far is that it will not necessarily help you upgrading from 4.6.0 (but that may change).

**Comment by dheles** [comment] 2018-12-07 21:07
@landreev Thanks for the info. We are right on the cusp of going live with an Ansibilized upgrade process I've been developing and testing for a while now. In the long run, I think the scripted and Flyway upgrade processes will be much easier and I look forward to testing and using them in the future. However, especially as our EZID-to-DataCite DOI migration is to be facilitated by our upgrade, I don't think we are inclined to wait even the fairly modest time that would be required to benefit from these enhancements.

**Comment by landreev** [comment] 2018-12-07 21:22
@dheles Makes sense. 
Still, keep in mind that you don't need to wait for the next release, in order to use the new database upgrade script. 
You check out the develop branch and run it from there.
The script is scripts/database/dbupgrade.sh; the instruction is in scripts/database/README_upgrade_across_versions.txt. 
In order to run, the script also uses the file scripts/database/releases.txt; and the files supplied in the 2 directories scripts/database/upgrades and scripts/database/create. 
(note that *all* of the files/directories above need to be checked out from the develop branch for the whole thing to work)

(and of course disregard all this if you have an antsible solution that does it all for you already)

**Comment by pdurbin** [comment] 2018-12-07 21:43
@landreev @MrK191 @poikilotherm thanks to @dheles who put me in touch with some DSpace developers, I now know where the document Flyway in their dev guide. Check this out:

- https://wiki.duraspace.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-Databaseschemachanges
- https://wiki.duraspace.org/display/DSDOC6x/Storage+Layer#StorageLayer-CustomRDBMStables,columsorviews

**Comment by dheles** [comment] 2018-12-07 22:07
Regarding the need to tell Flyway your current database version... DSpace has a process wherein the database version is automatically identified and I'm pretty sure that information is passed on to Flyway to make sure the proper migrations are applied. IDK exactly how it's done, but it's alluded to under "Upgrade your database" here: https://wiki.duraspace.org/display/DSDOC6x/Upgrading+DSpace#UpgradingDSpace-UpgradeSteps

**Comment by pdurbin** [comment] 2019-01-04 12:08
Happy New Year! What's the status of this issue?

**Comment by MrK191** [comment] 2019-01-31 15:01
Hi, I am able to work on this now, so when I will finish it i will just update the pr.

**Comment by MrK191** [comment] 2019-02-01 13:04
@poikilotherm I tried to extract app version from maven but I realized that after merge the version will be ofc overridden, so as you said the user would have to pass the variable somehow. But I don't think this should be the concern of flyway, we already have the script to migrate to the newest version. It would just over complicate things, addign some external variable to flyway, since it would be 1 time thing anyway. I think we should just stick to the idea that the repo owner should migrate as before to the newest version, and after that the flyway will take care of the migration.

**Comment by pdurbin** [comment] 2019-02-14 14:30
@MrK191 pushed some more commits to pull request #5349 and indicated in IRC that he's ready for more code review.

**Comment by pdurbin** [comment] 2019-03-05 20:15
I can't "run project" from  Netbeans (deploy to Glassfish) when I switch to https://github.com/tjanek/dataverse/commit/c1f5282b2 (I confirmed that this works fine from e707a22cf in IQSS repo). I'm attaching the errors I'm seeing ("BUILD FAILURE" and something about Guice provision errors:

[flyway-run-error.txt](https://github.com/IQSS/dataverse/files/2932657/flyway-run-error.txt)

@MrK191 can you please help me figure out why I can't deploy to Glassfish? I'd like to kick the tires on this branch (try adding a column to a table automatically) but I'm feeling pretty blocked.

I did merge the latest from "develop" into the branch. I hope I didn't break anything.

**Comment by MrK191** [comment] 2019-03-06 09:20
@pdurbin Could you try and decrease surefire plugin version to 2.22.0?

**Comment by pdurbin** [comment] 2019-03-06 16:17
@MrK191 good idea. I can deploy now after putting the surefire version back: https://github.com/tjanek/dataverse/commit/94ca97edf

**Comment by pdurbin** [comment] 2019-03-06 17:32
I tested as of 94ca97edf and I'm confused about how developers are supposed to use Flyway in Dataverse.

I deployed the code and `src/main/resources/db/migration/V1__flyway_schema_baseline.sql` was created. Good! But it's empty. Is that normal?

Then I tried adding a column ("bio") to a table ("authenticateduser") like this: https://github.com/pdurbin/dataverse/commit/ceda3ce Screenshot below.

![screen shot 2019-03-06 at 12 23 25 pm](https://user-images.githubusercontent.com/21006/53900853-73047280-400b-11e9-852d-8d085ca1621c.png)

I did a "clean and build" in Netbeans and then "Run" to deploy the changed code with the new "bio" column. I was hoping for magic to happen, that the "bio" column would be automatically created for me. Instead, I got behavior I expect from the "develop" branch. Dataverse isn't happy (white screen of death) and the following appears in server.log:

    Internal Exception: org.postgresql.util.PSQLException: ERROR: column "bio" does not exist

No new files were added to the `src/main/resources/db/migration` directory. It still has just the initial `V1__flyway_schema_baseline.sql` file. Shouldn't a new file be created? I looked a bit at https://flywaydb.org/documentation/migrations#sql-based-migrations (linked from the updated version of `sql-upgrade-scripts.rst`, which didn't help me much) but I'm not sure why my test of adding a "bio" filed automatically didn't work. What am I doing wrong?

**Comment by MrK191** [comment] 2019-03-07 08:57
@pdurbin V1__flyway_schema_baseline.sql was already created by me. The sql files are not automatically generated. Reason of it being empty is because flyway needs to create database table on already existing schema so it is empty, just treat it as "initialization" sql. If you want the new column besides adding it to the entity class, you need to create another sql with well sql inside which adds the column.
  If we wanted automatic column generation we wouldn't be using flyway since eclipse-link/hibernate already has this function buildin which you can enable (it is not recommended by hibernate team but that's another topic).

**Comment by pdurbin** [comment] 2019-03-07 21:31
@MrK191 sorry, I didn't realize that ``V1__flyway_schema_baseline.sql`` was already in the pull request. I understand now that it's an empty file you added, not a file that I created locally.

I played around with Flyway some more and just pushed d458c83 which reflects my understanding of how Flyway works (which is different than what I've been saying at standup!). I also renamed the `upgrade_v4.11_to_v4.12.sql` file because with Flyway a good deal of our process needs to change. I described the new process in the commit above and I'd like to have a "talk after" following standup on the way things work with Flyway before we pass this to QA.

In short, I was under the impression that Flyway will give us Django-style migrations where we can just change our models and the necessary SQL will be written for us. This is not how Flyway works. Rather, we still must write the SQL. The advantage of Flyway is that the SQL will be automatically run for you when you deploy the war file (as long as you name your SQL migration scripts by certain conventions and put them in the right directory). So you don't have to communicate as much with other developers or with sysadmins who are upgrading to the latest release of Dataverse. Again, I documented all of this but I'd like to talk it out. I'm also not sure if I'm happy with the example I put in the docs. I called it ``V1.1__5513-database-variablemetadata.sql`` so I guess I'm suggesting that the next number should be ``V1.2``.

Also, I did some testing with SQL update in develop (the one I moved from https://github.com/IQSS/dataverse/blob/4cf0c95ab5e87b7a825e809c219a23ce18af1303/scripts/database/upgrades/upgrade_v4.11_to_v4.12.sql ) and it seemed to work. That is to say. Before I did anything, I had a "universe" column like this:

```
dvndb=> select id,universe from datavariable limit 1;
 id | universe 
----+----------
  1 | 
(1 row)
```

Then, I deployed the code and "universe" was dropped automatically:

```
dvndb=> select id,universe from datavariable limit 1;
ERROR:  column "universe" does not exist
LINE 1: select id,universe from datavariable limit 1;
```

In the docs I mentioned that you can check the table below to see which migrations have run:

```
dvndb=> select * from flyway_schema_history;
 installed_rank | version |          description           |   type   |                  script                  | checksum  | installed_by |        installed_on        | execution_time | success 
----------------+---------+--------------------------------+----------+------------------------------------------+-----------+--------------+----------------------------+----------------+---------
              1 | 1       | << Flyway Baseline >>          | BASELINE | << Flyway Baseline >>                    |           | dvnapp       | 2019-03-06 11:15:30.587043 |              0 | t
              2 | 1.1     | 5513-database-variablemetadata | SQL      | V1.1__5513-database-variablemetadata.sql | 767369850 | dvnapp       | 2019-03-07 15:44:18.282634 |             13 | t
(2 rows)
```

**Comment by pdurbin** [comment] 2019-03-08 21:05
@landreev here are the file names DSpace uses:

```
V1.1__Initial_DSpace_1.1_database_schema.sql
V1.2__Upgrade_to_DSpace_1.2_schema.sql
V1.3__Upgrade_to_DSpace_1.3_schema.sql
V1.4__Upgrade_to_DSpace_1.4_schema.sql
V1.5__Upgrade_to_DSpace_1.5_schema.sql
V1.6__Upgrade_to_DSpace_1.6_schema.sql
V1.7__Upgrade_to_DSpace_1.7_schema.sql
V1.8__Upgrade_to_DSpace_1.8_schema.sql
V3.0__Upgrade_to_DSpace_3.x_schema.sql
V4.0__Upgrade_to_DSpace_4.x_schema.sql
V4.9_2015.10.26__DS-2818_registry_update.sql
V5.0_2014.08.08__DS-1945_Helpdesk_Request_a_Copy.sql
V5.0_2014.09.26__DS-1582_Metadata_For_All_Objects.sql
V5.6_2016.08.23__DS-3097.sql
V5.7_2017.04.11__DS-3563_Index_metadatavalue_resource_type_id_column.sql
V6.0_2015.03.07__DS-2701_Hibernate_migration.sql
V6.0_2016.01.03__DS-3024.sql
V6.0_2016.02.25__DS-3004-slow-searching-as-admin.sql
V6.0_2016.04.01__DS-1955_Increase_embargo_reason.sql
V6.0_2016.04.04__DS-3086-OAI-Performance-fix.sql
V6.0_2016.04.14__DS-3125-fix-bundle-bitstream-delete-rights.sql
V6.0_2016.05.10__DS-3168-fix-requestitem_item_id_column.sql
V6.0_2016.07.21__DS-2775.sql
V6.0_2016.07.26__DS-3277_fix_handle_assignment.sql
V6.0_2016.08.23__DS-3097.sql
V7.0_2017.10.12__DS-3542-stateless-sessions.sql
```

That's from https://github.com/DSpace/DSpace/tree/master/dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/postgres via https://wiki.duraspace.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-Databaseschemachanges . Here's a screenshot of what's written there:

![Screen Shot 2019-03-08 at 4 05 26 PM](https://user-images.githubusercontent.com/21006/54055762-067ca580-41bc-11e9-9bb2-1540301e831c.png)

**Comment by pdurbin** [comment] 2019-03-14 13:58
As agreed in tech hours on Tuesday we'll try using the previous/current release of Dataverse (4.11 as of this writing) rather than the arbitrary "1.1" I was using previously. I made this change in 0c10897 and also added a troubleshooting section because I encountered "FlywayException: Validate failed: Detected applied migration not resolved locally" and was unable to deploy until I deleted the old "1.1" migration from the `flyway_schema_history` database table. Here's how that table looks now:

```
dvndb=> select * from flyway_schema_history;
 installed_rank | version |          description           |   type   |                  script                   | checksum  | installed_by |        installed_on        | execution_time | success 
----------------+---------+--------------------------------+----------+-------------------------------------------+-----------+--------------+----------------------------+----------------+---------
              1 | 1       | << Flyway Baseline >>          | BASELINE | << Flyway Baseline >>                     |           | dvnapp       | 2019-03-06 11:15:30.587043 |              0 | t
              2 | 4.11    | 5513-database-variablemetadata | SQL      | V4.11__5513-database-variablemetadata.sql | 767369850 | dvnapp       | 2019-03-14 09:34:30.167735 |              7 | t
(2 rows)
```

Please note that I removed "database migration script" as one of the artifacts we will need to upload when making releases. Currently, it's one of four artifacts listed at http://guides.dataverse.org/en/4.11/developers/making-releases.html#make-artifacts-available-for-download as shown in the screenshot below:

![Screen Shot 2019-03-14 at 9 50 34 AM](https://user-images.githubusercontent.com/21006/54362037-a1530500-463e-11e9-8a26-c0cb187ef675.png)

That is to say, developers aren't the only ones who will benefit from Flyway. Sysadmins will be able to simply deploy the latest war file and SQL migrations will be run automatically. I added a note about this in 3b07490bb.

**Closed** 2019-03-14 18:00 UTC
Labels: Status: QA
