### ISSUE TITLE
Shibboleth login fails (in specific case involving multiple accounts and multiple e-mails)

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#6014] opened 2019-07-11 19:44 UTC
On 4.15.1 (on Harvard Dataverse) I tried to login using shib. I got an Internal Server (500) error. The logs show:
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "authenticateduser_email_key"
  Detail: Key (email)=(EMAIL_ADDRESS) already exists.

I'm pretty sure we used to handle this, so this seems to be a regression.

**Comment by djbrooke** [comment] 2019-08-13 18:42
@scolapasta - can you try this again and provide some more details? @sekmiller and I dug into this a bit and are stumped. Thank you!

**Comment by scolapasta** [comment] 2019-08-29 19:37
After further testing, we learned that the use case is more specific:
- have logged in with shibboleth before and have a dataverse account (account 1)for it with e-mail 1
- create a native account (account 2) with email 2
- (on the IP side, the e-mail gets changed to e-mail 2)
- try logging in via shib; since the persistentIdentifier that the IP provides is the same, we try to update the e-mail address for account 1 to email 2; but since it's in use by account 2, an exception is thrown

Since this is rare enough, we decided just to catch this happening and throw a user friendly error message. The user would contact support and then we could either merge their accounts or walk them through changing the email address associated with account 2.

**Comment by pdurbin** [comment] 2019-08-30 09:49
@scolapasta can we close this issue now that pull request #6136 has been merged?

As you, @sekmiller and I discussed yesterday, to me the root cause is how Dataverse is too strict about requiring field from Shibboleth that we don't require for OAuth. See #3749 for examples of how many people can't log into Dataverse using their institutional credentials due to this strictness.

#3486 links to the meeting with @mercecrosas I mentioned: 2015-04-30 Dataverse User Accounts and Auth Meeting - https://docs.google.com/document/d/157sw9gaFGwrb0EtCGGlLMxSg0cooHfKEvIsjcebPcA8/edit?usp=sharing

Here's a dump of those meeting notes:

---

2015-04-30 Dataverse User Accounts and Auth Meeting

Attendees: Merce Crosas and Philip Durbin

* Where information about users comes from
   * Institution (Shibboleth/OAuth, etc.)
      * uneditable
         * unique identifier for user within institution
         * unique identifier for institution
         * friendly name of institution (i.e. "Harvard University" from Shibboleth, if provided, otherwise the unfriendly URL)
         * unique identifier for school, department, lab, etc. (if provided)
         * friendly name of school, department, lab, etc. (i.e. "HMS" from Shibboleth, if provided)
      * initial population of certain fields (if provided), later editable
         * required fields (make user fill in if not provided)
            * first name
            * last name
            * email address[a]
            * username (best possible and unique based on email or other available info)
         * optional fields
            * affiliation/friendly name of institution (i.e. "Harvard University")
   * From user, who can change these at will (subject to uniqueness constraints) - https://github.com/IQSS/dataverse/issues/2046
      * first name
      * last name
      * email address (if unique)
      * username (if unique)
         * to be done later because of large refactoring necessary per https://github.com/IQSS/dataverse/issues/1151 and https://github.com/IQSS/dataverse/issues/1445
      * affiliation, institution, school, department, lab, etc.?
      * ORCID ID - https://github.com/IQSS/dataverse/issues/923 
         * Eventually, we may be able to get ORCID IDs from Shibboleth in the form of a SAML assertion of an "eduPersonOrcid" attribute per the (unfinalized) spec linked from https://spaces.internet2.edu/display/macedir/ORCID+and+other+researcher+IDs




[a]Today I learned that some installations of Dataverse may receive *multiple* email addresses from their identity providers. The Dataverse code currently only works with a single email address. The related issue is https://github.com/IQSS/dataverse/issues/2512

---

I don't know if the work @poikilotherm is planning for #5974 will help with the situation or not.

**Closed** 2019-08-30 13:58 UTC
Labels: Small
