### ISSUE TITLE
Metadata added to draft dataset becomes visible in previously published version before publication

### ISSUE THREAD

**Issue by tdilauro** [IQSS/dataverse#3658] opened 2017-03-01 20:02 UTC
We are seeing this problem with some fields defined in our custom [software (SW) metadata block](https://github.com/tdilauro/dataverse-ansible-role/blob/master/roles/dataverse/files/dv-mdblocks/jhuSoftware.tsv).

It appears that when selecting a license in the SW metadata block that has text in the displayName column of the license controlled vocab (e.g., ["GPL v3"](https://github.com/tdilauro/dataverse-ansible-role/blob/master/roles/dataverse/files/dv-mdblocks/jhuSoftware.tsv#L130)), some data leaks out of the draft instance, even though it has not yet been published. We're not fully sure which information leaks out, but at least the License, Contributor (partially), and Dependencies (partially) do.

After changing the license from MIT to GPL on [a record in our development instance (behind firewall)](https://dms-dev02.mse.jhu.edu/dataset.xhtml?persistentId=doi:10.5072/FK2/KGIGBR), the GPL license showed up in the public view of the dataset, even though the version had not yet been published. Changing it back to MIT had no effect, it still showed GPL until the dataset was actually published.

**Comment by pdurbin** [comment] 2017-03-10 00:41
@tdilauro thanks for sharing that `jhuSoftware.tsv` file! It might be potentially helpful for the CodeMeta project ( http://codemeta.github.io ), which @mercecrosas is part of.

To be honest, I'm having a little trouble following this bug report. Is it reproducible with any of the standard metadata blocks that ship with Dataverse? If you think the problem is isolated to your custom metadata block, do you need help improving it? Screenshots might help me understand what you're seeing and what you mean by information leaking out.

**Comment by pdurbin** [comment] 2017-06-23 12:14
@tdilauro I'm closing this issue but if you have more information to provide I'd be quite happy to re-open it. Thanks.

**Closed by pdurbin** 2017-06-23 12:14 UTC
Labels: Component: Publishing & Versions
