### ISSUE TITLE
Inconsistencies in reported size of files

### ISSUE THREAD

**Issue by Xarthisius** [IQSS/dataverse#5321] opened 2018-11-15 21:30 UTC
Search API returns size that's inconsistent with the actual size of file being downloaded. E.g.

```
$ curl -s https://dataverse.harvard.edu/api/search?q=filePersistentId:JKTORG | jq '.data.items[0].size_in_bytes'
12025
```

whereas

```
$ curl -s -I https://dataverse.harvard.edu/api/access/datafile/3040230 | grep Content-Length
Content-Length: 12100
```

**Comment by Xarthisius** [comment] 2018-11-15 21:34
Also md5sum is being reported for original format (csv), whereas `url` points to a tab file

**Comment by pdurbin** [comment] 2018-11-15 21:38
@Xarthisius if you want the original file please add "format=original" as a query parameter like this:

https://dataverse.harvard.edu/api/access/datafile/3040230?format=original

See http://guides.dataverse.org/en/4.9.4/api/dataaccess.html#basic-file-access for a list of parameters.

Does this help with the file size inconsistency?

**Comment by Xarthisius** [comment] 2018-11-15 21:39
@pdurbin no, it doesn't match either of them, for `original` it's:

```
$ curl -s -I 'https://dataverse.harvard.edu/api/access/datafile/3040230?format=original' | grep Content-Length
Content-Length: 11684
```

**Comment by pdurbin** [comment] 2018-11-15 21:39
Bummer. Thanks. 😄

**Comment by pameyer** [comment] 2018-11-15 21:46
Not sure if it's a factor, but I could see the S3 chunk/block size as being a factor that could be contributing to this inconsistency.  It might be interesting to see if similar behaviour was seen with POSIX storage.

**Comment by pdurbin** [comment] 2018-11-15 21:47
@pameyer could be. @Xarthisius do you want to try the same test on https://demo.dataverse.org which doesn't use S3?

**Comment by Xarthisius** [comment] 2018-11-15 21:52
Sure!

```
$ curl -s https://demo.dataverse.org/api/search?q=filePersistentId:8BVIX2 | jq '.data.items[0].size_in_bytes'
36843
$ curl -s -I https://demo.dataverse.org/api/access/datafile/300662 | grep Content-Length
Content-Length: 36920
$ curl -s -I https://demo.dataverse.org/api/access/datafile/300662?format=original | grep Content-Length
Content-Length: 26465
```

**Comment by pameyer** [comment] 2018-11-15 22:09
@Xarthisius thanks!  It's not just S3.

**Comment by pameyer** [comment] 2018-11-15 22:56
Slightly more investigation into https://demo.dataverse.org/api/access/datafile/300662 ; downloaded tab format and original for comparison:

- `Content-Length` header on access API matches the size of the files (python3 / jython 2.7.0 `rb`) for both original and reformatted; suggests that the DB results driving the search (and files section of dataset API) are inaccurate.
- `Content-Length` and `files` section of native API match for an image file w\ in the same dataverse on demo; suggesting that the problem is related to ingest.

This makes me think that the size of an ingested file is determined based on whatever unified representation gets used for UNF calculation, rather than storage size - but I don't know enough in that area to know if that's reasonable or not.

The checksum swap seems like a bug to me - but wouldn't be surprised if tabular data folks were more concerned about UNF matches than checksum matches.

**Comment by landreev** [comment] 2018-11-15 23:00
@Xarthisius et al:
demo.datafverse.org also uses a Posix file system (it just lives on AWS). 
This inconsistency in size should only be the case with files ingested as tabular data.
The size reported by the search API is the actual size in bytes, as saved on the filesystem. Here's the physical file for the file id=300662 from the example above: 
```
# ls -l 10.5072/FK2/N7YHEY/167188a391e-300c2dad66c1
-rw-r--r--. 1 root root 36843 Nov 15 18:03 10.5072/FK2/N7YHEY/167188a391e-300c2dad66c1
```
The extra bytes you get when you download the file through the API are the *variable header* we add to tabular files by default: 
```
# curl -s https://demo.dataverse.org/api/access/datafile/300662 | head -1 
#metadataBlock	name	dataverseAlias	displayName	E	F	G	H	I	J	K	L	M	N	O	S
```
# curl -s https://demo.dataverse.org/api/access/datafile/300662 | head -1  | wc
      1      19      77
```
hence the total size 36920 bytes

**Comment by landreev** [comment] 2018-11-15 23:02
(there was some bad formatting in my last comment - should be fixed now)

**Comment by landreev** [comment] 2018-11-15 23:13
@Xarthisius et al: 
Here's an annoying discovery: 
We used to provide a way to download the tabular file as is, without the tabular header, via
/api/access/datafile/[FILEID]?noVarHeader=true
but - unless I'm missing something, it looks like we've lost that, and the noVarHeader argument is no longer being honored...

**Comment by landreev** [comment] 2018-11-15 23:23
(just edited a couple of small things above, for clarity)

**Comment by Xarthisius** [comment] 2018-11-16 14:41
I checked that `/api/datasets` exhibits the same problem:

```
$ curl -s https://demo.dataverse.org/api/datasets/:persistentId?persistentId=doi:10.5072/FK2/N7YHEY | jq '.data.latestVersion.files'
[
  {
    "label": "citation.tab",
    "restricted": false,
    "version": 2,
    "datasetVersionId": 37426,
    "dataFile": {
      "id": 300662,
      "persistentId": "doi:10.5072/FK2/N7YHEY/8BVIX2",
      "pidURL": "https://doi.org/10.5072/FK2/N7YHEY/8BVIX2",
      "filename": "citation.tab",
      "contentType": "text/tab-separated-values",
      "filesize": 36843,
      "storageIdentifier": "167188a391e-300c2dad66c1",
      "originalFileFormat": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "originalFormatLabel": "MS Excel (XLSX)",
      "UNF": "UNF:6:TKPMHywLQ/mUjLTNYTskAQ==",
      "rootDataFileId": 298540,
      "previousDataFileId": 298540,
      "md5": "de6b320f891115ce23d7a4b28727ebdb",
      "checksum": {
        "type": "MD5",
        "value": "de6b320f891115ce23d7a4b28727ebdb"
      }
    }
  }
]
```

That's more problematic, since it turns current ingestion method's cost from O(1) to O(n), because I need to grab the 'Content-Length' from `/access/datafile/{}?format=original` for each file.

**Comment by landreev** [comment] 2018-11-16 16:17
The /datasets api exhibits the same behavior because it uses the same data from the database. Once again, this behavior is correct - this is the true size of the file on disk. 
The header thing is confusing and counter-intuitive. But it makes sense actually. The reason the variable name header is not stored in the file is that the contents of a file are *data*. And the names of the variables are *metadata*; and are mutable. (in theory at least; as in, right now there is no API for editing the variable names. but it is in the pipe line, and it is a perfectly reasonable use case - a researcher may want to change the names of the variables after ingest, to make them more descriptive for example). 
And the reason the variable header is added to the output by default is that, apparently, real life users never really wanted to download the tab data without it. So it became the default and, by now, a matter of legacy. 
To the point where nobody ever noticed or complained when the "no header" option disappeared.

**Comment by landreev** [comment] 2018-11-16 16:29
As for your other comment - if you want the size of the saved original in the output of the /datasets api, that we can achieve easily. I've been thinking myself that the original file size should actually be saved in the database, and added to the API output for tabular files; in addition to the originalFileFormat 
like
```
"originalFileFormat": "application/x-stata",
"originalFileSize": 123456,
```
That would be a very easy fix; I'll use this occasion to open an issue for it and will try to squeeze it into the next release.

**Comment by Xarthisius** [comment] 2018-11-16 16:30
> As for your other comment - if you want the size of the saved original in the output of the /datasets api, that we can achieve easily. I've been thinking myself that the original file size should actually be saved in the database, and added to the API output for tabular files; in addition to the originalFileFormat
> like
> 
> ```
> "originalFileFormat": "application/x-stata",
> "originalFileSize": 123456,
> ```
> That would be a very easy fix; I'll use this occasion to open an issue for it and will try to squeeze it into the next release.

That would be great and solve all my problems!

**Comment by landreev** [comment] 2018-11-16 17:11
OK, opened #5323
Once again, I'll try to prioritize this, seeing how it is both useful and fairly trivial. 

But,

> That's more problematic, since it turns current ingestion method's cost from O(1) to O(n), because I need to grab the 'Content-Length' from `/access/datafile/{}?format=original` for each file.

Just to make sure we are on the same page, in that these are 2 separate issues: 

1) The filesize in the API output not matching the content-length of the actual bytes from /api/access/datafile for a tabular file (on account of the variable name header); and
2) For a tabular file, no easy way to get the size of the saved original, without making an `/api/access/datafile{}?format=original` call. 

#5323 will solve 2), but not 1).

**Comment by Xarthisius** [comment] 2018-11-16 17:22
That's perfectly fine. I think we prefer to ingest the originals anyway, so 2) is order of magnitude more important for me.

**Comment by pameyer** [comment] 2018-11-16 21:20
@Xarthisius it might be worth a separate issues for the checksum inconsistency you mentioned (I'll defer on the `noVarHeader` question).

**Comment by djbrooke** [comment] 2018-11-28 21:57
We estimated the other items spun off from this and we'll track those individually. Is there a checksum inconsistency that needs to be tracked as well? If so, feel free to open a separate ticket.

**Closed by djbrooke** 2018-11-28 21:57 UTC
Labels: Feature: File Upload & Handling, Status: Ready, Type: Bug, ready for estimation
