### ISSUE TITLE
As a researcher, I want to know what dataset/dataverse a contact email is referring to so that I can follow up

### ISSUE THREAD

**Issue by suenjedt** [IQSS/dataverse#1916] opened 2015-04-08 16:00 UTC
I tried to contact dataset contacts and received the emails as expected. I just wanted to raise that there was no context info given: which dataset/dataverse, who wrote (I was logged in) etc. Thought that might be helpful for potential recipients. 
![screen shot 2015-04-08 at 11 59 17](https://cloud.githubusercontent.com/assets/7300319/7049329/b7bcb7b0-dde6-11e4-8b86-bc691090c444.png)
![screen shot 2015-04-08 at 11 59 00](https://cloud.githubusercontent.com/assets/7300319/7049328/b7bc3fd8-dde6-11e4-8821-7bfdcb4c53ab.png)

**Comment by eaquigley** [comment] 2015-04-21 19:06
Great suggestion @suenjedt we should do what we do for notifications where we include links to the dataset and dataverses they are referencing.

**Comment by pdurbin** [comment] 2017-01-06 16:13
> who wrote (I was logged in)

This part is mentioned in #3545.

**Comment by pdurbin** [comment] 2017-01-06 16:26
#2882 seems related as well.

**Comment by pameyer** [comment] 2017-01-06 16:49
At @pdurbin 's request; if this includes username (for authenticated users), than #3545 is a duplicate of this one.

**Comment by mheppler** [comment] 2018-03-23 20:41
This issue was reported again by Gary in Slack today.

>All emails that go out (especially the automatic ones) need to have contact info at the end of the signature.  if it is going to the wrong person, that person needs to have someone to respond to.  we can’t assume, as this message does, that we are always right in who the email is going to.  please fix this and let’s look for other examples of this.  thanks

![image](https://user-images.githubusercontent.com/687227/37852460-0d1a25f0-2eb9-11e8-9b26-603ac53eb682.png)

**Comment by djbrooke** [comment] 2018-04-04 18:49
- The focus of this is that a contact button is being pressed on a dataverse/dataset/file(?) page and the dataset information (context) does not make it to the recipient.

**Comment by pdurbin** [comment] 2018-04-04 21:02
Here's the "before" picture... I went to https://doi.org/10.7910/DVN/TJCLKP (a dataset of mine) and filled in the form like this:

![screen shot 2018-04-04 at 5 00 42 pm](https://user-images.githubusercontent.com/21006/38334596-bc4e61de-3829-11e8-9388-cbc838ae6b8f.png)

Here's the email I got as the contact for the dataset:

![screen shot 2018-04-04 at 5 01 28 pm](https://user-images.githubusercontent.com/21006/38334625-c9f5edd4-3829-11e8-8c10-7618d88a8111.png)

I agree that some more context would be appreciated! I did this test on version 4.8.6.

**Comment by pdurbin** [comment] 2018-04-05 18:29
In 8652ffa I started making the "Contact" button code testable and added context to the message based on if you are on a dataverse, dataset or file. Next steps

- [ ] Delete old/existing untestable code.
- [ ] Figure out why context for file ends up being context for dataset. I suspect when the "Contact" button was introduced, there was not yet a landing page for individual files.

**Comment by pdurbin** [comment] 2018-04-06 16:19
I just made pull request #4571 and moved this issue to code review at https://waffle.io/IQSS/dataverse

**Comment by pdurbin** [comment] 2018-04-06 19:05
As I mentioned to @djbrooke I'm making some somewhat arbitrary decisions about what context to include in the email. I figured the main thing is to provide a URL to the dataverse, dataset, or file, which I did at the top. Here are some examples:

## Dataverse Contact

![screen shot 2018-04-06 at 2 57 42 pm](https://user-images.githubusercontent.com/21006/38439283-1368994e-39ab-11e8-8fa5-ae42c633217c.png)
![screen shot 2018-04-06 at 2 57 58 pm](https://user-images.githubusercontent.com/21006/38439282-135defe4-39ab-11e8-8821-adf076dc5947.png)

## Dataset Contact


![screen shot 2018-04-06 at 2 48 34 pm](https://user-images.githubusercontent.com/21006/38439286-139e2514-39ab-11e8-9416-ccc29f6975b2.png)
![screen shot 2018-04-06 at 2 48 56 pm](https://user-images.githubusercontent.com/21006/38439285-139307a6-39ab-11e8-838b-4872289ab423.png)

## File (Dataset) Contact

![screen shot 2018-04-06 at 3 03 24 pm](https://user-images.githubusercontent.com/21006/38439392-7a2886f8-39ab-11e8-8cb3-95159c232577.png)
![screen shot 2018-04-06 at 3 03 08 pm](https://user-images.githubusercontent.com/21006/38439393-7a35c0d4-39ab-11e8-9bef-d817c95a060b.png)

## Contact Support

![screen shot 2018-04-06 at 2 30 04 pm](https://user-images.githubusercontent.com/21006/38439287-13aa245e-39ab-11e8-94a9-0fab08109e3f.png)
![screen shot 2018-04-06 at 2 49 25 pm](https://user-images.githubusercontent.com/21006/38439284-1376ca46-39ab-11e8-8702-d7af06382b53.png)

Feedback from anyone is welcome!

**Comment by dlmurphy** [comment] 2018-04-06 20:00
This is a marked improvement over the old email format! I have a few thoughts on potential other improvements we could make:

- Subject line: It might be nice to indicate somehow that this email comes from a Dataverse user. It's a bit long, but perhaps the subject line could be something like: 

> _Message from Dataverse User: "[user-entered subject line]"_

- Message body: It might be nice to include the name of the dataset or file in the body of the message. Perhaps it could be something like:

> The following message was sent from the contact button of [_dataset or file name, in italics_] at [url of dataset or file]
> 
> **Message:** [body of message]

- For the support form, maybe the subject line could read

> Support Request: [user-entered subject line]

**Comment by pameyer** [comment] 2018-04-06 20:18
One slightly less extensive suggestion would be to move the "context" part of the message after the user-generated part.  Aka - 
`
Have you looked to see if this is too green in light of the recent paper?

Best,
Bob the Post-Doc

You're receiving this message from the contact button of The Spruce Dataset ($url)
`

**Comment by sbarbosadataverse** [comment] 2018-04-08 03:04
@pdurbin Thanks, Phil. Is it possible to get the dataset DOI to show up in the contact dialogue box? Dataverse name is fine, if that is the contact point, but for datasets it would make send to just use the DOI

**Comment by mheppler** [comment] 2018-04-10 13:54
Closed duplicate issue **Email Dataset Contact - Email needs more information when authors replyto a user #2882**. In that issue @sbarbosadataverse commented on on Jan 21, 2016.

> I've been using the email icon to contact authors and when they reply I get no indication which dataset/dataverse they are replying from. Would be more helpful to have this info attached to the email dialogue box in some way.

**Comment by mheppler** [comment] 2018-04-11 13:54
![screen shot 2018-04-09 at 5 16 51 pm](https://user-images.githubusercontent.com/687227/38621199-5ade0ca2-3d6e-11e8-828f-6b81da48a07d.png)

**Comment by pdurbin** [comment] 2018-04-11 17:49
@mheppler one of the challenges with `Hello {dataset.contact.FirstName + LastName},` is that Contact Name is freeform. Also, we suggest the form "LastName, FirstName" (i.e. "Brady, Tom") like this:

![screen shot 2018-04-11 at 1 51 18 pm](https://user-images.githubusercontent.com/21006/38633948-2268f14a-3d8f-11e8-928d-44eeb6b04a51.png)

**Comment by pdurbin** [comment] 2018-04-12 17:02
Just a quick update that I'm working away on the code and I think YAML-style separators (`---`) look better. Like this:

> Hello Tom Brady,
> 
> You have just been sent the following message from hsimpson@mailinator.com via the LibraScholar hosted dataset titled "Darwin's Finches" (doi:10.7910/DVN/TJCLKP):
> 
> `---`
> 
> Let's talk!
> 
> `---`
> 
> LibraScholar SWAT Team
> support@librascholar.edu
> 
> Go to dataset https://dataverse.librascholar.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/TJCLKP
> 
> You received this email because you have been listed as a contact for the dataset. If you believe this was an error, please contact LibraScholar SWAT Team at support@librascholar.edu. To respond directly to the individual who sent the message, simply reply to this email.

I also made a couple other small tweaks. Note that the contact form doesn't let you say your name so above you just see the email address but I guess I'll be adding that.

Finally, at standup this morning we decided that #4580 is out of scope for now but it's highly related and sounds like a real issue based on my reading of https://help.hmdc.harvard.edu/Ticket/Display.html?id=260778

**Comment by pdurbin** [comment] 2018-04-12 19:10
9c56a0f has some of the progress I've made. Note that at the dataverse level, we do not persist the contact name. We only persist the email address. Here's a screenshot:

![screen shot 2018-04-12 at 3 10 18 pm](https://user-images.githubusercontent.com/21006/38698592-96b6de02-3e63-11e8-8975-c24a607c752b.png)


So, I'll try to come up a reasonable alternative to "Hello Tom Brady," for the greeting.

**Comment by pdurbin** [comment] 2018-04-13 19:03
@mheppler @scolapasta @dlmurphy and anyone else who's interested in what text appears in the "bundle", I think I'm mostly done messing with the text as of 6c22b9e if you'd like to take a look at the "diff" in Bundle.properties at https://github.com/IQSS/dataverse/pull/4571/files

Please note that since I've been focused on providing more context for dataverses, datasets, and files, I haven't thought much about adding more context to the generic "Support" emails but if someone wants to suggest something I can probably work it in without too much trouble since it's the same code.

I'm staying on this issue to do some testing to make sure I didn't break anything with all my refactoring to make the code testable.

Ok, also, @qqmyers popped in IRC this morning and he's going to take a look at related issue #4580. I explained that we're working on the content first but then we'll want to address how in some cases these emails aren't being delivered, which is what that other issue is about.

**Comment by mheppler** [comment] 2018-04-13 19:11
Thanks, @pdurbin. I will take a quick look at the PR. For the support emails, I think we can go a little more generic. I've cut down the template to something a little more streamline since we don't need to pass any dataverse, dataset, file info.

```
{Harvard Dataverse Support}<br>
<br>
The following message from {usr.contact.email}...<br>
<br>
----<br>
<br>
{usr.contact.message}<br>
<br>
----<br>
<br>
To respond directly to the individual who sent the message, simply reply to this email.
```

**Comment by dlmurphy** [comment] 2018-04-13 19:57
The bundle text looks good to me, thanks!

**Comment by pdurbin** [comment] 2018-04-13 20:38
Ok, as of 197c57d I think the pull request is in pretty good shape for code review.

We could keep doing more on this branch, including:

- [ ] update the form to ask for the user's name (instead of just their email address
- [ ] add more context to the support emails (see suggestion from @mheppler above)

I'll keep myself on this issue for now but developers are welcome to give me feedback on the code.

**Comment by pdurbin** [comment] 2018-04-16 15:38
In 038d5a3 I went ahead and added more context to the support emails, with minor tweaks approved by @mheppler 

@mheppler and I are on the same page that at this time I am not going to pursue adding a field for "full name" or whatever we call it. The main reason for this is that I'd have to touch a lot of files and this isn't a high priority. Here's a screnshot of the files we'd need to modify:

![screen shot 2018-04-16 at 11 26 02 am](https://user-images.githubusercontent.com/21006/38819618-e29e91a8-4169-11e8-8c97-ff1f204c0f6c.png)

In addition to the files above the change would need to be made in `contactFormFragment.xhtml`. The benefits of making this change in the future are two-fold. First, "From" in the current form is somewhat ambiguous in that it could mean "email address" or "name". Here's a screenshot:

![screen shot 2018-04-16 at 11 34 04 am](https://user-images.githubusercontent.com/21006/38819697-175254d4-416a-11e8-91d5-a1e3c60ceb2f.png)

If or when we add "full name" we should decide how to label it. Perhaps we could write "Your Name" and "Your Email" like this:

![screen shot 2018-04-16 at 11 33 33 am](https://user-images.githubusercontent.com/21006/38819698-17730f94-416a-11e8-851d-6526b1d53132.png)

The second benefit of having the second field is that we'll be able populate `{usr.contact.FirstName + LastName}` in the desired design above, which says "You have just been sent the following message from {usr.contact.FirstName + LastName}". Right now the code just always puts the email address there instead.

Since I think I'm done hacking on the code (barring any bugs I introduced), I'm taking myself off this issue and I'm ready for code review.

**Comment by landreev** [comment] 2018-04-17 01:54
Reviewed, moved into QA.

**Comment by kcondon** [comment] 2018-04-17 20:52
Tested new context email works as described with the exception of
Support email says, "To respond directly to the individual who sent the message, simply reply to this email." but this does not currently work this way according to @pdurbin

**Comment by pdurbin** [comment] 2018-04-17 22:26
@kcondon sorry, I believe we have a misunderstanding. It does work that way, or it should. Support emails are sent from the email address provided in the support form. That's the "from" address. So replying to that from address should reach the individual who provided an email address in the support form.

Of course, if you're logged in, when you fill the the support form, you shouldn't be asked for an email address. The email on file for your account will be used.

I hope this all makes sense!

**Comment by mheppler** [comment] 2018-04-18 14:40
Updated support email template text to remove inaccurate reply instructions.

```
contact.context.support.ending=\n\n---\n\nMessage sent from Support contact form.
```

The issue for **Contact Us Email: Set the reply to address to be from the user, from address from dataverse. Otherwise email blocked. #4580** should address existing issues with the reply address. I will add a comment on that issue as well. There will need to be consideration for how our RT system works when we change the from and reply fields in the support emails.

**Closed** 2018-04-18 17:05 UTC
Labels: Feature: Email Dataset Contact, Status: QA, Status: UX & UI
