### ISSUE TITLE
New API: Add api end point to move datasets

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4405] opened 2018-01-10 17:40 UTC
We frequently get support requests to move datasets. Adding an API endpoint to do this would be empower end users to do this.

**Comment by mheppler** [comment] 2018-01-10 17:53
Related/duplicate of #2226 from 2015-06-01.

**Comment by djbrooke** [comment] 2018-01-10 21:22
Questions from backlog grooming:

- How are guestbooks handled? Versions? Templates? Groups? 
- Doing this first makes #4406 easier
- If not superadmin only, what permissions are needed on both dataverses?

**Comment by kcondon** [comment] 2018-01-10 22:28
Note: we currently move a dataset by updating the owner_id in the dvobject table to be the new parent dv and the indexing the moved dataset:

Move dataset, id=16 to dataverse, id=6:
update dvobject set owner_id=6 where id=16;
Index dataset:
curl http://localhost:8080/api/admin/datasets/16

Note: when moving dataverses (another ticket) you do not need to move their child datasets directly but you do need to reindex them.

**Comment by sekmiller** [comment] 2018-02-08 20:13
Slight change in process for datasets with guestbooks being moved to a dataverse where that guestbook is not available.  The user is warned that the guestbook is not in the target dataverse and that she may use 'forceMove=true' to complete the move. The guestbook is then removed from the dataset.

**Closed** 2018-02-08 22:17 UTC
