### ISSUE TITLE
URL link: add links to fields that allow URL

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2457] opened 2015-08-13 19:42 UTC
the fields exists have values and should show as a link rather than the url address

![screen shot 2015-08-13 at 3 50 18 pm](https://cloud.githubusercontent.com/assets/8322346/9259804/ccf497d4-41d1-11e5-9138-8ac84c0c80af.png)

**Comment by sbarbosadataverse** [comment] 2016-01-14 18:33
@mcrosas 
Hi Merce:
Any idea when this can be corrected? Currently all the URLs appear as the entire address instead of a link.

**Comment by kcondon** [comment] 2016-04-08 16:43
This is a duplicate of #1625 . Closing this, added reference in other.

**Closed by kcondon** 2016-04-08 16:43 UTC
Labels: Component: Metadata, Component: Migration, Priority: Medium, Status: Duplicate, Status: Triaged, Type: Bug, Type: Feature
