### ISSUE TITLE
update travis.yml for Java 11

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#7537] opened 2021-01-26 15:56 UTC
Travis still points at Java 1.8, so Travis (and therefore Coveralls) are now failing. These should be updated for Java 11. PR forthcoming.

**Comment by djbrooke** [comment] 2021-01-26 16:00
Closing as a duplicate of #7536

**Closed by djbrooke** 2021-01-26 16:00 UTC

**Comment by mheppler** [comment] 2021-01-26 16:06
@pdurbin by a hair in a photo finish!
