### ISSUE TITLE
Allow to send a message when Approving or Rejecting a data access request

### ISSUE THREAD

**Issue by mercecrosas** [IQSS/dataverse#2139] opened 2015-05-08 00:25 UTC
When a data owner rejects or approves a request to access his/her data, he/she should be able to add a message or comments for the requestor. The message should be added to the notification sent to the requestor.

**Comment by pdurbin** [comment] 2017-06-25 15:21
Related: #3943

**Comment by pdurbin** [comment] 2017-06-25 15:22
I believe this is a duplicate of #3702.

**Comment by stevenmce** [comment] 2017-07-05 00:09
Marina our developer @mdmADA is working on the "Request a access" and guestbook code at the moment to customise for our needs. We are testing it out at the moment, so will circulate for everyone once we have it to a suitable state. We are probably not incorporating custom notes in version 1, but would definitely like to leverage the API being proposed to support custom responses to users when it is available. Definitely keen to see who else is interested and whether we can integrate it into the main code base.

**Comment by cmbz** [comment] 2024-08-20 15:27
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Closed by cmbz** 2024-08-20 15:27 UTC
Labels: UX & UI: Design, Type: Suggestion, Feature: Permissions, Feature: Request Access Workflow, User Role: Depositor
