### ISSUE TITLE
View File Versions

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#3241] opened 2016-08-05 15:45 UTC
The user may view the previous versions of a file, if they exist
- [ ] via UI
  - [ ] Includes the versions tab on the Dataset page and the written description of differences between versions.
- [ ] via API

**Comment by djbrooke** [comment] 2016-09-02 19:41
@mheppler - can you link up the mockups here so that we can review and move to ready? Thanks!

**Comment by mheppler** [comment] 2016-09-07 19:45
Mockups: [Files (All Things) - Admin - Dataverse 4.2 and BEYOND...](https://iqssharvard.mybalsamiq.com/projects/filesprovenancefacetsfilter-dataverse40/grid)

![file-replace-step2](https://cloud.githubusercontent.com/assets/687227/18326057/0b4bffc6-7512-11e6-92a9-e20d46058896.jpeg)

![file-versions](https://cloud.githubusercontent.com/assets/687227/18326056/0b49c74c-7512-11e6-8f00-0bab76940bae.jpeg)

**Comment by mheppler** [comment] 2016-09-07 19:50
Related to/duplicate of: Files: Ability to Replace a File Instead of Deleting #2290

**Comment by djbrooke** [comment] 2016-10-18 20:42
@mheppler - sending this your way, as you were going to update some wireframes - thanks!

**Comment by mheppler** [comment] 2016-11-10 19:59
Discussion on some outstanding issues was made in this [File Pg - UI Review](https://docs.google.com/document/d/1T925vuiC1TZlUk9mXUrSRjlGFMX5LoAg4uOBTe5AqrA/edit) Google doc.

Updated mockup.

![mockup-file-versions](https://cloud.githubusercontent.com/assets/687227/20192038/285d6d86-a756-11e6-961f-5a99b9e98a8f.jpg)

**Comment by mheppler** [comment] 2016-11-21 17:11
Notes from QA on #2465 to follow up on in development of this File Versions issue.

*Browsing*
- When viewing a draft or older version of a file, and you click the dataset name link in the breadcrumbs nav, should you go the dataset associated with that draft/version or should you go to the most recently published version?
- When browsing a dataverse, or searching, and you click the file name link on a result card, should you go to the file pg, or the dataset pg that the file belongs to (as it currently does in 4.5)?

**Comment by mheppler** [comment] 2016-11-29 18:34
Briefly discussed in today's status meeting past performance issues with displaying dataset version numbers and links (#2782) in the UI and it was determined that we can and should be able to add these back as part of this development on the file versions feature.

I have added this as part of the outline in my comment above, under the Browsing section. Both @raprasad and @scolapasta would be excellent resources on how best to approach this.

**Comment by sekmiller** [comment] 2016-12-21 18:55
The version numbers on the file page version tab refer to the dataset version. Or do we need two columns of version numbers one referring to the dataset version and the second referring to the file version.

I can envision a situation where version 1 of the file would correspond with version 2 of the dataset.

**Comment by mheppler** [comment] 2016-12-21 18:57
@sekmiller -- there is only one version number we track/display, and that is the dataset version. There is no "file version" number.

**Comment by mheppler** [comment] 2017-01-03 16:26
- Versions tab: 
    - Column names on versions table need to be clear - change “Version” to “Dataset Version”. “Description” to… TBD.
    - Automatically generated messages must be specific to the file, not dataset specific.
- File version differences - tune the current display of information format to work for files

Make sure to deliver items as [recommended by the UX Team](https://docs.google.com/document/d/1mNNRqRqIW92LXock332sIA-uXh-2agOpoyLLLKwXUA0/edit) based upon user feedback in usability testing of 4.6.

**Comment by djbrooke** [comment] 2017-01-04 22:41
We discussed this in the planning meeting on 1/4 and there are some questions. The team agreed that a good first step would be to have a design workshop to discuss the different views over some paper prototypes instead of just talking it out. 

I'll work with @TaniaSchlatter to schedule this.

**Comment by scolapasta** [comment] 2017-01-24 21:58
Closing; broken out into two smaller issues.

**Closed by scolapasta** 2017-01-24 21:58 UTC
Labels: ready
