### ISSUE TITLE
Harvesting geonode (pycsw) by OAI-PMH does not work

### ISSUE THREAD

**Issue by kamil386** [IQSS/dataverse#6242] opened 2019-10-02 00:15 UTC
Harvesting geonode (pycsw) by OAI-PMH does not work, the details:

XML response from geonode (pycsw):
http://master.demo.geonode.org/catalogue/csw?mode=oaipmh

`<!-- pycsw 2.4.0 --><oai:OAI-PMH xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd"><oai:responseDate>2019-10-01T18:51:35Z</oai:responseDate><oai:request>http://master.demo.geonode.org/catalogue/csw?mode=oaipmh</oai:request><oai:error code="badArgument">Missing 'verb' parameter</oai:error></oai:OAI-PMH>`

On the second hand, valid XML response from dataverse that works for harvesting without any problem:
https://demo.dataverse.org/oai

`<OAI-PMH xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd"><responseDate>2019-10-01T23:52:01Z</responseDate><request>https://demo.dataverse.org/oai</request><error code="badVerb">Illegal verb</error></OAI-PMH>`

Logs:
`[2019-10-02T01:58:18.164+0200] [glassfish 4.1] [INFO] [] [edu.harvard.iq.dataverse.HarvestingClientsPage] [tid: _ThreadID=51 _ThreadName=jk-connector(4)] [timeMillis: 1569974298164] [levelValue: 800] [[
  metadataformats: failed;received empty list from ListMetadataFormats]]`

Dataverse version: 4.16

The screenshot from the dashboard on create harvesting client window:
![image](https://user-images.githubusercontent.com/56053188/66009090-4b01c280-e4b9-11e9-894d-c06c8465da82.png)

Maybe it is related to the oai: in the tag (it is the only difference in both xml responses) and dataverse can't process that xml.

Providing full url of oai in geonode also does not work:
http://master.demo.geonode.org/catalogue/csw?mode=oaipmh&verb=ListRecords&set=citable&metadataPrefix=oai_dc

**Comment by djbrooke** [comment] 2019-10-02 17:47
Hi @kamil386, I'm not sure this is a Dataverse issue. When I click "Metadata search via OAI-PMH:" on the right side of the page here:

http://master.demo.geonode.org/developer/

It takes me to http://master.demo.geonode.org/catalogue/csw?mode=oaipmh&verb=Identify which shows what appears to be an error.

Can you reach out to the Geonode team to make sure this is working as expected before we start troubleshooting here? Thanks!

**Comment by kamil386** [comment] 2019-10-07 10:53
@djbrooke Geonode team has just fixed that bug, but still the same error appears.
All of the six OAIMH protocol requests are valid and works in geonode/pycsw. Valid url:
[http://master.demo.geonode.org/catalogue/csw?mode=oaipmh&verb=ListMetadataFormats](url)
gives an error in Dataverse logs:
`[2019-10-07T12:34:04.775+0200] [glassfish 4.1] [INFO] [] [edu.harvard.iq.dataverse.HarvestingClientsPage] [tid: _ThreadID=52 _ThreadName=jk-connector(5)] [timeMillis: 1570444444775] [levelValue: 800] [[
  metadataformats: failed;received empty list from ListMetadataFormats]]`
what is not true.

Maybe the problem is with bad interpreting the oai in the tag or additional necessary parameter "mode=oaipmh" in geonode/pycsw is not included in the Dataverse queries?

**Comment by pdurbin** [comment] 2019-10-07 12:29
@kamil386 is right, there are no more errors at http://master.demo.geonode.org/catalogue/csw?mode=oaipmh&verb=Identify (weird Django errors last week) so I'm re-opening this issue.

**Comment by JingMa87** [comment] 2020-06-19 02:05
**Error**
This is the error I'm getting when trying to harvest the GeoNode repository: `metadataformats: failed;Failed to execute listmetadataformats; No valid response received from the OAI server.` After hacking in the code, I found out that the code breaks at this part `sp.listMetadataFormats()` where sp stands for ServiceProvider. Deeper than that I can't dig since it's a 3rd party library called XOAI that handles the rest.

**XML response**
The XML response from the GeoNode repository seems the same as other responses, except every tag starts with `oai:` which might cause the issue. I ran the URL `https://master.demo.geonode.org/catalogue/csw?mode=oaipmh` through an online validator `http://oval.base-search.net/` and the harvesting check returned a lot of issues. I'm assuming the repository hasn't been implemented well.

**Harvard check**
![image](https://user-images.githubusercontent.com/16444164/85086544-31d1ab00-b1db-11ea-8f1e-df89ace1f13b.png)

**GeoNode check**
![image](https://user-images.githubusercontent.com/16444164/85086564-4150f400-b1db-11ea-84d6-af592dd1921f.png)

**Comment by pdurbin** [comment] 2020-06-22 17:53
@JingMa87 thanks for all the investigation. Do you think the bug is on the Dataverse side or the Geonode side (or both)?

**Comment by JingMa87** [comment] 2020-06-22 19:30
@pdurbin I did some more investigation and updated my last comment. The issue is definitely not with Dataverse.

**Comment by pdurbin** [comment] 2020-06-22 19:42
@JingMa87 thanks, from looking at our pom.xml we seem to be running a fork:

```
<!-- EXPERIMENTAL: -->
<!-- lyncode xoai OAI-PMH implementation: -->
<!-- unfortunately, their 4.10 version -->
<!-- is still buggy. As an experiment, I'm using -->
<!-- a patched version I built locally. -->
<!-- (pull requests pending - L.A. -->
<dependency>
    <groupId>com.lyncode</groupId>
    <artifactId>xoai-common</artifactId>
    <version>4.1.0-header-patch</version>
</dependency>
<dependency>
    <groupId>com.lyncode</groupId>
    <artifactId>xoai-data-provider</artifactId>
    <version>4.1.0-header-patch</version>
</dependency>
<dependency>
    <groupId>com.lyncode</groupId>
    <artifactId>xoai-service-provider</artifactId>
    <version>4.1.0-header-patch</version>
</dependency>
```

It looks like the code moved to https://github.com/DSpace/xoai and there's a version called 4.2.0.

**Comment by JingMa87** [comment] 2020-06-22 19:58
@pdurbin I can test the newest version of the library but I'm wondering what changes L.A. patched? It might be that the newest version of XOAI doesn't have to features that L.A. patched in so I would have to test for that.

**Comment by pdurbin** [comment] 2020-06-22 20:18
@JingMa87 I mean, you certainly could but is this issue a high priority for you? If so, I can ask L.A. about that patch. If not, are there other issues we could re-direct your energy into? We really appreciate all the pull requests!

**Comment by JingMa87** [comment] 2020-06-23 01:16
@pdurbin If any issues have more priority just let me know so I can discuss it with my coordinator. Do note that I'm a recently hired engineer for Data Archiving and Networked Services (DANS) in the Netherlands so I'm quite new to Dataverse. My current goal is to get to know the app more and in particular the harvesting client feature.

**Comment by pdurbin** [comment] 2020-06-23 17:09
@JingMa87 welcome to the Dataverse community! Here are a few harvesting-related issues you might want to read through:

- OAI PMH: Invalid Identify-Response #4597 
- OAI_dc compatibility #4537 
- Dataverse doesn't always produce valid DDI codebook 2.5 XML #3648 

@jggautier thinks a lot about harvesting and might have some other issues in mind. I'd also like to bring it to @landreev 's attention that we may have a future harvesting hacker in our midst. 😄 Thanks!

**Comment by jggautier** [comment] 2020-06-23 21:16
Thanks @pdurbin  and hi @JingMa87. The issue https://github.com/IQSS/dataverse.harvard.edu/issues/72 - about special characters in dataset metadata preventing other repositories from harvesting from Harvard Dataverse - is the harvested-related issue most pressing to me right now. It's in Harvard Dataverse's GitHub repo, but as far as I know it's possible that other repositories would be or are being affected by it. That is, other repositories have characters in their metadata exports that are preventing others from harvesting from them. I did as much digging as I could, but wouldn't know how to proceed.

**Comment by JingMa87** [comment] 2020-06-23 21:32
@jggautier Sounds like something I can look into! Also do you or @pdurbin think I can get permissions to add issues and PRs to a project? Otherwise I would have to ask a colleague to do it every time I do something.

**Comment by pdurbin** [comment] 2020-06-24 15:48
@JingMa87 I just invited you to join https://github.com/orgs/IQSS/teams/dataverse-readonly . I hope that helps.

**Comment by JingMa87** [comment] 2020-06-28 13:34
@pdurbin I validated GeoNode's repo URL on https://www.openarchives.org/Register/ValidateSite and they're giving me the same error caused by double question marks. I asked our functional manager to report this issue and a fix to GeoNode. Since the original poster of this issue is not commenting, I'd like to close it. Agreed?

**Comment by pdurbin** [comment] 2020-06-29 16:12
@JingMa87 thanks for the leg work. @kamil386 presented at our Dataverse Community Meeting just a couple weeks ago so he should be around. I'm getting the sense that the feeling is that there isn't a bug in Dataverse after all so yes, I'll close it, at least for now. Thanks.

**Closed by pdurbin** 2020-06-29 16:12 UTC
Labels: Feature: Harvesting
