### ISSUE TITLE
Dataset - Save invalid data in additional metadata block, error message displays, but block closes

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#531] opened 2014-07-09 15:39 UTC
---

Author Name: **Elda Sotiri** (@esotiri)
Original Redmine Issue: 3946, https://redmine.hmdc.harvard.edu/issues/3946
Original Date: 2014-05-07
Original Assignee: Gustavo Durand

---

should the block stay open to easy locate where the invalid value was entered?

**Comment by scolapasta** [comment] 2015-02-11 18:13
Let's see what, if anything can be done during beta 14, and otherwise defer.

**Comment by eaquigley** [comment] 2015-12-03 21:37
This is only happening on the Edit Metadata page after a dataset is created. I tried this on the Create Dataset page but on that page, the extra block with a required field was open by default so it didn't close. I'm wondering what the difference in the code is between the Create Dataset page (where extra metadata block is open by default) and Edit Dataset Metadata page (where extra metadata block is closed by default). @mheppler or @sekmiller would one of you know why the code is different? or if its something else.

**Comment by scolapasta** [comment] 2015-12-03 21:57
I believe this was a design decision. On create there are required fields
(that are initially blank) so they are open. On Edit, they are already
filled in, and it was decided to start them as closed to keep form more
manageable.

If we were to have them open to start, then I think this issue would go
away.

**Comment by pdurbin** [comment] 2015-12-11 18:55
> On Edit, they are already filled in, and it was decided to start them as closed to keep form more manageable.

Apparently the same logic holds when **viewing** a dataset. Everything but the "Citation" metadata block is hidden (collapsed). You have to click "Geospatial Metadata" for example, to see the fields that have been filled in. I suspect that new users may not realize they can click to see more metadata:

![ethiopia_social_accounting_matrix_ sam _2005-06_-_international_food_policy_research_institute_ ifpri _dataverse_-_2015-12-11_13 54 36](https://cloud.githubusercontent.com/assets/21006/11752648/c3b9584e-a00e-11e5-8360-b88dab151988.png)


I'd suggest simply having all metadata blocks open (expanded) when viewing a dataset.

**Comment by mheppler** [comment] 2015-12-15 18:15
It looks like the render logic is there, but it isn't applied consistently to the various moving parts of the collapsible panel components of the additional metadata blocks.

For example, here is what Citation Metadata block looks like in the dataset pg "Edit" view, with the text blue, and the chevron icon pointed up, and the panel open.

![screen shot 2015-12-15 at 1 09 58 pm](https://cloud.githubusercontent.com/assets/687227/11819396/928d5406-a32d-11e5-8323-6c9e3d38850f.png)

Now, in comparison, here is an additional metadata block in the dataset pg "Create" view, with the text ~~black~~, and the chevron icon pointed ~~down~~, and the panel ~~open~~.

![screen shot 2015-12-15 at 1 13 44 pm](https://cloud.githubusercontent.com/assets/687227/11819437/cc301cd4-a32d-11e5-8c16-2505baf096f2.png)

**Comment by mheppler** [comment] 2015-12-15 20:27
Fixed render logic for the collapsible panel and styles missing from panel-heading of dataset metadata blocks in the "create" view.

The other reported issues regarding the additional metadata blocks being collapsed in the "edit" and "info" views was as designed, as was pointed out in previous comments. This is something that can be further looked into with usability testing, and shouldn't keep this ticket from getting resolved.

**Comment by kcondon** [comment] 2016-01-06 00:28
@mheppler @eaquigley 
I can test Mike's latest changes but this ticket is not about that so think it should stay open:
Elda:
should the block stay open to easy locate where the invalid value was entered?
Liz:
yes, the block should stay open and this relates to #661
Thoughts?

**Comment by kcondon** [comment] 2016-01-06 16:35
@mheppler 
OK, tested chevrons and label colors and are consistent between create and edit modes.
However, viewing metadata blocks from the tab does not work consistent with the other modes:
chevrons never change direction opened or closed and for citation is always pointing up, for others, always pointing down.

**Comment by mheppler** [comment] 2016-01-07 16:47
Added oncomplete attribute to the p:ajax component associated with the p:tabView component to rebind jQuery that toggles the chevron icons on the metadata panels of the dataset pg.

**Comment by kcondon** [comment] 2016-01-07 20:12
Chevrons working now, Mike's changes have been verified. Passing back to Liz for consideration of original issue.

**Comment by djbrooke** [comment] 2016-07-29 19:02
(just assigning this to Liz so that we can discuss on Monday)

**Comment by eaquigley** [comment] 2016-08-01 19:58
Yes, I still do believe that the metadata block with the error in it should stay open.

**Closed** 2023-11-11 15:47 UTC
Labels: Feature: Metadata, Type: Bug, User Role: Depositor, Component: JSF, UX & UI: New React UI
