### ISSUE TITLE
Change the production date

### ISSUE THREAD

**Issue by MohanaPriyaNarapareddy** [IQSS/dataverse#5911] opened 2019-06-04 14:47 UTC
I imported my dataset from datacite to dataverse. Is there anyway that i could change the Publication  data from today's date to the production date?

**Comment by jggautier** [comment] 2019-06-04 15:30
Hi @MohanaPriyaNarapareddy. This seems related to your discussion at https://github.com/IQSS/dataverse/issues/5729. So is this issue about being able to edit or hide Dataverse's publication date timestamp?

**Comment by djbrooke** [comment] 2019-06-12 21:07
@MohanaPriyaNarapareddy and @jggautier - I'm going to close this as a duplicate of #5729.

**Closed by djbrooke** 2019-06-12 21:07 UTC
