### ISSUE TITLE
Versions Tab: Adding/removing a guestbook does not appear in version differences

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#4905] opened 2018-07-27 14:10 UTC
When you add a guestbook to a published dataset, or remove one, and publish a new dataset version, the change isn't in the table in the versions tab or in the pop up. And if guestbook changes are the only changes you've made, the table and pop up show no changes:

<kbd>![screen shot 2018-07-27 at 10 04 16 am](https://user-images.githubusercontent.com/18374574/43325381-846e3604-9184-11e8-8116-17716a73250f.png)</kbd>

<kbd>![screen shot 2018-07-27 at 10 04 37 am](https://user-images.githubusercontent.com/18374574/43325417-97cf90f8-9184-11e8-87ba-498821170b77.png)</kbd>

I haven't heard about a user need to track this kind of change across versions, but making a change and seeing an empty versions table has been a little confusing.

This is similar to _Versions Tab: Enable request access value does not appear in version differences_. (https://github.com/IQSS/dataverse/issues/2432)

**Comment by pdurbin** [comment] 2018-07-27 15:41
@jggautier as far as I know this is by design. Have any users of Dataverse asked for this?

**Comment by jggautier** [comment] 2018-08-21 20:35
Thanks @scolapasta. That makes sense. The issue in the case the prompted this ticket is that it looked like no change had occurred, which has been a little confusing. Maybe, in cases where changes occur that we don't track, we could display a message saying that changes to guestbooks and file restrictions are not tracked (and whatever other category of actions Dataverse doesn't track in the version table)

To help clarify the issue, I haven't heard about a user need to track these kinds of changes across versions, but making a change and seeing an empty versions table has been a little confusing. I'm added this to the issue description.

**Comment by mheppler** [comment] 2018-08-21 20:51
A while back there was a discussion about Dataverse tracking changes like these. I think it was referred to as an "audit" or "change log". Who did what, when and why kinda details. This issue #1002 is similar, referencing pre-publish changes, but I'm not sure it is an exact match.

**Comment by pdurbin** [comment] 2018-08-21 22:03
Yeah. Maybe the User Guide should clarify what aspects of a dataset are versioned. Thumbnails are not versioned, for example.

**Comment by shlake** [comment] 2019-07-15 15:35
Wanted to add another observation to this ticket - adding/removing Guestbooks.

If one removes or adds a Guestbook and does not "Publish" that draft version, the update happens anyway. Example:   If I do not have a guestbook on V1 (published) and then later add a guestbook (my dataset page shows this change is now a Draft version w/ a Publish button), I see the added guestbook on my original V1 (and I have not published the "draft").

Maybe there are two possible solutions:

- When changing something that is not versioned, make a note of it like other changes once published.

OR

- When changing something that is not versioned, don't note it (as it is done now) AND do not activate re-publish (i.e., do not make a draft that needs to be published).

**Comment by shlake** [comment] 2019-07-26 15:03
My comment above seems to relate to ISSUE #2807

**Comment by cmbz** [comment] 2024-08-20 15:24
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Closed by cmbz** 2024-08-20 15:24 UTC
Labels: Type: Bug, Feature: Publishing & Versions, Feature: Guestbook
