### ISSUE TITLE
Error when trying to download a non ingested file on a dataset with another ingested file 

### ISSUE THREAD

**Issue by LauraPremSmile** [IQSS/dataverse#7505] opened 2021-01-12 14:37 UTC
Hello,
We encountered an issue when downloading files.
When there is a ingested file in the dataset, there are two options on the download: either "original format" or "archival format (.tab)"
On a dataset with an ingested file, when trying to download a non ingested file and picking "orignal", there is the following error:
{"status":"ERROR","code":404,"message":"datafile access error: requested optional service (image scaling, format conversion, etc.) is not supported on this datafile."}
This error can be reproduced on the following dataset from the demo site when trying to download test.pdf in original format:
https://demo.dataverse.org/dataset.xhtml?persistentId=doi%3A10.70122%2FFK2%2FWAPYVE&version=DRAFT

**Comment by djbrooke** [comment] 2021-01-12 15:04
Hi @LauraPremSmile - I think this a duplicate of #6972. I'll close this and add a reference there. I'll increase the priority of this.

**Closed by djbrooke** 2021-01-12 15:04 UTC
