### ISSUE TITLE
Users/Groups section of permissions page:  the "users/groups" section of permission should expand on access

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2627] opened 2015-10-07 16:46 UTC
The user/groups section doesn't expand on access to permission page and is causes confusion when users access the page and try to figure out where to add users.

**Comment by bencomp** [comment] 2015-10-15 08:08
This could be a duplicate of #2255 (in which I agree with @sbarbosadataverse) and is very likely a duplicate of #2354 (in which I mentioned the relation with #2255 to @pdurbin).

**Comment by eaquigley** [comment] 2016-01-05 16:27
Duplicate of #2354. Passing to @kcondon to close.

**Comment by kcondon** [comment] 2016-01-05 17:40
Duplicate, closing.

**Closed by kcondon** 2016-01-05 17:40 UTC
Labels: Status: QA
