### ISSUE TITLE
Notification Email send failure: email Address shouldn't be quoted in sendSystemMail()

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#4490] opened 2018-03-08 13:24 UTC
https://github.com/IQSS/dataverse/blob/83463618574c7a94ad36babf35c5ee6781d4c4cb/src/main/java/edu/harvard/iq/dataverse/MailServiceBean.java#L129
It looks like quotes were added here in a commit last July. They break our (QDR) setup using Amazon SES for mail, causing a  501 Invalid RCPT TO address provided . (The Harvard Dataverse delivers the mail, but I do see quotes around my email address in my mail client, unlike mail from other sources). Having quotes is different than the similar code in sendMail in line 94, so I think it is just a typo. We've replaced line 129 with line 94 locally and verified that this fixes the problem with our SES setup.

**Comment by pdurbin** [comment] 2018-03-08 13:34
@qqmyers hi! This sounds like a possible fix for #4240

If you think so (or even if you don't!) can you please make a pull request? Thanks!!

**Comment by qqmyers** [comment] 2018-03-08 13:46
Yep - same thing. I'll make the request.

**Comment by pdurbin** [comment] 2018-03-08 14:13
@qqmyers thanks for making pull request #4491 !

I just dragged this issue to Code Review at https://waffle.io/IQSS/dataverse

**Comment by pdurbin** [comment] 2018-03-08 14:14
I'm closing this as a duplicate of #4240.

**Closed by pdurbin** 2018-03-08 14:14 UTC
Labels: Status: Code Review
