### ISSUE TITLE
Advanced search for a specific dataverse - show metadatablocks for children dvs

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1302] opened 2015-01-07 18:56 UTC
Right now we only show the enabled metadatablocks in the advanced search, but we really should check child and linked dvs and show those blocks.

**Comment by pdurbin** [comment] 2017-06-29 09:51
I'm closing this issue as a duplicate of #2353 which also has screenshots.

**Closed by pdurbin** 2017-06-29 09:51 UTC
Labels: Component: Search/Browse, zTriaged
