### ISSUE TITLE
Metadata Validation: Allow Users to Save Edits to Files + Terms when required metadata is not filled out

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2450] opened 2015-08-12 21:07 UTC
Long term solution for datasets that existed prior to 4.0 and do not have subject and/or contact email filled out when they go to save edits to files or terms for a new draft of the dataset.

This will also allow users to save edits to files or terms for a new draft of a dataset if any required metadata fields have been added to the dataverse since the creation of the dataset.

Currently, validation is checking the entire dataset (metadata, files, terms) to see if there is any missing value and not allowing a user to save if there is. This solution would change the logic so only the files or terms validation is being checked when a user is trying to save edits, not the entire dataset. 

However, for publishing, a pop up needs to appear to let the dataset author know these required metadata fields must be filled out before publishing is allowed.

**Comment by mheppler** [comment] 2018-04-02 17:12
This issue is a duplicate of #2451. Closing this and copying over the comment above.

**Closed by mheppler** 2018-04-02 17:12 UTC
Labels: Feature: File Upload & Handling, Feature: Metadata, Feature: Migration, Feature: Terms & Licensing, Status: UX & UI, Type: Suggestion, User Role: Depositor
