### ISSUE TITLE
Enable Saved Search Feature For End Users

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2053] opened 2015-04-20 17:39 UTC
In 4.0 only Super Users have the ability to Link Dataverses and Datasets and Save Searches, however we have had several users (during trainings and RT https://help.hmdc.harvard.edu/Ticket/Display.html?id=196686) ask for this functionality to be available to them so that they can do this and manage these themselves (like they did in 3.6).

**Comment by sbarbosadataverse** [comment] 2015-04-29 18:42
just received a request to link 15 studies. when will this feature be available for dataverse admins?

**Comment by mcrosas** [comment] 2015-04-29 21:52
4.0.2 release: https://github.com/IQSS/dataverse/milestones

**Comment by dlmurphy** [comment] 2018-01-11 17:42
Edited this issue to focus on the saved search feature, created a new separate issue to focus on the dataverse/dataset linking: #4410

**Comment by mheppler** [comment] 2018-01-11 17:51
@dlmurphy if @djbrooke approves, I think you can close this issue as a duplicate of #1840. There seems to be more information in that original issue.

**Comment by djbrooke** [comment] 2018-01-11 17:52
@dlmurphy @mheppler I don't need to approve the closure of an issue. Feel free!

**Comment by dlmurphy** [comment] 2018-01-11 18:12
Sounds good. I'll transplant Eleni's original post from this issue into that issue, since that one has no original message.

**Closed** 2018-01-11 18:13 UTC
Labels: Feature: Search/Browse, Status: UX & UI, Type: Suggestion, User Role: Curator
