### ISSUE TITLE
Publishing: Success not displaying properly, gives error when refresh a draft

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#4129] opened 2017-09-08 22:09 UTC
Thought this was a "handle" publishing bug, but got the error below once I refreshed the page

steps:
1. edit a dataset with a handle and save
2. select publish but it appears to fail
3. refresh draft and get the error below,  because publish apparently did work. New version does show up under versions tab successfully at this point.

![pastedimage 1](https://user-images.githubusercontent.com/8322346/30232946-97113a70-94c0-11e7-85dd-f3b6b0d6c468.png)

**Comment by djbrooke** [comment] 2019-02-14 16:31
@sbarbosadataverse - can you try to reproduce this?

**Comment by mryder2** [comment] 2019-07-18 21:36
I could only find one dataset in the MRA with this issue, and was unable to reproduce.
However, if you could do a search for datasets that still have the hdl identifier, I can do some more testing.  I could only find one in the MRA.

**Comment by djbrooke** [comment] 2019-07-18 21:38
Hi @mryder2 - thanks for the testing here. I'll close this, as it's low impact and it's a bit of a older issue.

**Closed by djbrooke** 2019-07-18 21:38 UTC
Labels: Feature: Publishing & Versions, Medium, Type: Bug, User Role: Curator
