### ISSUE TITLE
Dataset/Dataverse Desciption - Allow HTML for description fields

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#610] opened 2014-07-09 15:39 UTC
---

Author Name: **Elizabeth Quigley** (@eaquigley)
Original Redmine Issue: 4046, https://redmine.hmdc.harvard.edu/issues/4046
Original Date: 2014-05-28
Original Assignee: Elizabeth Quigley

---

How will we be handling this in 4.0? A user asked me if we would support it in a way similar to the way you can edit a wiki. Currently in Beta, a user can't input any HTML and have it work.

Things to consider:
*if we allow links in metadata fields, we should have a link checker that could provide notifications when links break
*Potential PrimeFaces widget to use for fields that can use HTML (i.e.-description): http://www.primefaces.org/showcase/ui/input/editor.xhtml

(Overview of email discussion from 5/28-5/29)

---

Related issue(s): #239
Redmine related issue(s): [3653](https://redmine.hmdc.harvard.edu/issues/3653)

---

**Comment by scolapasta** [comment] 2015-01-23 22:34
Sending to QA as dupe of #1320

**Comment by kcondon** [comment] 2015-01-29 18:14
Closing as duplicate.

**Closed by kcondon** 2015-01-29 18:14 UTC
Labels: Priority: High, Status: QA, Type: Feature
