### ISSUE TITLE
Include tabular ingest failure reason in tooltip on dataset page file table

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#9427] opened 2023-03-07 15:38 UTC
**What steps does it take to reproduce the issue?**

* **When does this issue occur?**

  When reviewing the tabular ingest failure messages in the tooltips on a dataset's file table and in the tooltips on the file's pages.

* **Which page(s) does it occurs on?**

  The dataset page and the file page

* **What happens?**

  On the dataset page's file table, there's a tooltip with more information about tabular files that could not be ingested:
  <img width="760" alt="Screen Shot 2023-03-07 at 10 24 35 AM" src="https://user-images.githubusercontent.com/18374574/223467777-ca716aea-a4fe-4091-be13-f479ab7d1a08.png">

  As far as I can tell, that message always reads that "No further information is available," regardless of the dataset or file.

  But on the file's page, the tooltip might have more information:

  <img width="765" alt="Screen Shot 2023-03-07 at 10 28 19 AM" src="https://user-images.githubusercontent.com/18374574/223471216-0c69b0ae-c36c-4f0a-89b4-b7fba5797319.png">

  I was able to reproduce this on Demo Dataverse, and here are more datasets in Harvard's repository where you can see this:

  - https://doi.org/10.7910/DVN/SEGOVA
  - https://doi.org/10.7910/DVN/XT15Y0
  - https://doi.org/10.7910/DVN/QBRISH
  - https://doi.org/10.7910/DVN/LQW3CT

* **To whom does it occur (all users, curators, superusers)?**
Curators, superusers, depositors (anyone who can edit a dataset with one or more tabular files that could not be ingested)

* **What did you expect to happen?**
The details about why the ingest failed are also in the tooltips in the dataset file table. Otherwise, users who see the tooltip on the file table might think that the repository has no more information about why the ingest failed.

**Which version of Dataverse are you using?**
v5.13

**Comment by luddaniel** [comment] 2024-04-17 13:58
Although I couldn't find the explanation via a commit in versions higher than `v5.13`; I was not able to reproduce on `v5.14` and `v6.2`. Both tooltip are displaying the same message containing the ingest report error message.
This file was used for tests : https://dataverse.harvard.edu/file.xhtml?fileId=6525049&version=2.0
![Screenshot from 2024-04-17 15-52-30](https://github.com/IQSS/dataverse/assets/83018819/feb312e6-32fb-45a8-ac08-db8af84c43e4)
![Screenshot from 2024-04-17 15-52-03](https://github.com/IQSS/dataverse/assets/83018819/4c2d1b11-575b-457d-993d-18d120c40247)
@jggautier Can you test and close the issue ?

**Comment by jggautier** [comment] 2024-04-17 14:28
Hmm yeah I can't reproduce it either for any of the files I mentioned in [this issue's original post](https://github.com/IQSS/dataverse/issues/9427#issue-1613707896).

Do you think the PR for the issue at https://github.com/IQSS/dataverse/issues/9570 fixed this? Or did you rule that out too when you looked through commits in versions higher than v5.13?

@stevenferey, you wrote that this GitHub issue was related to the one you opened at https://github.com/IQSS/dataverse/issues/9570? Did your PR resolve this issue with the tooltips?

**Comment by luddaniel** [comment] 2024-04-17 14:53
@jggautier I mean : I checked the code, git blamed, checked [5.14 milestone ](https://github.com/IQSS/dataverse/milestone/108?closed=1) I didn't find the bug fix. But it works so no need to overthink ^^

**Comment by jggautier** [comment] 2024-04-17 15:06
Thanks yeah. I don't mean to overthink it. I guess generally I'm worried when things change and no one knows why.

Do you think it's not worth waiting to hear from @stevenferey?

Maybe that's the nature of software development or specifically development in open source software?

**Comment by luddaniel** [comment] 2024-04-17 15:24
@stevenferey is in my team, his code didn't change anything related to this issue.
If you didn't had fork of `v5.13` my best guess is this : there is a lot of JSF tag that can update `datasetForm:filesTable`; maybe the dynamic reloading was done somehow before ingest error was registered in database resulting in the display of default Bundle key `file.ingestFailed=Ingest failed. No further information is available.` instead of [the actual real error](https://github.com/IQSS/dataverse/blob/v5.13/src/main/java/edu/harvard/iq/dataverse/DataFile.java#L419). In this case, reloading the page would fix it...

> Maybe that's the nature of software development or specifically development in open source software?

Most of my developper carrear I was able to find a code explanation really fast. But some times you need 3 days because it's a really complicated context. For this issue, as it seems fixed, I'll suggest to just move on :)

**Closed** 2024-04-17 15:29 UTC
Labels: Type: Bug
