### ISSUE TITLE
Provide File-Level Data Citation for All Files

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1400] opened 2015-01-30 17:58 UTC
As shown in #1066 only tabular data files are currently able to export a citation at the file-level. However, there have been discussions with external (Data Citation Index) and internal stakeholders that we should support exporting citations for ALL files.

@eaquigley @scolapasta can you see if this is trivial for us to do for 4.0 or if we should postpone this for later?

**Comment by eaquigley** [comment] 2015-01-30 20:00
@landreev Can you answer @posixeleni 's question above on if this will be trivial or not. Thanks!

**Comment by landreev** [comment] 2015-02-13 23:01
@eaquigley 
@posixeleni 
I honestly don't feel like it would be super useful...

For tabular data files, having a file-level citation is somewhat justified - because we generate UNFs for them; and the UNF is a fairly important thing, being the unique signature of the data, etc. 
For a non-tabular file, the citation will just be the citation of the dataset with the file name added... which is kind of silly. I feel that anyone who wants to cite a file should just use the dataset-level citation. 

If you do decide that this is something we need, generating the citation will be trivial. (again, it will just be the dataset citation + the name of the file). 
But the dataset page ui will need to be changed - an additional button/link for this citation will need to be added... So, if you end up making such an unfortunate choice (that, I believe, would be a mistake), please give this issue to Mike for making the UI change; and then I'll wire the actual citation to it.

**Comment by mcrosas** [comment] 2015-02-13 23:06
Let's not do this for 4.0. We would want to review it with Gary and Micah to see if it should follow something similar to their proposed format for tabular datasets. As long as we are have citation for tabular files for 4.0, we are set.

**Comment by mheppler** [comment] 2016-12-21 21:18
@mcrosas -- did we deliver this feature in 4.6 with the file pg? Or is this issue more about persistent identifiers? In which case, we can close this as a duplicate of **Files: Need Persistent Identifiers/URL's for Data Files #2700**.

**Comment by mcrosas** [comment] 2016-12-22 17:08
Yes, looks all good, with the citation of a file in the file page. This
issue can be closed.

**Comment by pdurbin** [comment] 2016-12-22 17:47
Great! I added the 4.6 milestone and will move it to a column in Waffle that we touch on during standup.

**Closed** 2017-01-03 22:19 UTC
Labels: Component: File Upload & Handling, Priority: Medium, Status: Triaged, Type: Feature
