### ISSUE TITLE
uploading datafile: uploading getting stuck between upload and draft creation, no progress no error display

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2429] opened 2015-08-03 16:51 UTC
This file has been processing for over 4 minutes. It's a small list file that when uploaded originally took a few a seconds to complete. I uploaded this at the same time with a stata data file that already successfully uploaded.
I decided to just refresh the page, which refreshed to the published version and not the draft, and when I check draft, the file did  not successfully upload.

3 complaints about this today and I was able to replicate all three

![screen shot 2015-08-03 at 12 58 19 pm](https://cloud.githubusercontent.com/assets/8322346/9042676/4e92f0f2-39de-11e5-9467-a3b98430e855.png)

![screen shot 2015-08-03 at 4 20 30 pm](https://cloud.githubusercontent.com/assets/8322346/9047342/47721ac0-39ff-11e5-92fc-2d802b166ad8.png)

**Comment by landreev** [comment] 2015-08-06 16:35
This was caused by a problem with Jhove configuration. 
The issue was actually resolved back in January (see #951). But it was solved by a change in the config file. Which is shipped with the installer, that puts it in the domain config directory. But we never updated the copy installed in production; so this became a problem on Monday, when the schema url from the old config file stopped working. 
I updated the config files on prod servers; sent out a reminder for the developers to update theirs. 
There shouldn't be anyone else around who may have pre-January installations. 
Closing.

**Closed** 2015-08-06 16:36 UTC
Labels: Component: File Upload & Handling, Component: UX & Upgrade, Priority: Critical
