### ISSUE TITLE
Password Reset Emails Blocked by Gmail

### ISSUE THREAD

**Issue by jyuenger** [IQSS/dataverse#9965] opened 2023-09-28 12:28 UTC
Gmail users are increasingly unable to receive our password reset emails. The messages seem to be blocked before even reaching that point, so advising them to check their spam folder doesn't help - they just never show up.

I can start keeping track of these, but I feel like we get a few each week. They wind up needing to create new accounts, so we can then merge the ones they're locked out of into them, and regain access. This is specific to Gmail, I'm not seeing any other cases of users unable to receive reset emails at other domains.

**Comment by pdurbin** [comment] 2023-09-28 12:49
@jyuenger thanks for the bug report. Can you reproduce this on https://demo.dataverse.org ?

**Comment by jyuenger** [comment] 2023-09-28 12:59
@pdurbin Yes, my demo account uses Gmail, and if I log out and try to do a password reset request, I don't receive the email, even in spam.

**Comment by jyuenger** [comment] 2023-10-31 13:29
This seems to be becoming more widespread among Gmail users, with multiple tickets daily from folks who can no longer receive reset emails.

**Comment by cmbz** [comment] 2023-10-31 13:55
@jyuenger Do you know if HUIT reported similar problems with password resets sent to non-Harvard GMail accounts?

**Comment by jyuenger** [comment] 2023-10-31 13:57
I haven't had any contact with HUIT, but no non-Gmail users have complained. I can reproduce the issue on the demo site using a Gmail account, while I do receive reset emails if I use another provider. They don't appear to even go to spam, they seem to be blocked before reaching that point.

**Comment by cmbz** [comment] 2023-10-31 19:41
2023/10/31: I've opened a ticket with HUIT and have cc'd @jyuenger and @landreev. Hopefully we'll be able to address the problem with this additional bit of help.

**Comment by landreev** [comment] 2023-10-31 23:11
@cmbz I am replying to Christine via the HUIT ticket with some details about the outgoing email configuration of our servers. 
@jyuenger Could you please provide Christine with a couple of recent gmail addresses/approximate dates when the messages to them were lost from RT? 

The fact that messages to gmail from demo.dataverse.org are not getting delivered either may or may not be relevant. It uses a completely different way to relay mail (running its own local postfix, which in turn talks to some Amazon mail relay); it uses the same unsecured, un-authed smtp to talk to postfix - so that may be a problem there as well. But then I just tried to reset my password there on the account with my hmdc.harvard.edu address... and didn't receive anything either. So, let's focus on figuring out how to get it to work in prod. But we may learn something in the process that will apply to how we configure, or recommend to configure mail on other Dataverse instances.

**Comment by jyuenger** [comment] 2023-11-01 11:57
Sure, I know we had at least two yesterday. I'll go back through RT and see if I can dig some up from the past couple weeks.

**Comment by landreev** [comment] 2023-11-01 14:54
Perfect, thank you!

**Comment by landreev** [comment] 2023-11-01 19:58
I just saw an update from Christine on https://harvard.service-now.com/ithelp?id=requests. 
I doesn't look like I can add to/comment there - is there a way to add myself to the ticket?

**Comment by cmbz** [comment] 2023-11-01 20:05
@landreev I just asked them to add you and @jyuenger to the ticket. There didn't seem to be a way to add you directly in Service Now.

**Comment by landreev** [comment] 2023-11-01 20:07
Jeremy appears to be able to add to the ticket already.  
My email from last night is showing there (as sent from Guest), but I can't tell from Christine's message if she actually saw it.

**Comment by landreev** [comment] 2023-11-01 21:03
It really looks like service-now only thought I was a "guest" because that message came from my g.harvard.edu address. As long as I use my hmdc email, it treats me as a legitimate user. I don't think I need any extra permissions on that ticket really.

**Comment by jyuenger** [comment] 2024-01-31 13:26
Christine at HUIT helped us modify the SPF record on our outgoing mail, so it's now signed and encrypted. Specifically, we're including the network the mailhub servers are on in the record now. My own testing shows this seems to be working; using dummy Gmail accounts, I can now request and receive reset emails and other correspondence that weren't coming through previously.

**Comment by landreev** [comment] 2024-01-31 22:55
My experience has been similarly positive so far, when testing with my personal Gmail account.

**Comment by pdurbin** [comment] 2024-07-08 20:21
@philippconzett kicked off a related thread at https://groups.google.com/g/dataverse-community/c/WjEgjrKzaxs/m/LiH-8P-vEAAJ

[In Slack](https://iqss.slack.com/archives/CVB2SMDFX/p1706734605069869), on Jan 31, @landreev wrote: "According to [Harvard IT], the problem with delivery to gmail addresses should be resolved now. Let’s keep an eye on it."

So maybe the problem has been resolved and we should just add some documentation to close this issue?

**Comment by jyuenger** [comment] 2024-07-09 12:10
It is resolved so far as I can tell, now that we're signing out outbound email. I haven't run into anyone with this issue since the change was implemented in January.

**Comment by pdurbin** [comment] 2024-07-09 13:37
Wonderful, I'll go ahead and close it then. Thanks for the update, @jyuenger!

**Closed by pdurbin** 2024-07-09 13:37 UTC
Labels: Type: Bug, Feature: Notifications, User Role: Depositor
