### ISSUE TITLE
Templates: Unable to inherit/ see parent templates.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1947] opened 2015-04-09 19:15 UTC
Unable to inherit/ see parent templates. When I create a sub dv from a parent that has templates, I see the Create Template helpful how to page rather than the parent template list.

**Comment by sekmiller** [comment] 2015-04-09 19:31
By design, you cannot inherit if your metadata blocks differ from your parent.

May want to add a message to the user in the manage page.

Assigning to Gustavo for prioritizing...

**Comment by kcondon** [comment] 2016-01-05 23:58
@eaquigley 
Works as described for sub dv's but not for sub dv's from root.

**Comment by kcondon** [comment] 2016-01-06 00:19
@eaquigley 
It is true if the metadata blocks are different from parent dv blocks, you cannot inherit templates. However, it also doesn't work if parent has any additional blocks selected other than citation (default) and the child is using the same blocks. That seems like a bug.

**Closed** 2023-11-10 23:42 UTC
Labels: UX & UI: Design, Feature: Metadata, Type: Bug, User Role: Curator
