### ISSUE TITLE
Linked/Saved Search: Review Functionality + Usability Test

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1840] opened 2015-04-02 14:10 UTC
Original post from Eleni in #2053:

In 4.0 only Super Users have the ability to Link Dataverses and Datasets and Save Searches, however we have had several users (during trainings and RT https://help.hmdc.harvard.edu/Ticket/Display.html?id=196686) ask for this functionality to be available to them so that they can do this and manage these themselves (like they did in 3.6).

**Comment by scolapasta** [comment] 2015-04-18 19:55
Among things to decide:
- a manage page #1760
- do we have a facet #1335

**Comment by scolapasta** [comment] 2015-04-18 19:58
Re: facets, I know we'll have the manage page, but I would still like us to consider a facet (or at least index of this so we can filter by it if we want in search)

**Comment by eaquigley** [comment] 2015-04-21 19:08
Would there be a way to have the publication status facet change to be "Status" and have Unpublished, Published, Draft, Linked, and Harvested appear there? @scolapasta @mcrosas @pdurbin

**Comment by mcrosas** [comment] 2015-04-22 03:24
nice idea. But perhaps "status" is not the best term - how about "mode"? (but I don't feel too strong eitehr way - whatever term you prefer)

**Comment by eaquigley** [comment] 2015-05-06 16:54
Related to #1813 #2053 #1884 #1898 #1890

**Comment by mheppler** [comment] 2015-05-06 17:00
To continue this discussion, and to help move it along for 4.0.1 development, I have reviewed all the linked workflows currently in 4.0, and where the mockups for managing are at. Here are some thoughts.

- There is a 4.0.1 ticket for manage functionality, #1364. If we use this ticket as the high-level discussion, we could use that ticket as the specific feature development issue, and then create other feature development issues as needed. (Also, the two tickets Gustavo linked to, one #1335 seems to be the wrong issue, #1365 maybe? And #1760, he said was to be closed but is still in QA.)
- In regards to a facet, I have mocked up a suggestion that doesn't include it with "Publication Status" because I felt this dealt with something different, and warranted it's own category title. I couldn't decide on a title, so I included both "Domain" and "Province" in the mockup, and the options are "Local" and "Linked", because I don't think you can have one facet without the other.
![screen shot 2015-05-06 at 12 22 59 pm](https://cloud.githubusercontent.com/assets/687227/7498140/a7509aa6-f3ec-11e4-8e51-587112c41afd.png)
- We need to review all the success and errors messages, because it looks like those haven't been fully reviewed ("...Please wait for your content to appear." What does that mean? How long do I have to wait? Do I have time to reheat this cold pizza in my fridge?).
- We need to review Link Search workflow, and tie it into this manage workflow (Liz just commented with those related issues), so that we can manage all linked dataverses, datasets and searches in one easy to find place, that we can call "Linked Data" (just like we have "Add Data"), which you would find under "Edit Dataverse", as has been previously mocked up.
- This one manage workflow can be laid out in a few different ways -- one big table for all linked data, separate the different types into different tables, which might be in tabs, or in collapsible panels -- so we should discuss those and decide which direction we think works best. One big table might be the easiest to develop, but could get a little messy and difficult to manage for the admin.
- The Link Search workflow still needs some more thought too. It contains some "developie" looking options (looking at YOU "Facets") that might not make a whole lot of sense to anyone other than the developers, so might not be needed, or just need a little friendlier wording and formatting, to be useful information to the admin.
- And, I think I found a bug, or not fully developed unexpected result of the Link Search success message. After I have linked my search for "pizza" to my dataverse in the popup, I am brought back to the dataverse landing page, with a success message, all is good there, expect that my search is no longer retained. Not sure if that was intended, but I think, since we opened the Link Search workflow in a popup, that the content/search results under the popup shouldn't be lost.

**Comment by eaquigley** [comment] 2015-05-12 21:35
Functional Requirements Document for Linked Search: https://docs.google.com/document/d/1dmxs4XIQkrn9QfP4Ih4wIbyARUyWFJflJk3y4W3nzXk/edit?usp=sharing

**Comment by pdurbin** [comment] 2015-11-07 12:03
> We need to review all the success and errors messages

Yes. In some cases the bundle keys aren't even present. In #2718 we learned that when Link Search fails the logs show 'Could not find key "dataverse.saved.search.failure" in bundle file' and after I fixed that regression we continue to see 'Could not find key "dataverse.saved.search.success" in bundle file' in the logs (and no success message). @eaquigley and I agreed to defer the cleanup of these bundle keys and messages until the functionality has been reviewed in this issue. I'm just leaving a note here so we don't forget.

**Comment by pdurbin** [comment] 2017-06-29 10:08
I forgot that I did a little bit of work on this at d110ce2. Cool.

**Comment by cmbz** [comment] 2024-08-26 14:14
2024/08/26:
We are closing this issue. Implementing it affects reindexing, possibly in a negative way. Super users can currently do this, it could be problematic for others to do so. We will close for now and work to improve indexing functionality before implementing a feature like this.

**Closed by cmbz** 2024-08-26 14:14 UTC
Labels: Type: Feature, Feature: Search/Browse, UX & UI: Design, User Role: Depositor
