### ISSUE TITLE
Pain point: no drop down of controlled vocabularies for "Affiliation" for dataset authors

### ISSUE THREAD

**Issue by youssefOuahalou** [IQSS/dataverse#6406] opened 2019-11-25 13:41 UTC
Hi I hope you're fine,
When I want to add a new dataset, I have this error. I edit the .tsv file to add a drop-down menu. And I enter these two command curl to reload them: 

-curl http://localhost:8080/api/admin/datasetfield/load -X POST --data-binary @data/metadatablocks/citation.tsv -H "Content-type: text/tab-separated-values"

-curl -H "X-Dataverse-key:*******************
![AuthorAffiliation](https://user-images.githubusercontent.com/46802308/69545130-72dd4600-0f91-11ea-98b7-fe5778ea6b68.PNG)
![ErrorNewDataset](https://user-images.githubusercontent.com/46802308/69545131-72dd4600-0f91-11ea-9e65-cbc2461b0d99.PNG)

" -X POST -H "Content-type:application/json" -d "[\"citation\"]" http://localhost:8080/api/dataverses/:root/metadatablocks

-curl http://localhost:8080/api/admin/index/solr/schema

**Comment by youssefOuahalou** [comment] 2019-11-25 13:52
[citation.txt](https://github.com/IQSS/dataverse/files/3886888/citation.txt)

**Comment by djbrooke** [comment] 2019-11-27 14:53
Hi @youssefOuahalou, we don't recommend editing that file, as it's pretty core to the functioning of Dataverse. 

That being said, we should do a better job of allowing this, but it will need to be part of a larger redesign, which we're tracking in #6030. I'm going to close this as a duplicate of the third bullet there:

"I want depositors to select from a list of people provided by LDAP (or another system) for fields such as author, contributor, producer"

**Closed by djbrooke** 2019-11-27 14:53 UTC
