### ISSUE TITLE
Assigning Roles: Assigning a duplicate role results in less helpful message.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2928] opened 2016-02-08 16:51 UTC
When I attempt to assign the same role to the same user, it fails and presents an error in the ui:
 The role was not able to be assigned.  Please contact support. Date/Time: 2016-02-08 16:47:16 Server: dataverse-internal.iq.harvard.edu 

I was doing something not allowed but this could happen with long lists of users and it would be better if the message said This role has already been assigned or something like that since the server log error reports:

Internal Exception: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "unq_roleassignment_0"
  Detail: Key (assigneeidentifier, role_id, definitionpoint_id)=(@dataverseAdmin, 1, 5) already exists.

**Comment by mheppler** [comment] 2016-02-10 20:13
@kcondon - is this issue a duplicate of #1503?

**Closed** 2016-02-22 19:43 UTC
Labels: Component: Permissions, Priority: Medium, Status: Duplicate, Type: Suggestion
