### ISSUE TITLE
Datafile suggested citation doesn't include file DOI

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#4777] opened 2018-06-23 18:11 UTC
The suggested citation that appears on a 4.9 datafile page is currently just the suggested citation for the dataset with the file name and the text'[filename]' postpended. With file DOIs now being generated, it seems like the suggested citation should be updated, e.g. to postpend the file name and file DOI for example. An alternative would be to change the whole citation to just reference the file (which would require changing the text 'This file is part of "<dataset name>". If you use this file, please cite the data project:' that is directly above the citation block). I personally think that keeping the citation focused on the dataset and just adding the filename and DOI is a good approach, but I don't know if that would work for everyone/if this needs to be a config option, etc.

**Comment by qqmyers** [comment] 2018-06-24 16:18
Per discussion in  https://github.com/IQSS/dataverse/issues/2438 and on the community group (https://groups.google.com/forum/#!msg/dataverse-community/ZY53hidy-MU/MaU2YtJUBwAJ), it sounds like the idea of including both the dataset and file DOI in the citation was not a desired solution. 

It may still be an open question whether a direct data file citation is desirable as an alternative to citing the dataset and mentioning the file...

**Comment by djbrooke** [comment] 2018-06-28 16:09
@scolapasta you mentioned yesterday in backlog grooming that there were a few options for moving forward here. Assigning to you for the specifics.

@qqmyers - do you have any availability to pick this up once we get feedback from the Community + @mercecrosas  and others about what we want to do here?

**Comment by qqmyers** [comment] 2018-06-28 20:33
@djbrooke - I think so. Looks like the latest discussion is along the lines of the image below. In testing how to do this, I realized that the code for the endnote, ris, and bibtex downloads has to be modified as well... (and the help link to data citation practices might need to move so it is not repeated.)  

![image](https://user-images.githubusercontent.com/6731983/42059204-a9895ca2-7af0-11e8-899a-67e06ce33afa.png)

**Comment by pdurbin** [comment] 2018-07-03 14:36
@qqmyers thanks for making pull request #4802! I just dragged this issue to code review at https://waffle.io/IQSS/dataverse

**Comment by pdurbin** [comment] 2018-07-09 19:22
It was driving me crazy that DataCitation.java had zero code coverage among it's 623 lines so I pushed a test in 4c67e61 to increase it to 24%. I don't want to hold up QA but in the future I hope we can add more tests.

## Before

![screen shot 2018-07-09 at 3 12 41 pm](https://user-images.githubusercontent.com/21006/42471409-910bf66e-838b-11e8-85fc-ab1da769fdb3.png)

## After

![screen shot 2018-07-09 at 3 14 17 pm](https://user-images.githubusercontent.com/21006/42471408-90fe85f6-838b-11e8-9819-9cb05f4005c8.png)

**Comment by scolapasta** [comment] 2018-07-09 19:32
@qqmyers can you make a small change to the text?

I ran this by Merce to check on on the citation formats / labels, and since the first citation includes the file details, it's better to say:
For the first citation: Cite dataset and file
For the second citation: Cite file directly

**Comment by adam3smith** [comment] 2018-07-19 16:11
Thinking more about this, I'm not convinced what we're doing with this is optimal. As of now we have three different citations:
1. Dataset citation
2. Dataset with file citation (equivalent of current data file citation)
3. Data file citation.

with 1 on the dataset landing page, 2 and 3 on the data file landing page.

Logically these also correspond to three different sets of metadata. I think that's very confusing. With two different versions of a file citation on the file landing page, it's also unclear which of them should be encoded in schema.org metadata on that page.

I would suggest, instead, to make 1. and 2. identical, so we have 
1. Dataset citation 
2. Data file citation

In other words, get rid of the <filename>[file name] at the end of the dataset citation on file landing pages.

If people want to cite a specific file, they should just use 2. In the more common case, where they're looking at a file but really mean to cite the whole dataset, we should have 1. available on the file landing page (as per the discussion in the community group). Thoughts?

### To illustrate: 

_Currently implemented_
![image](https://user-images.githubusercontent.com/128986/42953359-45891cca-8b48-11e8-860b-ca7a6d750f03.png)

_Suggested change:_
![image](https://user-images.githubusercontent.com/128986/42953479-85269704-8b48-11e8-8bb5-eb6c85866420.png)

(recall that QDR uses "data project" instead of "dataset")

**Comment by scolapasta** [comment] 2018-07-19 16:18
@mercecrosas thoughts on @adam3smith's comment? (this is related to one of our recent discussions)

**Comment by mercecrosas** [comment] 2018-07-19 19:20
I do agree that is cleaner and less confusing to display simply:

Dataset citation
File citation

The reason to include the "dataset with file citation" was to maintain the
standard proposed by Altman & King 2007. However, we PID for files, now it
makes less sense to maintain that format, so it seems reasonable to change
it and use the proposed File Citation. I'd like to make sure though that
what we implement follows best practices or any existing standards, if
applies.

@adam3smith
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_adam3smith&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=n9HCCtgqDPssu5vpqjbO3q4h2g6vMeTOp0Ez7NsdVFM&m=CQ_ezhcbh77o30L9bfecuj09ykCc5q2VoenOwTZn6xs&s=EfzAT6qhGLJ7s_6motpfDLkxfTgng97YTWNAThZzx5Q&e=>
Have
you checked with Martin Fenner and others (perhaps other repositories) to
see if your suggested format for the File citation is adequate and follows
good practice or some standard?

Merce

----------
Mercè Crosas, Ph.D., Chief Data Science and Technology Officer, IQSS, Harvard
University
@mercecrosas <https://twitter.com/mercecrosas>  scholar.harvard.
edu/mercecrosas

**Comment by adam3smith** [comment] 2018-07-19 19:22
No, I haven't yet -- happy to check

**Comment by adam3smith** [comment] 2018-07-26 16:44
@mercecrosas -- haven't heard back from Martin. Do you have any other thoughts on who to ask? My view would be to just go ahead with this change. I tried to look for standards and practices on file citations when I made the original proposal and didn't  find anything at all.

**Comment by mercecrosas** [comment] 2018-07-26 17:03
This makes sense.

Here is what I think we should implement as a general rule:

- If there is a PID (now DOI) assigned to a file, display file citation (in
addition to dataset citation)
- If files doesn't have a PID, display Dataset with file citation


----------
Mercè Crosas, Ph.D., Chief Data Science and Technology Officer, IQSS, Harvard
University
@mercecrosas <https://twitter.com/mercecrosas>
scholar.harvard.edu/mercecrosas

**Comment by adam3smith** [comment] 2018-07-26 17:04
Yes, that makes sense to me, too.

**Comment by pdurbin** [comment] 2018-08-08 19:34
I'm copying a comment from @qqmyers just now from https://github.com/IQSS/dataverse/pull/4802#issuecomment-411512289 ...

"I think this PR may be ready again for review. It should now contain @adam3smith 's updates to the RIS and endnote exports and the consensus to provide a dataset and file citations on the file page (with the latter using the file DOI if published and appending the filename to the dataset citation if not)."

... and just moved this issue to code review.

**Comment by mheppler** [comment] 2018-08-09 20:09
@TaniaSchlatter has suggested a background color change, and I don't mind going into the branch to make it. I might take the liberty of also cleaning up the layout of the text around the citation blocks as well.

**Comment by mheppler** [comment] 2018-08-16 19:58
I have created a new [`4777-file-pg-citations-layout` branch](https://github.com/IQSS/dataverse/compare/4777-file-pg-citations-layout) off of the original #4802 pull request from @qqmyers. I will create a new PR for that and link it to this issue.

Here is the cleaned up layout.

<img width="960" alt="screen shot 2018-08-16 at 11 52 41 am" src="https://user-images.githubusercontent.com/687227/44231717-0f008680-a16d-11e8-9cd9-8919966c2652.png">

- "This file is part of "{dataset.title}" is styled with the muted grey
- "Cite the dataset:" label above the dataset citation block was changed to "Dataset Citation" and styled like our other labels in the UI
- Same with "File Citation" label text
- File citation block was changed to grey to better differentiate the dataset vs file citations
- Block column widths were adjusted to keep "Learn about Data Citation Standards" on one line

**Comment by pdurbin** [comment] 2018-08-17 19:49
The status of this issue wasn't immediately clear to me so here's a screenshot of the conversation from https://github.com/IQSS/dataverse/pull/4971#pullrequestreview-147340481

![screen shot 2018-08-17 at 3 48 08 pm](https://user-images.githubusercontent.com/21006/44285897-0b383700-a235-11e8-850a-74dca5c3656a.png)

I put it back into code review because that seems to be the right spot.

**Comment by kcondon** [comment] 2018-08-24 22:53
Noticed a couple things:
1. dataset title in file citation block is italicized.
2. downloading RIS from citation throws exception, works in /develop:

[2018-08-24T18:47:30.003-0400] [glassfish 4.1] [WARNING] [AS-EJB-00056] [javax.enterprise.ejb.container] [tid: _ThreadID=50 _ThreadName=jk-connector(1)] [timeMillis: 1535150850003] [levelValue: 900] [[
  A system exception occurred during an invocation on EJB FileDownloadServiceBean, method: public void edu.harvard.iq.dataverse.FileDownloadServiceBean.downloadDatasetCitationRIS(edu.harvard.iq.dataverse.Dataset)]]

[2018-08-24T18:47:30.003-0400] [glassfish 4.1] [WARNING] [] [javax.enterprise.ejb.container] [tid: _ThreadID=50 _ThreadName=jk-connector(1)] [timeMillis: 1535150850003] [levelValue: 900] [[
  
javax.ejb.EJBException
	at com.sun.ejb.containers.EJBContainerTransactionManager.processSystemException(EJBContainerTransactionManager.java:748)
	at com.sun.ejb.containers.EJBContainerTransactionManager.completeNewTx(EJBContainerTransactionManager.java:698)
	at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:503)
	at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4566)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2074)
	at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2044)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:220)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
	at com.sun.proxy.$Proxy629.downloadDatasetCitationRIS(Unknown Source)
	at edu.harvard.iq.dataverse.__EJB31_Generated__FileDownloadServiceBean__Intf____Bean__.downloadDatasetCitationRIS(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.el.ELUtil.invokeMethod(ELUtil.java:332)
	at javax.el.BeanELResolver.invoke(BeanELResolver.java:537)
	at javax.el.CompositeELResolver.invoke(CompositeELResolver.java:256)
	at com.sun.el.parser.AstValue.invoke(AstValue.java:283)
	at com.sun.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:304)
	at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
	at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
	at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105)
	at javax.faces.event.MethodExpressionActionListener.processAction(MethodExpressionActionListener.java:147)
	at javax.faces.event.ActionEvent.processListener(ActionEvent.java:88)
	at javax.faces.component.UIComponentBase.broadcast(UIComponentBase.java:813)
	at javax.faces.component.UICommand.broadcast(UICommand.java:300)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790)
	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282)
	at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:295)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:412)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at edu.harvard.iq.dataverse.DataCitation.flattenHtml(DataCitation.java:634)
	at edu.harvard.iq.dataverse.DataCitation.writeAsRISCitation(DataCitation.java:314)
	at edu.harvard.iq.dataverse.FileDownloadServiceBean.downloadCitationRIS(FileDownloadServiceBean.java:318)
	at edu.harvard.iq.dataverse.FileDownloadServiceBean.downloadDatasetCitationRIS(FileDownloadServiceBean.java:282)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)
	at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.GeneratedMethodAccessor2448.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at sun.reflect.GeneratedMethodAccessor2449.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4758)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4746)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
	... 63 more
]]

**Comment by adam3smith** [comment] 2018-08-26 11:56
1. Is intentional on our end. It mirrors the use of italics for book titles in book chapter citations, on which we modelled the data file citation. I'd recommend keeping them.

**Comment by qqmyers** [comment] 2018-08-26 17:56
2. Fix in a PR 4999

**Comment by djbrooke** [comment] 2018-08-27 14:30
Thanks @adam3smith and @qqmyers for the information and the fix!

**Comment by kcondon** [comment] 2018-08-27 17:07
@qqmyers OK, confirmed RIS download is working, thanks. Noticed italicized title is now normal text in file citation. Was that changed? We are taking @adam3smith advice on this and are fine with italicized.

**Closed** 2018-08-27 17:33 UTC
Labels: Status: QA

**Comment by qqmyers** [comment] 2018-08-27 18:46
@kcondon - I didn't change the italics. It does only apply to published files where the citation includes the file title then the dataset title in italics versus the file title being appended for unpublished ones.

**Comment by jggautier** [comment] 2018-08-28 19:45
Spoke with @adam3smith about the citation styles for files versus datasets. Bit of a puzzle. He pointed out that for most citation styles, when the citation includes two objects, like a chapter and the book that the chapter is in, the secondary object (like the book) is never in quotes. So keeping the dataset title in quotes when it's in the file citation would break that rule and may confuse users.

But because the dataset title of the dataset citation IS in quotes, this means that the dataset title won't be styles the same. One solution is to use something other than quotes for the dataset title in the dataset citation, but this would change Dataverse's dataset citation style.
