### ISSUE TITLE
Create Dataset Page: fails on restricting a file when missing a required dataset field

### ISSUE THREAD

**Issue by ferrys** [IQSS/dataverse#3896] opened 2017-06-13 18:49 UTC
On the `develop` branch, creating a dataset violates a bean validation constraint on prePersist when a user uploads a file and tries to restrict it while creating a dataset **only if** they miss a required field and try to save it again.

`[2017-06-13T18:30:29.732+0000] [glassfish 4.1] [SEVERE] [] [edu.harvard.iq.dataverse.EjbDataverseEngine] [tid: _ThreadID=29 _ThreadName=http-listener-1(1)] [timeMillis: 1497378629732] [levelValue: 1000] [[
  Unexpected bean validation constraint exception: Invalid value: <<<null>>> for identifier at [Dataset id:null ] - Please enter an identifier for your dataset.]]`

**Comment by pdurbin** [comment] 2018-10-17 20:35
Closing as a duplicate of #5190

**Closed by pdurbin** 2018-10-17 20:35 UTC
Labels: Feature: File Upload & Handling, Feature: Request Access Workflow, User Role: Depositor
