### ISSUE TITLE
Updating a dataset with Native API is bugged

### ISSUE THREAD

**Issue by omaralsoudanii** [IQSS/dataverse#3899] opened 2017-06-14 08:07 UTC
> PUT http://$SERVER/api/datasets/$id/versions/:draft?key=$apiKey

> 
where $id = database id of the dataset,
Using v. 4.2.3 , I add a dataset and then try to update it with the same json structure as per the documentation here

> Updates the current draft version of dataset $id. If the dataset does not have an draft version - e.g. when its most recent version is published, a new draft version is created. The invariant is - after a successful call to this command, the dataset has a DRAFT version with the passed data. The request body is a dataset version, in json format.

> 
which can be found here : http://guides.dataverse.org/en/4.2/api/native-api.html
However this returns error 404 not found  ,
If this is due to incorrect JSON format ( note that i used the format for adding a dataset and it worked ) what's the format for editing?

**Comment by pdurbin** [comment] 2017-06-14 10:51
@omaralsoudanii please see if this comment helps: https://github.com/IQSS/dataverse/issues/3777#issuecomment-295358540

**Comment by omaralsoudanii** [comment] 2017-06-17 06:27
@pdurbin I managed to fix it by removing "datasetVersion" key and sending the JSON file through curl and it's working even if there is a file exist ,I think the error appears when "datasetVersion" is in the JSON payload ,Thanks for the help.

**Comment by pdurbin** [comment] 2017-06-17 14:05
@omaralsoudanii you're welcome. I'm glad you got it working. I think of this issue as a duplicate of #3777 so please feel free to close it. The team discussed #3777 on Monday when we were doing practice talks for the 2017 Dataverse Community Meeting so it's on our minds. Also @leeper made pull request #3912 about the API Guide and I'm hoping it spurs me on to make some improvements to that guide.

**Closed** 2017-06-17 16:47 UTC
Labels: Component: API, Component: Documentation
