### ISSUE TITLE
Are there anymore datasets/dataverses in search results but not in database?

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#4205] opened 2017-10-13 19:06 UTC
An unpublished dataset and dataverse (which someone uploaded for testing purposes in 2015) show up in search results on Harvard Dataverse, but they no longer exist in the database. When logged in as a superuser, you can see the problem dataset, the only result from this search on Harvard Dataverse : https://dataverse.harvard.edu/dataverse/harvard?q=title%3A%22test+file+2%22.

Clicking on the dataset and its dataverse gives 404 and validation errors. This is Harvard Dataverse on Dataverse 4.8.1. How can we see if anything else would show up in search results (is indexed in Solr?) that doesn't exist in the database?

**Comment by pdurbin** [comment] 2017-10-13 19:15
Years ago in #702 I stubbed out some code with the intention of being able to display when Solr is out of sync with the database. I never documented it because it's buggy and slow but here's how you would call it:

```
curl -s http://localhost:8080/api/admin/index/status | jq .
{
  "status": "OK",
  "data": {
    "contentInDatabaseButStaleInOrMissingFromIndex": {
      "dataverses": 0,
      "datasets": 0
    },
    "contentInIndexButNotDatabase": {
      "dataverses": 0,
      "datasets": 0,
      "files": 0
    },
    "permissionsInDatabaseButStaleInOrMissingFromIndex": {
      "dvobjects": 2
    },
    "permissionsInIndexButNotDatabase": {
      "dvobjects": 0
    }
  }
}
```

In the absence of a working "index status" feature like that the best we can do is hit Solr directly with:

- a search for the offending Solr document (hit)
- a delete against that document
- a second search for the offending doc (now gone)

I'll try to post some curl commands here soon. I'm not sure what the definition of done is for this issue but maybe we can just throw the curl commands in the Admin Guide for now.

**Comment by pdurbin** [comment] 2017-10-16 14:31
@kcondon @jggautier here are some quick and dirty curl commands based on some quick testing on https://dev1.dataverse.org running v. 4.8.1 as of 494bc23.

The scenario is:

- User creates a dataset.
- Solr goes down.
- User changes mind and deletes dataset while Solr is still down and gets a weird message about Solr being down (screenshot 1 below).
- Solr comes back up.
- Stale data for the dataset and the "permission document" are still in Solr. The dataset is still visible from the root dataverse but when you click it, you get an error that it can't be found (screenshot 2 below).
- Sysadmin comes along and does manual cleanup via a series of curl commands.
- The deleted dataset is no longer visible from the root dataverse. The cruft in Solr has been deleted.

![screen shot 2017-10-16 at 10 12 58 am](https://user-images.githubusercontent.com/21006/31617225-ae765d6c-b25c-11e7-971d-59b630e5e124.png)

![screen shot 2017-10-16 at 10 14 05 am](https://user-images.githubusercontent.com/21006/31617372-0231478c-b25d-11e7-8e60-cea8de6c53c4.png)


```
[root@dvnweb-vm2 dataverse]# grep -v ^# scripts/search/query
curl -s 'http://localhost:8983/solr/collection1/select?rows=1000000&wt=json&indent=true&q=*%3A*'
[root@dvnweb-vm2 dataverse]# 

[root@dvnweb-vm2 dataverse]# scripts/search/query | grep 5ZZUKP
182331 [qtp519821334-19] INFO  org.apache.solr.core.SolrCore  – [collection1] webapp=/solr path=/select params={q=*:*&indent=true&rows=1000000&wt=json} hits=29 status=0 QTime=0 
        "identifier":"doi:10.5072/FK2/5ZZUKP",
        "dsPersistentId":"doi:10.5072/FK2/5ZZUKP",
        "persistentUrl":"http://dx.doi.org/10.5072/FK2/5ZZUKP",
        "citation":"Admin, Dataverse, 2017, \"issue4205\", doi:10.5072/FK2/5ZZUKP, Root, DRAFT VERSION",
        "citationHtml":"Admin, Dataverse, 2017, \"issue4205\", <a href=\"http://dx.doi.org/10.5072/FK2/5ZZUKP\" target=\"_blank\">doi:10.5072/FK2/5ZZUKP</a>, Root, DRAFT VERSION",
[root@dvnweb-vm2 dataverse]# 
[root@dvnweb-vm2 dataverse]# curl -s 'http://localhost:8983/solr/collection1/select?rows=1000000&wt=json&indent=true&q=identifier%3A*5ZZUKP'
349460 [qtp519821334-17] INFO  org.apache.solr.core.SolrCore  – [collection1] webapp=/solr path=/select params={q=identifier:*5ZZUKP&indent=true&rows=1000000&wt=json} hits=1 status=0 QTime=20 
{
  "responseHeader":{
    "status":0,
    "QTime":20,
    "params":{
      "q":"identifier:*5ZZUKP",
      "indent":"true",
      "rows":"1000000",
      "wt":"json"}},
  "response":{"numFound":1,"start":0,"docs":[
      {
        "id":"dataset_14_draft",
        "entityId":14,
        "dataverseVersionIndexedBy_s":"4.8.1",
        "identifier":"doi:10.5072/FK2/5ZZUKP",
        "dsPersistentId":"doi:10.5072/FK2/5ZZUKP",
        "persistentUrl":"http://dx.doi.org/10.5072/FK2/5ZZUKP",
        "dvObjectType":"datasets",
        "publicationStatus":["Unpublished",
          "Draft"],
        "dateSort":"2017-10-16T14:11:18.308Z",
        "dateFriendly":"Oct 16, 2017",
        "isHarvested":false,
        "metadataSource":"Root",
        "datasetVersionId":3,
        "citation":"Admin, Dataverse, 2017, \"issue4205\", doi:10.5072/FK2/5ZZUKP, Root, DRAFT VERSION",
        "citationHtml":"Admin, Dataverse, 2017, \"issue4205\", <a href=\"http://dx.doi.org/10.5072/FK2/5ZZUKP\" target=\"_blank\">doi:10.5072/FK2/5ZZUKP</a>, Root, DRAFT VERSION",
        "nameSort":"issue4205",
        "title":"issue4205",
        "authorName":["Admin, Dataverse"],
        "authorName_ss":["Admin, Dataverse"],
        "affiliation_ss":["Dataverse.org"],
        "authorAffiliation":["Dataverse.org"],
        "authorAffiliation_ss":["Dataverse.org"],
        "datasetContactName":["Admin, Dataverse"],
        "datasetContactAffiliation":["Dataverse.org"],
        "dsDescriptionValue":["Are there anymore datasets/dataverses in search results but not in database? · Issue #4205 · IQSS/dataverse"],
        "subject":["Other"],
        "subject_ss":["Other"],
        "depositor":"Admin, Dataverse",
        "dateOfDeposit":"2017",
        "dateOfDeposit_s":"2017",
        "parentId":"1",
        "parentName":"Root",
        "_version_":1581423608600723456}]
  }}
[root@dvnweb-vm2 dataverse]# 
[root@dvnweb-vm2 dataverse]# curl -s 'http://localhost:8983/solr/collection1/select?rows=1000000&wt=json&indent=true&q=definitionPointDocId%3Adataset_14_draft'
448438 [qtp519821334-14] INFO  org.apache.solr.core.SolrCore  – [collection1] webapp=/solr path=/select params={q=definitionPointDocId:dataset_14_draft&indent=true&rows=1000000&wt=json} hits=1 status=0 QTime=1 
{
  "responseHeader":{
    "status":0,
    "QTime":1,
    "params":{
      "q":"definitionPointDocId:dataset_14_draft",
      "indent":"true",
      "rows":"1000000",
      "wt":"json"}},
  "response":{"numFound":1,"start":0,"docs":[
      {
        "id":"dataset_14_draft_permission",
        "definitionPointDocId":"dataset_14_draft",
        "definitionPointDvObjectId":"14",
        "discoverableBy":["group_user1",
          "group_user1"],
        "_version_":1581423609054756864}]
  }}
[root@dvnweb-vm2 dataverse]# 
[root@dvnweb-vm2 dataverse]# grep delete scripts/search/clear
curl http://localhost:8983/solr/update/json?commit=true -H "Content-type: application/json" -X POST -d "{\"delete\": { \"query\":\"*:*\"}}"
[root@dvnweb-vm2 dataverse]# 
[root@dvnweb-vm2 dataverse]# curl http://localhost:8983/solr/update/json?commit=true -H "Content-type: application/json" -X POST -d "{\"delete\": { \"query\":\"identifier:*5ZZUKP\"}}"
[root@dvnweb-vm2 dataverse]# curl http://localhost:8983/solr/update/json?commit=true -H "Content-type: application/json" -X POST -d "{\"delete\": { \"query\":\"definitionPointDocId:dataset_14_draft\"}}"
```

**Comment by pdurbin** [comment] 2017-10-20 15:34
## Search for a specific Solr doc of a dataset to get the id ("id":"dataset_14_draft")

`curl -s 'http://localhost:8983/solr/collection1/select?rows=1000000&wt=json&indent=true&q=identifier%3A*5ZZUKP'`

**Comment by kcondon** [comment] 2017-10-20 19:11
OK, could not find the record using the identifier but did find it using authorName and checking the resulting identifier:
curl -s 'http://localhost:8983/solr/collection1/select?rows=1000000&wt=json&indent=true&q=authorName%3A*Kappenman'

{
  "responseHeader":{
    "status":0,
    "QTime":1,
    "params":{
      "q":"authorName:*Kappenman",
      "indent":"true",
      "rows":"1000000",
      "wt":"json"}},
  "response":{"numFound":1,"start":0,"docs":[
      {
        "id":"dataset_2668955_draft",
        "entityId":2668955,
        "identifier":"doi:10.7910/DVN/PM8ZXQ",
        "dsPersistentId":"doi:10.7910/DVN/PM8ZXQ",
        "persistentUrl":"http://dx.doi.org/10.7910/DVN/PM8ZXQ",
        "dvObjectType":"datasets",
        "publicationStatus":["Unpublished",
          "Draft"],
        "dateSort":"2015-04-22T17:59:35.667Z",
        "dateFriendly":"Apr 22, 2015",
        "datasetVersionId":68933,
        "citation":"Kappenman, Emily, 2015, \"Test File 2\", <a href=\"http://dx.doi.org/10.7910/DVN/PM8ZXQ\">http://dx.doi.org/10.7910/DVN/PM8ZXQ</a>,  Harvard Dataverse,  DRAFT VERSION ",
        "nameSort":"Test File 2",
        "title":"Test File 2",
        "authorName":["Kappenman, Emily"],
        "authorName_ss":["Kappenman, Emily"],
        "datasetContactName":["Kappenman, Emily"],
        "dsDescriptionValue":["Testing another file"],
        "subject":["Other"],
        "subject_ss":["Other"],
        "depositor":"Kappenman, Emily",
        "dateOfDeposit":"2015",
        "dateOfDeposit_s":"2015",
        "subtreePaths":["/2668793",
          "/2668793/2668952"],
        "parentId":"2668952",
        "parentName":"Another Test ",
        "_version_":1499175926638837760}]
  }}

Then deleted it:

curl http://localhost:8983/solr/update/json?commit=true -H "Content-type: application/json" -X POST -d "{\"delete\": { \"query\":\"id:dataset_2668955_draft\"}}"
{"responseHeader":{"status":0,"QTime":702}}

**Comment by kcondon** [comment] 2017-10-20 19:23
The specific record has been removed. I'm keeping this open as a general feature request to have something that can check for disparities (should be rare) between the index and database, namely orphaned records in the index which no longer exist in the db.

**Comment by pdurbin** [comment] 2017-10-20 19:49
> could not find the record using the identifier

The dataset is so old (2015) that maybe it was indexed when "identifier" wasn't searchable. We fixed this in #2038.

**Comment by matthew-a-dunlap** [comment] 2018-05-30 22:32
There was discussion today around potential mismatches between solr and the db causing search to error in production. Here are some notes:
* Searching Tab and * for file type is causing a 500 internal server error
* Errors seem to be at the primefaces level
* We think this is an issue when solr isn't cleaned up right after a delete or error
* One solution is we could compare db ids to the solr indexed files and purge regularly
* We are going to have to do some sort of indexing with 4.9 coming out, so this may be fixed somewhat from that
    * If we go with the full indexing route which will take almost a day, users will need to be notified about incomplete results in the interim.
* Even if full indexing helps, we should also be handling the bad data before it hits primefaces and explodes.

Here is the error produced from searching tab or * :
 ```
[2018-05-30T13:01:24.935-0400] [glassfish 4.1] [SEVERE] [] [javax.enterprise.resource.webcontainer.jsf.application] [tid: _ThreadID=7627 _ThreadName=jk-connector(25)] [timeMillis: 1527699684935] [levelValue: 1000] [[
  Error Rendering View[/dataverse.xhtml]
javax.el.ELException: /search-include-fragment.xhtml: java.lang.NullPointerException
	at com.sun.faces.facelets.compiler.AttributeInstruction.write(AttributeInstruction.java:94)
	at com.sun.faces.facelets.compiler.UIInstructions.encodeBegin(UIInstructions.java:82)
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:302)
	at com.sun.faces.renderkit.html_basic.PassthroughRenderer.encodeChildren(PassthroughRenderer.java:104)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:889)
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:304)
	at com.sun.faces.renderkit.html_basic.TableRenderer.renderRow(TableRenderer.java:385)
	at com.sun.faces.renderkit.html_basic.TableRenderer.encodeChildren(TableRenderer.java:161)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:889)
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:304)
	at com.sun.faces.renderkit.html_basic.PassthroughRenderer.encodeChildren(PassthroughRenderer.java:104)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:889)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:456)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:133)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
	at org.ocpsoft.rewrite.faces.RewriteViewHandler.renderView(RewriteViewHandler.java:196)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:647)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.ApplicationDispatcher.doInvoke(ApplicationDispatcher.java:873)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:739)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:575)
	at org.apache.catalina.core.ApplicationDispatcher.doDispatch(ApplicationDispatcher.java:546)
	at org.apache.catalina.core.ApplicationDispatcher.dispatch(ApplicationDispatcher.java:428)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:378)
	at org.ocpsoft.rewrite.servlet.impl.HttpRewriteResultHandler.handleResult(HttpRewriteResultHandler.java:42)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.rewrite(RewriteFilter.java:297)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:198)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:412)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
]]

[2018-05-30T13:01:24.935-0400] [glassfish 4.1] [WARNING] [] [javax.enterprise.web.core] [tid: _ThreadID=7627 _ThreadName=jk-connector(25)] [timeMillis: 1527699684935] [levelValue: 900] [[
  Servlet.service() for servlet Faces Servlet threw exception
java.lang.NullPointerException
]]

[2018-05-30T13:01:24.936-0400] [glassfish 4.1] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=7627 _ThreadName=jk-connector(25)] [timeMillis: 1527699684936] [levelValue: 900] [[
  StandardWrapperValve[default]: Servlet.service() for servlet default threw exception
java.lang.NullPointerException
```

**Comment by djbrooke** [comment] 2020-02-27 01:32
@jggautier I'm going to close this as a duplicate of #4225 and link up this issue from there.

**Closed by djbrooke** 2020-02-27 01:32 UTC
Labels: Feature: Search/Browse
