### ISSUE TITLE
As a Dataverse user, I want automated emails to include contact info so I can reach out for more info.

### ISSUE THREAD

**Issue by dlmurphy** [IQSS/dataverse#4541] opened 2018-03-26 17:11 UTC
Currently, automated emails from Dataverse do not include contact information. Let's automatically include this info in all automated emails, so users can know who to reach out to if they're confused, if they received the message in error, or if they just want more information.

This issue was inspired by Gary's recent report in our Slack:

> All emails that go out (especially the automatic ones) need to have contact info at the end of the signature. if it is going to the wrong person, that person needs to have someone to respond to. we can’t assume, as this message does, that we are always right in who the email is going to. please fix this and let’s look for other examples of this. thanks

[...]

> i’m not sure which contact it should be.  but let’s make sure that _every_ automated email we have has someone to contact.  at least an email address

Here's the example screenshot he included, showing an automated Dataverse email as it looks currently:
![37852460-0d1a25f0-2eb9-11e8-9b26-603ac53eb682](https://user-images.githubusercontent.com/22962740/37921098-cb4cb80a-30f6-11e8-82cb-ef0918b6badb.png)

**Comment by dlmurphy** [comment] 2018-03-26 17:16
Spoke with @scolapasta and @djbrooke about this. We'd like to include text at the end of every automated email that dynamically includes the contact email address of the installation sending out the email. 

In a new paragraph after the main body of the email, the message could read:

> If you believe you have received this message in error, you may contact us at [Dataverse installation support email].

or, if we want it to be more general:

> You may contact us for support at [Dataverse installation support email].

**Comment by pdurbin** [comment] 2018-04-04 14:12
I just created pull request #4567 and dragged this issue to code review at https://waffle.io/IQSS/dataverse

While I was in there, I noticed that we are signing the emails with the brand of the installation of Dataverse rather than the support email name. For example https://dataverse.lib.virginia.edu uses a support team name of "Libra Data Support":

![screen shot 2018-04-04 at 10 08 58 am](https://user-images.githubusercontent.com/21006/38312613-3263790c-37f0-11e8-8dd7-3e0246dd8ce1.png)

So while we are in this part of the code, we could change the closing from

```
Thank you,
Libra Data
```

to

```
Thank you,
Libra Data Support
```

I think having the email come from a support team (Libra Data Support) sounds friendlier than having it come from the brand of the installation (Libra Data) but I didn't want to make this change without talking about it first. I did go ahead and leave a comment in the code about this.

**Comment by pdurbin** [comment] 2018-04-04 16:14
I chatted with @mheppler after standup and he likes the idea of using the support team name (i.e. "Libra Data Support") in the closing so I'll work on that. We also decided that whatever appears in the "from" such as "Harvard Dataverse Support" (this is the support team name) should match what's in the closing. This would be more consistent. As of last summer, this wasn't consistent:

<img width="689" alt="screen shot 2018-04-04 at 11 56 15 am" src="https://user-images.githubusercontent.com/21006/38320113-ac42a44e-3801-11e8-890e-d4d53f6f858a.png">

**Comment by pdurbin** [comment] 2018-04-04 16:34
Ok, in a0740c9 I made the "from" and signature consistent. They are now both the support team name. In the example below I set the support team name using the example from http://guides.dataverse.org/en/4.8.6/installation/config.html#systememail ...

    curl -X PUT -d 'LibraScholar SWAT Team <support@librascholar.edu>' http://localhost:8080/api/admin/settings/:SystemEmail

... then I generated a welcome message. Note in the screenshots below that you now see "LibraScholar SWAT Team" in both the "from" and the closing:

![screen shot 2018-04-04 at 12 28 46 pm](https://user-images.githubusercontent.com/21006/38320968-1f57818c-3804-11e8-9b0f-2bc9752bef83.png)

![screen shot 2018-04-04 at 12 28 50 pm](https://user-images.githubusercontent.com/21006/38320967-1f42038e-3804-11e8-9631-c55d4a85720f.png)

(To make this example a little more real I probably should have changed the name of my root dataverse from "Root" to "LibraScholar".)

While I'm uploading screenshots I'll say that we could refactor this part of the code base if we want to increase our code coverage. All the red lines below are not tested by JUnit:

![screen shot 2018-04-04 at 12 30 31 pm](https://user-images.githubusercontent.com/21006/38320966-1f3714a6-3804-11e8-86d6-49dd1a4d7d8c.png)

**Comment by pdurbin** [comment] 2018-04-04 17:00
Meh, I took a quick swing at refactoring this code but it's a little hairy and makes this issue no longer a "1" so I'm stepping away.

@mheppler stopped by and we discussed how technically we could just add "or just reply to this email" since the email comes from the support address. I'll leave the wordsmithing to others. The code is now dynamic and included the support team's name and email address so if someone wants to adjust the wording it's just a matter of playing with `notification.email.closing` in `Bundle.properties` and updating `testEmailClosing` in `BrandingUtilTest.java`.

**Comment by mheppler** [comment] 2018-04-09 18:56
Testing on demo (v. 4.8.6 build 146-874a944) and confirmed email for publishing a dataset work as expected, email sent via the contact btn on dataverse pg never appeared in the contact's mailinator inbox.

**Comment by scolapasta** [comment] 2018-04-09 19:04
@mhepppler are you sure that the email is being set in the contact email metadata field? 

The form isn't sent to a user by role but by what's in that field.

**Comment by mheppler** [comment] 2018-04-09 19:11
@scolapasta the required/pre-filled contact fields are correctly set for both the dataverse and dataset.

Also, sat with @djbrooke and confirmed that this contact btn bugginess is not on production (v. 4.8.6 build 146-874a944) -- which I guess suggests it could be a set up issue since it's the same build as demo...??

**Comment by kcondon** [comment] 2018-04-09 23:13
OK tested the automatic emails and also confirmed they are working so this ticket should be closable. The other issue, contact dv owner, is preexisting and likely a config issue involving email servers not wanting to forward email with a from address not in email server domain.

Merging this issue and other issue should be worked on separately.

**Closed** 2018-04-09 23:16 UTC
Labels: Status: QA

**Comment by pdurbin** [comment] 2018-04-09 23:45
Phew! I'm glad things aren't horribly broken. I would have been surprised if they were!

**Comment by mheppler** [comment] 2018-04-10 13:50
The email issues that I found on dvn-build and demo could be explained by existing issues. If not, we can create a new issue to resolve them.

- Documentation: add recommendation that jvm-option and :SystemEmail options match to avoid spam filters #4210
- Request access for restricted files with terms not working from the file page #4554
