### ISSUE TITLE
Clean up user code (review specific methods for shib and built in user on AuthenticatedUser)

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1456] opened 2015-02-17 21:24 UTC

**Comment by pdurbin** [comment] 2016-01-08 14:12
@scolapasta what is this issue about?

**Comment by pdurbin** [comment] 2016-04-20 19:33
"methods that were specific to shibboleth that ideally would exist in a general way or not at all"

**Comment by pdurbin** [comment] 2016-12-21 21:34
As @mheppler suggested at https://github.com/IQSS/dataverse/issues/3486#issuecomment-268636806 I think we should close this issue in favor of #3486.

**Comment by mheppler** [comment] 2016-12-21 21:35
Duplicate of **Improve consistency of various remote auth options (Shibboleth vs. OAuth) #3486**

**Closed** 2016-12-21 21:35 UTC
Labels: Component: Code Infrastructure, Status: Triaged

**Comment by pdurbin** [comment] 2017-06-25 16:02
@scolapasta do you agree that we should close this one?
