### ISSUE TITLE
Zip File Download Error Messaging: You shouldn't have to unzip the archive and read a manifest file to know there was an error

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2060] opened 2015-04-21 15:23 UTC
Reported by a user https://twitter.com/AABoyles/status/590509840532971520 that the file download error messaging only appears if you open up the manifest file. There should be clearer error messaging directly in the UI if a single file or a group of selected files fail to download.

**Comment by eaquigley** [comment] 2015-04-21 18:52
@posixeleni is this happening only with files that have been zipped or is this for all files that aren't properly downloading?

**Comment by posixeleni** [comment] 2015-04-21 19:10
@eaquigley from this users error this looks to be only about error messaging for zipped file downloads but I am not sure about error messaging for individual file downloads.

**Comment by eaquigley** [comment] 2015-04-30 18:38
@landreev can you answer if the file download error message is only in the manifest for a zip file that fails? or if all error messages for file download behave this way.

**Comment by eaquigley** [comment] 2015-08-10 13:51
Moving into 4.2 as downloading multiple files is scheduled to occur during this milestone. Error message currently displaying only in the readme file for the downloads, needs to also display in the UI when a user attempts to download multiple files and it is too big to allow them to unselect files and try downloading without having to wait to open the readme file.

**Comment by eaquigley** [comment] 2015-09-25 16:24
Mockups for this found here: https://iqssharvard.mybalsamiq.com/projects/filesallthings-enduser-dataverse42andbeyond/Dataset%20-%20Files%20-%20Download%20Limit%20Error

Passing to @sekmiller

**Comment by mheppler** [comment] 2016-02-03 20:42
I was able to replicate this locally. The issue relates to the "Download" button at the top of the files page not properly handling when restricted files are selected, whether it's multiple files or a single file. The same problem has been reported by @sbarbosadataverse in #2722.

**Comment by pdurbin** [comment] 2016-12-12 15:03
This bug was reported at https://twitter.com/justin_littman/status/803929260759154688 a couple weeks ago.

**Comment by kcondon** [comment] 2017-05-24 21:52
Reported again today, see RT 249731

**Comment by pdurbin** [comment] 2018-04-09 18:28
I'm closing this as a duplicate of #4576.

**Closed** 2018-04-09 18:28 UTC
Labels: Feature: File Upload & Handling, Status: UX & UI, Type: Feature, User Role: Guest
