### ISSUE TITLE
Minor version number is not included in citation

### ISSUE THREAD

**Issue by mankoff** [IQSS/dataverse#7202] opened 2020-08-15 14:41 UTC
The minor version number is not included in the reference. For example, going to

https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.70122/FK2/EIB6CG&version=DRAFT

The yellow **info** box states, `Info – The "DRAFT" version was not found. This is version "3.1".`, but the citation is: ` mankoff, ken, 2020, "test for file replacement", https://doi.org/10.70122/FK2/EIB6CG, Demo Dataverse, V3`. Note **V3** at the end, not **V3.1**.

**Comment by pdurbin** [comment] 2020-08-24 20:07
My understanding is that is it by design that the citation only shows major versions (V3) instead of minor versions (V3.1).

**Comment by mankoff** [comment] 2020-08-24 20:11
That may be, in which case please consider this a feature request to change that design?

**Metadata is important** (I assume we agree on this) and changing it may have downstream impacts. I don't see any good reason to hide those changes.

**Comment by BPeuch** [comment] 2021-03-01 14:07
Seconded!

**Comment by pdurbin** [comment] 2022-10-01 01:53
I changed "reference" to "citation" in the title. We get lots of requests for more flexibility in how the citation is displayed. I believe this is the oldest such issue:

- #2297

**Comment by cmbz** [comment] 2024-08-20 15:19
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Closed by cmbz** 2024-08-20 15:19 UTC
Labels: Type: Suggestion, Feature: Metadata, User Role: Depositor
