### ISSUE TITLE
File Permissions Page: If you add an already existing user to files, message should say "user already exists"

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2913] opened 2016-02-03 22:18 UTC
instead message says "not able to add role please contact ......"

**Comment by mheppler** [comment] 2016-02-04 15:16
Sonia, is this a duplicate of #1503 "Role Assignment: Able to Attempt to Assign the Same Role to the Same User Multiple Times"? If not, could you clarify the issue in more detail. Thanks.

**Closed** 2016-02-09 18:31 UTC
Labels: Component: Permissions, Priority: Medium, Status: Duplicate, Type: Feature
