### ISSUE TITLE
installer: UNCONFIRMED: noninteractive stops on prompt with "asadmin login"

### ISSUE THREAD

**Issue by otheus** [IQSS/dataverse#5177] opened 2018-10-12 15:04 UTC
When using `default.config` and `-y` options, the installer will enter "noninteractive" mode, skipping all prompts. However, when initializing a login for glassfish, the user will still be prompted with the name of the admin user for glassfish. 

          When/if asadmin askes you to Enter admin user name,
          it should be safe to hit return and accept the default
          which is admin
          
          Press any key to continue...
          
          Enter admin user name >

The last line waits for a prompt. This is undesirable. Maybe if the TTY or stdin is closed this won't happen?

**Comment by pdurbin** [comment] 2018-10-12 15:12
@otheus thanks for opening this issue and for all the chatter at http://irclog.iq.harvard.edu/dataverse/2018-10-12

I just wanted to point out that problem above is as of 4.9.4 with the installer coming from the dvinstall.zip for that release.

Related: #5175 #5176

**Comment by pameyer** [comment] 2018-10-12 15:18
Also worth pointing out that I can't reproduce this behavior on c95e53d805579b1f6718c7b8f49b6d4126db52ba (develop after 4.9.4) in case anyone's looking into it in more detail.

**Comment by pdurbin** [comment] 2022-10-09 16:17
I see this with the interactive installer too, even the new Python one from PR #6484. My expectation is that it'll just run, just do its thing, but at some point in the process I have to watch for the part where I hit a key to keep it moving when it asks for the Payara admin password. Not a huge deal but slightly annoying.

**Comment by cmbz** [comment] 2024-08-20 15:23
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Closed by cmbz** 2024-08-20 15:23 UTC
Labels: Type: Bug, Feature: Installer, User Role: Sysadmin
