### ISSUE TITLE
Access request date/time not visible, recoverable

### ISSUE THREAD

**Issue by tokeefe** [IQSS/dataverse#2261] opened 2015-06-15 13:59 UTC
I propose adding a timestamp column to the permissions editing panel to reveal when a user submitted a request to access a restricted file, or files. Alternatively, adding the user's name to the automated email would make this information recoverable.

**Comment by eaquigley** [comment] 2016-02-03 17:38
passing to qa to close as duplicate of #2855. (#2855 has more information)

**Closed** 2016-02-22 19:44 UTC
Labels: Status: Duplicate
