### ISSUE TITLE
File Upload - Allow files of the same name within different directories of a dataset

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6574] opened 2020-01-24 16:10 UTC
Within in a dataset, we currently add "-1" to any files uploaded that have the same name. We'll need to change this as we integrate with more reproducibility tools and other systems, where scripts, code, etc/ are expecting the names of files to not change. 

Needs some thought, and may make sense to discuss at the same time as #4813.

---

Status (by @pdurbin). When "fixed" is indicated, it means in the branch below.

- Bugs described below by @mheppler have been reproduced, specifically:
  - From the "edit metadata for files" page, you can give files the same name. Fixed.
  - If you delete some files while uploading, the counting is not reset so you'll get "-3" when it could have been "-2", for example.
- Bugs in the API have been found:
  - It was possible to give rename files to have the same name. Fixed.
  - It was possible to "move" files to directory with a file that has the same name, creating a duplicate. Fixed.
- API tests have been written:
  - uploadTwoFilesWithSameNameSameDirectory
  - uploadTwoFilesWithSameNameDifferentDirectories
  - renameFileToSameName
  - moveFileToDirectoryContainingSameFileName

`6574-filenames` is the branch where fixes are being pushed. Here's the "compare" view: https://github.com/IQSS/dataverse/compare/6574-filenames

**Comment by djbrooke** [comment] 2020-01-24 16:30
Updated the title based on a quick discussion with @jggautier.

**Comment by scolapasta** [comment] 2020-02-03 15:11
This should be straightforward in that our name checking should be based not just on the name solely but on the path + name. 

@djbrooke if path + name are the same, is it still appropriate to add the 1? (in any real upload, there can't be too files with the same name in the same directory)

**Comment by djbrooke** [comment] 2020-02-03 16:08
@scolapasta makes sense, thanks. Moving to Ready.

**Comment by djbrooke** [comment] 2020-02-05 19:55
- We should try this out to see the current behavior (this may be fixed?). Thanks @mheppler for volunteering
- We should keep in mind that we want to create empty directories in the future (link issue)
- In the previous implementation, we would append -1 in the file name of the upload widget, we just want to not do this for files in the same dataset directory 
- There may be ripple effects in other places (permissions page, search)

**Comment by mheppler** [comment] 2020-02-05 21:01
In an attempt to document the current state of affairs, I created a new draft dataset on demo, [_TEST ZIP UPLOADS_](https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.70122/FK2/YGR6WA&version=DRAFT), and updated the example [Code Ocean capsule](https://codeocean.com/capsule/0704207/tree/v2) which I exported as a ZIP. Here is what I've seen so far. I will test a little further and review with the team to make sure I am covering all our reproducibility use cases.

For the record, spoiler alert, I haven't seen any "-1" added to the file names yet.

_ZIP UPLOAD (two LICENSE files)_
- The following file is a duplicate of an already uploaded file:LICENSE(skipping)

_MANUAL UPLOAD (second/duplicate LICENSE file again)_
- (fails silently, file extension?)

_MANUAL UPLOAD (second/duplicate README.md)_
- The following file already exists in the dataset:README.md

_MANUAL UPLOAD (second/same name, different file README.md)_
- Success! (no "-1" added to file name)

MANUAL EDIT PATH (second/same name, different file README.md to **same "code" directory**)
- Success!

![Screen Shot 2020-02-05 at 3 53 52 PM](https://user-images.githubusercontent.com/687227/73882305-d0aec980-482f-11ea-850e-ce689033bfb8.png)

Here is one funny behavior that I thought I should document. I have three different README files, with three different names, README.md and README copy.md are duplicates and the system accepted "README copy.md" but not "README.md" presumably because that was the file it tried to load first, because that's what display first when sorting the files by name.

<img width="620" alt="Screen Shot 2020-02-05 at 3 59 02 PM" src="https://user-images.githubusercontent.com/687227/73882658-75310b80-4830-11ea-9295-66a6d7e4bc41.png">

![Screen Shot 2020-02-05 at 3 59 30 PM](https://user-images.githubusercontent.com/687227/73882697-8417be00-4830-11ea-892a-18f5223f5133.png)

**Comment by qqmyers** [comment] 2020-02-05 21:38
FWIW: An odd corner case - zip files can contain two files with the same path/dir. They won't if they are created from zipping up a file system, but one can use a zip library to do so (and having a source repository that allows duplicate names), so there is the potential to receive a zip that does this. (When I've unzipped one of these files, it does as Dataverse does and adds a -1 to the filename.)

**Comment by landreev** [comment] 2020-02-05 21:42
@mheppler Not sure what you did or how you tested, but the "-1" suffix does get added when I try it:
![Screen Shot 2020-02-05 at 4 40 56 PM](https://user-images.githubusercontent.com/737558/73885876-8aa93400-4836-11ea-8a10-20c7ae04250f.png)

**Comment by landreev** [comment] 2020-02-05 21:50
@mheppler - in your example above, it does look like the upload accepted 2 files - "README copy.md" and "README fake.md" with the md5s that are already in the dataset (you may be right about it having something to do with it only dropping the *first* checksum duplicate it finds - it may be buggy). 
But what happens when you try to click save? Does it allow you to then save these 2 files, or rejects them?

**Comment by mheppler** [comment] 2020-02-07 17:06
Here is what I found when lookign into the inconsistent behavior when upload two different README.md files, in two different directories, that have the same name.

_DRAG + DROP EACH FILE ... ADDS "-1"_
- README.md
- README-1.md

_DRAG + DROP ZIP ... NO CHANGE TO FILE NAME_
- folder2/README.md
- folder1/README.md

Then found a bug where deleting files during upload does not reset the duplicate file name counter.

_DRAG + DROP EACH FILE ... ADDS "-1" ... DELETE FILES + REPEAT UPLOAD_
- README-2
- README-3

Then I tried to replicate the use case from @qqmyers. With the use of a ZIP library I attempted to use a workaround that isn't the exact scenario but should be close. I created two different ZIPs of the same name, containing two different README.md, and the system again added "-1" as Jim reported.

_DRAG + DROP TWO ZIP WITH SAME PATHS ... ADDS "-1"_
- folder1/README.md
- folder1/README-1.md

I'll review these results with @scolapasta and @landreev, but I think the system is handling each of these uses as we'd expected.

**Comment by scolapasta** [comment] 2020-03-05 20:45
Code for checking filename should be centralized so that all use cases call it - whether through UI, native API, or Sword, and considering zip vs individual files.

**Comment by scolapasta** [comment] 2020-03-05 20:52
A couple of extra notes from the developers: 
• we need to make sure to consider both upload and edit
• should we also add a warning here that let's the user know we changed the name of the file since we found a file with the same name? @mheppler

**Comment by scolapasta** [comment] 2020-04-28 17:44
From discussion today to add some clarity:

When we are referring to unique name, we are specifically referring to the same "path/name" combination; users should be able to upload two files with the same file name in different directories.

The logic for the API and UI should be the same (and therefore the code to determine this test centralized, as mentioned in an above comment). If not path/name is not unique, we add a -1 (or -2, etc). 

In the UI the user will see the change before save. 

In the API, we accept the change (as it is easily reversible) but add the warning to the response (this same warning could be added to the UI to further highlight the change, if desired).

**Closed** 2020-05-07 16:45 UTC
Labels: Feature: File Upload & Handling, Medium
