### ISSUE TITLE
Track time when a File Access Request is made

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#3258] opened 2016-08-10 19:58 UTC
In discussions with @sbarbosadataverse  around the Manage Permissions issues, she asked that we track the time a file access request is made and display it on the Manage File Permissions page so that the admin responsible for granting permissions could see when an access request was made. (Currently we just track the user and file in the fileaccessrequests table).  Dream scenario - allow the admin to sort requests by time submitted - difficult because a given user may have submitted requests for access to multiple files.

**Comment by djbrooke** [comment] 2016-08-10 20:01
Thanks @sekmiller! I talked briefly with @sbarbosadataverse and we'll punt on this for now but may come back to it in a future release.

**Comment by mheppler** [comment] 2017-12-02 03:47
@sekmiller @djbrooke I believe this is a duplicate of **Permissions: Timestamp + user name in notifications/permissions pg for access requests #2855**.

**Closed** 2017-12-03 23:07 UTC
Labels: Feature: Request Access Workflow, Help Wanted: Code, Mentor: pdurbin, Status: UX & UI, Type: Feature, User Role: Curator
