### ISSUE TITLE
Handles: Need to cleanup up Harvard production handle data so can publish datasets with handles.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4046] opened 2017-08-04 21:24 UTC
In the course of investigating a user problem we discovered some lingering migration issues with handles.

For 2251 out of 11,000+ in the 1902.1 namespace there was no publicationdate and no globalidcreatetime. 
This will prevent them from being published.

**Comment by djbrooke** [comment] 2017-09-12 19:30
Closing as a duplicate of #3081, please reopen if I am wrong! :)

**Closed by djbrooke** 2017-09-12 19:30 UTC
Labels: Status: Backlog
