### ISSUE TITLE
Deaccession: Regression in Production

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2732] opened 2015-11-09 16:37 UTC
It appears deaccession is no longer appearing as an option for recently created datasets. @sbarbosadataverse checked the Murray datasets and deaccession is appearing for those which is what leads us to believe this is only for recently created datasets (perhaps since 4.2.1 was released).

**Comment by sbarbosadataverse** [comment] 2015-11-09 16:39
@eaquigley 
tested in demo and confirmed it's not showing up for the dataset I created there today

**Comment by scolapasta** [comment] 2015-11-09 17:30
It actually appears to be all datasets in production (and demo). Beta is on an older build and still has the deaccession button.

**Comment by landreev** [comment] 2015-11-09 17:34
I haven't looked into this myself (and not going to, unless you tell me to). 
But, it could also be a side effect of my 4.2.1 work. I did focus on speeding up the file-level lookups. But I did also at least touch the DatasetPage code that looks up and caches the dataset-level permissions. (The infrastructure that you put in place there originally). 
Hopefully it is just a matter of broken logic in the method that retrieves the Deaccession permission.

**Comment by pdurbin** [comment] 2015-11-09 17:40
At times like this it would be awfully nice to have an API call to deaccession datasets (#778) to compare against.

**Comment by landreev** [comment] 2015-11-09 18:05
True, having an API call would help, in general. But in this case it sounds so far like it's just a missing button, not broken functionality.

**Comment by landreev** [comment] 2015-11-09 18:36
OK, being ADD I could not stop myself from going in there and taking a look...
The rendering of the deaccession button appears to be one of the few places that I DIDN'T touch there...
But I have a guess as to what may be causing it:

The renderging logic for the button is 

DatasetPage.dataset.released and !empty(DatasetPage.releasedVersionTabList) and permissionsWrapper.canIssuePublishDatasetCommand(DatasetPage.dataset)

I remember one of the optimizations @sekmiller did was he changed the versions tab initialization, so that it would not happen on page init, but in real time, when the user activates the tab... 
That was actually great. It made the page load faster, and eliminated the "wrong file bug". 
But maybe that's why the rendering logic is now getting an empty DatasetPage.releasedVersionTabList?

**Comment by landreev** [comment] 2015-11-09 18:43
P.S. Also, I may be missing something, but - isn't this "!empty(DatasetPage.releasedVersionTabList)" redundant? I mean, if the dataset is released, doesn't that mean that it must have at least one released version? OK, maybe released, but since deaccessioned, also counts as "dataset.released"... then maybe
"DatasetPage.dataset.released AND !DatasetPage.dataset.deaccessioned" would do the job, without relying on this local list of released versions?

**Comment by landreev** [comment] 2015-11-09 18:48
P.P.S. No, 

"DatasetPage.dataset.released AND DatasetPage.workingVersion.released AND !DatasetPage.workingVersion.deaccessioned"

- or something like that... y'all figure it out. :)
my point is, should be possible/easy to render this without relying on that tab list.

**Comment by pdurbin** [comment] 2015-11-09 19:41
@sekmiller has a fix in mind so I'm giving this issue to him.

**Comment by sekmiller** [comment] 2015-11-09 21:06
Leonid was correct the button wasn't rendered because of the released versions list not being set at page init.  Now a boolean stands in for the list until the deaccession button is pressed at which time the list is created for the pop-up.  Also did a find on the versions just prior to calling the deaccession command to prevent the stale read error.

**Comment by sekmiller** [comment] 2015-11-09 21:06
Ready for testing pending a new build.

**Comment by kcondon** [comment] 2015-11-17 23:06
Button is back but edit button disappears when most recent version is deaccessioned. However, can edit files metadata and create a new draft. Passing back.

**Comment by sekmiller** [comment] 2015-11-18 14:05
Now the edit button is suppressed only if all versions have been deaccessioned.

**Comment by sekmiller** [comment] 2015-11-18 14:06
New build required for testing

**Comment by kcondon** [comment] 2015-11-18 20:08
OK, works, closing.

**Closed by kcondon** 2015-11-18 20:08 UTC
Labels: Priority: Critical, Status: QA, Type: Bug

**Comment by pdurbin** [comment] 2015-11-20 18:25
@bricas noticed this issue: http://irclog.iq.harvard.edu/dataverse/2015-11-20#i_27175

He's just testing in Vagrant for now.
