### ISSUE TITLE
Dataverse Guestbook:  Custom question output has inconsistent order

### ISSUE THREAD

**Issue by umuchlish** [IQSS/dataverse#4671] opened 2018-05-15 04:59 UTC
Hi @pdurbin, as per discussion during dinner at that old town Bandung to open a ticket.

I have found my Guestbook csv data has inconsistent order, especially for custom question.

![dataverseGuestbookDownload](https://user-images.githubusercontent.com/906898/40037159-e149c16e-5835-11e8-9e9c-3ca1afca4cde.JPG)

![dataverseguesbookouput](https://user-images.githubusercontent.com/906898/40037165-e8d93464-5835-11e8-9ecf-27e60fa8cfe2.JPG)

While visiting the code, not related above case or perhaps related a bit: https://github.com/IQSS/dataverse/blob/v4.8.6/src/main/java/edu/harvard/iq/dataverse/GuestbookResponseServiceBean.java#L147 

Please add quote (“) to each field and data to avoid the content being misplaced rather than do intervention to the data by replace ",". 

out.write("\"Guestbook\", \"Dataset\", \"Date\", \"Type\", \"File Name\", \"File Id\", \"User Name\", \"Email\", \"Institution\", \"Position\", \"Custom Questions\"\n".getBytes());

perhaps:
sb.append("\"");
sb.append(((String)result[1]));
sb.append("\"");
sb.append(SEPARATOR);

or better....

**Comment by mheppler** [comment] 2018-05-16 19:21
@kcondon commented on Nov 2, 2016 in issue *Guestbook: Guestbook csv download has issues if contents also includes commas, title, text q. #3449*
>Found by a user, see RT 243224, if a dataset's title contains a comma, loading the guestbook download csv into a spreadsheet requires manually removing the comma before it is properly imported. This would also happen if a question had commas or an answer had commas.
>
>One solution might be to scrub commas from content when writing this doc.

Closed that issue as a duplicate.

**Comment by pdurbin** [comment] 2018-05-21 15:37
As I mentioned in standup, I'm having trouble reproducing this issue. @sekmiller said he'd help me try (thanks!) but if @umuchlish or @kaitlinnewson or others have specific scenarios they'd like to have tested, please comment here. Thanks!

**Comment by pdurbin** [comment] 2018-05-21 15:48
Ok, I think I was obsessed with the commas but @sekmiller just pointed out that both the interface and the CSV but custom questions in an indeterminate order. For example, in the CSV I see a mix of "How's the weather?" and "Any trips planned?" in the same column:

<img width="473" alt="screen shot 2018-05-21 at 11 45 24 am" src="https://user-images.githubusercontent.com/21006/40316554-b24a0f20-5cec-11e8-8860-1aa423ec7687.png">

As @sekmiller pointed out, this mixture is also reflected in the GUI so we'll need to make sure it's fixed in both places:

![screen shot 2018-05-21 at 11 45 43 am](https://user-images.githubusercontent.com/21006/40316553-b23d6a9a-5cec-11e8-9f06-3cb0835f8814.png)

**Comment by pdurbin** [comment] 2018-05-21 17:15
I just made pull request #4700 and would love some code review so I moved this issue to that column in Waffle.

While I was in there I was struck by how downloading a guestbook is an operation you can only do from the GUI rather than the API so I added it to the list at #3440. If any users of Dataverse want this, please create a new issue for just downloading a guestbook via API because #3440 is a long list and we try to work in small chunks. Thanks.

**Closed** 2018-05-23 16:50 UTC
Labels: Feature: Guestbook, Status: QA
