### ISSUE TITLE
Searching for "digital" finds "digit"

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2484] opened 2015-08-28 18:43 UTC
Pointed out by someone on Twitter:

"try search "digital" and you find files labelled "digit". add phrase support."

In production, I searched for digital and narrowed down to files. Digital did show up in the description of some files (on page 66, I was logged in) but not in the name of the file as far as I could see in my quick look. The first page of results (and many after) had Digit in the title but not Digital. We should look at the relevancy for searches; would make sense that if the exact term showed up anywhere in the metadata of an object, it would be one of the first results displayed.

**Comment by pdurbin** [comment] 2015-09-04 20:34
Ah, this tweet: https://twitter.com/jonintweet/status/637223429175947264

Hmm. We worked a bit on search relevance in #1928 . Maybe the comment from @tercer at https://github.com/IQSS/dataverse/issues/1928#issuecomment-104471953 should be copied to this issue since that was for Beta 15 (but still open in QA).

**Comment by pdurbin** [comment] 2022-10-06 02:17
> "try search "digital" and you find files labelled "digit"

Easy to reproduce at https://dataverse.harvard.edu/dataverse/andrewleigh/?q=digital (running 5.11.1):

<img width="1365" alt="Screen Shot 2022-10-05 at 10 16 28 PM" src="https://user-images.githubusercontent.com/21006/194199310-5aaf96b0-582a-420c-9673-0e13ef8a7de3.png">

**Comment by qqmyers** [comment] 2022-10-06 12:26
FWIW - there is phrase support - searching for "digital code" only returns the first hit above. However, stemming is enabled so the various forms of words - digital/digit, code/codes are found, even in the phrase.

**Comment by pdurbin** [comment] 2022-10-06 15:53
Yes, stemming. Exactly. What we should probably do is first write some tests to make assertion about how our search works. Then try to fix this issue and hopefully not cause other problems. 😄 

If anyone wants to pick this up, here is where we keep the search tests: https://github.com/IQSS/dataverse/blob/v5.12/src/test/java/edu/harvard/iq/dataverse/api/SearchIT.java

**Comment by cmbz** [comment] 2024-08-20 15:26
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Closed by cmbz** 2024-08-20 15:26 UTC
Labels: Feature: Search/Browse, Type: Bug, Help Wanted: Code, Mentor: pdurbin, User Role: Guest
