### ISSUE TITLE
Metadata HTML Validation - Limit the valid HTML tags in metadata fields

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#239] opened 2014-07-09 15:36 UTC
---

Author Name: **Mike Heppler** (@mheppler)
Original Redmine Issue: 3653, https://redmine.hmdc.harvard.edu/issues/3653
Original Date: 2014-03-06
Original Assignee: Steve Kraffmiller

---

We should probably limit the HTML tags we allow in dataverse and dataset metadata fields to things like <p>, <b>, <i>, etc. and not <div>, <table>, etc. This is limit the damage to the UI that allowing any and all HTML tags in those fields can bring upon the page. I believe that OpenScholar does something like this.

---

Related issue(s): #454
Redmine related issue(s): [3869](https://redmine.hmdc.harvard.edu/issues/3869)

---

**Comment by scolapasta** [comment] 2015-01-23 22:35
Sending to QA as dupe of #1320

**Comment by kcondon** [comment] 2015-01-29 18:17
Closing as duplicate

**Closed by kcondon** 2015-01-29 18:17 UTC
Labels: Priority: Medium, Status: QA, Type: Feature
