### ISSUE TITLE
Export / Share Full DataCite XML to EZID

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2774] opened 2015-11-25 01:53 UTC
This will be important for our work with Helmsley to include fuller DataCite XML metadata when registering DOIs to EZID/DataCite.

**Comment by pdurbin** [comment] 2015-11-25 02:09
@posixeleni thanks for opening this issue. #907 is the parent ticket for exporting various formats such as DDI, JSON, etc. but it's great to have a focused issue about a subtask.

**Comment by bencomp** [comment] 2015-11-25 09:50
This may be a precondition for #24. 
Note that according to [the DataCite metadata schema v3.1](http://doi.org/10.5438/0010), if a related identifier is included (e.g. for publications that build on the dataset), a relation type must be given. That may require to have another look at the metadata model.

**Comment by posixeleni** [comment] 2015-11-30 14:07
Thanks @bencomp I created a separate new ticket to track the "Relation type" work that needs to be done. https://github.com/IQSS/dataverse/issues/2778

**Comment by posixeleni** [comment] 2015-12-01 15:05
@scolapasta @mcrosas since this relates to the Helmsley project can we assign this to a milestone to make sure it gets prioritized?

**Comment by mcrosas** [comment] 2015-12-01 20:58
@posixeleni we are not ready yet to assign issues to milestones since the focus now is in the patch performance releases. We will as soon 4.2.2 and 4.2.3 are completed.

Also this is not as high priority as I thought originally. Dataverse does submit already the required fields from DataCite schema to EZID, and those are searchable through DataCite new search. However, we could send additional metadata fields for better discoverability.

**Comment by pdurbin** [comment] 2017-07-04 18:01
Duplicate of #2917. Closing.

**Closed by pdurbin** 2017-07-04 18:01 UTC
Labels: Component: Metadata, Persona: Curator
