### ISSUE TITLE
Move Dataverse:  Allow super user to move a dataverse and reindex it and all child objects.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2278] opened 2015-06-17 20:02 UTC
I've recently received 2 separate requests to move dataverses through the DB. The moving part is easy -just change the owner id of the dv to be moved. To make it visible in the new location, you need to index the dv, then index all sub dv's and sub datasets individually. 

I know this was originally a feature but I'm asking for it as a super user tool that includes indexnig for now until the bigger picture is sorted out.

Luckily the most recent request only requires 2 dv's and 22 datasets to be indexed.

While we're at it, add in an index super user tool as well like in v3.6: just drop in a list of ids, it does the rest. I'll open a separate ticket.

Related to #2226

**Comment by pdurbin** [comment] 2015-06-17 20:13
Related: #283 and the "[Implications of moving dataverses and datasets](https://docs.google.com/document/d/1W8AXMtFJ32XCILCe1PX2BTIER6hxGiOLZMLhbFPQe7A/edit?usp=sharing)" doc.

**Comment by kcondon** [comment] 2015-08-12 23:54
I have moved countless datasets and dataverses manually through the db, including the gigantic PSI. There were 3 separate requests today alone! Stop the madness!

**Comment by mcrosas** [comment] 2015-08-13 02:05
:+1:

**Comment by pdurbin** [comment] 2016-01-15 18:54
> I have moved countless datasets and dataverses manually through the db

@kcondon can you please write down any guidelines based on your real-world experience of moving datasets and dataverses through the database? I know that in some cases reindexing is required but I'm also wondering about the concerns we had expressed in the doc I mentioned previously:

* metadata blocks may be different
* groups (defined at dataverse level) may not be available: https://github.com/IQSS/dataverse/issues/2412
* roles (including their permissions), will they carry over? some of them inherit from the parent dataverse so those will be impacted
* Solr re-indexing must happen

Basically, any case where inheritance comes into play should be considered. I'm not even sure if we have a complete list of this anywhere since **facet selections at the dataverse level** should probably be added to the list of concerns above.

@scolapasta this should probably be treated at a project/feature. Are we implementing this as an API call available to superusers only? That would be the easiest thing so there's no GUI to worry about.

There's a MoveDataverseCommandTest class that @michbarsinai added long ago that could/should be greatly expanded especially in light of his "The Testable Command" doc/implementation he's working on at https://github.com/IQSS/dataverse/blob/2746-testable-commands/doc/theTestableCommand/TheTestableCommand.md . As of this writing the tests only check that you can move a dataverse to a sibling but not a dataverse to its own child. And of course the MoveDataverseCommand itself doesn't work. It was never made real. And there's no MoveDatasetCommand at all (I suppose we could dedicate #2226 to this). This is what I mean when I say this is a project. I can't imagine this would be developed quickly.

Finally, the subject of this issue says "reindex it [the moved dataverse] and all child objects" but we don't support such a concept at all in indexing. It would be nice, of course, but this could be split out and developed separately.

**Comment by tlchristian** [comment] 2016-09-15 14:40
We are up to our elbows moving datasets to dataverses and dataverses to other dataverse in preparation of our migration.  Front-end functionality would be immensely helpful.

**Comment by pdurbin** [comment] 2016-09-15 15:44
@tlchristian Amber from Scholars Portal (not sure if she's on GitHub or I'd @mention her) brought this up on this week's community call: https://docs.google.com/document/d/1_IrtixbLPDPU7B73EhwJML9t_hfpqs3tdxRGXYb8e0k/edit?usp=sharing

**Comment by pdurbin** [comment] 2016-12-02 15:29
This issue was mentioned at https://help.hmdc.harvard.edu/Ticket/Display.html?id=244231 - "tinkering in any production database by hand isn't good for my blood pressure." 😄

**Comment by pdurbin** [comment] 2017-01-26 19:51
See also the "How to move dv's, ds" doc at https://docs.google.com/document/d/1A2v_ylLIRLIV6UpkDAJNNiFQt7q3SrAtAvQmg4nHBoY/edit?usp=sharing mentioned at https://groups.google.com/d/msg/dataverse-community/polE7z9_-NE/3xwAxgIHGgAJ

Here are the related issued:

- Moving Dataverses + Datasets: Provide way in the UI for a user to do this - https://github.com/IQSS/dataverse/issues/2073
- Move Dataset: Allow super user to move a dataset to another dataverse, one at a time. - https://github.com/IQSS/dataverse/issues/2226
- Move Dataverse: Allow super user to move a dataverse and reindex it and all child objects. - https://github.com/IQSS/dataverse/issues/2278

**Comment by djbrooke** [comment] 2018-01-16 15:42
Closing as a duplicate of #4406

**Closed by djbrooke** 2018-01-16 15:42 UTC
Labels: Feature: Dataverse General Info, Feature: Search/Browse, Feature: Superuser Dashboard, Help Wanted: Code, Mentor: pdurbin, Type: Suggestion, User Role: Superuser, User Role: Sysadmin
