### ISSUE TITLE
file downloading for large number of files: downloading problematic

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2871] opened 2016-01-14 16:09 UTC
Example dataset: https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/21919

User complaint:
1.When I try to download all the files at once, the app times out. 
2.When I try to download small batches (5-6 at a time) I often don’t get the files that I checked. 3.Downloading the files one at a time works but is very frustrating as it reloads the page every time and I have to scroll down and wait for the later file icons to load again.

**Comment by sbarbosadataverse** [comment] 2016-01-14 16:11
@eaquigley  
assigning to you so you can make sure it gets into the correct milestone.
We need to figure out this issue with "download all" that fails using API or simply via the UI. 

The second issues seems to be a bug---

**Comment by kcondon** [comment] 2016-01-15 16:48
I tested this after the user report. The dataset mentioned has a lot of small files, 50k or so. I was able to download 5-6 files with no trouble but when I downloaded a page worth of files, sometimes it worked, sometimes I got the server busy/ 503 error, which in this case seems like a timeout between apache and glassfish when processing the request. I say this because I can immediately browse the server and it does not seem slow at all and top does not report any significant load or resource problem.

I'll try to reproduce in the test environment and see whether there is any tuning of timeouts that may improve things. Please note that all the servers exhibited the issue but when downloading the same zip twice it seemed to work but then adding some files failed again, etc.

**Comment by kcondon** [comment] 2016-01-19 16:51
I've tested on staging and did not see the problem, even when selecting all. However, the zip process occurred much quicker, whereas in production, it was 40+ seconds, then the error. Seems likely a timeout. Why it's slower in production, available memory, etc, I don't know. Load didn't seem to be high.

**Comment by landreev** [comment] 2016-02-17 21:56
Yes, there is a very serious delay, on the API side, before any content is written; that must be triggering the timeout with the Apache proxy. (Works though, for this particular dataset, on the command line, with wget to localhost:8080). Once the download stars, it's done in less than a minute (there's 300MB in 274 files in this dataset total). 

The delay is caused *entirely* by the Authorization checks, that the API performs on each file before zipping anything. Kind of a shame, in this particular case especially - seeing how all the files are actually public. I'm looking into ways to optimize this (there are obvious ways, similarly to what we are doing inside the Dataset page/in the PermissionsWrapper - checking the permissions on the dataset only once, then caching it, etc.) Although ideally it would be nice to somehow not have to repeat all these checks at all - seeing how we have already checked all these permissions during their dataset page session). 

Obviously, this can also be worked around/fixed for most datasets via increasing whatever timeout Apache appears to be enforcing now... But it needs to be fixed in the Access API anyway. 

This does not explain the delay before the page even showed the guestbook dialog (reported by Gustavo earlier today). The page should have all the permission checks cached already. But I'll look at the code there as well.

**Comment by landreev** [comment] 2016-02-22 23:52
New code pushed into the branch 2871-batch-downloads-improvements. 
Will make a pull request shortly.

Testing: 

For the dataset specified in the original report above (hdl:1902.1/21919), this can be tested on dvn-vm5. 
Because I copied all the files from this dataset onto vm5. Downloads are not going to work for any other dataset, for which the files are not there. 

Before the new code is deployed, trying to download all files from the dataset: 

wget -O batch.zip http://localhost:8080/api/access/datafiles/2456470,2456530,2456307,2456503,2456565,2456527,2456322,2456511,2456315,2456346,2456385,2456526,2456554,2456531,2456550,2456313,2456562,2456423,2456363,2456422,2456305,2456378,2456434,2456368,2456320,2456466,2456327,2456351,2456350,2456495,2456433,2456398,2456390,2456474,2456481,2456502,2456403,2456292,2456552,2456449,2456472,2456469,2456399,2456551,2456559,2456393,2456330,2456324,2456332,2456336,2456365,2456558,2456416,2456396,2456353,2456352,2456310,2456369,2456339,2456334,2456380,2456463,2456406,2456389,2456494,2456293,2456538,2456345,2456321,2456454,2456295,2456354,2456362,2456364,2456482,2456483,2456485,2456480,2456342,2456341,2456340,2456337,2456361,2456358,2456356,2456370,2456366,2456372,2456367,2456382,2456400,2456402,2456395,2456411,2456405,2456424,2456456,2456458,2456457,2456491,2456504,2456501,2456497,2456496,2456498,2456490,2456514,2456507,2456508,2456509,2456515,2456516,2456520,2456517,2456564,2456567,2456479,2456475,2456381,2456436,2456410,2456568,2456420,2456549,2456357,2456318,2456408,2456435,2456513,2456439,2456448,2456555,2456302,2456418,2456304,2456344,2456314,2456541,2456373,2456444,2456442,2456561,2456306,2456371,2456394,2456414,2456360,2456460,2456384,2456499,2456413,2456468,2456471,2456467,2456488,2456486,2456489,2456493,2456308,2456512,2456506,2456521,2456522,2456487,2456375,2456391,2456427,2456426,2456392,2456447,2456544,2456386,2456355,2456566,2456412,2456429,2456560,2456316,2456492,2456407,2456478,2456343,2456451,2456519,2456500,2456303,2456319,2456326,2456419,2456431,2456432,2456440,2456459,2456477,2456535,2456533,2456528,2456534,2456543,2456542,2456539,2456540,2456547,2456553,2456548,2456557,2456437,2456536,2456349,2456374,2456545,2456299,2456524,2456525,2456532,2456428,2456421,2456446,2456445,2456484,2456298,2456297,2456296,2456301,2456300,2456312,2456317,2456323,2456325,2456328,2456329,2456333,2456335,2456331,2456338,2456441,2456505,2456438,2456510,2456404,2456383,2456452,2456453,2456379,2456464,2456409,2456294,2456461,2456425,2456401,2456311,2456387,2456397,2456415,2456376,2456523,2456537,2456529,2456417,2456518,2456546,2456455,2456359,2456473,2456388,2456462,2456476,2456465,2456556,2456309,2456450,2456377,2456563,2456443

- results in an almost 3 min. delay, before any content is downloaded. 

With the new code in place, you should see something downloading almost immediately.

**Comment by landreev** [comment] 2016-02-23 01:33
Oh, forgot to  put this into QA (please see my previous comment).

**Comment by landreev** [comment] 2016-02-23 18:40
OK, NOW the branch is ready for QA.

**Comment by kcondon** [comment] 2016-02-24 23:02
Yes, great performance improvement: download begins immediately versus 3min delay. Great job!
Closing.

**Closed by kcondon** 2016-02-24 23:02 UTC
Labels: Component: File Upload & Handling, Priority: Critical, Status: QA, Type: Bug
