### ISSUE TITLE
 edu.harvard.iq.dataverse.api.FilesIT.testForceReplaceAndUpdate Test Failing

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6846] opened 2020-04-21 18:52 UTC
Expected status code <200> doesn't match actual status code <500>.

See build 425 on dataverse.org Jenkins for more info.

**Comment by pdurbin** [comment] 2020-04-22 21:00
At first I could reproduce the `FilesIT.testForceReplaceAndUpdate` failure locally but the error went away after I doubled the following 

```
-XX:MaxMetaspaceSize=512m
-XX:MetaspaceSize=256m
```

(I did this because I'm getting this `java.lang.OutOfMemoryError: Metaspace` in my logs when running even a single API test.)

Now I can't reproduce the original errors but when I run the whole API test suite (which I couldn't do with Glassfish 4.1 without it falling over) I get a seemingly random assortment of failing tests, just like we're seeing on Jenkins.

When I look at my logs, I see many cases of `org.postgresql.util.PSQLException: ERROR: deadlock detected` which we discussed but never fixed in #2460. I think these deadlocks should be discussed in tech hours.

I'm not sure what to do with this issue.

**Comment by djbrooke** [comment] 2020-04-22 21:39
Thanks @pdurbin for the details.

@scolapasta can you get automated testing on the docket for a future tech hours? We've been picking off the some failing tests one by one, but I saw on some recent runs that 4 new ones were failing so I'm not sure if we should re-evaluate. Generally I'm happy to spend sprint time in the automated test area. :)

**Comment by poikilotherm** [comment] 2020-04-23 11:25
About the MetaspaceSize and MaxMetaspaceSize: I stumbeld over https://dzone.com/articles/permgen-and-metaspace and my attention was catched here:

> Whenever there is a need to resize PermGen/Metaspace, JVM will do it as it does with the standard heap. Resizing those spaces requires a full GC, which is always an expensive operation. It can usually be observed during a startup when a lot of classes are being loaded. Especially if the application has dependencies on many external libraries. If there are a lot of full GCs during the startup, it’s usually because of that. If that case, increasing the initial size can boost the startup performance.

Has anyone taken a look at this during startup? During playing a bit with container memory limits, I noticed a few times rising and sudden drops in memory use. I wonder if this related to GC and if the metaspace is related to our very long deploy times, next to our massive amount of beans we are loading...

**Comment by donsizemore** [comment] 2020-04-23 11:37
@poikilotherm I sent the Metaspace settings along with https://blog.payara.fish/fine-tuning-payara-server-5-in-production to roll in as part of the switch to Payara 5: https://github.com/IQSS/dataverse/blob/68bb65630bc3ca1c1d4c1fbc55b99a2102c83fc6/scripts/installer/as-setup.sh#L67 

In tinkering with Prometheus I did see a series of fairly steep memory reclamation during garbage collection; I can try again with some test Metaspace settings during deployment.

**Comment by djbrooke** [comment] 2020-05-20 18:23
- We expect that this class of error is related to DB deadlocking (#6865). If this is the case, we can close this issue.

**Comment by pdurbin** [comment] 2020-07-28 20:54
@djbrooke @scolapasta now that #6865 is closed (🎉 ) should we close this issue as well?

**Comment by scolapasta** [comment] 2020-07-28 20:56
I am not sure if this was caused by deadlocks, but more importantly the past two jenkins builds (I'm not including the one that couldn't connect) passed. So unless we see this occur again, yes we can close.

**Comment by djbrooke** [comment] 2020-07-28 20:56
@pdurbin Sure, we can reopen if we start to see consistent failures from this test !

**Comment by djbrooke** [comment] 2020-07-28 20:57
@scolapasta 👍

**Comment by scolapasta** [comment] 2020-07-28 20:57
@djbrooke beat me to it, while I was typing my comment! (but I got the comment in first at least :))

**Comment by pdurbin** [comment] 2022-03-15 20:05
Another case of testForceReplaceAndUpdate failing at https://jenkins.dataverse.org/blue/organizations/jenkins/IQSS-Dataverse-Develop-PR/detail/PR-8486/2/tests for PR #8486.

**Comment by pdurbin** [comment] 2022-05-05 14:54
testForceReplaceAndUpdate just failed at https://jenkins.dataverse.org/blue/organizations/jenkins/IQSS-Dataverse-Develop-PR/detail/PR-8624/4/tests for #8624.

That's it. Time to reopen this issue. 😄

**Comment by donsizemore** [comment] 2022-05-23 21:42
testForceReplaceAndUpdate failure seen again at https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/view/change-requests/job/PR-8689/1/consoleFull

The Payara log doesn't seem particularly helpful, sorry.

**Comment by pdurbin** [comment] 2022-05-24 15:46
https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/view/change-requests/job/PR-8689/1/testReport/edu.harvard.iq.dataverse.api/FilesIT/testForceReplaceAndUpdate/ is showing a 500 error on FilesIT.testForceReplaceAndUpdate(FilesIT.java:668)

That's this line:

https://github.com/IQSS/dataverse/blob/8ec50c8168986da036da66b46071e0dc2b3ec76b/src/test/java/edu/harvard/iq/dataverse/api/FilesIT.java#L668

From [server.log.txt](https://github.com/IQSS/dataverse/files/8764232/server.log.txt) we see that the metadata of the file couldn't be edited due to a dataset lock:

[#|2022-05-11T13:30:47.039+0000|WARNING|Payara 5.2021.6|edu.harvard.iq.dataverse.api.Files|_ThreadID=69;_ThreadName=http-thread-pool::http-listener-1(2);_TimeMillis=1652275847039;_LevelValue=900;|
  Dataset publication finalization: exception while exporting:{0}
edu.harvard.iq.dataverse.api.AbstractApiBean$WrappedResponse: edu.harvard.iq.dataverse.engine.command.exception.IllegalCommandException: Dataset cannot be edited due to dataset lock.
	at edu.harvard.iq.dataverse.api.AbstractApiBean.execCommand(AbstractApiBean.java:633)
	at edu.harvard.iq.dataverse.api.Files.updateFileMetadata(Files.java:423)


So, I think we just need to add our normal `UtilIT.sleepForLock` in the test code just before the failing line.

**Comment by mreekie** [comment] 2022-05-25 18:44
sprint
 - sized small
 -

**Comment by mreekie** [comment] 2022-06-08 17:55
Sprint:
- pm.sprint.2022_05_25 ended OnDeck
-

**Comment by pdurbin** [comment] 2022-07-22 21:11
Another case: https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/view/change-requests/job/PR-8792/2/testReport/edu.harvard.iq.dataverse.api/FilesIT/testForceReplaceAndUpdate/

**Closed** 2022-07-27 19:45 UTC
Labels: sz.Small, pm.sprint.2022_05_25, pm.sprint.2022_06_08
