### ISSUE TITLE
My Data: Spinner Continues after moving to different tab

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2335] opened 2015-07-09 20:56 UTC
Discovered during usability testing:

When a user clicks on a checkbox in the my data then goes to a different tab, the spinner continues to run. This shouldn't happen.

**Comment by raprasad** [comment] 2015-07-22 15:24
Recheck with latest code.  I'm not sure if this is still happening--the spinner also activates when switching tabs.

**Comment by kcondon** [comment] 2015-07-22 18:48
I was not able to reproduce this, closing.

**Closed by kcondon** 2015-07-22 18:48 UTC
Labels: Component: UX & Upgrade, Priority: High, Status: QA, Type: Bug
