### ISSUE TITLE
MyData - streamline retrieval of role labels

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2411] opened 2015-07-24 20:20 UTC
Currently 70 to 200+ queries.  Can be done in 2 queries--or max. 30--up to 3 per card

- [RoleTagRetriever.java](https://github.com/IQSS/dataverse/blob/4.2/src/main/java/edu/harvard/iq/dataverse/mydata/RoleTagRetriever.java) class reduces queries to 2 or 3 total

**Comment by raprasad** [comment] 2015-08-03 20:06
@kcondon, Now 'all' roles should show, even if assigned at a higher level.

**Comment by raprasad** [comment] 2015-08-07 13:55
@scolapasta - I moved this to "4.2" since the code is already checked in.

**Comment by kcondon** [comment] 2015-09-03 15:27
OK, regression tested role tags and seems to be working, closing.

**Closed by kcondon** 2015-09-03 15:27 UTC
Labels: Component: Code Infrastructure, Priority: High, Status: QA, Type: Suggestion
