### ISSUE TITLE
Edit Dataset: Some page actions clear some fields values unexpectedly, eg. validation error, add field instance.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#5282] opened 2018-11-06 19:35 UTC
When doing significant dataset metadata testing and data input, ran into some annoying form behavior that cleared some fields.

1. If any required fields were missing, when field validation error was thrown, some fields, eg. description, subject, were cleared.
2. Some adjacent compound fields had their values cleared when another compound field instance was added: geospatial coverage, contributor/grant information.

The fields that are cleared were added in the same edit session and had not been saved yet.

Steps to reproduce:
1.
Enter a contributor, enter a second contributor, enter a grant agency, select + to add another grant agency, the 2nd contirbutor is cleared.

2. Enter basic info for dataset, except title. Save, see validation error, see description and subject values are cleared. If not able to reproduce, add multiple description fields and subjects, repeat validation error.

**Comment by pdante-ubc** [comment] 2019-06-07 21:55
I'm seeing the same issue. My guess is that the whole page gets reloaded when the + is pressed in order to add the new fields to the visual display, so unsaved fields get cleared. Seems to possibly be connected to the same issue that I noted in https://github.com/IQSS/dataverse/issues/5929

**Comment by mheppler** [comment] 2019-06-21 18:17
@kcondon it appears this issue was a duplicate of #5477, which was fixed and merge in 4.11. I am going to close this issue. The recently opened #5929 also reports this issue in v. 4.10.1, and I have commented there as well reporting the fix.

**Closed by mheppler** 2019-06-21 18:17 UTC
Labels: Feature: Metadata, Type: Bug

**Comment by kcondon** [comment] 2019-06-21 21:40
@mheppler  Confirmed.
