### ISSUE TITLE
Verify that API sets license on create dataset

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1991] opened 2015-04-13 15:36 UTC

**Comment by pdurbin** [comment] 2015-07-17 17:24
Testing as of 306bf7f (4.0.2 branch, pre 4.1 release).

## SWORD (nothing specified)

If you don't specify anything in the XML...

```
<?xml version="1.0"?>
<entry xmlns="http://www.w3.org/2005/Atom" xmlns:dcterms="http://purl.org/dc/terms/">
   <dcterms:title>SWORD: nothing specified</dcterms:title>
   <dcterms:creator>Saber, Sierra</dcterms:creator>
   <dcterms:description>Why specify anything?</dcterms:description>
</entry>
````

... SWORD will create a dataset with a licens of "CC0":

`$ curl -s http://localhost:8080/api/datasets/2672183?key=$API_TOKEN | jq '.data.latestVersion.metadataBlocks.citation.fields[] | select(.typeName=="title").value '
"SWORD: nothing specified"`

```
dataverse_db=# select dataset_id,license from datasetversion where dataset_id=2672183;
 dataset_id | license 
------------+---------
    2672183 | CC0
(1 row)
```

## SWORD (dcterms:rights but no dcterms:license)

A dataset created via SWORD with no explicit license specified in the XML file but with dcterms:rights ( such as the "Spruce Goose" dataset at https://github.com/IQSS/dataverse/blob/306bf7ff9fb22c7fd94a4c412198deec22eb1660/scripts/search/tests/data/dataset-trees1.xml ) has license set to "NONE". This is by design per #805 and documented:

> “License” can now be set with dcterms:license and the possible values are “CC0” and “NONE”. “License” interacts with “Terms of Use” (dcterms:rights) in that if you include dcterms:rights in the XML, the license will be set to “NONE”. If you don’t include dcterms:rights, the license will default to “CC0”. It is invalid to specify “CC0” as a license and also include dcterms:rights; an error will be returned. For backwards compatibility, dcterms:rights is allowed to be blank (i.e. <dcterms:rights></dcterms:rights>) but blank values will not be persisted to the database and the license will be set to “NONE”. -- http://guides.dataverse.org/en/4.0.1/api/sword.html

`$ curl -s http://localhost:8080/api/datasets/2672172?key=$API_TOKEN | jq '.data.latestVersion.metadataBlocks.citation.fields[] | select(.typeName=="title").value '
"Spruce Goose"`

```
dataverse_db=# select dataset_id,license from datasetversion where dataset_id=2672172;
 dataset_id | license 
------------+---------
    2672172 | NONE
(1 row)
```

## Native API (nothing specified)

First of all, I don't think you **can** specify a license via the native API. As far as I know, a license can only be specified via SWORD (the rules are somewhat complex, per above) or via the GUI.

If you use https://github.com/IQSS/dataverse/blob/306bf7ff9fb22c7fd94a4c412198deec22eb1660/scripts/search/tests/data/dataset-finch1.json to create a dataset via the native API the license is null in the database:

`$ curl -s http://localhost:8080/api/datasets/2672173?key=$API_TOKEN | jq '.data.latestVersion.metadataBlocks.citation.fields[] | select(.typeName=="title").value '
"Darwin's Finches"`

```
dataverse_db=# select dataset_id,license from datasetversion where dataset_id=2672173;
 dataset_id | license 
------------+---------
    2672173 | 
(1 row)
```

**Comment by pdurbin** [comment] 2015-12-03 21:37
Related: license and terms of access information not appearing in json #2794

**Comment by pdurbin** [comment] 2016-05-23 18:34
@bmckinney and I discussed this and decided that his pull request at #3082 seem to be a fix so I listed it under "related issues" in that pull request and am sending this issue to QA.

**Comment by kcondon** [comment] 2016-07-19 14:07
Leaving in QA but removing my name until I receive pull request.

**Comment by kcondon** [comment] 2016-07-27 15:50
Reassign it to the person and say it needs CR before QA as was agreed upon by the team, move it back into the development column

**Comment by pdurbin** [comment] 2016-07-27 16:00
This issue needs more than code review. As I mentioned at https://github.com/IQSS/dataverse/pull/3082#issuecomment-234373747 pull request #3082 has merge conflicts. Since that pull request was made by @bmckinney I'll assign this to him. But! In that pull request @sekmiller has said he has applied a similar fix to the https://github.com/IQSS/dataverse/tree/4.5-export-harvest branch. Does @sekmiller want me to repeat the test above in the 4.5-export-harvest branch? I'm not sure if @bmckinney and @sekmiller have communicated yet so I'll assign this issue to both of them.

**Comment by djbrooke** [comment] 2016-09-02 16:39
May we retest this now that 4.5 is out?

**Comment by pdurbin** [comment] 2016-09-02 17:01
It looks like the licensing handling was changed at c785d50 for 4.5. Yes, we should retest this issue.

**Comment by pdurbin** [comment] 2016-09-02 17:25
I just moved this card to the QA column in https://waffle.io/IQSS/dataverse since the behavior changed in 4.5. From a quick test it looks like when you create a dataset via native API the license is now persisted as "NONE" rather than a null value. I didn't try specifying CC0 but is should persist that value. "NONE" seems to be the default basically, which is different than what the GUI does.

**Comment by kcondon** [comment] 2016-09-09 19:47
Discussed with Gustavo, he needs to confirm with Merce what the expected default behavior should be so assigning to him at his suggestion.

To summarize the status of this winding path of an issue:
Creating a dataset in UI and through APIs (Sword, native) have default Licensing and they differ. UI defaults to CC0, Sword defaults to CC0, Native defaults to NONE per Phil's testing. Should Native default to CC0? A side issue is how to specify licensing using native API since it is not documented. The original issue was native API  was not setting licensing and so resulted in a null value. That has been corrected.

**Closed** 2016-09-14 21:18 UTC
Labels: Component: API

**Comment by kcondon** [comment] 2016-09-14 21:20
per Gustavo/Danny, this endpoint may need additional work but for this issue it is incrementally better so closing this.

**Comment by scolapasta** [comment] 2016-09-14 21:29
New issue opened as #3357
