### ISSUE TITLE
Dataset Tabular File Ingest - Displaying both "success" and "ingest in process" message is confusing/wrong

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2709] opened 2015-10-29 18:27 UTC
There should maybe be no "success" message until the files completes ingest

**Comment by pdurbin** [comment] 2017-06-25 18:17
@oscardssmith have you noticed this while working on #3767?

**Comment by mheppler** [comment] 2018-04-02 19:17
Closed the issue **Tabular File Ingest: No message indicating page will refresh on its own, or if user needs to manually refresh #1798** as a duplicate of this issue.

Recently saw this issue in my localhost `develop` branch, build d317d23d1bc31ca2d8cc3a0f2c32ab6ad2431112, and agree that is confusing and should be clearer in the UI what the process will be for the end user.

![screen shot 2018-04-02 at 2 51 23 pm](https://user-images.githubusercontent.com/687227/38210997-0d520f8a-3687-11e8-8cc2-c6c17bbc3c90.png)

The "Ingest in progess..." message will automatically be removed from the page, but the disabled state for the Publish, Edit and Upload buttons remains. In addition to the buttons, there is other functionality on the page that is broken when the page doesn't refresh properly, including the Explore button being added to the file table row, as well as the "Upload Completed with Errors" hover popover linked to the warning icon not working, as reported in issue #3491.

Recently, we have developed "workflows" for publish, that use the [warning message block to inform the user about the dataset lock status](https://github.com/IQSS/dataverse/issues/3561#issuecomment-283779898). We should apply similar messaging to the file ingest workflow, explaining why those buttons are disable and for how long. We should also fix the page refresh to properly update _everything_ on the page.

**Comment by djbrooke** [comment] 2019-04-10 18:24
- Improve messaging on the page (top of page and on ingesting files, possible lock messaging). The files are there and available for download, but the ingest process is not yet complete. Expectations setting is important.
- Verify that the auto-page refresh is working as expected (work with @sbarbosadataverse on this one).

**Comment by TaniaSchlatter** [comment] 2019-04-22 17:08
Issues #3491 and #3794 are also page-refresh related, and might be able to be addressed with this issue.

**Comment by pdurbin** [comment] 2019-04-25 21:28
At sprint planning the other week I mentioned this tweet about waiting for ingest to complete: https://twitter.com/b_schaffner/status/1108158686265044993

<img width="606" alt="Screen Shot 2019-04-25 at 5 19 59 PM" src="https://user-images.githubusercontent.com/21006/56769228-8ec00580-677e-11e9-9c0a-30e888432828.png">

The animated version is even better:

![tenor](https://user-images.githubusercontent.com/21006/56769377-068e3000-677f-11e9-918e-777c9e3dc313.gif)

But the good news is that ingest succeeded! Then he tweeted this: https://twitter.com/b_schaffner/status/1108173691224031234

<img width="597" alt="Screen Shot 2019-04-25 at 5 26 28 PM" src="https://user-images.githubusercontent.com/21006/56769492-5836ba80-677f-11e9-9280-bff58597d9ac.png">

**Comment by mheppler** [comment] 2019-04-29 19:29
Confirmed... no action needed...
- In my localhost I was able to see the "Ingest in progess..." msg and disabled buttons all refresh as expected, issue #1798 reported this required manual refresh of the page, but I didn't have to, that issue was closed as a dup already, nothing we need to do here...
- Was also able to confirm that the Explore btn displayed properly when the "Upload Completed with Errors" warning icon displayed, I think this means we can close #3491...
- I have not seen the UI issues reported in #3794 in a long time and I suggest we close that issue as well...

Ingest in progress... to-do list...
- Utilize dataset lock workflow to display warning msg (see screenshot) with new msg text
- Create new ingest success msg text and display that when ingest completes (see screenshot)
- Fix the "Upload Completed with Errors" popover still displays when you hover over the warning icon after you have selected that file and the table refreshes, and breaks the jquery binding to trigger popover

![file-ingest-lock](https://user-images.githubusercontent.com/687227/56921359-9855b000-6a93-11e9-9b18-2e9a4743cbdd.png)

![file-ingest-success](https://user-images.githubusercontent.com/687227/56921366-9b50a080-6a93-11e9-95a4-104b6d76056f.png)

**Comment by kcondon** [comment] 2019-05-07 11:37
@mheppler Issues found:
-The explore button still needs a manual refresh to appear, at least when a configure button is also configured. Will retest without it.

**Comment by sekmiller** [comment] 2019-05-07 15:59
The fix I put in to display the explore button when ingest completes wipes out the success message (you see it for a moment and then it goes away.) This is because the explore button is rendered based on the fileDownloadhelper which is injected into the DatasetPage bean. In order to refresh the "helper" you have to reload the whole page. I'll see if there's a tricky way to repost the success message after reloading the page.

**Comment by sekmiller** [comment] 2019-05-07 20:54
I fixed the ingest success message so that it will appear after the page reloads any explore buttons.

I haven't seen an empty locked message. Are there any tricky steps needed to recreate?

**Comment by mheppler** [comment] 2019-05-07 20:59
@sekmiller -- that could be due to a local dev setup error on my part, by not copying over the new bundle in this branch over to my local properties files directory that I configured for internationalization.

**Closed** 2019-05-08 19:37 UTC
Labels: Feature: File Upload & Handling, Status: QA
