### ISSUE TITLE
Server error when accessing notifications

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2168] opened 2015-05-14 16:43 UTC
Internal Server Error - An unexpected error was encountered, no more information is available.

I have a movie file of the steps to reproduce,  but can't attach that to github-not supported.

**Comment by sbarbosadataverse** [comment] 2015-05-14 17:57
![error](https://cloud.githubusercontent.com/assets/8322346/7638207/2a1087a8-fa41-11e4-9ebd-2ec6bddaafbd.gif)

**Comment by scolapasta** [comment] 2015-09-17 18:42
Reviewed with @eaquigley and could not reproduce.

**Comment by kcondon** [comment] 2016-01-16 12:13
Many of these notifications issues were resolved. Not able to reproduce, closing.

**Closed by kcondon** 2016-01-16 12:13 UTC
Labels: Component: UX & Upgrade, Priority: High, Status: QA, Type: Bug
