### ISSUE TITLE
Dataset File Upload -- Missing Dataset Title Context at Top

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1341] opened 2015-01-14 19:05 UTC
When you click into the Upload + Edit File workflow from an existing dataset, there are no breadcrumbs or other indicators of which dataset you are working on.

**Comment by scolapasta** [comment] 2015-01-23 18:06
@mheppler talk to me before working on this one, as I will also be working on general breadcrumb cleanup

**Comment by mheppler** [comment] 2015-02-09 14:39
Could not get the breadcrumbs to display on the dataset page, in Upload + Edit Files view.

Notes:
- dataset.xhtml still has the ui:param showBreadcrumbs
- dv_rebind_bootstrap_ui.js has a function hide_breadcrumb, which hides the breadcrumbs section with jQuery + CSS, that gets called by post_edit_files, which gets called when either Upload + Edit Files, commenting out that call does not show the breadcrumb, that function should probably be removed and the hide/show functionality of the breadcrumb should all exist in one place, in the backend (there is a lot happening on that javascript file that probably doesn't belong there)

**Comment by scolapasta** [comment] 2015-02-20 19:18
@mheppler you readded the breadcrumbs to this page and they are there on view, not edit. I think the issue is now that javascript you refer to. Call you relook at that?

**Comment by mheppler** [comment] 2015-02-24 16:16
Removed javascript from dv_rebind_bootstrap_ui, that was in relation to the hiding and showin of the breadcrumbs. Also commented out javascript that was used for info text, which will be moved to the backing beans.

**Comment by posixeleni** [comment] 2015-03-26 19:50
Can now see breadcrumbs when editing and uploading files for a dataset after Create:

![image](https://cloud.githubusercontent.com/assets/5013837/6855539/a3e473fc-d3cf-11e4-90ec-7ac84026c89e.png)

Closing this ticket.

**Closed by posixeleni** 2015-03-26 19:50 UTC
Labels: Component: UX & Upgrade, Status: QA, Type: Bug
