### ISSUE TITLE
Files permission page: success message when assigning permissions by files, should list all files assigned, not just one file

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2910] opened 2016-02-03 21:42 UTC
Can't include complete screen shot due to user name, but when assigning permissions using the bottom files dialogue box on permissions page, you have the choice to select all files, and when you do and assign permission, success message only lists the "first" file in the dialogue box, and not all files successfully assigned and listed

<img width="390" alt="screen shot 2016-02-03 at 4 39 29 pm" src="https://cloud.githubusercontent.com/assets/8322346/12798018/2449c634-ca95-11e5-9806-50a377b9ea07.png">

**Comment by pdurbin** [comment] 2016-02-04 01:53
https://github.com/IQSS/dataverse/issues/2464#issuecomment-179409362 is a writeup of another bug where there's a difference between how the first file is treated compared to subsequent files but I sort of doubt these issue are related and this comment I'm making may well just be noise. :)

**Comment by mheppler** [comment] 2016-02-04 15:20
Sonia, is this a duplicate of #2840 "File Permissions: Grant Access success msg only lists file name for one of multiple"? If not, could you clarify the issue in more detail. Thanks.

**Closed** 2016-02-09 18:31 UTC
Labels: Component: Permissions, Priority: High, Status: Duplicate, Type: Bug
