### ISSUE TITLE
Fix URL field alignment under "Related Publications" on Create Dataset page

### ISSUE THREAD

**Issue by dlmurphy** [IQSS/dataverse#3871] opened 2017-05-31 16:58 UTC
In #3838 we added a set of "Related Publications" fields to the Create Dataset page. Here's a screenshot:

![related_publications_screenshot](https://cloud.githubusercontent.com/assets/22962740/26643483/78c08694-45ff-11e7-9a6b-acf61d374b5d.png)

In that issue, @TaniaSchlatter pointed out that the **URL** field under Related Publications is right-aligned, which is inconsistent with the placement of the **Vocabulary URL** field higher on the page. She and I recommend aligning the **URL** field to the left to match the **Vocabulary URL** field's alignment.

(Note: Made a new issue for this instead of dropping it into the other issue because that issue was already closed)

**Comment by mheppler** [comment] 2017-05-31 21:32
I don't see this problem when trying to replicate it locally in Firefox. The screenshot above was originally posted by @landreev is from his localhost during development. My localhost is built from the latest from the develop branch.

@kcondon has built the latest from the develop branch on dvn-build. I looked to see if it was there, but the Related Publication field hasn't been configured to be displayed as Leonid outlined out in [his comment](https://github.com/IQSS/dataverse/issues/3838#issuecomment-302740264) in the original issue.

**Comment by dlmurphy** [comment] 2017-05-31 21:37
Interesting... You're definitely looking at the Create Dataset page here, right? If this problem is actually already fixed then that's fantastic.

**Comment by pdurbin** [comment] 2017-06-23 10:53
I can't reproduce this bug either. I'm on a461340. Here's a screenshot. Closing.

![screenshot from 2017-06-23 06-49-51](https://user-images.githubusercontent.com/21006/27479150-a733fb08-57e0-11e7-8fcd-8d495f637acb.png)

**Closed by pdurbin** 2017-06-23 10:53 UTC
Labels: Component: UX & UI

**Comment by jggautier** [comment] 2017-06-23 13:36
I've always wondered if this was related to the bug I wrote about in #3685, where compound fields in the citation metadata block were out of order and the bug couldn't be reproduced. Just noting that issue here in case this happens again.
