### ISSUE TITLE
delayed "draft" creation and display: when you create a new version, DRAFT version is delayed under "versions tab."

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2434] opened 2015-08-05 21:22 UTC
User reported this issue yesterday as well and I was able to replicate today:

created a new dataset version, his save twice to get out of edit screen (first time see processing blue spinner but save never resolves from "Edit" page). 

Page display shows successful metadata changes associated with new version, but citation shows "published" V#, and there is no option to "publish."

Hit "version tab" and no DRAFT version available. About 20 -30 seconds later, hit version tab again, and DRAFT finally shows up.

**Comment by pdurbin** [comment] 2016-01-15 18:37
@sbarbosadataverse this "save twice" issue sounds suspiciously like #2436 which we just agreed to close per https://github.com/IQSS/dataverse/issues/2436#issuecomment-172036797 where you had said "I think this was one of those bugs that we won't be able to reproduce....we have many of these...I think we can close it and say we will open again if it happens again...I haven't seen it since i reported the ticket"

That is to say I'm closing this one as well but please reopen it if I'm mischaracterizing this as one of the many issues we can't reproduce or if you have any more information.

**Closed by pdurbin** 2016-01-15 18:37 UTC
Labels: Priority: High, Type: Bug
