### ISSUE TITLE
Not able to save "roles" on the dataset level

### ISSUE THREAD

**Issue by suenjedt** [IQSS/dataverse#2048] opened 2015-04-20 16:12 UTC
During the training we could not save the role we created on the dataset level. It worked on the DataVerse level though. Note: we worked on the demo site.

**Comment by kcondon** [comment] 2015-06-04 21:27
Was not able to reproduce/ works fine, closing.

**Comment by kcondon** [comment] 2015-06-04 21:28
@suenjedt Can you reproduce this? If not, marked as closed.

**Closed by kcondon** 2015-06-04 21:27 UTC
Labels: Component: High-level, Priority: Medium, Status: QA, Type: Bug
