### ISSUE TITLE
Make validation messages bundled

### ISSUE THREAD

**Issue by bsilverstein** [IQSS/dataverse#3980] opened 2017-07-05 20:48 UTC
For most of the application's messages / text / etc. we utilize `Bundle.properties` to centralize the words that appear on each webpage and make it easier to translate into other languages going forward. 

Dataverse currently utilizes bean validation in many places and files. For custom validation tags within the code (supporting various webpages), there are messages which the user can see defined _in the code_ within the line for a tag. 

Example: 

`@Pattern(regexp = "[a-zA-Z0-9\\_\\-]+", message = "Alias cannot be empty. Valid characters are a-Z, 0-9, '_', and '-'.")`

This particular line above currently exists in `DataverseRole.java` at line 100 as a prefix for the alias string. Beyond just `@Pattern(. . . , message = "___")` there are other tags across other back end files using concretely English strings as error messages. 

While it's not a show stopper, it's something to consider in the way of internationalization across the app. It's much slower to do a find-and-replace for each message across so many Java files when trying to translate into other languages. 

On another issue and in another file's `@Pattern` tag, I tried replacing the message's string using the `BundleUtil.getStringFromBundle()` but for whatever reason the tag doesn't play nice with `Bundle.properties` and so I left it as is. There doesn't seem to be a ton of info out there on how to customize these messages, but it looks possible to do.

Related webpages that may be helpful:

http://docs.oracle.com/javaee/6/tutorial/doc/gkahi.html
https://stackoverflow.com/questions/6593845/jsf2-bean-validation-with-custom-message-bundle

**Comment by bsilverstein95** [comment] 2017-07-07 13:55
Thanks to @scolapasta for this example screenshot from the OpenScholar Dataverse site in French:

![sp_validation](https://user-images.githubusercontent.com/16244907/27960752-6aaf541e-62fa-11e7-852d-52231ec16fb8.jpg)

**Comment by djbrooke** [comment] 2018-05-22 13:54
@scolapasta @JayanthyChengan - is this a duplicate of (or very similar to) one of the current internationalization issues in progress?

**Comment by JayanthyChengan** [comment] 2018-05-22 14:40
@djbrooke @scolapasta  - In the issue https://github.com/IQSS/dataverse/issues/4680 , I was planning to handle only the strings which has to be moved to bundle.properties.  

For Validataion message from Java programs, we can use this one.

**Comment by pdurbin** [comment] 2018-07-09 14:29
@JayanthyChengan pull request #4815 looks good so I'm moving it to QA. Thanks!

**Closed** 2018-07-13 21:12 UTC
Labels: Feature: Internationalization, Status: QA
