### ISSUE TITLE
File Tags: When adding new Categories and Tags to a Published Version. No new version is Created.

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#2979] opened 2016-02-29 19:52 UTC
Whether in "Bulk Update" of files on the Dataset page or Edit Tags on the Edit Files page, if you start with a published version that has no tags or categories and try to add both tags and categories to one or more tabular files, the Save Dataset Command fails and no new version is created.

The issue is caused during the merge dataset in the Update Dataset Command.  Specifically a new DataFilesTag record cannot be created because its id is null.  This should not be an issue because the id on the table is annotated with a generated value of Identity, but there must be something about the order in which the records are actually created that causes it to fail.

**Comment by mheppler** [comment] 2016-03-01 19:18
Currently I can replicate this bug on the Edit File pg, in a local build of the "develop" branch.

User Workflow:

1. Latest published version of a dataset, with tabular data files.
2. Select tabular file, click "Edit Files" button, select "Tags" from dropdown.
4. Select new file tag from the dropdown.
4. Select new tabular data tag from the dropdown.
5. Click "Save Changes" button on the Edit Tags popup.
7. See "Success!..." msg on dataset pg, see "Info..." msg saying "DRAFT" version was not found, scroll down to find tabular data file missing the new tags.

![screen shot 2016-03-01 at 2 10 42 pm](https://cloud.githubusercontent.com/assets/687227/13438557/8076beb2-dfb7-11e5-8c21-71ea324b1131.png)

**Comment by landreev** [comment] 2016-03-02 20:55
Hmm, bummer, for a moment I thought that the code I checked in yesterday also fixed this issue, at least for the Edit Files page. Turns out it is still bombing as described above, when the file doesn't have any categories and tags, AND has not had any categories or tags assigned previously. (Meaning, if I create a tab file, assign some tags, then assign some categories, then remove them all, then publish - then I can start with that published version, assign BOTH tags and categories on the edit files page, then save - and then the new draft is saved successfully. Go figure). 

Anyway, this is some weird EJB cascading implementation at work. We don't really do anything special, to save neither categories nor tags. We call the UpdateDatasetCommand that executes em.merge() calls on the filemetadata, datafile and dataset objects involved; with a fairly reasonable expectation that it will resolve the full hierarchy of all the affected database tables and modify them properly. Why it's working in some cases and not in others, I can't tell. 

I feel strongly that we should not worry about this to be addressed in 4.3. a) this is not a new bug, it must have been there all along, b) it's a fairly exotic scenario  and c) there's a workaround - change one thing at a time, not both. 

It would be nice to address this eventually. It may even be fixed by adjusting the cascade rules. And/or by explicitly merging the categories and tags in the db in the right order. But it could be cleaner to address the root issue instead and reconsider the nature of these "categories" and "tags". It is kind of annoying, that the former are tied to filemetadatas and the latter to files. There were historical reasons for why it ended up so - but they are irrelevant now. It would make life easier if the "tabular data tags" were just file categories, perhaps with an attribute/flag that specified that they can only be assigned to tabular data files. 

So, let's discuss this when we plan a future release.

**Comment by mheppler** [comment] 2016-03-02 21:07
Good stuff, @landreev. Thank you for reviewing this in more depth today.

Related to #2808.

**Comment by kcondon** [comment] 2016-04-19 16:49
Was not able to reproduce, will retest and hopefully close.

**Comment by kcondon** [comment] 2016-04-21 18:05
This is no longer happening, was not able to reproduce independently or using Mike's steps above. Closing.

**Closed by kcondon** 2016-04-21 18:05 UTC
Labels: Component: File Upload & Handling, Priority: Medium, Status: QA, Type: Bug
