### ISSUE TITLE
Download double counting

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#4637] opened 2018-05-01 16:40 UTC
Under some circumstances, I see a double count of a download. I see the following behavior for file download counting in v. 4.8.6 when downloading from the dataset page (https://demo.dataverse.org/file.xhtml?fileId=28535&version=RELEASED&version=.0 for example):
For a file for which the terms of access acceptance dialog is triggered, if a new draft of the dataset is created (e.g. by editing the metadata), downloading a file from the published dataset page increments the count by 2!

Downloading the same file from the draft dataset (requires being logged in) increments the count by 1 and doesn't show the accept dialog.

I also see:
If there is only a draft version of the dataset, downloading the file does not change the count (still 0 downloads)
Once the dataset is published, downloading a file increments the download by 1, regardless of whether you download from the published or draft dataset version page.

I've verified that I can 'fix' the double count by changing FileDownloadServiceBean's writeGuestbookAndStartDownload method's call the callDownloadServlet to hardcode the last parameter to true (instead of guestbookResponse.isWriteResponse()), which leads me to suspect one of the calls to setWriteReponse(false) in GuestbookResponseServiceBean where writeResponse is set to false inside an if statement like:
 if(workingVersion != null && workingVersion.isDraft()){
(slight variants in the different methods that do this). 

I can continue to debug but am hoping that someone else might understand this part of the code and be able to suggest a fix or provide some guidance regarding what the correct behavior is (should a download from the draft version of the dataset increment the count?) and/or what the intent of the if statements are (in what use cases should writeResponse be false in GuestbookResponseServiceBean) so I can avoid breaking some other use case.

**Comment by jggautier** [comment] 2018-05-01 17:18
> Should a download from the draft version of the dataset increment the count?

Hi @qqmyers. Just chiming in to write that no, downloading from a draft version of a dataset, whether or not that dataset has a published version, should not increment a download count. And on Harvard Dataverse and Demo Dataverse, I was able to reproduce both counting behaviors that you wrote about.

(As a non-developer I understand the code even less, so I'll defer to others about finding a fix.

**Comment by qqmyers** [comment] 2018-05-02 17:32
I've looked through 5 cases, 2 that produce incorrect download counts. First a description of what's happening, followed by discussion of the underlying issues, and some draft options to fix things.

draft dataset (no published versions): correct result - not counted. The writeResponse for the GbResponse is set to false (due to the latest version of the dataset being draft). The call to startFileDownload finds fileMetadata.getDatasetVersion().isDraft() == true and doesn't write the response. The call to the api with no gbrecs parameter, which should cause the response to be written is suppressed because dataset version isReleased() == false - the second half of the api's if clause stops the response from being written.

published dataset, no draft: correct result - counted once. The writeResponse for the GbResponse is true (due to the latest version not being draft). A response is written in the startFileDownload method based on a check of if(!fileMetadata.getDatasetVersion().isDraft()). startFileDownload requests that callDownloadServlet set gbrecs==true in the api call, which suppresses a response write there, leading to a total of 1 write.

download from draft when a published version exists: incorrectly counted once instead of not counted: The writeResponse is false since the latest version is draft. The call to startFileDownload finds fileMetadata.getDatasetVersion().isDraft() == true and doesn't write a response. It's call to callDownloadServlet results in a URI with no gbrecs parameter and, since datafile.isReleased() is true, the API incorrectly writes a response.

download from published when draft exists: correct result - counted once. The writeResponse is false since the latest version is draft. The call to startFileDownload finds fileMetadata.getDatasetVersion().isDraft() == false and writes a response. It's call to callDownloadServlet results in a URI with gbrecs == true which suppresses the api call from writing a second response.

download from published when draft exists and access dialog pops up: incorrect result - counted twice. The writeResponse is false since the latest version is draft. The call to goes to writeGuestbookAndStartDownload (instead of startFileDownload) which writes a response (It doesn't have filemetadata as a param and doesn't check datasetversion.isDraft()). It passes isWriteResponse() to callDownloadServlet (false in this case) instead of true from it having just written a response, That results in a URI with no gbrecs parameter which writes a second response.

I think a simple fix would be:
change writeGuestbookAndStartDownload to hardcode true in its call to callDownloadServlet, perhaps only if it writes the response. (Since it is only called when there are terms and conditions, the downloads are always from a published dataset, so having it always write and suppress a second from the api makes sense.)
change startFileDownload to also hardcode true. Right now, it sends false when it doesn't write a response because the version isDraft(), but this then allows the api to incorrectly record the download.

What this does is essentially turn the gbrecs flag into an indicator that the GUI has generated the call to the API versus an indication that a response has already been written, which seems to be its current meaning (seeing gbRecordsWritten param names). I think that works, but it might be worth a name change. I think this change works globally since the only other use of gbrecs I see is in creating public URLs (where gbRecordsWritten is hardcoded false to avoid having a gbrecs param on the URL). (Minor point: I do see the URL shown for a datafile in a draft dataset does not have a gbrecs = true param, meaning use of that URL counts as a download if there's a published version of the dataset.)

It's also not clear to me what the writeResponse variable is used for - it's currently being set false if there is a draft version of the dataset, regardless of whether the current version is draft or not. Other than the writeGuestbookAndStartDownload method where I suggest above it no longer be used, it only appears to be checked in the explore() and startWorldMapDownloadLink() calls in FileDownloadServiceBean (false and no guestbookresponse is written) Given that writeResponse is only true if there is a published dataset with no draft version, I'm not sure this is what's intended. I see that both of these have fileMetadata as a parameter - would checking fileMetadata.getDatasetVersion().isDraft() as is done is startFileDownload be better - it appears to be being set correctly in the cases above? And if this substitution does work - is there any reason to keep writeResponse and the logic related to setting it (which again results in true only for a published dataset with no draft version).

All this said - with the idea of dataset-level guestbooks with custom questions, which I haven't looked into, I may be missing something. Since the suggested changes above favor the writes from startFileDownload and writeGuestbookAndStartDownload over having responses written by the API code for anything starting in the GUI, I hope they are consistent with the logic for custom questions, which I assume are skipped/defaulted for an API call.

I guess I'll put together a PR with the two basic changes above and wait to hear whether changing the gbrecs variable name for clarity makes sense and/or whether dropping the writeResponse logic makes sense.

**Comment by djbrooke** [comment] 2018-05-08 15:08
Thanks @qqmyers for the PR, we'll take a look at it this week!

**Comment by djbrooke** [comment] 2018-05-09 19:26
We discussed this in Sprint Planning today, the team will review and provide feedback this sprint. Moving to Code Review column.

**Comment by landreev** [comment] 2018-05-14 18:34
Hi, 
Sorry about the delay with your PR; I'm giving it a final review before it goes to QA. And even though it only changes 2 lines of code, it wasn't immediately obvious to me that this fix would not introduce other issues (specifically, that some downloads that should legitimately be counted on the API side would not be left uncounted...) And the only way I can be sure is to retest every possible scenario. 

Thank you for the detailed explanations of all the cases. 
It may have not been the wisest of decisions on our part - when we implemented these guestbook entries counts in this way; that in some situations they are created on the UI side, and in others - in the API, with that "do not count" flag passed to the API... It's resulted in all this complexity and all these extra opportunities for things to go wrong. This part of the system is a prime candidate for some refactoring. But in the meantime we should definitely fix this double/extra count bug; so we'll try to merge it in as soon as we can.

**Comment by landreev** [comment] 2018-05-14 19:26
Upon closer inspection, it may all be more straightforward than I assumed early on... Meaning, that whenever a user is downloading a file through the UI, the guestbook record is either written on the UI side, or not written on the UI side because it shouldn't be (when it's a DRAFT); meaning it should NEVER be written on the API side when the download was initiated in the UI... 

That would mean that all that logic inside the FileDownloadServiceBean - for deciding whether to send the "do not count" flag to the API or not - was all legacy code, left over from some earlier days when it was necessary. Ouch.

**Comment by landreev** [comment] 2018-05-14 19:30
So yes, renaming that gbrecs variable to something more descriptive - like "doNotCount" or "doNotCreateGBRec" - could be a good idea at some point...

**Comment by landreev** [comment] 2018-05-14 21:08
@scolapasta 
Gustavo, this appears to be a safe assumption at this point - to just say that if the download is initiated in the UI, it is never the API side's job to write the GB record... and then this PR achieves its goal, since it simply makes the download service to always pass that "do not count" flag to the API. 

But, looking at the part of the original bug, where we get a *double* count, on a published file that just happens to also have a draft version... it was happening because guestbookResponse.isWriteResponse() happens to be set to false for such a file, even though we ARE writing the guestbook record for it properly, on the app side... And this is in turn the result of how we initiate the guestBookResponse inside the DatasetPage: 

```
this.guestbookResponse = guestbookResponseService.initGuestbookResponseForFragment(dataset, null, session);
```
 that null there means we are not calling it on a specific filemetadata, but as a pre-generated response that will be used for all the files downloaded from the page... but then the version defaults to the latest: 

```
if (fileMetadata != null){
   workingVersion = fileMetadata.getDatasetVersion();
} else {
   workingVersion = dataset.getLatestVersion();
}
```
and what that happens to be a draft, isWriteResponse() gets set to false... 

So, I'm debating if I should just accept this PR as is, to just go ahead and fix the double + extra count bugs in question. Or if we should also fix the thing with initiating the guestbook response with the wrong version, above - just because, as you mentioned, it may become important again; and when's going to be the next time anyone will go this deep looking at this awfulness? 
What do you think?

**Comment by landreev** [comment] 2018-05-14 21:15
@scolapasta 
(I'm tempted to just create a quick branch of my own with the fix from this PR, and quickly add the fix for the version; I think all it should take is to change this method in GuestbookResponseServicBean:
```
public GuestbookResponse initGuestbookResponseForFragment(Dataset dataset, FileMetadata fileMetadata, DataverseSession session){
```
To take DatasetVersion instead of Dataset as the first argument...)

**Comment by landreev** [comment] 2018-05-14 23:00
OK, I have created my own PR (https://github.com/IQSS/dataverse/pull/4670), incorporating @qqmyers' fixes and a few lines of extra comments/small fixes. I clarified that the flag passed to the API specifically means "do not write a GuestBook response record of your own", also fixed the part I mentioned above, about the response initiated with the wrong verison. It's not affecting anything as of now, but we may end up using it for something in the future. 
@scolapasta - I re-linked the issue to my new PR; and we'll just delete the old one. Should I drag it straight into QA, or do you want to take a look/review?

**Comment by landreev** [comment] 2018-05-14 23:07
@qqmyers as for your question about the writeResponse variable: it doesn't look like it's being used for anything, at this point. The way it's set, it appears that its original purpose was to indicate whether this response needs to be written or not; but then we are not checking it for that purpose. And then yes, it was mistakenly being used for the "do not write guestbook record on the API side" flag. It appears that this is some ancient legacy business... 
Thanks for contributing; and I'm seriously impressed by your willingness to dive into this messy part of our code; that we ourselves here are afraid to touch by now, apparently. :)

**Closed** 2018-05-18 19:28 UTC
Labels: Feature: Metrics + Reports, Status: QA
