### ISSUE TITLE
Clarify use of DataCite's DOI testing environment (10.5072 no longer the universal test prefix)

### ISSUE THREAD

**Issue by dheles** [IQSS/dataverse#5448] opened 2019-01-09 20:42 UTC
DataCite doesn't do things quite the same as EZID when it comes to test DOIs and the what the "FAKE" DOI provider isn't completely obvious.

**Comment by pdurbin** [comment] 2019-01-09 21:04
It might be nice for @landreev to take a look at pull request #5449 because I'm confused about if 10.5072 is a test prefix or not. Another thought is that three developers are going to https://pidapalooza.org in a couple weeks so maybe they could get some clarification on all this.

**Comment by landreev** [comment] 2019-01-10 15:53
Reviewing the PR - I'm not sure about the "configured with your own prefix" part, in 
"Unlike EZID, DataCite requires that you register for a test account, configured with your own prefix" 
The above really implies that one must have a registered, unique prefix, just to start using DataCite, even in a testing setup... It should probably say something to the extent of, if it's just for testing, you can keep using the test authority above (10.5072), set by default by the installer; (all new DataCite accounts come pre-configured with that authority, correct?); and if a real, registered authority is desired, it needs to be obtained from DataCite, and configured via the setting API... 

Please correct me if the above is no longer true; but this is how it used to work - i.e., all the new accounts would indeed be automatically enabled to use 10.5072.

**Comment by landreev** [comment] 2019-01-10 16:01
OK, looking at the new title of the issue - this appears to be the whole point of it, that "10.5072" is no longer the universal test prefix... Could you please point us to any DataCite documentation where this is explained?

**Comment by dheles** [comment] 2019-01-11 03:14
Sure:
https://support.datacite.org/docs/create-a-client-in-fabrica-test#section-assign-a-prefix

**Comment by landreev** [comment] 2019-01-11 21:32
Thank you @dheles 
Reading the page above, it appears to be specific to "DOI Fabrica" - the new API, that we are not using yet. (correct?) 
So far I can't find similar information in their "classic" API docs. And the examples there are still showing the 10.5072 prefix appearing alongside the dedicated prefixes assigned to specific users... Have you actually been able to confirm this scenario - registering a test account with DataCite, but not being able register test dois under the prefix 10.5072? 

Sorry, not trying to be difficult at all - just really want to confirm for sure what the deal is. (I'll go ahead and ask Marten from DataCite to confirm)

@pdurbin 
@scolapasta 
If we confirm that the above is true - that 10.5072 does not automatically work with DataCite test accounts - we should probably NOT be setting up as the default prefix in the installer. We could either leave it as the default prefix, but also switch to configuring FAKE as the default provider; or, if we want to continue configuring new installations with DataCite, we should probably leave the prefix blank - like we are leaving the registration username and password blank.

**Comment by dheles** [comment] 2019-01-12 04:57
@landreev NP. We all want the docs to be as clear and as accurate as possible. 

I have a GDCC-administrated test account which was assigned a unique prefix. When I configured my dev Dataverse (v4.9.4) instance with the correct username and password, but kept the prefix as the default 10.5072, and I attempted to publish a test dataset, I received an error and the publication failed. When I reconfigured the instance with my assigned prefix, I was successfully able to publish it.

If it would be helpful, I'd be happy to host a demo/conversation over zoom next week.

**Comment by dheles** [comment] 2019-01-14 19:49
I repeated the test to confirm my previous results and took screenshots this time.

Configured with 10.5072 - Error:
<img width="1114" alt="dataversepubfail" src="https://user-images.githubusercontent.com/2560887/51136644-05a64380-180b-11e9-9243-f23c8befbf09.png">

Configured with the prefix assigned to my client account - Success:
<img width="1114" alt="dataversepubsuccess" src="https://user-images.githubusercontent.com/2560887/51136664-0fc84200-180b-11e9-8cbd-c16c46b9092b.png">

**Comment by landreev** [comment] 2019-01-24 21:36
@scolapasta 
Gustavo, this is the DataCite documentation PR that I reviewed/commented on before I left for my mini-vacation... I just realized that it's still sitting in the "community dev." column waiting. 
Since the author has tested and confirmed that the name space 10.5072 is NOT automatically available to everyone with the DataCite test account, I believe we should: 

- Accept and merge the PR; 
- BUT, also, we should change the way the installer configures new instances out of the box: It should either leave the name space blank (with the doc guiding the owner on how to obtain the credentials AND the name space from DataCite); OR, we should keep configuring 10.5072 by default, but with the builtin "fake" registration provider instead of DataCite. (Should we also rename it, to "TEST" instead of "FAKE"?)

What do you think we should do? Do you have a preference? 
The latter would make it easier to bring up a test instance for some tire kicking...

**Comment by dheles** [comment] 2019-01-24 23:40
FWIW, @landreev, for the sake of the aforementioned tire kicking, I think your latter suggestion would be much better than the former.

**Comment by landreev** [comment] 2019-01-26 01:58
@kcondon I'm moving this into QA; this is a doc. change only- please review and merge.
I'm opening another issue for modifying the installer, as discussed in the last comments.

**Closed** 2019-01-28 17:11 UTC
Labels: Status: QA

**Comment by pdurbin** [comment] 2019-05-22 10:37
Related: https://github.com/IQSS/dataverse.harvard.edu/issues/19
