### ISSUE TITLE
Edit Files - Dropdown (delete/restrict/unrestrict) menu hidden in new dataset form

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#5178] opened 2018-10-12 17:52 UTC
The Edit menu in the file table on the new dataset page appears to be being cut-off/not shown except for a few pixels. Visible on demo.dataverse.org. I've tracked it down to an overflow:hidden style being applied to the table as part of the .ui-datatable-scrollable-header class being applied, but I'm not sure what a good fix would be. The existing dataset page, which has a paginated table rather than a scrollable one, doesn't have the issue.

**Comment by pdurbin** [comment] 2018-10-12 17:59
Sounds like a duplicate of #3835

Here's a screenshot I just took from the demo server:

![screen shot 2018-10-12 at 1 58 08 pm](https://user-images.githubusercontent.com/21006/46885742-e3c1ad00-ce26-11e8-82c8-9809428fdca2.png)

Or are you seeing something else, @qqmyers ? A screenshot might help.

**Comment by mheppler** [comment] 2018-10-12 18:00
@qqmyers I had noticed this in a recent development branch and will look into it in more detail. This seems to be an oversight on my part, or possibly a result of bad merge.

**Comment by qqmyers** [comment] 2018-10-12 18:10
@pdurbin - possibly the same bug, but different symptom. I see the cutoff in the Edit menu in the header - almost completely hidden in this snip.

![image](https://user-images.githubusercontent.com/6731983/46886309-84fd3300-ce28-11e8-9aa3-58bdcba00cb1.png)

**Comment by qqmyers** [comment] 2018-10-12 18:42
@mheppler - Hmmm. I only see it on demo when I have enough files (I tried 4 and then 47 but guessing it's above the 25 per page limit). It is in the new dataset page only, which I think is using editFilesFragment.xhtml rather than filesFragment from #4656. The stylesheet being referenced shows as 
https://demo.dataverse.org/javax.faces.resource/components.css.xhtml?ln=primefaces&v=6.2 in my browse...

**Comment by mheppler** [comment] 2018-10-12 18:50
Ahhhh, sorry I missed that it was on the New Dataset pg form, @qqmyers. I was able to replicate this locally with 33 files and will investigate further.

<img width="1146" alt="screen shot 2018-10-12 at 2 49 14 pm" src="https://user-images.githubusercontent.com/687227/46888302-1622d880-ce2e-11e8-8c9c-8c8f5fd7f174.png">

**Comment by mheppler** [comment] 2018-10-12 20:18
Removed the scroll functionality from the Edit Files dataTable, which was left behind after the changes to the dataset version of the dataTable in #4656. This was causing the Edit File dropdown menu in the table header to display behind table rows, because the CSS which would correct this was removed.

You would need 27 or more files in the dataTable to see this issue when editing/uploading files or creating a new dataset, which both use the editFilesFragment. Removing the scroll feature will now clearly display all files in the table on the page. If you upload 100's of files, you will have to scroll the entire page through all of them to get to the Save Changes and Cancel buttons displayed below the dataTable.

Another solution could be to return the CSS that overwrites the CSS from PrimeFaces which is the cause of the disappearing dropdown menu.

**Closed** 2018-10-17 17:51 UTC
Labels: Feature: File Upload & Handling, Status: QA
