### ISSUE TITLE
Unintuitive behaviors when deleting files via SWORD API

### ISSUE THREAD

**Issue by rliebz** [IQSS/dataverse#1784] opened 2015-03-27 15:39 UTC
Expected
------
Attempting to delete a file from a dataset in the `RELEASED`  released state will:
 1. Succeed regardless of when the file was published or what actions have occurred since publishing
 2. Move the dataset to the `DRAFT` state

Actual
-----

First, a file that has been published on a dataset cannot be deleted if no actions been taken since that file was published. This means that the sequence `upload file A, publish dataset, delete file A` will fail, but `upload file A, publish dataset, upload file B, delete file A` will succeed. The error produced here is:

`Could not delete file: edu.harvard.iq.dataverse.engine.command.exception.IllegalCommandException: Cannot delete a released file`

Second, a file deletion is not sufficient to move a dataset from the `RELEASED` state to the `DRAFT` state. Because of this, it is possible for a dataset listed by SWORD as `RELEASED` to be different than the actual last published version. This also means datasets that only deleted files since the last publication cannot be published until some other action is taken.

**Comment by pdurbin** [comment] 2015-03-28 00:31
I agree that this is very strange behavior. I wonder if DVN 3.x works the same way. I haven't yet tried to reproduce this.

**Comment by scolapasta** [comment] 2015-04-01 15:26
@rliebz Can you clarify something on this?

You said "Because of this, it is possible for a dataset listed by SWORD as RELEASED to be different than the actual last published version."

We're trying to understand this to make sure that it's not something critical.

What we understand is you can't just delete a file from a dataset (because it fails - and shouldn't). So to delete a file, you first make some other change (like adding a file), that creates a draft, and then you delete the intended file.

**Comment by rliebz** [comment] 2015-04-01 17:04
These may be two separate issues. You can't delete a file from a dataset if and only if that file was originally released in the most recent published version.

This is the scenario in which I the dataset listed by SWORD as RELEASED can be different than the actual last published version:

1. A unpublished dataset is published with file1.txt. 
2. The dataset is published again with file1.txt unchanged, and file2.txt. 
3. file1.txt is deleted through SWORD. (file2.txt is not deletable, which may be a separate issue)
4. The SWORD statement will:
  - Display only file2.txt (file1.txt has been deleted)
  - List the dataset as RELEASED, despite being inconsistent with the last published version.

**Comment by scolapasta** [comment] 2015-04-03 18:42
@pdurbin setting to critical at least for the investigation.

**Comment by pdurbin** [comment] 2015-04-07 18:47
There's definitely something weird going on. I just pushed some code to https://github.com/IQSS/dataverse-apitester/commit/79fb4b91f8bc3134cef6da271cd29dc8e4409387 to start reproducing this bug but I need more time to make an assessment.

(A more crucial bug has surfaced at #1901 that needs my attention.)

**Comment by pdurbin** [comment] 2015-04-07 20:15
I'm getting new behavior as of 71dc999 I think.

**Comment by pdurbin** [comment] 2015-04-08 13:48
Uh oh. When I pulled the latest (df14aee) and ran my test at https://github.com/IQSS/dataverse-apitester/blob/79fb4b91f8bc3134cef6da271cd29dc8e4409387/src/test/java/org/dataverse/apitester/sword/SwordTest.java#L156 two drafts are created:

![2drafts](https://cloud.githubusercontent.com/assets/21006/7046524/5fd4ddd2-ddd4-11e4-9448-7576d05c302a.png)

**Comment by scolapasta** [comment] 2015-04-08 20:29
OK, so attempting to fix this has been trickier than we anticipated. So, for 4.0, what we've done is not allow deleting of any file from a released dataset version. What that means is that if you try the above the delete will fail with this error: 
"Could not delete file: edu.harvard.iq.dataverse.engine.command.exception.CommandException: Cannot delete files from a released version. Please create a draft version of this dataset."

What you need to do, is first create a new draft then you can delete the files.

In testing, it would be good to make sure this did not affect deleting files through the UI (outside of already existing issues like #1344)

**Comment by rliebz** [comment] 2015-04-08 20:31
Is there a simple way to create a draft version of the dataset through the API without making any changes?

**Comment by pdurbin** [comment] 2015-04-08 20:45
@rliebz if you send the same XML you used to create the dataset, it should create a draft version.

**Comment by rliebz** [comment] 2015-04-08 20:51
Does this update the metadata? SWORD doesn't return as much metadata as you send, so for pre-existing datasets, I wouldn't want to remove any metadata that I don't know about.

**Comment by pdurbin** [comment] 2015-04-09 02:21
Hmm, if you want preserve all the metadata, I would recommend the "native" API: http://guides.dataverse.org/en/latest/api

**Comment by pdurbin** [comment] 2015-04-11 12:54
In the course of working on this ticket, I think a regression was introduced (now fixed, hopefully) that was noticed on Twitter: https://github.com/IQSS/dataverse/commit/71dc9994d266f98836a3a5d7bb95a27476987835

**Closed** 2016-01-12 19:05 UTC
Labels: Component: API, Priority: Critical, Status: QA, Type: Bug

**Comment by pdurbin** [comment] 2016-02-02 18:47
Today I wrote some tests for this bug. See https://github.com/IQSS/dataverse/issues/2222#issuecomment-178752740
