### ISSUE TITLE
File Upload - Scalable upload options, AKA "dual-mode"

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4610] opened 2018-04-24 15:32 UTC
As a repository operator, I'd like to be able to support Dataverse native HTTP (browser and API) uploads and DCM uploads in the same installation.  Similarly, I'd like to be able to support Dataverse native HTTP, S3 redirect (, swift?) download methods alongside RSAL downloads in the same installation.

**Comment by mheppler** [comment] 2018-05-30 16:38
This includes:
- make the Upload Files pg scalable for any combination of HTTP, dropbox, rsync+ssh, or any other config options we develop down the road
- the file upload workflow for rsync only will need to change, to use the Upload Files pg and not just the Upload Files popup, to be more consistent across the various config options
- for this initial phase of delivering "dual-mode", you will only be able to upload one way or another, HTTP/Dropbox or rsync+ssh, but not both
- download methods will depend on which upload method was used

**Comment by mheppler** [comment] 2018-05-31 20:14
Initial commit for UI prototype added to branch `4610-upload-dual-mode`. Changes include:

- New accordion panel UI for various upload method options
- Placeholder panel headers, help text, etc
- Fixed trailing hyphen issue in help msg block outlined in #4608
- New "Done" button added to editdatafiles.xhtml when the page is empty/no file/nothing to save

Tasks to tackle in the next phase of development:

- Proper render logic for dropbox and rsync panels
- Final help text for panels, added to bundle
- Investigate bug for new "Done" button on editdatafiles.xhtml when you delete uploaded files from the table
- Investigate use of element id's in commandButtons on Lines 296-297 of editFilesFragment.xhtml, does not seem scalable, and not sure if I added all the new UI id's to all the buttons that need them (see delete bug above?)
- Write help/error/success msg text for all the various render conditions related to what upload options are available and when (note: you can not upload via rsync if you have already uploaded files via http, and vice versa)
-

**Comment by mheppler** [comment] 2018-05-31 20:18
This probably needs it's own issue, but the documentation for how to set up Dropbox for file upload is severely lacking. It took me far too long to find these [required steps in the Dropbox documentation](https://www.dropbox.com/developers/chooser). We should link to that page from our guides to make it easier to set up. Currently, we provide [no instructions](http://guides.dataverse.org/en/4.8.6/installation/config.html#dataverse-dropbox-key).

**Comment by pdurbin** [comment] 2018-06-25 15:01
3db4486 was so far `develop` that I couldn't even run the code so I merged the lastest in fb4e4f3. Heads up to @dlmurphy that I went with the version of @mheppler 's branch, which will undo fe59aef so you two should get on the same page about that tooltip.

**Comment by dlmurphy** [comment] 2018-06-25 17:41
@pdurbin I just talked with @mheppler and we're good with that merge. That tooltip will likely be further edited in the near future as part of the 5.0 redesign process anyway.

**Comment by pdurbin** [comment] 2018-07-17 18:54
I took a quick look at pull request #4862 and noticed that there are merge conflicts in the bundle.

**Comment by pdurbin** [comment] 2018-07-17 20:41
@sekmiller fixed the merge conflict in b5f81e3 and I offered to help with weaving this new feature into the guides somehow. He's going to take a look at the render logic for installations that haven't been configured with Dropbox or DCM. Right now it's all visible, including some placeholder text that @dlmurphy or others might want to weigh in on:

![screen shot 2018-07-17 at 4 37 00 pm](https://user-images.githubusercontent.com/21006/42844114-fae6a9b2-89df-11e8-903b-5f2d187629d8.png)

Question for @pameyer (and others): Is it ok if it's not possible to turn off "native" or "traditional" file upload? I believe you have it turned off it your fork but it's not possible in the pull request as of this writing. I checked with @sekmiller

**Comment by pameyer** [comment] 2018-07-17 20:47
Yes, it does make sense to retain the ability for different upload methods to be configurable (at minimum at the installation level, possibly at the dataverse level).

**Comment by pdurbin** [comment] 2018-07-17 22:04
@pameyer ok, thanks. @sekmiller we can't just put `!settingsWrapper.rsyncUpload` back in to disable "Upload with HTTP via your browser". (Also, I just noticed that we need to move that English out of editFilesFragment.xhtml and into the bundle.) I guess we need a setting or something to disable "Upload with HTTP via your browser". @pameyer in your mind when "Upload with HTTP via your browser" is disabled does that mean that APIs that use HTTP are disabled as well? Or would that be a different setting?

**Comment by pdurbin** [comment] 2018-07-18 14:39
@sekmiller and I spoke with @djbrooke @pameyer @landreev and @oscardssmith this morning. In 3ba0036 I adjusted the `FileUploadMethods` enum to rename "NATIVE" to "native/http" in preparation for making it possible to disable http upload for both GUI and API. @sekmiller and I believe it will be better to have "native/http" explicitly set as a database setting out of the box rather than having implicit logic in the code. So we'll be updating setup scripts to add it. I also added a TODO to add "native/dropbox" if we feel like it helps makes the code and user experience for sysadmins better. Some discussion about if it would be better to move the Dropbox key from a JVM option to a database setting. (I'd probably leave it alone but I don't have a strong opinion about this.)

**Comment by pdurbin** [comment] 2018-07-19 19:40
Pull request #4862 is looking good, I think, so I moved it to QA. Heads up to @mheppler and @dlmurphy that in 4a7fcf5 I removed some help text that I didn't find very helpful. If someone can suggest better text, please advise and it can be put back in.

**Comment by kcondon** [comment] 2018-07-20 21:03
Discussed design with Stephen and Phil. Have 3 questions/issues before testing:
1. It says dual mode but drop box was added as a 3rd option. Is that legit and it implies people want to remove drop box and potentially run in drop box only mode (may not work well).
2. File upload apis (sword, native, replace) are disabled during rsync-only mode but not disabled during dual mode. UI blocks mixed uploads per dataset but API may allow mixed uploads.
3. Changing upload mode config may result in unanticipated behavior. Going from one->dual should be ok as one is subset of dual but going from dual->one might be an issue, particularly if dropping https. Am told behavior should be that https downloads should continue working but may not make additional uploads.

**Comment by kcondon** [comment] 2018-07-20 23:01
Native and Dropbox work in basic UI testing. Could not get Rsync to work by following dcm_mock instructions.

Need to test API enable/disable, mixed mode, rsync only mode. Need to follow up on above questions.

**Comment by dlmurphy** [comment] 2018-07-25 19:14
Some notes from conversation about Add New Dataset page with Phil, Kevin, and Tania:

- Make rsync window collapsible like the other two.

- Properly indent the messaging in the rsync window

- Replace the text in the rsync window with:

> rsync allows you to run a script that transfers your files into or out of Dataverse via SSH. It is useful for extremely large files, or packages containing a large number of files. Once you have saved this dataset, you can upload your data using rsync via the "Upload Files" button on the dataset page.

**Comment by TaniaSchlatter** [comment] 2018-07-25 20:31
Sketch that hints at render logic for dropbox and rsync panels:
![img_6949](https://user-images.githubusercontent.com/15386424/43225863-36aacf16-9028-11e8-9bc3-c08caf0d0908.jpg)

**Comment by pdurbin** [comment] 2018-07-25 20:37
> Replace the text in the rsync window

Fixed in 7452e66


> Properly indent the messaging in the rsync window

Fixed in a867f5b

> collapsible

My understanding is that there is still work to be done in this area. @djbrooke will do housekeeping on the issue.

**Comment by djbrooke** [comment] 2018-07-25 20:44
Will discuss with @mheppler and other interested parties when he's back next week.

**Comment by djbrooke** [comment] 2018-07-30 17:54
Thanks @sekmiller and @mheppler for working together to generate a checklist of remaining items here. I'll be happy to help with questions of scope, etc.

**Comment by mheppler** [comment] 2018-07-30 19:06
Talked to @sekmiller. The only remaining to-do requiring my attention is:

- [ ] fix the header link toggle for the rsync panel

**Comment by pdurbin** [comment] 2018-08-06 16:29
At standup this morning I volunteered to deploy the code to the dev1 server in various configurations:

- native + dropbox only
- rsync only
- both

As of ec8aa56, native + dropbox only has been deployed: https://dev1.dataverse.org

**Comment by mheppler** [comment] 2018-08-08 17:45
Latest and greatest to-do checklist based on review of the new [feature summary doc](https://docs.google.com/document/d/14mkaH_YW1jP-xlFMtLuW-xDuAx_3g3FbIuVJ_0YhLAE/edit#) with @pameyer and @pdurbin and @dlmurphy.

- [ ] Need to improve `isHasRsyncScript()` render logic to deliver more informative msg than just "Rsync script not available!" Should add "I'm broken" and "I'm busy" logic, with appropriate msg text for each (i.e. "contact Support", or "try again later")
- [ ] If any file exists, fix render logic which incorrectly displays "Rsync script not available!" error msg, to instead display new dynamic version of the "You can not upload additional files to this dataset." warning msg, which should also explain "_why can't I upload more files?_"
- [ ] When dataset lock warning msg is displayed, add text link to "Download Script" just like the download btn in the rsync upload instructions in case someone needs to access that script again, as well as text link to user guide in case someone needs to learn more about rsync uploads which is the cause of the lock
- [ ] When HTTP file is added, fix render logic which incorrectly displays "The script will be available..." info msg, to instead display "You can not upload additional files to this dataset." warning msg, which should also explain "_why can't I upload more files?_"
- [ ] When HTTP file exists, fix render logic which incorrectly displays "Rsync script not available!" error msg, to instead display "You can not upload additional files to this dataset." warning msg, which should also explain "_why can't I upload more files?_"

Still to consider, which might ultimately get added to the to-do list:
- Do we want disable and add warning msgs to Upload Files pg if user accesses pg manually view browser history while dataset is locked/upload disabled?
- File size upload limit info msg (HTTP vs rsync, might need dynamic msg for dual mode)
- File type info msg (is rsync properly supported with this msg)

**Comment by dlmurphy** [comment] 2018-08-10 17:02
Document with in-app messaging for this feature: https://docs.google.com/document/d/14mkaH_YW1jP-xlFMtLuW-xDuAx_3g3FbIuVJ_0YhLAE/edit

My new revisions to the messaging are highlighted in green.

Next step for me is to work on the documentation.

**Comment by dlmurphy** [comment] 2018-08-10 22:03
I just committed the bulk of the Dual Mode documentation, but on Monday morning I want to briefly check around the rest of the guides and make sure other sections about rsync are still accurate.

**Comment by pdurbin** [comment] 2018-08-13 20:03
I'm ready for code review as of cf041d5 so I dragged this issue over in https://waffle.io/IQSS/dataverse

**Comment by dlmurphy** [comment] 2018-08-13 20:25
Hold up, I have one more doc commit to make, then I'm ready too.

**Comment by dlmurphy** [comment] 2018-08-13 20:29
OK, docs are done too now, ready for code review.

**Comment by kcondon** [comment] 2018-08-17 21:08
Found an issue in dual mode: guestbook is missing from dataverse edit menu when rsync is defined in :DownloadMethods. :DownloadMethods is used both for rsync only and dual mode as it renders rsync urls. This check no longer seems correct in dual mode where we want gb for http download and that is defined in :UploadMethods. When both are defined, I assume we do want to show gb but would like to discuss.

**Comment by mheppler** [comment] 2018-08-21 16:34
Discussed briefly with @sekmiller and @kcondon and here is what I have as the outstanding issues:

- [ ] update branch with develop to get all the goodness of DCM S3 in there
- [ ] dataverse pg needs {settingsWrapper.rsyncDownload} render logic for metrics block and guestbook link in Edit dropdown changed to something that supports dual mode
- [ ] confirm with @pameyer that he signs off on everything

Happy to discuss in more detail if needed to get this to done.

**Comment by kcondon** [comment] 2018-08-21 22:31
Message should use email address rather than the name of the root dataverse per DMurphy:
You cannot upload additional files to this dataset. A dataset can only hold one data package. If you need to replace the data package in this dataset, please contact Support at [support email].

**Comment by kcondon** [comment] 2018-08-21 22:35
This message is missing:
“Multiple file upload/download methods are available for this dataset. Once you upload a file using one of these methods, your choice will be locked in for this dataset.”

**Comment by kcondon** [comment] 2018-08-21 22:39
This message is missing for already published with http files but I think it is ok since it is not possible:
rsync upload is disabled because this dataset has already been published with files uploaded via HTTP. If you would like to switch to rsync upload, please contact Support at [support email].

**Comment by kcondon** [comment] 2018-08-21 22:41
This message also seems impossible but was implemented:
 HTTP upload is disabled for this dataset because because you have already uploaded files via rsync. If you would like to switch to HTTP upload, please contact Support at [support email].

**Comment by kcondon** [comment] 2018-08-21 22:51
Once published, delete should not be available for rsync. Subsequent drafts should also not have file delete.
Restrict/Unrestrict should not be available for rsync files since they're downloaded outside of Dataverse (and are are public).

**Comment by pameyer** [comment] 2018-08-22 20:36
On c7c6b7e

DCM only mode:
- [ ] delete unpublished package file, click upload again, error message is "The Data Capture Module failed to generate the rsync script. Please contact Root Support." Implies system failure, rather than expected behavior.  Implementation complexity for changing messaging may be more than its worth.
- [ ] renaming a package file in UI works.  Won't change anything other than display, may not be worth disabling.  Any thoughts on this being high-complexity or low-complexity?
- [ ] `ui-datatable-tablewrapper` might be too short; clicking the "edit files" menu results in the appearance of a scrollbar.  Seen with single package file present in dataset, may apply to other cases with single file.
- (split into separate issue)`api/info/metrics/downloads/toMonth` endpoint returns `0`; but won't have any useful information (and in dual-mode, this info will be incomplete).
- fixes for shoulder/identifier from were split out from 
https://github.com/IQSS/dataverse/pull/4946; so DCM checksum success API in Dataverse is non-functional.  Not something that needs to be fixed in this branch; just noting it.

Dual mode:
- [ ] create dataset in UI; upload native file, `/dataCaptureModule/rsync` API endpoint still produces valid transfer script.  scanner still picks it up, results in mixed dataset (endpoint would be expected to return an error if there's a native file).
![screen shot 2018-08-22 at 3 27 38 pm](https://user-images.githubusercontent.com/10261853/44485848-fafece00-a61f-11e8-9aa4-ca9e82a8cc4a.png)
- [ ] create dataset in UI with no files; publish; click "add files"; download transfer script; upload native/http file; click "save changes"; error message "the files could not be updated". glassfish logs show that the save is being rejected (correctly) due to dataset log.  May be worth providing more informative messaging (aka - "you picked DCM uploads, don't do native").
- (split into separate issue) in dual mode, it looks like the metrics block on the dataset page is hidden/disabled for datasets with only native files (possible I'm missing this due to unfamiliarity with metrics blocks).  Metrics blocks are still displayed for the root Dataverse.

Initial thinking is that it makes sense to defer metrics-related issues to a separate issue (which intersects with multiple storage locations).

**Comment by kcondon** [comment] 2018-08-28 17:48
Message needs to be updated to use support email addresses:
unpublished, rsync file uploaded
http section says:  HTTP upload is disabled for this dataset because you have already uploaded files via rsync. If you would like to switch to HTTP upload, please contact Harvard Dataverse Support.
should have support email rather than Harvard Dataverse Support
rsync section should also have support email rather than null:
You cannot upload additional files to this dataset. A dataset can only hold one data package. If you need to replace the data package in this dataset, please contact null.

**Comment by mheppler** [comment] 2018-09-05 17:50
As @pameyer suggested above, the button added for "Redownload DCM Script" when the dataset is locked for upload, needs some attention. This issue was moved back into develop in order to solve this. The button currently links to the File Upload pg which is the same page the disabled "Upload Files" btn links to.

In an attempt to deliver something closer to what was [initially suggested](https://github.com/IQSS/dataverse/issues/4610#issuecomment-408975721), I have managed to get this Frankenstein looking button and message block solution mocked up. (It is only mocked up because when you click on the button you don't get the script, but instead the page refreshes and the dataset lock warning msg is no longer displayer.) 

![screen shot 2018-09-05 at 1 48 21 pm](https://user-images.githubusercontent.com/687227/45111216-68c3f300-b112-11e8-8dd0-c6be4ee5cefc.png)

Will be working to get something similar to this solution, or a text link -- if possible, but there were concerns about the `onclick` nature of this link, as opposed to a URL you can navigate to.

**Comment by mheppler** [comment] 2018-09-05 19:39
After reviewing options with the team, it was determined the easiest solution would be to make the "Download DCM Script" button on the dataset pg actually download script, instead of link to the Upload Files pg. (What made it even easier was that the DatasetPage.java bean already had the `DatasetPage.downloadRsyncScript()` code in it!)

![screen shot 2018-09-05 at 3 37 08 pm](https://user-images.githubusercontent.com/687227/45116793-df1c2180-b121-11e8-9820-9d75e95a526a.png)

**Comment by mheppler** [comment] 2018-09-05 19:47
Moving back to QA with the blessing of @pameyer. Will address his last ["jumping up and down" UX issue](https://github.com/IQSS/dataverse/issues/4610#issuecomment-417765117) in another issue or later in this QA cycle.

**Comment by pameyer** [comment] 2018-09-18 21:55
On 92ec40559e37dfd3c795f15b0732ff4165de460a

big-data mode:
 - slightly odd that there's an option to edit file permissions (dataset page -> edit button -> permissions -> file) that doesn't do anything; may not be worth fixing.

dual-mode:
 - "jumping up and down" is there for normal files too; haven't checked develop to see if it's an issue outside dual-mode.
 - still possible to create a mixed dataset (in an empty dataset, navigate to upload files page, download script via API, upload file via browser, save dataset, run upload script and DCM scanner).  Low probability path, but it results in a dataset in a state is shouldn't be possible for it to be in.

![screen shot 2018-09-18 at 5 48 40 pm](https://user-images.githubusercontent.com/10261853/45718473-1bf90700-bb6b-11e8-893a-b6eee5c2fd7c.png)

**Comment by pameyer** [comment] 2018-09-18 22:07
A little more investigation on the mixed dataset; native upload APIs are blocked when a DCM upload lock is present, but not blocked when there's already a package file in the dataset.

**Comment by sekmiller** [comment] 2018-09-20 16:06
checked in fixes for both of @pameyer 's notes above. moving back to QA assigning back to Pete.

**Comment by pameyer** [comment] 2018-09-20 21:57
@sekmiller Thanks; fixes look good.

It looks like I've run out of ways to break this; the closest I came was inconsistent UI state:

one way native upload can be inactive
![screenshot from 2018-09-20 17-39-36](https://user-images.githubusercontent.com/10261853/45848935-40d1b380-bcfe-11e8-81dc-08f2dd71ab0d.png)

the other way native upload can be inactive
![screenshot from 2018-09-20 17-44-31](https://user-images.githubusercontent.com/10261853/45848968-5e068200-bcfe-11e8-8972-7bc033bc91b0.png)

There were suggestions from the UI review yesterday (https://docs.google.com/document/d/1Cshqx10BnYKy8HWEPFgI7Dho8ObXSN8zo48mP3t9Egk); @djbrooke are we considering those (chevron icons; red error -> yellow warning; link in "please contact support") in-scope for this issue, or splitting them off?

**Comment by djbrooke** [comment] 2018-09-21 18:52
Thanks @pameyer - we should do those suggestions as part of this issue. 

@dlmurphy can you put together a checklist from the notes doc and add it here?

**Comment by dlmurphy** [comment] 2018-09-21 20:45
**Checklist from UX Review:**

- [ ] Add text to end of rsync upload script: "ALL TRANSFERS COMPLETE. Dataverse is now verifying the checksum and your upload should appear in the UI in ~5 minutes."

- [ ] Upload method accordions need chevron icons to indicate open/closed state, similar to this metadata block, for example:
<img width="104" alt="chevron" src="https://user-images.githubusercontent.com/22962740/45905236-a8026d00-bdbd-11e8-80e0-b6a47a7248bc.PNG">

- [ ] As soon as one http file is uploaded, the rsync upload window should change its message to the warning message. You shouldn’t need to click save first.

- [ ] rsync upload warning message when http files are added -- message should be yellow warning style, not red error style.

- [ ] In message when DCM fails to generate script - “Please contact support” should link to the support modal.

**Comment by mheppler** [comment] 2018-09-24 19:20
Added chevron icons to upload method headers. Fixed warning msg styling. Added new render logic for missing msgs when HTTP file is added. de33aec8f88981ffcea0f7f0286326dea99165eb

![screen shot 2018-09-24 at 2 54 25 pm](https://user-images.githubusercontent.com/687227/45973783-68ca5b00-c00d-11e8-9e9e-504b0707cb4d.png)

**Comment by mheppler** [comment] 2018-09-24 19:54
Had to remove `!empty EditDatafilesPage.fileMetadatas` render logic from the dataTable to get the "There are no selected files to display." empty table msg on the Edit Files pg to display again. Unfortunately that also return the "Files you upload will appear here." empty table msg on the Create Dataset and Upload Files pgs.

![screen shot 2018-09-24 at 3 50 44 pm](https://user-images.githubusercontent.com/687227/45975328-f445eb00-c011-11e8-9314-e116bb67be34.png)
![screen shot 2018-09-24 at 3 51 09 pm](https://user-images.githubusercontent.com/687227/45975334-f740db80-c011-11e8-8d10-945d96a78f16.png)

**Comment by pameyer** [comment] 2018-09-25 18:47
on 7e45bbfd9

@mheppler do you think the oddness with "files will appear" widgets is confusing enough to get sorted?
![screen shot 2018-09-25 at 2 04 43 pm](https://user-images.githubusercontent.com/10261853/46033413-23209780-c0cc-11e8-81a7-d0b3fcfbd473.png)
![screen shot 2018-09-25 at 2 05 16 pm](https://user-images.githubusercontent.com/10261853/46033450-3af81b80-c0cc-11e8-9423-d4cb5feb7a5d.png)
![screen shot 2018-09-25 at 2 15 43 pm](https://user-images.githubusercontent.com/10261853/46034134-e05fbf00-c0cd-11e8-9029-786b736f3d90.png)

dual mode:

- [ ] dataset w\ package file; "http upload disabled" is red, should be orange (unless I'm misinterpreting/misremembering from UX review)
![screen shot 2018-09-25 at 2 26 51 pm](https://user-images.githubusercontent.com/10261853/46034636-1fdadb00-c0cf-11e8-9cda-057ba29ed17e.png)
- probably not dual-mode specific; but "upload package file; delete package file; add/edit files page" shows red "DCM couldn't generate script" error.  This is not an error (DCM won't provide a script for a dataset where the files have already been validated), but the logic required to distinguish this from an actual error may mean it's better handled elsewhere.

**Comment by mheppler** [comment] 2018-09-25 19:01
@pameyer -- I was at a loss with that one. Initially, there was render logic that would hide that table, but it also resulted in an empty Edit Files pg when you delete a file. I can take another look at the render logic and see if there is another workaround for both workflows.

**Comment by mheppler** [comment] 2018-09-26 20:18
Discussed remaining to-do issues with @sekmiller so we can swarm and get this to done!

- [ ] Improve render logic to display empty files table with "There are no selected files to display" msg on Edit Files pg after you delete a file, but *NOT* display empty files table with "Files you upload will appear here" msg that is inaccurate for rsync uploads
- [ ] Edit Files pg, when you delete a file, Save Change btn is broken
- [ ] Update Replace File pg with new "Replace File" pg title, and hide rsync upload widget because you can not replace dataverse package files (note: must check if Replace option appears in Edit btn dropdown on file pg for package files...)

**Comment by mheppler** [comment] 2018-09-27 18:19
Wanted to add some additional information about the commit above --  "Improved render logic for filesTable on editFilesFragment to only show with empty msg if a file was deleted in the Edit File view".

Once upon a time, the editFilesFragment was made to be an include that could be used on more than once page (7c7e1e0259d426680e9279de997197652932aca6). I believe there may have been some render logic related to authentication in the `filesTable` dataTable that was a remnant and was no longer needed.

`#{(datasetPage or (dataverseSession.user.authenticated and permissionsWrapper.canIssueUpdateDatasetCommand(EditDatafilesPage.dataset)))}`

In the rsync upload does not require this dataTable to be displayed with the `emptyMessage` "Files you upload will appear here." The changes to dual-mode brought that msg back into rsync-only and is also not required in dual mode. So new render logic was added to the table, removing the unnecessary authentication render logic.

`#{!empty EditDatafilesPage.fileMetadatas or !EditDatafilesPage.showFileUploadFragment()}`

This new render logic only displays the dataTable when it is empty when it is the Edit Files workflow and you have deleted the only file displayed in the table, which then displays the proper "There are no selected files to display" as the `emptyMessage`.

Edit Files:

![screen shot 2018-09-27 at 2 18 02 pm](https://user-images.githubusercontent.com/687227/46166035-2d739a80-c260-11e8-8ec0-a3b21b1a6f60.png)

Create Dataset:

![screen shot 2018-09-27 at 2 18 27 pm](https://user-images.githubusercontent.com/687227/46166076-4e3bf000-c260-11e8-8302-572b2f6eb949.png)

**Comment by sekmiller** [comment] 2018-10-05 14:45
With my latest check in you can delete a file in the Edit Metadata workflow. IF the list of files is empty the buttons will not revert to "Done" because you must press "Save Changes" complete the delete. Or "Cancel" if you change your mind. Again.

**Closed** 2018-10-05 16:23 UTC
Labels: Collaboration: SBGrid, Status: QA
