### ISSUE TITLE
Contributor and Curator roles being dropped after dataset is created with files

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#4783] opened 2018-06-25 21:05 UTC
Steps to reproduce:

- create a dataset in root (curator role) or established dataverse (contributor) (journal etc...)
- ADD A FILE
- Click "save dataset" selected
- get "not authorized" message.

Notification is sent successfully to author but it results in same error.I checked each dataset and where author should have been listed as 'contributor'  or "curator" they are not. I added them back manually waiting to see if they can access datasets.

Doesn't seem to be impacting role of "admin."

here is draft dataset I tested in production: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi%3A10.7910%2FDVN%2F6ENH7I&version=DRAFT
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/BJGEMS

If no files added, "curator" can publish and no error.

**Comment by djbrooke** [comment] 2018-06-25 21:37
I was with Sonia as she tested this. Moving into the sprint as a high priority issue.

**Comment by scolapasta** [comment] 2018-06-26 14:34
One observation - I don't think the role ever gets assigned. The user is able to create the dataset because that is checked as a permission on the dataverse.

And then, since they don't have the needed role, they immediately get the Not Authorized page.

**Comment by pdurbin** [comment] 2018-06-27 13:51
We should get whatever fix works into production quickly so I'm fine with the pull request as-is, especially since it sounds like it's been well discussed. Moving to QA.

Over at https://github.com/IQSS/dataverse/pull/4786#issuecomment-400492787 @oscardssmith asked, "Could a test be added to prevent a regression here?" and I thought I'd repeat my reply here:

@oscardssmith it's a great idea to add a test here but in practice our GUI code hasn't lent itself to testing. Maybe we could get a toe hold on this problem by working on #4207 and eventually more complicated tasks like the one above.

Creating a dataset with files at once is a GUI only operation. Perhaps we should create an API for this because currently using the API it's possible to create a dataset and then upload files later. If this new API exists, perhaps the code that's currently exclusively in the GUI could be consolidated into a command.

**Closed** 2018-06-27 20:51 UTC
Labels: Feature: Permissions, Status: QA
