### ISSUE TITLE
Guides URLs are not Consistent

### ISSUE THREAD

**Issue by shlake** [IQSS/dataverse#2832] opened 2015-12-16 20:35 UTC
The Guides URLs are not consistent.

Two of them have - __en/4.2__ and 
two have __en/latest__

Because of the inconsistent URLs, adding a baseURL (GuidesBaseURL) does not work.

Phil says Harvard DV manually symlink "latest" to the version of the docs that's in production.
 
But I don't believe that this is feasible for the rest of us to do it that way.  If we want to change the default Guide locations we would have to use "GuidesBaseURL" and then make sure we have symlinks for our directories?

Rather than fixing this (with consistent URLs), maybe a better solution is in this issue:
 https://github.com/IQSS/dataverse/issues/2831

**Comment by pdurbin** [comment] 2015-12-16 22:13
> The Guides URLs are not consistent.

You can read about the reasoning behind "latest" for Dev and Installation Guides and "4.2" (or whatever versions) for User and API Guides at #2154. In short, we want to direct users (both GUI and API users) to the version they are using. People installing Dataverse should install the latest version. Developers should look at the latest dev guide.

Thanks for opening this issue @shlake as a follow up to https://groups.google.com/d/msg/dataverse-community/pH_XT1NBQyk/D8mfM_jSDQAJ

**Comment by pdurbin** [comment] 2016-01-05 21:34
Today I [noticed](http://irclog.iq.harvard.edu/dataverse/2016-01-05#i_29241) the installation of Dataverse 4 at http://opendata.pku.edu.cn and was reminded of @shlake saying "[We only want the User Guides](https://groups.google.com/d/msg/dataverse-community/pH_XT1NBQyk/D8mfM_jSDQAJ)" which is all PKU seems to want as well:

![peking_university_open_research_data_platform_-_2016-01-05_16 32 43](https://cloud.githubusercontent.com/assets/21006/12128238/f65f0b94-b3c9-11e5-8758-8ad90d0e9481.png)

@pengchengluo did you help with this?

**Comment by pengchengluo** [comment] 2016-01-07 01:12
I also agree with that users only want the user guides. For developers, installation, dev, API guides are necessary and we can lead them to dataverse.org where all of this can be found.

**Comment by pengchengluo** [comment] 2016-01-07 01:13
Hi, @pdurbin and @shlake. I also agree with that users only want the user guides. For developers, installation, dev and API guides are necessary. We can lead them to dataverse.org where all of this can be found.

**Comment by shlake** [comment] 2016-02-08 15:59
Update on the Guide URL problem:

We were running (in test) DV version 4.2 where the guide link for the (user) guide was pointing to:
:GuideBaseUrl/en/4.2/user

Now that we have upgraded our test server to 4.2.3, the URL that the User Guide points to is:
:GuideBaseUrl/en/4.2.3/user
(which means I had to symlink another directory for my guides - or move my guides to the new place)

Please make this link consistent between upgrades so my user guide link will not break the next time. Thanks.

**Comment by pdurbin** [comment] 2016-02-08 18:17
@shlake I understand you're problem but it's not clear to me what change you are proposing. When you upgrade to 4.3 or 4.4 you'll need to create a new symlink or rename the directory that has your custom docs, like you said. We could document this fact if it's helpful. It sounds like you already know what to do. It's a post-upgrade step that people who have written custom docs must do.

**Comment by mheppler** [comment] 2016-10-07 18:15
@shlake -- we are starting to look at feature requests related to customizing Dataverse installations (#2003) and this issue as well as #2831 are features we intend to include.

Can we close this specific issue related to inconsistent URLs, and track your request going forward with just #2831? The two issues are already linked, so comments here can continue to be referenced even if the issue is closed.

**Comment by shlake** [comment] 2016-10-10 15:33
Love to help @mheppler

**Comment by mheppler** [comment] 2016-10-10 15:35
Great! Thank you, @shlake.

**Closed by mheppler** 2016-10-10 15:35 UTC
Labels: Component: Documentation, Type: Suggestion

**Comment by pdurbin** [comment] 2017-03-10 00:34
In a comment at https://github.com/IQSS/dataverse/issues/3637#issuecomment-285533169 I suggested that this issue should be considered when we work on #3637.
