### ISSUE TITLE
Mobile Dataverse: Solution for Displaying Dataverse on a Mobile Device

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1063] opened 2014-11-03 17:16 UTC
Currently with 4.0, the facets look really messed up and aren't usable. We need to figure out a mobile display solution for Dataverse. Perhaps only have the Dataverse, Dataset, File facet and then search.

**Comment by pdurbin** [comment] 2015-04-25 01:01
Over the holiday break I knocked together an Android app at https://github.com/IQSS/dataverse-android but boy is it rough! :)

**Comment by pdurbin** [comment] 2015-09-17 14:48
@mheppler is this a duplicate of #811? You're doing some great work there that benefits mobile devices.

**Comment by mheppler** [comment] 2015-09-17 21:11
Don't think it's a dup. It relates though. So does #2498.

#811 is a higher-level, app-wide ticket, and #2498 outlines specific layout issues currently in the layout. Where as #1063 is focused specifically on designing a specific mobile experience, that differs from the desktop UX. In 4.2, we introduced the facets toggle to the dataverse pg, for smaller browsers, but we should still have this ticket to look into doing more, in respect to the other elements on the page, like description, metrics, contact/share/link/edit action buttons, search, etc.

**Comment by mheppler** [comment] 2020-05-28 16:50
Discussed this issue with @TaniaSchlatter and we agreed that rather than keeping this issue open until a PR comes along to solve out mobile, responsive layout issues across the entire app, that we would instead link it to the **6684 dataset pg btn responsive #6909** pull request and close this.

Going forward, all UI work will go through a responsiveness check, just like it does for accessibility. That will insure no new responsive issues are added to the UI. That effort will also allow us to check for existing layout issues in those same workflows, so that we can make incremental improve to each page as developers work on them.

**Closed** 2020-06-11 17:24 UTC
Labels: Feature: Accessibility, Feature: Code Infrastructure, Status: UX & UI
