### ISSUE TITLE
Terms of Use popup should not pop up when CC0

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1849] opened 2015-04-02 16:00 UTC
Right now if you have a dataset with CC0 and no guet book, you still get a terms of use popup. With CC0 there are no terms to agree to.

**Comment by sekmiller** [comment] 2015-04-02 22:15
We could't recreate this but in testing discovered that TOU wasn't available for editing when CC0 was de-selected.  I fixed that and now you should be able to set custom terms if you de-select CC0.

**Comment by pdurbin** [comment] 2015-04-02 23:54
Ah ha! I see what's going on.

Here is a screenshot of what @mcrosas and I were looking at this morning:

![spruce_goose_-_spruce_dataverse_-_2015-04-02_19 35 21](https://cloud.githubusercontent.com/assets/21006/6975829/88b50dda-d96f-11e4-8031-ce4c3427a89d.png)

This was confusing to us because we were thinking it's not right that we have to accept Terms of Use to download a file from a dataset licensed as CC0.

But this dataset is **not** license as CC0, as @sekmiller pointed out. Confusingly, the Terms of Use was set to "Creative Commons CC-BY 3.0 (unported) http://creativecommons.org/licenses/by/3.0":

![tou](https://cloud.githubusercontent.com/assets/21006/6976032/d3b5d6d2-d971-11e4-8f58-ce94ced62c52.png)


I think I had copied and pasted `<dcterms:rights>Creative Commons CC-BY 3.0 (unported) http://creativecommons.org/licenses/by/3.0/</dcterms:rights>` from the DVN 3.6 example SWORD XML at http://guides.dataverse.org/en/3.6.2/dataverse-api-main.html#create-a-study-with-an-atom-entry-xml-file

So... I think the thing for us to do (and why I'll steal this out of QA) is to update https://github.com/IQSS/dataverse/blob/master/scripts/search/tests/data/dataset-trees1.xml so that it doesn't have a confusing Terms of Use. And the example XML at http://guides.dataverse.org/en/latest/api/sword.html#create-a-dataset-with-an-atom-entry should be updated too. (I'm not sure if we should update the DVN 3.6 example or not.)

@posixeleni or @eaquigley or @mcrosas do you have any suggestions on what example text I should use for Terms of Use for the SWORD XML example?

@eaquigley I worked primarily with you to implement this in https://github.com/IQSS/dataverse/issues/805#issuecomment-71543827 so I guess I'll pass this ticket to you for assistance. Anyone is welcome to jump in though, of course!

@posixeleni I do still plan to review http://guides.dataverse.org/en/latest/api/sword.html#dublin-core-terms-dc-terms-qualified-mapping-dataverse-db-element-crosswalk in #1077. Obviously, we've changed the meaning of `dcterms:rights` in the move from DVN 3.6 to 4.0.

**Comment by posixeleni** [comment] 2015-04-03 13:36
@pdurbin here is a sample Terms of Use you can use that Berkman put together for us for human subject data 

http://best-practices.dataverse.org/harvard-policies/sample-dua.html

**Comment by posixeleni** [comment] 2015-04-03 13:42
confirmed that @sekmiller fix is working in build.

![image](https://cloud.githubusercontent.com/assets/5013837/6982895/8d88e8b0-d9e5-11e4-94e5-f1c1833b52f5.png)

Re-assigning to @pdurbin to modify the documentation per his comment https://github.com/IQSS/dataverse/issues/1849#issuecomment-89084026 and feel free to close this ticket when that's completed.

**Comment by pdurbin** [comment] 2015-04-03 13:44
Thanks @posixeleni ! Maybe I'll use something short like "Downloader will not use the Materials in any way prohibited by applicable laws" in the SWORD XML examples.

**Comment by posixeleni** [comment] 2015-04-03 14:12
@pdurbin works for me... just has to make sense

thanks!

**Comment by pdurbin** [comment] 2015-04-06 12:43
In 0d12045 (in a new branch) I updated the Terms of Use to not be about CC0: "Downloader will not use the Materials in any way prohibited by applicable laws."

@scolapasta I made a pull request for this so you can easily approve and merge it: #1888

**Comment by suenjedt** [comment] 2015-04-07 22:11
The pop up did not appear anymore when having an unrestricted, no guestbook, CC0 file. 
Text change for ToU is visible here, http://guides.dataverse.org/en/latest/api/sword.html#dublin-core-terms-dc-terms-qualified-mapping-dataverse-db-element-crosswalk

**Closed by suenjedt** 2015-04-07 22:11 UTC
Labels: Component: API, Component: Documentation, Component: Metadata, Status: QA
